### PR TITLE
vsock-exporter: switch to tokio runtime

### PR DESCRIPTION
**Pull request by Tim-Zhang**
- Make the vsock-exporter async totally using tokio runtime.
- Delay the timing of the connection to trace-forwarder so that it is easy to reconnect when the connection was broken.

### CODE REVIEW

**Comment by fidencio** [comment]
@Tim-Zhang, would you mind if we merge this **after** the alpha1 release, but before the rc0 one?

**Review by jodh-intel — APPROVED** [review]
Nice. Thanks @Tim-Zhang!

lgtm

**Comment by fidencio** [comment]
Let me close and re-open the PR so we can get the latest static checks running (hopefully!).

**Comment by fidencio** [comment]
I'm adding the `do-not-merge` label till we get `2.2.0-alpha1` release out.
Once we cut the release I'll come back removing the label from the PRs.

**Comment by Tim-Zhang** [comment]
> @Tim-Zhang, would you mind if we merge this **after** the alpha1 release, but before the rc0 one?

OK

**Review by liubin — APPROVED** [review]

**Comment by fidencio** [comment]
I'm really sorry for the disruption we had, but I'm glad to say that 2.2.0-alpha1 release is finally out and we're removing all the `do-not-merge` labels that were added due to this.

Thanks a lot for your understanding and happy hacking!

**Pull request merged**
