### PR TITLE
packaging: fix qemu build on ppc64le

### PR DESCRIPTION
**Pull request by Amulyam24**
Fixes: kata-containers/tests#3993

Signed-off-by: Amulya Meka <amulmek1@in.ibm.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
Thanks @Amulyam24!
I think this one deserves a backport, or was this only exposed on latest QEMU?

**Comment by Amulyam24** [comment]
@fidencio, I encountered this with the latest qemu only.

**Review by cmaf — COMMENTED** [review]
@Amulyam24 could you add a commit message describing the PR? [Guidelines](https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#closing-issues)

You might also need an issue in the kata-containers/kata-containers repo in order to pass the static checks.

**Comment by Amulyam24** [comment]
@cmaf , updated with changes.

**Review by cmaf — APPROVED** [review]

**Pull request merged**
