### PR TITLE
[backport] kata-monitor: cache improvements

### PR DESCRIPTION
**Pull request by fgiudici**
Backport of https://github.com/kata-containers/kata-containers/pull/2566 and https://github.com/kata-containers/kata-containers/pull/2739

### CODE REVIEW

**Review by c3d — APPROVED** [review]
lgtm

**Comment by fgiudici** [comment]
I think we are ready to merge this into stable 2.2.x.
@marcel-apf , @liubin ,  @fidencio, opinions?

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
