### PR TITLE
[forward port]: osbuilder: Update yq

### LINKED ISSUE #576: [forward port]: scripts: Update yq
Port https://github.com/kata-containers/osbuilder/pull/454 (issue https://github.com/kata-containers/osbuilder/issues/421) from Kata 1.x.

### PR DESCRIPTION
**Pull request by GabyCT**
This PR ports kata-containers/osbuilder#454 to kata 2.0

Fixes #576

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @GabyCT ! I think you get the prize for the first person to raise one of these PRs! :trophy: :smile:

**Review by fidencio — COMMENTED** [review]
@GabyCT, in the code there are a bunch of mentions to the go agent.
Considering this is not supported, wouldn't be good to just drop those mentions entirely?

**Review by fidencio — APPROVED** [review]
@GabyCT, thanks for the very quick action on this one!

lgtm!

**Comment by GabyCT** [comment]
@fidencio yes, thanks for the comment, I worked on that :)

**Pull request merged**
