### PR TITLE
virtcontainers: Use available s390x hugepages

### PR DESCRIPTION
**Pull request by Jakob-Naucke**
in TestHandleHugepages. On s390x, hugepage sizes must be set at boot, so
test with any that are present (default is 1M).

Fixes: #3763
Signed-off-by: Jakob Naucke <jakob.naucke@ibm.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
@Jakob-Naucke I just triggered the s390x CI to test this commit

**Comment by Jakob-Naucke** [comment]
depends on #3770, /debug-s390x

**Comment by Jakob-Naucke** [comment]
It appears those changes are not pulled in with the debug job:
```
=== RUN   TestHandleHugepages
    kata_agent_test.go:1259: 
        	Error Trace:	kata_agent_test.go:1259
        	Error:      	Received unexpected error:
        	            	invalid argument
        	Test:       	TestHandleHugepages
        	Messages:   	Unable to mount /tmp/hugepages-test1287894312/hugepages-1Gi
```

(look at the line numbers)
In the meantime, I can tell you that this Works On My Machine(tm) and suggest we merge it even with the s390x CI failing…
/test

**Review by fidencio — APPROVED** [review]
lgtm, thanks @Jakob-Naucke!

**Comment by fidencio** [comment]
> and suggest we merge it even with the s390x CI failing…

This makes sense as s390x is not currently running on all PRs.

**Review by fgiudici — APPROVED** [review]
lgtm

**Pull request merged**
