### PR TITLE
runtime: Add podman and containerd shim v2 to data collection script

### PR DESCRIPTION
**Pull request by jodh-intel**
Updated `kata-collect-data.sh` to gather basic podman details and containerd shim v2 logs.

Also fixed a minor legacy package bug, ksm throttler log collection issue and whitespace and ordering issues.

Fixes: #243.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by tedyu** [comment]
lgtm

**Comment by jodh-intel** [comment]
Ping @kata-containers/kata-containers - this should have landed days ago folks...

**Comment by jodh-intel** [comment]
grrr....

/test

**Comment by jodh-intel** [comment]
Ping y'all - one more ack needed on this important fix...

**Comment by jodh-intel** [comment]
Thanks @fidencio.

**Pull request merged**
