### PR TITLE
snap: Use helper script and cleanup

### PR DESCRIPTION
**Pull request by jodh-intel**
Move the common shell code to a helper script that is sourced by all
parts.

Add extra quoting to some variables in the snap config file
and simplify.

Fixes: #4304.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jodh-intel!

**Review by cmaf — APPROVED** [review]
thanks @jodh-intel

**Comment by jodh-intel** [comment]
Note the new "[snap: Fix CH architecture check](https://github.com/kata-containers/kata-containers/pull/4322/commits/d759f6c3e5e3324136d34c087068dcf88abd6cde)" commit. That one line fix means that Cloud Hypervisor is now actually packaged for x86_64 and aarch64 :smile:

**Comment by jongwu** [comment]
> @jongwu - can you offer any insight into missing `make` on ARM issue above ([#4322 (comment)](https://github.com/kata-containers/kata-containers/pull/4322#issuecomment-1143764511))?

No worries, I just reinstall OS for this CI machine.

**Pull request merged**
