### PR TITLE
Entropy source annotation

### PR DESCRIPTION
**Pull request by c3d**
It would be undesirable to be given an annotation like "/dev/null".
Filter out bad annotation values.
    
Fixes: #1043
    
Suggested-by: James O. D. Hunt <james.o.hunt@intel.com>
Signed-off-by: Christophe de Dinechin <dinechin@redhat.com>

This is based on commits for #1048 and #1045 so as to minimize the diffs.

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Nice! Thanks @c3d.

lgtm

**Review by devimc — APPROVED** [review]
thanks @c3d

**Comment by bergwolf** [comment]
@c3d Need rebase

**Comment by fidencio** [comment]
I'm really sorry for the disruption but in order to do the branch name changes announced [here](http://lists.katacontainers.io/pipermail/kata-dev/2021-January/001695.html) I'm adding the "do-not-merge" and the "needs-branch-adjustment" labels to the PR.

I'll add a new comment once the branch changes are done and once it happens I'd like to ask you to resubmit the PR against the new `main` branch, possibly linking to this PR in case you find the conversations / reviews already made important to proceed.

**Comment by fidencio** [comment]
Kata Containers repos are back to business.  Thanks a lot for your patience and I'm very happy to announce that there's no changes needed from your side as renaming the branches automagically reflected here.

If you notice something weird, some missing CI, please, do not hesitate on contacting us here or on #kata-dev on bit.ly/katacontainersslack.

Also, this is a good opportunity to have your PR rebased atop of `main`, to ensure your PR follow all the guidelines (https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format) enforced by this community, or even to re-evaluate whether the PR is currently needed.

Last but not least,  as the default branch has been renamed to `main`, if you have a local clone you'd need to update it and you do so by running:
```
git branch -m 2.0-dev main
git fetch origin
git branch -u origin/main main
```

Happy hacking!

**Comment by jodh-intel** [comment]
Hi @c3d - another confliced branch I'm afraid.

**Comment by fidencio** [comment]
@c3d, please, rebase atop of current `main` and we can proceed with this one.

**Comment by cmaf** [comment]
@c3d another rebase reminder :)

**Comment by c3d** [comment]
The entropy source tests needed to be updated now that there is a framework to deal with protected annotations.

**Pull request merged**
