### PR TITLE
# Kata Containers 2.4.2

### PR DESCRIPTION
**Pull request by snir911**
- My 2.4 pr backport -- fix shim leak caused by ESRCH in agent destroy
- backport-2.4 | workflows: add workflow_dispatch triggering to test-kata-deploy
- stable-2.4: runtime: Adding the correct detection of mediated PCIe devices
- stable-2.4: backport agent fixes
- stable-2.4 | clh: Update to the v24.0 release
- stable-2.4 | Backport fixes for direct-volume stats
- stable-2.4 | tools: Add QEMU patches for SGX numa support
- stable-2.4 | versions: Upgrade to Cloud Hypervisor v23.1

607a8a9c2 release: Adapt kata-deploy for 2.4.2
e5568a31a agent: ignore ESRCH error when destroying containers
322839ac7 runtime: force stop container after the container process exits
b75d5cee7 docs: update release process github token instructions
e938ce443 docs: update release process with latest workflow triggering
046ba4df7 workflows: add workflow_dispatch triggering to test-kata-deploy
14ce4b01b runtime: Adding the correct detection of mediated PCIe devices
f54d5cf16 agent: Fix is_signal_handled failing parsing str to u64
80d5f9e14 agent: move assert_result macro to test_utils file
50a74dfee agent: add tests for is_signal_handled function
560247f8d agent: add tests for update_container_namespaces
47d4e79c1 agent: add tests for do_write_stream function
e3ce8aff9 agent: add tests for get_memory_info function
ebe9fc2ca clh: Update to the v24.0 release
29c9391da agent: fix direct-assigned volume stats
d1848523d runtime: direct-volume stats use correct name
338c9f2b0 runtime: direct-volume stats update to use GET parameter
f528bc010 runtime: fix incorrect Action function for direct-volume stats
3413c8588 tools: Add QEMU patches for SGX numa support
db6d4f7e1 versions: Upgrade to Cloud Hypervisor v23.1

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @snir911!

**Comment by fengwang666** [comment]
@snir911 Can you include this one https://github.com/kata-containers/kata-containers/pull/4389?

**Comment by snir911** [comment]
Yes, I'll add it, also waiting for #4388 (if acked) that allows to run test-kata-deploy workflow on this PR

**Review by amshinde — APPROVED** [review]

**Comment by snir911** [comment]
`test-kata-deploy` will fail here as it will try to run the workflow which is defined on the default branch (main) although this PR was raised against stable branch (viriofsd asset available only for main, hence workflow will fail on stable), see https://github.com/kata-containers/kata-containers/issues/4349 .
We should be able to test-kata-deploy correctly once https://github.com/kata-containers/kata-containers/pull/4387 and https://github.com/kata-containers/kata-containers/pull/4388 are merged, however, ATM I'll suggest to continue with the release as although test-kata-deploy fails, kata-deploy-push is expected to pass (as it should run correctly against stable because the triggering event in this case does point to the correct branch)

**Pull request merged**
