### PR TITLE
CC | runtime: Revendor containerd to v1.6.8

### PR DESCRIPTION
**Pull request by fidencio**
As we bumped containerd dependency to v1.6.8, let's also do the re-vendor of its code on the runtime side.

Fixes: #5745

Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
LGTM - thanks!

**Review by GabyCT — APPROVED** [review]

**Comment by BbolroC** [comment]
Please ignore the test result for s390x.

**Pull request merged**
