### PR TITLE
src: reorg source code directory

### PR DESCRIPTION
**Pull request by bergwolf**
To make the code directory structure more clear:
```
└── src
    ├── agent
    ├── libs
    │   └── logging
    ├── runtime
    ├── runtime-rs (to be added)
    └── tools
        ├── agent-ctl
        └── trace-forwarder
```

Fixes: #3204

### CODE REVIEW

**Review by liubin — APPROVED** [review]

**Comment by fidencio** [comment]
@bergwolf, please, squash this minor one into your PR:
```
[ffidenci@ffidenci-desk kata-containers]$ git diff HEAD~1
diff --git a/src/tools/agent-ctl/.gitignore b/src/tools/agent-ctl/.gitignore
new file mode 100644
index 000000000..48b8bf907
--- /dev/null
+++ b/src/tools/agent-ctl/.gitignore
@@ -0,0 +1 @@
+vendor/
diff --git a/src/tools/trace-forwarder/.gitignore b/src/tools/trace-forwarder/.gitignore
new file mode 100644
index 000000000..48b8bf907
--- /dev/null
+++ b/src/tools/trace-forwarder/.gitignore
@@ -0,0 +1 @@
+vendor/
```

The reason for that is to avoid having the results of `make vendor` being added by mistake into a commit.

**Comment by fidencio** [comment]
Apart from the minor, LGTM.  I'd like to have @jodh-intel's approval on this one before having it merged, though.

**Review by egernst — APPROVED** [review]
sgtm

**Review by jodh-intel — APPROVED** [review]
Nice work @bergwolf !

lgtm

**Comment by liubin** [comment]
@jodh-intel I think it needs you to remove the `do-not-merge` label.

**Review by fidencio — APPROVED** [review]
Yay! :-)

**Pull request merged**
