### PR TITLE
versions: Update kernel to latest LTS version 5.15.48

### LINKED ISSUE #4438: Update kernel to latest LTS 5.15.46

### PR DESCRIPTION
**Pull request by amshinde**
This brings in a few security fixes.

Fixes #4438

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by fidencio** [comment]
I am closing and re-opening this one to re-trigger the tests.

**Comment by fidencio** [comment]
@amshinde, patches are not cleanly applying.

**Comment by amshinde** [comment]
@fidencio ok, let me take a look.

**Comment by amshinde** [comment]
@jongwu Please take a look at this. I have removed a couple of patches specific to arm that were no longer applying cleanly in this LTS update.
I checked upstream for the patches. Seems like `0007-virtio-mem-enable-virtio-mem-on-arm64.patch`  has been merged upstream but with the commit message of the other patch `0006-arm64-mm-avoid-fixmap-race-condition-when-create-pud.patch`. 
So wanted to check with you if it is ok to remove both the patches. 

On a side note, was wondering why these patches are even applied on this tree when there exists a separate arm-experimental tag in our versions.yaml file.

**Comment by jongwu** [comment]
> @jongwu Please take a look at this. I have removed a couple of patches specific to arm that were no longer applying cleanly in this LTS update. I checked upstream for the patches. Seems like `0007-virtio-mem-enable-virtio-mem-on-arm64.patch` has been merged upstream but with the commit message of the other patch `0006-arm64-mm-avoid-fixmap-race-condition-when-create-pud.patch`. So wanted to check with you if it is ok to remove both the patches.
> 
> On a side note, was wondering why these patches are even applied on this tree when there exists a separate arm-experimental tag in our versions.yaml file.

Hello @amshinde -, pls do not remove these patches under arm-expremental/ which is specific for arm experimental use and will not impact other arches.

**Comment by amshinde** [comment]
@fidencio @jongwu @jodh-intel @GabyCT Can you take a look?
Earlier patches were not being cleanly applied, as I saw one of them was already merged in this kernel version. But was wondering why the arm-experimental patches were being applied to our main default kernel. 
This looked to me as a bug. We havent seen it earlier as our default and experimental kernels were on a different major version. I have included a fix for this. Please take a look.

**Review by GabyCT — APPROVED** [review]

**Comment by jongwu** [comment]
Thanks @amshinde -, it seems a bug for kernel build script. We really should find the patches on the top level destination dir, so the patches under arm-experimental/ should not applied.

nit: The virtio-mem related patches for arm is merged into main stream in 5.17 not 5.15.

**Review by jongwu — APPROVED** [review]

**Comment by amshinde** [comment]
@jongwu Your 0007-virtio-mem-enable...patch has been backported to in 5.15.48. Have a look: https://elixir.bootlin.com/linux/v5.15.48/source/arch/arm64/mm/mmu.c#L66

**Comment by jongwu** [comment]
> @jongwu Your 0007-virtio-mem-enable...patch has been backported to in 5.15.48. Have a look: https://elixir.bootlin.com/linux/v5.15.48/source/arch/arm64/mm/mmu.c#L66

Exactly! Thanks @amshinde

**Review by jodh-intel — APPROVED** [review]
Thanks @amshinde.

lgtm

**Review by fidencio — APPROVED** [review]
lgtm, thanks @amshinde!

**Pull request merged**
