### PR TITLE
network: Fix network hotplug for ipvlan and macvlan endpoints for qemu and add tests

### PR DESCRIPTION
**Pull request by amshinde**
network: Fix network hotplug for ipvlan and macvlan endpoints.
Since moving from network coldplug to hotplug, the only case verified
was veth endpoints. Support for network hotplug for ipvlan and macvlan was
broken/not added. Fix it.

Fixes: https://github.com/kata-containers/kata-containers/issues/8391

Add test to verify kata supports ipvlan networks.
This test can be bit tricky as it requires knowledge about host interfaces to be used as a master for the ipvlan network.
However, with github actions, we can assume interface called eth0 to be present on the host(VM) and functioning.

Fixes: #8366

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @amshinde!

I'd suggest backporting this one to the stable-3.2 branch as well.

**Review by jodh-intel — APPROVED** [review]
Thanks @amshinde.

lgtm

**Comment by amshinde** [comment]
> I'd suggest backporting this one to the stable-3.2 branch as well.

Will do, looks like ipvlan support broke with the last refactoring done on the code for qemu. I'll push a fix for it in this PR and backport that as well.

**Comment by amshinde** [comment]
@fidencio I have added a small fix for fixing qemu network hoplug for the test to pass for all hypervisors. I think you reviewed the PR prior to the fix. Can you take another look?

**Pull request merged**
