### PR TITLE
kata-deploy: fix version bump from -rc to stable

### PR DESCRIPTION
**Pull request by bergwolf**
In such a case, we should bump from the "latest" tag rather than from
current_version.

Fixes: #3986

### CODE REVIEW

**Review by egernst — DISMISSED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @bergwolf1

**Review by snir911 — APPROVED** [review]
LGTM, thanks, FWIW AFAIU it's not tested by /test_kata_deploy

**Comment by bergwolf** [comment]
@snir911 
> FWIW AFAIU it's not tested by /test_kata_deploy

I did trigger `/test_kata_deploy`. Do you mean the comment command does not work?

**Comment by snir911** [comment]
@bergwolf it should be with underscore IIRC but i think the update-repository-version.sh script will not be tested by it

**Pull request merged**
