### PR TITLE
merge documentation and packaging repository

### PR DESCRIPTION
**Pull request by bergwolf**
As part of the repository consolidation process, we want to move documentation and packaging to the kata-containers repository as well.

Generated by
```
git subtree add --prefix=docs git@github.com:kata-containers/documentation.git master
    git-subtree-dir: docs
    git-subtree-mainline: ec146a1b39ea86e98eee0c802ccde57542202339
    git-subtree-split: 510287204b32a9b515a9491f338d3bffc0668774

git subtree add --prefix=tools/packaging git@github.com:kata-containers/packaging.git master
    git-subtree-dir: tools/packaging
    git-subtree-mainline: f818b46a418fc80a4f0031a71ae3e43a59e959fd
    git-subtree-split: 1f22d72d5d1bd80b252c02bba5b53f329c89addb
```

### CODE REVIEW

**Comment by bergwolf** [comment]
`SOB` failure is expected as the imported code has a lot of merge commits that do not carry a SOB line in it.

**Comment by bergwolf** [comment]
ubuntu CI cannot handle this because it tries to rebase on top of `2.0-dev` and failed with
```
Checking out to PR_330 branch
Switched to branch 'PR_330'
... and rebasing with origin/2.0-dev
First, rewinding head to replay your work on top of it...
Applying: Initial commit
Using index info to reconstruct a base tree...
Falling back to patching base and 3-way merge...
Auto-merging README.md
CONFLICT (add/add): Merge conflict in README.md
error: Failed to merge in the changes.
Patch failed at 0001 Initial commit
Use 'git am --show-current-patch' to see the failed patch
```

**Comment by bergwolf** [comment]
@chavafg Any reason why we always do a rebase after checking out? If we want to make sure there is no merge conflicts, we can merge the two branches.

**Comment by bergwolf** [comment]
Looks like `Depends-on` is not working...
I have 
```
Depends-on: github.com/kata-containers/tests#2674
```
that changes `rebase` to `merge`, but CI is still using `rebase`:
```
Checking out to PR_330 branch
Switched to branch 'PR_330'
... and rebasing with origin/2.0-dev
First, rewinding head to replay your work on top of it...
Applying: Initial commit
Using index info to reconstruct a base tree...
Falling back to patching base and 3-way merge...
Auto-merging README.md
CONFLICT (add/add): Merge conflict in README.md
error: Failed to merge in the changes.
```
```

**Comment by bergwolf** [comment]
CI is failing to handle `Depends-on` tags as there are a lot of them and should be ignored.

```
This PR depends on repository: github.com/kata-containers/tests/pull/2334 and pull request: github.com/kata-containers/tests/pull/2334
# cd /tmp/jenkins/workspace/kata-containers-2.0-ubuntu-PR/go/src/github.com/kata-containers/tests; git pull --ff-only
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> p2240

package github.com/kata-containers/tests/pull/2334: exit status 1
/tmp/jenkins/workspace/kata-containers-2.0-ubuntu-PR/go/src/github.com/kata-containers/tests/.ci/resolve-kata-dependencies.sh: line 54: pushd: /tmp/jenkins/workspace/kata-containers-2.0-ubuntu-PR/go/src/github.com/kata-containers/tests/pull/2334: No such file or directory
```

**Comment by chavafg** [comment]
should we just ignore jenkins CI and force-merge? I don't think there are any breakages as this is only merging the repos.

**Comment by bergwolf** [comment]
@chavafg sounds good to me. What do others think? This is a one time thing and we'll have to force merge regardlessly because of the SOB check failure.

**Comment by jodh-intel** [comment]
+1 from me. Looks like you'll have to disable the checks on the repo temporarily to actually do the merge though.

**Comment by chavafg** [comment]
ok, so with this other ack, I'll proceed to merge

**Pull request merged**
