### PR TITLE
dragonball: enable kata3.0/dragonball CI on Arm

### PR DESCRIPTION
**Pull request by jongwu**
kernel boot on dragonball is too slow for the rng init on Arm. We can enable random_trust_cpu to speed up rng init. After that, we can enable dragonball CI on Arm.

### CODE REVIEW

**Comment by jongwu** [comment]
Help TAL @fidencio @studychao

**Comment by xuejun-xj** [comment]
LGTM

**Review by xuejun-xj — APPROVED** [review]
LGTM

**Review by studychao — APPROVED** [review]
Thanks @jongwu

**Comment by studychao** [comment]
OOI, did you add the `
jenkins-ci-dragonball-ARM-ubuntu-20.04` test? @jongwu

**Comment by jongwu** [comment]
@studychao -, Yes, and the dragonball test on Arm has passed. see http://jenkins.katacontainers.io/job/kata-containers-dragonball-ubuntu-Arm-20.04-PR/12/console

**Comment by studychao** [comment]
Thanks @jongwu :)
LGTM, and @fidencio please take a look at this.

**Review by liubin — APPROVED** [review]

**Pull request merged**
