### PR TITLE
agent: Pass standard I/O to container launched by runk

### PR DESCRIPTION
**Pull request by ManaSugi**
The `kata-agent` passes its standard I/O file descriptors
through to the container process that will be launched
by `runk` without manipulation or modification in order to
allow the container process can handle its I/O operations.

Fixes: #4327

Signed-off-by: Manabu Sugimoto <Manabu.Sugimoto@sony.com>

### CODE REVIEW

**Review by liubin — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Thanks @ManaSugi. Is there any way you could add a unit test for these scenarios?

**Comment by jodh-intel** [comment]
ok, thanks @ManaSugi. I've added the dnm label for this PR. Once we've landed #4353, we can land this one.

**Pull request merged**
