### PR TITLE
Don't update cpusets if no CPUs changed closes #1172

### LINKED ISSUE #1172: Agent: No need to update cpuset for containers if no CPU changes
In  `online_cpu_memory` function of `sandbox.rs`, the updating containers' `cpuset` will always run whether there is CPU changes or not.

### PR DESCRIPTION
**Pull request by maruthgoyal**

### CODE REVIEW

**Comment by egernst** [comment]
Hey @maruthgoyal - thanks for grabbing this issue and making a PR!

Our travis/ci check enforced some git formatting conventions: PTAL @ https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#general-format

You can probably squash your commits as well.  As for the actual changes..... let me take a look now :)

**Review by egernst — COMMENTED** [review]
This looks good to me, but also wonder if it would make sense to have unit tests for the cpuset management. With that in mind, it may be easier if the cpuset updating is handled in a separate function with a unit test.

Not a strong requirement, but I'm just trying to assess where we can add more unit tests.

@liubin  WDYT?

**Comment by liubin** [comment]
Yes, I agree with @egernst that more test will make changes of code more safer. To let code testable, we should refactor it to let it more mock-oriented for some system(OS level operation), though it's a hard job.

**Comment by Tim-Zhang** [comment]
@maruthgoyal Thanks,  you'd better squash these 3 commits to 1.

**Comment by maruthgoyal** [comment]
Apologies for the delay just squashed the commits and fixed the commit message to pass the check.

**Review by liubin — APPROVED** [review]

**Review by Tim-Zhang — APPROVED** [review]
lgtm, thanks

**Pull request merged**
