### PR TITLE
agent: Remove dynamic tracing APIs

### PR DESCRIPTION
**Pull request by jodh-intel**
Remove the `StartTracing` and `StopTracing` agent APIs that toggle
dynamic tracing. This is not supported in Kata 2.x, as documented in the
[tracing proposals document](https://github.com/kata-containers/kata-containers/pull/2062).

Fixes: #2985.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jodh-intel!

**Comment by cmaf** [comment]
Failed static checks:
```
INFO: Spell checking file 'docs/design/kata-2-0-metrics.md'
WARNING: Word 'Vsock': did you mean one of the following?: Sock, V sock
ERROR: Spell check failed for file: 'docs/design/kata-2-0-metrics.md'
[static-checks.sh:825] INFO: spell check failed for document docs/design/kata-2-0-metrics.md
[static-checks.sh:828] ERROR: spell check failed, See https://github.com/kata-containers/kata-containers/blob/main/docs/Documentation-Requirements.md#spelling for more information.
make: *** [Makefile:40: static-checks] Error 1
```

**Review by cmaf — APPROVED** [review]

**Comment by jodh-intel** [comment]
Hmm, the debian CI is failing in an odd fashion:

```
sudo: kubeadm: command not found
[init.sh:153] ERROR: sudo -E kubeadm init --config /tmp/kubeadm_config.yjjke5.yaml
[run_kubernetes_tests.sh:66] ERROR: ./init.sh
sudo: kubeadm: command not found
[cleanup_env.sh:28] ERROR: sudo -E kubeadm reset -f --cri-socket=/var/run/crio/crio.sock
make: *** [Makefile:117: kubernetes] Error 1
```

/cc @GabyCT

**Comment by Jakob-Naucke** [comment]
See https://github.com/kata-containers/tests/issues/4168 for Debian

**Comment by Jakob-Naucke** [comment]
and #2987 for s390x -- /retest-s390x

**Comment by GabyCT** [comment]
> Hmm, the debian CI is failing in an odd fashion:
> 
> ```
> sudo: kubeadm: command not found
> [init.sh:153] ERROR: sudo -E kubeadm init --config /tmp/kubeadm_config.yjjke5.yaml
> [run_kubernetes_tests.sh:66] ERROR: ./init.sh
> sudo: kubeadm: command not found
> [cleanup_env.sh:28] ERROR: sudo -E kubeadm reset -f --cri-socket=/var/run/crio/crio.sock
> make: *** [Makefile:117: kubernetes] Error 1
> ```
> 
> /cc @GabyCT

not sure what is happening @jodh-intel , I am not a maintainer of the debian CI

**Comment by jodh-intel** [comment]
@GabyCT - looks like we don't have one yet: https://github.com/kata-containers/ci/issues/403.

/cc @zhsj in case you are interested in becoming more involved with the Kata project and have a few free cycles?

**Comment by zhsj** [comment]
> @GabyCT - looks like we don't have one yet: [kata-containers/ci#403](https://github.com/kata-containers/ci/issues/403).
> 
> /cc @zhsj in case you are interested in becoming more involved with the Kata project and have a few free cycles?

Thanks for mention. However I'm quite busy with my day job, which is not debian or kata related :crying_cat_face:

**Comment by jodh-intel** [comment]
@zhsj - no problem! If you do hear of any other DDs or DMs that might be interested, please do let us know.

**Pull request merged**
