### PR TITLE
runtime: Update containerd to 1.5.8

### PR DESCRIPTION
**Pull request by c3d**
Release 1.5.8 of containerd contains fixes for two low-severity advisories:

[GHSA-5j5w-g665-5m35](https://github.com/opencontainers/distribution-spec/security/advisories/GHSA-mc8v-mgrf-8f4m)
[GHSA-77vh-xpmg-72qh](https://github.com/opencontainers/image-spec/security/advisories/GHSA-77vh-xpmg-72qh)

Fixes: #3074

Signed-off-by: Christophe de Dinechin <dinechin@redhat.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @c3d!

On a side note, we need to start ensuring we take more advantage of dependabot and let the bot do the work for us.  I will open an issue for that so we don't have to spend human power for this kind of PRs.

**Comment by fidencio** [comment]
> On a side note, we need to start ensuring we take more advantage of dependabot and let the bot do the work for us. I will open an issue for that so we don't have to spend human power for this kind of PRs.

https://github.com/kata-containers/kata-containers/issues/3077

**Review by gkurz — APPROVED** [review]
LGTM. Thanks @c3d !

**Pull request merged**
