### PR TITLE
fix govet fieldalignment

### LINKED ISSUE #2271: structures are misaligned
govet fieldalignment is failing because some structures are misaligned, see https://github.com/kata-containers/tests/pull/3727

### PR DESCRIPTION
**Pull request by devimc**
Fix structures alignment

fixes #2271

Depends-on: github.com/kata-containers/tests#3727

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks for doing this painful work @devimc !

lgtm

**Comment by fidencio** [comment]
Note to self, we also need to revert https://github.com/kata-containers/tests/commit/b4fee25e1f66a307084647844df9fabb1b227cef

**Review by amshinde — APPROVED** [review]

**Review by GabyCT — APPROVED** [review]

**Comment by fidencio** [comment]
@devimc, while testing it locally I am still hitting warnings in the following places in the virtcontainers:
```
container.go:241:22: fieldalignment: struct with 400 pointer bytes could be 392 (govet)
type ContainerConfig struct {
                     ^
fc.go:142:18: fieldalignment: struct of size 1040 could be 1032 (govet)
type firecracker struct {
                 ^
kata_agent.go:236:16: fieldalignment: struct with 80 pointer bytes could be 72 (govet)
type kataAgent struct {
               ^
monitor.go:21:14: fieldalignment: struct of size 80 could be 72 (govet)
type monitor struct {
             ^
sandbox.go:73:20: fieldalignment: struct with 880 pointer bytes could be 776 (govet)
type SandboxStatus struct {
                   ^
sandbox.go:93:20: fieldalignment: struct with 1056 pointer bytes could be 936 (govet)
type SandboxConfig struct {
                   ^
sandbox.go:163:14: fieldalignment: struct with 336 pointer bytes could be 280 (govet)
type Sandbox struct {
             ^
```

And then on those places which are part of the virtcontainers/device/config:
```
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/device/config
config.go:96:17: fieldalignment: struct with 104 pointer bytes could be 64 (govet)
type DeviceInfo struct {
                ^
config.go:144:17: fieldalignment: struct with 152 pointer bytes could be 136 (govet)
type BlockDrive struct {
                ^
config.go:202:14: fieldalignment: struct with 112 pointer bytes could be 104 (govet)
type VFIODev struct {
             ^
config.go:240:27: fieldalignment: struct with 112 pointer bytes could be 104 (govet)
type VhostUserDeviceAttrs struct {
                          ^
```

And this one in virtcontainers/device/drivers:
```
generic.go:19:20: fieldalignment: struct with 24 pointer bytes could be 16 (govet)
type GenericDevice struct {
            ^
```

And yet another one in virtcontainers/device/manager
```
manager.go:50:20: fieldalignment: struct with 48 pointer bytes could be 32 (govet)
type deviceManager struct {
            ^
```

And one more at virtcontainers/factory
```
factory.go:34:13: fieldalignment: struct with 784 pointer bytes could be 768 (govet)
type Config struct {
            ^
```

And it goes ... virtcontainers/factory/cache
```
cache.go:19:12: fieldalignment: struct with 64 pointer bytes could be 40 (govet)
type cache struct {
           ^
```

... and goes ... virtcontainers/persist/api
```
config.go:15:23: fieldalignment: struct with 624 pointer bytes could be 536 (govet)
type HypervisorConfig struct {
                      ^
config.go:240:22: fieldalignment: struct with 144 pointer bytes could be 136 (govet)
type ContainerConfig struct {
                     ^
config.go:250:20: fieldalignment: struct with 800 pointer bytes could be 760 (govet)
type SandboxConfig struct {
                   ^
container.go:37:12: fieldalignment: struct with 104 pointer bytes could be 88 (govet)
type Mount struct {
           ^
container.go:71:14: fieldalignment: struct with 48 pointer bytes could be 32 (govet)
type Process struct {
             ^
container.go:88:21: fieldalignment: struct with 168 pointer bytes could be 160 (govet)
type ContainerState struct {
                    ^
device.go:15:17: fieldalignment: struct with 152 pointer bytes could be 136 (govet)
type BlockDrive struct {
                ^
device.go:53:14: fieldalignment: struct with 48 pointer bytes could be 40 (govet)
type VFIODev struct {
             ^
device.go:87:18: fieldalignment: struct with 136 pointer bytes could be 80 (govet)
type DeviceState struct {
                 ^
hypervisor.go:29:22: fieldalignment: struct with 136 pointer bytes could be 88 (govet)
type HypervisorState struct {
                     ^
network.go:83:22: fieldalignment: struct with 80 pointer bytes could be 72 (govet)
type NetworkEndpoint struct {
                     ^
network.go:98:18: fieldalignment: struct with 40 pointer bytes could be 24 (govet)
type NetworkInfo struct {
                 ^
sandbox.go:19:19: fieldalignment: struct with 1112 pointer bytes could be 1080 (govet)
type SandboxState struct {
                  ^
```

... and goes.  At this point I stopped decorating the code with `//nolint: govet` ...

**Comment by fidencio** [comment]
By the way, @devimc, thanks for doing the work the compiler should do.

**Comment by devimc** [comment]
@fidencio thanks, just realized that I updated my local tests repository and govet is disable :sweat:

**Comment by fidencio** [comment]
> @fidencio thanks, just realized that I updated my local tests repository and govet is disable

Yep, sorry about that.  I ended up disabling it in order to avoid doing the work you're doing. /o\.

**Comment by devimc** [comment]
@fidencio updated, thanks

**Review by fidencio — APPROVED** [review]
I've tested this one locally, and now it passes!
```
INFO: Running golangci-lint checks on the following packages:

github.com/kata-containers/kata-containers/src/runtime/cli github.com/kata-containers/kata-containers/src/runtime/cli/containerd-shim-kata-v2 github.com/kata-containers/kata-containers/src/runtime/cli/kata-monitor github.com/kata-containers/kata-containers/src/runtime/containerd-shim-v2 github.com/kata-containers/kata-containers/src/runtime/netmon github.com/kata-containers/kata-containers/src/runtime/pkg/kata-monitor github.com/kata-containers/kata-containers/src/runtime/pkg/katatestutils github.com/kata-containers/kata-containers/src/runtime/pkg/katautils github.com/kata-containers/kata-containers/src/runtime/pkg/katautils/katatrace github.com/kata-containers/kata-containers/src/runtime/pkg/signals github.com/kata-containers/kata-containers/src/runtime/pkg/types github.com/kata-containers/kata-containers/src/runtime/pkg/utils github.com/kata-containers/kata-containers/src/runtime/protocols/cache github.com/kata-containers/kata-containers/src/runtime/virtcontainers github.com/kata-containers/kata-containers/src/runtime/virtcontainers/device/api github.com/kata-containers/kata-containers/src/runtime/virtcontainers/device/config github.com/kata-containers/kata-containers/src/runtime/virtcontainers/device/drivers github.com/kata-containers/kata-containers/src/runtime/virtcontainers/device/manager github.com/kata-containers/kata-containers/src/runtime/virtcontainers/experimental github.com/kata-containers/kata-containers/src/runtime/virtcontainers/factory github.com/kata-containers/kata-containers/src/runtime/virtcontainers/factory/base github.com/kata-containers/kata-containers/src/runtime/virtcontainers/factory/cache github.com/kata-containers/kata-containers/src/runtime/virtcontainers/factory/direct github.com/kata-containers/kata-containers/src/runtime/virtcontainers/factory/grpccache github.com/kata-containers/kata-containers/src/runtime/virtcontainers/factory/template github.com/kata-containers/kata-containers/src/runtime/virtcontainers/hook/mock github.com/kata-containers/kata-containers/src/runtime/virtcontainers/persist github.com/kata-containers/kata-containers/src/runtime/virtcontainers/persist/api github.com/kata-containers/kata-containers/src/runtime/virtcontainers/persist/fs github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/agent/protocols github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/agent/protocols/client github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/agent/protocols/grpc github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/annotations github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/annotations/dockershim github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/cgroups github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/compatoci github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/cpuset github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/firecracker/client github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/firecracker/client/models github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/firecracker/client/operations github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/mock github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/nsenter github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/oci github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/rootless github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/types github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/uuid github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/vcmock github.com/kata-containers/kata-containers/src/runtime/virtcontainers/types github.com/kata-containers/kata-containers/src/runtime/virtcontainers/utils github.com/kata-containers/kata-containers/tools/packaging/cmd/kata-pkgsync/cli

INFO: Package paths:

/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/cli
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/cli/containerd-shim-kata-v2
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/cli/kata-monitor
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/containerd-shim-v2
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/netmon
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/pkg/kata-monitor
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/pkg/katatestutils
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/pkg/katautils
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/pkg/katautils/katatrace
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/pkg/signals
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/pkg/types
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/pkg/utils
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/protocols/cache
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/device/api
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/device/config
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/device/drivers
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/device/manager
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/experimental
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/factory
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/factory/base
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/factory/cache
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/factory/direct
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/factory/grpccache
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/factory/template
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/hook/mock
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/persist
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/persist/api
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/persist/fs
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/agent/protocols
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/agent/protocols/client
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/agent/protocols/grpc
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/annotations
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/annotations/dockershim
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/cgroups
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/compatoci
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/cpuset
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/firecracker/client
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/firecracker/client/models
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/firecracker/client/operations
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/mock
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/nsenter
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/oci
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/rootless
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/types
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/uuid
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/vcmock
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/types
/home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/utils
/home/fidencio/go/src/github.com/kata-containers/kata-containers/tools/packaging/cmd/kata-pkgsync/cli
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/cli
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/cli/containerd-shim-kata-v2
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/cli/kata-monitor
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/containerd-shim-v2
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/netmon
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/pkg/kata-monitor
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/pkg/katatestutils
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/pkg/katautils
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/pkg/katautils/katatrace
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/pkg/signals
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/pkg/types
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/pkg/utils
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/protocols/cache
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/device/api
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/device/config
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/device/drivers
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/device/manager
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/experimental
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/factory
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/factory/base
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/factory/cache
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/factory/direct
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/factory/grpccache
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/factory/template
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/hook/mock
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/persist
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/persist/api
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/persist/fs
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/agent/protocols
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/agent/protocols/client
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/agent/protocols/grpc
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/annotations
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/annotations/dockershim
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/cgroups
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/compatoci
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/cpuset
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/firecracker/client
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/firecracker/client/models
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/firecracker/client/operations
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/mock
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/nsenter
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/oci
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/rootless
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/types
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/uuid
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/pkg/vcmock
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/types
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/utils
INFO: Running golangci-lint on /home/fidencio/go/src/github.com/kata-containers/kata-containers/tools/packaging/cmd/kata-pkgsync/cli
INFO: Running 'static_check_json' function
INFO: Checking local branch for changed JSON only
INFO: No JSON files to check
INFO: Running 'static_check_labels' function
make -C cmd/github-labels
make[1]: se entra en el directorio '/home/fidencio/go/src/github.com/kata-containers/tests/cmd/github-labels'
go build -o "kata-github-labels" -ldflags "-X main.name=kata-github-labels -X main.commit="5e29a323e055cab5f0a8a3db97709498b36ddc58-dirty" -X main.version=0.0.1" .
install -d /home/fidencio/go/bin
install kata-github-labels /home/fidencio/go/bin/kata-github-labels
make[1]: se sale del directorio '/home/fidencio/go/src/github.com/kata-containers/tests/cmd/github-labels'
INFO: Checking labels for repo github.com/kata-containers/kata-containers using temporary combined database /tmp/tmp.MFubZSAkQw
INFO: No repo-specific labels database
INFO: Generated labels database /tmp/tmp.MFubZSAkQw
Checked file /tmp/tmp.MFubZSAkQw
INFO: Running 'static_check_license_headers' function
INFO: Checking SPDX license header
INFO: Checking Copyright header
INFO: Running 'static_check_rust_arch_specific' function
INFO: Running 'static_check_shell' function
INFO: Checking local branch for changed scripts only
INFO: No scripts to check
INFO: Running 'static_check_vendor' function
INFO: No vendoring in this repository
INFO: Running 'static_check_versions' function
INFO: Running 'static_check_xml' function
INFO: Checking local branch for changed XML files only
INFO: No XML files to check
```

Thanks Julio!

**Pull request merged**
