### PR TITLE
Remove trailing whitespaces and add github action to prevent them from returning

### PR DESCRIPTION
**Pull request by c3d**
There is a lot of trailing whitespace in the code.

Removed them, added a github action to detect and report them.

### CODE REVIEW

**Comment by devimc** [comment]
thanks @c3d , but you can't do that in the `vendor/` directory, we shouldn't edit those files.

**Review by fidencio — CHANGES_REQUESTED** [review]
As @devimc mentioned, vendored code shouldn't be touched, and we should ensure that the action will not run against the vendored code (or that the vendored result will be ignored).

**Comment by fidencio** [comment]
I'd say if this patch is ready for the release happening as soon as possible, I wouldn't mind having it merged.  Otherwise, I'd strongly prefer waiting till 2.2 release cycles.

The reason behind this is to avoid conflicts while doing backports.  Although I understand trailing whitespaces can be annoying, removing those doesn't bring any clear benefit to the project and may negatively impact the life of those working on backports / releases.

**Comment by ariel-adam** [comment]
@c3d any updates :-)?

**Comment by ariel-adam** [comment]
After a long discussion with @c3d  we have decided to close this issue :-).

**Pull request closed without merging**
