### PR TITLE
osbuilder: remove traces of cmake

### PR DESCRIPTION
**Pull request by dgibson**
AFAICT cmake is referenced in the osbuilder scripts, but never actually invoked.

### CODE REVIEW

**Comment by fidencio** [comment]
I'm really sorry for the disruption but in order to do the branch name changes announced [here](http://lists.katacontainers.io/pipermail/kata-dev/2021-January/001695.html) I'm adding the "do-not-merge" and the "needs-branch-adjustment" labels to the PR.

I'll add a new comment once the branch changes are done and once it happens I'd like to ask you to resubmit the PR against the new `main` branch, possibly linking to this PR in case you find the conversations / reviews already made important to proceed.

**Comment by dgibson** [comment]
@fidencio understood.  It's a minor hassle and the new branch names make much more sense to me.

**Comment by fidencio** [comment]
Kata Containers repos are back to business.  Thanks a lot for your patience and I'm very happy to announce that there's no changes needed from your side as renaming the branches automagically reflected here.

If you notice something weird, some missing CI, please, do not hesitate on contacting us here or on #kata-dev on bit.ly/katacontainersslack.

Also, this is a good opportunity to have your PR rebased atop of `main`, to ensure your PR follow all the guidelines (https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format) enforced by this community, or even to re-evaluate whether the PR is currently needed.

Last but not least,  as the default branch has been renamed to `main`, if you have a local clone you'd need to update it and you do so by running:
```
git branch -m 2.0-dev main
git fetch origin
git branch -u origin/main main
```

Happy hacking!

**Review by fidencio — APPROVED** [review]
lgtm, thanks @dgibson!

Please, I'd just like to ask you to rebase atop of current main, just to rerun the CIs and be sure nothing would be failing there after we renamed the branches.

**Comment by fidencio** [comment]
**jenkins-ci-ubuntu-1804-cloud-hypervisor-k8s-containerd-2.0** is failing, @likebreath, mind to take a look?

**Comment by dgibson** [comment]
@fidencio, I *think* `jenkins-ci-ubuntu-1804-cloud-hypervisor-k8s-containerd-2.0` is failing on an unmodified tree at the moment, which is why @GabyCT took it off the required list.

**Comment by fidencio** [comment]
> @fidencio, I _think_ `jenkins-ci-ubuntu-1804-cloud-hypervisor-k8s-containerd-2.0` is failing on an unmodified tree at the moment, which is why @GabyCT took it off the required list.

Oh, okay, good to know that that's the case.  I thought I had broke this one during Friday's migration.
I'll wait for a review from someone else **outside** of Red Hat and let @GabyCT or @likebreath merge this one, as most likely they're aware of the failure and would be the best people to decide whether to merge or not with this job failing.

Thanks for the contribution!

**Comment by wainersm** [comment]
@dgibson code-wise, the changes look good to me.

But I have no idea whether cmake is still needed or not. Maybe  @yyyeerbo  can comment on this as he introduced the code on commit 1a7b735c3 .

**Comment by likebreath** [comment]
There were few pending changes (now landed) for the CLH CI by @jcvenegas. Restarted the CLH CI and see how it goes. 

I am not aware of dependencies of CLH CI on CMake, and the changes look good to me. @jcvenegas Please correct me if I am wrong. Thank you.

**Review by likebreath — APPROVED** [review]

**Pull request merged**
