### PR TITLE
main: Split config code into separate module

### PR DESCRIPTION
**Pull request by jodh-intel**
Create a config module and add more tests. Also enable setting the log level from the kernel command-line.

Fixes: #59, #63.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
@yyyeerbo, @lifupan - ptal as there are a number of follow-on PRs relating to configuration that need this change.

**Comment by yyyeerbo** [comment]
lgtm

**Comment by yyyeerbo** [comment]
> @yyyeerbo, @lifupan - ptal as there are a number of follow-on PRs relating to configuration that need this change.

I've no permission to do anything. The only thing is "lgtm" :)

**Comment by jodh-intel** [comment]
@yyyeerbo - thanks! I've added you as a "member" of this repo, so you *should* now be able to approve PRs.

**Comment by yyyeerbo** [comment]
> @yyyeerbo - thanks! I've added you as a "member" of this repo, so you _should_ now be able to approve PRs.

My approval is gray instead of green. -_- It doesn't count :)

**Comment by jodh-intel** [comment]
@yyyeerbo - I don't know why, but you were added as a member, but with lower privileges. I've now updated your user in the group for this repo, so hopefully that will solve the problem :)

**Pull request merged**
