### PR TITLE
docs: remove the 1.x version description about shim and proxy

### PR DESCRIPTION
**Pull request by YchauWang**
Remove the build in shim and proxy desgin description from the
kata-api-design.md file.

Fixes: #912

Signed-off-by: Ychau Wang <wangyongchao.bj@inspur.com>

### CODE REVIEW

**Review by bergwolf — APPROVED** [review]
Thanks!

**Comment by bergwolf** [comment]
Please fix the check spell failure. You may simply use "`" to quote these words to pass it.
```
INFO: Spell checking file 'docs/design/kata-api-design.md'
WARNING: Word 'containerID': did you mean one of the following?: container Id, container ID, container-ID, container-id, containerized, containerize, container
WARNING: Word 'containerID': did you mean one of the following?: container Id, container ID, container-ID, container-id, containerized, containerize, container
WARNING: Word 'containerID': did you mean one of the following?: container Id, container ID, container-ID, container-id, containerized, containerize, container
WARNING: Word 'containerID': did you mean one of the following?: container Id, container ID, container-ID, container-id, containerized, containerize, container
WARNING: Word 'hypervisor's': did you mean one of the following?: hyper visor's, hyper-visor's, supervisor's
WARNING: Word 'param': did you mean one of the following?: para, pram, paras, pa ram, pa-ram, par am, par-am, para m, rampart
ERROR: Spell check failed for file: 'docs/design/kata-api-design.md'
INFO: spell check failed for document docs/design/kata-api-design.md
ERROR: spell check failed, See https://github.com/kata-containers/documentation/blob/master/Documentation-Requirements.md#spelling for more information.
The command "ci/static-checks.sh" exited with 1.
```

**Comment by YchauWang** [comment]
> Please fix the check spell failure. You may simply use "`" to quote these words to pass it.
> 
> ```
> INFO: Spell checking file 'docs/design/kata-api-design.md'
> WARNING: Word 'containerID': did you mean one of the following?: container Id, container ID, container-ID, container-id, containerized, containerize, container
> WARNING: Word 'containerID': did you mean one of the following?: container Id, container ID, container-ID, container-id, containerized, containerize, container
> WARNING: Word 'containerID': did you mean one of the following?: container Id, container ID, container-ID, container-id, containerized, containerize, container
> WARNING: Word 'containerID': did you mean one of the following?: container Id, container ID, container-ID, container-id, containerized, containerize, container
> WARNING: Word 'hypervisor's': did you mean one of the following?: hyper visor's, hyper-visor's, supervisor's
> WARNING: Word 'param': did you mean one of the following?: para, pram, paras, pa ram, pa-ram, par am, par-am, para m, rampart
> ERROR: Spell check failed for file: 'docs/design/kata-api-design.md'
> INFO: spell check failed for document docs/design/kata-api-design.md
> ERROR: spell check failed, See https://github.com/kata-containers/documentation/blob/master/Documentation-Requirements.md#spelling for more information.
> The command "ci/static-checks.sh" exited with 1.
> ```

**Review by jodh-intel — APPROVED** [review]
Thanks @YchauWang.

**Review by amshinde — APPROVED** [review]

**Comment by amshinde** [comment]
@YchauWang Can you port this to stable 2.0 branch as well?

**Pull request merged**
