### PR TITLE
# Kata Containers 2.3.2

### PR DESCRIPTION
**Pull request by snir911**
- stable-2.3-backports
- [backport from main] agent: fix the issue of missing create a new session for container
- stable-2.3 - kata-deploy: validate conf file can be created
- stable-2.3 | kata-monitor: increase delay before syncing with the container manager
- stable-2.3 | versions: Upgrade to Cloud Hypervisor v21.0
- stable-2.3: backport lint fixes from main
- stable-2.3 | runtime: -Wl,--s390-pgste for s390x
- stable-2.3 | kata-manager: Retrieve static tarball
- stable-2.3 | ci: Pass function arguments in static-checks.sh

99ed596a workflows: Fix typo in kata-deploy-push action
13b7d93b workflows: Ensure a label change re-triggers the actions
b8463224 workflows: Ensure force-skip-ci skips all actions
8c8571f4 workflows: Use the correct branch ref on test kata-deploy
620bb97e runtime: Provide protection for shared data
770d4acf tools: Fix groupname if it differs from username
cedb01d2 runtime: close span before return from function in case of error
a661e538 agent: fix the issue of missing create a new session for container
bed0f3c8 kata-deploy: validate conf file can be created
786c667e kata-monitor: increase delay before syncing with the container manager
e3b00f39 runtime: -Wl,--s390-pgste for s390x
3260adc4 virtcontainers: clh: Re-generate the client code
cc64461f versions: Upgrade to Cloud Hypervisor v21.0
f2c6cd08 ci: Pass function arguments in static-checks.sh
78afa10a agent: resolve unused variables in tests
a8298676 agent: remove unused field in mount handling
87f9a690 agent: drop unused fields from network
fc012a2b agent: clear cargo test warnings
63c5a8aa uevent: Fix clippy issue in test code
d1530afa kata-manager: Retrieve static tarball

### CODE REVIEW

**Comment by snir911** [comment]
dnm until [test-kata-deploy ](https://github.com/kata-containers/kata-containers/actions/runs/1778586983) passes
@wainersm ^
and:
/test

**Comment by fidencio** [comment]
Yeah, issues popping up with libseccomp build.

**Comment by snir911** [comment]
I guess gnu.org is down again:
https://github.com/kata-containers/kata-containers/issues/3313
I wonder whether i should backport it

**Comment by fidencio** [comment]
> To monitor: https://github.com/kata-containers/kata-containers/actions/runs/1778954654

The failure seen there means that 3924470c8ff3cab4e1e628fc5559e83854f1b479 is missing a backport.

**Comment by fidencio** [comment]
> > To monitor: https://github.com/kata-containers/kata-containers/actions/runs/1778954654
> 
> The failure seen there means that [3924470](https://github.com/kata-containers/kata-containers/commit/3924470c8ff3cab4e1e628fc5559e83854f1b479) is missing a backport.

Reviews of the backport are very mich appreciated: https://github.com/kata-containers/kata-containers/pull/3580

**Comment by snir911** [comment]
closing until 3924470 is in

**Pull request closed without merging**
