### PR TITLE
runtime: Add heuristic to get the right value(s) for mem-reserve

### PR DESCRIPTION
**Pull request by zvonkok**
Add heuristic to get the right values for mem-reserve and pref-64-reserve. 

Fixes: #2938

Signed-off-by: Zvonko Kaiser <zkaiser@nvidia.com>

### CODE REVIEW

**Comment by zvonkok** [comment]
@liubin @bergwolf @Jimmy-Xu PTAL

**Comment by zvonkok** [comment]
```
E: Could not get lock /var/lib/apt/lists/lock. It is held by process 123429 (apt-get)
E: Unable to lock directory /var/lib/apt/lists/
[install_kubernetes.sh:33] ERROR: chronic sudo -E apt update
[jenkins_job_build.sh:168] ERROR: ci/setup.sh
Build step 'Execute shell' marked build as failure
```

@BbolroC s390x failing. Thanks!

**Comment by BbolroC** [comment]
@zvonkok it will fail anyway because of 

```
Trying to install containerd from static tarball
Download tarball from https://github.com/containerd/containerd/releases/download/v1.5.2/cri-containerd-cni-1.5.2-linux-s390x.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
Failed to download tarball from https://github.com/containerd/containerd/releases/download/v1.5.2/cri-containerd-cni-1.5.2-linux-s390x.tar.gz
Trying to install containerd from source
```

**Comment by BbolroC** [comment]
I have deleted a comment I had left because I found that it it not correct. Sorry. I will have a look into this as well. Thanks. :wink:

**Comment by Amulyam24** [comment]
Hi @zvonkok, the ppc64le CI is failing with a known issue. Please ignore it and I will probably disable the CI until fixed.

**Comment by zvonkok** [comment]
@Amulyam24 Thanks!

**Comment by zvonkok** [comment]
```
23:08:23 curl: (22) The requested URL returned error: 404 
23:08:23 Failed to download tarball from https://github.com/containerd/containerd/releases/download/v1.5.2/cri-containerd-cni-1.5.2-linux-arm64.tar.gz
23:08:23 Trying to install containerd from source
23:08:23 Repo /home/jenkins/workspace/kata-containers-2.0-ubuntu-ARM-PR/go/src/github.com/containerd/containerd already in git's safe.directory
23:08:35 Note: switching to 'v1.5.2'.
``` 

The same error that ppc64 has a version pulled that does not exist anymore. 

@jongwu @justin-he PTAL /cc @jodh-intel

**Comment by liubin** [comment]
@zvonkok Did you committed your `go.sum`?

```
all modules verified
./hack/tree_status.sh
tree is dirty, please commit all changes
 M src/runtime/go.sum
diff --git a/src/runtime/go.sum b/src/runtime/go.sum
index 7b7964d4e..f4737746d 100644
--- a/src/runtime/go.sum
+++ b/src/runtime/go.sum
@@ -908,8 +908,6 @@ github.com/yuin/goldmark v1.3.5/go.mod h1:mwnBkeHKe2W/ZEtQ+71ViKU8L12m81fl3OWwC1
 github.com/yvasiyarov/go-metrics v0.0.0-20140926110328-57bccd1ccd43/go.mod h1:aX5oPXxHm3bOH+xeAttToC8pqch2ScQN/JoXYupl6xs=
 github.com/yvasiyarov/gorelic v0.0.0-20141212073537-a9bba5b9ab50/go.mod h1:NUSPSUX/bi6SeDMUh6brw0nXpxHnc96TguQh0+r/ssA=
 github.com/yvasiyarov/newrelic_platform_go v0.0.0-20140908184405-b21fdbd4370f/go.mod h1:GlGEuHIJweS1mbCqG+7vt2nvWLzLLnRHbXz5JKd/Qbg=
-gitlab.com/nvidia/cloud-native/go-nvlib v0.0.0-20220525163429-038b3f8b475d h1:WLnoEFzgCutNeWSdVTOU6U/55FA/FS0EbXNifmOAPHA=
-gitlab.com/nvidia/cloud-native/go-nvlib v0.0.0-20220525163429-038b3f8b475d/go.mod h1:TBB3sR7/jg4RCThC/cgT4fB8mAbbMO307TycfgeR59w=
 gitlab.com/nvidia/cloud-native/go-nvlib v0.0.0-20220601114329-47893b162965 h1:EXE1ZsUqiUWGV5Dw2oTYpXx24ffxj0//yhTB0Ppv+4s=
```

**Comment by zvonkok** [comment]
@liubin Yes, I needed an extra library, shouldn't go.mod and go.sum be committed anyway?

**Comment by liubin** [comment]
> @liubin Yes, I needed an extra library, shouldn't go.mod and go.sum be committed as a pair?

You are right, they should be committed as a pair.

Can you verify why ./hack/tree_status.sh locally?

Or rust run `go mod tidy && go mod vendor` and then see whether your work dir is clean.

**Comment by zvonkok** [comment]
@liubin test-runk is failing, who is the owner? Thanks!

**Comment by liubin** [comment]
> @liubin test-runk is failing, who is the owner? Thanks!

It's maybe a random failing. I retried and now all tests passed.

**Comment by zvonkok** [comment]
@liubin @jodh-intel We might remove the man-db completely from the CI, it is not needed anyway. 

`apt remove -y --purge man-db` WDYT?

**Review by fidencio — COMMENTED** [review]
This looks sane to me, but I have no hardware to test.
I'll add a lgtm after having someone from QEMU side (cc @gkurz) taking a look at it.

**Comment by fidencio** [comment]
@liubin, @gkurz, mind to take a look at this one?

**Review by Bevisy — APPROVED** [review]
LGTM, thanks.
By the way, I am trying to compile this PR and intend to put it into the environment to further verify.

**Comment by zvonkok** [comment]
@Bevisy Please report back, if you have any errors, can you also post your BAR sizes of the GPU on the host and in the VM? Thanks!

**Comment by soulseen** [comment]
@zvonkok Hi, I compiled this PR and test in my environment, but sadly, the error still exists.
run `lspci -s 0000:1a:00.0 -vv` in host:
```
root@ai-2080ti-27:/etc/kubernetes/manifests# lspci -s 0000:1a:00.0 -vv
1a:00.0 VGA compatible controller: NVIDIA Corporation TU102 [GeForce RTX 2080 Ti] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: Micro-Star International Co., Ltd. [MSI] TU102 [GeForce RTX 2080 Ti]
	Control: I/O+ Mem+ BusMaster- SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR+ FastB2B- DisINTx-
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Interrupt: pin A routed to IRQ 25
	NUMA node: 0
	IOMMU group: 40
	Region 0: Memory at a9000000 (32-bit, non-prefetchable) [size=16M]
	Region 1: Memory at 39ffe0000000 (64-bit, prefetchable) [size=256M]
	Region 3: Memory at 39fff0000000 (64-bit, prefetchable) [size=32M]
	Region 5: I/O ports at 5000 [size=128]
	Expansion ROM at aa000000 [disabled] [size=512K]
	Capabilities: [60] Power Management version 3
		Flags: PMEClk- DSI- D1- D2- AuxCurrent=375mA PME(D0+,D1-,D2-,D3hot+,D3cold-)
		Status: D3 NoSoftRst+ PME-Enable- DSel=0 DScale=0 PME-
	Capabilities: [68] MSI: Enable- Count=1/1 Maskable- 64bit+
		Address: 0000000000000000  Data: 0000
	Capabilities: [78] Express (v2) Legacy Endpoint, MSI 00
		DevCap:	MaxPayload 256 bytes, PhantFunc 0, Latency L0s unlimited, L1 <64us
			ExtTag+ AttnBtn- AttnInd- PwrInd- RBE+ FLReset+
		DevCtl:	CorrErr+ NonFatalErr+ FatalErr+ UnsupReq-
			RlxdOrd+ ExtTag+ PhantFunc- AuxPwr- NoSnoop+ FLReset-
			MaxPayload 128 bytes, MaxReadReq 512 bytes
		DevSta:	CorrErr- NonFatalErr- FatalErr- UnsupReq- AuxPwr- TransPend-
		LnkCap:	Port #8, Speed 8GT/s, Width x16, ASPM L0s L1, Exit Latency L0s <1us, L1 <4us
			ClockPM+ Surprise- LLActRep- BwNot- ASPMOptComp+
		LnkCtl:	ASPM Disabled; RCB 64 bytes, Disabled- CommClk-
			ExtSynch- ClockPM- AutWidDis- BWInt- AutBWInt-
		LnkSta:	Speed 8GT/s (ok), Width x16 (ok)
			TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-
		DevCap2: Completion Timeout: Range AB, TimeoutDis+ NROPrPrP- LTR+
			 10BitTagComp- 10BitTagReq- OBFF Via message, ExtFmt- EETLPPrefix-
			 EmergencyPowerReduction Not Supported, EmergencyPowerReductionInit-
			 FRS-
			 AtomicOpsCap: 32bit- 64bit- 128bitCAS-
		DevCtl2: Completion Timeout: 50us to 50ms, TimeoutDis- LTR- OBFF Disabled,
			 AtomicOpsCtl: ReqEn-
		LnkCap2: Supported Link Speeds: 2.5-8GT/s, Crosslink- Retimer- 2Retimers- DRS-
		LnkCtl2: Target Link Speed: 8GT/s, EnterCompliance- SpeedDis-
			 Transmit Margin: Normal Operating Range, EnterModifiedCompliance- ComplianceSOS-
			 Compliance De-emphasis: -6dB
		LnkSta2: Current De-emphasis Level: -6dB, EqualizationComplete+ EqualizationPhase1+
			 EqualizationPhase2+ EqualizationPhase3+ LinkEqualizationRequest-
			 Retimer- 2Retimers- CrosslinkRes: unsupported
	Capabilities: [100 v1] Virtual Channel
		Caps:	LPEVC=0 RefClk=100ns PATEntryBits=1
		Arb:	Fixed- WRR32- WRR64- WRR128-
		Ctrl:	ArbSelect=Fixed
		Status:	InProgress-
		VC0:	Caps:	PATOffset=00 MaxTimeSlots=1 RejSnoopTrans-
			Arb:	Fixed- WRR32- WRR64- WRR128- TWRR128- WRR256-
			Ctrl:	Enable+ ID=0 ArbSelect=Fixed TC/VC=01
			Status:	NegoPending- InProgress-
	Capabilities: [250 v1] Latency Tolerance Reporting
		Max snoop latency: 0ns
		Max no snoop latency: 0ns
	Capabilities: [258 v1] L1 PM Substates
		L1SubCap: PCI-PM_L1.2+ PCI-PM_L1.1+ ASPM_L1.2+ ASPM_L1.1+ L1_PM_Substates+
			  PortCommonModeRestoreTime=255us PortTPowerOnTime=10us
		L1SubCtl1: PCI-PM_L1.2- PCI-PM_L1.1- ASPM_L1.2- ASPM_L1.1-
			   T_CommonMode=0us LTR1.2_Threshold=0ns
		L1SubCtl2: T_PwrOn=10us
	Capabilities: [128 v1] Power Budgeting <?>
	Capabilities: [420 v2] Advanced Error Reporting
		UESta:	DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
		UEMsk:	DLP+ SDES- TLP+ FCP+ CmpltTO+ CmpltAbrt+ UnxCmplt+ RxOF+ MalfTLP+ ECRC- UnsupReq+ ACSViol-
		UESvrt:	DLP+ SDES+ TLP- FCP+ CmpltTO- CmpltAbrt- UnxCmplt- RxOF+ MalfTLP+ ECRC- UnsupReq- ACSViol-
		CESta:	RxErr- BadTLP- BadDLLP- Rollover- Timeout- AdvNonFatalErr-
		CEMsk:	RxErr+ BadTLP+ BadDLLP+ Rollover+ Timeout+ AdvNonFatalErr+
		AERCap:	First Error Pointer: 00, ECRCGenCap- ECRCGenEn- ECRCChkCap- ECRCChkEn-
			MultHdrRecCap- MultHdrRecEn- TLPPfxPres- HdrLogCap-
		HeaderLog: 00000000 00000000 00000000 00000000
	Capabilities: [600 v1] Vendor Specific Information: ID=0001 Rev=1 Len=024 <?>
	Capabilities: [900 v1] Secondary PCI Express
		LnkCtl3: LnkEquIntrruptEn- PerformEqu-
		LaneErrStat: 0
	Capabilities: [bb0 v1] Physical Resizable BAR
		BAR 0: current size: 16MB, supported: 16MB
		BAR 1: current size: 256MB, supported: 64MB 128MB 256MB
		BAR 3: current size: 32MB, supported: 32MB
	Kernel driver in use: vfio-pci
	Kernel modules: nouveau
```
in container:
```
root@ai-2080ti-27:/etc/kubernetes/manifests# ctr --debug run --runtime "io.containerd.kata.v2"  --device /dev/vfio/40  --rm -t  "docker.io/library/archlinux:latest" arch bash
[root@clr-20e4d3dc97f94b2b8efbc958b401b961 /]# lspci -s 0000:01:01.0 -vv
01:01.0 VGA compatible controller: NVIDIA Corporation TU102 [GeForce RTX 2080 Ti] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: Micro-Star International Co., Ltd. [MSI] Device 3712
	Physical Slot: 1
	Control: I/O- Mem- BusMaster- SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR+ FastB2B- DisINTx-
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Interrupt: pin A routed to IRQ 11
	NUMA node: 0
	Region 5: I/O ports at c000 [disabled] [size=128]
	Capabilities: <access denied>
lspci: Unable to load libkmod resources: error -2
```
and other information is:
I disabled `hotplug_vfio_on_root_bus` and `pcie_root_port `, because can not start the container with the error `ctr: failed to create shim task: the file nvidia-smi was not found: unknown` when enabling it.(if i wrong pls correct me)

**Comment by zvonkok** [comment]
@soulseen Can you do a `lspci` inside the guest and not inside the container? 

`lspci -s $BDF_IN_GUEST -vv | grep Region` 

You do not have the privilege to read all the Regions on the container.

**Comment by zvonkok** [comment]
@soulseen I am also thinking that your `rootfs` is not correct. I will provide you with my guest OS and Kernel just to sanity check.

**Comment by soulseen** [comment]
> @soulseen Can you do a `lspci` inside the guest and not inside the container?
> 
> `lspci -s $BDF_IN_GUEST -vv | grep Region`
> 
> You do not have the privilege to read all the Regions on the container.


hi, run the command in guest:
```
root@ai-2080ti-27:/home/zhuxiaoyang# kata-runtime exec arch
root@localhost:/# lspci -s 0000:01:01.0 -vv | grep Region
	Region 1: Memory at <unassigned> (64-bit, prefetchable) [disabled]
	Region 3: Memory at <unassigned> (64-bit, prefetchable) [disabled]
	Region 5: I/O ports at c000 [disabled] [size=128]
root@localhost:/# dmesg | grep BAR
[    2.923533] pci 0000:01:01.0: BAR 1: no space for [mem size 0x10000000 64bit pref]
[    2.923535] pci 0000:01:01.0: BAR 1: failed to assign [mem size 0x10000000 64bit pref]
[    2.923538] pci 0000:01:01.0: BAR 3: no space for [mem size 0x02000000 64bit pref]
[    2.923539] pci 0000:01:01.0: BAR 3: failed to assign [mem size 0x02000000 64bit pref]
[    2.923541] pci 0000:01:01.0: BAR 0: no space for [mem size 0x01000000]
[    2.923542] pci 0000:01:01.0: BAR 0: failed to assign [mem size 0x01000000]
[    2.923543] pci 0000:01:01.0: BAR 5: assigned [io  0xc000-0xc07f]
[    2.968991] pci 0000:01:02.0: BAR 0: assigned [mem 0xfe400000-0xfe403fff]
[    3.010224] pci 0000:01:03.0: BAR 0: assigned [mem 0xfe800000-0xfe83ffff 64bit pref]
[    3.010307] pci 0000:01:03.0: BAR 3: assigned [mem 0xfe840000-0xfe84ffff 64bit pref]
[    3.076810] pci 0000:01:04.0: BAR 0: assigned [mem 0xfe404000-0xfe404fff]
root@localhost:/#
```
looks like the bar space still assign failed. 
If it is convenient, please email me your guest and kernel image to [zhuxiaoyang@corp.netease.com](mailto:zhuxiaoyang@corp.netease.com). thanks.

**Comment by Bevisy** [comment]
@zvonkok I tried, but failed.
```sh
[    3.340854] pci 0000:02:00.0: [10de:20f1] type 00 class 0x030200
[    3.342530] pci 0000:02:00.0: reg 0x10: [mem 0x00000000-0x00ffffff]
[    3.342738] pci 0000:02:00.0: reg 0x14: [mem 0x00000000-0xfffffffff 64bit pref]
[    3.342941] pci 0000:02:00.0: reg 0x1c: [mem 0x00000000-0x01ffffff 64bit pref]
[    3.343315] pci 0000:02:00.0: Max Payload Size set to 128 (was 256, max 256)
[    3.344096] pci 0000:02:00.0: Enabling HDA controller
[    3.345186] pci 0000:02:00.0: PME# supported from D0 D3hot
[    3.345965] pci 0000:02:00.0: 126.016 Gb/s available PCIe bandwidth, limited by 8.0 GT/s PCIe x16 link at 0000:00:05.0 (capable of 252.048 Gb/s with 16.0 GT/s PCIe x16 link)
[    3.347275] pci 0000:02:00.0: BAR 1: assigned [mem 0x4000000000-0x4fffffffff 64bit pref]
[    3.347467] pci 0000:02:00.0: BAR 3: assigned [mem 0x3280000000-0x3281ffffff 64bit pref]
[    3.347685] pci 0000:02:00.0: BAR 0: no space for [mem size 0x01000000]
[    3.347689] pci 0000:02:00.0: BAR 0: failed to assign [mem size 0x01000000]
```
GPU Info:
```sh
# HOST GPU CARD INFO, NOT IN GUEST
d8:00.0 3D controller: NVIDIA Corporation GA100 [A100 PCIe 40GB] (rev a1)
        Subsystem: NVIDIA Corporation Device 145f
        Control: I/O- Mem- BusMaster- SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Interrupt: pin A routed to IRQ 456
        NUMA node: 1
        IOMMU group: 79
        Region 0: Memory at f1000000 (32-bit, non-prefetchable) [disabled] [size=16M]
        Region 1: Memory at 384000000000 (64-bit, prefetchable) [disabled] [size=64G]
        Region 3: Memory at 386000000000 (64-bit, prefetchable) [disabled] [size=32M]
        Capabilities: [60] Power Management version 3
                Flags: PMEClk- DSI- D1- D2- AuxCurrent=0mA PME(D0+,D1-,D2-,D3hot+,D3cold-)
                Status: D0 NoSoftRst+ PME-Enable- DSel=0 DScale=0 PME-
        Capabilities: [68] Null
        Capabilities: [78] Express (v2) Endpoint, MSI 00
                DevCap: MaxPayload 256 bytes, PhantFunc 0, Latency L0s unlimited, L1 <64us
                        ExtTag+ AttnBtn- AttnInd- PwrInd- RBE+ FLReset+ SlotPowerLimit 75.000W
                DevCtl: CorrErr- NonFatalErr+ FatalErr+ UnsupReq+
                        RlxdOrd+ ExtTag+ PhantFunc- AuxPwr- NoSnoop+ FLReset-
                        MaxPayload 256 bytes, MaxReadReq 512 bytes
                DevSta: CorrErr- NonFatalErr- FatalErr- UnsupReq- AuxPwr- TransPend-
                LnkCap: Port #0, Speed 16GT/s, Width x16, ASPM not supported
                        ClockPM+ Surprise- LLActRep- BwNot- ASPMOptComp+
                LnkCtl: ASPM Disabled; RCB 64 bytes, Disabled- CommClk+
                        ExtSynch- ClockPM- AutWidDis- BWInt- AutBWInt-
                LnkSta: Speed 8GT/s (downgraded), Width x16 (ok)
                        TrErr- Train- SlotClk+ DLActive- BWMgmt- ABWMgmt-
                DevCap2: Completion Timeout: Range AB, TimeoutDis+ NROPrPrP- LTR+
                         10BitTagComp+ 10BitTagReq+ OBFF Via message, ExtFmt- EETLPPrefix-
                         EmergencyPowerReduction Not Supported, EmergencyPowerReductionInit-
                         FRS- TPHComp- ExtTPHComp-
                         AtomicOpsCap: 32bit- 64bit- 128bitCAS-
                DevCtl2: Completion Timeout: 65ms to 210ms, TimeoutDis- LTR- OBFF Disabled,
                         AtomicOpsCtl: ReqEn-
                LnkCap2: Supported Link Speeds: 2.5-16GT/s, Crosslink- Retimer+ 2Retimers+ DRS-
                LnkCtl2: Target Link Speed: 16GT/s, EnterCompliance- SpeedDis-
                         Transmit Margin: Normal Operating Range, EnterModifiedCompliance- ComplianceSOS-
                         Compliance De-emphasis: -6dB
                LnkSta2: Current De-emphasis Level: -3.5dB, EqualizationComplete+ EqualizationPhase1+
                         EqualizationPhase2+ EqualizationPhase3+ LinkEqualizationRequest-
                         Retimer- 2Retimers- CrosslinkRes: unsupported
        Capabilities: [c8] MSI-X: Enable- Count=6 Masked-
                Vector table: BAR=0 offset=00b90000
                PBA: BAR=0 offset=00ba0000
        Capabilities: [100 v1] Virtual Channel
                Caps:   LPEVC=0 RefClk=100ns PATEntryBits=1
                Arb:    Fixed- WRR32- WRR64- WRR128-
                Ctrl:   ArbSelect=Fixed
                Status: InProgress-
                VC0:    Caps:   PATOffset=00 MaxTimeSlots=1 RejSnoopTrans-
                        Arb:    Fixed- WRR32- WRR64- WRR128- TWRR128- WRR256-
                        Ctrl:   Enable+ ID=0 ArbSelect=Fixed TC/VC=ff
                        Status: NegoPending- InProgress-
        Capabilities: [250 v1] Latency Tolerance Reporting
                Max snoop latency: 0ns
                Max no snoop latency: 0ns
        Capabilities: [258 v1] L1 PM Substates
                L1SubCap: PCI-PM_L1.2+ PCI-PM_L1.1+ ASPM_L1.2+ ASPM_L1.1+ L1_PM_Substates+
                          PortCommonModeRestoreTime=255us PortTPowerOnTime=10us
                L1SubCtl1: PCI-PM_L1.2- PCI-PM_L1.1- ASPM_L1.2- ASPM_L1.1-
                           T_CommonMode=0us LTR1.2_Threshold=0ns
                L1SubCtl2: T_PwrOn=10us
        Capabilities: [128 v1] Power Budgeting <?>
        Capabilities: [420 v2] Advanced Error Reporting
                UESta:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt- RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UEMsk:  DLP- SDES- TLP- FCP- CmpltTO- CmpltAbrt- UnxCmplt+ RxOF- MalfTLP- ECRC- UnsupReq- ACSViol-
                UESvrt: DLP+ SDES+ TLP+ FCP+ CmpltTO+ CmpltAbrt+ UnxCmplt- RxOF+ MalfTLP+ ECRC- UnsupReq- ACSViol-
                CESta:  RxErr- BadTLP- BadDLLP- Rollover- Timeout- AdvNonFatalErr+
                CEMsk:  RxErr+ BadTLP+ BadDLLP+ Rollover+ Timeout+ AdvNonFatalErr+
                AERCap: First Error Pointer: 00, ECRCGenCap- ECRCGenEn- ECRCChkCap- ECRCChkEn-
                        MultHdrRecCap- MultHdrRecEn- TLPPfxPres- HdrLogCap-
                HeaderLog: 00000000 00000000 00000000 00000000
        Capabilities: [600 v1] Vendor Specific Information: ID=0001 Rev=1 Len=024 <?>
        Capabilities: [900 v1] Secondary PCI Express
                LnkCtl3: LnkEquIntrruptEn- PerformEqu-
                LaneErrStat: 0
        Capabilities: [bb0 v1] Physical Resizable BAR
                BAR 0: current size: 16MB, supported: 16MB
                BAR 1: current size: 64GB, supported: 64MB 128MB 256MB 512MB 1GB 2GB 4GB 8GB 16GB 32GB 64GB
                BAR 3: current size: 32MB, supported: 32MB
        Capabilities: [bcc v1] Single Root I/O Virtualization (SR-IOV)
                IOVCap: Migration-, Interrupt Message Number: 000
                IOVCtl: Enable- Migration- Interrupt- MSE- ARIHierarchy+
                IOVSta: Migration-
                Initial VFs: 16, Total VFs: 16, Number of VFs: 0, Function Dependency Link: 00
                VF offset: 4, stride: 1, Device ID: 20f1
                Supported Page Size: 00000573, System Page Size: 00000001
                Region 0: Memory at f2000000 (32-bit, non-prefetchable)
                Region 1: Memory at 0000385000000000 (64-bit, prefetchable)
                Region 3: Memory at 0000386002000000 (64-bit, prefetchable)
                VF Migration: offset: 00000000, BIR: 0
        Capabilities: [c14 v1] Alternative Routing-ID Interpretation (ARI)
                ARICap: MFVC- ACS-, Next Function: 0
                ARICtl: MFVC- ACS-, Function Group: 0
        Capabilities: [c1c v1] Physical Layer 16.0 GT/s <?>
        Capabilities: [d00 v1] Lane Margining at the Receiver <?>
        Capabilities: [e00 v1] Data Link Feature <?>
        Kernel driver in use: vfio-pci
        Kernel modules: nouveau
```

**Review by liubin — APPROVED** [review]

**Comment by zvonkok** [comment]
@soulseen @Bevisy Can you also share the PCIe Root Port `Region`, I am thinking of a boundary condition that may arise here. 

In the quest not in the container to "see" the complete PCIe config space.

**Comment by soulseen** [comment]
hi, @zvonkok  can not see any Root Port.
```
root@localhost:/# lspci | grep Root
root@localhost:/# lspci -s 00:05.0 -vvv | grep '\[size='
	Region 1: Memory at fe602000 (32-bit, non-prefetchable) [size=4K]
	Region 4: Memory at fea0c000 (64-bit, prefetchable) [size=16K]
```

**Comment by zvonkok** [comment]
Rebased and fixed an error with 32bit mem-size. 
@Bevisy PTAL 
@soulseen You need a pcie root port.

**Comment by Bevisy** [comment]
@zvonkok @fidencio Verified ☑️
```sh
[root@node-2 ~]# ctr -n k8s.io run --rm --runtime "io.containerd.kata.v2"  --device /dev/vfio/79 --rm -t "docker.io/nvidia/cuda:11.6.0-base-ubuntu20.04" cuda bash
root@localhost:/# lsmod
bash: lsmod: command not found
root@localhost:/# nvidia-smi
Tue Jun 21 11:02:09 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.48.07    Driver Version: 515.48.07    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-PCI...  Off  | 00000000:02:00.0 Off |                    0 |
| N/A   62C    P0    56W / 250W |      0MiB / 40960MiB |      3%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
root@localhost:/# exit
exit
[root@node-2 ~]# ctr -n k8s.io run --rm --runtime io.containerd.kata.v2 -t --device /dev/vfio/79 docker.io/library/archlinux:latest test sh
sh-5.1# lspci
00:00.0 Host bridge: Intel Corporation 82G33/G31/P35/P31 Express DRAM Controller
00:01.0 Communication controller: Red Hat, Inc. Virtio console
00:02.0 PCI bridge: Red Hat, Inc. QEMU PCI-PCI bridge
00:03.0 SCSI storage controller: Red Hat, Inc. Virtio SCSI
00:04.0 Unclassified device [00ff]: Red Hat, Inc. Virtio RNG
00:05.0 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:06.0 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:07.0 Communication controller: Red Hat, Inc. Virtio socket (rev 01)
00:08.0 Mass storage controller: Red Hat, Inc. Virtio file system (rev 01)
00:1f.0 ISA bridge: Intel Corporation 82801IB (ICH9) LPC Interface Controller (rev 02)
00:1f.2 SATA controller: Intel Corporation 82801IR/IO/IH (ICH9R/DO/DH) 6 port SATA Controller [AHCI mode] (rev 02)
00:1f.3 SMBus: Intel Corporation 82801I (ICH9 Family) SMBus Controller (rev 02)
02:00.0 3D controller: NVIDIA Corporation GA100 [A100 PCIe 40GB] (rev a1)
sh-5.1# lspci -v -s 02:00.0
02:00.0 3D controller: NVIDIA Corporation GA100 [A100 PCIe 40GB] (rev a1)
        Subsystem: NVIDIA Corporation Device 145f
        Physical Slot: 0-2
        Flags: fast devsel, IRQ 11, NUMA node 0, IOMMU group 10
        Memory at fd000000 (32-bit, non-prefetchable) [disabled] [size=16M]
        Memory at 6000000000 (64-bit, prefetchable) [disabled] [size=64G]
        Memory at 5280000000 (64-bit, prefetchable) [disabled] [size=32M]
        Capabilities: <access denied>
```

**Comment by soulseen** [comment]
> @soulseen @Bevisy Can you also share the PCIe Root Port `Region`, I am thinking of a boundary condition that may arise here.
> 
> In the guest not in the container to "see" the complete PCIe config space.
> 
> ```
> [~]$ sudo kata-runtime exec arch
> root@r750-206:/# lspci | grep Root
> 00:05.0 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
> 00:06.0 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
> root@r750-206:/# 
> ```
> 

@zvonkok hi, I enabled `pcie_root_port` and rerun in the guest:
```
root@localhost:/# lspci | grep Root
00:05.0 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
00:06.0 PCI bridge: Red Hat, Inc. QEMU PCIe Root port
root@localhost:/# lspci -s 00:05.0 -vvv | grep '\[size='
	Region 0: Memory at fea02000 (32-bit, non-prefetchable) [size=4K]
	I/O behind bridge: 00001000-00001fff [size=4K]
	Memory behind bridge: fa800000-fe7fffff [size=64M]
	Prefetchable memory behind bridge: 00000061a0000000-00000061bfffffff [size=512M]
```
> With the current implementation it should be `00:05.0`
> 
> `lspci -s 00:05.0 -vvv | grep '\[size='`

and using latest code still failed.

**Comment by zvonkok** [comment]
@soulseen Please also run a 

`dmesg | grep BAR`

**Comment by soulseen** [comment]
@zvonkok 8 GPUs

**Comment by zvonkok** [comment]
@soulseen Can you ping me on Kata's Slack, handle is `@zvonkok`. This might be easier since  the turnaround times are much faster.

**Comment by zvonkok** [comment]
@soulseen Do you have resizable BARs enabled on your system?

**Comment by soulseen** [comment]
> @soulseen Can you ping me on Kata's Slack, handle is `@zvonkok`. This might be easier since the turnaround times are much faster. Might be already too late for you. We can start the debugging session tomorrow morning, just ping me so I have your handle and as soon as I start working I can ping you back. I am in CET.

@zvonkok I can't join the Kata's Slack, because the slack link https://github.com/kata-containers/community#join-us is invalid, can you give me a new link? thanks

**Comment by zvonkok** [comment]
@jodh-intel @fidencio PTAL @soulseen is not able to join.

**Comment by soulseen** [comment]
@zvonkok hi, I used `GeForce RTX 2080 Ti` which is not supported resizable BARs. or can this problem be solved in other ways?

**Comment by zvonkok** [comment]
https://join.slack.com/t/katacontainers/shared_invite/zt-16w1u6usn-sK871qbMxVN8KsCP5Gr56A @soulseen for the joining slack

**Comment by zvonkok** [comment]
@fidencio We have fixed @Bevisy corner-case and @soulseen is also now running a GPU Kata container. We will keep his issues open since they are not related to this PR. I will create some follow-up PRs to mitigate the situation they have encountered.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @zvonkok!

**Pull request merged**
