### PR TITLE
ci: guest-components without sudo

### PR DESCRIPTION
**Pull request by zvonkok**
Build guest-components without sudo docker this is not needed. This is part 2 of N

### CODE REVIEW

**Comment by zvonkok** [comment]
```
❯ ls -l build/coco-guest-components/{builddir,destdir} 
build/coco-guest-components/builddir:
total 6388
-rw-r--r--  1 root    root        107 May 28 08:56 coco-guest-components-sha256sum
drwxr-xr-x 10 zvonkok zvonkok    4096 May 28 08:56 guest-components
-rw-r--r--  1 root    root    6533060 May 28 08:56 kata-static-coco-guest-components.tar.xz
```
The final tarball and hashsum is not owned by the user since we're doing it with `sudo` in kata-deploy-binaries.sh. Once we have all parts build without sudo the final tarball should be owned by the user as well.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @zvonkok!

**Review by BbolroC — APPROVED** [review]
LGTM, thanks @zvonkok !

**Pull request merged**
