### PR TITLE
gha: Keep kata tarballs for 15 days

### PR DESCRIPTION
**Pull request by ldoktor**
these tarballs are useful for debugging and re-running jobs, keep them for 15 days.

Fixes: #8000

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @ldoktor!

**Review by gkurz — APPROVED** [review]
LGTM. Thanks @ldoktor !

**Comment by ldoktor** [comment]
Big thanks to @fidencio who provided the link to docs on what to change ;-)

**Comment by gkurz** [comment]
I see no reason we wouldn't want that as well in stable so I'll add the `needs-backport` label.

**Comment by ldoktor** [comment]
@gkurz is the backport on me (and which branches) or is it a maintainer's job?

**Comment by gkurz** [comment]
> @gkurz is the backport on me (and which branches) or is it a job for maintainers?

We only have one stable branch at a time, currently it is `stable-3.2`. This job can be done by developers. Please go ahead @ldoktor :smile:

**Pull request merged**
