### PR TITLE
WIP: test 1.7 containerd with CC

### PR DESCRIPTION
**Pull request by stevenhorsman**
test 1.7 containerd with CC

Signed-off-by: stevenhorsman <steven@uk.ibm.com>

### CODE REVIEW

**Comment by stevenhorsman** [comment]
The thing worth noting here is that all the tests passed despite us installing an upstream version of containerd. I think this means that the images are still being pulled on the host and therefore 'not confidential'. I've raised https://github.com/kata-containers/tests/issues/5410 to cover adding this check and hopefully after that we'd see and expected failure here.

**Comment by fidencio** [comment]
The reason the tests are passing is because we're, for some reason, still installing the correct forked version of containers.  See:
```
23:10:14 INFO: Install cri-containerd
23:10:14 Set up environment
23:10:14 Trying to install containerd from static tarball
23:10:14 Download tarball from https://github.com/confidential-containers/containerd/releases/download/v1.6.8.1/cri-containerd-cni-1.6.8.1-linux-amd64.tar.gz
23:10:14   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
23:10:14                                  Dload  Upload   Total   Spent    Left  Speed
23:10:14 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
23:10:15 
 97  122M   97  120M    0     0   107M      0  0:00:01  0:00:01 --:--:--  107M
100  122M  100  122M    0     0   108M      0  0:00:01  0:00:01 --:--:--  340M
```

**Comment by fidencio** [comment]
Let me debug why this is happening, though.

**Comment by stevenhorsman** [comment]
> The reason the tests are passing is because we're, for some reason, still installing the correct forked version of containers. 

Yeah - sorry - I thought I'd already added an update to state this was the problem, but obvious didn't manage to save the comment. I know if the kata-container repo isn't found it checks out the default_branch, to get the version, but given that we're testing the kata-containers with this PR I'd expect it to have that directory. I have a few other bits of debug in https://github.com/kata-containers/tests/pull/5418 as well if we need to test any changes in tests repo.

**Comment by stevenhorsman** [comment]
I've rebased this on main and going to check to see if the problem with version not getting picked up is specific to `CCv0` fork or not /test-ubuntu

**Comment by stevenhorsman** [comment]
The good news is that the version update seems to be fine for main:
```
INFO: Install cri-containerd
Set up environment
Trying to install containerd from static tarball
Download tarball from https://github.com/containerd/containerd/releases/download/v1.7.0-beta.3/cri-containerd-cni-1.7.0-beta.3-linux-amd64.tar.gz
```
The test did fail with:
```
+ bin/cri-integration.test
# github.com/containerd/containerd/integration [github.com/containerd/containerd/integration.test]
integration/container_restart_test.go:28:3: undefined: pauseImage
make[1]: *** [Makefile:220: bin/cri-integration.test] Error 2
```
but that's not too surprising and out of scope for this.

It looks like the problem is specific to the CCv0 target branch, so I'll switch back to that and try and look into it some more when I get the chance

**Comment by stevenhorsman** [comment]
Resolved in https://github.com/kata-containers/tests/pull/5432

**Pull request closed without merging**
