### PR TITLE
dbs-pci: introduce Cargo.lock to prevent the influence from upstream

### PR DESCRIPTION
**Pull request by studychao**
As reported in #8767, we have found that the root cause is that rust-vmm's vmm-sys-utils introduce a new release 0.12.1 and dbs-pci rely on rust-vmm's vfio-ioctls which uses >= to declare vmm-sys-utils so it automatically upgrade vmm-sys-utils to 0.12.1. That's how two different versions of vmm-sys-utils is introduced and this breaks the compilation.

In order to fix this and also avoid future problems, we introduce Cargo.lock file to dbs crates.

fixes: #8770

### CODE REVIEW

**Review by justxuewei — APPROVED** [review]
Lgtm, thanks!

**Review by danmihai1 — APPROVED** [review]

**Comment by danmihai1** [comment]
I agree, let's try https://github.com/kata-containers/kata-containers/pull/8771 instead.

**Comment by danmihai1** [comment]
Sorry, I closed this one by mistake. Thanks for re-opening it.

**Pull request merged**
