### PR TITLE
versions: kernel 5.10.x

### PR DESCRIPTION
**Pull request by jcvenegas**
Linux 5.10.x is the new LTS branch, move
kata to a more recent kernel branch.

Fixes: #1288
Depends-on: github.com/kata-containers/tests#3363
Signed-off-by: Carlos Venegas <jos.c.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by jcvenegas** [comment]
Hi @jongwu, I created a new PR to bump to the new Linux LTS. I see ARM CI failing, the patches for ARM does not apply anymore. Is there a place we can take the patches for 5.10.x  ?

**Comment by jongwu** [comment]
Thanks @jcvenegas ,  As memory hotplug has enabled in kernel 5.10, I think there is no such patch needed. It's something new that blocks the ci. I'm trying to fix it.

**Comment by jongwu** [comment]
hello @jcvenegas. I have found the root cause. It derived from memory range check in arch_add_memory at arch/arm64/mm/mmu.c 
`int arch_add_memory(int nid, u64 start, u64 size,
                    struct mhp_params *params)
{
        int ret, flags = 0;

if (!inside_linear_region(start, size)) {
		pr_err("[%llx %llx] is outside linear mapping region\n", start, start + size);
		return -EINVAL;
	}
.....`

but in the newest kernel, it has been substituted by:
`VM_BUG_ON(!mhp_range_allowed(start, size, true));`
see patch https://patchwork.kernel.org/project/linux-mm/patch/1610975582-12646-3-git-send-email-anshuman.khandual@arm.com/
So you can add this patch under 5.10 to see if the error gone.

**Comment by jcvenegas** [comment]
hi @jongwu, I have applied the patch but seems the issue is still there. Please let me know anything else we could do.

**Comment by jongwu** [comment]
sorry @jcvenegas -,  it seems the patch doesn't change the original logic. I think this memory range check code is the direct cause of that failure. so there is a workaround of removing that check to let the ci pass. we can take it to let it go. I will find the root cause and fix it later.

**Comment by jcvenegas** [comment]
@jongwu  I have added logic to keep using 5.4.x in ARM until find the boot issues.

**Review by GabyCT — APPROVED** [review]

**Review by likebreath — APPROVED** [review]

**Pull request merged**
