### PR TITLE
CC | static checks workflow improvements

### PR DESCRIPTION
**Pull request by jepio**
Cherry-pick of:
- #6406 

so that we can get the same fix for out-of-space errors in the CI.

Depends on:
- kata-containers/tests#5532

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jepio!

**Comment by fidencio** [comment]
`make-kata-tarball` is failing as the disk is out of space, this is worrisome but doesn't seem related to this PR at all.
@jepio, can you also open an issue for this and we take a look at this later on?  Feels like the size of some components may have increased without us noticing that.

**Comment by jepio** [comment]
@stevenhorsman I saw you restarted the make-kata-tarball job, but i'd need to rebase to actually pick up #6491

**Comment by stevenhorsman** [comment]
> @stevenhorsman I saw you restarted the make-kata-tarball job, but i'd need to rebase to actually pick up #6491

Sorry about that - I meant to message you about rebasing first, but got distracted by something else and skipped that step. Whenever you are ready we can rebase and re-run the tests and hopefully they will all go green 🤞

**Comment by jepio** [comment]
Closing this PR, replaced by #6503.

Sharing a branch for 2 PRs targeting main and CCv0 did not work out as well as I expected...

**Pull request closed without merging**
