### PR TITLE
gha: ci: Revert tracing test PR to unbreak CI

### PR DESCRIPTION
**Pull request by sprt**
This unbreaks CI as seen in https://github.com/kata-containers/kata-containers/actions/runs/6434757133

Fixes: #8161

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @sprt!

**Review by GabyCT — APPROVED** [review]

**Review by bergwolf — APPROVED** [review]
I'm wondering why CI didn't catch it when https://github.com/kata-containers/kata-containers/pull/8115 was merged. @fidencio Any clue?

**Comment by fidencio** [comment]
> I'm wondering why CI didn't catch it when #8115 was merged.

That's because the `pull_request_target` event is not able to test the yaml changes in the PR. :-/.
I'll bypass the checks and get this one merged right now.

**Pull request merged**
