### PR TITLE
experimentally enable the vcpu-hotplug for arm in qemu side

### PR DESCRIPTION
**Pull request by zyzii**
Enable the vcpu-hotplug with the patches (most patch are from Salil Mehta).

Signed-off-by: Huang Shijie <shijie8@gmail.com>

### CODE REVIEW

**Comment by jongwu** [comment]
thanks @zyzii

**Comment by jongwu** [comment]
Hello @devimc @fidencio -, take a look at this.

**Review by jodh-intel — APPROVED** [review]
Thanks @zyzii.

lgtm

**Comment by jodh-intel** [comment]
@jongwu - could you tal at this please?

**Review by jongwu — APPROVED** [review]

**Comment by jongwu** [comment]
thanks @jodh-intel

**Comment by jodh-intel** [comment]
@zyzii - the Commit Message check is failing:

```
Error: 

  ebfb644f3cea709f39b58123f19369b1b11995a0    Failed to find subsystem in subject

See the document below for help on formatting commits for the project.

https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format
```

To resolve this, you need to:

- add a subsystem to the start of the first line of the commit (something like `packaging:`).
- Add a "Fixes #xxx` comment as shown in the URL above where `xxx` is the number of a GitHub issue you have raised for this PR work.

**Pull request merged**
