### PR TITLE
agent: Add config file option to cli

### PR DESCRIPTION
**Pull request by stevenhorsman**
- Add option to pass in config with -c/--config

Fixes: #3252

Signed-off-by: stevenhorsman <steven@uk.ibm.com>

### CODE REVIEW

**Comment by stevenhorsman** [comment]
This is the native version of #3253 which I couldn't get to work on all platforms.

A unit test was provided, but there are currently no integration tests for the kata-agent, so I've done manual testing in which I created a sample config file with:
```
cat << EOT | tee agent_config.toml
# This is an agent configuration file example.
dev_mode = true
server_addr = 'unix://@/tmp/foo.socket'

[endpoints]
allowed = [ "CreateContainer", "RemoveContainer", "AddSwap"]
EOT
```

The behaviour of the standalone kata-agent is as follows (killing the process after the announce once the configuration has been created):
- With no config option specified to the agent the behaviour is unchanged:
```
target/x86_64-unknown-linux-musl/release/kata-agent
```
results in:
```
{"msg":"announce","level":"INFO","ts":"2021-12-13T09:41:15.573681172-08:00","source":"agent","pid":"478384","subsystem":"root","version":"0.1.0","name":"kata-agent","agent-commit":"2.4.0-alpha0-ff572fa2192c051246c5bccb29c968ac597b5360-dirty","agent-version":"2.4.0-alpha0","config":"AgentConfig { debug_console: false, dev_mode: false, log_level: Info, hotplug_timeout: 3s, debug_console_vport: 0, log_vport: 0, container_pipe_size: 0, server_addr: \"vsock://-1:1024\", unified_cgroup_hierarchy: false, tracing: false, endpoints: AgentEndpoints { allowed: {}, all_allowed: true }, supports_seccomp: true }","api-version":"0.0.1","agent-type":"rust"}
```
  All config parameters have their default values.
- With the `--config <config_file>` option specified to the agent:
```
target/x86_64-unknown-linux-musl/release/kata-agent --config ./agent_config.toml
```
results in:
```
{"msg":"announce","level":"INFO","ts":"2021-12-13T09:40:59.413175186-08:00","pid":"478331","subsystem":"root","source":"agent","name":"kata-agent","version":"0.1.0","agent-version":"2.4.0-alpha0","agent-type":"rust","api-version":"0.0.1","config":"AgentConfig { debug_console: false, dev_mode: true, log_level: Info, hotplug_timeout: 3s, debug_console_vport: 0, log_vport: 0, container_pipe_size: 0, server_addr: \"unix://@/tmp/foo.socket\", unified_cgroup_hierarchy: false, tracing: false, endpoints: AgentEndpoints { allowed: {\"CreateContainer\", \"RemoveContainer\", \"AddSwap\"}, all_allowed: false }, supports_seccomp: true }","agent-commit":"2.4.0-alpha0-ff572fa2192c051246c5bccb29c968ac597b5360-dirty"}
```
  Note the `server_addr`, `dev_mode` and `endpoints` are correctly read from the config file.
- With the `-config <config_file>` short option specified to the agent:
```
target/x86_64-unknown-linux-musl/release/kata-agent -c ./agent_config.toml
```
results in:
```
{"msg":"announce","level":"INFO","ts":"2021-12-13T09:40:36.807326956-08:00","name":"kata-agent","subsystem":"root","version":"0.1.0","source":"agent","pid":"478280","api-version":"0.0.1","config":"AgentConfig { debug_console: false, dev_mode: true, log_level: Info, hotplug_timeout: 3s, debug_console_vport: 0, log_vport: 0, container_pipe_size: 0, server_addr: \"unix://@/tmp/foo.socket\", unified_cgroup_hierarchy: false, tracing: false, endpoints: AgentEndpoints { allowed: {\"CreateContainer\", \"RemoveContainer\", \"AddSwap\"}, all_allowed: false }, supports_seccomp: true }","agent-commit":"2.4.0-alpha0-ff572fa2192c051246c5bccb29c968ac597b5360-dirty","agent-version":"2.4.0-alpha0","agent-type":"rust"}
```
  Again `server_addr`, `dev_mode` and `endpoints` are correctly read from the config file.
- With the `-config <non existing file>` option specified to the agent the behaviour is the same as when a non-existing file is passed through the guest image `kernel_parms`:
```
target/x86_64-unknown-linux-musl/release/kata-agent --config junk
```
results in:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', src/main.rs:83:75
stack backtrace:
...
```
- With the `-config` (ie no file) specified to the agent:
```
target/x86_64-unknown-linux-musl/release/kata-agent --config
```
results in:
```
thread 'main' panicked at 'The config argument wasn't formed properly: ["target/x86_64-unknown-linux-musl/release/kata-agent", "--config"]', src/config.rs:204:17
stack backtrace:
...
```

**Review by liubin — APPROVED** [review]

**Comment by stevenhorsman** [comment]
@sameo - Hey Samuel, I had a bunch of issue using the `clap` crate as some of the dependencies it dragged in (~120 it seems 😮) didn't work on all our platforms (specifically `s390x` and ARM), so I switched to use this native implementation.  If that is merged then I'm happy to try the refactor use `clap` later once v3 has properly released and see if the situation is better then. Let me know what you think. Thanks!

**Comment by Jakob-Naucke** [comment]
> I had a bunch of issue using the `clap` crate as some of the dependencies it dragged in (~120 it seems :open_mouth:)

I count 268 to 286 for the agent, which is 18. (Not exactly few, but not uncommon in Rust...)

> didn't work on all our platforms (specifically `s390x` and ARM)

This is because of https://github.com/kata-containers/tests/issues/4179, which should be fixed.

> so I switched to use this native implementation. If that is merged then I'm happy to try the refactor use `clap` later once v3 has properly released and see if the situation is better then.

Waiting for an official release might be a good reason to withhold, although it's not a huge deal IMO (we happily use many [zero-versioned](https://0ver.org/) projects...)

**Comment by stevenhorsman** [comment]
> I count 268 to 286 for the agent, which is 18. (Not exactly few, but not uncommon in Rust...)

Sorry, as you suspected I was comparing the number of crates from a different module. I'll edit the above post to remove the error. Thanks!

**Comment by stevenhorsman** [comment]
Thanks for the extra info Jakob. I think the best approach is probably to get this native version merged, then once rust has updated on `s390x` and ARM I can try out clap again and get the benefit of the generated help.

**Review by dgibson — COMMENTED** [review]
Looks fine in terms of implementation.  Obivously it might be obsoleted if a proper clap version is working.

**Comment by stevenhorsman** [comment]
@dgibson - if you are happy to approve then I think the best approach, in terms of keeping changes small and because there are still potential issues with rust versions and the clap implementation in #3252, is to get this merged, re-base the other PR and try and deal with the extra complications that are in there separately. Does that sound reasonable?

**Pull request merged**
