### PR TITLE
osbuilder: Remove suse rootfs-builder

### PR DESCRIPTION
**Pull request by fidencio**
As the suse rootfs is not tested in our CI, we can't guarantee it
actually works as expected.

Whenver we have someone willing to maintain this rootfs we can have it
added back, and also add a CI job to test it altogether, avoiding then
any possible regression.

Fixes: #2145

Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

### CODE REVIEW

**Comment by Jakob-Naucke** [comment]
In the spirit of https://github.com/kata-containers/tests/pull/3658, I had wanted to use this in an SLE CI at a later date. I have no strong opinion on keeping it though.

**Review by GabyCT — APPROVED** [review]

**Comment by jodh-intel** [comment]
@fidencio - could you rebase to resolve the conflict?

**Comment by fidencio** [comment]
This got superseded by https://github.com/kata-containers/kata-containers/pull/3420

**Pull request closed without merging**
