### PR TITLE
rustjail: optimization, merged several writelns into one

### LINKED ISSUE #3772: optimize: multiple writeln can be simplify by one
from

https://github.com/kata-containers/kata-containers/blob/2fc7f75724ac9e18e60f63dcc9aa395dc51c184d/src/agent/rustjail/src/utils.rs#L99-L105

to 

```rust
let data = r#"
root:x:0:0:root:/root0:/bin/bash
root:x:1:0:root:/root1:/bin/bash
...
"#;

writeln!(tempf, data).unwrap(); 
```

### PR DESCRIPTION
**Pull request by Shensd**
Optimized several writelns by merging them into one in src/utils.rs

Fixes #3772 

Signed-off-by: Jack Hance <jack.hance@ndsu.edu>

### CODE REVIEW

**Review by gkurz — CHANGES_REQUESTED** [review]
Hi @Shensd !

Contribution guidelines require each commit to have a proper changelog and Signed-off-by.
e.g.

```
rustjail: optimization, merged several writelns into one 

Optimized several writelns by merging them into one in src/utils.rs

Fixes: #3772
Signed-off-by: Jack Hance <jack.hance@ndsu.edu>
```

Appart from that, the change looks good.

**Comment by jodh-intel** [comment]
Thanks for raising @Shensd ! This looks good and just needs a tweak to the commit as @gkurz mentions. That will keep the "Commit Message Check" happy.

---

Aside:

It might seem excessive having to provide a summary _and_ a description for every commit (https://xkcd.com/1296 maybe? :), even when the change is simple. But since the summary is by nature very terse,  it could be pretty cryptic, particularly if you are new to the project, new to the programming language, or indeed if English is not your native language.

Honestly, the description has saved us so many times in the past. Aside from expanding on the summary (ideally using different words to do so), the description might include additional information such as:

- why this change is actually necessary (we see so many PRs which tell us _what_ is being changed, but no rationale)
- how the bug was identified (tooling? manual code review?)
- any additional contributors.
- links to reference material.
- how to recreate the bug.
- _etc_.

Again, the "fixes" issue might seem overkill, but it protects against the scenario where multiple people work on _the same PR_ without knowing it (and yes, this has happened... multiple times!). By raising an issue on the problem and getting it assigned to yourself, you have "priority" in the case where we have overlapping PRs ;)

**Comment by Shensd** [comment]
I have added the changelog and sign-off to the commit, apologies for missing that the first time around!

**Review by gkurz — APPROVED** [review]
LGTM. Thanks @Shensd !

**Review by jodh-intel — APPROVED** [review]
Thanks @Shensd !

lgtm

**Pull request merged**
