### PR TITLE
osbuilder: Remove gentoo rootfs-builder

### PR DESCRIPTION
**Pull request by fidencio**
As the gentoo rootfs is not tested in our CI, we can't guarantee it
actually works as expected.

Whenever we have someone willing to maintain this rootfs we can have it
added back, and also add a CI job to test it altogether, avoiding then
any possible regression.

Fixes: #2144

Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

### CODE REVIEW

**Review by Jakob-Naucke — CHANGES_REQUESTED** [review]
@fidencio I think this applies to the whole bunch you've raised, please check `tools/osbuilder/rootfs-builder/rootfs.sh` for references to these distros and remove them.
e: a great deal of those might be host distros, sorry

**Comment by Jakob-Naucke** [comment]
@fidencio oh, and the compatibility matrix. Best to just do a bit of `grep`ping :)

**Review by GabyCT — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Thanks @fidencio.

lgtm, although it needs a rebase.

**Comment by jodh-intel** [comment]
@fidencio - ah - yeah, as @Jakob-Naucke says, we do need the doc updates too ;)

**Comment by fidencio** [comment]
This got superseded by https://github.com/kata-containers/kata-containers/pull/3420

**Pull request closed without merging**
