### PR TITLE
Added a glossary of terms 

### PR DESCRIPTION
**Pull request by hspease99**
I added a glossary to support SEO tactics. The terms added are: Kata
Containers, container software, container runtime interface, virtual
machine software, container virtualization, container security
solutions, serverless containers, pod containers, virtual machine
monitor, private cloud, infrastructure architecture, public cloud,
and auto scaling.

Fixes: #1509

Signed-off-by: Helena Spease <helena@openstack.org>

### CODE REVIEW

**Comment by fidencio** [comment]
@hspease99, could you take a look at https://github.com/kata-containers/kata-containers/pull/1515/checks?check_run_id=2114234313 ?

There it says the commit requires a subsystem, which I'd suggest being "docs" (ex: "docs: Add glossary of terms").

After that, please, squash all the commits, rebase atop of current main, and update the PR.

Thanks a lot for the contribution, looking forward to the second iteration!

**Comment by ariel-adam** [comment]
@hspease99 any updates on this PR :-)?

**Comment by jodh-intel** [comment]
Hi @hspease99 - are you planning to continue working on this PR? If not, shall we close it?

**Comment by pmores** [comment]
@jodh-intel @fidencio Do we want this change? The original contributor is apparently gone but I'd be happy to update and resubmit the PR for them.

**Comment by jodh-intel** [comment]
Hi @pmores - thanks for the offer! I think it would be a good idea. A few thoughts:

- We used to have an "assisted PR process" defined in the contributing guide, but it got dropped. However, this is an instance where it could be useful, so I've created a wiki page that summarises the process we used to use: https://github.com/kata-containers/community/wiki/Assisted-PR-process.
- You will undoubtably have to update the Kata spell checking dictionary for this PR. Thankfully, this is easy and documented here: https://github.com/kata-containers/tests/tree/main/cmd/check-spelling#adding-a-new-word. You can run that spelling tool locally before you raise a PR to ensure you've added all new words/terms.
- You could do what we've done a few times in the past and convert this doc (temporarily) into a wiki page. You could then advertise that it exists on the ML/slack/etc, start hacking the wiki page along with the other contributors, then after a couple of weeks, convert the wiki page into a PR, then delete the contents of the wiki page and paste in a link to the "in-tree" version of the document.

**Comment by pmores** [comment]
@hspease99 

Thank you for your contribution but we are unable to merge it until all review feedback has been applied and all CI checks have passed.

Since we have not heard from you for a while, we assume you are unable to progress this PR. As such, we intend to create a new PR based on this one, and resolve the identified issues on the new PR. The new PR will reference this PR for tracking purposes.

This PR will be marked do-not-merge and will be closed when our new PR has been merged. We will credit all authors of this PR on the new PR.

**Comment by pmores** [comment]
The "assisted" PR is here: https://github.com/kata-containers/kata-containers/pull/2272

**Comment by pmores** [comment]
The assisted PR mentioned above was merged, closing this one as per Assisted PR Process.

**Pull request closed without merging**
