### PR TITLE
tests: Fix missing log on TDX

### PR DESCRIPTION
**Pull request by ChengyuZhu6**
Currently, we have found that `assert_logs_contain` does not work on TDX. We manually located the specific log, but it fails to get the log using `kubectl debug`. The error found in CI is:
```
warning: couldn't attach to pod/node-debugger-984fee00bd70.jf.intel.com-pdgsj,
falling back to streaming logs: error stream protocol error: unknown error
```

Upon debugging the TDX CI machine, we found an error in containerd:
```
Attach container from runtime service failed" err="rpc error: code = InvalidArgument desc = tty and stderr cannot both be true"
containerID="abc8c7a546c5fede4aae53a6ff2f4382ff35da331bfc5fd3843b0c8b231728bf"
```

We believe this is the root cause of the test failures in TDX CI. Therefore, we need to ensure that tty and stderr are not set to true at same time.

Fixes: #10011

### CODE REVIEW

**Review by arronwy — APPROVED** [review]
Thanks @ChengyuZhu6 LGTM!

**Review by stevenhorsman — APPROVED** [review]
The non-TEE tests are still working, so LGTM. Thanks!

**Comment by wainersm** [comment]
Cool!

@ChengyuZhu6 would make sense to enable [k8s-guest-pull-image-authenticated.bats](https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats#L16) on TDX as part of this PR? This way we can "see" the fix working.

**Review by GabyCT — APPROVED** [review]

**Comment by GabyCT** [comment]
@ChengyuZhu6 I tried to enable the [k8s-guest-pull-image-authenticated.bats](https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats#L16) on the TDX with your changes but I see that the failure is still there `assert_logs_contain "${node}" kata "${node_start_time}" "failed to pull manifest Not authorized"' failed`

**Comment by ChengyuZhu6** [comment]
> Cool!
> 
> @ChengyuZhu6 would make sense to enable [k8s-guest-pull-image-authenticated.bats](https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats#L16) on TDX as part of this PR? This way we can "see" the fix working.

Done.

**Comment by ChengyuZhu6** [comment]
> @ChengyuZhu6 I tried to enable the [k8s-guest-pull-image-authenticated.bats](https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/k8s-guest-pull-image-authenticated.bats#L16) on the TDX with your changes but I see that the failure is still there `assert_logs_contain "${node}" kata "${node_start_time}" "failed to pull manifest Not authorized"' failed`

Hi @GabyCT thanks for your feedback.  I debugged the TDX machine and found that the log during the test exceeded 100000 entries. I have removed the limit of journal entries, so the tests can now run on TDX. cc @stevenhorsman @arronwy @wainersm

**Comment by BbolroC** [comment]
I've confirmed that the PR also fixes the same issue on IBM SE. Thanks!

**Pull request merged**
