### PR TITLE
osbuilder: don't pull ubuntu image from dockerhub

### LINKED ISSUE #2461: Avoid building the image using a docker ubuntu image
We hit an issue with using an ubuntu docker image on a recent CI
```
22:07:39 Step 1/6 : ARG IMAGE_REGISTRY=docker.io
22:07:39 Step 2/6 : FROM ${IMAGE_REGISTRY}/ubuntu:20.04
22:07:40 20.04: Pulling from library/ubuntu
22:07:40 toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
22:07:40 Makefile:93: recipe for target '/home/jenkins/workspace/go/src/github.com/kata-containers/kata-containers/tools/osbuilder/.ubuntu_rootfs.done' failed
```
/cc @devimc @Jakob-Naucke @fidencio @jcvenegas

### PR DESCRIPTION
**Pull request by devimc**
Pull ubuntu image from public.ecr.aws/ubuntu to fix dockerhub rate
limit issue.

fixes #2461

cc @GabyCT  @Jakob-Naucke 

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by Jakob-Naucke** [comment]
@devimc public.ecr.aws/ubuntu is not built for ppc64le, also there is a rate limit of 1 pull per second that I have seen before (I think that CI run is rotated out though) https://github.com/kata-containers/kata-containers/issues/2461#issuecomment-900988403 https://docs.aws.amazon.com/AmazonECR/latest/public/public-service-quotas.html

**Comment by GabyCT** [comment]
@devimc @Jakob-Naucke so we will need to use `quay.io` images even if they are not updated frequently

**Comment by devimc** [comment]
@Jakob-Naucke @GabyCT we should use quay.io only for testing, `not update frequently` is equal to CVEs, so I suggest is to set `IMAGE_REGISTRY="quay.io/libpod"` only in those jobs where the image used to build the rootfs is available in `quay.io/libpod`

**Comment by Jakob-Naucke** [comment]
@devimc i.e. use it in tests, but not in anything that might be distributed, e.g. osbuilder?

**Comment by devimc** [comment]
> @devimc i.e. use it in tests, but not in anything that might be distributed, e.g. osbuilder?

right, btw quay.io/libpod will not work, @GabyCT  tested it and she got the following error:

```
 manifest for quay.io/libpod/ubuntu:20.04 not found: manifest unknown: manifest unknown
```

so, @Jakob-Naucke  what do you think ?

**Comment by Jakob-Naucke** [comment]
> ```
>  manifest for quay.io/libpod/ubuntu:20.04 not found: manifest unknown: manifest unknown
> ```

yes, they only have `latest`, which is 20.04.
> so, @Jakob-Naucke what do you think ?

Since we were already talking AWS... Google's `mirror.gcr.io` also exists. Chris Evich of Red Hat told me it's "lacking real multi-arch support", although it worked fine for me on s390x so far, and the other architectures seem to be built too.

**Comment by GabyCT** [comment]
I am not expert into this topic but is there a particular reason why we need Ubuntu? or can we use another image?

**Comment by Jakob-Naucke** [comment]
> I am not expert into this topic but is there a particular reason why we need Ubuntu? or can we use another image?

@GabyCT for osbuilder, we support a bunch of distros mostly for diversity reasons, I guess. However, we use Ubuntu in a bunch of places that could be migrated to `registry.fedoraproject.org/fedora`:

```
$ grep -Eri "(^| )(FROM|image:) ubuntu"
kata-containers/src/runtime/vendor/golang.org/x/net/http2/Dockerfile:FROM ubuntu:trusty
kata-containers/tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile:FROM ubuntu
kata-containers/tools/packaging/static-build/qemu/Dockerfile:from ubuntu:20.04
kata-containers/tools/packaging/static-build/kernel/Dockerfile:FROM ubuntu
kata-containers/tools/packaging/static-build/shim-v2/Dockerfile:FROM ubuntu
tests/metrics/network/iperf_dockerfile/Dockerfile:FROM ubuntu:16.04
tests/metrics/network/nuttcp_dockerfile/Dockerfile:FROM ubuntu
tests/metrics/storage/fio_dockerfile/Dockerfile:FROM ubuntu
tests/metrics/storage/fio-k8s/configs/example-config/kata.yaml:    image: ubuntu:latest
tests/metrics/storage/fio-k8s/configs/example-config/runc.yaml:    image: ubuntu:latest
tests/metrics/storage/fio-k8s/configs/test-config/kata.yaml:    image: ubuntu:latest
tests/metrics/storage/fio-k8s/configs/test-config/runc.yaml:    image: ubuntu:latest
tests/metrics/storage/web-tooling-dockerfile/Dockerfile:FROM ubuntu:latest
```

**Comment by GabyCT** [comment]
maybe we can start by moving it on building the image

**Pull request closed without merging**
