### PR TITLE
network: Fix network attach for ipvlan and macvlan

### PR DESCRIPTION
**Pull request by amshinde**
We used the approach of cold-plugging network interface for pre-shimv2 support for docker.Since the hotplug approach was not required, we never really got to implementing hotplug support for certain network endpoints, ipvlan and macvlan being among them.

Since moving to shimv2 interface as the default for runtime, we switched to hotplugging the network interface for supporting docker and nerdctl. This was done for veth endpoints only.

Implement the hot-attach apis for ipvlan and macvlan as well to support ipvlan and macvlan networks with docker and nerdctl.

Fixes: #8333

### CODE REVIEW

**Comment by amshinde** [comment]
Follow-up for this PR would be to add a test with nerdtcl for ipvlan and macvlan networking.

**Comment by amshinde** [comment]
cc @fidencio

**Review by fidencio — APPROVED** [review]
lgtm, thanks @amshinde!

@Greatsamps has given it a try and it seems to work as expected on his setup!

**Review by dborquez — APPROVED** [review]
LGTM, thank you @amshinde

**Pull request merged**
