### PR TITLE
kernel: Enable OVERLAY_FS_{METACOPY,XINO_AUTO}

### PR DESCRIPTION
**Pull request by fidencio**
* CONFIG_OVERLAY_FS_METACOPY is needed to have reasonable performance
  for chmod and similar calls;
* CONFIG_OVERLAY_FS_XINO_AUTO is recommended for POSIX compliance.

Fixes: #1075

Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>

### CODE REVIEW

**Comment by fidencio** [comment]
@snir911, @c3d, do you happen to have an ack to spare on this one?

**Review by snir911 — APPROVED** [review]

**Comment by snir911** [comment]
Hi @egernst, could you share your thoughts on this one, IIUC overlay was added to support DinD (https://github.com/kata-containers/packaging/pull/716) however DinD [won't work if overlay is used](https://github.com/kata-containers/runtime/issues/2493#issuecomment-593492160).
Hence, I was wondering whether I misunderstood and overlay does work in certain cases or was it enabled for development purposes?

**Review by c3d — APPROVED** [review]
Looks good, but wouldn't it be more robust to modify the code to add the `metacopy=on` and `xino=on` mount options? That way you would get the benefits even with a kernel that does not have the option.

**Pull request merged**
