### PR TITLE
CC | agent: add support for ttrpc + dependency on test PR

### PR DESCRIPTION
**Pull request by jepio**
Ignore this, this is an attempt to run CI on
- #6404
- #6520 
combined with the following tests pr:
- ~kata-containers/tests#5577~ kata-containers/tests#5579

### CODE REVIEW

**Comment by jepio** [comment]
s390x tests failed due to wrong fixtures, pushed a fix and going to re-run those jobs.

**Comment by fidencio** [comment]
TDX tests are now passing.

**Comment by jepio** [comment]
s390x test presumably failing because it's pulling an amd64-only encrypted container image.

**Comment by fidencio** [comment]
Cloud Hypervisor TDX passed but didn't report back: http://10.112.240.208:8080/job/kata-containers-CCv0-cloud-hypervisor-TDX-CRI_CONTAINERD_K8S-PR/820/

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jepio!

**Comment by fidencio** [comment]
I'm removing the `do-not-merge` label as we do want to have this one merged.

**Pull request merged**
