### PR TITLE
Backport/stable-3.0: fix "cargo not found" issue in snap build

### PR DESCRIPTION
**Pull request by jongwu**

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @jongwu.

lgtm

**Comment by jongwu** [comment]
@fidencio @liubin -, mind help TAL this? Thanks!

**Review by liubin — APPROVED** [review]

**Comment by liubin** [comment]
@jongwu you need to fix the conflict.

**Comment by jongwu** [comment]
Seems we don't need this PR as snap build test for #5869 passes.

**Pull request closed without merging**
