### PR TITLE
 kernel: Enabling PTP clock support in kernel

### LINKED ISSUE #587: [forward port]: kernel: Enabling PTP clock support in kernel
Port https://github.com/kata-containers/packaging/pull/1104 (issue https://github.com/kata-containers/packaging/issues/1103) from Kata 1.x.

### PR DESCRIPTION
**Pull request by amshinde**
Allows time synchronization.
    
    Fixes #587

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @amshinde.

**Comment by jongwu** [comment]
@bergwolf @amshinde it's OK for me, as this patch may has not tested on x86. maybe I can repost the ptp_kvm patch for Arm64 later.

**Comment by amshinde** [comment]
@likebreath @jcvenegas @egernst Can you ack this?

**Review by likebreath — APPROVED** [review]

**Pull request merged**
