### PR TITLE
agent: fix almost all warnings

### LINKED ISSUE #101: rust agent source code has many clippy warnings
**Which feature do you think can be improved?**
Quality of source code

**How can it be improved?**
Clean up clippy warnings and simplify code implementation.

**Additional Information**

### PR DESCRIPTION
**Pull request by devimc**
Improve quality of code by fixing almost all warnings, remaining warnings
may need more work/research.

fixes #101

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by fidencio** [comment]
@devimc, have you seen https://github.com/kata-containers/kata-containers/pull/410?
My feeling is that your PR may cover more content than #410, but would be good to re-use #410 patches.

**Comment by devimc** [comment]
@fidencio ouch! I didn't see that PR :-(
@sameo are you still working on that?

**Comment by jodh-intel** [comment]
@devimc - #410 is blocked on #411 (which is blocked ;).

I think we should land either @sameo's PR (without the changes that make it block on #411), or your PR (you can fight it out amongst yourselves :smile:) as #411 won't be landing this week.

**Comment by devimc** [comment]
closing -  see https://github.com/kata-containers/kata-containers/pull/410

**Pull request closed without merging**
