### PR TITLE
# Kata Containers 2.0.4

### PR DESCRIPTION
**Pull request by fidencio**
- [backport] runtime: fix static check errors
- [backport] versions: Upgrade to cloud-hypervisor v15.0
- qemu: kill virtiofsd if failure to start VMM
- docs: Document limitation regarding subpaths
- Makefile: Replace @RUNTIME_NAME@ with the target in generated files
- runtime: handle io.katacontainers.config.hypervisor.virtio_fs_extra_args

3d33250e agent: Wrong pid method used
afe4df04 agent: Fix compiler checks
f859f8af agent: Fixes for static and compiler checks
657d7552 agent: simplify ttrpc error construction
7d96f22b ci: add `cargo clippy` for agent
2f67e831 agent: fix clippy for rustc 1.5
4f9b5faf agent: clear match_like_matches_macro/vec_resize_to_zero warnings
974e0e3b agent: clear module_inception/type_complexity warnings
91e12404 agent: clear clippy warnings
02aaab22 agent: clear clippy `len_zero` warnings
165988a3 rustjail: clear clippy warnings
9d49a69f oci: clear clippy warnings
cab530cb agent: clear redundant_field_names clippy warning
8d16767b logging: clear clippy warnings
01b2bbc1 runtime: fix static check errors
c60951f5 actions: enable unit tests in PR check
c750ce13 agent: makefile: Add codecov target
0704641c makefile: agent: Add self documented help
04dcbd4d github: Update ubuntu version to 20.04
f1c63380 github: Add github actions
ee202408 versions: Upgrade to cloud-hypervisor v15.0
aad549fe qemu: kill virtiofsd if failure to start VMM
16e358b3 docs: Document limitation regarding subpaths
a8137eef Makefile: Replace @RUNTIME_NAME@ with the target in generated files
351a01bd runtime: handle io.katacontainers.config.hypervisor.virtio_fs_extra_args

### CODE REVIEW

**Comment by fidencio** [comment]
@jongwu, did I break the ARM CI? :-) From http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-ARM-PR/1393/console
```
Running baremetal cleanup script for arch aarch64
panic: reflect: indirection through nil pointer to embedded struct [recovered]
	panic: reflect: indirection through nil pointer to embedded struct

goroutine 1 [running]:
text/template.errRecover(0x40005ff280)
	/usr/local/go/src/text/template/exec.go:170 +0x1ac
panic(0xaaaabe8a8ae0, 0xaaaabebe9d80)
	/usr/local/go/src/runtime/panic.go:679 +0x194
reflect.Value.FieldByIndex(0xaaaabea61b40, 0x40005560c0, 0x99, 0x4000396510, 0x2, 0x2, 0x0, 0xaaaabeca1580, 0xaaaabe8a8ae0)
	/usr/local/go/src/reflect/value.go:883 +0x334
text/template.(*state).evalField(0x40005ff200, 0xaaaabea61b40, 0x40005560c0, 0x99, 0xffffe173e86d, 0x6, 0xaaaabec720c0, 0x400045e1b0, 0x4000438040, 0x1, ...)
	/usr/local/go/src/text/template/exec.go:605 +0x318
text/template.(*state).evalFieldChain(0x40005ff200, 0xaaaabea61b40, 0x40005560c0, 0x99, 0xaaaabea61b40, 0x40005560c0, 0x99, 0xaaaabec720c0, 0x400045e1b0, 0x4000438030, ...)
	/usr/local/go/src/text/template/exec.go:558 +0x170
text/template.(*state).evalFieldNode(0x40005ff200, 0xaaaabea61b40, 0x40005560c0, 0x99, 0x400045e1b0, 0x4000438040, 0x1, 0x1, 0xaaaabe94d960, 0xaaaabfc96370, ...)
	/usr/local/go/src/text/template/exec.go:522 +0xc0
text/template.(*state).evalCommand(0x40005ff200, 0xaaaabea61b40, 0x40005560c0, 0x99, 0x400045e180, 0xaaaabe94d960, 0xaaaabfc96370, 0x99, 0x0, 0x40005fefc8, ...)
	/usr/local/go/src/text/template/exec.go:460 +0x6c0
text/template.(*state).evalPipeline(0x40005ff200, 0xaaaabea61b40, 0x40005560c0, 0x99, 0x4000512060, 0xaaaabcea2da0, 0x400045e210, 0x30)
	/usr/local/go/src/text/template/exec.go:434 +0x100
text/template.(*state).walk(0x40005ff200, 0xaaaabea61b40, 0x40005560c0, 0x99, 0xaaaabec71f40, 0x400045e1e0)
	/usr/local/go/src/text/template/exec.go:258 +0x424
text/template.(*state).walk(0x40005ff200, 0xaaaabea61b40, 0x40005560c0, 0x99, 0xaaaabec72180, 0x400045e150)
	/usr/local/go/src/text/template/exec.go:266 +0x11c
text/template.(*Template).execute(0x4000556040, 0xaaaabec0b840, 0x400031dc20, 0xaaaabea61b40, 0x40005560c0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:221 +0x188
text/template.(*Template).Execute(...)
	/usr/local/go/src/text/template/exec.go:204
github.com/docker/cli/cli/command/system.formatInfo(0xaaaabec9c2a0, 0x40005601a0, 0x0, 0x4000327d70, 0x1, 0x1, 0x40005467d0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/cli/cli/command/system/info.go:490 +0x168
github.com/docker/cli/cli/command/system.runInfo(0x40001fd340, 0xaaaabec9c2a0, 0x40005601a0, 0x4000327560, 0x0, 0x0)
	/go/src/github.com/docker/cli/cli/command/system/info.go:87 +0x2a4
github.com/docker/cli/cli/command/system.NewInfoCommand.func1(0x40001fd340, 0x4000327b30, 0x0, 0x1, 0x0, 0x0)
	/go/src/github.com/docker/cli/cli/command/system/info.go:53 +0x40
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0x40001fd340, 0x4000572f90, 0x1, 0x1, 0x40001fd340, 0x4000572f90)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:850 +0x314
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x4000469b80, 0x4000572f80, 0x2, 0x2)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:958 +0x250
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:895
main.runDocker(0x40005601a0, 0xaaaabec0de60, 0x4000010020)
	/go/src/github.com/docker/cli/cmd/docker/docker.go:287 +0x16c
main.main()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:298 +0xcc
INFO: kill stale process
Build timed out (after 25 minutes). Marking the build as aborted.
Build was aborted
```

**Comment by fidencio** [comment]
Adding the `do-not-merge` label till @jongwu can help us with the ARM CI :-)

**Comment by jongwu** [comment]
Hello @fidencio -, ARM ci turns green again.

**Review by bergwolf — APPROVED** [review]
nice work!

**Review by snir911 — APPROVED** [review]
Thanks @fidencio !

**Pull request merged**
