### PR TITLE
this is no use commit, just neglect it.

### PR DESCRIPTION
**Pull request by jongwu**

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @jongwu - we have a sort of tradition when these "NOP" PRs get raised... we add emojis! 

My emojis of the day: :champagne: :ice_cream: :smile:

**Comment by jongwu** [comment]
hah, @jodh-intel I just nearly change nothing, but it fail to make.

**Comment by jongwu** [comment]
hello @jodh-intel  @GabyCT , help trigger jenkins-ci, as it will test github.com/kata-containers/tests#2476 I think.

**Comment by jongwu** [comment]
can you here me? @jodh-intel @caoruidong, help trigger the jenkins ci, thanks.

**Comment by jongwu** [comment]
thanks @jodh-intel

**Comment by bergwolf** [comment]
Closing stale testing PR.

**Pull request closed without merging**
