### PR TITLE
kernel: backport erofs patch to 6.1.52 guest kernel

### PR DESCRIPTION
**Pull request by ChengyuZhu6**
Backport the erofs patch from linux kernel to solve the error #8083 when sharing the image to the guest through block devices.

Fixes: #8083

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @ChengyuZhu6!

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks @ChengyuZhu6!

**Pull request merged**
