### PR TITLE
metrics: Enable memory inside container metrics

### LINKED ISSUE #7254: metrics: enable memory inside container script

### PR DESCRIPTION
**Pull request by GabyCT**
This PR will enable the memory inside container metrics for the Kata CI.

Fixes #7254

### CODE REVIEW

**Comment by GabyCT** [comment]
@dborquez could you please take a look at this PR? thanks

**Review by dborquez — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @GabyCT!

**Pull request merged**
