### PR TITLE
5.4.x: PTP_KVM support for arm/arm64 in Kata

### PR DESCRIPTION
**Pull request by damon-kwok**
The enablement of ptp_kvm for arm is completed, see [[1]](https://lore.kernel.org/kvmarm/20210330145430.996981-1-maz@kernel.org/).
It's for `kernel 5.13.x`, so we have to apply private patch to enable it in `kernel 5.4`.
The `ptp_kvm` can offer the capability of time sync in `kata` even there
is no network available and higher precision than time sync
service depend on network.
I saw that Archana Shinde deleted the ARM patch of `ptp_kvm`，
 because this patch caused many error in the `x86` build [[2]](kata-containers/packaging@82c6318#diff-dedd9a2bb757a0d2f27b981d37edf70b563e94735bbe76508e02e4f4aff93575).
I refactored the patch to fix the build problem on `x86` and tried to reactivate it.

In order for the ptp_kvm module to work on all kernel versions, I did some work.
I merged the code from kernel 5.13, and made patches for different versions.

Fixes: kata-containers#2123

Signed-off-by: Damon Kwok <damon-kwok@outlook.com>

---
Test:
|HOST  |  GUEST |  RESULT|
| --- | -------|---- |
|4.19   |  4.19   |  pass|
|5.4   |   5.4    |  pass|
|5.10   |  5.10   |  pass|
|4.19   |  5.4    |  pass|
|4.19  |   5.10   |  pass|
|5.4   |   4.19   |  pass|
|5.4    |  5.10   |  pass|
|5.10  |   5.4    |  pass|
|5.10  |   4.19   |  pass|
|5.12  |   4.19   |  pass|
|4.19  |   5.12   |  pass|

See:
```
[root@localhost ~]# uname -sm
Linux aarch64
[root@localhost ~]# modprobe ptp_kvm
[root@localhost ~]# chronyc sources
210 Number of sources = 1
MS Name/IP address         Stratum Poll Reach LastRx Last sample               
===============================================================================
#* PHC0                          0   2   377     4    -13ns[  -61ns] +/-  181ns
```
---
- [1] https://lore.kernel.org/kvmarm/20210330145430.996981-1-maz@kernel.org/
- [2] https://github.com/kata-containers/packaging/commit/82c6318b9dc78feab07775fd92a2a9578cbf55fe#diff-dedd9a2bb757a0d2f27b981d37edf70b563e94735bbe76508e02e4f4aff93575

### CODE REVIEW

**Comment by jongwu** [comment]
hello @damon-kwok -, the number after "Fixes" should be a issue number not the PR number. I have just open the related issue [2123](https://github.com/kata-containers/kata-containers/issues/2123), please use it instead.

**Comment by jongwu** [comment]
@damon-kwok -, you can also merge your three PRs in just one to save the review work.

**Comment by fidencio** [comment]
Howdy!

I'd like to ask you to rebase your PR atop of current `main`, as https://github.com/kata-containers/kata-containers/pull/2197 has been merged and it has a fix that unblocks the CI.

Please, do the rebase and feel free `@fidencio` in case you do not have the powers to run `/test`.

Sorry for the inconvenience and happy hacking!

**Comment by fidencio** [comment]
Hey, we've had yet another breakage in our CI and now it's fixed as part of https://github.com/kata-containers/kata-containers/pull/2203 ... it means that you'll need to rebase your PR atop of current main.

Sorry for the inconvenience.

**Review by jodh-intel — APPROVED** [review]
Thanks @damon-kwok.

lgtm

/cc @jongwu.

**Pull request closed without merging**
