### PR TITLE
gha: add a post cleanup script for cri-containerd ppc64le workflow

### PR DESCRIPTION
**Pull request by Amulyam24**
This PR identifies and adds an action to cleanup the ppc64le self hosted runner.

Fixes: #8666

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks!

**Review by BbolroC — APPROVED** [review]
LGTM, thanks @Amulyam24 !

**Comment by Amulyam24** [comment]
One of the required test - [kata-containers-ci-on-push / run-basic-amd64-tests / run-runk](https://github.com/kata-containers/kata-containers/pull/8667#logs) is failing. It is not related to this PR, hope it is okay to merge this.

**Comment by stevenhorsman** [comment]
> One of the required test - [kata-containers-ci-on-push / run-basic-amd64-tests / run-runk](https://github.com/kata-containers/kata-containers/pull/8667#logs) is failing. It is not related to this PR, hope it is okay to merge this.

I'll re-run as we can't merge with it failing.

**Comment by Amulyam24** [comment]
> I'll re-run as we can't merge with it failing.

All the required tests passed.

**Pull request merged**
