### PR TITLE
docs: Update licensing strategy to use kata 2.0 repository

### LINKED ISSUE #1413: update licensing strategy document to use kata 2.0 repository

### PR DESCRIPTION
**Pull request by GabyCT**
This PR updates the licensing strategy document to use the proper
tests repository for kata 2.0

Fixes #1413

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @GabyCT!

**Review by wainersm — APPROVED** [review]
LGTM

BTW, in https://github.com/kata-containers/tests/blob/main/.ci/static-checks.sh#L38 there is a "master" occurrence as well.

**Comment by GabyCT** [comment]
@wainersm thanks I will fix that too

**Pull request merged**
