### PR TITLE
Fix and re-enable s390x GoVMM tests

### PR DESCRIPTION
**Pull request by Jakob-Naucke**
govmm: Unite VirtioNet tests
govmm: readonly=on in s390x blkdev test
govmm: TestAppendPCIBridgeDevice et al. on !s390x
govmm: Remove unnecessary comma in iommu_platform
Revert "govmm: s390x: Skip broken tests"

Fixes: #3500

### CODE REVIEW

**Comment by Jakob-Naucke** [comment]
```
+ curl -LO https://golang.org/dl/go1.17.3.linux-s390x.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100    80  100    80    0     0    776      0 --:--:-- --:--:-- --:--:--   776

+ tar -xf go1.17.3.linux-s390x.tar.gz --strip-components=1
tar: This does not look like a tar archive

gzip: stdin: not in gzip format
```

huh? Tests passed though. /retest-s390x

**Comment by Jakob-Naucke** [comment]
okay that passed, let's go with the rest /test

**Comment by Jakob-Naucke** [comment]
on s390x:
```
INFO: Set filesystem reserved blocks percentage to 3%
tune2fs 1.45.6 (20-Mar-2020)
The file /dev/loop9p1 does not exist and no size was specified.
tune2fs: No such file or directory while trying to open /dev/loop9p1
Couldn't find valid filesystem superblock.
ERROR: Could not format loop device: /dev/loop9
```

hmm okay? /retest-s390x

**Review by fidencio — APPROVED** [review]
lgtm, thanks @Jakob-Naucke!

**Review by jodh-intel — APPROVED** [review]
Thanks @Jakob-Naucke.

lgtm

**Pull request merged**
