### PR TITLE
# Kata Containers 2.5.1

### PR DESCRIPTION
**Pull request by amshinde**
f74155cd5 release: Adapt kata-deploy for 2.5.1
    cd898d28c runtime: clh: Use the new 'payload' interface
    e8512320c runtime: clh: Re-generate the client code
    2e3ae3f23 agent-ctl: Get rid of compiler warning
    14a4551d5 versions: Upgrade rust supported version to 1.59.0
    012837260 versions: Update kernel to 5.15.63
    69505695b agent-ctl/trace-forwarder: udpate thread_local dependency
    48a94f36a agent/runk: update regex dependency
    1a396a178 dep: update nix dependency
    c0b5ba230 versions: Upgrade to Cloud Hypervisor v26.0

### CODE REVIEW

**Comment by fidencio** [comment]
@amshinde, would be possible to go through the PRs which have a `needes-baclport` and also ensure those are backported for the 2.5.1 release?

https://github.com/kata-containers/kata-containers/pulls?q=is%3Apr+is%3Aclosed+label%3Aneeds-backport

**Comment by amshinde** [comment]
@fidencio I have added a couple of backports that applied cleanly.

I tried to apply https://github.com/kata-containers/kata-containers/pull/4930 and https://github.com/kata-containers/kata-containers/pull/4969 as they fix security issues, but these do not apply cleanly and cause quite a few conflicts.
@bergwolf Do these need backports, and if so can you help with backporting those?

**Comment by fidencio** [comment]
@amshinde, https://github.com/kata-containers/kata-containers/pull/4861 is needed as well.

**Comment by amshinde** [comment]
@fidencio Just had a chat over the #4861 PR in the release slack channel. We usually just backport stable versions of kernel.

**Comment by bergwolf** [comment]
@amshinde Sure, let me take care of https://github.com/kata-containers/kata-containers/pull/4930 and https://github.com/kata-containers/kata-containers/pull/4969

**Comment by bergwolf** [comment]
FYI, backport PR https://github.com/kata-containers/kata-containers/pull/5049

**Comment by fidencio** [comment]
> @fidencio Just had a chat over the #4861 PR in the release slack channel. We usually just backport stable versions of kernel.

And we miss things like `CONFIG_SPECULATION_MITIGATIONS`.
We're not adding new code, we have tests running with the new kernel.  This, sincerely, is a case that we should consider backporting.

**Comment by fidencio** [comment]
> > @fidencio Just had a chat over the #4861 PR in the release slack channel. We usually just backport stable versions of kernel.
> 
> And we miss things like `CONFIG_SPECULATION_MITIGATIONS`. We're not adding new code, we have tests running with the new kernel. This, sincerely, is a case that we should consider backporting.

But hey, as we're sticking to **not** updating the kernel, would be possible to at least update the version to 5.15.63?

**Comment by fidencio** [comment]
I've raised: https://github.com/kata-containers/kata-containers/pull/5052

**Comment by fidencio** [comment]
@amshinde, may I bother you to update the commit message of https://github.com/kata-containers/kata-containers/pull/5047/commits/e32646e2984d2b97b04bdcaec1bf86c7558cd924 to include the fixes recently merged in the stable-2.5 branch?

**Comment by amshinde** [comment]
@fidencio Can we remove the dnm label on this one?
The firecracker CI is passing this time. It seemed to be an error from cgroups-rs crate earlier.   It seems as a random error, not sure if we want to continue debugging this.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @amshinde!

**Review by GabyCT — APPROVED** [review]

**Review by chavafg — APPROVED** [review]

**Comment by amshinde** [comment]
Result of test-kata-deploy action:
https://github.com/kata-containers/kata-containers/runs/8147353406?check_suite_focus=true

It has passed.

**Pull request merged**
