### PR TITLE
runtime: Always add network endpoints from the pod netns

### LINKED ISSUE #3661: Host VM network interfaces crash when starting kata container
# Description of problem

When running (main branch) kata containers as nested workload on top of fedora/centos/ubuntu VM, the host VM network disappeared as soon as the kata starts to run.

# Expected result

kata works as nested workload seamlessly

# Actual result
starting kata on host VM make the VM network to be disabled

# Further information

* This does not seem to apply to VMs deployed on Azure, otherwise you would expect CI to fail.
* Bisecting seems to point to https://github.com/kata-containers/kata-containers/commit/2edea883698bddcc2b17f24ac3c516382027d753 as the first bad commit (thanks to @fidencio)
* Reproduced on Fedora32/CentOS8Stream VMs based on libvirt, [xmldump](https://pastebin.com/CkdL3ymr)
* Reproduced on Ubuntu VM created according to the vagrant [instructions](https://github.com/kata-containers/tests#using-vagrant-to-test-your-code-changes) (thank to @wainersm)
* container runtime doesn't seem to affect the results 
* host console log - dmesg (thanks to fidencio):
```
[ 1872.647965] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[ 1872.657782] IPv6: ADDRCONF(NETDEV_UP): veth506e729e: link is not ready
[ 1872.659189] IPv6: ADDRCONF(NETDEV_CHANGE): veth506e729e: link becomes ready
[ 1872.660432] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[ 1872.661919] cni0: port 3(veth506e729e) entered blocking state
[ 1872.662685] cni0: port 3(veth506e729e) entered disabled state
[ 1872.663475] device veth506e729e entered promiscuous mode
[ 1872.664205] cni0: port 3(veth506e729e) entered blocking state
[ 1872.664913] cni0: port 3(veth506e729e) entered forwarding state
[ 1872.814540] NET: Registered protocol family 40
[ 1872.992432] cni0: port 3(veth506e729e) entered disabled state
[ 1872.996111] device veth506e729e left promiscuous mode
[ 1872.996808] cni0: port 3(veth506e729e) entered disabled state
[ 1887.324993] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[ 1887.336780] IPv6: ADDRCONF(NETDEV_UP): veth1aca15e5: link is not ready
[ 1887.337929] IPv6: ADDRCONF(NETDEV_CHANGE): veth1aca15e5: link becomes ready
[ 1887.338870] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[ 1887.339946] cni0: port 3(veth1aca15e5) entered blocking state
[ 1887.340695] cni0: port 3(veth1aca15e5) entered disabled state
[ 1887.341677] device veth1aca15e5 entered promiscuous mode
[ 1887.342620] cni0: port 3(veth1aca15e5) entered blocking state
[ 1887.343539] cni0: port 3(veth1aca15e5) entered forwarding state
[ 1887.483042] tun: Universal TUN/TAP device driver, 1.6
[ 1887.495118] eth0: Caught tx_queue_len zero misconfig
[ 1887.499118] u32 classifier
[ 1887.499560]     Performance counters on
[ 1887.500172]     input device check on
[ 1887.500693]     Actions configured
[ 1887.507665] Mirror/redirect action on
```
[containerd-logs](https://pastebin.com/cfAS3Lhw)

cc @sameo

### PR DESCRIPTION
**Pull request by sameo**
As the container runtime, we're never inspecting, adding or configuring
host networking endpoints.
Make sure we're always do that by wrapping addSingleEndpoint calls into
the pod network namespace.

Fixes #3661

Signed-off-by: Samuel Ortiz <s.ortiz@apple.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
This solves the issue for me, thanks @sameo!

**Review by jodh-intel — APPROVED** [review]
Thanks @sameo !

lgtm

But shouldn't this be backported?

**Comment by sameo** [comment]
@jodh-intel It's fixing a bug introduced with https://github.com/kata-containers/kata-containers/commit/2edea883698bddcc2b17f24ac3c516382027d753, and afaiu this is not part of any release yet.

**Pull request merged**
