### PR TITLE
kernel: PTP_KVM support for arm/arm64 in Kata

### PR DESCRIPTION
**Pull request by damon-kwok**
The enablement of ptp_kvm for arm is completed, see [[1]](https://lore.kernel.org/kvmarm/20210330145430.996981-1-maz@kernel.org/).
It's for `kernel 5.13+`, so we have to apply private patch to enable it in `kernel 4.19/5.4/5.10`.

This work patched the 4.19, 5.4 and 5.10 kernels, and now ptp_kvm can work
correctly when the host and guest use different kernel versions.

Fixes: #2123

Signed-off-by: Damon Kwok <damon-kwok@outlook.com>

---
Test:
|HOST  |  GUEST |  RESULT|
| --- | -------|---- |
|4.19   |  4.19   |  pass|
|5.4   |   5.4    |  pass|
|5.10   |  5.10   |  pass|
|4.19   |  5.4    |  pass|
|4.19  |   5.10   |  pass|
|5.4   |   4.19   |  pass|
|5.4    |  5.10   |  pass|
|5.10  |   5.4    |  pass|
|5.10  |   4.19   |  pass|
|5.12  |   4.19   |  pass|
|4.19  |   5.12   |  pass|

```sh
[root@localhost ~]# chronyc sources
210 Number of sources = 1
MS Name/IP address         Stratum Poll Reach LastRx Last sample               
===============================================================================
#* PHC0                          0   2   377     4     +1ns[   +1ns] +/-   60ns
```
---
- [1] https://lore.kernel.org/kvmarm/20210330145430.996981-1-maz@kernel.org/

### CODE REVIEW

**Comment by damon-kwok** [comment]
@jodh-intel @fidencio @jongwu 
#2123 This work has been completed, please preview.

**Review by jodh-intel — APPROVED** [review]
Thanks @damon-kwok.

lgtm

**Comment by jongwu** [comment]
Thanks @damon-kwok ，Great job！

**Comment by GabyCT** [comment]
@damon-kwok could you please update your commit message as it is failing the static checks with the following error
```
Failed to find subsystem in subject

See the document below for help on formatting commits for the project.

https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format
```
thanks

**Comment by damon-kwok** [comment]
@jongwu @GabyCT updated.

**Comment by jongwu** [comment]
Hello @GabyCT @fidencio -, help take look at this.

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
