### PR TITLE
docs: Fix url in virtiofs documentation

### LINKED ISSUE #2134: fix URL in virtio fs documentation

### PR DESCRIPTION
**Pull request by GabyCT**
This PR updates the url for virtiofs documentation.

Fixes #2134

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by devimc — APPROVED** [review]

**Review by gkurz — COMMENTED** [review]
https://github.com/kata-containers/packaging/tree/main/kata-deploy#kubernetes-quick-start is 404. This repo still uses master and it "has been archived by the owner. It is now read-only. "
So unless some change happens in the repo, this PR looks awkward. Can you explain what's going on here ?

**Review by gkurz — CHANGES_REQUESTED** [review]
The content of this repo got moved to kata-containers/kata-containers. The new URL should be:

https://github.com/kata-containers/kata-containers/tree/main/tools/packaging/kata-deploy#kubernetes-quick-start

**Comment by fidencio** [comment]
Please, rebase your PR atop of current main, as it'll need a fix included as part of https://github.com/kata-containers/kata-containers/pull/2127 (which just got merged).

Sorry for the inconvenience.

**Comment by GabyCT** [comment]
@fidencio @gkurz changes applied

**Review by fidencio — APPROVED** [review]
lgtm, thanks @GabyCT!

**Review by gkurz — APPROVED** [review]

**Pull request merged**
