### PR TITLE
stable-2.3 | versions: Upgrade to Cloud Hypervisor v21.0

### PR DESCRIPTION
**Pull request by likebreath**
Backport PR #3520.

### CODE REVIEW

**Review by Jakob-Naucke — COMMENTED** [review]
I guess the PR is mostly automatic API changes and docs, so probably not a lot of room for controversy despite its size. I'm just wondering: Are we backporting such such upgrades? Because I usually keep it to bugfixes. Do you have a strong opinion on this @likebreath?

**Comment by likebreath** [comment]
@Jakob-Naucke Thank you for the comment. That's a valid question.

The benefit is to always keep up with the latest features/improvements from Cloud Hypervisor (CH) and also each CH release normally comes with a set of bug fixes. These bug fixes can impact Kata users, for example the virtio-net performance regression from release v20.1. For the sake of consistency and simplicity (for maintaining CH with Kata), I normally prefer to keep both main and stable branches with the latest CH release, even there is little changes needed on Kata side (given the CH APIs have been quite stable for a while).

Of course, if I am missing some context for maintaining the stable branch, please let me know and I am open to adjust.

**Comment by likebreath** [comment]
Note: I believe the CI failure on `jenkins-ci-s390x-ubuntu-20-04` is irrelevant (considering the same CI job failed on several other PRs).

**Comment by fidencio** [comment]
A head's up that may affect your PR.

In the Architecture Committee meeting from January 25th, 2022, the Architecture Committee has agreed on using the "Dismiss stale pull request approvals when new commits are pushed" configuration from GitHub.  It basically means that if your PR has been rebased or updated, the approvals given will be erased.

In order to minimize traumas due to the new approach, please, consider adding a note on the changes done before the rebase / force-push, and also pinging the reviewers for a subsequent round of reviews.

Thanks for your understanding!

Related issue: https://github.com/kata-containers/community/issues/249

**Review by Jakob-Naucke — APPROVED** [review]
> each CH release normally comes with a set of bug fixes. These bug fixes can impact Kata users

Okay, makes sense.

> Note: I believe the CI failure on `jenkins-ci-s390x-ubuntu-20-04` is irrelevant (considering the same CI job failed on several other PRs).

Yes, investigations are ongoing.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @likebreath!

**Pull request merged**
