### PR TITLE
CCv0: Update CC containerd version

### PR DESCRIPTION
**Pull request by Megan-Wright**
Update kata-containers version to pickup Wang Lei's 1.6.6 rebase of containerd
Re-vendor to pickup Wang Lei's containerd 1.6.6 rebase
Fixes: #4489
    
Signed-off-by: Megan Wright <megan.wright@ibm.com>

### CODE REVIEW

**Comment by Megan-Wright** [comment]
When running the `crictl` tests locally on Ubuntu 20.04, we also see this error:
```
not ok 1 [cc][agent][cri][containerd] Test can pull an unencrypted image inside the guest
# (from function `crictl_create_cc_pod' in file lib.sh, line 82,
#  from function `create_test_pod' in file tests_common.sh, line 104,
#  in test file agent_image.bats, line 35)
#   `create_test_pod' failed
# Delete any existing kata-cc-busybox-sandbox pod
# time="2022-06-20T07:22:17-07:00" level=fatal msg="unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /run/containerd/containerd.sock: connect: no such file or directory\""
# Prepare containerd for Confidential Container
# Enable image service offload
# Enable full debug
# kata-containers/
# kata-containers/confidential-containers/
# kata-containers/confidential-containers@sha256=febcf61cd6e1ac9628f6ac14fa40836d16f3c6ddef3b303ff0321606e55ddd0b/
# kata-containers/confidential-containers@sha256=febcf61cd6e1ac9628f6ac14fa40836d16f3c6ddef3b303ff0321606e55ddd0b/signature-1
# kata-containers/confidential-containers@sha256=7250923ba3543110040462388756ef099331822c6172a050b12c7a38361ea46f/
# kata-containers/confidential-containers@sha256=7250923ba3543110040462388756ef099331822c6172a050b12c7a38361ea46f/signature-1
# Create the test sandbox
# E0620 07:22:25.911778  193187 remote_runtime.go:201] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to reserve sandbox name \"kata-cc-busybox-sandbox___0\": name \"kata-cc-busybox-sandbox___0\" is reserved for \"baa2771e6f2a96d3467fd0999946e0939f69ad753815545eacf8603c1b27f51f\""
# time="2022-06-20T07:22:25-07:00" level=fatal msg="run pod sandbox: rpc error: code = Unknown desc = failed to reserve sandbox name \"kata-cc-busybox-sandbox___0\": name \"kata-cc-busybox-sandbox___0\" is reserved for \"baa2771e6f2a96d3467fd0999946e0939f69ad753815545eacf8603c1b27f51f\""
# Failed to create the pod
```

**Comment by stevenhorsman** [comment]
It's worth noting that with the Jenkins job failures are seeing [example job output](http://jenkins.katacontainers.io/job/kata-containers-CCv0-ubuntu-20.04-PR/281/console) the underlying error of 
```Stopped sandbox 980a34f6f85d3ff8d23c79681b68073466c666a0dd040f066b2ceda80d1ddfe1
getting sandbox status of pod "980a34f6f85d3ff8d23c79681b68073466c666a0dd040f066b2ceda80d1ddfe1": metadata.Name, metadata.Namespace or metadata.Uid is not in metadata "&PodSandboxMetadata{Name:nydus-sandbox,Uid:,Namespace:default,Attempt:1,}"
[nydus_tests.sh:158] ERROR: sudo -E crictl rmp 980a34f6f85d3ff8d23c79681b68073466c666a0dd040f066b2ceda80d1ddfe1
```
This looks like the same issue that @arronwy saw in the TDX tests a little while back: https://github.com/kata-containers/kata-containers/pull/4314#issuecomment-1138776055

I think the fix he did was to use the `crictl` that was built on a different machine to get rid of the problem. 

With the new version of containerd we are installing:
```
$ crictl --version
crictl version 1.24.1
```
, whereas the old fork installed:
```
$ crictl --version
crictl version 1.20.0-24-g53ad8bb7
```
so maybe there is some build incompatibility there?

@wllenyj - I'm not sure if you have any ideas on what might be going wrong testing with the re-base?

**Comment by fidencio** [comment]
@stevenhorsman, just thinking out loud, but do we use `crictl exec --timeout` in the tests?  If so, https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.24.2 had a fix for that and may be worth trying that out.

**Comment by stevenhorsman** [comment]
> @stevenhorsman, just thinking out loud, but do we use `crictl exec --timeout` in the tests? If so, https://github.com/kubernetes-sigs/cri-tools/releases/tag/v1.24.2 had a fix for that and may be worth trying that out.

Thanks for the suggestion, but we aren't using that command. Our [`crictl` test functions](https://github.com/kata-containers/tests/blob/CCv0/integration/containerd/confidential/lib.sh) are just pretty standard `sudo crictl runp -r kata <config>`, `sudo crictl create -with-pull "${pod_id}" "${container_config}" "${pod_config}"`, `sudo crictl stopp`, `sudo crictl rmp` commands with a separate bash timeout function that Wainer added.

I might be interesting to see if we can override the crictl installation that containerd 1.6.6 is bringing, after the install, borrowing some of the logic from the `crio` install, but I'm a bit nervous about moving further away from the `main` process and potentially hiding a problem in our fork code.

**Comment by stevenhorsman** [comment]
So locally I've tested some different `crictl` versions and `1.23.0` works fine, but `1.24.0`,`1.24.1` and `1.24.2` all fail on pod creation with the error that Megan added above:
```
E0620 08:14:59.868179  137636 remote_runtime.go:201] "RunPodSandbox from runtime service failed" err="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
FATA[0004] run pod sandbox: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Failed to create the pod
```

**Comment by wllenyj** [comment]
@stevenhorsman Will creating any container trigger this problem?
I am looking at this problem, is there any important information?

**Comment by stevenhorsman** [comment]
> @stevenhorsman Will creating any container trigger this problem? I am looking at this problem, is there any important information?

So creating a pod sandbox with crictl >= 1.24.0 seems to cause the problem, not even the container (so I'm wondering if there is some crictl 1.24.0 - kata incompatibility, rather than a containerd specific problem). With Confidential container pods in Kubernetes it seems to work fine.

**Comment by stevenhorsman** [comment]
So I introduced a hack to installing the kata version.yaml specified version of critools after the containerd install in https://github.com/kata-containers/tests/pull/4867 and the tests all worked. I'm not sure if we should just go with this approach in the CCv0 branch and then defer the problem until we have a 'real' container release? Any thoughts?

**Comment by stevenhorsman** [comment]
> @stevenhorsman Found the problem, need to add `uid`,`namespace` two fields to `pod-config.yaml`.
> 
> ```yaml
> # Copyright (c) 2021, 2022 IBM Corporation
> #
> # SPDX-License-Identifier: Apache-2.0
> #
> metadata:
> #  name: ${crictl_sandbox_name}
>   name: kata-cc-busybox-sandbox
>   # Can be generated using uuidgen.
>   uid: 22eefd51-cac3-4508-a31b-3d8a38ba2059
>   namespace: default
> dns_config:
>   servers:
>     - 8.8.8.8
> ```

Thanks, I'll give that a try. If it is the solution then I'm really sorry - we looked at this on Monday, but I interpreted the error message as saying that one of name, uid, namespace needed setting, not all three, so ignored it 😞

**Comment by stevenhorsman** [comment]
I'm testing the change on the pipeline at the moment, but I'm still having issues with the manual tests even with the pod-config.yaml change:
```
$ crictl -v
crictl version 1.24.1
```
```
$ cat pod-config.yaml
# Copyright (c) 2021, 2022 IBM Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
metadata:
  #  name:
  name: kata-cc-busybox-sandbox
  uid: 9aab68a9-9930-440c-8381-7198b8540d4a
  namespace: default
dns_config:
  servers:
    - 8.8.8.8
```
```
$ sudo crictl runp -r kata pod-config.yaml
E0622 02:59:31.275476  154189 remote_runtime.go:201] "RunPodSandbox from runtime service failed" err="rpc error: code = DeadlineExceeded desc = context deadline exceeded"
FATA[0004] run pod sandbox: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

**Comment by stevenhorsman** [comment]
> @stevenhorsman Have some logs?

I'm still getting the same error as https://github.com/kata-containers/kata-containers/pull/4490#issuecomment-1162900415

I've created a gist with the kata logs: https://gist.github.com/stevenhorsman/e827ffccf9fbdcfbce85cecda175b1b2 , but there isn't anything obvious I can spot there. I'm happy to get the crictl pod config problems merged and re-base this PR once those changes are in first to double-check that there isn't some other problem going on.

**Comment by stevenhorsman** [comment]
Now the crictl fixes have gone into CCv0, I've rebased this branch on top of them, so 🤞 hopefully the /test will work now. I'll also try and re-test the manual case today if I get a chance

**Comment by stevenhorsman** [comment]
Sorry, I realised that the logs I uploaded previously were filtered for kata and the issue might be happening outside of it, so I've created a new gist with my whole `journalctl`: https://gist.github.com/stevenhorsman/e0c5de34c2cbdb45a5ea9886f8dfa92a

**Comment by stevenhorsman** [comment]
Some success! I think I'd found out the problem locally. I ran `sudo crictl config --set timeout=10` to increase the timeout and it started working, so now I need to work out why the pipeline has a different timeout.
It's worth noting that both crictl `v1.23.0` and `v1.24.1` have a default config value of `0` for the timeout, so should both fall-back to `2s` standard 🤷 

I now need to decide whether to:
- Add the timeout explicitly to all the commands
- Set the timeout in `ccv0.sh` (which is probably much easier!)

**Comment by stevenhorsman** [comment]
I've updated `ccv0.sh` to add the timeout call, so will manually test and make sure it's still working on a clean box (and regression test Kubernetes too) and then if the /test pass I think we'll be ready to force push the containerd rebase. @wllenyj  - thank you for your patience!

**Comment by stevenhorsman** [comment]
Manually tested `ccv0.sh` with `crictl` and everything seems to be working okay:
```
$ cat /etc/crictl.yaml
runtime-endpoint: unix:///run/containerd/containerd.sock
image-endpoint: ""
timeout: 10
debug: false
pull-image-on-create: false
disable-pull-on-run: false
$ ~/ccv0.sh crictl_create_cc_pod
POD ID              CREATED             STATE               NAME                      NAMESPACE           ATTEMPT             RUNTIME
f257a79cc9859       5 seconds ago       Ready               kata-cc-busybox-sandbox   default             0                   kata
$ ~/ccv0.sh crictl_create_cc_container
16de1d73587f431c25d52f045d4fb32355ee35ec725857ea528237d4763694ba
CONTAINER           IMAGE                                                    CREATED                  STATE               NAME                     ATTEMPT             POD ID              POD
16de1d73587f4       quay.io/kata-containers/confidential-containers:signed   Less than a second ago   Running             kata-cc-busybox-signed   0                   f257a79cc9859       unknown
$ ~/ccv0.sh crictl_delete_cc
16de1d73587f431c25d52f045d4fb32355ee35ec725857ea528237d4763694ba
16de1d73587f431c25d52f045d4fb32355ee35ec725857ea528237d4763694ba
Stopped sandbox f257a79cc9859c36e05627029f8c4ec51a64cccd370f43c16f48cd6d63f64172
Removed sandbox f257a79cc9859c36e05627029f8c4ec51a64cccd370f43c16f48cd6d63f64172
$ crictl --version
crictl version 1.24.1
```
I've also check the kubernetes tests and they still work:
```
~/ccv0.sh kubernetes_create_cc_pod
pod/busybox-cc created
pod/busybox-cc condition met
stevenh@containerd-rebase-k8s1:~$ kubectl get pods
NAME         READY   STATUS    RESTARTS   AGE
busybox-cc   1/1     Running   0          20s
```
so I think we are good now!

**Review by fidencio — APPROVED** [review]
lgtm, thanks @Megan-Wright and @stevenhorsman!

**Comment by stevenhorsman** [comment]
For reference I've manually tested `crictl` changes with `ccv0.sh`:
```
~/ccv0.sh crictl_create_cc_pod
[sudo] password for stevenh:
# Copyright (c) 2021, 2022 IBM Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
metadata:
  #  name:
  name: kata-cc-busybox-sandbox
  uid: bd312a66-0c80-48b8-a796-447f81c32827
  namespace: default
dns_config:
  servers:
    - 8.8.8.8
POD ID              CREATED             STATE               NAME                      NAMESPACE           ATTEMPT             RUNTIME
45373fa188ae7       5 seconds ago       Ready               kata-cc-busybox-sandbox   default             0                   kata
stevenh@ccv0-containerd-crictl1:~$ ~/ccv0.sh crictl_create_cc_container
f05131d6ca3158bf209bcd36202443b19a3b95bcfb6a8a3e3716def12ce70a5f
CONTAINER           IMAGE                                                    CREATED                  STATE               NAME                     ATTEMPT             POD ID              POD
f05131d6ca315       quay.io/kata-containers/confidential-containers:signed   Less than a second ago   Running             kata-cc-busybox-signed   0                   45373fa188ae7       unknown
stevenh@ccv0-containerd-crictl1:~$ ~/ccv0.sh crictl_delete_cc
f05131d6ca3158bf209bcd36202443b19a3b95bcfb6a8a3e3716def12ce70a5f
f05131d6ca3158bf209bcd36202443b19a3b95bcfb6a8a3e3716def12ce70a5f
Stopped sandbox 45373fa188ae705a874ed9c063f22e01d6b24a1c8c89fcd08fe6aededf3c364b
Removed sandbox 45373fa188ae705a874ed9c063f22e01d6b24a1c8c89fcd08fe6aededf3c364b
```

**Comment by stevenhorsman** [comment]
It sounds like we are good to go on this one now if we have working automated tests and some local tests too!

**Pull request merged**
