### PR TITLE
runtime-rs: Add Hybrid VSOCK device handling for CH

### LINKED ISSUE #6692: runtime-rs: cs: Implement VSOCK / Hybrid VSOCK device handling
Update the cloud Hypervisor implementation of [`handle_add_device()`](https://github.com/kata-containers/kata-containers/blob/main/src/runtime-rs/crates/hypervisor/src/ch/inner_device.rs#L41) to allow VSOCK and Hybrid VSOCK devices to be handled.

Also:

- Implement `remove_device()` for these  device types.
- See `handle_hvsock_device()` (stub)

### PR DESCRIPTION
**Pull request by cmaf**
Update cloud hypervisor implementation to allow hybrid vsock devices to be handled.

Fixes #6692

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @cmaf.

lgtm

**Review by lifupan — APPROVED** [review]

**Comment by cmaf** [comment]
Hi @lifupan, how did you test adding a hybrid vsock device for dragonball?

**Review by amshinde — APPROVED** [review]

**Comment by cmaf** [comment]
Adding some of the contributors whose work touched vsock/hybrid vsock: @yipengyin @quanweiZhou, could you tell me how you tested adding a hybrid vsock device for dragonball?

**Pull request merged**
