### PR TITLE
runtime-rs: cleanup the run dir of hypervisor when shut down

### PR DESCRIPTION
**Pull request by yaoyinnan**
Cleanup the run dir of hypervisor when shut down.

Fixes: #5825

Signed-off-by: yaoyinnan <yaoyinnan@foxmail.com>

### CODE REVIEW

**Review by Tim-0731-Hzt — APPROVED** [review]

**Review by YushuoEdge — APPROVED** [review]
True, should cleanup here.

**Comment by studychao** [comment]
I see there is a function below has `self.hypervisor.cleanup`
```
    async fn cleanup(&self, _id: &str) -> Result<()> {
        self.resource_manager.delete_cgroups().await?;
        self.hypervisor.cleanup().await?;
        // TODO: cleanup other snadbox resource
        Ok(())
    }
```

Why doesn't `cleanup` triggered?

**Comment by Tim-0731-Hzt** [comment]
> I see there is a function below has `self.hypervisor.cleanup`
> 
> ```
>     async fn cleanup(&self, _id: &str) -> Result<()> {
>         self.resource_manager.delete_cgroups().await?;
>         self.hypervisor.cleanup().await?;
>         // TODO: cleanup other snadbox resource
>         Ok(())
>     }
> ```
> 
> Why doesn't `cleanup` triggered?

This is triggered by exception handling, a different call chain.

**Comment by studychao** [comment]
> > I see there is a function below has `self.hypervisor.cleanup`
> > ```
> >     async fn cleanup(&self, _id: &str) -> Result<()> {
> >         self.resource_manager.delete_cgroups().await?;
> >         self.hypervisor.cleanup().await?;
> >         // TODO: cleanup other snadbox resource
> >         Ok(())
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Why doesn't `cleanup` triggered?
> 
> This is triggered by exception handling, a different call chain.

Thanks！

**Review by liubin — APPROVED** [review]

**Review by studychao — APPROVED** [review]
Thanks, @yaoyinnan

**Pull request merged**
