### PR TITLE
kernel: add CONFIG_X86_SGX into whitelist

### PR DESCRIPTION
**Pull request by studychao**
CONFIG_X86_SGX is introduced after kernel 5.11, and that config is a default x86_64 config for Kata build-kernel.sh script. But if we use -v to specify any kernel version below 5.11 will cause an inevitable error because CONFIG_X86_SGX is not supported in older kernels and that may cause problem for the situation if we need kernel version below 5.11.

So I propose to put CONFIG_X86_SGX into whitelist.conf to avoid break building guest kernel below 5.11.

fixes: #5741

Signed-off-by: Chao Wu <chaowu@linux.alibaba.com>

### CODE REVIEW

**Comment by studychao** [comment]
@fidencio  Please help to take a look at this:)

**Review by fidencio — APPROVED** [review]
lgtm, thanks @studychao!

**Comment by studychao** [comment]
Thanks! @fidencio

**Review by liubin — APPROVED** [review]

**Pull request merged**
