### PR TITLE
agent-ctl: Refactor CopyFile handler.

### LINKED ISSUE #9689: kata-agent-ctl refactor CopyFile handler
**Which feature do you think can be improved?**

In the current implementation of `CopyFile` handler
1. The command line input which maps to the ttrpc message struct of `CopyFileRequest` has many fields which adds to the size of the input. Also, many fields are related to fs metadata.
2. The data bytes field adds further complexity to the input if the file size is big as it has to be provided as an input when invoking the subcommand.
3. The current handler fails if the provided file size is greater than the ttrpc maximum data length of 4Mb.

Example:
To copy a file[with some random data]
`kata-agent-ctl -l debug connect --server-address "unix://${socket_path}" --hybrid-vsock --bundle-dir "$bundle_dir" -c Check -c 'CopyFile json://{"path":"/run/kata-containers/test","file_size":15,"file_mode":60,"dir_mode":2147484136,"uid":0,"gid":0,"offset":0,"data":[193, 91, 36, 71, 66, 52, 242, 218, 120, 159, 130, 45]}`

**How can it be improved?**

The input can be changed to use a known `CopyFile json://{"src": , "dest": }` format
The handler can be changed to
- determine the fs metadata information from the source field in the input
- for large file transfer handling, the copy request can be sent in multiple calls buffered over a size like 1Mb.

This also reduces the command line string:
To copy a file[with some random data]
`kata-agent-ctl -l debug connect --server-address "unix://${socket_path}" --hybrid-vsock --bundle-dir "$bundle_dir" -c Check -c 'CopyFile json://{"src": "/tmp/file_with_above_metadata", "dest":"/run/kata-containers/test"}'`

**Additional Information**

Anything else to add?

**Before raising this enhancement request**

Have you looked at the [limitations document](https://github.com/kata-containers/kata-containers/blob/main/docs/Limitations.md)?
Yes

**Kata Containers survey**

Please consider taking the survey to help us help you: https://openinfrafoundation.formstack.com/forms/kata_containers_user_survey

### PR DESCRIPTION
**Pull request by Sumynwa**
In the existing implementation for the CopyFile subcommand,
- cmd line argument list is too long, including various metadata information.
- in case of a regular file, passing the actual data as bytes stream adds to the size and complexity of the input.
- the copy request will fail when the file size exceeds that of the allowed ttrpc max data length limit of 4Mb.

This change refactors the CopyFile handler and modifies the input to a known 'source' 'destination' syntax.

Fixes #9689

### CODE REVIEW

**Comment by danmihai1** [comment]
@Sumynwa , is the CI already testing CopyFile? If not, how difficult would it be to add some test coverage for it?

**Review by danmihai1 — CHANGES_REQUESTED** [review]
Let's add some tests.

**Comment by Sumynwa** [comment]
@danmihai1 I have added CI tests for `CopyFile` api using agent-ctl. I have not introduced any new workflow for now.

**Comment by Sumynwa** [comment]
Closing this PR and raising #10271

**Pull request closed without merging**
