### PR TITLE
backport: bindmount fixes

### PR DESCRIPTION
**Pull request by egernst**
runtime: mount shared mountpoint readonly
runtime: readonly mounts should be readonly bindmount on the host

### CODE REVIEW

**Comment by bergwolf** [comment]
clh build failed on missing commits. Looks like the kvm-ioctls repo has been force pushed.

```
13:09:33 Caused by:
13:09:33   Unable to update https://github.com/cloud-hypervisor/kvm-ioctls?branch=ch#64427395
13:09:33 
13:09:33 Caused by:
13:09:33   object not found - no match for id (64427395b60e00403aed3026362a1b19873230e6); class=Odb (9); code=NotFound (-3)
13:09:33 Failed at 41: "${kata_repo_dir}/tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh"
13:09:34 Failed at 42: "${cidir}/install_cloud_hypervisor.sh"
```

**Review by fidencio — APPROVED** [review]
lgtm, thanks @egernst!

**Review by jodh-intel — APPROVED** [review]

**Pull request merged**
