### PR TITLE
kernel: Remove nemu.conf from packaging

### LINKED ISSUE #4272: remove nemu.conf from kernel configurations

### PR DESCRIPTION
**Pull request by GabyCT**
This PR removes the nemu.conf as we are not longer using NEMU from
the kernel configurations.

Fixes #4272

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Review by cmaf — COMMENTED** [review]
@GabyCT I'm not sure, but do we need to bump the `kata_config_version` in this case?

**Comment by GabyCT** [comment]
@cmaf mmm good question, @fidencio should I do that?

**Comment by fidencio** [comment]
> @cmaf mmm good question, @fidencio should I do that?

I think so, @GabyCT.

**Review by cmaf — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @GabyCT!

**Pull request merged**
