### PR TITLE
tools/packaging/kata-deploy: Copy install_yq.sh before starting parallel builds

### LINKED ISSUE #3756: make kata-tarball sometimes fails with file exists error
# Description of problem

Run `make kata-tarball`

# Expected result

Reliably builds `kata-static.tar.xz`.

# Actual result

Sometimes fails with this error:

```
$ make kata-tarball
make -f /home/dwg/src/kata-containers/tools/packaging/kata-deploy/local-build/Makefile all -j$(( $(nproc) - 1  )) NO_TTY="true" V=
make[1]: Entering directory '/home/dwg/src/kata-containers'
make cloud-hypervisor-tarball-build
make firecracker-tarball-build
make kernel-tarball-build
make qemu-tarball-build
make rootfs-image-tarball-build
make rootfs-initrd-tarball-build
make shim-v2-tarball-build
make[2]: Entering directory '/home/dwg/src/kata-containers'
make[2]: Entering directory '/home/dwg/src/kata-containers'
make[2]: Entering directory '/home/dwg/src/kata-containers'
make[2]: Entering directory '/home/dwg/src/kata-containers'
make[2]: Entering directory '/home/dwg/src/kata-containers'
make[2]: Entering directory '/home/dwg/src/kata-containers'
make[2]: Entering directory '/home/dwg/src/kata-containers'
/home/dwg/src/kata-containers/tools/packaging/kata-deploy/local-build//kata-deploy-binaries-in-docker.sh -s --build=firecracker
/home/dwg/src/kata-containers/tools/packaging/kata-deploy/local-build//kata-deploy-binaries-in-docker.sh -s --build=cloud-hypervisor
/home/dwg/src/kata-containers/tools/packaging/kata-deploy/local-build//kata-deploy-binaries-in-docker.sh -s --build=kernel
/home/dwg/src/kata-containers/tools/packaging/kata-deploy/local-build//kata-deploy-binaries-in-docker.sh -s --build=qemu
/home/dwg/src/kata-containers/tools/packaging/kata-deploy/local-build//kata-deploy-binaries-in-docker.sh -s --build=rootfs-image
/home/dwg/src/kata-containers/tools/packaging/kata-deploy/local-build//kata-deploy-binaries-in-docker.sh -s --build=rootfs-initrd
/home/dwg/src/kata-containers/tools/packaging/kata-deploy/local-build//kata-deploy-binaries-in-docker.sh -s --build=shim-v2
cp: cannot create regular file '/home/dwg/src/kata-containers/tools/packaging/kata-deploy/local-build/dockerbuild/install_yq.sh': File exists
make[2]: *** [tools/packaging/kata-deploy/local-build/Makefile:30: cloud-hypervisor-tarball-build] Error 1
make[2]: Leaving directory '/home/dwg/src/kata-containers'
make[1]: *** [/home/dwg/src/kata-containers/tools/packaging/kata-deploy/local-build/Makefile:33: cloud-hypervisor-tarball] Error 2
make[1]: *** Waiting for unfinished jobs....
```

# Further information

I suspect this is a race between different parts of the parallel build both trying to install yq in the same location.

### PR DESCRIPTION
**Pull request by gkurz**
`make kata-tarball` sometimes fails with a `file exists` error. This happens because several parts of the parallel build try to copy `install_yq.sh` to the same location using the `cp` command. This is a well known issue that can only be avoid by serialization.

PR #3949 tried to address that by serializing the sub-builds but this raised other problems (`make kata-tarball` taking 30% longer) and not really fixed the issue since it can still be hit with 'make -j kata-tarball`.

Let's go for another approach : decouple the copying of `yq_install.sh` from the rest and ensure it happens *before* starting the parallel builds.

The first two patches are preliminary cleanups, indirectly related, but worth merging. The first one helps to have a pristine working directory with `git clean -fdx`, that I've used a lot between invocations of the various `make *-tarball` targets. The second one does an healthy simplification that touches the same part of the makefile : it seems simpler to merge it right now rather than having to rebase it later.

Fixes #3756 

Signed-off-by: Greg Kurz <groug@kaod.org>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @gkurz!

**Review by GabyCT — APPROVED** [review]

**Review by dgibson — APPROVED** [review]
👍

A small step, but a good one.

**Comment by snir911** [comment]
after discussion with @gkurz added needs-backport

**Comment by gkurz** [comment]
> after discussion with @gkurz added needs-backport

Yes this is an actual bug fix. Thanks @snir911 !

**Pull request merged**
