### PR TITLE
tools: Improve cached artifacts for qemu

### LINKED ISSUE #5670: improve cached artifacts for qemu

### PR DESCRIPTION
**Pull request by GabyCT**
This PR improves the cached artifacts for qemu components.

Fixes #5670

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
I've test this PR in a special jenkins job and seems working fine

**Comment by GabyCT** [comment]
@wainersm here are the improvements thanks

**Comment by GabyCT** [comment]
@wainersm and @fidencio could you please take a look? thanks

**Comment by fidencio** [comment]
Gaby, this one is good to go, but I will need to wait til the CCv0 merge happens, and we can rebase this one atop.
I will take care of the rebase pushing to your branch, and after that re-trigger the CIs.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @GabyCT!

**Pull request merged**
