### PR TITLE
tools: Fix indentation of build static clh script

### LINKED ISSUE #5528: fix indentation of build static clh script

### PR DESCRIPTION
**Pull request by GabyCT**
This Pr removes single spaces and fix the indentation of the script.

Fixes #5528

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
@fidencio here it is the change at main

**Review by fidencio — APPROVED** [review]
lgtm, thanks @GabyCT1

**Review by littlejawa — APPROVED** [review]
lgtm
Thanks!

**Review by Ji-Xinyou — APPROVED** [review]
LGTM.

**Pull request merged**
