### PR TITLE
runtime: upgrade go.mod version to 1.18

### PR DESCRIPTION
**Pull request by yaoyinnan**
golang 1.17.x is no longer supported as of Aug 2022 according to
https://endoflife.date/go
Bumping the minimum version supported to 1.18.6 and the newest
version supported to 1.19.1.

Upgrade go.mod version to 1.18.

Fixes: #5208

Signed-off-by: yaoyinnan <yaoyinnan@foxmail.com>

### CODE REVIEW

**Comment by fengwang666** [comment]
@yaoyinnan Can you resolve the conflict?

**Comment by yaoyinnan** [comment]
@fengwang666 I have rebase. There are still a lot of problems with the CI of this PR. Currently, the PR https://github.com/kata-containers/kata-containers/pull/5248 for updating the containerd version has not been merged.

**Pull request closed without merging**
