### PR TITLE
fix(clippy): fix clippy checks

### PR DESCRIPTION
**Pull request by Ji-Xinyou**
Fix clippy checks for components in need.

### CODE REVIEW

**Comment by liubin** [comment]
Which version of rust get these warnings when `cargo clippy`?

**Comment by Ji-Xinyou** [comment]
> Which version of rust gets these warnings when `cargo clippy`?

I think it was 1.64?

**Comment by liubin** [comment]
I mean we should only fix clippy warnings under the version we are using now.

https://github.com/kata-containers/kata-containers/blob/1da2d0603c882073b38fb586f6b46de51f584685/versions.yaml#L311-L319

@kata-containers/architecture-committee In which steps should we keep upgrading Rust version?

**Comment by Ji-Xinyou** [comment]
> I mean we should only fix clippy warnings under the version we are using now.
> 
> https://github.com/kata-containers/kata-containers/blob/1da2d0603c882073b38fb586f6b46de51f584685/versions.yaml#L311-L319
> 
> @kata-containers/architecture-committee In which steps should we keep upgrading Rust version?

IMO the clippy checks are mostly back-compatable with previous rustc so the clippy suggestions could be independently fixed w.r.t. the rustc version.

**Comment by Tim-Zhang** [comment]
Hi @Ji-Xinyou, I find this pr is the oldest PR that try to fix clippy warnings. Could you please rewrite it for [rust 1.66](https://github.com/kata-containers/kata-containers/pull/5967) and resolve the conflict?

**Pull request closed without merging**
