### PR TITLE
runtime: return error if clh's binary doesn't have a normal stat

### PR DESCRIPTION
**Pull request by liubin**
When checking clh's binary path if valid, return error even
though the error is not a IsNotExist error.

And add errors to log filed when errors occurred.

Fixes: #2208

Signed-off-by: bin <bin@hyper.sh>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @liubin.

lgtm

**Comment by fidencio** [comment]
Hey, we've had yet another breakage in our CI and now it's fixed as part of https://github.com/kata-containers/kata-containers/pull/2203 ... it means that you'll need to rebase your PR atop of current main.

Sorry for the inconvenience.

**Review by Tim-Zhang — APPROVED** [review]
LGTM @liubin

**Pull request merged**
