### PR TITLE
versions: Upgrade to cloud-hypervisor v16.0

### PR DESCRIPTION
**Pull request by likebreath**
Highlights from the Cloud Hypervisor release v16.0: 

1. Improved live migration support;
2. Improved `vhost-user` support; 
3. ARM64 ACPI and UEFI support; 
4. Bug fixes.

Details can be found: https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v16.0

Note: The client code of cloud-hypervisor's OpenAPI is automatically
generated by `openapi-generator` [1-2]. As the API changes do not
impact usages in Kata, no additional changes in kata's runtime are
needed to work with the current version of cloud-hypervisor.

[1] https://github.com/OpenAPITools/openapi-generator
[2] https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/pkg/cloud-hypervisor/README.md

Fixes: #1992

Signed-off-by: Bo Chen <chen.bo@intel.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @likebreath!

**Comment by jongwu** [comment]
Hello @likebreath -, just one question. Can kata boot with firmware in x86 when start using cloud hypervisor? As far as I know, cloud hypervisor doesn't support direct kernel boot when start with firmware, since it only has "-kernel" interface both used for kernel and firmware.

**Comment by likebreath** [comment]
>  Can kata boot with firmware in x86 when start using cloud hypervisor? 

No, I don't think so. kata+clh only supports direct kernel boot as you said. (I thought kata+qemu also only supports direct kernel boot. Correct me if I am mistaken.)

> As far as I know, cloud hypervisor doesn't support direct kernel boot when start with firmware, since it only has "-kernel" interface both used for kernel and firmware.

I may miss some context here. I don't quite understand `cloud hypervisor doesn't support direct kernel boot when start with firmware`.  Would you please elaborate more? @jongwu 

From my understanding, when you boot the hypervisor (aka qemu or clh) w/ firmware, you are booting from the stock kernel inside the guest image you provided (which is supported in clh through https://github.com/cloud-hypervisor/rust-hypervisor-firmware).

**Review by GabyCT — APPROVED** [review]

**Comment by jongwu** [comment]
Hello @likebreath -,  take qemu as an example. you can use "-bios" to specify firmware meanwhile using "-kernel" to specify kernel image, then VM will boot from the kernel you specified not the stock kernel in the guest image, which will speed up.
But it is not the case in clh, since the firmware and kernel both use the same interface "-kernel" to be specified.

**Comment by likebreath** [comment]
> take qemu as an example. you can use "-bios" to specify firmware meanwhile using "-kernel" to specify kernel image, then VM will boot from the kernel you specified not the stock kernel in the guest image, which will speed up.

Good to learn there is such usage case for qemu. Thanks for sharing, @jongwu. One quick question: do you mean using a `-bios` option will speed-up the direct kernel boot purely using `-kernel`?

> But it is not the case in clh, since the firmware and kernel both use the same interface "-kernel" to be specified.
You are right.

**Comment by jongwu** [comment]
Hello @likebreath -, Generally, when a VM starts from firmware, it will often transfer its “power" to bootloader, e.g. grub, then the bootloader will start the kernel. But if you specify kernel image through "-kernel", the VMM, e.g. qemu, will boot kernel directly at the end of firmware booting, thus, the bootloader booting can be canceled.
Also, in kata, there is no kernel in the kata container image for now. So, there is no way to boot firmware in kata using clh, only if  do some changes in clh.

**Pull request merged**
