### PR TITLE
docs: Add tracing proposals doc

### PR DESCRIPTION
**Pull request by jodh-intel**
Create a document summarising the tracing design proposals from PR #1937.

Fixes: #2061.

Signed-off-by: bin <bin@hyper.sh>
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
@kata-containers/architecture-committee - Please comment on these proposals. I've added an agenda item for next week's AC meeting (https://etherpad.opendev.org/p/Kata_Containers_2021_Architecture_Committee_Mtgs)

**Comment by jodh-intel** [comment]
Posted review request to the ML: http://lists.katacontainers.io/pipermail/kata-dev/2021-June/001980.html

**Comment by c3d** [comment]
Hi @jodh-intel, I would like to suggest a third way, which I implemented for C/C++ in the [flight recorder library](https://github.com/c3d/recorder). There is a video at the top of the readme that explains that approach.

The basic idea is that you split the recording of events from their transmission to the consumer. The recording probe is always there, and records in circular buffers in memory. It must cost sufficiently little to be left on all the time. So you have some "always on" instrumentation.

Data recording is topical, not based on code locality. There are no "spans", but topic-specific buffers. For example, instead of tracing if you enter/exit this or that function, you record command-line options, memory allocation, RPC messages, hypervisor commands, and so on.

The second part is getting the data out of the buffers. The recorder library offers:

1. Dynamic tracing, which logs anything sent to a particular buffer is emitted. For example, you can ask to dump anything related to qemu. Note that you can also disable recording entirely.
2. Post-mortem dump, which on some event, logs what happened just before. In the case of the recorder library, there is a global order, so that events can be ordered even when they happen at very different speeds. For example, in case of crash, you can get the command-line options from the early start of the program as well as the last memory allocations that happened in the last millisecond or so.
3. Filtered extraction, where you extract data from the traces, e.g. for graphing purpose. For example, you can have a particular buffer that records the total amount of memory being allocated, and you can plot that over time.

The recorder library is small (~4500 LOCs). We might want to do an equivalent Rust crate.

I believe that this approach is more powerful, and not significantly more complicated. It's simply a matter of splitting the data probe from the data transmission with some intermediate circular buffer.

**Comment by egernst** [comment]
For my clarity, you’re suggesting this library instead of opentelemtry?

I think there’s value in using a common pattern; in particular; I could see enabling tracing from kubelet to containerd down through to the agent.

**Comment by jodh-intel** [comment]
Hi @c3d - this sounds very interesting and would provide a workable dynamic tracing feature (which looks unlikely with OpenTelememetry in the agent). How about adding an AC meeting agenda item so you can present further details on flight recorder?

**Comment by c3d** [comment]
> For my clarity, you’re suggesting this library instead of opentelemtry?

More like an intermediate data buffer to collect data that we could then feed either to opentelemetry or other sources (including, in case of crash, the console)

> 
> I think there’s value in using a common pattern; in particular; I could see enabling tracing from kubelet to containerd down through to the agent.

Agreed.

**Comment by c3d** [comment]
> Hi @c3d - this sounds very interesting and would provide a workable dynamic tracing feature (which looks unlikely with OpenTelememetry in the agent). How about adding an AC meeting agenda item so you can present further details on flight recorder?

Since we are discussing tracing anyways, I may simply comment. This is already the topic.

**Comment by jodh-intel** [comment]
# Status

These proposals were presented and discussed at the Kata Architecture Committee Meeting on 2021-06-22 and 2021-06-29:

- https://etherpad.opendev.org/p/Kata_Containers_2021_Architecture_Committee_Mtgs

The community were notified almost two weeks ago now and nobody raised concerns in the meetings or on the mailing list. As such, I think it's reasonable to proceed with implementing the proposals for agent tracing (particularly since these decisions could always be undone in the future if needed).

# Proposals

## Agent tracing proposal 1: Don't implement dynamic trace mode

**Discussion summary:** No concerns raised although it's still unclear how many users favour long-running containers (where dynamic tracing would be a better option). However, @c3d is proposing an alternative for that use-case in https://github.com/c3d/recorder (to be discussed in the AC meeting on 2021-07-13).

**Potential future work:** What we could potentially do is add some sort of OpenTelemetry dynamic tracing at the "highest level" rather than at the lowest (the agent). That "highest level" could/would initially be the Kata shimv2 runtime, but ideally it would be higher still. By moving the control of dynamic tracing "up the stack", the problem becomes simpler since the higher levels have more intrinsic knowledge of the scope of what could be a trace transaction. If we were to add dynamic tracing to the runtime, we could add a set of CLI commands to control it (rather than hard-coding in the configuration file). Something like:

```bash
$ sudo kata-runtime tracing [start|stop|status]
```

**Conclusion:** No concerns raised, so plan to _not_ implement dynamic tracing of any kind at this stage.

## Agent tracing proposal 2: Simplify handling of trace type

**Conclusion:** No concerns raised, so plan to implement.

## Trace collection proposals

- Trace collection proposal 1: Send all spans to the trace forwarder as a span proxy
- Trace collection proposal 2: Send spans to collector directly from runtime/agent

We didn't discuss these two proposals much as we didn't have enough detail on why this should be done.

The trace forwarder component is somewhat of a "necessary evil": we need it to "listen" to the trace spans being sent from the agent running in the VM and forward them on to a trace collector running on the host.

### Possible benefits of channeling all traces through the forwarder

- monitoring
- filtering
- conversion (to other trace formats?)
- consistency (having all traces flow through one component)

### Possible costs of channeling all traces through the forwarder

- Not strictly required for the runtime traces.
- Extra performance overhead for runtime traces.

@liubin - can you add any more thoughts on the trace collection proposals?

**Comment by jodh-intel** [comment]
I'll update #1937 to take account of the agent tracing proposals...

**Comment by fidencio** [comment]
Howdy!

I'd like to ask you to rebase your PR atop of current `main`, as https://github.com/kata-containers/kata-containers/pull/2197 has been merged and it has a fix that unblocks the CI.

Please, do the rebase and feel free `@fidencio` in case you do not have the powers to run `/test`.

Sorry for the inconvenience and happy hacking!

**Comment by fidencio** [comment]
Hey, we've had yet another breakage in our CI and now it's fixed as part of https://github.com/kata-containers/kata-containers/pull/2203 ... it means that you'll need to rebase your PR atop of current main.

Sorry for the inconvenience.

**Comment by jodh-intel** [comment]
Please can folk review this doc so we can get it landed ;)

/test

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jodh-intel!

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
