### PR TITLE
vendor: Fix qemu commandline issue with empty romfile

### PR DESCRIPTION
**Pull request by QiuMike**
Currently, if romfile field is empty, the commandline will
shows like below:
-device driver=virtio-net-pci,...,mq=on,vectors=4,romfile=

This does not make sense, just remove this field in commandline

Signed-off-by: Michael Qiu <qiudayu@huayun.com>

### CODE REVIEW

**Comment by devimc** [comment]
thanls @QiuMike , but you need to move this to https://github.com/kata-containers/govmm and once it's merged, revendor it in this repo

**Comment by cmaf** [comment]
@QiuMike also once you submit to the appropriate repo, please make sure to follow our [patch format guidelines](https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format)

**Comment by QiuMike** [comment]
> thanls @QiuMike , but you need to move this to https://github.com/kata-containers/govmm and once it's merged, revendor it in this repo

OK,
I will resubmit it to repo https://github.com/kata-containers/govmm

Thanks

**Comment by cmaf** [comment]
PR moved to https://github.com/kata-containers/govmm/pull/169 and merged; fixes issue https://github.com/kata-containers/kata-containers/issues/1694

**Pull request closed without merging**
