### PR TITLE
 ci: k8s: Add k8s devmapper tests (part 0)

### PR DESCRIPTION
**Pull request by fidencio**
Let's enable the devmapper kubernetes tests to match exactly what's been
tested as part of the Jenkins CI.

Fixes: #6542

### CODE REVIEW

**Review by BbolroC — APPROVED** [review]
LGTM, thanks @fidencio

**Review by zvonkok — APPROVED** [review]
LGTM, the nice thing is about having tests for everything, it is implicitly documented how to do things the right way :)

**Pull request merged**
