### PR TITLE
Validate runtime annotations

### LINKED ISSUE #901: Validate annotations that refer to binaries
The description of the problem is in https://bugs.launchpad.net/katacontainers.io/+bug/1878234.

This issue is a placeholder to allow the fixes to be submitted.

This is the 2.0 port of https://github.com/kata-containers/runtime/issues/3004.

### PR DESCRIPTION
**Pull request by c3d**
This fixes #901 and https://bugs.launchpad.net/katacontainers.io/+bug/1878234.

Need to add a link to code reviews once this is merged.

### CODE REVIEW

**Comment by bergwolf** [comment]
Thanks @c3d ! Travis failed on UTs. Please take a look.

**Comment by c3d** [comment]
@bergwolf Thanks. It looks like the new `@PROJECT_URL@` was not added to `USER_VARS` in my fix for https://github.com/kata-containers/runtime/issues/2943. I added it. We'll see.

**Review by jodh-intel — APPROVED** [review]
Thanks @c3d !

lgtm

**Review by devimc — APPROVED** [review]
lgtm - thanks @c3d - all green

cc @kata-containers/architecture-committee

**Comment by jodh-intel** [comment]
@bergwolf - any further comments before we merge?

**Comment by bergwolf** [comment]
lgtm, thanks @c3d !

**Pull request merged**
