### PR TITLE
stable-2.1 | week 23: weekly backports

### PR DESCRIPTION
**Pull request by fidencio**
This week we're pulling down the following commits:
* docs: Fix Release Process document 9158ec68cc30889c773a97bbe34ef73e18f25fe4 #1961
* runtime: remove covertool from cli test db8d853b99e27aefc291f71b9f43b1563bc6e3ec #1863
* tools/packaging: clone meson and dependencies before building QEMU 492729f44301b2ba7ad2370d0cbb9bd5e3d5527b #1966

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @fidencio.

lgtm

**Review by bpradipt — APPROVED** [review]
/lgtm

**Pull request merged**
