### PR TITLE
CCv0: update deps for 0.4.0

### PR DESCRIPTION
**Pull request by jepio**
- attestation-agent: c6cdff6dcd4f4ca45fa0fb7df439057d2dba15ea
- image-rs: ~48bb221d8e76cb35549f2ffa626d2f687f959bd2~ 948db858579be538724266a650e840e75e7e824d
- td-shim: latest HEAD (5fa81efa1e43c8005d6d8099b5c099125c17b4b0)

Fixes: #6366

### CODE REVIEW

**Comment by fidencio** [comment]
```
13:44:30 # Feb 23 12:44:23 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:23.579916074Z" level=debug msg="PullImage() start" image="quay.io/kata-containers/confidential-containers:unsigned" name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=containerd-kata-shim-v2
13:44:30 # Feb 23 12:44:23 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:23.580016375Z" level=debug msg="Making image pull request" image="quay.io/kata-containers/confidential-containers:unsigned" name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=containerd-kata-shim-v2
13:44:30 # Feb 23 12:44:23 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:23.766297344Z" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3/console.sock name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=virtcontainers subsystem=sandbox vmconsole="{\"msg\":\"image_client.config.auth set to: true\",\"level\":\"INFO\",\"ts\":\"2023-02-23T12:44:23.575194632Z\",\"source\":\"agent\",\"subsystem\":\"rpc\",\"pid\":\"120\",\"version\":\"0.1.0\",\"name\":\"kata-agent\"}"
13:44:30 # Feb 23 12:44:23 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:23.766441946Z" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3/console.sock name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=virtcontainers subsystem=sandbox vmconsole="{\"msg\":\"enable_signature_verification set to: true\",\"level\":\"INFO\",\"ts\":\"2023-02-23T12:44:23.575248784Z\",\"subsystem\":\"rpc\",\"pid\":\"120\",\"name\":\"kata-agent\",\"version\":\"0.1.0\",\"source\":\"agent\"}"
13:44:30 # Feb 23 12:44:23 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:23.766495947Z" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3/console.sock name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=virtcontainers subsystem=sandbox vmconsole="{\"msg\":\"pull image \\\"confidential-containers_unsigned\\\", bundle path \\\"/run/kata-containers/confidential-containers_unsigned\\\"\",\"level\":\"INFO\",\"ts\":\"2023-02-23T12:44:23.575302066Z\",\"version\":\"0.1.0\",\"subsystem\":\"rpc\",\"pid\":\"120\",\"name\":\"kata-agent\",\"source\":\"agent\"}"
13:44:30 # Feb 23 12:44:23 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:23.76825727Z" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3/console.sock name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=virtcontainers subsystem=sandbox vmconsole="\x1b[0m\x1b[38;5;8m[\x1b[0m2023-02-23T12:44:23Z \x1b[0m\x1b[1m\x1b[31mERROR\x1b[0m attestation_agent::grpc::getresource\x1b[0m\x1b[38;5;8m]\x1b[0m Call AA-KBC to get resource failed: Received unknown resource name: Credential"
13:44:30 # Feb 23 12:44:24 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:24.116107681Z" level=error msg="agent pull image err. rpc error: code = Internal desc = Security validate failed: unknown variant `signedBy`, expected one of `insecureAcceptAnything`, `reject`, `sigstoreSigned` at line 11 column 38" name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=virtcontainers subsystem=kata_agent
13:44:30 # Feb 23 12:44:24 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:24.116216982Z" level=error msg="kata runtime PullImage err. rpc error: code = Internal desc = Security validate failed: unknown variant `signedBy`, expected one of `insecureAcceptAnything`, `reject`, `sigstoreSigned` at line 11 column 38" name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=containerd-kata-shim-v2
13:44:30 # Feb 23 12:44:24 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:24.116267783Z" level=debug msg="PullImage() end" image="quay.io/kata-containers/confidential-containers:unsigned" name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=containerd-kata-shim-v2
```

**Comment by Xynnn007** [comment]
> ```
> 13:44:30 # Feb 23 12:44:23 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:23.579916074Z" level=debug msg="PullImage() start" image="quay.io/kata-containers/confidential-containers:unsigned" name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=containerd-kata-shim-v2
> 13:44:30 # Feb 23 12:44:23 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:23.580016375Z" level=debug msg="Making image pull request" image="quay.io/kata-containers/confidential-containers:unsigned" name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=containerd-kata-shim-v2
> 13:44:30 # Feb 23 12:44:23 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:23.766297344Z" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3/console.sock name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=virtcontainers subsystem=sandbox vmconsole="{\"msg\":\"image_client.config.auth set to: true\",\"level\":\"INFO\",\"ts\":\"2023-02-23T12:44:23.575194632Z\",\"source\":\"agent\",\"subsystem\":\"rpc\",\"pid\":\"120\",\"version\":\"0.1.0\",\"name\":\"kata-agent\"}"
> 13:44:30 # Feb 23 12:44:23 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:23.766441946Z" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3/console.sock name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=virtcontainers subsystem=sandbox vmconsole="{\"msg\":\"enable_signature_verification set to: true\",\"level\":\"INFO\",\"ts\":\"2023-02-23T12:44:23.575248784Z\",\"subsystem\":\"rpc\",\"pid\":\"120\",\"name\":\"kata-agent\",\"version\":\"0.1.0\",\"source\":\"agent\"}"
> 13:44:30 # Feb 23 12:44:23 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:23.766495947Z" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3/console.sock name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=virtcontainers subsystem=sandbox vmconsole="{\"msg\":\"pull image \\\"confidential-containers_unsigned\\\", bundle path \\\"/run/kata-containers/confidential-containers_unsigned\\\"\",\"level\":\"INFO\",\"ts\":\"2023-02-23T12:44:23.575302066Z\",\"version\":\"0.1.0\",\"subsystem\":\"rpc\",\"pid\":\"120\",\"name\":\"kata-agent\",\"source\":\"agent\"}"
> 13:44:30 # Feb 23 12:44:23 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:23.76825727Z" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3/console.sock name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=virtcontainers subsystem=sandbox vmconsole="\x1b[0m\x1b[38;5;8m[\x1b[0m2023-02-23T12:44:23Z \x1b[0m\x1b[1m\x1b[31mERROR\x1b[0m attestation_agent::grpc::getresource\x1b[0m\x1b[38;5;8m]\x1b[0m Call AA-KBC to get resource failed: Received unknown resource name: Credential"
> 13:44:30 # Feb 23 12:44:24 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:24.116107681Z" level=error msg="agent pull image err. rpc error: code = Internal desc = Security validate failed: unknown variant `signedBy`, expected one of `insecureAcceptAnything`, `reject`, `sigstoreSigned` at line 11 column 38" name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=virtcontainers subsystem=kata_agent
> 13:44:30 # Feb 23 12:44:24 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:24.116216982Z" level=error msg="kata runtime PullImage err. rpc error: code = Internal desc = Security validate failed: unknown variant `signedBy`, expected one of `insecureAcceptAnything`, `reject`, `sigstoreSigned` at line 11 column 38" name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=containerd-kata-shim-v2
> 13:44:30 # Feb 23 12:44:24 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:24.116267783Z" level=debug msg="PullImage() end" image="quay.io/kata-containers/confidential-containers:unsigned" name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=containerd-kata-shim-v2
> ```

Please add feature `"signature-simple"` to the features of `[target.'cfg(not(target_arch = "s390x"))'.dependencies]`

**Comment by jepio** [comment]
> > ```
> > 13:44:30 # Feb 23 12:44:23 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:23.579916074Z" level=debug msg="PullImage() start" image="quay.io/kata-containers/confidential-containers:unsigned" name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=containerd-kata-shim-v2
> > 13:44:30 # Feb 23 12:44:23 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:23.580016375Z" level=debug msg="Making image pull request" image="quay.io/kata-containers/confidential-containers:unsigned" name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=containerd-kata-shim-v2
> > 13:44:30 # Feb 23 12:44:23 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:23.766297344Z" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3/console.sock name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=virtcontainers subsystem=sandbox vmconsole="{\"msg\":\"image_client.config.auth set to: true\",\"level\":\"INFO\",\"ts\":\"2023-02-23T12:44:23.575194632Z\",\"source\":\"agent\",\"subsystem\":\"rpc\",\"pid\":\"120\",\"version\":\"0.1.0\",\"name\":\"kata-agent\"}"
> > 13:44:30 # Feb 23 12:44:23 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:23.766441946Z" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3/console.sock name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=virtcontainers subsystem=sandbox vmconsole="{\"msg\":\"enable_signature_verification set to: true\",\"level\":\"INFO\",\"ts\":\"2023-02-23T12:44:23.575248784Z\",\"subsystem\":\"rpc\",\"pid\":\"120\",\"name\":\"kata-agent\",\"version\":\"0.1.0\",\"source\":\"agent\"}"
> > 13:44:30 # Feb 23 12:44:23 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:23.766495947Z" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3/console.sock name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=virtcontainers subsystem=sandbox vmconsole="{\"msg\":\"pull image \\\"confidential-containers_unsigned\\\", bundle path \\\"/run/kata-containers/confidential-containers_unsigned\\\"\",\"level\":\"INFO\",\"ts\":\"2023-02-23T12:44:23.575302066Z\",\"version\":\"0.1.0\",\"subsystem\":\"rpc\",\"pid\":\"120\",\"name\":\"kata-agent\",\"source\":\"agent\"}"
> > 13:44:30 # Feb 23 12:44:23 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:23.76825727Z" level=debug msg="reading guest console" console-protocol=unix console-url=/run/vc/vm/8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3/console.sock name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=virtcontainers subsystem=sandbox vmconsole="\x1b[0m\x1b[38;5;8m[\x1b[0m2023-02-23T12:44:23Z \x1b[0m\x1b[1m\x1b[31mERROR\x1b[0m attestation_agent::grpc::getresource\x1b[0m\x1b[38;5;8m]\x1b[0m Call AA-KBC to get resource failed: Received unknown resource name: Credential"
> > 13:44:30 # Feb 23 12:44:24 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:24.116107681Z" level=error msg="agent pull image err. rpc error: code = Internal desc = Security validate failed: unknown variant `signedBy`, expected one of `insecureAcceptAnything`, `reject`, `sigstoreSigned` at line 11 column 38" name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=virtcontainers subsystem=kata_agent
> > 13:44:30 # Feb 23 12:44:24 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:24.116216982Z" level=error msg="kata runtime PullImage err. rpc error: code = Internal desc = Security validate failed: unknown variant `signedBy`, expected one of `insecureAcceptAnything`, `reject`, `sigstoreSigned` at line 11 column 38" name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=containerd-kata-shim-v2
> > 13:44:30 # Feb 23 12:44:24 ubuntu20-da2a10 kata[107824]: time="2023-02-23T12:44:24.116267783Z" level=debug msg="PullImage() end" image="quay.io/kata-containers/confidential-containers:unsigned" name=containerd-shim-v2 pid=107824 sandbox=8ac939474861930bdf5315624a02531803bb95041371704bdf2399a8a264d9f3 source=containerd-kata-shim-v2
> > ```
> 
> Please add feature `"signature-simple"` to the features of `[target.'cfg(not(target_arch = "s390x"))'.dependencies]`

I've added signature-simple, but maybe we need the "enclave-cc" feature?

**Comment by fidencio** [comment]
TDX QEMU failed due to spurious network, I'm rerunning that.

**Comment by fidencio** [comment]
CLH TDX also succeeded, but didn't report its result back: http://10.112.240.208:8080/job/kata-containers-CCv0-cloud-hypervisor-TDX-CRI_CONTAINERD_K8S-PR/708/console

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jepio!

**Comment by fidencio** [comment]
@jepio, please, create an issue for this one and add the `Fixes: #` to one of the commits.  I wouldn't have asked for this one if there we had not to go through the PR again in any case, but as we do have to squash some cmmits, then we can go ahead with this in order to get the Commit Message Check happy.

**Comment by fidencio** [comment]
@jepio, oops, what's the reason you got rid of the attestation-agent bump?

**Comment by jepio** [comment]
What do you mean? It's still there

**Comment by fidencio** [comment]
> What do you mean? It's still there

Ignore me, too early, my brain is not booted up yet.  I didn't notice you did the td-shim and as bump as part of the same commit.  Things are good, thanks! :-)

**Comment by stevenhorsman** [comment]
> /test-sev

Jeremi - fyi the sev trigger doesn't work (there has been discussions about this in the past, but I'm not sure if they've gone anywhere), so I just login into jenkins and rebuild the job. I'm guessing you don't have access to that, so in the short-term please ping me/Fabiano/Ryan or something who have do that rebuild. Thanks!

**Comment by stevenhorsman** [comment]
@ryansavino - the SEV tests are failing on this PR which just bumps the versions of packages we are using for the release. Can you check it out and let us know what the issue is please?
```
11:00:32 INFO: Run tests
11:00:33 1..4
11:03:13 ok 1 [cc][kubernetes][containerd][sev] Test SEV unencrypted container launch success
11:03:16 not ok 2 [cc][kubernetes][containerd][sev] Test SEV encrypted container launch failure with INVALID measurement
11:03:16 # (in test file confidential/sev.bats, line 394)
11:03:16 #   `measurement=$(generate_firmware_measurement_with_append ${append})' failed
11:03:16 # Deleting previous test pods...
11:03:16 # service "unencrypted-image-tests" deleted
11:03:16 # deployment.apps "unencrypted-image-tests" deleted
11:03:16 # pod/unencrypted-image-tests-86866d45b5-529nm condition met
11:03:16 # mysql: [Warning] Using a password on the command line interface can be insecure.
11:03:24 ok 3 [cc][kubernetes][containerd][sev] Test SEV encrypted container launch success with NO measurement
11:03:27 not ok 4 [cc][kubernetes][containerd][sev] Test SEV encrypted container launch success with VALID measurement
11:03:27 # (in test file confidential/sev.bats, line 463)
11:03:27 #   `measurement=$(generate_firmware_measurement_with_append "${append}")' failed
```

**Comment by jepio** [comment]
Just in case this helps: the SEV job passed yesterday (http://jenkins.katacontainers.io/job/kata-containers-CCv0-ubuntu-20.04_sev-x86_64-CC_SEV_CRI_CONTAINERD_K8S-PR/542/), the only thing I did this morning was squash 4 commits into 2.

**Comment by fitzthum** [comment]
Might be worth re-running the SEV test. This doesn't look like a typical error, but let's make sure we don't break something at the last second here. 

CC: @ryansavino

**Comment by fitzthum** [comment]
Ok, same result. Seems like maybe it's an issue with how the kernel command line is being stored. Is it possible that we have run out of space in `/tmp` on the milan node? Can we for the test to run on the other node?

@ryansavino

**Comment by fitzthum** [comment]
Oh, also possible that https://github.com/kata-containers/kata-containers/pull/6338 conflicts with https://github.com/kata-containers/tests/blob/CCv0/integration/kubernetes/confidential/sev.bats#L226

That seems likely to be an issue.

**Comment by fitzthum** [comment]
https://github.com/kata-containers/tests/issues/5488

I will make PR shortly

**Comment by fidencio** [comment]
Cloud Hypervisor CI didn't report back, but it's green: http://10.112.240.208:8080/job/kata-containers-CCv0-cloud-hypervisor-TDX-CRI_CONTAINERD_K8S-PR/725/

**Comment by stevenhorsman** [comment]
Latest SEV tests failed with:
```
09:04:25 Install Kubernetes components
09:04:25 Warning: apt-key output should not be parsed (stdout is not a terminal)
09:04:26 gpg: no valid OpenPGP data found.
09:04:26 [install_kubernetes.sh:32] ERROR: sudo apt-key add -
09:04:26 [jenkins_job_build.sh:251] ERROR: ci/setup.sh
```
I *think* it's a networking flake, so have re-queued it.

**Comment by fidencio** [comment]
> I _think_ it's a networking flake, so have re-queued it.

Nops, this is happening with a bunch of upstream jobs as well. :-/

**Comment by stevenhorsman** [comment]
> > I _think_ it's a networking flake, so have re-queued it.
> 
> Nops, this is happening with a bunch of upstream jobs as well. :-/

Maybe related to https://github.com/GoogleCloudPlatform/gcsfuse/issues/961 ?

**Comment by stevenhorsman** [comment]
Rumours are that the google cloud problem is fixed, so I'll re-run the sev tests

**Pull request merged**
