### PR TITLE
stable-2.3: cgroups systemd fix

### PR DESCRIPTION
**Pull request by snir911**
bcf181b7 cgroups: Fix systemd cgroup support
b34ed403 cgroups: pass vhost-vsock device to cgroup
7362e1e8 runtime: remove prefix when cgroups are managed by systemd
(once https://github.com/kata-containers/kata-containers/pull/2959 is merged)

### CODE REVIEW

**Comment by snir911** [comment]
@fidencio it seems the no-backport-needed lable is required, however, adding **do-not-merge** until https://github.com/kata-containers/kata-containers/pull/2959 is in

**Comment by snir911** [comment]
No, i was wrong, is it failing because https://github.com/kata-containers/kata-containers/pull/2959 is not merged? error isn't clear

**Comment by snir911** [comment]
I accidentally opened the same PR earlier against main (#3018), i closed the PR, it seems like the porting checks are done against this wrong closed PR for some reason 
```
Run pr=3018
  pr=3018
  repo=kata-containers/kata-containers
  
  pr-porting-checks.sh "$pr" "$repo"
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_TOKEN: ***
Error: Cannot determine details for PR 3018
Error: Process completed with exit code 1.

**Comment by wainersm** [comment]
> I accidentally opened the same PR earlier against main (#3018), i closed the PR, however, it seems like the porting checks are done against this wrong closed PR for some reason
> 

I suspect it happens because you are using the same branch (`stable-2.3-cgroups-systemd-fix`) on the new PR. Maybe it is a bug on github; maybe `.github/workflows/require-pr-porting-labels.yaml` has read the PR number from the wrong property. Need to investigate.

Could you try to use a different branch?

**Review by gkurz — APPROVED** [review]
LGTM (i.e. same changes as in main)

Side-note, it would help to have the "(cherry pick from commit XXX)" string in each commit in order to automate the comparison with the original changes in main.

**Comment by snir911** [comment]
For the record:
* changing the branch name didn't help, `github.event.number` seemed to be wrong, after couple of days I changed the commit msgs to change the hashes and forcibly pushed, the porting check didn't run
* Porting checks should not run on the stable branch (fc42dc07cfb7c0bf22a195aba9e4d6c5301e9f11), probably something was messed due to the same PR and commit hashes i accidentally pushed on the main earlier (and closed)

**Pull request closed without merging**
