### PR TITLE
action: ignore 'fixes check' for subsystem 'release'

### LINKED ISSUE #754: The 'fixes check' should ignore for subsystem release
The check in go version used to ignore this, reported by @bergwolf

### PR DESCRIPTION
**Pull request by Tim-Zhang**
Fixes #754

Signed-off-by: Tim Zhang <tim@hyper.sh>

### CODE REVIEW

**Review by bergwolf — APPROVED** [review]
Thanks @Tim-Zhang !

**Review by jodh-intel — APPROVED** [review]
Thanks @Tim-Zhang.

**Pull request merged**
