### PR TITLE
virtiofsd: change cache mod to const

### PR DESCRIPTION
**Pull request by liubin**
Change cache mod from literal to const and place them in one place.

Also set default cache mode from `none` to `never` in `pkg/katautils/config-settings.go.in`.

Fixes: #6151

Signed-off-by: Bin Liu <bin@hyper.sh>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @liubin!

**Review by amshinde — APPROVED** [review]

**Review by Tim-Zhang — APPROVED** [review]

**Pull request merged**
