### PR TITLE
remove ProcessListContainer API

### PR DESCRIPTION
**Pull request by liubin**
This commit will remove ProcessListContainer API from VCSandbox
and ListProcesses from agent.proto.
    
Fixes: #1668

Signed-off-by: bin <bin@hyper.sh>

### CODE REVIEW

**Comment by fidencio** [comment]
@liubin, is it okay if I hold this one and merge it after 2.1.0-alpha2 is out?

**Comment by liubin** [comment]
> @liubin, is it okay if I hold this one and merge it after 2.1.0-alpha2 is out?

@fidencio it's no problem to hold this, it's not a bug, so has a low priority.
I have added a `do-not-merge` label.

**Comment by fidencio** [comment]
Thanks a lot, @liubin!

**Review by fidencio — APPROVED** [review]
lgtm, thanks @liubin!

**Review by lifupan — APPROVED** [review]

**Pull request merged**
