### PR TITLE
initdata: add initdata annotation in hypervisor config

### PR DESCRIPTION
**Pull request by huoqifeng**
- Add Initdata annotation for hypervisor config, so that it can be passed when CreateVM following [initdata](https://github.com/confidential-containers/trustee/blob/main/kbs/docs/initdata.md)
    
Signed-off-by: Qi Feng Huo <huoqif@cn.ibm.com>

### CODE REVIEW

**Comment by huoqifeng** [comment]
@Xynnn007 @fitzthum @mkulke @stevenhorsman here is change to enable kata passing initdata annotations to PeerPod.

**Review by Xynnn007 — APPROVED** [review]
LGTM. io.katacontainers.config.runtime.cc_init_data` is a good choice and let's follow this.

cc @arronwy

**Comment by huoqifeng** [comment]
kata/ci maintainers, are these errors known issue today? Looks these errors are not related with the change.

- containerd `TestContainerRestart`
```
=== RUN   TestContainerRestart
    container_restart_test.go:29: Create a pod config and run sandbox container
E0711 16:31:14.254655   21206 remote_runtime.go:135] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: Others("failed to handle message try init runtime instance\n\nCaused by:\n    0: init runtime handler\n    1: start sandbox\n    2: connect\n    3: connect agent server\n    4: connect\n    5: cannot connect to agent ttrpc server ConnectConfig { dial_timeout_ms: 10, reconnect_timeout_ms: 3000 }"): unknown
    main_test.go:233: 
        	Error Trace:	/home/runner/work/kata-containers/kata-containers/containerd/integration/main_test.go:233
        	            				/home/runner/work/kata-containers/kata-containers/containerd/integration/container_restart_test.go:30
        	Error:      	Received unexpected error:
        	            	rpc error: code = Unknown desc = failed to create containerd task: failed to create shim task: Others("failed to handle message try init runtime instance\n\nCaused by:\n    0: init runtime handler\n    1: start sandbox\n    2: connect\n    3: connect agent server\n    4: connect\n    5: cannot connect to agent ttrpc server ConnectConfig { dial_timeout_ms: 10, reconnect_timeout_ms: 3000 }"): unknown
        	Test:       	TestContainerRestart
--- FAIL: TestContainerRestart (6.75s)
```

- `shared_fs`: unbound variable
```
/home/runner/work/kata-containers/kata-containers/tests/integration/nydus/../../common.bash: line 177: shared_fs: unbound variable
/home/runner/work/kata-containers/kata-containers/tests/integration/nydus/../../common.bash: line 80: shared_fs: unbound variable
/home/runner/work/kata-containers/kata-containers/tests/integration/nydus/../../common.bash: line 80: shared_fs: unbound variable
[nydus_tests.sh:177] ERROR: SHARED_FS=
``` 

- failed to create shim task
```
time="2024-07-11T16:32:01Z" level=warning msg="cannot set cgroup manager to \"systemd\" for runtime \"io.containerd.kata-cloud-hypervisor.v2\""
time="2024-07-11T16:32:17Z" level=fatal msg="failed to create shim task: Others(\"failed to handle message try init runtime instance\\n\\nCaused by:\\n    0: init runtime handler\\n    1: start sandbox\\n    2: connect\\n    3: connect agent server\\n    4: connect\\n    5: cannot connect to agent ttrpc server ConnectConfig { dial_timeout_ms: 10, reconnect_timeout_ms: 3000 }\"): unknown"
```

- [run_kubernetes_tests.sh:115] INFO: Executing k8s-nginx-connectivity.bats
```
#   `kubectl wait --for=condition=Available --timeout=$timeout deployment/${deployment}' failed
```

CC @stevenhorsman @BbolroC

**Comment by stevenhorsman** [comment]
Yes - we have various issues with the CI at the moment. My recommendation is to wait until it stabilises and then rebase your branch to pick up the latest fixes.

**Comment by stevenhorsman** [comment]
Closing and re-opening the PR to re-trigger all the tests

**Review by ChengyuZhu6 — COMMENTED** [review]
@huoqifeng Could you please add unit tests with `InitData` to the `TestAddRuntimeAnnotations` function in `utils_test.go`?

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @huoqifeng

**Review by ChengyuZhu6 — APPROVED** [review]
LGTM thanks @huoqifeng. Let’s wait for TDX CI to pass.

**Review by ChengyuZhu6 — COMMENTED** [review]
```
utils_test.go:779:2: ineffectual assignment to err (ineffassign)
	err = addAnnotations(ocispec, &sbConfig, runtimeConfig)
```
You may need to fix the error @huoqifeng

**Pull request merged**
