### PR TITLE
runtime: packaging: Use confidential kernel instead of the TDX one

### PR DESCRIPTION
**Pull request by fidencio**
We've been building a 6.7 kernel for some time and it can be used for all the TEEs.  For now I'm just enabling this for TDX, at least till the SEV / SNP CIs are up and running again.

### CODE REVIEW

**Review by danmihai1 — APPROVED** [review]

**Review by portersrc — APPROVED** [review]
looks good

**Comment by fidencio** [comment]
I'm adding a `do-not-merge  as Ryan wants to test a few things outside of the CI.

**Comment by fidencio** [comment]
Folks, I've dropped the AMD bits from here in order to have this one moving,

**Review by zvonkok — APPROVED** [review]
LGTM, thanks!

**Review by ryansavino — APPROVED** [review]
LGTM.
Just a brief update here based on the slack discussion:
There is a SNP guest kernel patch in the current AMDESE/linux fork for a bug that addresses an issue when more than 1 TB is allocated for a guest. This will get pulled in when we update to a newer kernel at a later point in time.

**Comment by ryansavino** [comment]
@niteeshkd we should make sure to rebase your forked branch once this gets into main.

**Comment by fidencio** [comment]
> LGTM.
> Just a brief update here based on the slack discussion:
> There is a SNP guest kernel patch in the current AMDESE/linux fork for a bug that addresses an issue when more than 1 TB is allocated for a guest. This will get pulled in when we update to a newer kernel at a later point in time.

Cool, I've re-add the AMD related bits to this PR. Thanks.

**Pull request merged**
