### PR TITLE
CCv0|osbuilder: support to build Centos8.4 rootfs

### LINKED ISSUE #2873: CCv0 | rootfs - Need to add CentOS 8.4 into supported OS list
# Description of problem
- As CentOS, currently rootfs build script only support CentOS 7. But we need to build a guest rootfs image that can be used inside TDX environment. And currently TDX's offical MVP package only supports CentOS 8.4. And we also don't sure whether TDX will support CentOS 7 in future.

# Proposal
- In order to let CCv0 also workable inside TDX, it needs to extend the rootfs build script supported OS list to include CentOS 8.4 also.

### PR DESCRIPTION
**Pull request by wllenyj**
Fixes #2873

Signed-off-by: wanglei01 <wllenyj@linux.alibaba.com>

### CODE REVIEW

**Comment by fidencio** [comment]
> > But also, since [CentOS Linux goes EOL in 3 months](https://www.centos.org/centos-linux) should we be adding a config for CentOS Stream or a CentOS variant (such as AlmaLinux or Rocky Linux) instead?
> 
> Sorry, I haven't build other CentOS variant, I think it should be possible if their package management tools are the same and there is a basic Docker Image.

You can find the container images at https://quay.io/repository/centos/centos?tab=tags and I think the recommended way would be to follow one of the paths:
* Use CentOS Stream 8
* Use one of the RHEL forks (Alma, Rocky, for instance)
* Use RHEL for developers and its UBI image (which may be for free depending on the use case).

As James mentioned we'll need to evaluate what to do with the CentOS based CIs sooner than later, and I'll take care of opening an issue for that by the beginning of the next week.

**Comment by jodh-intel** [comment]
Any update on this @wllenyj?

**Comment by Jakob-Naucke** [comment]
@jodh-intel yes, the "community" version of RHEL for s390x used to be ClefOS maintained up to version 7, but CentOS 9 appears to be coming (currently in Stream).

**Comment by jodh-intel** [comment]
@Jakob-Naucke - ack. Does this mean we can't move to CentOS Stream currently then? I've just checked Alma and Rocky and it looks like both are only currently available for x86_64 and aarch64.

**Comment by jodh-intel** [comment]
@Jakob-Naucke - Stream 8 seems like the best option generally (since presumably it's the closest to CentOS 8) even though it is architecture restricted currently. I guess this doesn't change the situation much for s390x (see https://github.com/kata-containers/kata-containers/tree/main/tools/osbuilder#platform-distro-compatibility-matrix), but you can indicate your views via an ack/nack on this PR of course.

**Comment by Jakob-Naucke** [comment]
General ack -- I think we should try to move to CentOS 8 Stream overall then. As this is upon `CCv0`, it has some time to settle anyway.

**Comment by fidencio** [comment]
> > You can find the container images at https://quay.io/repository/centos/centos?tab=tags and I think the recommended way would be to follow one of the paths:
> > 
> > * Use CentOS Stream 8
> > * Use one of the RHEL forks (Alma, Rocky, for instance)
> > * Use RHEL for developers and its UBI image (which may be for free depending on the use case).
> > 
> > As James mentioned we'll need to evaluate what to do with the CentOS based CIs sooner than later, and I'll take care of opening an issue for that by the beginning of the next week.
> > EDITED: CentOS Stream 8 used `dnf` as CentOS 8 does.
> 
> like this that you mean ? `FROM quay.io/centos/centos:stream8`

Exactly!

**Comment by Jakob-Naucke** [comment]
so @wllenyj can we move this to stream then?

**Comment by jodh-intel** [comment]
Any update @wllenyj ?

**Comment by Jakob-Naucke** [comment]
might be superseded by #3328/#3341

**Comment by wllenyj** [comment]
@jodh-intel @Jakob-Naucke Merry Christmas.

About #2873, Now it is compatible with ubuntu. So Centos is not necessary.

**Comment by jodh-intel** [comment]
Thanks @wllenyj ! Closing...

**Pull request closed without merging**
