### PR TITLE
doc: update kata metrics documentation

### PR DESCRIPTION
**Pull request by fgiudici**
We support any CRI compliant container engine with kata-monitor: update the documentation (and the associated image) to reflect that.
In the meanwhile, fixed a couple of typos and added few minor changes.

### CODE REVIEW

**Comment by fgiudici** [comment]
Hey @liubin , if/when you have time, please take a look if this makes sense.
Thanks!

**Comment by cmaf** [comment]
Hi @fgiudici, could you create an issue for this PR and add the `Fixes: #xxxx` to the commit message?

**Review by liubin — APPROVED** [review]
LGTM.
And please fix the GitHub actions errors.

**Comment by fgiudici** [comment]
> Hi @fgiudici, could you create an issue for this PR and add the `Fixes: #xxxx` to the commit message?
Yeah, thanks @cmaf, I forgot to reference an open issue. Instead of opening a new one I referred to the CRI-O support in kata-monitor issue which is still open. Implementation is already merged, with this PR we will have also updated documentation.

**Comment by fgiudici** [comment]
> LGTM. And please fix the GitHub actions errors.

Sure! Thanks @liubin for the quick review :-)

**Review by cmaf — APPROVED** [review]
thanks @fgiudici

**Pull request merged**
