### PR TITLE
kernel: add missing config fragment for TDx

### LINKED ISSUE #3659: kernel: add tdx config fragment
Add kernel config fragment that enables Intel TDx

### PR DESCRIPTION
**Pull request by devimc**
Add kernel config fragment that enables TDx

fixes #3659

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @devimc.

lgtm

**Review by fidencio — APPROVED** [review]
lgtm, thanks @devimc!

**Review by egernst — APPROVED** [review]

**Pull request merged**
