### PR TITLE
kernel: add CONFIG_KEYS=y to enable kernel keyring

### PR DESCRIPTION
**Pull request by Crypt0s**
Adding `CONFIG_KEYS=y` to the kernel configuration of Kata will allow Kata container runtimes using the kernel to support technologies such as Kubernetes in Docker (KinD), allowing Kata to power end-to-end testing.

### CODE REVIEW

**Comment by fidencio** [comment]
Also, I'd say it'd be good to explain why KinD use cases require the retention of the authentication tokens, and possible drawbacks on enabling it (if possible) :-)

**Comment by Crypt0s** [comment]
Thanks for the feedback!

I've bumped the `kata_config_version` and squashed the commit and shortened the commit message.  
Regarding the KinD use cases:

KinD (and I believe other similar projects such as K3s) checks for the presence of this (and other) kernel configuration via scripts like https://blog.hypriot.com/post/verify-kernel-container-compatibility/ or attempts to directly use `/proc/sys/kernel/keys/` without checking to see if it exists, causing an exit when it does not see it.

Docker/it's consumers apparently expect to be able to use the kernel keyring and it's associated syscalls from/for containers.

There aren't any known (to me) downsides to enabling this except that it would by definition enable additional syscalls defined in https://man7.org/linux/man-pages/man7/keyrings.7.html which are reachable from userspace.  This minimally increases the attack surface of the Kata Kernel, but this attack surface is minimal (especially since the kernel is most likely being executed by some kind of hypervisor) and highly restricted compared to the utility of enabling this feature to get further containerization compatibility.

**Comment by fidencio** [comment]
I've adjusted the commit message to make it as clear as possible for someone looking at the git history (without the need to revisit the issues; and I also adjusted the SoB line as it has to match the author's one.

With this done, CI is running, and as long as it doesn't cause any issues there (and it shouldn't) we'll try get it merged before the next release.

**Review by stevenhorsman — APPROVED** [review]
This seems reasonable to me. Thanks and welcome @Crypt0s!

**Comment by mythi** [comment]
> Docker/it's consumers apparently expect to be able to use the kernel keyring and it's associated syscalls from/for containers.

I think it's worth pointing out that these are still blocked by [Docker's default seccomp policies](https://docs.docker.com/engine/security/seccomp/#significant-syscalls-blocked-by-the-default-profile) so these consumers must know what they are doing to avoid keys being leaked (e.g., root user keyring is the same of all containers from kernel's pow).

**Pull request merged**
