### PR TITLE
vc: remove swagger binary

### PR DESCRIPTION
**Pull request by zhsj**
Fix: #3362

### CODE REVIEW

**Review by bergwolf — APPROVED** [review]
Nice catch, thanks!

**Review by liubin — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Yowzers! Good catch @zhsj!

lgtm

**Comment by jodh-intel** [comment]
Re-starting the failing CI's which fell over with what I hope is a transitory comms error:

```
09:53:31 hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- https://github.com/kata-containers/kata-containers.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
09:53:31 stdout: 
09:53:31 stderr: fatal: unable to access 'https://github.com/kata-containers/kata-containers.git/': OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104
```

/retest-fedora
/retest-centos
/retest-clh-k8s-containerd

**Comment by jodh-intel** [comment]
Further info on the the SSL error: https://github.com/kata-containers/tests/issues/4307

**Pull request merged**
