### PR TITLE
runtime: clear virtcontainers cgroup duplicated function

### PR DESCRIPTION
**Pull request by YchauWang**
There are `DeviceToDeviceCgroup` and `deviceToDeviceCgroup` two functions,
 creating a `specs.LinuxDeviceCgroup` object. We clear the new function `deviceToDeviceCgroup`.

Fixes: #2694

Signed-off-by: wangyongchao.bj <wangyongchao.bj@inspur.com>

### CODE REVIEW

**Review by cmaf — APPROVED** [review]
lgtm @YchauWang

**Comment by YchauWang** [comment]
There are some errors about the CI test:
centos/fedora:
'''
14:33:39  > git init /tmp/jenkins/workspace/kata-containers-2.0-centos-PR # timeout=10
14:33:39 ERROR: Error cloning remote repo 'origin'
14:33:39 hudson.plugins.git.GitException: Could not init /tmp/jenkins/workspace/kata-containers-2.0-centos-PR
14:33:39 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$5.execute(CliGitAPIImpl.java:1048)
14:33:39 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:803)
14:33:39 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:160)
14:33:39 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$GitCommandMasterToSlaveCallable.call(RemoteGitImpl.java:153)
14:33:39 	at hudson.remoting.UserRequest.perform(UserRequest.java:211)
14:33:39 	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
14:33:39 	at hudson.remoting.Request$2.run(Request.java:376)
14:33:39 	at hudson.remoting.InterceptingExecutorService.lambda$wrap$0(InterceptingExecutorService.java:78)
14:33:39 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
14:33:39 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
14:33:39 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
14:33:39 	at java.lang.Thread.run(Thread.java:748)
'''

ubuntu:
'''
22:46:32 [install_qemu.sh:70] INFO: Installing cached QEMU
22:46:32 #=#=#                                                                         

                                                                           0.0%
                                                                           0.3%
                                                                           1.3%
###                                                                        4.6%
######                                                                     9.1%
##########                                                                14.2%
#############                                                             19.0%
#################                                                         24.3%
####################                                                      28.4%
#######################                                                   32.7%
##########################                                                37.1%
#############################                                             41.6%
#################################                                         46.3%
##################################                                        48.1%
##################################                                        48.1%
##################################                                        48.2%
##################################                                        48.3%
###################################                                       48.7%
####################################                                      50.2%
######################################                                    53.6%
#########################################                                 57.3%
############################################                              61.3%
##############################################                            64.3%
##############################################                            64.5%curl: (18) transfer closed with 6181655 bytes remaining to read
22:46:32 
22:48:28 [install_qemu.sh:153] ERROR: return 1
22:48:28 [jenkins_job_build.sh:170] ERROR: ci/setup.sh
'''

@devimc, Cloud you help me exec the `retest`, thanks!

**Review by bergwolf — APPROVED** [review]

**Review by liubin — APPROVED** [review]

**Pull request merged**
