### PR TITLE
release: Bump version to 3.9.0

### PR DESCRIPTION
**Pull request by emanuellima1**
Starting the v3.9.0 release

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
LGTM once ready. Thanks!

**Comment by fidencio** [comment]
Should https://github.com/kata-containers/kata-containers/blob/4d11fecc2d8b12cb8d01e10fa50bc7fb874f8d02/tools/packaging/kata-deploy/helm-chart/kata-deploy/Chart.yaml#L18-L24 be bumped as well?

**Comment by stevenhorsman** [comment]
> Should
> 
> https://github.com/kata-containers/kata-containers/blob/4d11fecc2d8b12cb8d01e10fa50bc7fb874f8d02/tools/packaging/kata-deploy/helm-chart/kata-deploy/Chart.yaml#L18-L24
> 
> be bumped as well?

Good point - I added it as a discussion point in the AC and then forgot about it!

**Comment by emanuellima1** [comment]
Bumped Helm chart as well

**Review by fidencio — APPROVED** [review]
lgtm, thanks @emanuellima1!

**Comment by fidencio** [comment]
It doesn't make sense to have all the set of tests running for the PR, so just taking advantage of admin powers and merging it!

**Pull request merged**
