### PR TITLE
deploy: fix shell script error

### PR DESCRIPTION
**Pull request by stevenhorsman**
- Remove local introduced by bad copy-paste

Fixes: #6814
Signed-off-by: stevenhorsman <steven@uk.ibm.com>
(cherry picked from commit 1a3f8fc1a23297230b4a9fe532232a753ae2701a)

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @stevenhorsman!

**Comment by stevenhorsman** [comment]
@arronwy or @fidencio - the tdx is pending here. Can you let us know if it's just the reporting back that went wrong and/or if I can just merge this anyway as it isn't TDX specific code. Thanks!

**Comment by stevenhorsman** [comment]
Given this is a minor bug fix that has been code reviewed and the tdx job reporting is a bit flakey I'm going to merge this to unblock downstream work.

**Pull request merged**
