### PR TITLE
kubernetes: add agnhost command in pod yaml

### PR DESCRIPTION
**Pull request by LindaYu17**
Fixes: #6928

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @LindaYu17!

/cc @arronwy

**Review by fidencio — APPROVED** [review]
lgtm, thanks @LindaYu17!

/cc @arronwy

**Review by arronwy — APPROVED** [review]
Thanks @LindaYu17 , LGTM!

**Pull request merged**
