### PR TITLE
[stable-2.5] backport security related dependency commits

### PR DESCRIPTION
**Pull request by bergwolf**
Taken from https://github.com/kata-containers/kata-containers/pull/4930 and https://github.com/kata-containers/kata-containers/pull/4969

69505695b agent-ctl/trace-forwarder: udpate thread_local dependency
48a94f36a agent/runk: update regex dependency
1a396a178 dep: update nix dependency

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @bergwolf!

**Comment by fidencio** [comment]
```
Package python is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python2-minimal python2 dh-python 2to3 python-is-python3
```

This is from the Ubuntu CI.

**Comment by fidencio** [comment]
> ```
> Package python is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> However the following packages replace it:
>   python2-minimal python2 dh-python 2to3 python-is-python3
> ```
> 
> This is from the Ubuntu CI.

https://github.com/kata-containers/tests/pull/5092

**Comment by fidencio** [comment]
Okay, the issue with Ubuntu will be fixed as soon as https://github.com/kata-containers/tests/pull/5093 gets merged.

**Comment by fidencio** [comment]
/test-ubuntu

`jenkins-ci-ubuntu-22-04` should be ignored as cgroupsv2 is not supported by Kata Containers 2.5

**Comment by fidencio** [comment]
@littlejawa, would you have some cycles to debug the CRI-O issues?

**Comment by littlejawa** [comment]
> @littlejawa, would you have some cycles to debug the CRI-O issues?

It is failing on a `kubectl wait` call.
It seems retrieving the image took longer than the timeout. The logs says:

```
14:31:09 #   Normal   Pulling    5s (x8 over 88s)  kubelet            Pulling image "quay.io/kata-containers/fsnotify:latest"
14:31:09 #   Warning  Failed     5s (x8 over 83s)  kubelet            Error: CreateContainer failed: unable to write to a control group file caused by: Os { code: 95, kind: Uncategorized, message: "Not supported" }: unknown
14:31:09 #   Normal   Pulled     5s                kubelet            Successfully pulled image "quay.io/kata-containers/fsnotify:latest" in 170.502246ms
```

The timeout for the kubectl call is 90s, and apparently, it failed for (at least) 88s if I understand the logs correctly.
Now I'm not sure: I'm not familiar with the reported error - not sure why it would suddenly work if it was previously "not supported"? Am I missing something?

**Review by amshinde — APPROVED** [review]

**Comment by amshinde** [comment]
I am seeing this error in the ubuntu 20.04 CI: 
```
error: failed to compile `kata-trace-forwarder v0.0.1 (/tmp/jenkins/workspace/kata-containers-2.0-ubuntu-20.04-PR/go/src/github.com/kata-containers/kata-containers/src/tools/trace-forwarder)`, intermediate artifacts can be found at `/tmp/jenkins/workspace/kata-containers-2.0-ubuntu-20.04-PR/go/src/github.com/kata-containers/kata-containers/src/tools/trace-forwarder/target`

Caused by:
  package `time v0.3.14` cannot be built because it requires rustc 1.59.0 or newer, while the currently active rustc version is 1.58.1
++ handle_error 1329
++ local exit_code=101
++ local line_number=1329
+++ basename functional/tracing/test-agent-shutdown.sh
+++ eval echo 'cargo install --path .'
++++ echo cargo install --path .
```

**Comment by amshinde** [comment]
@fidencio I think the crio issue is a cgroupsv2 error. Afaik, fedora 35 uses cgroupsv2 as well.

**Pull request merged**
