### PR TITLE
image_rpc: Add container_count for containers without cid

### PR DESCRIPTION
**Pull request by arronwy**
If cid is empty, we will use image name as default cid, and `image-rs` will use `cid` as bundle directory name for each container, to support multiple containers with same image, we need append unique id to the image name.

Fixes: #6456

### CODE REVIEW

**Comment by arronwy** [comment]
@stevenhorsman @fidencio  can you help review this PR?

**Review by stevenhorsman — APPROVED** [review]
The code looks okay to me, running the tests now...

**Comment by stevenhorsman** [comment]
SEV tests failed with:
```
09:25:05 E: The repository 'http://apt.kubernetes.io/ kubernetes-xenial-unstable Release' no longer has a Release file.
```
/test-sev

**Comment by fidencio** [comment]
http://jenkins.katacontainers.io/job/kata-containers-CCv0-ubuntu-20.04_sev-x86_64-CC_SEV_CRI_CONTAINERD_K8S-PR/642/ is green, I'm merging it.

**Pull request merged**
