### PR TITLE
agent: collect PCI address mapping for both vfio-pci-gk and vfio-pci device

### PR DESCRIPTION
**Pull request by l8huang**
The `update_env_pci()` function need the PCI address mapping to translate the host PCI address to guest PCI address in below environment variables:

- `PCIDEVICE_<prefix>_<resource-name>_INFO`
- `PCIDEVICE_<prefix>_<resource-name>`

Fixes https://github.com/kata-containers/kata-containers/issues/9614

### CODE REVIEW

**Review by lifupan — APPROVED** [review]
LGTM

**Review by zvonkok — APPROVED** [review]
LGTM, thanks!

**Review by cmaf — COMMENTED** [review]
@l8huang could you add the Fixes  line in the commit per our contributing guide?

https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#closing-issues

**Comment by l8huang** [comment]
@cmaf thanks for the heads up, commit updated.

**Pull request merged**
