### PR TITLE
runk: Move delete logic to libcontainer

### PR DESCRIPTION
**Pull request by ManaSugi**
Move delete logic to `libcontainer` crate to make the code clean
like other commands.

Fixes: #4975

Signed-off-by: Manabu Sugimoto <Manabu.Sugimoto@sony.com>

### CODE REVIEW

**Review by liubin — APPROVED** [review]

**Review by cyyzero — APPROVED** [review]
LGTM

**Review by fidencio — APPROVED** [review]
lgtm, thanks @ManaSugi!

**Pull request merged**
