### PR TITLE
osbuilder: update dockerfiles to utilize IMAGE_REGISTRY

### PR DESCRIPTION
**Pull request by egernst**
While we introduced IMAGE_REGISTRY, we didn't actually update the
corresponding Dockerfiles to utilize it. Let's add

Fixes: #1622

Signed-off-by: Eric Ernst <eric.g.ernst@gmail.com>

### CODE REVIEW

**Review by cmaf — APPROVED** [review]

**Review by sameo — APPROVED** [review]

**Review by likebreath — APPROVED** [review]

**Comment by egernst** [comment]
restarting http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-initrd-PR/801/ -- flake for OOM test.

**Review by ganeshmaharaj — APPROVED** [review]

**Pull request merged**
