### PR TITLE
kata-deploy: Support containerd configuration version 3

### PR DESCRIPTION
**Pull request by fidencio**
As Ubuntu seems to already be shipping a containerd version that uses version 3 as its default version.

### CODE REVIEW

**Comment by zvonkok** [comment]
Some k8s distribution have yet another drop-in conf path than the default `/etc/containerd/....`  for the start we can use this as is. The configurable drop-in conf path may also need to end up in the Helm chart as a configurable value.

**Review by zvonkok — APPROVED** [review]
LGTM thanks!

**Comment by fidencio** [comment]
> Some k8s distribution have yet another drop-in conf path than the default `/etc/containerd/....` for the start we can use this as is. The configurable drop-in conf path may also need to end up in the Helm chart as a configurable value.

Keep in mind that right now it's just adapting to version 3, I have another PR to be opened that we can rely on to start using drop-in files (and there I'm just setting them up as part of the `/opt/kata/containerd/....` as containerd only requires the path of the file, and that's it.

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks @fidencio!

**Pull request merged**
