### PR TITLE
Revert "kata-deploy: Rely on the configured config path"

### PR DESCRIPTION
**Pull request by fidencio**
This reverts commit f7ccf92dc82e9264fafd0ccf565f6dd014786e3e.

### CODE REVIEW

**Comment by egernst** [comment]
Happy if it works in your testing, but I'm curious to understand what changed / why this is needed.

**Comment by fidencio** [comment]
> Happy if it works in your testing, but I'm curious to understand what changed / why this is needed.

Right now we're not even sure if this is actually needed., but this is the only change done recently that could cause the issues faced by @bergwolf when cutting the 3.0.0-alpha0 release.

It also makes me think that, **maybe**, the script used to by kata-deploy to do the needed changes in the host may not actually be used as part of the CI, but this needs proper investigation.

**Comment by fidencio** [comment]
I'm adding a `do-not-merge` label for now till we find some time to properly debug the issue.

**Comment by fidencio** [comment]
Closing this one as kata-deploy does work on my local environment without this change.

**Pull request closed without merging**
