### PR TITLE
kata-deploy: Add cri-o support

### PR DESCRIPTION
**Pull request by stevenhorsman**
Add support for cri-o into kata-deploy and merge in CAA features

Fixes: #6351

### CODE REVIEW

**Comment by stevenhorsman** [comment]
I'm a little out of my knowledge here, but this is my attempt at merging the extra code from CAA's fork of kata-deploy in. I think it's mostly the cri-o support and we might need to also modify the default-shim to be remote for peer pods? /cc @fidencio @bpradipt

**Review by fidencio — APPROVED** [review]
lgtm, thanks @stevenhorsman!

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @stevenhorsman 
Once this gets merged and kata-deploy payload has the required config, this entire [folder] (https://github.com/confidential-containers/cloud-api-adaptor/tree/staging/install/runtime-payload) can be deleted.

**Comment by stevenhorsman** [comment]
@UnmeshDeodhar @ryansavino - I'm seeing sev test failures on this PR test which seems unrelated to the changes? Is this a known issue?
```
11:16:21 [init.sh:34] INFO: Taint 'NoSchedule' is found. Untaint the node so pods can be scheduled.
11:16:21 node/amd-coco-ci-ubuntu2004-001 untainted
11:16:21 INFO: Run tests
11:16:21 1..4
11:16:22 ok 1 [cc][kubernetes][containerd][sev] Test SEV unencrypted container launch success
11:19:32 ok 2 [cc][kubernetes][containerd][sev] Test SEV encrypted container launch failure with INVALID measurement
11:19:57 not ok 3 [cc][kubernetes][containerd][sev] Test SEV encrypted container launch success with NO measurement
11:20:20 # (from function `esudo' in file confidential/sev.bats, line 35,
11:20:20 #  from function `kubernetes_wait_for_pod_ready_state' in file confidential/sev.bats, line 74,
11:20:20 #  in test file confidential/sev.bats, line 430)
11:20:20 #   `kubernetes_wait_for_pod_ready_state "$pod_name" 20' failed
11:20:20 # Deleting previous test pods...
11:20:20 # service "encrypted-image-tests" deleted
11:20:20 # deployment.apps "encrypted-image-tests" deleted
11:20:20 # pod/encrypted-image-tests-68b98bc8f8-pdvwl condition met
11:20:20 # mysql: [Warning] Using a password on the command line interface can be insecure.
11:20:20 # mysql: [Warning] Using a password on the command line interface can be insecure.
11:20:20 # service/encrypted-image-tests created
11:20:20 # deployment.apps/encrypted-image-tests created
11:20:20 # error: timed out waiting for the condition on pods/encrypted-image-tests-68b98bc8f8-2d2ql
11:20:20 not ok 4 [cc][kubernetes][containerd][sev] Test SEV encrypted container launch success with VALID measurement
11:20:42 # (from function `esudo' in file confidential/sev.bats, line 35,
11:20:42 #  from function `kubernetes_wait_for_pod_ready_state' in file confidential/sev.bats, line 74,
11:20:42 #  in test file confidential/sev.bats, line 467)
11:20:42 #   `kubernetes_wait_for_pod_ready_state "$pod_name" 20' failed
11:20:42 # Deleting previous test pods...
11:20:42 # service "encrypted-image-tests" deleted
11:20:42 # deployment.apps "encrypted-image-tests" deleted
11:20:42 # pod/encrypted-image-tests-68b98bc8f8-2d2ql condition met
11:20:42 # mysql: [Warning] Using a password on the command line interface can be insecure.
11:20:42 # Kernel Append: tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k cryptomgr.notests net.ifnames=0 pci=lastbus=0 console=hvc0 console=hvc1 quiet panic=1 nr_cpus=1 selinux=0 agent.aa_kbc_params=online_sev_kbc::10.216.91.122:44444 agent.config_file=/etc/agent-config.toml agent.enable_signature_verification=false
11:20:42 # Firmware Measurement: Xt4oTZuQQ2GyhHNCtw1C7bPQv/RiWnL+bYgzV2TIx2U=
11:20:42 # mysql: [Warning] Using a password on the command line interface can be insecure.
11:20:42 # service/encrypted-image-tests created
11:20:42 # deployment.apps/encrypted-image-tests created
11:20:42 # error: timed out waiting for the condition on pods/encrypted-image-tests-68b98bc8f8-bwg9h
11:20:42 [run_kubernetes_tests.sh:153] ERROR: bats confidential/sev.bats
```

**Comment by stevenhorsman** [comment]
TDX qemu tests is a known issue, so this can merge now

**Pull request merged**
