### PR TITLE
Update mod.rs

### LINKED ISSUE #6256: Typo in src/runtime-rs/crates/resource/src/cgroups/mod.rs
`ignor`

https://github.com/kata-containers/kata-containers/blob/86501d5f6f2ae3ad16e2f8630f7624386cb8ff0d/src/runtime-rs/crates/resource/src/cgroups/mod.rs#L117

### PR DESCRIPTION
**Pull request by predatorprasad**
fixed typo in line 117
changed:- 
> ignor to **ignore**.

Fixes: https://github.com/kata-containers/kata-containers/issues/6256

signed-off-by: Prasad Joshi <ppjoshi2003@gmail.com>

### CODE REVIEW

**Review by c3d — APPROVED** [review]
Thanks

**Comment by predatorprasad** [comment]
**Ensure PR has required porting labels**  what do I need to add??

**Comment by c3d** [comment]
> **Ensure PR has required porting labels** what do I need to add??

See https://github.com/kata-containers/community/blob/6221e05d9e1f453cb3a15c5fcb790e632d89611c/CONTRIBUTING.md#porting-labels for information. As an exercise, I will let you apply the one you want. If you choose "backport-needed", please also submit a backport ;-) It is not strictly necessary in this case, but feel free to do it.

**Comment by predatorprasad** [comment]
ok

**Comment by predatorprasad** [comment]
I am not able to figure out how to add Porting labels to my PR, can I get some help 😅

**Comment by c3d** [comment]
> I am not able to figure out how to add Porting labels to my PR, can I get some help 😅

Do you see the "labels" column in the top-right of the GitHub web interface? There, you click on the little gear icon
image

Then you just type a label. Try typing `no-back` and you should see the `no-backport-needed` label show up. Click on it and you should be done.

**Comment by c3d** [comment]
> fixed typo in line 117
> closes #6256

@predatorprasad you will also need to change that message so that it says "Fixes: #6256", because our tools don't recognize "closes" AFAIK.

Welcome to our little island of computer-enforced process insanity.

**Comment by predatorprasad** [comment]
Thanks a lot @c3d I will complete it

**Comment by predatorprasad** [comment]
@c3d I scrolled through in the issues and PR but I am **not able to see the Gear logo**

issue 6256

**Comment by predatorprasad** [comment]
**replaced** `closes` with `Fixes`

**Comment by fidencio** [comment]
> Do you see the "labels" column in the top-right of the GitHub web interface? There, you click on the little gear icon

This is only available to folks who are part of the org, unfortunately. :-/

**Comment by predatorprasad** [comment]
It means **someone from the org** has to add the label and then it can be merged? right...

**Comment by c3d** [comment]
So I added the flags. @fidencio I was not aware that flag setting was restricted in that way, thanks for pointing it out.

**Comment by c3d** [comment]
@predatorprasad Sorry, I think that the script is really strict about the formatting. Please take a look at another PR to see the expected format ("Fixes: ", with a colon).

**Comment by predatorprasad** [comment]
no problem 😄 I have made the necessary changes. ig now it should work

**Comment by predatorprasad** [comment]
ser 1 more review is required to merge the changes

**Pull request closed without merging**
