### PR TITLE
versions: bump versions of kubernetes and cri-o to 1.26

### PR DESCRIPTION
**Pull request by littlejawa**
Fixes: #5988

Signed-off-by: Julien Ropé <jrope@redhat.com>

### CODE REVIEW

**Comment by littlejawa** [comment]
CI failures: we need https://github.com/kata-containers/tests/pull/5363 to fix it.

**Comment by liubin** [comment]
@littlejawa  here is an error prevents the kubelet to start:

> Jan 05 19:44:15 ubuntu20-773920 kubelet[88579]: E0105 19:44:15.486288   88579 run.go:74] "command failed" err="failed to set feature gates from initial flags-based config: unrecognized feature gate: PodOverhead"

You may need to update https://github.com/kata-containers/tests/blob/bf1ec7c3002605dc64c3f7c099dc6f0b417bd093/integration/kubernetes/kubeadm/config.yaml too.

**Comment by fidencio** [comment]
This one can be closed as we've switched the way we've been testing things for CRI-O and Kata Containers in general.
Please, feel free to re-open it in case you think something has been missed.

**Pull request closed without merging**
