### PR TITLE
agent: remove redundant checks

### PR DESCRIPTION
**Pull request by Rouzip**
Remove redundant checks for executable files.

FIXes: #3730

Signed-off-by: Rouzip <1226015390@qq.com>

### CODE REVIEW

**Comment by yaoyinnan** [comment]
Thanks @Rouzip, LGTM. /test

**Review by Ji-Xinyou — APPROVED** [review]
Thanks @Rouzip , LGTM.

**Review by yaoyinnan — APPROVED** [review]

**Review by ManaSugi — APPROVED** [review]
LGTM, thanks @Rouzip!

**Review by liubin — APPROVED** [review]

**Pull request merged**
