### PR TITLE
cloud-hypervisor: Fix GetThreadIDs function

### PR DESCRIPTION
**Pull request by fengyehong**

### CODE REVIEW

**Review by rbradford — COMMENTED** [review]
Seems a perfectly reasonable way to get the PIDs of the vCPU threads.

**Review by sboeuf — APPROVED** [review]
Looks good

**Review by likebreath — COMMENTED** [review]
Thank you for the contribution. Changes look good to me. You will need to fix the GH action errors and you take this document as a reference: https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md

**Comment by fengyehong** [comment]
> Thank you for the contribution. Changes look good to me. You will need to fix the GH action errors and you take this document as a reference: https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md

Updated code and commit msg, but can not figure out why "Add PR sizing label" failed~~

**Review by fidencio — APPROVED** [review]
lgtm, thanks @fengyehong!

**Pull request merged**
