### PR TITLE
agent: vendor all the used crates

### PR DESCRIPTION
**Pull request by fidencio**
This it not different than what we've been doing for the go code, and it
does help a lot distro maintainers, as usually the build machines don't
provide access to the internet during the build time, forcing the
package maintainers to manually vendor the code themselves.

Knowing about this, let's make their life simpler by vendoring the code
ourselves, which will lead to us releasing the vendored code together
with our released tarballs.

Fixes: #1203

Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>

### CODE REVIEW

**Comment by Tim-Zhang** [comment]
Can we run cargo vendor only when packing the tarball instead of storing the vendor in the repo?

I think there are following disadvantages if we store the vendor in the repo
- The code is too much to review 
- The third-party code in our repo is meaningless and hard to maintain
- Unnecessary code changes when crates updating.

**Comment by fidencio** [comment]
@Tim-Zhang, I hear you and I agree with you.

My preference would be:
* Add a `dist` target that would do:
  * cargo vendor > .cargo/config.toml
  * create the tarball
* Make this part of the release process;

However, what we currently do is just tagging a release on GitHub and relying on GitHub to generate the tarballs and whanot.  Mind, I'm not that familiar with this process.  I do believe there's some way for us to upload the tarballs, but I have never done that.

With this in mind, I sincerely not sure what's the path to take, and how to proceed if we need changes on the way we do the releases.

@Tim-Zhang, any idea on how to proceed?

**Comment by fidencio** [comment]
Oh, I forgot about this one.

For this one we'll have to hack the scripts used as part of the release, by actually adding a `make dist` target and probably pushing our own tarballs together with the tags, as the current tarballs seem to be autogenerated by GitHub itself. :-/

For now, I'm closing this one.

**Pull request closed without merging**
