### PR TITLE
runtime: Replace TEE specific initrd / image for the confidential one

### PR DESCRIPTION
**Pull request by fidencio**
As https://github.com/kata-containers/kata-containers/pull/8983 got merged, let's switch to using the confidential image / initrd for SEV / SNP / TDX.

Fixes: #9010

### CODE REVIEW

**Review by zvonkok — APPROVED** [review]
LGTM, great work on simplifying

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks

**Review by BbolroC — APPROVED** [review]
LGTM, thanks @fidencio !

**Pull request merged**
