### PR TITLE
dragonball: convert BlockDeviceMgr and VirtioNetDeviceMgr functions to methods

### PR DESCRIPTION
**Pull request by ZhangShuaiyi**
VsockDeviceMgr::insert_device is a method. BlockDeviceMgr::insert_device and VirtioNetDeviceMgr::insert_device can convert to method too. Make the code more readable through this.

Fixes: #6880

### CODE REVIEW

**Comment by ZhangShuaiyi** [comment]
Hi, @studychao please take a look at this.

**Comment by studychao** [comment]
@ZhangShuaiyi Hi there, please fix the commit message CI error.

Please add a `fixes: #xxxx` into your commit message.

**Comment by ZhangShuaiyi** [comment]
> @ZhangShuaiyi Hi there, please fix the commit message CI error.
> 
> Please add a `fixes: #xxxx` into your commit message.

Done, Thinks.

**Review by wllenyj — APPROVED** [review]

**Comment by ZizhengBian** [comment]
LGTM, Nice Job!

**Review by ZizhengBian — APPROVED** [review]

**Review by ZizhengBian — APPROVED** [review]

**Review by ZizhengBian — APPROVED** [review]

**Comment by ZhangShuaiyi** [comment]
Hi @studychao , please take a look at this.

**Review by studychao — APPROVED** [review]
LGTM. 
Thanks! That's a really good improvement.

**Review by lifupan — APPROVED** [review]

**Pull request merged**
