### PR TITLE
CC | Rework TDX runtime configuration files

### PR DESCRIPTION
**Pull request by fidencio**
config: Set qemu-tdx as the one with eaa_kbc support

The `qemu-tdx` configuration is tied to using `offline_fs_kbc` as the
aa_kbc, which is something we're moving away from.

With this in mind, let's rename the `qemu-tdx-eaa-kbc` to `qemu-tdx` and
decrease the amount of the way too many configurations that we ship.

---

config: Drop clh-tdx-eaa-kbc configuration file

It turns out that there's more work needed to be done on the Cloud
Hypervisor side so we can fully support EAA_KBC with it.

For now, let's remove the configuration as the tests are not currently
passing when using it, and stick to the `offline_fs_kbc` and its
specific image for the Cloud Hypervisor + TDX case.

Fixes: #5862

### CODE REVIEW

**Review by arronwy — APPROVED** [review]
Thanks @fidencio ，LGTM!

**Comment by fidencio** [comment]
cc @UnmeshDeodhar:
```
14:20:00  Downloading crates ...
14:21:08 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (1 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (1 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (1 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (1 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (1 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (1 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (1 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (1 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (1 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (1 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (1 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:09 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:10 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:10 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:10 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:10 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:10 warning: spurious network error (1 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:10 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:10 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:10 warning: spurious network error (1 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:10 warning: spurious network error (1 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
14:21:10 error: failed to download from `[https://crates.io/api/v1/crates/regex-syntax/0.6.26/download`](https://crates.io/api/v1/crates/regex-syntax/0.6.26/download%60)
14:21:10 
14:21:10 Caused by:
14:21:10   [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
```

I've retriggered the build.

**Comment by fidencio** [comment]
And I retrigged the sev job again.

**Comment by BbolroC** [comment]
FYI: CI failures for s390:

1. jenkins-ci-s390x-ccv0-ubuntu-20-04: caused by https://github.com/kata-containers/kata-containers/pull/5811, the author of the PR is working on it
2. kata-containers-ubuntu-20.04-s390x-cc_cri_containerd_k8s: I am working on it with https://github.com/kata-containers/tests/issues/5314.

You could ignore them to get this PR merged. :wink:

**Pull request merged**
