### PR TITLE
CCv0: Set v0.8.0 tag for image-rs, AA and td-shim

### PR DESCRIPTION
**Pull request by portersrc**
Update toml and yaml files for v0.8.0 of image-rs, AA, and td-shim.

Fixes: [#8352](https://github.com/kata-containers/kata-containers/issues/8352)

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @portersrc

**Comment by fitzthum** [comment]
Looks like we might need guest-components v0.8.1. Let's discuss at the meeting.

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks!

**Comment by fitzthum** [comment]
Ok, KBS issue has been resolved. We don't need to wait for v0.8.1 here.

**Comment by stevenhorsman** [comment]
@fidencio @arronwy or @ChengyuZhu6 - when you get a chance can you review the TDX failure and confirm if this PR is good to merge, or we need to re-run tests as required. Thanks!

**Comment by stevenhorsman** [comment]
There are network issue with TDX, so we'll get them working in the operator which will be easier, so this can merge even with that failure

**Pull request merged**
