### PR TITLE
agent: Use rtnetlink's neighbours API to add neighbors

### PR DESCRIPTION
**Pull request by justxuewei**
Bump rtnetlink version from 0.8.0 to 0.11.0. Use rtnetlinks's API to
add neighbors and fix issues to adapt new verson of rtnetlink.

Fixes: #4607

Signed-off-by: Xuewei Niu <justxuewei@apache.org>

### CODE REVIEW

**Comment by justxuewei** [comment]
@liubin I fixed some issues with unit tests, PTAL and approve running CIs, thanks.

**Review by liubin — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @justxuewei!

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
