### PR TITLE
runtime-rs: Dragonball sandbox - add Vcpu::configure() function for aarch64

### PR DESCRIPTION
**Pull request by xuejun-xj**
This pull request adds Vcpu::configure() function for aarch64.

Fixes: #4445

### CODE REVIEW

**Comment by xuejun-xj** [comment]
Related issue: #4445

**Comment by xuejun-xj** [comment]
> @xuejun-xj - This PR has 14 commits but the only (?) aarch64 changes are to a single file `src/dragonball/src/vcpu/aarch64.rs` I think? Do you need to rebase this? /me is 😕

Thanks, I will fix it.

**Comment by xuejun-xj** [comment]
@jodh-intel Thanks for your recommendations and I have reviewed my commit again. This PR fixes issue #4445 which lacks the configure() function for aarch64 vcpu. At the same time, it is also based on the mainline Part II (#4400 ), so it seems difficult to use a dependent commit. Showing the total commit, we hope to help maintainers to get a complete view of runtime-rs. In the future, after the mainline Part II is merged, we will rebase this PR simultaneously.

**Comment by xuejun-xj** [comment]
> @xuejun-xj - This PR has 14 commits but the only (?) aarch64 changes are to a single file `src/dragonball/src/vcpu/aarch64.rs` I think? Do you need to rebase this? /me is 😕

@jodh-intel Now, I haved rebase it. Thanks!

**Review by jodh-intel — APPROVED** [review]
Thanks @xuejun-xj.

I can't test this and have only done a cursory review, but overall

lgtm

@jongwu - could you tal maybe?

**Comment by bergwolf** [comment]
@xuejun-xj Does it fix `runtime-rs` build/ut on `aarch64`? If so, please add a github action to verify it on `aarch64`. Thanks!

**Review by bergwolf — APPROVED** [review]

**Pull request merged**
