### PR TITLE
build: update golang version to 1.19.2

### PR DESCRIPTION
**Pull request by bergwolf**
So that we get the latest language fixes.

There is little use to maintain compiler backward compatibility. Let's just set the default golang version to the latest 1.19.2.

### CODE REVIEW

**Comment by snir911** [comment]
It seems like some "go get" needs to be removed

**Comment by bergwolf** [comment]
@snir911 I did `git grep "go get"` and none of the results are used for code dependency. Which place are you referring to?

**Comment by snir911** [comment]
saw it here : https://github.com/kata-containers/kata-containers/actions/runs/3325800315/jobs/5498864514

**Comment by bergwolf** [comment]
@snir911 OK, need to fix it in the tests repo side then. Thanks for the pointer!

**Comment by bergwolf** [comment]
Waiting on https://github.com/kata-containers/tests/pull/5224 to be merged first.

**Comment by bergwolf** [comment]
Closing. Patches are carried on in  #5669

**Pull request closed without merging**
