### PR TITLE
version: upgrade qemu version to v5.1.0 for arm64

### PR DESCRIPTION
**Pull request by edmond-hk**
Now, the qemu version used in arm is so old. As some new features have merged
in current qemu, so it's time to upgrade it.

Fixes: #816
Signed-off-by: Edmond AK Dantes <edmond.dantes.ak47@outlook.com>

@jodh-intel  @devimc @jongwu

### CODE REVIEW

**Comment by liubin** [comment]
Travis failed because:

```
ERROR: Required SPDX license header check ('SPDX-License-Identifier: Apache-2.0') failed for the following files:
tools/packaging/obs-packaging/qemu-aarch64/patches/0001-arm-enable-cold-plug-nvdimm-using-DT.patch
```
Do patch files need the license header ? @jodh-intel @bergwolf 

Patchs under `/tools/packaging/kernel/patches/` have not.

**Comment by jodh-intel** [comment]
Hmm. That's odd. I don't think they should need a license header, but I'm wondering why we haven't hit this issue before!

I'd suggest adding `*.patch` to:

- https://github.com/kata-containers/tests/blob/master/.ci/static-checks.sh#L448..L476

**Comment by jodh-intel** [comment]
Related: https://github.com/kata-containers/runtime/pull/2993.

**Comment by bergwolf** [comment]
@edmond-hk Please backport the actual commit instead of the merge commit so that we do not have unnecessary merge node in the git history. And right now it fails on commit message check as well.

**Comment by edmond-hk** [comment]
thanks @bergwolf

**Comment by jongwu** [comment]
@edmond-hk - thanks for your grate job, as you are saving kata on arm.

**Comment by jongwu** [comment]
hello @jodh-intel @devimc @bergwolf , could you please approve this PR?

**Review by bergwolf — APPROVED** [review]

**Comment by jongwu** [comment]
Thanks @bergwolf , happy Mid-autumn Festival and National Day!

**Review by devimc — APPROVED** [review]

**Pull request merged**
