### PR TITLE
Make uevent watching mechanism more flexible

### PR DESCRIPTION
**Pull request by dgibson**
The way we match devices we're waiting for to uevents is currently pretty sloppy and fragile.  See #1484 and #1397.

This is a substantial rework of the uevent matching code to address these problems.

### CODE REVIEW

**Comment by jodh-intel** [comment]
If possible, I'd really like to get https://github.com/kata-containers/kata-containers/pull/1535 landed before this PR since the former is essential for tracing and has been "brewing" for a very long time ;)

**Comment by dgibson** [comment]
> If possible, I'd really like to get #1535 landed before this PR since the former is essential for tracing and has been "brewing" for a very long time ;)

Ok by me.  AFAICT it will mean a moderately painful rebase, but I can manage.  This one has a bit of work still to do before it's ready to go.

**Review by devimc — APPROVED** [review]
thanks @dgibson

**Review by GabyCT — APPROVED** [review]

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
