### PR TITLE
CCv0 | WIP: Update vendor

### PR DESCRIPTION
**Pull request by wllenyj**
For rebase CC/containerd to upstream latest.

See #3642 for details.

@stevenhorsman Can you help me review? Thanks for your previous work.

### CODE REVIEW

**Comment by stevenhorsman** [comment]
I'm just re-running the crio tests that failed, but it looks good. I did a diff between my changes that failed and yours and there were 2 differences. Firstly I tested with a containerd versions `github.com/containerd/containerd v1.6.0-beta.2` and `github.com/containerd/containerd v1.6.0-beta.4` in my 2 PRs, but you used `github.com/containerd/containerd v1.6.0-beta.3` and possibly more importantly, we have a difference in how I attempted to remove the complication problems in `image.go`
```diff
--- a/src/runtime/pkg/containerd-shim-v2/image.go
+++ b/src/runtime/pkg/containerd-shim-v2/image.go
@@ -38,7 +38,7 @@ func initImageService(ic *plugin.InitContext) (interface{}, error) {
        if err != nil {
                return nil, errors.Errorf("get task plugin error. %v", err)
        }
-       task := i.(*shim.TaskService)
+       task := i.(shim.TaskService)
        s := task.TaskService.(*service)
        is := &ImageService{s: s}
        return is, nil
```
My golang is very basic, but I guess my pointer dereference was incorrect?

**Comment by wllenyj** [comment]
@stevenhorsman The old containerd used Pointer.  [code](https://github.com/confidential-containers/containerd/commit/61664f2493c22088e1b8ae80f9a6bbfa58761ebb#diff-23641874d68e8a18ce0b18bb8c0f2d1127427afd6a0522de493e253fe632ce18L274-L280)
``` golang
			Type: plugin.TTRPCPlugin,
			ID:   "task",
			InitFn: func(ic *plugin.InitContext) (interface{}, error) {
				return &taskService{ts}, nil
				return &TaskService{ts}, nil
			},
		})
```
The newer containerd used Struct instead of Pointer. 
``` golang
if manager == nil {                                                
    service, err := initFunc(ctx, id, publisher, sd.Shutdown)      
    if err != nil {                                                
        return err                                                 
    }                                                              
    plugin.Register(&plugin.Registration{                          
        Type: plugin.TTRPCPlugin,                                  
        ID:   "task",                                              
        Requires: []plugin.Type{                                   
            plugin.EventPlugin,                                    
        },                                                         
        InitFn: func(ic *plugin.InitContext) (interface{}, error) {
            return taskService{service}, nil                       
        },                                                         
    })                                                             
    manager = shimToManager{                                       
        shim: service,                                             
        name: name,                                                
    }                                                              
}                                                                  
```

**Comment by wllenyj** [comment]
@stevenhorsman I will close this patch, If this patch is helpful to you, cherry-pick it or just copy it

**Pull request closed without merging**
