### PR TITLE
docs: update general wording for installation documentation

### PR DESCRIPTION
**Pull request by converge**
This change update general wording for the installation documentation.

Remove duplicated information, reduce text separation, rewrite notes to be more clear and concise.

Fixes: #2449

Signed-off-by: Joao Vanzuita <joaovanzuita@me.com>

### CODE REVIEW

**Comment by egernst** [comment]
Changes LGTM. You'll need to update to match commit style guidelines: https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format

**Comment by egernst** [comment]
Kind of "fun" - but one thing you'll need in your commit body is a: "Fixes: #<>", where you'll need to reference a GitHub issue that this PR is addressing.

**Comment by converge** [comment]
> Kind of "fun" - but one thing you'll need in your commit body is a: "Fixes: #<>", where you'll need to reference a GitHub issue that this PR is addressing.

would it be enough?
`git commit --amend -m 'docs: This change update general wording for the installation documentation.' -m 'Remove duplicated information, reduce text separation, rewrite notes to be more clear and concise.' -m 'Fixes: #2449' --signoff`

**Comment by fidencio** [comment]
@converge, your commit message should look like:
```
docs: update general wording for installation documentation 

Remove duplicated information, reduce text separation, and rewrite notes
to be more clear and concise.

Fixes: #2449

Signed-off-by: Joao Vanzuita <joaovanzuita@me.com>
```

**Review by GabyCT — APPROVED** [review]

**Review by egernst — APPROVED** [review]

**Pull request merged**
