### PR TITLE
agent: Use network ID when update routes

### LINKED ISSUE #5207: agent: update_routes failed on none-8-times bits network prefix
Made a update_routes rpc call on agent with the `Route { device: "eth0", source: "", dest: "192.168.157.204/20", gateway: "", scope: 253 }`, and get an error from netlink request `Invalid argument (os error 22)`, while it was added to guest route successfully on go-agent.

### PR DESCRIPTION
**Pull request by Burning1020**
agent: Netgwork ID should be sent to netlink when update routes

According to go-agent code [here](https://github.com/kata-containers/agent/blob/master/network.go#L540), ` netlink.Route.Dst`  is the result of CIDR conversion, then **networkID**(ip address & mask) will be paased through update route request to netlink socket. However, ip address instead of networkID was paased in rust-agent.

Fix #5207

Signed-off-by: Zhang Tianyang <burning9699@gmail.com>

### CODE REVIEW

**Comment by fengwang666** [comment]
@Burning1020 Can you address the github action failures? For example, create a tracking github issue and link it to the PR, make sure the commit message follows the format: https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format

**Comment by Burning1020** [comment]
@fengwang666 Updated. Plz review.

**Comment by Burning1020** [comment]
@fengwang666 What else could I do to help this PR?

**Comment by liubin** [comment]
I think both will get the same result.

From netlink's [example](https://github.com/rust-netlink/rtnetlink/blob/07b478d9ac40943a81cced4e481f4521d4289a86/examples/add_route.rs#L39-L45
):

```rust
    let route = handle.route();
    route
        .add()
        .v4()
        .destination_prefix(dest.ip(), dest.prefix())
        .gateway(gateway.ip())
        .execute()
        .await?;
```

The first parameter should be `.ip()` but not `.network()`, the second parameter `prefix` can ensure it is a valid network address.

From the [Ipv4Network](https://docs.rs/ipnetwork/latest/ipnetwork/struct.Ipv4Network.html#method.network):

```rust
let net: Ipv4Network = "10.1.9.32/16".parse().unwrap();
assert_eq!(net.network(), Ipv4Addr::new(10, 1, 0, 0));
```

Can we just to say `network addr + prefix` == `ip addr + prefix` ?

**Comment by Burning1020** [comment]
@liubin You can look at #5207, I still think that's bug in whatever agent code or rtnetlink's example.

> Can we just to say `network addr + prefix` == `ip addr + prefix` ?

Yes, that's true, however my point is `ip addr` didn't do logical conjunction AND with prefix in the implemention of [`destination_prefix`](https://github.com/rust-netlink/rtnetlink/blob/63f083c0be51414e517cfc2412cc35a4b3dd1d2b/src/route/add.rs#L157), `prefix` was just recorded into the netlink request, diffetent with [go-agent](https://github.com/kata-containers/agent/blob/master/network.go#L540).

**Comment by liubin** [comment]
@Burning1020 


In the `Route` definition, src and dst have [different types](https://github.com/vishvananda/netlink/blob/d3c0a2caa559cabe7fee37662bc5248a88e87ecd/route.go#L52-L58):

```go
type Route struct {
	Dst              *net.IPNet
	Src              net.IP
	Gw               net.IP
```

Golang library [did that in the underground](https://github.com/vishvananda/netlink/blob/d3c0a2caa559cabe7fee37662bc5248a88e87ecd/route_linux.go#L727-L738) by parse IP and mask from `net.IPNet`:

```go
	if route.Dst != nil && route.Dst.IP != nil {
		dstLen, _ := route.Dst.Mask.Size()
		msg.Dst_len = uint8(dstLen)
		dstFamily := nl.GetIPFamily(route.Dst.IP)
		family = dstFamily
		var dstData []byte
		if dstFamily == FAMILY_V4 {
			dstData = route.Dst.IP.To4()
		} else {
			dstData = route.Dst.IP.To16()
		}
		rtAttrs = append(rtAttrs, nl.NewRtAttr(unix.RTA_DST, dstData))
	} else if route.MPLSDst != nil {
```

**Comment by Burning1020** [comment]
@liubin I've tried netlink's [example](https://github.com/rust-netlink/rtnetlink/blob/07b478d9ac40943a81cced4e481f4521d4289a86/examples/add_route.rs#L39-L45):

```
Note that you need to run this program as root. Instead of running cargo as root,
build the example normally:
    cd rtnetlink ; cargo build --example add_route
Then find the binary in the target directory:
    cd ../target/debug/example ; sudo ./add_route <destination>/<prefix_length> <gateway>"
```

run `./add_route 169.254.169.254/32 192.168.11.1` got right
run `./add_route 169.254.169.254/20 192.168.11.1` got `Received a netlink error message Invalid argument (os error 22)
`

**Comment by liubin** [comment]
@Burning1020 

`169.254.169.254/20` is a not well formatted network, you can try `169.254.160.0/20`.

```
Address:   169.254.169.254       10101001.11111110.1010 1001.11111110
Netmask:   255.255.240.0 = 20    11111111.11111111.1111 0000.00000000
Wildcard:  0.0.15.255            00000000.00000000.0000 1111.11111111
=>
Network:   169.254.160.0/20      10101001.11111110.1010 0000.00000000 (Class B)
Broadcast: 169.254.175.255       10101001.11111110.1010 1111.11111111
HostMin:   169.254.160.1         10101001.11111110.1010 0000.00000001
HostMax:   169.254.175.254       10101001.11111110.1010 1111.11111110
Hosts/Net: 4094                  
```

refer to https://jodies.de/ipcalc?host=169.254.169.254&mask1=20&mask2=

**Comment by Burning1020** [comment]
We can tolerance the not-well formatted network in Golang agent, so I think we could do the adapting work in Rust agent.
Now we can disscuss its necessarity and find out whether it should be fixed.

**Pull request closed without merging**
