### PR TITLE
ci: add golang 1.16 to the CI

### PR DESCRIPTION
**Pull request by devimc**

### CODE REVIEW

**Comment by devimc** [comment]
@c3d 

> @devimc Any idea why kata-containers/tests#3645 does not refer to this PR?

maybe because this is a different repository ... ?

**Review by fidencio — APPROVED** [review]
lgtm, thanks @devimc!

**Comment by fidencio** [comment]
@devimc, may I bother you to rebase this one atop of current main?

**Review by jodh-intel — APPROVED** [review]
Thanks @devimc.

lgtm

**Comment by fidencio** [comment]
Howdy!

I'd like to ask you to rebase your PR atop of current `main`, as https://github.com/kata-containers/kata-containers/pull/2197 has been merged and it has a fix that unblocks the CI.

Please, do the rebase and feel free `@fidencio` in case you do not have the powers to run `/test`.

Sorry for the inconvenience and happy hacking!

**Comment by fidencio** [comment]
Hey, we've had yet another breakage in our CI and now it's fixed as part of https://github.com/kata-containers/kata-containers/pull/2203 ... it means that you'll need to rebase your PR atop of current main.

Sorry for the inconvenience.

**Comment by fidencio** [comment]
@devimc, Julio, can we have this one rebased? I really would like to have it merged.

**Comment by fidencio** [comment]
So, some of the metrics really need some love as their results are not reliable right now.

For instance, we had to bring the midval number down because of this PR, and we did as part of https://github.com/kata-containers/tests/pull/3718, which was depending on this PR, which was using this PR as part of the tests in the `tests` repo.

However, the metrics CI is failing because the results here are now too high. :-/.

What's the usual way to deal with this and what can we do to try to ensure the numbers are, somehow, more stable?

**Pull request merged**
