### PR TITLE
runtime: run prestart hooks before starting VM for FC

### PR DESCRIPTION
**Pull request by bergwolf**
Add a new hypervisor capability to tell if it supports device hotplug. If not, we should run prestart hooks before starting new VMs as nerdctl is using the prestart hooks to set up netns. To make nerdctl + FC to work, we need to run the prestart hooks before starting new VMs.

Fixes: #6384

### CODE REVIEW

**Comment by bergwolf** [comment]
@ananos Would you like to take a look?

**Review by ananos — APPROVED** [review]
LGTM! thanks Tao!

**Review by teawater — APPROVED** [review]
LGTM

**Comment by zvonkok** [comment]
@bergwolf Haven't digged through the code, just for completeness, we're not changing the current behaviour? 
One thing that is still outstanding is how do we know which runtime is going to execute the hook? The inner runtime (kata-agent) or the outer runtime (shim)?

**Comment by bergwolf** [comment]
@zvonkok No, the PR does not change the behavior w.r.t. which runtime is executing the hooks. As for your question, we are currently implementing the table outlined here https://github.com/kata-containers/kata-containers/issues/5787#issuecomment-1331748449

**Pull request merged**
