### PR TITLE
kata-sys-util: upgrade nix version

### PR DESCRIPTION
**Pull request by liubin**
New nix is supporting UMOUNT_NOFOLLOW, upgrade nix
version to use this flag instead of the self-defined flag.

Fixes: #4670

Signed-off-by: liubin <liubin0329@gmail.com>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @liubin.

lgtm

**Review by fidencio — APPROVED** [review]
lgtm, thanks @liubin!

**Comment by jodh-intel** [comment]
@liubin - all green apart from the Alibaba CentOS CI, which is failing with a strange error:

```
+ local 'packages_regex=^(kata|qemu-lite)-'
+ local packages
+ info 'removing packages'
+ '[' no '!=' yes ']'
+ return
+ case "$distro" in
++ rpm -qa
++ egrep '^(kata|qemu-lite)-'
++ true
+ packages=
+ '[' -z '' ']'
+ die 'packages not installed'
+ local 'msg=packages not installed'
+ echo 'ERROR: packages not installed'
ERROR: packages not installed
```

**Pull request merged**
