### PR TITLE
osbuilder: Remove fedora rootfs-builder

### PR DESCRIPTION
**Pull request by fidencio**
As the fedora rootfs is not tested in our CI, we can't guarantee it
actually works as expected.

Whenever we have someone willing to maintain the rootfs we can have it
added back, and also add a CI job to test it altogether, avoiding then
any possible regression.

Fixes: #2143

Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

### CODE REVIEW

**Comment by Jakob-Naucke** [comment]
As alluded to in #3328, I'd prefer CentOS Stream over Fedora as a Red Hat (adjacent) distro due to release cadence, so I wouldn't have any objections here.

**Comment by wainersm** [comment]
@fidencio in case this PR gets acked by the impacted users (if any), then you will need to remove this line too: https://github.com/kata-containers/tests/blob/main/Vagrantfile#L117

**Review by GabyCT — APPROVED** [review]

**Comment by amshinde** [comment]
@fidencio Would like to first check with Redhat folks if anyone is willing to maintain this from their side. Would be useful to run this by the Kata AC meeting or atleast send out a mail on the kata mailing list. 
While this does cleanup things, I also do feel that having this here would serve somewhat as a blueprint for someone planning to use fedora as their rootfs in the future.

**Review by jodh-intel — APPROVED** [review]
Thanks @fidencio.

lgtm

**Comment by jodh-intel** [comment]
Ah - as @Jakob-Naucke says on #3326, this does need a doc update so let's keep the dnm for now.

**Comment by wainersm** [comment]
> @fidencio Would like to first check with Redhat folks if anyone is willing to maintain this from their side. Would be useful to run this by the Kata AC meeting or atleast send out a mail on the kata mailing list. While this does cleanup things, I also do feel that having this here would serve somewhat as a blueprint for someone planning to use fedora as their rootfs in the future.

@fidencio @amshinde I brought that to the attention of Red Hat, we are already discussing and soon I will post a official position here.

Regardless, IMHO we should have documented policies for the introduction and support of distros via osbuilder. Just like the CI jobs, I believe we should adopt a maintainers model for osbuilder distros and every entry must be tested on CI.

**Comment by wainersm** [comment]
@fidencio I got the Ack from @kata-containers/redhat  to remove the fedora rootfs-builder.

Could you please address my https://github.com/kata-containers/kata-containers/pull/3327#issuecomment-998978190 ?

**Comment by jodh-intel** [comment]
@fidencio - Could you rebase as this branch is now conflicted?

**Comment by jodh-intel** [comment]
@fidencio - could you rebase to resolve the conflict?

**Comment by fidencio** [comment]
This got superseded by https://github.com/kata-containers/kata-containers/pull/3420

**Pull request closed without merging**
