### PR TITLE
makefile: Fix error exit status code

### LINKED ISSUE #2479: runtime: command "make test" and "make coverage" can excute, but exit with non-zero status code
# Description of problem

excute `make test` and `make coverage` under the project dir "src/runtime"

# Expected result

command exit with zero status code

# Actual result

command exit with non-zero status code, like 
```sh
$ make test
# github.com/kata-containers/kata-containers/src/runtime/cli/containerd-shim-kata-v2
cli/containerd-shim-kata-v2/main.go:25:71: undefined: project
cli/containerd-shim-kata-v2/main.go:25:110: undefined: version
cli/containerd-shim-kata-v2/main.go:25:119: undefined: commit
...
make: *** [Makefile:614: go-test] Error 2
```

### PR DESCRIPTION
**Pull request by Bevisy**
Generate `config-generated.go` file under src/runtime/cli/containerd-shim-kata-v2 before excuting test or coverage.

Fixes #2479

Signed-off-by: Binbin Zhang <binbin36520@gmail.com>

### CODE REVIEW

**Review by bergwolf — APPROVED** [review]

**Comment by Bevisy** [comment]
Hi, all, we need to run jenkins ci here. Can anyone leave  comment "/test" to activate jenkins ci. :smiley:

**Review by devimc — APPROVED** [review]

**Pull request merged**
