### PR TITLE
main | kata-deploy: Fix kata deploy arm64 image build error

### PR DESCRIPTION
**Pull request by singhwang**
kata-deploy: Fix kata deploy image build error

When building the kata deploy arm64 image, using default base image report errors.

Fixes: #6358

Signed-off-by: Singh Wang <wangxin_0611@126.com>

### CODE REVIEW

**Comment by singhwang** [comment]
I have tested this image called centos:7, whether it is in the amd64 environment or in the arm64 environment, it supports.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @singhwang!

**Comment by jongwu** [comment]
Hi @singhwang -, how to reproduce the error? I run "make rootfs-image-tarball" on arm64 server and it works.

**Comment by singhwang** [comment]
> how to reproduce the error? I run "make rootfs-image-tarball" on arm64 server and it works.

@jongwu This is an error in building the kata deploy container image on the arm64 environment, not an error in building rootfs. You can check the issue corresponding to this pr, which mentions how to reproduce the error.

**Comment by jongwu** [comment]
@singhwang -, yes, registry.centos.org/centos is not a muti-arch image that doesn't support arm64.  Thanks!

**Review by jongwu — APPROVED** [review]

**Comment by fidencio** [comment]
I've closed and re-open the PR just to retrigger the GitHub actions.

**Comment by fidencio** [comment]
```
INFO: Installing hadolint 2.7.0 at /home/runner/work/kata-containers/kata-containers/bin/hadolint
INFO: Checking Dockerfile 'tools/packaging/kata-deploy/Dockerfile'
tools/packaging/kata-deploy/Dockerfile:7:22 unexpected ':' expecting '@', '\', a new line followed by the next instruction, or the image tag 
ERROR: failed to check Dockerfile 'tools/packaging/kata-deploy/Dockerfile'
```

**Comment by fidencio** [comment]
I just noticed that the CentOS dockerhub's been deprecated in favour of what we're currently using, and this is bad,

I'd suggesting switching to dockerhub only on ARM for now, and later on we can find a better image to use as base
/cc @zvonkok

**Comment by singhwang** [comment]
@fidencio Can this Dockerfile be considered to use the base image of other distributions, such as ubuntu:20.04, which you use the most, I have actually rewritten this Dockerfile with several base images, but you consider the community to use centos :7, multi-architecture support is also required, so I chose to use centos:7 on the hub as the base image.I can contribute.

**Comment by fidencio** [comment]
> @fidencio Can this Dockerfile be considered to use the base image of other distributions, such as ubuntu:20.04, which you use the most.I can contribute. I have actually rewritten this Dockerfile with several base images, but I consider the community to use centos:7, multi-architecture support is also required, so I chose to use centos:7 on the hub as the base image.

I am going back and forth on how to get this solved, please, just give me some time and we'll get there.

I also would like to get away from the old and not multi-arch friendly CentOS 7 containers, but we need to get a way to properly restart a systemd service from inside the daemon-set, and that proved to not be trivial to do  with newer images.

Please, keep this one opened and let me think a little bit about a possible short term solution for this.

**Comment by singhwang** [comment]
> I am going back and forth on how to get this solved, please, just give me some time and we'll get there.
> 
> I also would like to get away from the old and not multi-arch friendly CentOS 7 containers, but we need to get a way to properly restart a systemd service from inside the daemon-set, and that proved to not be trivial to do with newer images.
> 
> Please, keep this one opened and let me think a little bit about a possible short term solution for this.

Is the problem you encounter is that after replacing other images, the container started in the form of daemonset cannot operate the systemd service on the host?

**Comment by fidencio** [comment]
> @fidencio Is the problem you encounter is that after replacing other images, the container started in the form of daemonset cannot operate the systemd service on the host?

Exactly!

**Comment by singhwang** [comment]
> > @fidencio Is the problem you encounter is that after replacing other images, the container started in the form of daemonset cannot operate the systemd service on the host?
> 
> Exactly!

@fidencio I have solved this problem by using ubuntu 20.04 to build the kata-deploy image, and spent a lot of time solving various problems encountered. I would like to make a contribution to this issue through this pr. Would you like to take a look at my changes?

**Comment by fidencio** [comment]
> Would you like to take a look at my changes?

Yes, please! :-)

**Comment by singhwang** [comment]
@fidencio I have covered the previous submission. The current changes are the modifications I made. It is mainly used to solve the container started in the form of daemonset cannot operate the systemd service on the host.

**Comment by fidencio** [comment]
This is very good and it does pass our CI: https://github.com/kata-containers/kata-containers/actions/runs/4341672655/jobs/7582034479

Do you mind if I force-push to your branch as some changes that will conflict with yours were just merged?

**Comment by fidencio** [comment]
@singhwang, I've forced pushed to your branch in order to solve the conflict and adding a few pieces needed.

**Review by stevenhorsman — APPROVED** [review]
LGTM and it's great to see the switch from a end of the road base image to a proper multi-arch one! Thanks @singhwang and @fidencio!

**Comment by singhwang** [comment]
> @singhwang, I've forced pushed to your branch in order to solve the conflict and adding a few pieces needed.

@fidencio ok! I understand your idea by looking at the effect of merging our codes together. The effect is very good, and this is also the ideal effect in my mind. I believe that when it is released later, I can not only see the amd64 version of the kata-static package, but also its arm64 version.

In addition, I have another suggestion, whether the kata-deploy container image can be made into a multi-architecture, that is, the kata-deploy container image on quay.io supports both amd64 and arm64, and uses the same repository and the same tag. In this way, from the user's point of view, the yaml manifests of kata-deploy and kata-clean do not need to be modified. It is the same whether you use the amd64 environment or the arm64 environment.

**Comment by fidencio** [comment]
@singhwang, that's correct.  Here's a payload generated this morning from the latest pushed commit (which was still using the CentOS image): https://quay.io/repository/kata-containers/kata-deploy-ci/manifest/sha256:a1a9dfdcd2fcb69b60cbc9a355d3cedb4ad244e14665d3ea28585016af206777

There you can see that the kata-containers-latest image is a multi-arch one. :-)

Now, the next steps I'd like to see contributions on are:
* Adapting the workflows for the release
  * Thus multi-arch kata-deploy images can be generated
  * Thus multi-arch binaries can be tagged as part of the release

Would you be willing to work on those two pieces?

**Comment by singhwang** [comment]
> Now, the next steps I'd like to see contributions on are:

Yes I do. I'd love to try it out, but I still need to familiarize myself with this part of the code first. After that, I'll start making these two parts of the contribution.

**Comment by singhwang** [comment]
> @singhwang, that's correct. Here's a payload generated this morning from the latest pushed commit (which was still using the CentOS image): https://quay.io/repository/kata-containers/kata-deploy-ci/manifest/sha256:a1a9dfdcd2fcb69b60cbc9a355d3cedb4ad244e14665d3ea28585016af206777
> 
> There you can see that the kata-containers-latest image is a multi-arch one. :-)
> 
> Now, the next steps I'd like to see contributions on are:
> 
> * Adapting the workflows for the release
>   
>   * Thus multi-arch kata-deploy images can be generated
>   * Thus multi-arch binaries can be tagged as part of the release
> 
> Would you be willing to work on those two pieces?

Yes, I do. I'd love to try it out, but I still need to familiarize myself with this part of the code first. Then, I will start trying to make these two parts of the contribution.

**Pull request merged**
