### PR TITLE
Kata ctl drop privs

### PR DESCRIPTION
**Pull request by amshinde**
Add utility function to drop privileges. Add cargo.lock to version control.

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Nice! Thanks @amshinde.

lgtm

**Comment by jodh-intel** [comment]
Related: #5440.

**Comment by fidencio** [comment]
```
cargo fmt -- --check
Diff in /home/runner/work/kata-containers/kata-containers/src/github.com/kata-containers/kata-containers/src/tools/kata-ctl/src/utils.rs at line 5:
 
 #![allow(dead_code)]
 
-use privdrop;
 use anyhow::{anyhow, Result};
+use privdrop;
 
 const NON_PRIV_USER: &str = "nobody";
 
Diff in /home/runner/work/kata-containers/kata-containers/src/github.com/kata-containers/kata-containers/src/tools/kata-ctl/src/utils.rs at line 13:
-pub fn drop_privs()->Result<()> {
+pub fn drop_privs() -> Result<()> {
     if nix::unistd::Uid::effective().is_root() {
         privdrop::PrivDrop::default()
             .chroot("/")
make[1]: *** [../../../utils.mk:177: standard_rust_check] Error 1
make: *** [Makefile:32: check-kata-ctl] Error 2
make[1]: Leaving directory '/home/runner/work/kata-containers/kata-containers/src/github.com/kata-containers/kata-containers/src/tools/kata-ctl'
Error: Process completed with exit code 2.
```

**Review by dborquez — CHANGES_REQUESTED** [review]
LGTM, except that you need to remove src/tools/kata-ctl/Cargo.lock from the PR. Thank you @amshinde

**Comment by amshinde** [comment]
@dborquez We need to add Cargo.lock to version control. Please take a look at :
https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html
```
If you’re building a non-end product, such as a rust library that other rust [packages](https://doc.rust-lang.org/cargo/appendix/glossary.html#package) will depend on, put Cargo.lock in your .gitignore. If you’re building an end product, which are executable like command-line tool or an application, or a system library with crate-type of staticlib or cdylib, check Cargo.lock into git. If you're curious about why that is, see ["Why do binaries have Cargo.lock in version control, but not libraries?" in the FAQ](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries).
```

**Comment by snir911** [comment]
we missed have the lock file by mistake earlier? is it needed also for tools?

**Comment by dborquez** [comment]
@amshinde sorry ! you are right!

**Review by dborquez — APPROVED** [review]

**Review by cmaf — APPROVED** [review]

**Pull request merged**
