### PR TITLE
[backport] Fix Snap CI

### PR DESCRIPTION
**Pull request by devimc**

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Review by cmaf — APPROVED** [review]

**Comment by likebreath** [comment]
The CLH CI failure is caused is a known issue, and should be able to be resolved by upgrading to CLH v0.12.0. The backporting PR is here: https://github.com/kata-containers/kata-containers/pull/1409.

**Review by likebreath — APPROVED** [review]

**Comment by GabyCT** [comment]
@chavafg I think that we can merge this PR as other backports PRs are being blocked by this fix. This is only modifying the snap CI which is independent of the rest of the CI and merging this will unblock the other backports, wdyt?

**Review by chavafg — APPROVED** [review]

**Comment by chavafg** [comment]
+1 for merging this. I see snap CI is passing.

**Pull request merged**
