### PR TITLE
kata-deploy / kata-cleanup / ci: Fixes and improvements to kata-deploy / kata-cleanup and its usage in the CI

### PR DESCRIPTION
**Pull request by fidencio**
Please, see each commit for more details.

### CODE REVIEW

**Comment by fidencio** [comment]
https://github.com/fidencio/kata-containers/actions/runs/9245395710/job/25432061466?pr=24 shows k0s fully working with these patches.

**Review by zvonkok — APPROVED** [review]
LGTM, let get the CI rolling

**Pull request merged**
