### PR TITLE
Fixes for make generate-protocols

### PR DESCRIPTION
**Pull request by dgibson**
This fixes issue #1198 and makes some other cleanups to this code along the way.

### CODE REVIEW

**Review by Tim-Zhang — APPROVED** [review]
Thanks @dgibson

**Review by lifupan — APPROVED** [review]

**Comment by dgibson** [comment]
Hrm.  Many CI failures, which I don't *think* are due to my changes.

**Review by c3d — APPROVED** [review]
lgtm

**Comment by dgibson** [comment]
Ah.  Looks like at least one of the CI failures is due to my changes, in conjunction with https://github.com/kata-containers/tests/issues/3124

**Comment by dgibson** [comment]
Fix for kata-containers/tests#3124 is merged now, so:
/retest

**Pull request merged**
