### PR TITLE
agent: Cleanup config

### PR DESCRIPTION
**Pull request by mxpv**
This commit cleans up config parsing and testing code to make it a bit more easy to maintain.
- Adds `with_context` from `anyhow` to include the underlying error. This helps to understand what exactly went wrong.
- Uses `ensure!` and `bail!` as a shorter alternative for `if` checks.
- `TestData` in `test_parse_cmdline` is now implements `Default` trait to reduce boilerplate code.
- Remove `make_err` as it doesn’t make any sense.

Fixes: #2177

Signed-off-by: Maksym Pavlenko <pavlenko.maksym@gmail.com>

### CODE REVIEW

**Review by egernst — APPROVED** [review]
Net -364 lines of code without making it any less readable. I like it!

LGTM

**Review by fidencio — APPROVED** [review]
lgtm, thanks @mxpv!

**Pull request merged**
