### PR TITLE
deps: Resolve dependabot bumps of containerd, crossbeam-utils, regex

### PR DESCRIPTION
**Pull request by snir911**
https://github.com/kata-containers/kata-containers/pull/4401
https://github.com/kata-containers/kata-containers/pull/4402
https://github.com/kata-containers/kata-containers/pull/4403
https://github.com/kata-containers/kata-containers/pull/4404
https://github.com/kata-containers/kata-containers/pull/4405
https://github.com/kata-containers/kata-containers/pull/4406
https://github.com/kata-containers/kata-containers/pull/4408

Fixes: #4421

### CODE REVIEW

**Comment by snir911** [comment]
Let's see how tests goes:
/test

**Review by amshinde — APPROVED** [review]

**Comment by snir911** [comment]
cc @jodh-intel it contains bumps in agent-ctl

**Review by jodh-intel — APPROVED** [review]
Thanks @snir911.

lgtm

**Pull request merged**
