### PR TITLE
CI: Make docker version stick to v20.10 in ubuntu:20.04 for s390x|ppc64le

### PR DESCRIPTION
**Pull request by BbolroC**
This is to make a docker version to v20.10 in docker upstream image ubuntu:20.04 for s390x|ppc64le.

Fixes: #6211

Signed-off-by: Hyounggyu Choi <Hyounggyu.Choi@ibm.com>

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
This looks fine to me at the moment as the only package dropped as a result of this is `docker-buildx-plugin`, which we obviously aren't using on s390x as it isn't available!

**Review by gkurz — APPROVED** [review]
LGTM. Thanks @BbolroC !

**Comment by Amulyam24** [comment]
> It seems `ppc64le` is also affected. @Amulyam24 is it okay to include `ppc64le` in the conditional like below?
> 
> > if uname -m | grep -Eq 's390x|ppc64le'; then export VERSION="v20.10"; fi && \

Absolutely, Thanks @BbolroC !

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
