### PR TITLE
test: enable running tests under root user

### PR DESCRIPTION
**Pull request by liubin**
Add tests that run under root user to test special cases.

Fixes: #2446

Signed-off-by: bin <bin@hyper.sh>

### CODE REVIEW

**Comment by liubin** [comment]
Hi, @egernst @mxpv can you help to review the modification of `src/agent/src/watcher.rs`, there is a strange behavior between my local PC and in GitHub Actions when run by the root user.

https://github.com/kata-containers/kata-containers/blob/103fdd3f6cc001d19737a6b34a60a4134037c1b5/src/agent/src/watcher.rs#L610-L629

This test case worked in my local and failed at line 628 in GitHub Actions.

But after reading the source, I think this should not work in my local, the file length check should be after updating the file list.

**Review by bergwolf — APPROVED** [review]
Great!

**Review by Tim-Zhang — APPROVED** [review]
LGTM, Thanks @liubin

**Pull request merged**
