### PR TITLE
Bump containerd to 1.6.1

### PR DESCRIPTION
**Pull request by fidencio**
Let's bump containerd to 1.6.1 as part of our vendored code.

Fixes: #3820

### CODE REVIEW

**Comment by liubin** [comment]
@fidencio The errors show that CNI issues, I don't remember nydus has set CNI configs?

So it may be a containerd issue, can you manually run some pods using crictl? 

And we are using an old CNI:

```
  cni-plugins:
    description: "CNI network plugins"
    url: "https://github.com/containernetworking/plugins"
    commit: "485be65581341430f9106a194a98f0f2412245fb"
```

Updating CNI may fix this issue.

**Review by devimc — APPROVED** [review]

**Review by stevenhorsman — APPROVED** [review]
LGTM - and I'm relieved to see that your `grpc.WithInsecure()` changes matched what I did in `CCv0`!

**Pull request merged**
