### PR TITLE
runtime: Format golang proto code

### PR DESCRIPTION
**Pull request by ManaSugi**
When golang proto files such as `agent.pb.go` are generated using `protoc-gen-gogo`, the code is formated by default.
Therefore, it is better to adopt the generated code by default.

Fixes: #2064

Signed-off-by: Manabu Sugimoto <Manabu.Sugimoto@sony.com>

### CODE REVIEW

**Comment by ManaSugi** [comment]
BTW, the code generated by `protoc-gen-gogo` is little different from existing code.

e.g. agent.pb.go

``` golang
-       for k := range this.HugetlbStats {
+       for k, _ := range this.HugetlbStats {
                keysForHugetlbStats = append(keysForHugetlbStats, k)
        }
```

The above code was formatted by the [commit](https://github.com/kata-containers/kata-containers/commit/0153f76b07f9e94df2491d611191c179b40d7152#diff-9d4fdd07e7b74e242cb5283603be659fae1bbc559d631a9d8e15873663da05d5).
Therefore, when I run `update-generated-proto.sh`,  I have to revert the above code manually because the code is not fixed by `gofmt`. Which code should we adopt, generated code automatically or the formatted code?

**Comment by liubin** [comment]
Hi, @ManaSugi what commands are you used for generating these go files from `.proto` files?

I tried:

```bash
$ cd src/agent
$ make PROTO_FILE=all generate-protocols
```

And it is true that newly generated files are different from the current code, but also different from your new code some bit.

And there is another proto file under `src/runtime/protocols/cache/` folder, and managed by `src/runtime/hack/update-generated-runtime-proto.sh`, this file may be updated also.

**Comment by ManaSugi** [comment]
Thank you for your comment.
I ran the same command as you.
```
$ cd src/agent
$ make PROTO_FILE=all generate-protocols
$ protoc --version
libprotoc 3.6.1
```
However, I did not add the like following changes to this commit as I mentioned above because the following changes was updated 
on purpose by the [commit](https://github.com/kata-containers/kata-containers/commit/0153f76b07f9e94df2491d611191c179b40d7152#diff-9d4fdd07e7b74e242cb5283603be659fae1bbc559d631a9d8e15873663da05d5).

<details><summary>changes </summary><div>

agent.pb.go
``` 
--- a/src/runtime/virtcontainers/pkg/agent/protocols/grpc/agent.pb.go       
+++ b/src/runtime/virtcontainers/pkg/agent/protocols/grpc/agent.pb.go       
@@ -7009,7 +7009,7 @@ func (this *MemoryStats) String() string {            
                return "nil"                                                
        }                                                                   
        keysForStats := make([]string, 0, len(this.Stats))                  
-       for k := range this.Stats {                                         
+       for k, _ := range this.Stats {                                      
                keysForStats = append(keysForStats, k)                      
        }                                                                   
        github_com_gogo_protobuf_sortkeys.Strings(keysForStats)             
@@ -7120,7 +7120,7 @@ func (this *CgroupStats) String() string {            
                return "nil"                                                
        }                                                                   
        keysForHugetlbStats := make([]string, 0, len(this.HugetlbStats))    
-       for k := range this.HugetlbStats {                                  
+       for k, _ := range this.HugetlbStats {                               
                keysForHugetlbStats = append(keysForHugetlbStats, k)        
        }                                                                   
        github_com_gogo_protobuf_sortkeys.Strings(keysForHugetlbStats)      
```
oci.pb.go
```
--- a/src/runtime/virtcontainers/pkg/agent/protocols/grpc/oci.pb.go     
+++ b/src/runtime/virtcontainers/pkg/agent/protocols/grpc/oci.pb.go     
@@ -6797,7 +6797,7 @@ func (this *Spec) String() string {               
        }                                                               
        repeatedStringForMounts += "}"                                  
        keysForAnnotations := make([]string, 0, len(this.Annotations))  
-       for k := range this.Annotations {                               
+       for k, _ := range this.Annotations {                            
                keysForAnnotations = append(keysForAnnotations, k)      
        }                                                               
        github_com_gogo_protobuf_sortkeys.Strings(keysForAnnotations)   
@@ -6996,7 +6996,7 @@ func (this *Linux) String() string {              
        }                                                               
        repeatedStringForDevices += "}"                                 
        keysForSysctl := make([]string, 0, len(this.Sysctl))            
-       for k := range this.Sysctl {                                    
+       for k, _ := range this.Sysctl {                                 
                keysForSysctl = append(keysForSysctl, k)                
        }                                                               
```
</div></details>

But, I'd like to update the above changes by this commit for maintainability if possible.
So, I added the changes to this commit.
In addition, I updated proto file under `src/runtime/protocols/cache/` folder using `src/runtime/hack/update-generated-runtime-proto.sh`.
Thank you.

**Comment by liubin** [comment]
@ManaSugi I think we should not modify the generated code manually, so all changes by the protocol compiler should be included in this PR.
PTAL @bergwolf

**Comment by ManaSugi** [comment]
@liubin Thank you for your comment.
Yes, I do not include any manual changes in this PR, so all this code is generated by the protocol compiler.

**Review by liubin — APPROVED** [review]

**Review by egernst — APPROVED** [review]

**Pull request merged**
