### PR TITLE
3.2 backport bunch

### PR DESCRIPTION
**Pull request by gkurz**
This backports the following PRs for the upcoming 3.2.0 release, according to the `needs-backport` label :

- #7703
- #7716
- #7718
- #7768 (except 3818bf3311a5d70704a3773941536f9a59a3a0e4 already backported)
- #7854
- #7865
- #7953
- #7985
- #7992
- #8036
- #8201
- #8197
- #8188
- #8179
- #8206
- #8213 
- #8149
- #8241
- #8243
- #8260

And also in order to fix CI :
- #7581

### CODE REVIEW

**Comment by gkurz** [comment]
Putting this PR on hold on @fidencio's request :
```
We may need to backport a whole lot more because of the tests
I appreciate the help, I sincerely do, but let's finish the CCv0 work
before we start this, otherwise my head will get confused really
really fast.
```

**Review by fidencio — APPROVED** [review]
lgtm, thanks @gkurz!

**Review by littlejawa — APPROVED** [review]
lgtm
Thanks!

**Pull request merged**
