### PR TITLE
doc: Improve kata-deploy README.md by changing sh blocks to bash blocks

### PR DESCRIPTION
**Pull request by dborquez**
The idea is to pass this README file to kata-doc-to-script.sh script and
then execute the result.

Added comments with a file name on top of each YAML snippet.
This helps in assigning a file name when we cat the YAML to a file.

Fixes: #3943

Signed-off-by: David Esparza <david.esparza.borquez@intel.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @dborquez!

**Review by jodh-intel — APPROVED** [review]
Thanks @dborquez.

lgtm

**Comment by jodh-intel** [comment]
@dborquez - all green, so can we remove the dnm label?

**Comment by dborquez** [comment]
> @dborquez - all green, so can we remove the dnm label?

@jodh-intel thanks, Just need to fix the doc to solve a couple of issues on the CI script.

**Comment by dborquez** [comment]
> lgtm, thanks @dborquez!
> @dborquez - all green, so can we remove the dnm label?

**Pull request merged**
