### PR TITLE
gha: ensure that the self hosted runner is in desired state before running the workflow 

### PR DESCRIPTION
**Pull request by Amulyam24**
This PR adds a step to ensure that containerd is up and running before building the payload image on Power.

Fixes: #9262

### CODE REVIEW

**Comment by Amulyam24** [comment]
> Do we also need this step in https://github.com/kata-containers/kata-containers/blob/main/.github/workflows/release-ppc64le.yaml ?

Hi @stevenhorsman, added the step wherever necessary. PTAL!

**Comment by BbolroC** [comment]
Hi, I think it would be wonderful to make the commit message more concrete (what kind of things should be proceeded in order to reach a desired state) so that maintainers for a self-hosted runner could have a look when they are stuck in a similar situation. 😉

**Comment by Amulyam24** [comment]
> Hi, I think it would be wonderful to make the commit message more concrete (what kind of things should be proceeded in order to reach a desired state) so that maintainers for a self-hosted runner could have a look when they are stuck in a similar situation. 😉

Hi @BbolroC , addressed it, PTAL.

**Review by BbolroC — APPROVED** [review]
LGTM, thanks @Amulyam24 !

**Pull request merged**
