### PR TITLE
virtcontainers: tests: Ensure Linux specific tests are just run on Linux

### PR DESCRIPTION
**Pull request by dcantah**
Fixes: #5993

Several tests utilize linux'isms like Mounts, bindmounts, vsock etc.

Let's ensure that these are still tested on Linux, but that we also skip these tests when on other operating systems (Darwin). This commit mainly just moves tests; there shouldn't be any functional test changes. I've left the copyright headers as is due to this, as it's just moving work with very minimal new introduced. While the tests still won't be runnable on Darwin/other hosts yet, this is a necessary step forward.

### CODE REVIEW

**Comment by egernst** [comment]
Oh, fun. You've inherited this lint error:

```
Error: kata_agent_linux_test.go:10:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
[284](https://github.com/kata-containers/kata-containers/actions/runs/3853563128/jobs/6570391200#step:10:285)
	"io/ioutil"
[285](https://github.com/kata-containers/kata-containers/actions/runs/3853563128/jobs/6570391200#step:10:286)
```

**Comment by dcantah** [comment]
@egernst Should be fixed. Seems this was fixed upstream since your change

**Comment by egernst** [comment]
(restarted jenkins-ci-fedora-35-x86_64-crio_k8s_minimal)

**Review by egernst — APPROVED** [review]

**Review by mxpv — APPROVED** [review]
LGTM

**Review by liubin — APPROVED** [review]

**Pull request merged**
