### PR TITLE
stable-2.1 | Get sandbox metrics cli

### PR DESCRIPTION
**Pull request by fidencio**
Backport of #1816

### CODE REVIEW

**Review by snir911 — APPROVED** [review]

**Review by liubin — APPROVED** [review]

**Comment by fidencio** [comment]
@GabyCT, is **jenkins-ci-ubuntu-20-04** ready or can we consider it not required for stable-2.1 branch?

**Comment by GabyCT** [comment]
@fidencio the ci for ubuntu 20.04 should be ready as far as I know

**Comment by GabyCT** [comment]
@fidencio for the errors that I see is that maybe a backport is missing?
```
[init] Using Kubernetes version: v1.21.0
[preflight] Running pre-flight checks
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR CRI]: container runtime is not running: output: time="2021-05-12T11:20:42Z" level=fatal msg="getting status of runtime failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
Failed at 112: sudo -E kubeadm init --config "${kubeadm_config_file}"
Failed at 78: ./init.sh
```

**Comment by GabyCT** [comment]
I see that for stable-2.0 ubuntu 20.04 is working fine as you can see http://jenkins.katacontainers.io/view/Kata%202.0/job/kata-containers-2.0-tests-ubuntu20.04-PR/25/....so it seems something is missing in stable-2.1

**Comment by fidencio** [comment]
```
+ bin/ctr
+ bin/containerd
# github.com/containerd/containerd/vendor/github.com/containerd/btrfs
vendor/github.com/containerd/btrfs/btrfs.go:38:10: fatal error: btrfs/ioctl.h: No such file or directory
   38 | #include <btrfs/ioctl.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:183: bin/containerd] Error 2
make[1]: Leaving directory '/tmp/cri-install-containerd.Cs0R/src/github.com/containerd/containerd'
make: *** [Makefile:132: _output/cri-containerd-f864905c.linux-amd64.tar.gz] Error 2
Failed at 48: make release
Failed at 53: ( cd "${GOPATH}/src/${cri_repository}" >> /dev/null; git fetch; git checkout "${cri_containerd_version}"; make release; local commit; commit=$(git rev-parse --short HEAD); tarball_name="cri-containerd-${commit}.${CONTAINERD_OS}-${CONTAIENRD_ARCH}.tar.gz"; sudo tar -xvf "./_output/${tarball_name}" -C / )
```

**Comment by fidencio** [comment]
@GabyCT, please, take a look at: https://github.com/kata-containers/tests/pull/3521

**Comment by GabyCT** [comment]
that is kind of weird as I see 
https://github.com/kata-containers/tests/blob/stable-2.1/.ci/setup_env_ubuntu.sh#L39
/cc @fidencio

**Comment by fidencio** [comment]
@GabyCT, the arm CI will fail until https://github.com/kata-containers/tests/pull/3513 gets merged.

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
