### PR TITLE
runtime-rs: split amend_spec function

### PR DESCRIPTION
**Pull request by liubin**
amend_spec do two works:

- modify the spec
- check if the pid namespace is enabled

This make it confusable. So split it into two functions.

Fixes: #5062

Signed-off-by: Bin Liu <bin@hyper.sh>

### CODE REVIEW

**Review by Tim-0731-Hzt — APPROVED** [review]
Thanks @liubin

**Review by quanweiZhou — APPROVED** [review]
Thanks @liubin, LGTM.

**Review by jodh-intel — APPROVED** [review]
Thanks @liubin.

lgtm

**Review by cmaf — APPROVED** [review]
thanks @liubin

**Pull request merged**
