### PR TITLE
CI: Create GHA to add PR sizing label

### PR DESCRIPTION
**Pull request by jodh-intel**
Created a new GitHub Action workflow file that adds a sizing label to
each PR.

Fixes: #3841.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
dnm - blocked on https://github.com/kata-containers/.github/pull/42.

**Review by liubin — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jodh-intel!

**Comment by jodh-intel** [comment]
Skipping ARM which looks like it's suffering from an upstream packaging issue:

```
10:40:11 Setting up docker-ce-rootless-extras (5:20.10.12~3-0~ubuntu-focal) ...
10:40:11 dpkg: dependency problems prevent configuration of docker-ce:
10:40:11  docker-ce depends on containerd.io (>= 1.4.1); however:
10:40:11   Package containerd.io is not configured yet.
10:40:11 
10:40:11 dpkg: error processing package docker-ce (--configure):
10:40:11  dependency problems - leaving unconfigured
10:40:11 Processing triggers for man-db (2.9.1-1) ...
10:40:11 Processing triggers for systemd (245.4-4ubuntu3.15) ...
10:40:12 Errors were encountered while processing:
10:40:12  containerd.io
10:40:12  docker-ce
10:40:12 E: Sub-process /usr/bin/dpkg returned an error code (1)
10:40:12 [jenkins_job_build.sh:168] ERROR: ci/setup.sh
```
/retest-arm

**Comment by jodh-intel** [comment]
Holding off merging this until [this one](https://github.com/kata-containers/tests/pull/4551) works.

**Comment by jodh-intel** [comment]
As shown on the new GHA check on https://github.com/kata-containers/kata-containers/pull/3850, this isn't working as the default token doesn't have the correct privileges to run this action.

**Pull request merged**
