### PR TITLE
# Kata Containers 3.1.3

### PR DESCRIPTION
**Pull request by fidencio**
- [stable-3.1] Fix deprecated virtiofsd args (go shim only)
- [stable-3.1] backport: versions: Use ubuntu as the default distro for the rootfs-image
- runtime: sending SIGKILL to qemu (backport to 3.1)

a43f10beb release: Adapt kata-deploy for 3.1.3
993ecec93 virtiofsd: Convert legacy `-o` sub-options to their `--` replacement
2e9125c32 virtiofsd: Drop `-o no_posix_lock`
407727e1f virtiofsd: Stop using deprecated `-f` option
6668ddb8b versions: Use ubuntu as the default distro for the rootfs-image
075a31128 runtime: sending SIGKILL to qemu

### CODE REVIEW

**Review by gkurz — APPROVED** [review]
LGTM. Thanks @fidencio !

**Review by bergwolf — APPROVED** [review]
lgtm!

**Pull request merged**
