### PR TITLE
Open CONFIG_VIRTIO_MEM in x86_64 Linux kernel

### PR DESCRIPTION
**Pull request by teawater**
Open CONFIG_VIRTIO_MEM in x86_64 Linux kernel.

Fixes: #1798

Signed-off-by: Hui Zhu <teawater@antfin.com>

### CODE REVIEW

**Review by liubin — APPROVED** [review]

**Comment by fidencio** [comment]
@liubin, @teawater, @kata-containers/architecture-committee, I **think** we could have this one backported to the stabe-2.1.0.
WDYT?

**Review by fidencio — APPROVED** [review]
lgtm, thanks @teawater!

**Comment by fidencio** [comment]
@liubin, please, feel free to remone the do-not-merge label and have it merged.  I just would like to check whether it's worth t have as part of the 2.1.0 release.

**Comment by teawater** [comment]
> @liubin, @teawater, @kata-containers/architecture-committee, I **think** we could have this one backported to the stabe-2.1.0.
> WDYT?

Current commit will open a new feature of Linux kernel.  I think it is not very suitable for a stable release.

**Comment by fidencio** [comment]
> > @liubin, @teawater, @kata-containers/architecture-committee, I **think** we could have this one backported to the stabe-2.1.0.
> > WDYT?
> 
> Current commit will open a new feature of Linux kernel. I think it is not very suitable for a stable release.

I agree, but 2.1.0 was not released yet.  Having this feature enabled in the kernel would be a plus for those who'd be willing to test 2.1.0.

For sure I would **not** like to see this as part of a 2.0.4 release ... but 2.1.0, that may be worth it.

**Comment by fidencio** [comment]
Yay!  Thanks @teawater!

**Comment by fidencio** [comment]
Ah, wait, I just realised another thing.
Shouldn't we also bump https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kernel/kata_config_version ?

AFAIU that should be bumped on every new kernel config, so CI jobs can properly handle a new kernel, build it ( or avoid to build it ), saving us some time on CI-land.

**Comment by teawater** [comment]
> Ah, wait, I just realised another thing.
> Shouldn't we also bump https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kernel/kata_config_version ?
> 
> AFAIU that should be bumped on every new kernel config, so CI jobs can properly handle a new kernel, build it ( or avoid to build it ), saving us some time on CI-land.

Updated commit for it.
Thanks!

**Comment by fidencio** [comment]
Let's get it merged then, thanks @teawater!

**Comment by fidencio** [comment]
ARM CI is known to be broken and we're workin on that.
I don't think Ubuntu 20.04 CI is ready yet to be used, but I'll check with @GabyCT later Today.

**Pull request merged**
