### PR TITLE
stable-2.3: cgroups systemd fix 

### PR DESCRIPTION
**Pull request by snir911**
bcf181b7 cgroups: Fix systemd cgroup support
b34ed403 cgroups: pass vhost-vsock device to cgroup
7362e1e8 runtime: remove prefix when cgroups are managed by systemd
(once #2959 is merged)

### CODE REVIEW

**Review by gkurz — APPROVED** [review]
LGTM. Thanks @snir911 !

**Comment by snir911** [comment]
Failing tests are waiting https://github.com/kata-containers/kata-containers/pull/3039

**Review by gkurz — APPROVED** [review]
Still LGTM. Thanks @snir911 !

**Review by bergwolf — APPROVED** [review]
Thanks!

**Pull request merged**
