### PR TITLE
virtcontainers: split out linux-specific bits for mount, factory

### PR DESCRIPTION
**Pull request by egernst**
This PR addresses virtcontainers/mount.go and factory pkg in order to ensure that they can be built on other architectures. This is part of the effort here: https://github.com/kata-containers/kata-containers/issues/3004

This is a code organization change and does not introduce any functional changes.

### CODE REVIEW

**Comment by egernst** [comment]
WIP -- need to fix up some unit tests!

**Review by fengwang666 — APPROVED** [review]
LGTM

**Review by fidencio — APPROVED** [review]
lgtm, thanks @egernst!

**Pull request merged**
