### PR TITLE
tools: Avoid building the kernel twice

### PR DESCRIPTION
**Pull request by zvonkok**
Fixes: #6588

`install_kata` does not set arch so setting it like in `build_kernel`

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @zvonkok!

**Review by cmaf — APPROVED** [review]
thanks @zvonkok

**Comment by zvonkok** [comment]
@cmaf Done.

**Review by amshinde — APPROVED** [review]

**Pull request merged**
