### PR TITLE
runtime-rs: Update status for pause and resume

### LINKED ISSUE #6434: runtime-rs: ch: Implement pause/resume VM
Implement the following methods in https://github.com/kata-containers/kata-containers/blob/main/src/runtime-rs/crates/hypervisor/src/ch/inner_hypervisor.rs:

- `pause_vm()`
- `resume_vm()`

### PR DESCRIPTION
**Pull request by cmaf**
Pause and resume task do not currently update the status of the container to paused or running, so fix this. This is for specifically pausing the task and not the VM.

Fixes #6434

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Comment by cmaf** [comment]
Added WIP label since I need to make `pause` and `resume` atomic before merging

**Comment by cmaf** [comment]
The locking is already covered by `.write()` which returns a RwLockWriteGuard which locks with exclusive write access.

**Review by jodh-intel — APPROVED** [review]
Thanks @cmaf - lgtm.

Comment: yes, this does initially feel slightly "sneaky" in that we don't set the intermediate "pausing". However, it does mean that we can _effectively_ be atomic and tbh if we were to use `ProcessStatus::Pausing`, there should strictly be a corresponding `ProcessStatus::Resuming`, but there isn't :smile:

If we find this feature gets used a lot _and_ if we encounter noticeable delays in pausing / resuming, we can revisit the issue at that point.

> **Note:** For bonus points, it should be possible to construct a test that uses a fake `Agent` inside the `ContainerManager` so that you could test the failure scenarios and assert the expected states (possibly on a follow-up PR?)

**Review by amshinde — APPROVED** [review]

**Comment by amshinde** [comment]
Looks like there was an error on uploading the tarball in GH workflow. Rerunning jobs.

**Pull request merged**
