### PR TITLE
kata-deploy: fix tar command in dockerfile

### PR DESCRIPTION
**Pull request by snir911**
tar params are passed wrongly

Fixes: #3394
Signed-off-by: Snir Sheriber <ssheribe@redhat.com>

### CODE REVIEW

**Review by wainersm — APPROVED** [review]
@snir911 I broke that Dockerfile when I delinted the dockerfiles of the project. Thanks for fixing it Snir!

**Review by fidencio — APPROVED** [review]
lgtm, thanks @snir911!

**Comment by fidencio** [comment]
Let's monitor https://github.com/kata-containers/kata-containers/actions/runs/1660355651 before merging this one.

**Comment by fidencio** [comment]
> Let's monitor https://github.com/kata-containers/kata-containers/actions/runs/1660355651 before merging this one.

Ah, okay, it has to be merged to be used :-/

**Pull request merged**
