### PR TITLE
initrd: Increase Alpine Version to 3.12

### LINKED ISSUE #610: [forward port]: initrd: Increase Alpine Version to 3.12
Port https://github.com/kata-containers/runtime/pull/2874 (issue https://github.com/kata-containers/runtime/issues/2873) from Kata 1.x.

### PR DESCRIPTION
**Pull request by jschintag**
Upgrade Alpine version from unsupported 3.7 to supported 3.12

Fixes #610

Signed-off-by: Jan Schintag jan.schintag@de.ibm.com

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @jschintag !

lgtm

**Comment by devimc** [comment]
missing < > in the signed-off

**Comment by jschintag** [comment]
Thanks @devimc , i thought i could be lazy and create this PR directly in the Webbrowser because it was just one line. This'll teach me.

**Pull request merged**
