### PR TITLE
CC | Update to v0.7.0 tags 

### PR DESCRIPTION
**Pull request by fitzthum**
Fixes: #7400 

Step 16 of https://github.com/confidential-containers/confidential-containers/issues/111

### CODE REVIEW

**Review by wainersm — APPROVED** [review]

**Review by jepio — APPROVED** [review]

**Comment by jepio** [comment]
@UnmeshDeodhar 
same SEV failure as we've been seeing all week:
```
00:06:45 not ok 3 [cc][kubernetes][containerd][sev] Test SEV encrypted container launch success with NO measurement
00:06:45 # (from function `kubernetes_wait_for_pod_ready_state' in file lib.sh, line 42,
00:06:45 #  in test file confidential/sev.bats, line 193)
00:06:45 #   `kubernetes_wait_for_pod_ready_state "$pod_name" 20' failed
00:06:45 # Deleting previous test services...
00:06:45 # ls: cannot access '/tmp/test-kata-sev.KKU6wJeX/*.yaml': No such file or directory
00:06:45 # mysql: [Warning] Using a password on the command line interface can be insecure.
00:06:45 # mysql: [Warning] Using a password on the command line interface can be insecure.
00:06:45 # service/sev-encrypted unchanged
00:06:45 # deployment.apps/sev-encrypted unchanged
00:06:45 # error: timed out waiting for the condition on pods/sev-encrypted-dd9f8bbb9-5hmdv
```

**Comment by fidencio** [comment]
/test-tdx

As those ended up not being triggered.

**Comment by fidencio** [comment]
TDX is failing due to the network issues building the components.
As this is **NOT** bringing anything new, I'm giving the green light to have it merged even with the tests not passing.

**Comment by wainersm** [comment]
> @UnmeshDeodhar same SEV failure as we've been seeing all week:
> 
> ```
> 00:06:45 not ok 3 [cc][kubernetes][containerd][sev] Test SEV encrypted container launch success with NO measurement
> 00:06:45 # (from function `kubernetes_wait_for_pod_ready_state' in file lib.sh, line 42,
> 00:06:45 #  in test file confidential/sev.bats, line 193)
> 00:06:45 #   `kubernetes_wait_for_pod_ready_state "$pod_name" 20' failed
> 00:06:45 # Deleting previous test services...
> 00:06:45 # ls: cannot access '/tmp/test-kata-sev.KKU6wJeX/*.yaml': No such file or directory
> 00:06:45 # mysql: [Warning] Using a password on the command line interface can be insecure.
> 00:06:45 # mysql: [Warning] Using a password on the command line interface can be insecure.
> 00:06:45 # service/sev-encrypted unchanged
> 00:06:45 # deployment.apps/sev-encrypted unchanged
> 00:06:45 # error: timed out waiting for the condition on pods/sev-encrypted-dd9f8bbb9-5hmdv
> ```

SEV 2nd tentative passed! \o/

**Comment by wainersm** [comment]
> TDX is failing due to the network issues building the components. As this is **NOT** bringing anything new, I'm giving the green light to have it merged even with the tests not passing.

@fidencio ,

jenkins-ci-tdx-x86_64-cc_cri_containerd_k8s-qemu  is still running. Shall I wait it finish? Would you like to try TDX jobs one more time?

**Comment by fidencio** [comment]
> > TDX is failing due to the network issues building the components. As this is **NOT** bringing anything new, I'm giving the green light to have it merged even with the tests not passing.
> 
> @fidencio ,
> 
> jenkins-ci-tdx-x86_64-cc_cri_containerd_k8s-qemu is still running. Shall I wait it finish? Would you like to try TDX jobs one more time?

Nops, let's have it merged.

**Pull request merged**
