### PR TITLE
CCv0: Merge main into CCv0 branch

### PR DESCRIPTION
**Pull request by stevenhorsman**
Merge remote-tracking branch 'upstream/main' into CCv0

Re-attempting the merge from 14th Feb `main` after confidential-containers' containerd was updated.
    
Fixes: #3573
Signed-off-by: stevenhorsman <steven@uk.ibm.com>

### CODE REVIEW

**Review by wainersm — APPROVED** [review]

**Comment by stevenhorsman** [comment]
@fidencio, or anyone else who sees - I got green integration tests here and in https://github.com/kata-containers/tests/pull/4451/, so I added `force-skip-ci` label, to try and let me merge, but the static checks are still running and failing, which based on https://github.com/kata-containers/kata-containers/blob/1dcb413e68701004355299e8858d58e46784b97e/.github/workflows/static-checks.yaml#L81-L84
I wasn't expecting. Have I done something else wrong, or missed something?

**Comment by jodh-intel** [comment]
From the static checks log:

```
Running checkcommits version 0.0.1 (commit 4b71445e4e1a3689ec9ad1243eac6c3c02b44291)
Found 385 commits between commit HEAD and branch CCv0
ERROR: Commit 306f54a90780b3b8f833fd7b9217890581d98b25: Failed to find subsystem in subject: "ciao-launcher, qemu: Move launchQemu to qemu"
ERROR: checkcommits failed. See the document below for help on formatting
commits for the project.

https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format
```

@stevenhorsman - That's an odd commit... from 2017! ;)

```
commit a8a798b0c02ba46476490ab22e99d8f9cf84b288
Author: Mark Ryan <mark.d.ryan@intel.com>
Date:   Mon Feb 6 12:16:09 2017 +0000

    qemu, ciao-launcher:  Move ConfigDrive ISO creation code to qemu

    Launcher's ConfigDrive ISO creation function, createCloudInitISO has
    been moved to the qemu package so that it can be re-used by ciao-down.

    Signed-off-by: Mark Ryan <mark.d.ryan@intel.com>

 image.go | 72 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 72 insertions(+)
```

I think the problem here is that this PR is now trying to pull in the contents of the [govmm](https://github.com/kata-containers/govmm/) repo (which pre-dates Kata I think) that was adopted into Kata. Certainly that commit summary line is not "valid" for Kata since it doesn't conform to our [patch format](https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format). Hence, I think we may need to consider forcing this PR.

See:

- https://github.com/kata-containers/kata-containers/pull/3468#issuecomment-1017330442
- https://github.com/kata-containers/kata-containers/pull/3496

/cc @fidencio.

**Comment by stevenhorsman** [comment]
Yeah, I spotted the problem and have chatted to fidencio about the reason, but I thought with the `force-skip-ci` label it shouldn't run that test and therefore get a pass. I guess if it doesn't work as I expect then we can either:
- force push
- temporarily remove the commit message and static check from being required to merge.

**Comment by jodh-intel** [comment]
idm as long as whatever we do only affects the CCv0 branch and not `main`.

**Comment by fidencio** [comment]
The tests were marked as not required and the branch was merged, as per suggested and agreed during the Confidential Containers meeting held in February 17th, 2022.

**Pull request merged**
