### PR TITLE
agent-ctl: Fix abstract socket connections

### PR DESCRIPTION
**Pull request by jodh-intel**
Unbreak the `agent-ctl` tool connecting to the agent with a Unix domain
socket.

It appears that [1] changed the behaviour of connecting to the agent
using a local Unix socket (which is not used by Kata under normal
operation).

The change can be seen by reverting to commit
72b8144b569f1d0fef3001642f244bf79b17ddc6 (the one before [1]) and
running the agent manually as:

```bash
$ sudo KATA_AGENT_SERVER_ADDR=unix:///tmp/foo.socket target/x86_64-unknown-linux-musl/release/kata-agent
```

Before [1], in another terminal we see this:

```bash
$ sudo lsof -U 2>/dev/null |grep foo|awk '{print $9}'
@/tmp/foo.socket@
```

But now, we see the following:

```bash
$ sudo lsof -U 2>/dev/null |grep foo|awk '{print $9}'
@/tmp/foo.socket
```

Note the last byte which represents a nul (`\0`) value.

The `agent-ctl` tool used to add that trailing nul but now it seems to not
be needed, so this change removes it, restoring functionality. No
external changes are necessary so the `agent-ctl` tool can connect to
the agent as below like this:

```bash
$ cargo run -- -l debug connect --server-address "unix://@/tmp/foo.socket" --bundle-dir "$bundle_dir" -c Check -c GetGuestDetails
```

[1] - https://github.com/kata-containers/kata-containers/issues/3124

Fixes: #4164.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jodh-intel!

**Comment by fidencio** [comment]
@jodh-intel, do you think this one deserves a backport?

**Comment by jodh-intel** [comment]
Updated to add doc details of how to use a local VSOCK socket as that's related to this indirectly (local VSOCK is an alternative to a Unix socket).

**Comment by jodh-intel** [comment]
@fidencio - It's not a tool we provide to users, so I'm uncertain tbh.

**Review by cmaf — COMMENTED** [review]
@jodh-intel The VSOCK loopback socket workaround didn't work for me, but I'm going to test the agent-ctl change locally

**Review by cmaf — APPROVED** [review]
thanks @jodh-intel, the change to client.rs fixed it

**Pull request merged**
