### PR TITLE
clh: arm: Use static_sandbox_resource_mgmt=true

### PR DESCRIPTION
**Pull request by fidencio**
Users have noticed that this is needed, as CLH does not yet implement a way to hotplug resources on aarh64.

With this patch, when building for x86_64, I can see the this is the resulting config:
```
$ ARCH=amd64 make
...

$ cat config/configuration-clh.toml | grep static_sandbox_resource_mgmt
static_sandbox_resource_mgmt=false

```

And when building for aarch64:
```
$ ARCH=arm64 make
...

$ cat config/configuration-clh.toml | grep static_sandbox_resource_mgmt
static_sandbox_resource_mgmt=true
```

Fixes: #7941

### CODE REVIEW

**Review by jepio — APPROVED** [review]

**Comment by gkurz** [comment]
@fidencio shouldn't this backported to 3.2 ?

**Comment by fidencio** [comment]
> @fidencio shouldn't this backported to 3.2 ?

It should!

**Comment by fidencio** [comment]
I am bypassing the WIP check that got stuck and never started, instead of re-running the whole CI. :-/

**Pull request merged**
