### PR TITLE
CCv0: Merge main into CCv0 branch

### PR DESCRIPTION
**Pull request by GeorginaKin**
Merge remote-tracking branch 'upstream/main' into CCv0
    
Fixes: #5824
Signed-off-by: Georgina Kinge <georgina.kinge@ibm.com>

### CODE REVIEW

**Comment by GeorginaKin** [comment]
```
git diff --stat upstream/main -- . ':!*/vendor/*'
 src/agent/Cargo.lock                     | 4057 ++++++++++++++++++++++++++++++++++++++++++++++++++++++--------
 src/agent/Cargo.toml                     |    8 +-
 src/agent/Makefile                       |    8 +
 src/agent/rustjail/src/cgroups/fs/mod.rs |   19 +-
 src/agent/rustjail/src/lib.rs            |    8 +-
 src/agent/src/config.rs                  |  327 ++++-
 src/agent/src/device.rs                  |   18 +-
 src/agent/src/image_rpc.rs               |  426 +++++++
 src/agent/src/main.rs                    |    1 +
 src/agent/src/rpc.rs                     |  333 +++++-
 src/agent/src/sandbox.rs                 |    2 +
 src/agent/src/signal.rs                  |    2 +-
 12 files changed, 4680 insertions(+), 529 deletions(-)
```

**Comment by stevenhorsman** [comment]
@UnmeshDeodhar FYI,  we've been seeing a bunch of network related failures in the SEV re-queues, in ubuntu package upgrades and downloading crates, so I think there is something wrong with the node.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @GeorginaKin!

**Comment by fidencio** [comment]
@UnmeshDeodhar:
```
12:43:03 Cloning into 'sevctl'...
12:43:03  Downloading crates ...
12:43:04 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (1 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (1 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (1 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (1 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (1 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 warning: spurious network error (2 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 error: failed to download from `[https://crates.io/api/v1/crates/serde/1.0.137/download`](https://crates.io/api/v1/crates/serde/1.0.137/download%60)
12:43:05 
12:43:05 Caused by:
12:43:05   [35] SSL connect error (OpenSSL SSL_connect: Connection reset by peer in connection to static.crates.io:443 )
12:43:05 ERROR Encountered with Exit Code: 101
```

**Pull request merged**
