### PR TITLE
qemu: add v5.1.0 dir under tag_patches

### PR DESCRIPTION
**Pull request by jongwu**
A related dir is needed when apply qemu patch using script. As qemu 5.1
is used for arm, a dir of "v5.1.0" is needed under tag_patches.

Fixes: #2696
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jongwu!

**Comment by fidencio** [comment]
This one would be good to be backported to the stable-2.2 branch.

**Review by GabyCT — APPROVED** [review]

**Comment by Jakob-Naucke** [comment]
Backport requirement superseded by #2702.

**Pull request merged**
