### PR TITLE
vendor: update govmm

### LINKED ISSUE #3080: Update govmm
See https://github.com/kata-containers/govmm/issues/205
And the new govmm deleted [`config.Knobs.Realtime`](https://github.com/kata-containers/govmm/pull/190/files), so runtime codes should be adjusted too.

### PR DESCRIPTION
**Pull request by devimc**
bring SGX support and other fixes

shortlog:
8939b0f qemu: add support for SGX
b17f073 qemu: update readonly flag for block devices
f971801 qemu: only set wait parameter for server mode socket based
        char device
82cc01d qemu: Fix 32 bit int overflow in test file
1d1a231 qemu: Add support for legacy serial device
9a2bbed qemu: Remove -realtime in favor of -overcommit
fe83c20 qemu: Add support for --no-shutdown Knob
1ed5271 qmp: wait for POWERDOWN event in ExecuteSystemPowerdown()

fixes #3080

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, assuming a green CI.

Thanks @devimc!

**Comment by devimc** [comment]
thanks @fidencio -  I forgot to add the `do-not-merge` label since the latest govmm repo is not working with Kata, I will try to fix it

**Comment by bergwolf** [comment]
Can we just move govmm under `src/runtime/pkg/`?

**Comment by fidencio** [comment]
@bergwolf, @devimc, please, take a look at https://github.com/kata-containers/kata-containers/pull/3468

**Review by GabyCT — APPROVED** [review]

**Comment by fidencio** [comment]
@devimc, I think the guest swap code removal is worth an issue.  Also, let's cc @teawater who worked on that.

**Comment by devimc** [comment]
@fidencio that's a different thing, swap guest support is still there

**Comment by fidencio** [comment]
> @fidencio that's a different thing, swap guest support is still there

Aha, I got confused, indeed. Sorry for the noise!

**Review by fidencio — APPROVED** [review]
lgtm, thanks @devimc!

**Pull request merged**
