### PR TITLE
Backport to stable-2.0 branch

### PR DESCRIPTION
**Pull request by bergwolf**
backport following commits:

```
David Gibson (2):
      runtime/network: Correct error reporting in listInterfaces()
      runtime/network: Fix error reporting in listRoutes()

Eric Ernst (1):
      qemu: no state to save if QEMU isn't running

Fabiano Fidêncio (6):
      trace-forwarder: Add void "install" target
      agent-ctl: Add void "install" target
      rootfs: Don't fallthrough in the docker_extra_args() switch
      rootfs: Always add SYS_ADMIN, CHROOT, and MKNOD caps to docker cmdline
      rootfs: apparmor=unconfined is needed for non Red Hat host OSes
      rootfs: Fix indentation inside a switch

Julio Montes (3):
      rootfs-builder: add functions to run before and after the container
      rootfs: reduce size of debian image
      rootfs-builder: add support for gentoo

Liu Jiang (5):
      oci: fix a typo in "addtionalGids"
      agent: consume ttrpc crate from crates.io
      oci: fix two incompatible issues with OCI spec
      rustjail: add more context info for errors
      jail/validator: avoid unwrap() for safety

Maruth Goyal (1):
      agent/sandbox:  Don't update cpuset when ncpus = 0

Snir Sheriber (2):
      shimv2: Avoid double removing of container from sandbox
      rustjail: allow network sysctls

Tim Zhang (1):
      agent: Avoid container stats panic caused by cgroup controller non-exist

Wainer dos Santos Moschetta (7):
      packaging/qemu: Add QEMU_DESTDIR argument to dockerfiles
      packaging/qemu: Build and package completely in the container
      packaging/qemu: Delete the temporary container
      runtime: Allow to overwrite DESTDIR
      agent: Return error on trying to persist a pid namespace
      agent: Fix temp prefix on Namespace::test_setup_persistent_ns
      agent: Clean up commented use declarations

fupan.lfp (2):
      rustjail: fix the issue of bind mount /dev
      rustjail: fix the issue of sync read
```

### CODE REVIEW

**Comment by fidencio** [comment]
@snir911, as this covers your backports, would you mind to drop your PR in favour of this one?
Thanks, @bergwolf! I'll do a review soon enough. :-)

**Comment by fidencio** [comment]
Hmm. the `jenkins-ci-ubuntu-18-04-initrd` issue should have been fixed by https://github.com/kata-containers/tests/commit/642d46c64363c6afc26717eecbfcca99ba6baadc

**Review by jodh-intel — APPROVED** [review]
Thanks @bergwolf.

**Review by fidencio — APPROVED** [review]
I've retriggered the tests and the PR lgtm!

Thanks, @bergwolf!

**Comment by egernst** [comment]
@devimc is looking at the VFIO failure.

**Pull request merged**
