### PR TITLE
# Kata Containers 2.5.0

### PR DESCRIPTION
**Pull request by bergwolf**
c2f6d1cb6 release: Adapt kata-deploy for 2.5.0
127f9d986 build: Fix clh source build as normal user
95f861122 runtime: Fix DisableSelinux config
70ac16ba6 container: kill all of the processes in this container
8220e5478 runtime: add unlock before return in sendReq
4f0ca40e0 versions: Update Firecracker version to v1.1.0
da24fd88e clh: Don't crash if no network device is set by the upper layer
ed25d2cf5 versions: Update Cloud Hypervisor to v25.0
dfc1413e4 action: extend commit message line limit to 150 bytes

### CODE REVIEW

**Comment by fidencio** [comment]
@bergwolf, I think there were more PRs that needed to be backported, they have been labeled properly but we need to backport them.

Please, hold it till we have those backported.

**Comment by bergwolf** [comment]
@fidencio Sure, I've labeled this as `do-not-merge`.

**Comment by bergwolf** [comment]
I've backported these missing commits. Removing `do-not-merge` label.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @bergwolf!

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks!

**Comment by fidencio** [comment]
> /test_kata_deploy

https://github.com/kata-containers/kata-containers/runs/7852716493?check_suite_focus=true

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
