### PR TITLE
osbuilder: Restore Debian as a rootfs

### PR DESCRIPTION
**Pull request by zhaojizhuang**
Restore Debian as a rootfs. Relate Issue #3372 
1. revert of #3154, but some change
2. update debian version to `10.11`
3. update  `libstdc++-6-dev` to `libstdc++-8-dev`
4.  changes discarded in QAT are not restored

Fixes: #3372
Signed-off-by: zhaojizhuang <571130360@qq.com>

### CODE REVIEW

**Comment by zhaojizhuang** [comment]
cc @fidencio

**Review by jodh-intel — APPROVED** [review]
Thanks @zhaojizhuang !

lgtm.

I've also added you to https://github.com/kata-containers/community/wiki/Areas-of-interest#distributions to show you have an interest in Kata + Debian.

**Review by liubin — APPROVED** [review]

**Comment by zhaojizhuang** [comment]
Got it ! Thank you,

By the way ,the pipeline `jenkins-ci-s390x-ubuntu-20-04 ` failed, It seems that k8s cluster hasn't been installed success, should we retest the single pipeline？ 

> Thanks @zhaojizhuang !
> 
> lgtm.
> 
> I've also added you to https://github.com/kata-containers/community/wiki/Areas-of-interest#distributions to show you have an interest in Kata + Debian.

**Pull request merged**
