### PR TITLE
agent: mount: augment ensure_destintation_exists tests

### PR DESCRIPTION
**Pull request by egernst**
Saw bugs downstream with ensure_destination_exists, and then noticed that Fupan already fixed it!  

Let's add a couple extra pieces to the test to ensure that we're covering mountpoints that are destinations, not just files.

Fixes: #xxxx

Signed-off-by: Eric Ernst <eric_ernst@apple.com>

### CODE REVIEW

**Comment by egernst** [comment]
@lifupan  - I noticed this function doesn't handle directories very well; and I'm not sure it *could* handle this as is, since it has no way based on a destination path to determine if the caller is intending to create a mount point for a file versus a directory. Perhaps we should update the function description accordingly? Or, WDYT?

**Comment by egernst** [comment]
Thanks Fupan. Yeah, I was going to use for my bind-watcher, but ended up skipping once I noticed the limitation.

**Review by fidencio — COMMENTED** [review]
LGTM, but I'd like to get a review also from someone else more experienced with rust.
@dgibson, mind to take a look at this one?

**Comment by dgibson** [comment]
Sigh.  The extra tests are ok, of themselves, but they kind of miss the point.  `ensure_destination_exists()` definitely is broken, but the new tests don't exercise why.

Basically the `|| d.is_dir()` in `ensure_destination_exists()` will never trigger: we've already established that the target doesn't exist, in which case it certainly can't be a directory.  The fundamental problem here is that "fs_type" is not useful information: if it's `bind` it's *possible* that we want a file rather than a directory, but we don't *know* we want a file rather than a directory.  So `ensure_destination_exists()` will only do the right thing for bind mount directories if the destination already exists, in which case we didn't need to call it anyway.

Also the existing tests (not the ones in this patch) use `into_path()` instead of `path()` which will have the side effect of not cleaning up the temp dirs afterwards.

And... for all that `ensure_destination_exists()` has exactly one caller (besides its tests).  Where it's an alternative used in some cases to an open-coded version of... precisely a subset of what it does.

**Comment by dgibson** [comment]
Oh, for pete's sake.  *And* it looks like none of the paths that would lead to the single caller of ensure_destination_exists() would make sense with fstype == bind in any case.

**Comment by dgibson** [comment]
Ok, as noted, this PR isn't wrong of itself, but really the problem is more fundamental than it's addressing: `ensure_destination_exists()` doesn't actually do anything useful.  I suggest we close this PR in favour of #2428 which eliminates the function entirely.

**Comment by fidencio** [comment]
Let me add the `do-not-merge` label in order to ensure we have a discussion about @dgibson's suggestion before merging this PR.
Thanks for taking a look at this one, and for opening #2428 @dgibson

**Comment by egernst** [comment]
Yeah agreed, David.  I had to work through the unit tests just to come to conclusion that it was a bit sub-optimal for usage. I'm good with it. Thanks!

**Pull request closed without merging**
