### PR TITLE
genpolicy: add back support for insecure

### PR DESCRIPTION
**Pull request by Redent0r**
registries

Adding back changes from
77540503f9b38ac75ead13e4bde6c07ff75ba311.

Fixes: #9008

### CODE REVIEW

**Review by burgerdev — APPROVED** [review]
Thanks a lot!

**Review by danmihai1 — APPROVED** [review]

**Review by sprt — APPROVED** [review]

**Comment by wainersm** [comment]
Hi @Redent0r @danmihai1 !

This feature was merged in https://github.com/kata-containers/kata-containers/pull/9294 then reverted (what commit?). Why?

Now that we are putting it back, what has changed?

**Comment by Redent0r** [comment]
> Hi @Redent0r @danmihai1 !
> 
> This feature was merged in #9294 then reverted (what commit?). Why?
> 
> Now that we are putting it back, what has changed?

Hi @wainersm. PTAL https://github.com/kata-containers/kata-containers/pull/9530/commits/2149cb65028d0f563f6d9534188379cbecb7ddd9#r1627146985. This was removed by me by accident in an unrelated PR. Thanks!

**Comment by wainersm** [comment]
> > Hi @Redent0r @danmihai1 !
> > This feature was merged in #9294 then reverted (what commit?). Why?
> > Now that we are putting it back, what has changed?
> 
> Hi @wainersm. PTAL [2149cb6#r1627146985](https://github.com/kata-containers/kata-containers/commit/2149cb65028d0f563f6d9534188379cbecb7ddd9#r1627146985). This was removed by me by accident in an unrelated PR. Thanks!

ah, ok, accidents happen!

Allow me to ask you, @Redent0r , one more thing: you have a couple of PRs marked as `wip` (and/or `do-not-merge`). With those labels developers usually won't even review them. Is it really your intention, i.e, they are really wip?

**Pull request merged**
