### PR TITLE
agent: Fix cargo 1.54 clippy warning

### LINKED ISSUE #2408: rust 1.54 clippy warnings and errors
Rust 1.54 brings a few new linters that trigger `make check` errors for the kata agent.

### PR DESCRIPTION
**Pull request by sameo**
Mostly the needless borrow one, plus a few others that are now enforced.

Fixes #2408

Signed-off-by: Samuel Ortiz <s.ortiz@apple.com>

### CODE REVIEW

**Comment by fidencio** [comment]
DCO check is failing:
```
Error: The SoB (DCO) check failed

  0cc4594518d5b8230286e7520b32db361ad54cc6    Expected "Samuel Ortiz <samuel.e.ortiz@protonmail.com>", but got "Samuel Ortiz <s.ortiz@apple.com>".

  What should I do to fix it ?

  All proposed commits should include a Signed-Off-By: <your-email-address> line in their commit message.
  This is most conveniently done by using --signoff (-s) when running git commit.
```

I'd advise to also bump the minimal rust version used, but I'd recommend checking what's the version used downstream to ensure there's no issue. /cc @marcel-apf, @dgibson to ensure no issue is hit by bumping the version, if we take this path.

**Comment by sameo** [comment]
> DCO check is failing:
Fixed.


> I'd advise to also bump the minimal rust version used

I'll wait for downstream's feedback and will bump to 1.54.

**Review by egernst — APPROVED** [review]

**Review by jcvenegas — APPROVED** [review]

**Pull request merged**
