### PR TITLE
CC | Update deps 0.7.0 (rc)

### PR DESCRIPTION
**Pull request by jepio**
This update the CC dependencies to the 0.7.0-rc commits.

Step 4. on https://github.com/confidential-containers/confidential-containers/issues/111.

### CODE REVIEW

**Comment by fidencio** [comment]
QEMU TDX failures are legit. /cc @arronwy

**Comment by fidencio** [comment]
Failure on the cloud-hypervisor CI:
```
09:37:38 INFO: Install attestation-agent with KBC offline_fs_kbc
09:37:38 Cloning into 'guest-components'...
09:37:40 /guest-components/attestation-agent /
09:37:42 From https://github.com/confidential-containers/guest-components
09:37:42  * branch            88dcc147ba8ddf34e8425c98d5931df8a995f04a -> FETCH_HEAD
09:37:42 Note: switching to 'FETCH_HEAD'.
09:37:42 
09:37:42 You are in 'detached HEAD' state. You can look around, make experimental
09:37:42 changes and commit them, and you can discard any commits you make in this
09:37:42 state without impacting any branches by switching back to a branch.
09:37:42 
09:37:42 If you want to create a new branch to retain commits you create, you may
09:37:42 do so (now or later) by using -c with the switch command. Example:
09:37:42 
09:37:42   git switch -c <new-branch-name>
09:37:42 
09:37:42 Or undo this operation with:
09:37:42 
09:37:42   git switch -
09:37:42 
09:37:42 Turn off this advice by setting config variable advice.detachedHead to false
09:37:42 
09:37:42 HEAD is now at 88dcc14 cc-kbc: fix kbs url in resource request
09:37:42 DEBIANOS is: true
09:37:42 info: component 'rust-std' for target 'x86_64-unknown-linux-musl' is up to date
09:37:42 make: sudo: Command not found
09:37:42 cd app &&  cargo build --release --no-default-features --features " offline_fs_kbc ttrpc,rust-crypto" --target x86_64-unknown-linux-musl
09:37:42     Updating git repository `[https://github.com/krustlet/oci-distribution.git`](https://github.com/krustlet/oci-distribution.git%60)
09:37:42     Updating crates.io index
09:37:46     Updating git repository `[https://github.com/kinvolk/azure-cvm-tooling`](https://github.com/kinvolk/azure-cvm-tooling%60)
09:37:47     Updating git repository `[https://github.com/occlum/occlum`](https://github.com/occlum/occlum%60)
09:37:51     Updating git submodule `[https://github.com/stepancheg/grpc-rust.git`](https://github.com/stepancheg/grpc-rust.git%60)
09:37:53     Updating git submodule `[https://github.com/occlum/itoa-sgx`](https://github.com/occlum/itoa-sgx%60)
09:37:54     Updating git submodule `[https://github.com/tailhook/resolv-conf.git`](https://github.com/tailhook/resolv-conf.git%60)
09:37:55     Updating git submodule `[https://github.com/agerasev/ringbuf.git`](https://github.com/agerasev/ringbuf.git%60)
09:37:56     Updating git submodule `[https://github.com/occlum/incubator-teaclave-sgx-sdk.git`](https://github.com/occlum/incubator-teaclave-sgx-sdk.git%60)
09:38:02     Updating git submodule `[https://github.com/occlum/sefs.git`](https://github.com/occlum/sefs.git%60)
09:38:04     Updating git submodule `[https://github.com/occlum/serde-json-sgx`](https://github.com/occlum/serde-json-sgx%60)
09:38:05     Updating git submodule `[https://github.com/occlum/serde-sgx`](https://github.com/occlum/serde-sgx%60)
09:38:07 warning: skipping duplicate package `init` found at `/root/.cargo/git/checkouts/occlum-09e22bc8c2a4bfe1/dbe404f/demos/remote_attestation/init_ra_flow/init_ra`
09:38:07 warning: skipping duplicate package `init` found at `/root/.cargo/git/checkouts/occlum-09e22bc8c2a4bfe1/dbe404f/example/init_ra`
09:38:07 warning: skipping duplicate package `init` found at `/root/.cargo/git/checkouts/occlum-09e22bc8c2a4bfe1/dbe404f/tools/init`
09:38:07     Updating git repository `[https://github.com/virtee/sev`](https://github.com/virtee/sev%60)
09:38:09     Updating git repository `[https://github.com/intel/SGXDataCenterAttestationPrimitives`](https://github.com/intel/SGXDataCenterAttestationPrimitives%60)
09:38:20 warning: skipping duplicate package `app` found at `/root/.cargo/git/checkouts/sgxdatacenterattestationprimitives-d6934a418e6beae0/71557c7/SampleCode/RustTDQuoteGenerationSample`
09:38:20     Updating git repository `[https://github.com/sigstore/sigstore-rs.git`](https://github.com/sigstore/sigstore-rs.git%60)
09:38:21  Downloading crates ...
09:38:22   Downloaded form_urlencoded v1.2.0
09:38:22   Downloaded io-lifetimes v1.0.11
09:38:22   Downloaded aes-gcm v0.10.2
09:38:23   Downloaded matches v0.1.10
09:38:23   Downloaded regex v1.9.1
09:38:23   Downloaded polyval v0.6.1
09:38:23   Downloaded reqwest v0.11.18
09:38:23   Downloaded num-bigint-dig v0.8.4
09:38:23   Downloaded proc-macro2 v1.0.66
09:38:23   Downloaded quote v1.0.31
09:38:23   Downloaded sha2 v0.10.7
09:38:23   Downloaded rustls-pemfile v1.0.3
09:38:23   Downloaded ryu v1.0.15
09:38:23   Downloaded tempfile v3.6.0
09:38:23   Downloaded serde_derive v1.0.171
09:38:23   Downloaded smallvec v1.11.0
09:38:23   Downloaded tracing-core v0.1.31
09:38:23   Downloaded time-core v0.1.1
09:38:23   Downloaded thiserror-impl v1.0.43
09:38:23   Downloaded syn v2.0.26
09:38:23   Downloaded time-macros v0.2.10
09:38:23   Downloaded url v2.4.0
09:38:23   Downloaded want v0.3.1
09:38:23   Downloaded universal-hash v0.5.1
09:38:23   Downloaded webpki v0.22.0
09:38:23   Downloaded sct v0.7.0
09:38:23   Downloaded h2 v0.3.20
09:38:23   Downloaded tracing v0.1.37
09:38:23   Downloaded untrusted v0.7.1
09:38:23   Downloaded time v0.3.23
09:38:23   Downloaded serde_json v1.0.103
09:38:23   Downloaded unicode-ident v1.0.11
09:38:23   Downloaded tokio-rustls v0.24.1
09:38:23   Downloaded hyper v0.14.27
09:38:23   Downloaded webpki-roots v0.22.6
09:38:23   Downloaded base64 v0.21.2
09:38:23   Downloaded const_format_proc_macros v0.2.31
09:38:23   Downloaded getrandom v0.2.10
09:38:23   Downloaded cpufeatures v0.2.9
09:38:23   Downloaded const_format v0.2.31
09:38:23   Downloaded env_logger v0.9.3
09:38:23   Downloaded cookie v0.16.2
09:38:23   Downloaded clap v3.2.25
09:38:23   Downloaded digest v0.10.7
09:38:23   Downloaded ipnet v2.8.0
09:38:23   Downloaded log v0.4.19
09:38:23   Downloaded once_cell v1.18.0
09:38:23   Downloaded percent-encoding v2.3.0
09:38:23   Downloaded libm v0.2.7
09:38:23   Downloaded serde v1.0.171
09:38:23   Downloaded subtle v2.5.0
09:38:23   Downloaded pin-project-lite v0.2.10
09:38:23   Downloaded os_str_bytes v6.5.1
09:38:23   Downloaded hyper-rustls v0.24.1
09:38:23   Downloaded num_cpus v1.16.0
09:38:23   Downloaded thiserror v1.0.43
09:38:23   Downloaded rustls-webpki v0.101.1
09:38:23   Downloaded rustversion v1.0.14
09:38:23   Downloaded mio v0.8.8
09:38:23   Downloaded aho-corasick v1.0.2
09:38:23   Downloaded itoa v1.0.9
09:38:23   Downloaded ghash v0.5.0
09:38:23   Downloaded humantime v2.1.0
09:38:23   Downloaded anyhow v1.0.72
09:38:23   Downloaded async-trait v0.1.71
09:38:23   Downloaded aes v0.8.3
09:38:23   Downloaded rustls v0.21.5
09:38:23   Downloaded psl-types v2.0.11
09:38:23   Downloaded idna v0.4.0
09:38:23   Downloaded regex-syntax v0.7.4
09:38:23   Downloaded rustix v0.37.23
09:38:23   Downloaded kbs-types v0.4.0
09:38:23   Downloaded idna v0.2.3
09:38:23   Downloaded tokio v1.29.1
09:38:23   Downloaded regex-automata v0.3.3
09:38:23   Downloaded cookie_store v0.16.2
09:38:23   Downloaded linux-raw-sys v0.3.8
09:38:23   Downloaded publicsuffix v2.2.3
09:38:23   Downloaded ring v0.16.20
09:38:24    Compiling libc v0.2.147
09:38:24    Compiling proc-macro2 v1.0.66
09:38:24    Compiling autocfg v1.1.0
09:38:24    Compiling unicode-ident v1.0.11
09:38:24    Compiling cfg-if v1.0.0
09:38:24    Compiling version_check v0.9.4
09:38:24    Compiling memchr v2.5.0
09:38:24    Compiling typenum v1.16.0
09:38:24    Compiling anyhow v1.0.72
09:38:24    Compiling once_cell v1.18.0
09:38:24    Compiling itoa v1.0.9
09:38:24    Compiling syn v1.0.109
09:38:24    Compiling pin-project-lite v0.2.10
09:38:24    Compiling either v1.8.1
09:38:24    Compiling spin v0.5.2
09:38:24    Compiling futures-core v0.3.28
09:38:24    Compiling thiserror v1.0.43
09:38:24    Compiling cc v1.0.79
09:38:24    Compiling subtle v2.5.0
09:38:24    Compiling futures-sink v0.3.28
09:38:24    Compiling futures-task v0.3.28
09:38:24    Compiling io-lifetimes v1.0.11
09:38:24    Compiling futures-channel v0.3.28
09:38:24    Compiling bytes v1.4.0
09:38:24    Compiling serde v1.0.171
09:38:24    Compiling tinyvec_macros v0.1.1
09:38:24    Compiling rustix v0.37.23
09:38:24    Compiling futures-util v0.3.28
09:38:24    Compiling pin-utils v0.1.0
09:38:24    Compiling hashbrown v0.12.3
09:38:24    Compiling futures-io v0.3.28
09:38:24    Compiling untrusted v0.7.1
09:38:24    Compiling protobuf v3.2.0
09:38:24    Compiling linux-raw-sys v0.3.8
09:38:24    Compiling bitflags v1.3.2
09:38:24    Compiling serde_json v1.0.103
09:38:24    Compiling libm v0.2.7
09:38:24    Compiling fastrand v1.9.0
09:38:24    Compiling ryu v1.0.15
09:38:24    Compiling log v0.4.19
09:38:24    Compiling unicode-bidi v0.3.13
09:38:24    Compiling percent-encoding v2.3.0
09:38:24    Compiling base64ct v1.6.0
09:38:24    Compiling byteorder v1.4.3
09:38:24    Compiling cpufeatures v0.2.9
09:38:24    Compiling regex-syntax v0.7.4
09:38:24    Compiling fnv v1.0.7
09:38:24    Compiling rustversion v1.0.14
09:38:24    Compiling const-oid v0.7.1
09:38:24    Compiling httparse v1.8.0
09:38:24    Compiling rustls v0.21.5
09:38:24    Compiling time-core v0.1.1
09:38:24    Compiling zeroize v1.6.0
09:38:24    Compiling ppv-lite86 v0.2.17
09:38:24    Compiling num-bigint-dig v0.8.4
09:38:24    Compiling try-lock v0.2.4
09:38:24    Compiling protobuf v2.28.0
09:38:24    Compiling heck v0.4.1
09:38:24    Compiling opaque-debug v0.3.0
09:38:24    Compiling matches v0.1.10
09:38:24    Compiling smallvec v1.11.0
09:38:24    Compiling unicode-segmentation v1.10.1
09:38:24    Compiling fixedbitset v0.2.0
09:38:24    Compiling tower-service v0.3.2
09:38:24    Compiling httpdate v1.0.2
09:38:24    Compiling psl-types v2.0.11
09:38:24    Compiling async-trait v0.1.71
09:38:24    Compiling base64 v0.13.1
09:38:24    Compiling base64 v0.21.2
09:38:24    Compiling multimap v0.8.3
09:38:24    Compiling mime v0.3.17
09:38:24    Compiling ipnet v2.8.0
09:38:24    Compiling kbc v0.1.0 (/guest-components/attestation-agent/kbc)
09:38:24    Compiling unicode-xid v0.2.4
09:38:24    Compiling os_str_bytes v6.5.1
09:38:24    Compiling termcolor v1.2.0
09:38:24    Compiling strsim v0.10.0
09:38:24    Compiling textwrap v0.16.0
09:38:24    Compiling humantime v2.1.0
09:38:24    Compiling encoding_rs v0.8.32
09:38:24    Compiling tinyvec v1.6.0
09:38:24    Compiling lazy_static v1.4.0
09:38:24    Compiling itertools v0.10.5
09:38:24    Compiling tracing-core v0.1.31
09:38:24    Compiling form_urlencoded v1.2.0
09:38:24    Compiling indexmap v1.9.3
09:38:24    Compiling slab v0.4.8
09:38:24    Compiling tokio v1.29.1
09:38:24    Compiling tempfile v3.6.0
09:38:24    Compiling num-traits v0.2.15
09:38:24    Compiling num-integer v0.1.45
09:38:24    Compiling num-iter v0.1.43
09:38:24    Compiling memoffset v0.6.5
09:38:24    Compiling generic-array v0.14.7
09:38:24    Compiling cookie v0.16.2
09:38:24    Compiling want v0.3.1
09:38:24    Compiling clap_lex v0.2.4
09:38:24    Compiling pem-rfc7468 v0.3.1
09:38:24    Compiling http v0.2.9
09:38:24    Compiling time-macros v0.2.10
09:38:24    Compiling rustls-pemfile v1.0.3
09:38:24    Compiling heck v0.3.3
09:38:24    Compiling tracing v0.1.37
09:38:24    Compiling ring v0.16.20
09:38:24    Compiling aho-corasick v1.0.2
09:38:24    Compiling quote v1.0.31
09:38:24    Compiling unicode-normalization v0.1.22
09:38:24    Compiling http-body v0.4.5
09:38:24    Compiling petgraph v0.5.1
09:38:25    Compiling syn v2.0.26
09:38:25    Compiling const_format_proc_macros v0.2.31
09:38:25    Compiling idna v0.4.0
09:38:25    Compiling idna v0.3.0
09:38:25    Compiling idna v0.2.3
09:38:25    Compiling time v0.3.23
09:38:25    Compiling getrandom v0.2.10
09:38:25    Compiling mio v0.8.8
09:38:25    Compiling socket2 v0.4.9
09:38:25    Compiling signal-hook-registry v1.4.1
09:38:25    Compiling num_cpus v1.16.0
09:38:25    Compiling nix v0.23.2
09:38:25    Compiling iovec v0.1.4
09:38:25    Compiling atty v0.2.14
09:38:25    Compiling clap v3.2.25
09:38:25    Compiling which v4.4.0
09:38:25    Compiling bytes v0.4.12
09:38:25    Compiling rand_core v0.6.4
09:38:25    Compiling regex-automata v0.3.3
09:38:25    Compiling prost-build v0.8.0
09:38:25    Compiling crypto-bigint v0.3.2
09:38:25    Compiling inout v0.1.3
09:38:25    Compiling block-buffer v0.10.4
09:38:25    Compiling crypto-common v0.1.6
09:38:25    Compiling rand_chacha v0.3.1
09:38:25    Compiling publicsuffix v2.2.3
09:38:25    Compiling url v2.4.0
09:38:25    Compiling const_format v0.2.31
09:38:25    Compiling universal-hash v0.5.1
09:38:25    Compiling aead v0.5.2
09:38:25    Compiling cipher v0.4.4
09:38:25    Compiling digest v0.10.7
09:38:25    Compiling polyval v0.6.1
09:38:25    Compiling rand v0.8.5
09:38:25    Compiling aes v0.8.3
09:38:25    Compiling ctr v0.9.2
09:38:25    Compiling sha2 v0.10.7
09:38:25    Compiling ghash v0.5.0
09:38:25    Compiling der v0.5.1
09:38:26    Compiling aes-gcm v0.10.2
09:38:26    Compiling spki v0.5.4
09:38:26    Compiling prost-derive v0.8.0
09:38:26    Compiling strum_macros v0.24.3
09:38:26    Compiling derive-new v0.5.9
09:38:26    Compiling pkcs8 v0.8.0
09:38:26    Compiling protobuf-codegen v2.28.0
09:38:26    Compiling pkcs1 v0.3.3
09:38:26    Compiling rsa v0.6.1
09:38:26    Compiling regex v1.9.1
09:38:27    Compiling vsock v0.2.6
09:38:27    Compiling thiserror-impl v1.0.43
09:38:27    Compiling tokio-macros v2.1.0
09:38:27    Compiling serde_derive v1.0.171
09:38:27    Compiling futures-macro v0.3.28
09:38:27    Compiling env_logger v0.9.3
09:38:27    Compiling strum v0.24.1
09:38:27    Compiling prost v0.8.0
09:38:27    Compiling prost-types v0.8.0
09:38:27    Compiling protobuf-support v3.2.0
09:38:28    Compiling rustls-webpki v0.101.1
09:38:28    Compiling sct v0.7.0
09:38:28    Compiling webpki v0.22.0
09:38:28    Compiling webpki-roots v0.22.6
09:38:28    Compiling ttrpc-compiler v0.6.1
09:38:29    Compiling futures-executor v0.3.28
09:38:29    Compiling futures v0.3.28
09:38:29    Compiling tokio-util v0.7.8
09:38:29    Compiling tokio-rustls v0.24.1
09:38:29    Compiling tokio-vsock v0.3.4
09:38:30    Compiling protobuf-parse v3.2.0
09:38:30    Compiling h2 v0.3.20
09:38:30    Compiling serde_urlencoded v0.7.1
09:38:30    Compiling protobuf-codegen v3.2.0
09:38:31    Compiling kbs-types v0.4.0
09:38:31    Compiling cookie_store v0.16.2
09:38:31    Compiling attester v0.1.0 (/guest-components/attestation-agent/attester)
09:38:31    Compiling resource_uri v0.1.0 (/guest-components/attestation-agent/deps/resource_uri)
09:38:31    Compiling crypto v0.1.0 (/guest-components/attestation-agent/deps/crypto)
09:38:31    Compiling ttrpc-codegen v0.4.2
09:38:31    Compiling ttrpc v0.7.1
09:38:31    Compiling hyper v0.14.27
09:38:32    Compiling attestation-agent v0.1.0 (/guest-components/attestation-agent/app)
09:38:33    Compiling hyper-rustls v0.24.1
09:38:33    Compiling reqwest v0.11.18
09:38:33    Compiling kbs_protocol v0.1.0 (/guest-components/attestation-agent/kbs_protocol)
09:38:34    Compiling attestation_agent v0.1.0 (/guest-components/attestation-agent/lib)
09:38:39     Finished release [optimized] target(s) in 56.58s
09:38:39 DEBIANOS is: true
09:38:39 info: component 'rust-std' for target 'x86_64-unknown-linux-musl' is up to date
09:38:39 make: sudo: Command not found
09:38:39 install -D -m0755 ../target/x86_64-unknown-linux-musl/release/attestation-agent /rootfs/usr/local/bin//attestation-agent
09:38:39 /
```

**Comment by fidencio** [comment]
Rerunning both clh and qemu jobs for TDX

**Comment by jepio** [comment]
The missing sudo looks non-fatal, but the log doesn't really show why it stopped?

**Comment by fidencio** [comment]
> That's networking right? `docker pull k8s.gcr.io/pause:3.6` works from here.

Most likely.  What worried me before is that we had legit failures on the tests, when we got to run them.
Let's see if we can get to that point.

**Comment by wainersm** [comment]
> > That's networking right? `docker pull k8s.gcr.io/pause:3.6` works from here.
> 
> Most likely. What worried me before is that we had legit failures on the tests, when we got to run them. Let's see if we can get to that point.

I'm cooking a fix for that. The issue https://github.com/kata-containers/kata-containers/issues/6461

**Comment by wainersm** [comment]
@jepio I've just merged the main -> CCv0 merge PR (https://github.com/kata-containers/kata-containers/pull/7300). Could you please rebase this PR?

**Comment by fidencio** [comment]
> @jepio I've just merged the main -> CCv0 merge PR (#7300). Could you please rebase this PR?

Can we wait till TDX tests finish before we rebase?

**Comment by wainersm** [comment]
@jepio here is (I expect) the fix to the pause image not pulling on TDX: https://github.com/wainersm/kata-containers/commit/b2c3bca558c38deff2117d5909d9071c23c05590

Could you cherry-pick it into this PR so we test all together?

**Comment by jepio** [comment]
Cherry-picked and rebased.

**Comment by wainersm** [comment]
> Karma: this url is actually currently down https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/nasm-2.15.05.tar.gz

Karma indeed :(

I figured out that Ubuntu 22.04 provides a packaged 2.15 nasm and ovmf builds with it! Unfortunately ubuntu 20.04 (currently builder image of ovmf, provides nasm 2.14 which doesn't build). Thus, an alternative to use the nasm sources tarball is to update the builder to ubuntu 22.04.

The majority of (if not all) builders are still on Ubuntu 20.04. I don't think bumping only ovmf's to 22.04 will be a problem. @fidencio do you see any problem with that?

If not, here is the fix: https://github.com/wainersm/kata-containers/commit/81e9ffa8db28d1d553c9fc93d20836ac3e309b7f (let's cherry-pick on this PR and wait for the next trouble :(

ah, tested locally as `make cc-sev-ovmf-tarball`

**Review by arronwy — APPROVED** [review]
Thanks @jepio , TDX CI both qemu and CLH passed, but CLH results is not reported back: http://10.112.240.228:8080/view/CCv0%20PR%20Triggered/job/kata-containers-CCv0-cloud-hypervisor-TDX-CRI_CONTAINERD_K8S-PR/991/

**Comment by fidencio** [comment]
> The majority of (if not all) builders are still on Ubuntu 20.04. I don't think bumping only ovmf's to 22.04 will be a problem. @fidencio do you see any problem with that?

For things like OVMF I'm not a big fond of just bumping the base container image, Wainer.
I did that recently for TDVF and hit some unexpected issues. :-/

Anyways, nasm seems to be back, TDX CI is passing.  Life is good. :-)

**Pull request merged**
