### PR TITLE
agent: refactor find_process function and add test cases

### PR DESCRIPTION
**Pull request by liubin**
Delete redundant parameter init in find_process function and
add test case for it.

Fixes: #3117

Signed-off-by: bin <bin@hyper.sh>

### CODE REVIEW

**Review by bergwolf — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Thanks @liubin !

lgtm

**Comment by jodh-intel** [comment]
@marcel-apf - Any ideas as to why the vfio CI is failing?:

```
6:53:02 + sudo ctr containers delete vfio-vfio-24888
06:53:02 + sudo rm -rf /tmp/tmp.MN93l7jHhR
06:53:02 + '[' -n 0000:00:03.0 ']'
06:53:02 + sudo driverctl unset-override 0000:00:03.0
06:53:02 make: *** [Makefile:177: vfio] Error 1
```

**Pull request merged**
