### PR TITLE
runtime: Clear the VCMock 1.x API Methods from 2.0

### PR DESCRIPTION
**Pull request by YchauWang**
Clear the 1.x branch api methods in the 2.0. Keep the same methods to
the VC interface, like the VCImpl struct.

Fixes: #751 

Signed-off-by: Ychau Wang <wangyongchao.bj@inspur.com>

### CODE REVIEW

**Comment by liubin** [comment]
Hi @YchauWang ,  it seems test of runtime is failed, you can run it locally by `make test` under runtime's src directory to debug.

**Comment by YchauWang** [comment]
Thanks @liubin I found it, and try to fix these error.

**Review by bergwolf — APPROVED** [review]
lgtm. Thanks!

**Review by liubin — APPROVED** [review]

**Pull request merged**
