### PR TITLE
runtime: fix vmcache for qemu vm

### PR DESCRIPTION
**Pull request by mingfukuang**
to reopen https://github.com/kata-containers/kata-containers/pull/3906%EF%BC%9A   
Fixes: https://github.com/kata-containers/kata-containers/issues/1106

the reason of reopen :  https://github.com/kata-containers/kata-containers/pull/4522  and https://github.com/kata-containers/kata-containers/issues/4545 depends on this fix.

### CODE REVIEW

**Comment by fengwang666** [comment]
@mingfukuang Thanks for the PR. Can you briefly describe how you tested the change?

**Comment by fidencio** [comment]
> @mingfukuang Thanks for the PR. Can you briefly describe how you tested the change?

I'd also be interested to know how we could add a test for it to ensure it won't break again.

**Comment by mingfukuang** [comment]
> @mingfukuang Thanks for the PR. Can you briefly describe how you tested the change?

I manually tested this fix: 
1) open one console run:
# kata-runtime factory init
2)open another console run:
# cat pod-kata.json
{
"metadata": {
"name": "kata-test",
"namespace": "default",
"attempt": 0,
"uid": "hdilhd44dsbidwnduwk28bcsb"
},
"annotations": {
"io.kubernetes.cri.untrusted-workload": "true"
},
"log_directory": "/tmp",
"linux": {
}
}
3)run pod 
# crictl runp pod-kata.json
finally , check the run  pod status , and create new container in this pod.

**Comment by mingfukuang** [comment]
> 
I added the change  based on the latest main branch code (Sun May 28 12:00:39 ).

**Comment by mingfukuang** [comment]
> Sorry, at the time you opened your PR we were having issues with our CI, which leads to required tests failing without having nothing to do with this PR.
> 
> AS this has been already fixed on main, we´d like to ask you to rebase your PR atop of the current `main` branch.
> 
> Thanks for the consideration, and sorry for the trouble.

I added the change based on the latest main branch code (Sun May 28 12:00:39 commit：099b4b0d0e3db31b9054e7240715f0d7f51f9a1c ).

**Comment by fidencio** [comment]
> I added the change based on the latest main branch code (Sun May 28 12:00:39 commit：099b4b0d0e3db31b9054e7240715f0d7f51f9a1c ).

Our CI was fixed after that.  It'd be really helpful if you could rebase atop of the current main, otherwise required tests will not pass.

**Comment by mingfukuang** [comment]
> > I added the change based on the latest main branch code (Sun May 28 12:00:39 commit：099b4b0d0e3db31b9054e7240715f0d7f51f9a1c ).
> 
> Our CI was fixed after that. It'd be really helpful if you could rebase atop of the current main, otherwise required tests will not pass.

I have  already reabsed , but there are still some failure unrelated to this change.   I couldn't  figured out the cause :-(

**Comment by mingfukuang** [comment]
I tried to add ci  for this change. If there's anything else I can do , or any suggestion, pls tell me. thanks.

**Pull request closed without merging**
