### PR TITLE
metrics: Enable Tensorflow metrics for kata CI

### LINKED ISSUE #7395: enable tensorflow metrics for kata ci

### PR DESCRIPTION
**Pull request by GabyCT**
This PR enables the Tensorflow benchmark metrics for kata CI.

Fixes #7395

### CODE REVIEW

**Comment by zvonkok** [comment]
@GabyCT Should we add GPU support?

**Review by dborquez — APPROVED** [review]

**Review by dborquez — APPROVED** [review]
LGTM, thank you @GabyCT

**Review by cmaf — APPROVED** [review]
thanks @GabyCT

**Pull request merged**
