### PR TITLE
[backport] runtime: fix static check errors

### LINKED ISSUE #1698: Missing backports fixes in stable-2.0
I am trying to enable github actions in stable-2.0 to remove the travis CI. However, I am facing with a lot of issues, I already did some backports in the agent that were missing to make the agent build properly https://github.com/kata-containers/kata-containers/pull/1687, however, I was getting a failure in `static-checks.sh` with a lot of errors. I tried to backport 36e438f, however, it seems that other backports are missing like `opentelemetry` PRs and so on. As I am getting errors like 
```
Error: ../virtcontainers/sandbox.go:48:2: cannot find package "." in:
	/home/runner/work/kata-containers/kata-containers/src/github.com/kata-containers/kata-containers/src/runtime/vendor/go.opentelemetry.io/otel/trace
```
Could you please submit to `stable-2.0` the PRs to fix the static checks, opentelemetry, etc to stable-2.0 so I can later enable the github actions @liubin @jodh-intel @cmaf @chavafg @fidencio

### PR DESCRIPTION
**Pull request by cmaf**
It turns out we have managed to break the static checker in many
different places with the absence of static checker in github action.
Let's fix them while enabling static checker in github actions...

Fixes #1698

Signed-off-by: Peng Tao <bergwolf@hyper.sh>
Signed-off-by: Chelsea Mafrica <chelsea.e.mafrica@intel.com>

Partial backport of https://github.com/kata-containers/kata-containers/pull/1539 in order to fix https://github.com/kata-containers/kata-containers/issues/1698, related to https://github.com/kata-containers/kata-containers/pull/1687

### CODE REVIEW

**Comment by cmaf** [comment]
Hey @GabyCT, I added additional patches listed in https://github.com/kata-containers/kata-containers/pull/1687 to test here. 

Regarding porting https://github.com/kata-containers/kata-containers/commit/36e438f883e617c2ae413b85520eb994cfc7b180 from https://github.com/kata-containers/kata-containers/pull/1539, I tried to do the minimum porting necessary to fix the static check errors and ended up not applying a significant amount of changes, including none of the changes for tracing. There are other areas where the changes didn't apply on stable-2.0, so it is only a partial backport. I'm not sure if this will be an issue later. 

The static checks seem to be ok now but the compiler checks are failing because of files generated from the ttrpc-compiler.

```
error: redundant field names in struct initialization
  --> protocols/src/agent_ttrpc.rs:32:13
   |
32 |             client: client,
   |             ^^^^^^^^^^^^^^ help: replace it with: `client`
   |
   = note: `-D clippy::redundant-field-names` implied by `-D warnings`
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_field_names

error: redundant field names in struct initialization
  --> protocols/src/health_ttrpc.rs:32:13
   |
32 |             client: client,
   |             ^^^^^^^^^^^^^^ help: replace it with: `client`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#redundant_field_names
```

**Comment by fidencio** [comment]
@cmaf, I see the static checks are still not working on this one, is this ready to be reviewed?

**Comment by GabyCT** [comment]
@cmaf no I am not sure about those errors

**Comment by cmaf** [comment]
@fidencio not quite yet, I'll re-add the the WIP label until the compiler checks are fixed

**Comment by bergwolf** [comment]
@Tim-Zhang any opinions?

**Comment by cmaf** [comment]
There are a lot of patches backported in this PR to resolve static checks & compiler checks. Could the authors PTAL? @GabyCT @jcvenegas @liubin @bergwolf @Tim-Zhang 

Also maybe @chavafg

**Review by liubin — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, huge thanks for working on that @cmaf!

**Pull request merged**
