### PR TITLE
Backports for 3.1

### PR DESCRIPTION
**Pull request by gkurz**
These are the backports for the upcoming 3.1 release.

### CODE REVIEW

**Comment by fidencio** [comment]
[8350389](https://github.com/kata-containers/kata-containers/pull/6507/commits/8350389987ba163a17dffb14698edc662d4a04d9) can be dropped as it ended up being reverted with a simpler fix: 2c4f8077fd2ea0bfa8f274c3aa18952093037daf and b4a1527aa664ec54ce4fc2941bc5858622ba944f

**Comment by fidencio** [comment]
> [8350389](https://github.com/kata-containers/kata-containers/pull/6507/commits/8350389987ba163a17dffb14698edc662d4a04d9) can be dropped as it ended up being reverted with a simpler fix: [2c4f807](https://github.com/kata-containers/kata-containers/commit/2c4f8077fd2ea0bfa8f274c3aa18952093037daf) and [b4a1527](https://github.com/kata-containers/kata-containers/commit/b4a1527aa664ec54ce4fc2941bc5858622ba944f)

You're bringing both in, you could only bring b4a1527aa664ec54ce4fc2941bc5858622ba944f in

**Comment by fidencio** [comment]
For some reason I was quite confident that @jepio had already backported his changes.

**Comment by gkurz** [comment]
> > [8350389](https://github.com/kata-containers/kata-containers/pull/6507/commits/8350389987ba163a17dffb14698edc662d4a04d9) can be dropped as it ended up being reverted with a simpler fix: [2c4f807](https://github.com/kata-containers/kata-containers/commit/2c4f8077fd2ea0bfa8f274c3aa18952093037daf) and [b4a1527](https://github.com/kata-containers/kata-containers/commit/b4a1527aa664ec54ce4fc2941bc5858622ba944f)
> 
> You're bringing both in, you could only bring [b4a1527](https://github.com/kata-containers/kata-containers/commit/b4a1527aa664ec54ce4fc2941bc5858622ba944f) in

Fixed.

**Review by snir911 — APPROVED** [review]
LGTM thanks

**Review by c3d — APPROVED** [review]
Looks good to me.

**Comment by c3d** [comment]
Note for other reviewers: #6340 has the `needs-backport` label, but no backport because it is captured here with "[kata-deploy: Fix static shim-v2 build on arm64](https://github.com/kata-containers/kata-containers/pull/6507/commits/697707493084b3aa40cface2c01079282d80a652)"

**Pull request merged**
