### PR TITLE
gha: enable SNP attestation

### PR DESCRIPTION
**Pull request by niteeshkd**
This tests the attestation of SNP guest. It depends upon the PR #9806.

### CODE REVIEW

**Comment by niteeshkd** [comment]
@ryansavino @AdithyaKrishnan @fitzthum @stevenhorsman @fidencio , this PR enables the SNP attestation test but it depends upon the [PR9806](https://github.com/kata-containers/kata-containers/pull/9806) . It should be tested only after merging the [PR9806](https://github.com/kata-containers/kata-containers/pull/9806) . It will be great if the other PR is reviewed and merged.

**Comment by niteeshkd** [comment]
@ryansavino , I cherry-picked the commit from [PR9806](https://github.com/kata-containers/kata-containers/pull/9806) just to test this PR.  Once the other PR is merged, i will remove that commit. Can we test this PR?

**Comment by fitzthum** [comment]
@niteeshkd this PR will expect a cert to be provisioned on the host, right? Any special instructions for where that should be located or how it should be formatted?

**Comment by fitzthum** [comment]
Last run passed but 

```
 [run_kubernetes_tests.sh:114] INFO: Executing k8s-confidential-attestation.bats
1..2
ok 1 Get CDH resource # skip Test skipped as KBS not setup
ok 2 Cannot get CDH resource when deny-all policy is set # skip Test skipped as KBS not setup
```

I think maybe this is because the test is using the upstream yaml files rather than the changes in this PR. Maybe we should move the yaml file changes to #9806 and then test this once that is in? wdyt @wainersm @stevenhorsman

**Comment by niteeshkd** [comment]
> @niteeshkd this PR will expect a cert to be provisioned on the host, right? Any special instructions for where that should be located or how it should be formatted?

@fitzthum @ryansavino , one could use [snphost](https://github.com/virtee/snphost/blob/main/docs/snphost.1.adoc) on the SNP host as follows to create the cert-chain file /opt/snp/cert_chain.cert .
```
$ git clone https://github.com/virtee/snphost.git && cd snphost/
$ cargo build
$ mkdir /tmp/certs
$ ./target/debug/snphost fetch ca der /tmp/certs << optional 
$ ./target/debug/snphost fetch vcek der /tmp/certs
$ ./target/debug/snphost import /tmp/certs /opt/snp/cert_chain.cert
```

**Comment by stevenhorsman** [comment]
> Last run passed but
> 
> ```
>  [run_kubernetes_tests.sh:114] INFO: Executing k8s-confidential-attestation.bats
> 1..2
> ok 1 Get CDH resource # skip Test skipped as KBS not setup
> ok 2 Cannot get CDH resource when deny-all policy is set # skip Test skipped as KBS not setup
> ```
> 
> I think maybe this is because the test is using the upstream yaml files rather than the changes in this PR. Maybe we should move the yaml file changes to #9806 and then test this once that is in? wdyt @wainersm @stevenhorsman

Yeah, we have an issue with our CI target that for workflow change, the upstream yaml will be used. Normally our approach is to deliver a separate PR with the workflow change and then follow up with the tests, which is similar to Tobin's suggestion to add it to #9806. I guess my concern with that approach is that is that I think once we merge that we will start running the attestation tests on SNP, which I assume will fail until this is also merged.

One compromise approach I can see if that we could add a new commit with the workflow changes in #9806, but also add explicit skips for snp in the attestation bats tests instead of relying on the KBS check https://github.com/kata-containers/kata-containers/blob/ff498c55d18dfb4cde86b4fa102e925993a37e19/tests/integration/kubernetes/k8s-confidential-attestation.bats#L20

Then in this PR we could remove that check and hopefully keep SNP stable and green throughout?

**Comment by wainersm** [comment]
> > Last run passed but
> > ```
> >  [run_kubernetes_tests.sh:114] INFO: Executing k8s-confidential-attestation.bats
> > 1..2
> > ok 1 Get CDH resource # skip Test skipped as KBS not setup
> > ok 2 Cannot get CDH resource when deny-all policy is set # skip Test skipped as KBS not setup
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think maybe this is because the test is using the upstream yaml files rather than the changes in this PR. Maybe we should move the yaml file changes to #9806 and then test this once that is in? wdyt @wainersm @stevenhorsman
> 
> Yeah, we have an issue with our CI target that for workflow change, the upstream yaml will be used. Normally our approach is to deliver a separate PR with the workflow change and then follow up with the tests, which is similar to Tobin's suggestion to add it to #9806. I guess my concern with that approach is that is that I think once we merge that we will start running the attestation tests on SNP, which I assume will fail until this is also merged.
> 
> One compromise approach I can see if that we could add a new commit with the workflow changes in #9806, but also add explicit skips for snp in the attestation bats tests instead of relying on the KBS check
>

This ^

**Comment by wainersm** [comment]
> > @niteeshkd this PR will expect a cert to be provisioned on the host, right? Any special instructions for where that should be located or how it should be formatted?
> 
> @fitzthum @ryansavino , one could use [snphost](https://github.com/virtee/snphost/blob/main/docs/snphost.1.adoc) on the SNP host as follows to create the cert-chain file /opt/snp/cert_chain.cert .
> 
> ```
> $ git clone https://github.com/virtee/snphost.git && cd snphost/
> $ cargo build
> $ mkdir /tmp/certs
> $ ./target/debug/snphost fetch ca der /tmp/certs << optional 
> $ ./target/debug/snphost fetch vcek der /tmp/certs
> $ ./target/debug/snphost import /tmp/certs /opt/snp/cert_chain.cert
> ```

@ryansavino @AdithyaKrishnan  what's your plan for this setup?

You can make it manually but it's error-prone. You call :)

**Comment by niteeshkd** [comment]
Please note that this PR contains all the three commits cherry-picked from #9806 and then one commit to enable the attestation by removing the code which was skipping the attestation in #9806. I will be adding one more commit for updating the how-to document regarding SNP attestation soon.

**Comment by wainersm** [comment]
Hi @niteeshkd ! https://github.com/kata-containers/kata-containers/pull/9806 was merged, so you should rebase this on top of main.

**Comment by niteeshkd** [comment]
> Hi @niteeshkd ! #9806 was merged, so you should rebase this on top of main.

Great! Thank you all so much! I just rebased this PR.

**Comment by GabyCT** [comment]
I re-run the TDX CI job

**Review by ryansavino — APPROVED** [review]
LGTM

**Review by fitzthum — APPROVED** [review]
LGTM, SNP tests passing

**Comment by wainersm** [comment]
CI liked this PR...
```
<snip>
[run_kubernetes_tests.sh:115] INFO: Executing k8s-confidential-attestation.bats
1..2
ok 1 Get CDH resource
<snip>
ok 2 Cannot get CDH resource when deny-all policy is set
<snip>
```

... so do I!

**Review by wainersm — APPROVED** [review]
Thanks @niteeshkd !

**Pull request merged**
