### PR TITLE
docs: Fix several build failures  when I tried the procedures in "Kata Containers with AMD SEV-SNP VMs"

### PR DESCRIPTION
**Pull request by kimullaa**
Fix several build failures  when I tried the procedures in [Kata Containers with AMD SEV-SNP VMs](https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-run-kata-containers-with-SNP-VMs.md).

Fixes: #10378

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Comment by AdithyaKrishnan** [comment]
Roping in @ryansavino as my review doesn't have merge privilege

**Review by ryansavino — APPROVED** [review]
Yep these instructions were out of date. Thanks @kimullaa.

**Review by AdithyaKrishnan — APPROVED** [review]
LGTM

**Comment by beraldoleal** [comment]
Sorry, added the label and then realized is just a md change.

**Comment by kimullaa** [comment]
I rebased to fix a CI job failure.

**Comment by ryansavino** [comment]
Sorry, lost track of this one. Merging.

**Pull request merged**
