### PR TITLE
kernel: add VFIO kernel dependencies for ppc64le

### PR DESCRIPTION
**Pull request by Amulyam24**
Recently added VFIO kernel configs require addtional
dependencies on pcc64le.

Fixes: #2991

Signed-off-by: Amulyam24 <amulmek1@in.ibm.com>

### CODE REVIEW

**Review by Jakob-Naucke — APPROVED** [review]
Thank you @Amulyam24 -- can you add porting labels?

**Comment by Amulyam24** [comment]
> Thank you @Amulyam24 -- can you add porting labels?

@Jakob-Naucke , I don't have the permissions to add labels. No backport required for now.

**Comment by fidencio** [comment]
> > Thank you @Amulyam24 -- can you add porting labels?
> 
> @Jakob-Naucke , I don't have the permissions to add labels. No backport required for now.

Hmm. Are you sure?  If we want this to be part of stable-2.3 we should get this one backported there (and I sincerely think we should, as 2.3.0 will be released next week -- considering everything goes well).

**Review by jodh-intel — APPROVED** [review]
Thanks @Amulyam24.

lgtm

**Comment by Amulyam24** [comment]
> > > Thank you @Amulyam24 -- can you add porting labels?
> > 
> > 
> > @Jakob-Naucke , I don't have the permissions to add labels. No backport required for now.
> 
> Hmm. Are you sure? If we want this to be part of stable-2.3 we should get this one backported there (and I sincerely think we should, as 2.3.0 will be released next week -- considering everything goes well).

For stable-2.3, yes, can you please help add a needs-backport label?

**Comment by Jakob-Naucke** [comment]
Ugh, let me TAL at these failures, they're definitely unrelated...

**Comment by Jakob-Naucke** [comment]
See https://github.com/kata-containers/tests/issues/4168 for Debian (which seems Debian-specific)

**Comment by Jakob-Naucke** [comment]
ARM was definitely a network downtime, FC I'm not 100% sure -- might not be reproducible:
```
00:19:41.971 [reset] Unmounting mounted directories in "/var/lib/kubelet"
00:19:42.024 W1109 10:54:38.029299    1448 unmount_linux.go:48] [reset] Failed to unmount mounted directory in /var/lib/kubelet/: /var/lib/kubelet/plugins/kubernetes.io~local-volume/volumeDevices/block-loop-pv/ae41b495-d4a5-407c-a85e-7e36a76101f6
00:19:42.024 Build timed out (after 15 minutes). Marking the build as aborted.
00:34:42.024 Build was aborted
```

**Pull request merged**
