### PR TITLE
qemu: don't emit scsi parameter

### PR DESCRIPTION
**Pull request by Freax13**
This parameter has been deprecated for a long time and QEMU 9.1.0 finally removes it.

Fixes: #10112

### CODE REVIEW

**Comment by Apokleos** [comment]
Thx @Freax13 
I think it'll be better to split the PR into two commits, one for runtime-rs and the other one for kata-runtime/qemu.

**Comment by fidencio** [comment]
@Freax13, very nice seeing you around! :-)

So, while your approach is correct, the version of QEMU that Kata Containers ships is still v8.2.4, see: https://github.com/kata-containers/kata-containers/blob/43dca8deb4891678f8a62c112749ac0938b373c6/versions.yaml#L88-L100

My sincere recommendation is that we don't take this patch till we bump the QEMU version being used.
@gkurz, what's your take on bumping QEMU to its latest release?

**Comment by Freax13** [comment]
> @Freax13, very nice seeing you around! :-)

:)

> So, while your approach is correct, the version of QEMU that Kata Containers ships is still v8.2.4, see: https://github.com/kata-containers/kata-containers/blob/43dca8deb4891678f8a62c112749ac0938b373c6/versions.yaml#L88-L100

Ah, I forgot to mention that before the parameter was deprecated, the default for `SCSI` was switched to off, so the code govmm is already outdated and serves no purpose in newer QEMU versions, including v8.2.4. We don't need to upgrade QEMU for this patch to be correct.

**Review by amshinde — APPROVED** [review]

**Comment by fidencio** [comment]
> Ah, I forgot to mention that before the parameter was deprecated, the default for `SCSI` was switched to off, so the code govmm is already outdated and serves no purpose in newer QEMU versions, including v8.2.4. We don't need to upgrade QEMU for this patch to be correct.

That's good info.

lgtm, thanks @Freax13, and welcome to the Kata Containers community! <3

**Review by fidencio — APPROVED** [review]
lgtm, thanks @Freax13!

**Pull request merged**
