### PR TITLE
Kata 2.0-dev port of #2867 (NoReboot Knob)

### PR DESCRIPTION
**Pull request by merwick**
This is a port of the NoReboot changes [1] merged into 1.12.x

One change needed in qemu_test.go was dropping the last parameter in the call to createSandbox()
I also changed the govmm commit to use go modules. I'm not sure if I should have deleted the old govmm lines (167-168) in go.sum

[1] https://github.com/merwick/runtime/commit/77e3024cd0ab2e865953667ec49ebd742e2fed1b

### CODE REVIEW

**Comment by merwick** [comment]
I think the jenkins-ci-ARM-ubuntu-18-04 failure below is due to #336 

```
E0730 17:13:16.174525    9453 remote_runtime.go:105] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed to setup network for sandbox "ee6eddf219c9405788c2704075abf1430aef783bf55cd8d7d47d30230be0bc56": open /run/flannel/subnet.env: no such file or directory
    TestImageLoad: image_load_test.go:80: 
        	Error Trace:	image_load_test.go:80
        	Error:      	Received unexpected error:
        	            	rpc error: code = Unknown desc = failed to setup network for sandbox "ee6eddf219c9405788c2704075abf1430aef783bf55cd8d7d47d30230be0bc56": open /run/flannel/subnet.env: no such file or directory
        	Test:       	TestImageLoad
--- FAIL: TestImageLoad (2.12s)
```

**Comment by fidencio** [comment]
Yep, the ARM CI issues doesn't seem related to this PR.

@devimc, may I just merge it?

**Comment by devimc** [comment]
@fidencio go for it

**Pull request merged**
