### PR TITLE
CC | agent: Update image-rs to bring stream pulling support

### PR DESCRIPTION
**Pull request by fidencio**
Image layers stream pulling support has been merged into image-rs, and
we're now pulling an image-rs version that contains the merged code.

See: https://github.com/confidential-containers/image-rs/pull/96

Fixes: #5968

Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

### CODE REVIEW

**Review by arronwy — APPROVED** [review]

**Comment by fidencio** [comment]
@stevenhorsman, is the s390x CI supposed to be working?
SEV has been consistently failing, cc @ryansavino

**Comment by stevenhorsman** [comment]
> @stevenhorsman, is the s390x CI supposed to be working?

The `s390x-ccv0-ubuntu-20-04` has been failing for a while due to some dragonball incompatibilities with s390x, but the CC specific s390x tests `s390x-cc_cri_containerd_k8s` should still pass all tests (that I know, so worth investigating - or flagging me, and/or Choi if it fails).

**Comment by ryansavino** [comment]
I'm working on getting more storage added to the milan node. I've cleaned up the drive and will rerun the test.

**Comment by ryansavino** [comment]
@stevenhorsman, I think this one needs #5939 merged in.

**Pull request merged**
