### PR TITLE
branch: change 2.0-dev to main

### PR DESCRIPTION
**Pull request by bergwolf**
Change all mentioning of 2.0-dev to main so that we can rename the
default branch to main.

Fixes: #1310

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @bergwolf!

**Comment by fidencio** [comment]
@jodh-intel, @pmores, may I bother you for an ack on this one?

**Review by liubin — APPROVED** [review]

**Review by Tim-Zhang — APPROVED** [review]

**Review by sameo — APPROVED** [review]

**Pull request merged**
