### PR TITLE
runtime: sync docstrings with function names

### LINKED ISSUE #4006: Incorrect comments in qemu.go
```diff
diff --git a/src/runtime/virtcontainers/qemu.go b/src/runtime/virtcontainers/qemu.go
index 242b3645d..99ff76e8f 100644
--- a/src/runtime/virtcontainers/qemu.go
+++ b/src/runtime/virtcontainers/qemu.go
@@ -796,7 +796,7 @@ func (q *qemu) setupVirtioMem(ctx context.Context) error {
        return err
 }
 
-// startSandbox will start the Sandbox's VM.
+// StartVM will start the Sandbox's VM.
 func (q *qemu) StartVM(ctx context.Context, timeout int) error {
        span, ctx := katatrace.Trace(ctx, q.Logger(), "StartVM", qemuTracingTags, map[string]string{"sandbox_id": q.id})
        defer span.End()
@@ -968,7 +968,7 @@ func (q *qemu) waitVM(ctx context.Context, timeout int) error {
        return nil
 }
 
-// stopSandbox will stop the Sandbox's VM.
+// StopVM will stop the Sandbox's VM.
 func (q *qemu) StopVM(ctx context.Context, waitOnly bool) error {
        span, _ := katatrace.Trace(ctx, q.Logger(), "StopVM", qemuTracingTags, map[string]string{"sandbox_id": q.id})
        defer span.End()
@@ -1996,7 +1996,7 @@ func (q *qemu) ResumeVM(ctx context.Context) error {
        return q.togglePauseSandbox(ctx, false)
 }
 
-// addDevice will add extra devices to Qemu command line.
+// AddDevice will add extra devices to Qemu command line.
 func (q *qemu) AddDevice(ctx context.Context, devInfo interface{}, devType DeviceType) error {
        var err error
        span, _ := katatrace.Trace(ctx, q.Logger(), "AddDevice", qemuTracingTags)
@@ -2055,7 +2055,7 @@ func (q *qemu) AddDevice(ctx context.Context, devInfo interface{}, devType Devic
        return err
 }
 
-// getSandboxConsole builds the path of the console where we can read
+// GetVMConsole builds the path of the console where we can read
 // logs coming from the sandbox.
 func (q *qemu) GetVMConsole(ctx context.Context, id string) (string, string, error) {
        span, _ := katatrace.Trace(ctx, q.Logger(), "GetVMConsole", qemuTracingTags, map[string]string{"sandbox_id": q.id})
@@ -2129,7 +2129,7 @@ func (q *qemu) Disconnect(ctx context.Context) {
        q.qmpShutdown()
 }
 
-// resizeMemory get a request to update the VM memory to reqMemMB
+// ResizeMemory get a request to update the VM memory to reqMemMB
 // Memory update is managed with two approaches
 // Add memory to VM:
 // When memory is required to be added we hotplug memory

```

### PR DESCRIPTION
**Pull request by r4f4**
The functions were renamed but their docstrings were not.

Fixes #4006

Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>

### CODE REVIEW

**Review by cmaf — APPROVED** [review]

**Review by gkurz — COMMENTED** [review]
The other hypervisors (acrn, fc, clh) also have the old docstrings. It would make sense to fix them as well in this PR.

**Comment by r4f4** [comment]
> The other hypervisors (acrn, fc, clh) also have the old docstrings. It would make sense to fix them as well in this PR.

Done!

**Review by gkurz — APPROVED** [review]
LGTM. Thanks @r4f4 !

**Pull request merged**
