### PR TITLE
osbuilder: Remove centos rootfs-builder

### PR DESCRIPTION
**Pull request by fidencio**
As the centos rootfs is not tested in our CI, we can't guarantee it
actually works as expected.

Whenever we have someone willing to maintain the rootfs we can have it
added back, and also add a CI job to test it altogether, avoiding then
any possible regression.

Fixes: #2140

Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

### CODE REVIEW

**Comment by Jakob-Naucke** [comment]
@wllenyj I'd like to loop you in here. In #2874, you said the MVP package would be required for TDX, and you said it was only available on CentOS. Is that still the case?

If we want to have one Red Hat (adjacent) distro, I'd vouch for CentOS Stream 9 once it lands, due to great cross-platform compatibility (read: s390x) and a calmer release cadence opposed to Fedora. I would test this on the upcoming RHEL s390x CI job. We can merge that as a "new feature" though once all the things are there.

This should be changed though: https://github.com/kata-containers/kata-containers/blob/ee66155a72a9f2adcf927489cb394336b13b01f3/versions.yaml#L122-L123
@Amulyam24 is Ubuntu okay?

**Comment by wainersm** [comment]
I will be working with @kata-containers/redhat to ensure it won't compromise any use case of Red Hat.

**Comment by Amulyam24** [comment]
> This should be changed though:
> 
> https://github.com/kata-containers/kata-containers/blob/ee66155a72a9f2adcf927489cb394336b13b01f3/versions.yaml#L122-L123
> 
> 
> @Amulyam24 is Ubuntu okay?

@Jakob-Naucke, yes. Only ubuntu rootfs is being used on ppc64le as of now. Thanks @fidencio !

**Review by jodh-intel — APPROVED** [review]
Thanks @fidencio.

lgtm

**Comment by wllenyj** [comment]
@Jakob-Naucke Merry Christmas. 
Now it is compatible with ubuntu. I will close #2874.

**Comment by wainersm** [comment]
@fidencio

blurb 1: I've already started a discussion internally with @kata-containers/redhat about this and #3327.

**Review by wainersm — APPROVED** [review]
@fidencio I got the Ack from the @kata-containers/redhat to remove the CentOS rootfs-builder. This PR looks good to me.

**Comment by jodh-intel** [comment]
@fidencio - could you rebase to resolve the conflict?

**Comment by fidencio** [comment]
This got superseded by https://github.com/kata-containers/kata-containers/pull/3420

**Pull request closed without merging**
