### PR TITLE
stable-3.0 | kata-deploy: Fix building the kata static arm package occurred an error

### PR DESCRIPTION
**Pull request by singhwang**
When building the kata static arm package, the two stages of firecracker and virtiofsd report errors.

Fixes: #5952

### CODE REVIEW

**Comment by singhwang** [comment]
The modification for firecracker is specially used to solve the error reporting part of firecracker in the issue. This part of the modification also considers the x86 environment.

**Comment by singhwang** [comment]
For the modification of Dockerfile and build-static-virtiofsd.sh, it mainly solves the problem that the build environment is not ready under arm. In the x86 environment, the logic of the script is to directly download the official compiled package, but in the arm environment, it needs to be compiled in the rust environment, refer to the document https://gitlab.com/virtio-fs/virtiofsd , the ubuntu compilation environment needs to install libcap-ng-dev and libseccomp-dev two dependent packages. At the same time, before using cargo in build-static-virtiofsd.sh, the logic of rust installation is added, otherwise an error will be reported here and cannot be found. to the cargo command.

**Comment by liyimeng** [comment]
Similar fix is proposed in https://github.com/kata-containers/kata-containers/pull/5534, but seem not easy to get through :(

**Comment by singhwang** [comment]
> #5534

It seems that we encountered a similar issue. For the modification of build-static-firecracker.sh, our purpose is the same, but I also made corresponding modifications to Dockerfile and build-static-virtiofsd.sh for virtiofsd.

**Comment by singhwang** [comment]
@liyimeng It seems that we encountered a similar issue. For the modification of build-static-firecracker.sh, our purpose is the same, but I also made corresponding modifications to Dockerfile and build-static-virtiofsd.sh for virtiofsd. Unfortunately, reviewers has not given me the opportunity to test.

**Comment by singhwang** [comment]
Can the reviewers trigger the 10 expected checks? Their status has been Expected — Waiting for status to be reported.

**Comment by singhwang** [comment]
The second problem 2 has been officially fixed in version 3.01

**Pull request closed without merging**
