### PR TITLE
runtime-rs: Fix constructing the RTC struct

### PR DESCRIPTION
**Pull request by emanuellima1**
RTC was being built in a wrong fashion on PR 9519

### CODE REVIEW

**Review by lifupan — APPROVED** [review]
LGTM.

**Review by beraldoleal — COMMENTED** [review]
Hi @emanuellima1 thanks for this. 

Please add a brief description to the commit description, explaining what was wrong and why this is needed.

Also a minor (maybe nit) suggestion is to use commit hash references instead of a PR reference.

**Review by pmores — APPROVED** [review]
LGTM, thanks @emanuellima1 !

**Review by beraldoleal — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
