### PR TITLE
versions: Update Firecracker version to v1.1.0

### PR DESCRIPTION
**Pull request by gntouts**
This patch upgrades Firecracker version from v0.23.4 to v1.1.0

* Generate swagger models for v1.1.0 (from firecracker.yaml)
* Replace ht_enabled param to smt (API change)
* Remove NUMA-related jailer param --node 0

Fixes: #4673
Depends-on: kata-containers/tests#4968

Signed-off-by: George Ntoutsos <gntouts@nubificus.co.uk>
Signed-off-by: Anastassios Nanos <ananos@nubificus.co.uk>

### CODE REVIEW

**Comment by fidencio** [comment]
I'd like to have this one bumped as part of the stable branch as well.

**Review by GabyCT — APPROVED** [review]

**Review by amshinde — APPROVED** [review]

**Pull request merged**
