### PR TITLE
kata-deploy: fix version bump from -rc to stable

### PR DESCRIPTION
**Pull request by bergwolf**
In such a case, we should bump from the "latest" tag rather than from
current_version.

backporting #3987

### CODE REVIEW

**Comment by bergwolf** [comment]
tagging `wip` to block on https://github.com/kata-containers/kata-containers/pull/3987

**Review by fidencio — APPROVED** [review]
lgtm, thanks @bergwolf!

**Comment by bergwolf** [comment]
As discussed in slack, s390x CI is disabled and can be ignored for now.

**Review by teawater — APPROVED** [review]

**Pull request merged**
