### PR TITLE
packaging: Add the kata manager script

### PR DESCRIPTION
**Pull request by jodh-intel**
Add `kata-manager.sh` to the release packages.

Fixes: #9066.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by fidencio** [comment]
@jodh-intel, what's included as part of the release is actually in https://github.com/kata-containers/kata-containers/blob/main/.github/workflows/build-kata-static-tarball-amd64.yaml#L29

Now, the question whether we want to ship as part of the tarball, or as its own file uploaded to github as part of the release.  Let's sync about this Tomorrow, @jodh-intel.

**Comment by jodh-intel** [comment]
Branch updated to resolve merge conflict.

**Comment by jodh-intel** [comment]
@fidencio - Thanks, I've also updated the YAML config file now :smile:

___

For a bit more detail on why this PR is useful...

Once #9059 lands, you'll be able to switch hypervisor config by running a "one line" command using `kata-manager`. As shown in the [`kata-manager` docs](https://github.com/kata-containers/kata-containers/blob/main/utils/README.md), you need to call the script using `bash` and `curl` to bootstrap your system. But once you've used it to install a working Kata system by running that single command, to switch the hypervisor config, you could either run something like this, to switch your [configured hypervisor](https://github.com/kata-containers/kata-containers/blob/main/docs/hypervisors.md) to [Cloud Hypervisor](https://www.cloudhypervisor.org) :

```bash
$ bash -c "$(curl -fsSL https://raw.githubusercontent.com/kata-containers/kata-containers/main/utils/kata-manager.sh) -S clh
```

... or, when this PR lands and gets into a release, you could do the same thing by running simply:

```
$ kata-manager -S clh
```

Which is a lot easier to remember and type :smile:

**Comment by fidencio** [comment]
So, I tried to run `make kata-manager-tarball` and this is the result that I got:
```sh
make kata-manager-tarball
make: *** No rule to make target 'kata-manager-tarball'.  Stop.
```

After adding the patch below it works as expected:
```patch
diff --git a/tools/packaging/kata-deploy/local-build/Makefile b/tools/packaging/kata-deploy/local-build/Makefile
index d85382fd1..a6986191f 100644
--- a/tools/packaging/kata-deploy/local-build/Makefile
+++ b/tools/packaging/kata-deploy/local-build/Makefile
@@ -111,6 +111,9 @@ pause-image-tarball:
 kata-ctl-tarball:
        ${MAKE} $@-build
 
+kata-manager-tarball:
+       ${MAKE} $@-build
+
 kernel-dragonball-experimental-tarball:
        ${MAKE} $@-build
```

**Comment by jodh-intel** [comment]
Thanks, @fidencio! Branch updated.

**Review by cmaf — APPROVED** [review]
thanks @jodh-intel

**Pull request merged**
