### PR TITLE
# Kata Containers 1.10.2

### PR DESCRIPTION
**Pull request by bergwolf**
537ecbe path-absolutize: version update

### CODE REVIEW

**Comment by amshinde** [comment]
@bergwolf Shortlog looks different, why does it contain the releases itself?

**Comment by bergwolf** [comment]
@amshinde Not sure. It's generated by the release script.

**Comment by bergwolf** [comment]
@amshinde Anyway, I updated the commit message by hand.

**Comment by jodh-intel** [comment]
Ouch - that's awkward - Travis failed with a build error:

```
 Compiling path-absolutize v1.1.3 (git://github.com/magiclen/path-absolutize.git?tag=v1.1.3#88936385)
error[E0133]: use of mutable static is unsafe and requires unsafe function or block
  --> /home/travis/.cargo/git/checkouts/path-absolutize-0aead0458025157b/8893638/src/unix.rs:15:35
   |
15 |             let path = Path::join(&CWD, self);
   |                                   ^^^^ use of mutable static
   |
   = note: mutable statics can be mutated by multiple threads: aliasing violations or data races will cause undefined behavior
error: aborting due to previous error
For more information about this error, try `rustc --explain E0133`.
error: could not compile `path-absolutize`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

/cc @lifupan

**Comment by lifupan** [comment]
> Ouch - that's awkward - Travis failed with a build error:
> 
> ```
>  Compiling path-absolutize v1.1.3 (git://github.com/magiclen/path-absolutize.git?tag=v1.1.3#88936385)
> error[E0133]: use of mutable static is unsafe and requires unsafe function or block
>   --> /home/travis/.cargo/git/checkouts/path-absolutize-0aead0458025157b/8893638/src/unix.rs:15:35
>    |
> 15 |             let path = Path::join(&CWD, self);
>    |                                   ^^^^ use of mutable static
>    |
>    = note: mutable statics can be mutated by multiple threads: aliasing violations or data races will cause undefined behavior
> error: aborting due to previous error
> For more information about this error, try `rustc --explain E0133`.
> error: could not compile `path-absolutize`.
> warning: build failed, waiting for other jobs to finish...
> error: build failed
> ```
> 
> /cc @lifupan

@bergwolf @jodh-intel 
We need to backport this fix commit https://github.com/kata-containers/kata-containers/commit/f0eaeac3be4683bf17d24021bf65f8460b6053b6 to 1.10.2 to fix this building  error.

**Pull request merged**
