### PR TITLE
docs: added a glossary to support SEO tactics

### PR DESCRIPTION
**Pull request by pmores**
This commit is a result of Assisted PR Process for PR #1515.  It
deviates from it in that the original commits were not retained as the
original commit structure was unnecessarily complex - the same commit
was added to two parallel branches which were then merged, producing the
same result in the end as any of the original two non-merge commits.
Also, a squash was requested by an original PR review.

The only other change to the original PR was to change capitalisation of
the word "Kubelet" in Glossary.md to placate spell checker.

The original commit message follows:

The terms added are: Kata Containers, container software, container
runtime interface, virtual machine software, container virtualization,
container security solutions, serverless containers, pod containers,
virtual machine monitor, private cloud, infrastructure architecture,
public cloud, and auto scaling.

Fixes: #1509

Signed-Off-By: Helena Spease <helena@openstack.org>
Signed-Off-By: Pavel Mores <pmores@redhat.com>

### CODE REVIEW

**Comment by pmores** [comment]
@hspease99 Would you care to review?  Thanks!

**Comment by fidencio** [comment]
We're missing the SoB tag.
```
Found 1 commit between commit HEAD and branch main
ERROR: Commit 9818b73310e6febab7adfbe936b93ddcd1b03b7f: no Signed-off-by specified
ERROR: checkcommits failed. See the document below for help on formatting
commits for the project.

https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format

make: *** [Makefile:34: static-checks] Error 1
Error: Process completed with exit code 2.
```

**Comment by pmores** [comment]
@fidencio ?? There are two of them... :-)

**Comment by fidencio** [comment]
> @fidencio ?? There are two of them there... :-)

Feels like those were added manually and that's the reason the static-check is complaining, as the spelling is not correct.
The correct spelling should be `Signed-off-by: ` instead of `Signed-Off-By: `.

**Comment by pmores** [comment]
@fidencio Oh I see, thanks (I do wish though that this PR process was less mean-spirited and pedantic...)

**Comment by fidencio** [comment]
> @fidencio Oh I see, thanks (I do wish though that this PR process was less mean-spirited and pedantic...)

Requires a `-s` in your commit is something that's common and seen in pretty much every open source project.
I get your point, though.

**Comment by fidencio** [comment]
There's a weird bug on GitHub where the static checks are not being triggered, unless one closes and reopens the PR (which I just did for this PR).

**Comment by pmores** [comment]
> There's a weird bug on GitHub where the static checks are not being triggered, unless one closes and reopens the PR (which I just did for this PR).

Thanks for the explanation - I was indeed slightly wondering why the close/open move... :-)

**Review by fidencio — APPROVED** [review]
thanks, @pmores!

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
