### PR TITLE
action: Add issue to project and move to "In progress" on linked PR

### PR DESCRIPTION
**Pull request by jodh-intel**
Add GitHub actions to:

- Add newly-created issues to the issue backlog project.
- Move issues with a linked PR into the "In progress" column
  of the issue backlog project.

Related: https://github.com/kata-containers/kata-containers/issues/512

Fixes: #637.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Review by amshinde — APPROVED** [review]

**Comment by amshinde** [comment]
ping @kata-containers/kata-containers

**Comment by jodh-intel** [comment]
Ping @kata-containers/kata-containers - we need this to land for issue backlog management! /cc @ariel-adam.

**Comment by jodh-intel** [comment]
@fidencio, @liubin, @bergwolf - please could one of you ack so we can land this today?

**Review by bergwolf — APPROVED** [review]

**Comment by jodh-intel** [comment]
Closing as needs to be based off `2.0-dev`.

**Pull request closed without merging**
