### PR TITLE
[forward-port] packaging: s390x kernel config fragments

### PR DESCRIPTION
**Pull request by Jakob-Naucke**
This is a forward-port of PR [#1046](https://github.com/kata-containers/packaging/pull/1046) in kata-containers/packaging. It adds support for s390x kernel configuration fragments. They are a prerequirement for a kernel fragment for VFIO-AP (see issue #491)

/cc @alicefr

Fixes: #510

### CODE REVIEW

**Comment by Jakob-Naucke** [comment]
Two checks failed, but both of them seem to fail for all builds currently (see issue #505 for ARM). Would you like to wait for one or both of them to receive fixes or do you think this could be merged? @devimc @jodh-intel

**Comment by devimc** [comment]
@Jakob-Naucke we need `Commit Message Check ` , but it's stuck, @GabyCT @amshinde   any idea?

**Comment by Jakob-Naucke** [comment]
@devimc Shall I try an empty force-push?

**Comment by devimc** [comment]
@Jakob-Naucke yes please, rebase and push.

**Comment by Jakob-Naucke** [comment]
Wrapped commit messages – commit message check failed due to long lines

**Pull request merged**
