### PR TITLE
CC | packaging: Allow passing a container builder to the scripts

### PR DESCRIPTION
**Pull request by fidencio**
This, combined with the effort of caching builder images *and* only performing the build itself inside the builder images, is the very first step for reproducible builds for the project.

Reproducible builds are quite important when we talk about Confidential Containers, as users may want to verify the content used / provided by the CSPs, and this is the first step towards that direction.

Fixes: #5517

Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
LGTM. Is the idea that we could export the env vars that point to the various builder container images in the release workflow (or similar)?

**Comment by fidencio** [comment]
> LGTM. Is the idea that we could export the env vars that point to the various builder container images in the release workflow (or similar)?

Right now we're not there yet, but I hope one day we can do a release and say:
* Components were built using:
  * Image A
  * image B
  * ...

And then when someone goes back to debug a problem, or simply to rebuild the artefacts by their own (let s say, to audit the components being used), then they can use the images mentioned by the release notes and end up with exactly the same binaries.

Makes sense?

**Comment by stevenhorsman** [comment]
> > LGTM. Is the idea that we could export the env vars that point to the various builder container images in the release workflow (or similar)?
> 
> Right now we're not there yet, but I hope one day we can do a release and say:
> 
> * Components were built using:
>   
>   * Image A
>   * image B
>   * ...
> 
> And then when someone goes back to debug a problem, or simply to rebuild the artefacts by their own (let s say, to audit the components being used), then they can use the images mentioned by the release notes and end up with exactly the same binaries.
> 
> Makes sense?

Cool, that addition of the build details in the release notes so we know what to reproduce is the bit I was missing. It makes total sense. Thanks!

**Pull request merged**
