### PR TITLE
runtime: migrate from opentracing to opentelemetry

### PR DESCRIPTION
**Pull request by liubin**
Why migrate?

- opentelemetry is the new opentracing
- agent will use opentelemetry, so span context will be easy to pass from runtime to agent.

This commit includes two changes:
- migrate from opentracing to opentelemetry
- add jaeger collector configuration items to let Kata runtime shim process directly send spans to on other hosts.(without using jaeger agent)

Fixes: #1351

Signed-off-by: bin <bin@hyper.sh>

Action items:
- [x] Update `cli/config/configuration-xxx.toml`
- [x] New jaeger client doesn't support `LogSpans` options.

This option uses an [internal logger](https://github.com/jaegertracing/jaeger-client-go/blob/fe3fa553c313b32f58cc684a59a4d48f03e07df9/reporter.go#L61
) only to write one line "Reporting span ... " like this:

```
Feb  2 20:31:12 kant-server containerd[19918]: time="2021-02-02T20:31:12.896616023+08:00" level=info msg="Reporting span 6b8e78fc491f368a:6b8e78fc491f368a:0000000000000000:1" pid=21706 sandbox=a12dde014584843dee8a0f5d8ceeaedeaa82e92970780b48ab62890228a82a73 source=katautils
```

And our [test script](https://github.com/kata-containers/tests/blob/master/tracing/tracing-test.sh) is checking the spans recorded in log and jaeger service.

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @liubin! Have you tested this with [the tracing test](https://github.com/kata-containers/tests/blob/main/tracing/tracing-test.sh)?

/cc @cmaf.

**Comment by liubin** [comment]
> Thanks @liubin! Have you tested this with [the tracing test](https://github.com/kata-containers/tests/blob/main/tracing/tracing-test.sh)?
> 
> /cc @cmaf.

Not the same as test script (that's for 1.x), I tested using this simple script to check the span count only:

```bash
#!/bin/bash

curl -s  http://localhost:16686/api/traces?service=kata 2>/dev/null  > /tmp/jaeger.json

journalctl -q -o cat -a -t kata > /tmp/kata.log
grep "Reporting span"  /tmp/kata.log > /tmp/spans.log

json=$(cat /tmp/jaeger.json)
len=$(echo $json | jq -S '.data | length')

for i in $( seq 0 $(($len - 1)) ); do
  row=$(echo $json | jq .data[$i])
  trace_id=$(echo $row | jq -S '.traceID' | tr -d '"')
  echo "trace ID: $trace_id"
  span_count=$(echo $row | jq -S '.spans | length')
  echo "  span count in jaeger: $span_count"
  log_count=$(grep $trace_id /tmp/spans.log | wc -l)
  echo "  span count in log file: $log_count"
  echo ""
done
```

**Review by lifupan — APPROVED** [review]

**Pull request merged**
