### PR TITLE
backport: Don't create socket file in /run/kata to 3.1

### PR DESCRIPTION
**Pull request by alex-matei**
Backport of #6623

### CODE REVIEW

**Comment by gkurz** [comment]
> Backport of #6623

Hi @alex-matei !

The expected workflow when backporting is to :

- wait for the original PR to be merged in main
- create a clone of the stable branch in your local repo
- `git cherry-pick -x` the relevant commits (this tells where the change comes from)
- submit a PR for inclusion in the stable branch

**Comment by gkurz** [comment]
> > Backport of #6623
> 
> Hi @alex-matei !
> 
> The expected workflow when backporting is to :
> 
> * wait for the original PR to be merged in main

This is done now. Please replace the commit with an official cherry-pick in your PR @alex-matei.

> * create a clone of the stable branch in your local repo
> * `git cherry-pick -x` the relevant commits (this tells where the change comes from)
> * submit a PR for inclusion in the stable branch

**Comment by alex-matei** [comment]
Got it, I updated the PR.

**Review by gkurz — APPROVED** [review]
Thanks for the backport @alex-matei ! Much appreciated.

**Review by littlejawa — APPROVED** [review]
lgtm
Thanks @alex-matei !

**Pull request merged**
