### PR TITLE
Update deps for the v0.5.0 release of Confidential Containers

### PR DESCRIPTION
**Pull request by fidencio**
image-rs, attestation-agent, and td-shim were bumped to v0.5.0 release.

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks!

**Comment by fidencio** [comment]
SEV CI is not collaborating, re-ran it a few times and had different failures, which do not seem related to this PR.
/cc @ryansavino

**Comment by fidencio** [comment]
@BbolroC, @stevenhorsman, s390x CI doesn't seem to be stable: http://jenkins.katacontainers.io/job/kata-containers-CCv0-ubuntu-20.04-s390x-PR/590/

Mind to take a look?

**Comment by stevenhorsman** [comment]
> @BbolroC, @stevenhorsman, s390x CI doesn't seem to be stable: http://jenkins.katacontainers.io/job/kata-containers-CCv0-ubuntu-20.04-s390x-PR/590/
> 
> Mind to take a look?

I've found in the last few days that every other test run fails. Choi and Hendrik are on vacation at the moment, and I don;t have access to the machine to debug, so I've rebuilt and hopefully that will do the trick, but I'll check later

**Comment by fidencio** [comment]
TDX Cloud Hypervisor failed due to:
```
13:37:54 warning: spurious network error (2 tries remaining): [92] Stream error in the HTTP/2 framing layer (HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1))
13:38:24 warning: spurious network error (1 tries remaining): [35] SSL connect error (OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to crates.io:443 )
13:38:54 error: failed to download from `[https://crates.io/api/v1/crates/libz-sys/1.1.8/download`](https://crates.io/api/v1/crates/libz-sys/1.1.8/download%60)
```

Rerunning.

**Review by wainersm — APPROVED** [review]
LGTM, Thanks @fidencio !

**Pull request merged**
