### PR TITLE
# Kata Containers 2.3.1

### PR DESCRIPTION
**Pull request by snir911**
- stable-2.3 | kata-deploy: fix tar command in dockerfile
- stable-2.3 | versions: Upgrade to Cloud Hypervisor v20.2
- stable-2.3 Missing backports
- stable-2.3 | docs: Fix kernel configs README spelling errors
- docs: Fix outdated links
- stable-2.3 | versions: Upgrade to Cloud Hypervisor v20.1
- Backport osbuilder: Revert to using apk.static for Alpine
- stable-2.3 | runtime: only call stopVirtiofsd when shared_fs is virtio-fs
- Backport versions: Use Ubuntu initrd for non-musl archs
- stable-2.3 | Upgrade to Cloud Hypervisor v20.0 and Openapi-generator v5.3.0
- stable-2.3 | packaging: Fix missing commit message in building kata-runtime
- stable-2.3 | runtime: enable vhost-net for rootless hypervisor
- [backport] agent: create directories for watchable-bind mounts
- runtime: enable FUSE_DAX kernel config for DAX

dfbe74c4 kata-deploy: fix tar command in dockerfile
9e7eed7c versions: Upgrade to Cloud Hypervisor v20.2
53cf1dd0 tools/packaging: add copyright to kata-monitor's Dockerfile
a4dee6a5 packaging: delint tests dockerfiles
fd87b60c packaging: delint kata-deploy dockerfiles
2cb4f7ba ci/openshift-ci: delint dockerfiles
993dcc94 osbuilder: delint dockerfiles
bbd7cc2f packaging: delint kata-monitor dockerfiles
9837ec72 packaging: delint static-build dockerfiles
8785106f packaging/qemu: Use QEMU script to update submodules
a915f082 packaging/qemu: Use partial git clone
ec3faab8 security: Update rust crate versions
1f61be84 osbuilder: Add protoc to the alpine container
d2d8f9ac osbuilder: avoid to copy versions.txt which already deprecated
ca30eee3 kata-manager: Retrieve static tarball
0217abce kata-deploy: Deal with empty containerd conf file
572b25dd osbuilder: be runtime consistent also with podman build
84e69ecb agent: user container ID as watchable storage key for hashmap
77b6cfbd docs: Fix kernel configs README spelling errors
24085c95 docs: Fix outdated k8s link
514bf74f docs: Replicate branch rename on runtime-spec
77a2502a cri-o: Update links for the CRI-O github page
6413ecf4 docs: Backport source reorganization links
a0bed72d versions: Upgrade to Cloud Hypervisor v20.1
d03e05e8 versions: Use fixed, minor version for Alpine
0f7db91c osbuilder: Revert to using apk.static for Alpine
271d67a8 runtime: only call stopVirtiofsd when shared_fs is virtio-fs
7c15335d versions: Use Ubuntu initrd for non-musl archs
15080f20 virtcontainers: clh: Upgrade to openapi-generator v5.3.0
c2b8eb3c virtcontainers: clh: Re-generate the client code
fe0fbab5 versions: Upgrade to Cloud Hypervisor v20.0
be5468fd packaging: Fix missing commit message in building kata-runtime
18bb9a5d runtime: enable vhost-net for rootless hypervisor
3458073d agent: create directories for watchable-bind mounts
0e91503c runtime: enable FUSE_DAX kernel config for DAX

### CODE REVIEW

**Comment by snir911** [comment]
adding do-not-merge until test-kata-deploy passed, currently it's [skipped](https://github.com/kata-containers/kata-containers/actions/runs/1664441248), I'm not sure why, let's try later

**Comment by fidencio** [comment]
@snir911, the command is `/test_kata_deploy` rather than `/test-kata-deploy`.  That's due to the action used when the command was introduced.  It could be changed nowadays, but it's what it's for now.  So, using `_` instead of `-` when calling the command will unblock you.

**Comment by snir911** [comment]
ahh missed that /o\ thanks @fidencio !
/reteset-arm

**Comment by snir911** [comment]
Sorry for the for the noisy arm testing
The ARM job is usually [failing](http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-ARM-PR/3053/console) with this [error **_HTTP error status 429_**](https://github.com/kata-containers/tests/issues/4311) which seems to be more frequent on arm01_slave
However, also when it passes, it [fails](http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-ARM-PR/3050/console) with the following odd error:
```
10:40:57 golangci/golangci-lint info checking GitHub for tag 'v1.41.1'
10:40:57 golangci/golangci-lint crit unable to find 'v1.41.1' - use 'latest' or see https://github.com/golangci/golangci-lint/releases for details
```
Tagging the ARM ppl @jongwu, @justin-he for advise and also @wainersm and @GabyCT for their attention

**Comment by snir911** [comment]
test-kata-deploy is [failing at clean up](https://github.com/kata-containers/kata-containers/runs/4752311415?check_suite_focus=true), @fidencio were you [referring](https://github.com/kata-containers/tests/pull/4314#issuecomment-1007574608) to this error legitimacy ? or the previous one?

**Comment by fidencio** [comment]
> test-kata-deploy is failing at clean up, @fidencio were you referring to this error legitimacy ? or the previous one?

That error.  You can try re-triggering the job, but if that persists, you'll need to debug that locally.

**Comment by snir911** [comment]
/test_kata_deploy
Just noticed arm passed \o/

**Review by jodh-intel — APPROVED** [review]
Thanks @snir911.

lgtm

**Review by bergwolf — APPROVED** [review]

**Comment by bergwolf** [comment]
Looks like we can drop the `do-not-merge` label now.

**Comment by bergwolf** [comment]
`jenkins-ci-s390x-ubuntu-20-04` is not required as it is constantly failing recently.

**Comment by fidencio** [comment]
This was merged without having a green `/test_kata_deploy` result.

**Pull request merged**
