### PR TITLE
kata-deploy: Add http_proxy as part of the docker build

### LINKED ISSUE #6834: add http_proxy as docker build arguments in kata deploy

### PR DESCRIPTION
**Pull request by GabyCT**
Add http_proxy and https_proxy as part of the docker build arguments in order to build properly when we are behind a proxy.

Fixes #6834

### CODE REVIEW

**Comment by fidencio** [comment]
Do we need to do so?

From my experience in the past, Just having this as part of the ~/.docker, and that should be it, as the file is mounted inside the containers: 4da743f90b22f9ae1235a1e13999a7097a8690f2

**Review by amshinde — APPROVED** [review]

**Comment by GabyCT** [comment]
> Do we need to do so?
> 
> From my experience in the past, Just having this as part of the ~/.docker, and that should be it, as the file is mounted inside the containers: [4da743f](https://github.com/kata-containers/kata-containers/commit/4da743f90b22f9ae1235a1e13999a7097a8690f2)

Well I have face this issue when I am using the CI scripts in a clean environment.

**Comment by fidencio** [comment]
> Well I have face this issue when I am using the CI scripts in a clean environment behind a proxy.

And this solved the issue for you?  If so, okay, we can have it in; but I had problems in the past making it work on this way.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @GabyCT!

**Pull request merged**
