### PR TITLE
versions: Qemu v6.0.0

### PR DESCRIPTION
**Pull request by jcvenegas**
Move qemu and qemu-experimental to version 6.0.0

Fixes: #1691

Signed-off-by: Carlos Venegas <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @jcvenegas - I can't see any mention of these new "magic trigger words" in the CI configs? Are there newer versions that need to be added to https://github.com/kata-containers/ci? Also, if these are valid new commands, could you add them to https://github.com/kata-containers/community/wiki/Controlling-the-CI?

**Comment by jodh-intel** [comment]
Ping @jcvenegas.

**Review by wainersm — APPROVED** [review]
Hi @jcvenegas ,

The changes looks good to me. I also could build both vanilla and experimental QEMU in my workstation with your changes.

Thanks!

**Review by jodh-intel — APPROVED** [review]
Thanks @jcvenegas.

lgtm

**Review by amshinde — APPROVED** [review]

**Review by dgibson — CHANGES_REQUESTED** [review]
The `no_patches` file should be called `no_patches.txt` instead: the incorrect name seems to mess up one of the pedantic style checks in the CI.

If you rebase this on top of #2382 I believe the remaining CI failures will be fixed.

**Comment by cmaf** [comment]
ping @jcvenegas

**Comment by dgibson** [comment]
@jcvenegas can we close this one in favour of #2502?

**Comment by jcvenegas** [comment]
@dgibson yes, closing this PR. Thanks!

**Pull request closed without merging**
