### PR TITLE
CCv0: update dependencies for CoCo release 0.6.0

### PR DESCRIPTION
**Pull request by Xynnn007**
td-shim:  9e9a045b08b04756ccbbd5c9477f34fe366f054c
attestation-agent: 1fc89c144089d6faa77f7e92b6733dbfbeadc070

### CODE REVIEW

**Review by jepio — APPROVED** [review]

**Review by jepio — APPROVED** [review]

**Review by stevenhorsman — APPROVED** [review]
The versions picked look correct to me. Thanks!

**Comment by stevenhorsman** [comment]
We got the standard sev failure of `E: The repository 'http://apt.kubernetes.io/ kubernetes-xenial-unstable Release' no longer has a Release file.`, so I've re-queued that job

**Comment by stevenhorsman** [comment]
The tests have all passed, so this can be merged now.

**Pull request merged**
