### PR TITLE
runtime-rs: workaround Dragonball compilation problem

### PR DESCRIPTION
**Pull request by studychao**
Since the upstream rust-vmm is changing its dependency style towards caret requirements in these days (more information: rust-vmm/vm-memory#199) and it breaks Dragonball compilation frequently.

rust-vmm is expected to finish the changes this week and in order to not break Kata CI due to Dragonball's compilation error, we will add Cargo.lock file into /src/dragonball first and remove it later when rust-vmm is stable.

fixes: #5657
Depends-on: https://github.com/kata-containers/kata-containers/pull/5640

Signed-off-by: Chao Wu <chaowu@linux.alibaba.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @studychao!

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks!

**Comment by fidencio** [comment]
I'm closing this one as it'll be merged as part of https://github.com/kata-containers/kata-containers/pull/5669

**Pull request closed without merging**
