### PR TITLE
versions: update ovmf to edk2-stable202208 for x86 and sev

### PR DESCRIPTION
**Pull request by Alex-Carter01**
This is the latest tagged release.

Fixes: #5686
Signed-off-by: Alex Carter <Alex.Carter@ibm.com>

@dubek @fitzthum

### CODE REVIEW

**Review by dubek — APPROVED** [review]
Looks good.

Specifically this release includes a fix that allows starting SEV-ES guests with Kata (tested as part of a WIP PR which will be submitted soon).

I tested with the new edk2 version and I can confirm it can start SEV-ES pods.

**Review by fitzthum — APPROVED** [review]
Nice

**Review by fidencio — APPROVED** [review]
lgtm, thanks @Alex-Carter01!

**Comment by fidencio** [comment]
One thing that I'm wondering here is how we'll test it on the AMD CI side.

Theoretically should be just a matter of running the AMD CI and having it passing, but it's been some reasonable time that it doesn't happen, see: http://jenkins.katacontainers.io/view/CCv0/job/kata-containers-CCv0-ubuntu-20.04_sev-x86_64-CC_SEV_CRI_CONTAINERD_K8S-PR/, which shows the last green run we had with AMD SEV CI is from 14 dayus ago (by the time I write this message).

I'm adding a `do-not-merge` label to this PR so we can ensure this can be tested through our CI.

**Comment by fidencio** [comment]
Removing the `do-not-merge` label as the SEV CI is back.
I'd recommend opening a PR with the same changes against the CCv0 branch just to make sure CI passes with this changes.

**Comment by Alex-Carter01** [comment]
Waiting for a release of ovmf with dov's patches switching to a need to use CC fork (https://github.com/confidential-containers-demo/edk2) until then. 

Making the switch in https://github.com/kata-containers/kata-containers/pull/5893.

Then once the patch gets upstreamed, come back and make a change like this to the version file for x86 and sev with a new release tag.

**Pull request closed without merging**
