### PR TITLE
Improve error checking of hugepage allocation

### PR DESCRIPTION
**Pull request by dgibson**
This series contains some small fixes and debugging improvements for bug #3752 and #3743.  It is *not* a fix for either of those problems, but may show the problems more clearly.

### CODE REVIEW

**Comment by dgibson** [comment]
Unfortunately, I haven't actually been able to test this code on my own cluster, due to #3757 and # #3755.

**Comment by dgibson** [comment]
Looks like #3752 was not a bug, I just saw weird things due to problems with deployment.  The changes here are still worthwhile cleanups, though.  Redirecting this to a new issue #3816

**Review by gkurz — APPROVED** [review]
I don't quite know rust yet but both changes make a lot of sense.

**Review by devimc — APPROVED** [review]

**Review by c3d — COMMENTED** [review]
Late to the party, but reviewed and looks good.

**Pull request merged**
