### PR TITLE
versions: Bump containerd to 1.7.0

### PR DESCRIPTION
**Pull request by amshinde**
Release includes features such as experimental Sanbox API, Node Resource Interface for plugging extensions,
gRPC shim support and support for Linux conatiners on FreeBSD.

Fixes: #6750

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]

**Comment by amshinde** [comment]
Some CI jobs are failing with error: 
```
+ bin/cri-integration.test
# github.com/containerd/containerd/integration [github.com/containerd/containerd/integration.test]
integration/container_restart_test.go:28:3: undefined: pauseImage
make[1]: *** [Makefile:220: bin/cri-integration.test] Error 2
```
Looking into this.

**Comment by amshinde** [comment]
https://github.com/kata-containers/tests/pull/5623 Should hopefully solve the CI failure.

**Review by fengwang666 — APPROVED** [review]

**Pull request closed without merging**
