### PR TITLE
clh:arm64: use arm AMBA UART for hypervisor debug

### PR DESCRIPTION
**Pull request by jongwu**
cloud hypervisor on arm64 only support arm AMBA UART(pl011) as serial dev. So, the console should be set to "ttyAMA0" instead of "ttyS0" when enable hypervisor debug mode.

### CODE REVIEW

**Comment by jepio** [comment]
hi @jongwu, would you be able to rebase this branch?

**Review by gkurz — APPROVED** [review]
LGTM. Thanks @jongwu !

**Comment by jepio** [comment]
@jongwu can you open PRs to backport if you need this in older releases?

**Comment by jongwu** [comment]
Thanks @jepio -, will do.

**Pull request merged**
