### PR TITLE
runtime: bind and unbind vfio with driver_probe

### PR DESCRIPTION
**Pull request by liangxianlong**
Make vfio driver switching more convenient and compatible.

Fixes: #6843

### CODE REVIEW

**Comment by fidencio** [comment]
@zvonkok, mind to take a look at this one?

**Comment by zvonkok** [comment]
Will do on Monday, public holiday and long weekend.

**Comment by amshinde** [comment]
@liangxianlong Thanks for the PR. Sorry for the delay in review.  I am trying to understand the root cause for the bug you are seeing.
The current implementation was tested and would work for a physical device/virtual function that has a driver assigned to it on the host, I can see it may not work for a physical device that does not have a driver assigned on the host. 
Is this what is happening in your case?
With the change you have implemented, I want to make sure vfio driver assignment works in all cases:
1) Physical device/VF assigned to host driver
2) Physical device/VF not using a driver on the host. 

Have you tested your code in the above scenarios? I'll try to test this on my end as well.

**Comment by amshinde** [comment]
@liangxianlong Since I havent heard from you, I have raised a PR that includes this change that I needed to add another network related feature. I have attributed the commit with you as a contributor:https://github.com/kata-containers/kata-containers/pull/8597/commits/17a8c573777ae04a2558eef9879347e4daae56a4

**Pull request closed without merging**
