### PR TITLE
Update QEMU >= 6.1.0 in configure-hypervisor.sh

### LINKED ISSUE #3547: configure-hypervisor: states require 5.0; Kata now requires 6.1 is a minimum version
With the  ACPI PCI hotplug changes introduced in 2.3, we require QEMU >= 6.1.  The hypervisor configuration script needs updating to reflect this. See:
https://github.com/kata-containers/kata-containers/blob/016569fd8e0158f709ff23e0f32567bc9918ca26/tools/packaging/scripts/configure-hypervisor.sh#L547

### PR DESCRIPTION
**Pull request by goodluckbot**
fixes #3547

### CODE REVIEW

**Review by Jakob-Naucke — COMMENTED** [review]
@goodluckbot Please sign off your message (`git commit -s`), give it a body and link an issue (see [contributing guidelines](https://github.com/kata-containers/community/blob/9df55940b64146dfb8e3d557fef9c672ab360007/CONTRIBUTING.md#general-format)). LGTM otherwise.

**Comment by liubin** [comment]
There are too many `qemu_version` checks:

```
$ grep -rn  qemu_version tools/packaging/scripts/configure-hypervisor.sh
tools/packaging/scripts/configure-hypervisor.sh:42:qemu_version=""
tools/packaging/scripts/configure-hypervisor.sh:226:	if ! gt_eq ${qemu_version} 5.2.0 ; then
tools/packaging/scripts/configure-hypervisor.sh:315:	if gt_eq "${qemu_version}" "5.2.0" ; then
tools/packaging/scripts/configure-hypervisor.sh:334:	if gt_eq "${qemu_version}" "5.2.0" ; then
tools/packaging/scripts/configure-hypervisor.sh:390:	if ! gt_eq "${qemu_version}" "5.1.0" ; then
tools/packaging/scripts/configure-hypervisor.sh:452:	if ! gt_eq "${qemu_version}" "5.2.0" ; then
tools/packaging/scripts/configure-hypervisor.sh:537:	local qemu_version_file="VERSION"
tools/packaging/scripts/configure-hypervisor.sh:538:	[ -f ${qemu_version_file} ] || die "QEMU version file '$qemu_version_file' not found"
tools/packaging/scripts/configure-hypervisor.sh:542:	qemu_version="$(awk 'BEGIN {FS = "-"} {print $1}' ${qemu_version_file})"
tools/packaging/scripts/configure-hypervisor.sh:544:	[ -n "${qemu_version}" ] ||
tools/packaging/scripts/configure-hypervisor.sh:545:		die "cannot determine qemu version from file $qemu_version_file"
tools/packaging/scripts/configure-hypervisor.sh:547:	if ! gt_eq "${qemu_version}" "5.0.0" ; then
```

If at least 6.1.0 is required, all other checks(5.1/5.2) should be determined, they will be all `true`. 
cc @egernst

**Comment by fidencio** [comment]
A head's up that may affect your PR.

In the Architecture Committee meeting from January 25th, 2022, the Architecture Committee has agreed on using the "Dismiss stale pull request approvals when new commits are pushed" configuration from GitHub.  It basically means that if your PR has been rebased or updated, the approvals given will be erased.

In order to minimize traumas due to the new approach, please, consider adding a note on the changes done before the rebase / force-push, and also pinging the reviewers for a subsequent round of reviews.

Thanks for your understanding!

Related issue: https://github.com/kata-containers/community/issues/249

**Comment by egernst** [comment]
@goodluckbot  -- thanks for raising this PR! You're not actually a bot, right?

I agree @liubin. IMO this script should just disable EVERYTHING, and then enable *just* what we need.

Something like the following run against QEMU's configure file:
```
DISABLE_ALL_FLAGS := $(shell grep -o '\-\-disable\(\-[a-zA-Z0-9]\+\)\+' configure 
```

I'm not sure if we need to necessarily do that in this PR, but it would be a good follow up. I think addressing Bin's feedback would be a good idea in this PR.

 Can you take that on @goodluckbot  ?

**Comment by jodh-intel** [comment]
It would also be great if we could avoid hard-coding the QEMU version in this script when it's already specified in https://github.com/kata-containers/kata-containers/blob/main/versions.yaml. We should try to extract the version by sourcing https://github.com/kata-containers/tests/blob/main/.ci/lib.sh and calling [`get_version()`](https://github.com/kata-containers/tests/blob/main/.ci/lib.sh#L164).

**Comment by amshinde** [comment]
All the previous checks for versions were meant to maintain backward compatibility. Similar logic was applied in the runtime code as well. Since backward compatibility for qemu < 6.1 was removed in the runtime code, we can make a decision to remove all the checks as well, unless we decide we want to reintroduce backward compatibility in the runtime code as well.

**Comment by liubin** [comment]
Maybe aarch64 needs a version smaller than 6.1.0:

https://github.com/kata-containers/kata-containers/blob/732c45de947d016cbb6f7e58eecdc4f3b5f6d4eb/versions.yaml#L88-L106

**Comment by egernst** [comment]
@jongwu  -- can you TAL and comment on ARM requirement for QEMU version?

**Comment by jongwu** [comment]
Hello @egernst -, I can remove the dependency of qemu 5.1 on arm side later.
By the way, maybe I miss the background. Can you make it clear about what's "the changes of ACPI hotplug pci"?

**Comment by liubin** [comment]
@goodluckbot please update your commit:

> Error: The SoB (DCO) check failed
  5d2f4c563[11](https://github.com/kata-containers/kata-containers/runs/4994546965?check_suite_focus=true#step:3:11)a2d627375f71ff4f593c3c7f3ac65    Expected "goodluckbot <tangbo_gl@hotmail.com>", but got "Bo Tang <tangbo_gl@hotmail.com>".

**Review by fidencio — APPROVED** [review]
lgtm, thanks @goodluckbot1

**Comment by fidencio** [comment]
@liubin, @goodluckbot, any chance to have a re-spin of this one?

**Review by egernst — APPROVED** [review]

**Comment by bergwolf** [comment]
`5d2f4c56311a2d627375f71ff4f593c3c7f3ac65    Expected "goodluckbot <tangbo_gl@hotmail.com>", but got "Bo Tang <tangbo_gl@hotmail.com>".`

Please make sure you sign off the commit with the same name as the commit author.

**Review by fidencio — APPROVED** [review]
lgtm, thanks!

**Review by Jakob-Naucke — APPROVED** [review]

**Pull request merged**
