### PR TITLE
agent: clear clippy warnings

### PR DESCRIPTION
**Pull request by liubin**
## This PR mainly contains two changes:

- add `cargo clippy` to Travis CI
- clear all clippy warnings for existing code to pass CI

Fixes: #951 

## Limitations:

Not all lint are checked. Explicitly allowed lint includes:

### redundant_allocation

```
warning: usage of `Box<&T>`
  --> rustjail/src/cgroups/fs/mod.rs:48:30
   |
48 | pub fn load_or_create<'a>(h: Box<&'a dyn cgroups::Hierarchy>, path: &str) -> Cgroup<'a> {
   |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `&'a dyn cgroups::Hierarchy`
   |
   = note: `#[warn(clippy::redundant_allocation)]` on by default
```
This only appears in `rustjail/src/cgroups/fs/mod.rs`, and I tried to resolve it, but it seems need more time.

Refer: https://rust-lang.github.io/rust-clippy/master/index.html#redundant_allocation

### CODE REVIEW

**Comment by liubin** [comment]
And also will fix #101

**Review by jodh-intel — APPROVED** [review]
Thanks @liubin.

**Comment by Tim-Zhang** [comment]
@liubin You can ignore clippy warnings in protocols by adding #![allow(clippy::redundant_field_names)] in the top of `src/agent/protocols/src/lib.rs`

**Comment by Tim-Zhang** [comment]
@liubin You can resolve the `module_inception` problem by removing `mod test_utils {}` 
and resolve the `type_complexity ` problem by using `Type aliases` e.g. `type MessageSender = Sender<(Vec<u8>, Sender<Result<Vec<u8>>>)>;`

**Comment by liubin** [comment]
@Tim-Zhang thanks, I have fixed the warnings.

**Comment by liubin** [comment]
I think we need some Rust version policy.

I tested for versions `1.44.1`/`1.45.0`/`1.47.0`, the `cargo clipy` complains fews different warnings.

If we update Rust too frequent, it will need additional more works to fix the clipyp warnings newly introduced.

cc @jodh-intel @bergwolf

**Review by lifupan — APPROVED** [review]

**Comment by Tim-Zhang** [comment]
> If we update Rust too frequent, it will need additional more works to fix the clipyp warnings newly introduced.

Can you list some of the differences?

**Pull request merged**
