### PR TITLE
docs: Update configuration reference for snap documentation

### LINKED ISSUE #4341: update configuration reference in snap documentation

### PR DESCRIPTION
**Pull request by GabyCT**
This PR updates the url link for the kata containers configuration
for the general snap documentation.

Fixes #4341

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by snir911** [comment]
Thanks @GabyCT, maybe worth also to switch to a relative link

**Review by jodh-intel — APPROVED** [review]

**Comment by jodh-intel** [comment]
@fidencio - only just seen this comments. Yes, ideally if someone else could ack https://github.com/kata-containers/kata-containers/pull/4322, we could land that first. Let's add a dnm on this for now...

**Comment by GabyCT** [comment]
@jodh-intel should I close this PR or resolve the conflict?

**Comment by GabyCT** [comment]
I did the rebase

**Review by cmaf — APPROVED** [review]

**Pull request merged**
