### PR TITLE
docs: Add instructions for getting QEMU source

### LINKED ISSUE #1907: doc: Developer guide: Expand on `$your_qemu_directory` reference
# Description of problem

It might just be that I've missed something, but I've been following the [developer guide](../blob/main/docs/Developer-Guide.md) to build my own version of kata-containers and I got confused when trying to follow the commands in [Build a custom QEMU](https://github.com/kata-containers/kata-containers/blob/main/docs/Developer-Guide.md#build-a-custom-qemu). It referred to `cd $your_qemu_directory` which hadn't been defined before. I had a search around and saw that in kata 1.x this was used to link to the kata-containers/qemu directory, which is now out of date as I think the intention is to use the upstream version of QEMU now?

I think I've worked out how to set-up this directory, so assuming I'm correct I think it might be helpful to add a section on this under "Kata Containers makes use of upstream QEMU branch. The exact version and repository utilized can be found by looking at the versions file." to add

Find the correct version of QEMU from the versions file:
```bash
$ source ${GOPATH}/src/github.com/kata-containers/kata-containers/tools/packaging/scripts/lib.sh
$ qemu_version=$(get_from_kata_deps "assets.hypervisor.qemu.version")
$ echo ${qemu_version}
```
Get the matching branch of QEMU:
```bash
$ go get -d github.com/qemu/qemu
$ cd ${GOPATH}/src/github.com/qemu/qemu
$ git checkout ${qemu_version}
$ your_qemu_directory=${GOPATH}/src/github.com/qemu/qemu
```

Let me know if you think my change is helpful for new people (like me!). Thanks!

### PR DESCRIPTION
**Pull request by stevenhorsman**
Update the developer guide to add instructions of how to get the
correct version of the QEMU source and sets your_qemu_directory
variable, so that follow on steps are easier for a new joiner to the
community to understand

Fixed #1907

Signed-off-by: stevenhorsman <steven@uk.ibm.com>

### CODE REVIEW

**Review by devimc — APPROVED** [review]
thanks @stevenhorsman

**Comment by stevenhorsman** [comment]
I've updated my git commit message properly now (I was missing a blank line between the subject body). Sorry for the inconvenience

**Review by GabyCT — APPROVED** [review]

**Comment by fidencio** [comment]
@stevenhorsman, there are two issues with this PR, and I'd like to suggest you to do the following:
$ `git rebase -i origin/main`

An editor will be opened and you'll see something like this:
```
pick 380ef517 docs: Add instructions for getting QEMU source
pick 05227c8d docs: Add instructions for getting QEMU source Update the developer guide to add instructions of how to get the correct version of the QEMU source and sets your_qemu_directory variable, so that follow on steps are easier for a new joiner to the community to understand Fixed #1907

# Rebase 0c463bab..f74b5fe9 en 0c463bab (2 comandos)
```

There, you need to switch the second `pick` to `fixup`, resulting on something like this:
```
pick 380ef517 docs: Add instructions for getting QEMU source
fixup 05227c8d docs: Add instructions for getting QEMU source Update the developer guide to add instructions of how to get the correct version of the QEMU source and sets your_qemu_directory variable, so that follow on steps are easier for a new joiner to the community to understand Fixed #1907
```

Then you force push the PR here.

With that we can get those two commits as a single one (and they should be a single one, right?), getting then rid of the merge commit as well.

**Comment by stevenhorsman** [comment]
@fidencio - thank you for the instructions - I think I've followed them correctly now? Sorry for my mess up originally!

**Pull request merged**
