### PR TITLE
# Kata Containers 1.11.0

### PR DESCRIPTION
**Pull request by katabuilder**
Version bump no changes

### CODE REVIEW

**Comment by GabyCT** [comment]
@jcvenegas the travis failure is impacted by https://github.com/kata-containers/kata-containers/issues/202

**Comment by jcvenegas** [comment]
@GabyCT thanks for the heads-up I think we will force the merge then this repo is not relly neeed for any functionality of kata.

**Comment by jcvenegas** [comment]
I will force merge this PR, we dont need the fix  for  kata release, it would be nice that after #202 is fixed get a backport for next releases

**Pull request merged**
