### PR TITLE
Subject: [PATCH] qemu: add annotations for iommu_platform for s390x v…

### LINKED ISSUE #603: [forward port]: qemu: add annotations for iommu_platform for s390x virtio devices
Port https://github.com/kata-containers/runtime/pull/2831 (issue https://github.com/kata-containers/runtime/issues/2830) from Kata 1.x.

### PR DESCRIPTION
**Pull request by huoqifeng**
…irtio devices

Add iommu_platform annotations for qemu for ccw,
other supported devices can also make use of that.

  Fixes #603

Signed-off-by: Qi Feng Huo <huoqif@cn.ibm.com>

### CODE REVIEW

**Comment by huoqifeng** [comment]
@jodh-intel the PR is opened to forward port `iommu_platform` described in #603, do you know why the job `jenkins-ci-ubuntu-18-04` is pending?

**Comment by huoqifeng** [comment]
@devimc thanks for review and approve. @jodh-intel may you help review and merge it?

**Review by bergwolf — APPROVED** [review]

**Comment by huoqifeng** [comment]
@bergwolf thanks for review and merge the code!

**Pull request merged**
