### PR TITLE
agent: optimize the code of systemd cgroup manager

### PR DESCRIPTION
**Pull request by stevenhorsman**
1. Directly support CgroupManager::freeze through systemd API.
2. Avoid always passing unit_name by storing it into DBusClient.
3. Realize CgroupManager::destroy more accurately by killing systemd unit rather than stop it.
4. Ignore no such unit error when destroying systemd unit.
5. Update zbus version and corresponding interface file.

Acknowledgement: error handling for no such systemd unit error refers to

Fixes: #7080, #7142, #7143, #7166

Signed-off-by: Yuan-Zhuo <yuanzhuo0118@outlook.com>
Signed-off-by: Yohei Ueda <yohei@jp.ibm.com>
(cherry picked from commit 470d065415e00e6bebd63f1b0e8f55d40707cb0e)

### CODE REVIEW

**Comment by stevenhorsman** [comment]
Everything is failing due to the rust 1.70 requirement issue

**Comment by stevenhorsman** [comment]
@fidencio @arronwy @ChengyuZhu6 - is one of you able to check the TDX failure and see if it's related to this PR, or a networking issue? Thanks!

**Comment by ChengyuZhu6** [comment]
> @fidencio @arronwy @ChengyuZhu6 - is one of you able to check the TDX failure and see if it's related to this PR, or a networking issue? Thanks!

That's not related to this PR, and I have rebuilt the tdx test.

**Pull request merged**
