### PR TITLE
ci: Re-enable SNP CI

### PR DESCRIPTION
**Pull request by AdithyaKrishnan**
We've debugged the SNP Node and we
wish to test the fixes on GHA.
This PR will undo [PR#10539](https://github.com/kata-containers/kata-containers/pull/10539)

### CODE REVIEW

**Comment by AdithyaKrishnan** [comment]
Requesting your approval @stevenhorsman @fidencio

**Review by wainersm — APPROVED** [review]
Hi @AdithyaKrishnan !

Cool. Fingers crossed it's fixed now!

**Review by stevenhorsman — APPROVED** [review]
This looks okay to me. I think it future it would be good to use`git revert` for clarity.

**Review by fidencio — CHANGES_REQUESTED** [review]
I would do this differently.

One commit enabling the CI, one commit skipping the tests that were failing before (everything related to attestation).

Then on the PR that you are trying to solve the attestation issue, I would un-skip the tests there.  This way we ensure we don't add a CI that will be red for we don't know how much time.

**Comment by wainersm** [comment]
> I would do this differently.
> 
> One commit enabling the CI, one commit skipping the tests that were failing before (everything related to attestation).
> 
> Then on the PR that you are trying to solve the attestation issue, I would un-skip the tests there. This way we ensure we don't add a CI that will be red for we don't know how much time.

IMO, That's a good plan.

**Review by wainersm — APPROVED** [review]
LGTM. Thanks @AdithyaKrishnan !

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks for the suggestion @fidencio

**Pull request merged**
