### PR TITLE
Fix commit-message-check and do some updates about github actions

### LINKED ISSUE #519: 'Fixes checking' for commit message should pass as long as one commit has 'Fixes'
# Description of problem
Fixes check for commit message should pass as long as one commit has Fixes

# Expected result

As long as one of the commits in the pull-request has 'Fixes' in its commit message the whole check should be ok.

# Actual result

all the commits need have 'Fixes' in their commit message otherwise the check will be failed.

### LINKED ISSUE #520: Subsystem check in github action will count SoB(DCO) as a valid subsystem. It's a regex bug.
The commit message is something like: "Rm xxx\n\nxxxx\n\nSigned-off-by: Tim Zhang <tim@hyper.sh>" and the regex does not process the '\n' correctly.

### PR DESCRIPTION
**Pull request by Tim-Zhang**
- Fixes #519 
- Fixes #520 
- Do not limit the length of single word in commit body
- Add commit-body-missing check
- Some minor updates

### CODE REVIEW

**Comment by Tim-Zhang** [comment]
> Since this is effectively a revendor, you might want to list the changes between the versions as documented here:
> 
> * https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#re-vendor-prs

Do you mean this 
image

**Comment by jodh-intel** [comment]
Ah - thanks @Tim-Zhang! I was looking for a `vendor:` commit so overlooked that ;)

**Pull request merged**
