### PR TITLE
Add openTelemetry tracing with VSOCK

### PR DESCRIPTION
**Pull request by jodh-intel**
Implement an openTelemetry custom exporter that sends trace spans to a VSOCK socket. A vsock-to-span converter needs to be running on the host to allow systems like Jaeger to capture the trace spans.

The agent tracer is enabled by specifying `agent.tracing` on the guest kernel command line.

Current limitations:

- Only static isolated tracing is supported.
- Only main, sandbox and RPC functions are traced.

Also contains:

- Some cosmetic changes
- Fix for a nasty crasher bug.
- Added the ability for the agent to shut down gracefully (required for correct tracing operation).

Fixes: #60.

### CODE REVIEW

**Comment by jodh-intel** [comment]
Note that there is no tracing documentation yet since this feature is not generally usable due to runtime regressions (see https://github.com/kata-containers/kata-containers/issues/421).

I'll add the doc in a follow-up PR.

**Comment by jodh-intel** [comment]
Ping @kata-containers/kata-containers - This is ready for review :smile:

rust-agent-OpenTelemetry-tracing-with-jaeger

**Comment by jodh-intel** [comment]
There's still a problem with this PR - I'm investigating...

**Comment by fidencio** [comment]
I'm really sorry for the disruption but in order to do the branch name changes announced [here](http://lists.katacontainers.io/pipermail/kata-dev/2021-January/001695.html) I'm adding the "do-not-merge" and the "needs-branch-adjustment" labels to the PR.

I'll add a new comment once the branch changes are done and once it happens I'd like to ask you to resubmit the PR against the new `main` branch, possibly linking to this PR in case you find the conversations / reviews already made important to proceed.

**Comment by fidencio** [comment]
Kata Containers repos are back to business.  Thanks a lot for your patience and I'm very happy to announce that there's no changes needed from your side as renaming the branches automagically reflected here.

If you notice something weird, some missing CI, please, do not hesitate on contacting us here or on #kata-dev on bit.ly/katacontainersslack.

Also, this is a good opportunity to have your PR rebased atop of `main`, to ensure your PR follow all the guidelines (https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format) enforced by this community, or even to re-evaluate whether the PR is currently needed.

Last but not least,  as the default branch has been renamed to `main`, if you have a local clone you'd need to update it and you do so by running:
```
git branch -m 2.0-dev main
git fetch origin
git branch -u origin/main main
```

Happy hacking!

**Comment by liubin** [comment]
hi @jodh-intel any update or plan about this?

**Comment by jodh-intel** [comment]
This PR is **very** stale. Closing in favour of the new PR https://github.com/kata-containers/kata-containers/pull/1929.

**Pull request closed without merging**
