### PR TITLE
runtime: new qemu-coco-dev configuration

### PR DESCRIPTION
**Pull request by wainersm**
Created a new configuration to configure Kata for CoCo without requiring TEE hardware so to allow developers implement/test/debug platform agnostic code on their workstations. It will also ease testing of CoCo features on CI with non-TEE supported VMs.

This is based off qemu configuration. The following differences applied:
  - switched to confidential guest image/initrd
  - switched to confidential kernel
  - switched to 9p shared_fs

Using guest image/initrd and kernel are obvious. The change to `9p` (from `virtio-fs`) is to keep this new runtimeClass aligned with TDX/SEV/SNP and probably it will be changed to `none` when the problems with containerd/nydus-snapshotter are sorted out.

In order to test this, I built a kata-deploy image and created the environment with following script (run from tests/integration/kubernetes):
```bash
#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
tests_k8s_dir="${script_dir}/tests/integration/kubernetes"

#export DOCKER_REGISTRY=${DOCKER_REGISTRY:-quay.io}
export DOCKER_REPO=wainersm/kata-deploy
export DOCKER_TAG=kata-containers-707399901a688c60ad33314c3d9596ed9ffedfd2-amd64

export SNAPSHOTTER=nydus
export KBS_INGRESS=nodeport
export PULL_TYPE="guest-pull"
export KATA_HYPERVISOR="qemu-coco-dev"

prep_env() {
    echo "== CREATE CLUSTER =="
    pushd "$tests_k8s_dir"
    ./gha-run.sh create-cluster-kcli

    export KUBECONFIG="$HOME/.kcli/clusters/${CLUSTER_NAME:-kata-k8s}/auth/kubeconfig"
    echo "== DEPLOY SNAPSHOTTER =="
    ./gha-run.sh deploy-snapshotter

    echo "== DEPLOY KATA =="
    ./gha-run.sh deploy-kata-kcli

    echo "== DEPLOY KBS =="
    ./gha-run.sh deploy-coco-kbs
    popd
}

teardown_env() {
    echo "== DESTROY CLUSTER =="
    pushd "$tests_k8s_dir"
    ./gha-run.sh delete-cluster-kcli
    popd
}

prep_env
#teardown_env
```

Then created a very simple pod with the following yaml:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-cc
  annotations:
    "io.containerd.cri.runtime-handler": kata-qemu-coco-dev
spec:
  runtimeClassName: kata-qemu-coco-dev
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: Always
```

Now I got confident CDH is working, then I ran the following to setup KBS (note: `kbs-client` is installed on environment) :
```
$ bash -c "source tests/integration/kubernetes/confidential_kbs.sh; kbs_set_allow_all_resources"
$ bash -c "source tests/integration/kubernetes/confidential_kbs.sh; kbs_set_resource "default" "aa" "key" "mysecretkey""
```

Then started the pod:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: aa-test-cc
  annotations:
    "io.katacontainers.config.hypervisor.kernel_params": "agent.guest_components_rest_api=resource agent.aa_kbc_params=cc_kbc::http://192.168.122.215:31099"
    "io.containerd.cri.runtime-handler": "kata-qemu-coco-dev"
spec:
  runtimeClassName: kata-qemu-coco-dev
  containers:
    - name: bash-curl
      image: storytel/alpine-bash-curl:latest
      imagePullPolicy: Always
      command:
        - sh
        - -c
        - |
          curl http://127.0.0.1:8006/cdh/resource/default/aa/key; sleep 1000
```

Which returned the secret correctly:
```
$ kubectl logs aa-test-cc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
mysecretkey
100    12  100    12    0     0     24      0 --:--:-- --:--:-- --:--:--    24
```

Fixes https://github.com/kata-containers/kata-containers/issues/9487

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @wainersm!

**Comment by wainersm** [comment]
Convert to draft because there are still some details I'd like to discuss.

@fitzthum would make sense to have `agent.guest_components_rest_api=resource` already set on configuration.toml's `kernel_params`?

@stevenhorsman remember the measured boot feature? I was considering have it enabled by default so that it will be tested (currently it's tested with tdx only IIRC) ... what do you think? But perhaps in a follow up PR...

**Comment by wainersm** [comment]
Update this PR with a commit that changes the non-TEE job and tests to use the new runtimeClass. I ran the tests locally and they passed:
```
== CREATE CLUSTER ==
~/src/github.com/kata-containers/kata-containers/tests/integration/kubernetes ~/src/github.com/kata-containers/kata-containers
== DEPLOY SNAPSHOTTER ==
== DEPLOY KATA ==
== DEPLOY KBS ==
~/src/github.com/kata-containers/kata-containers
== RUN TESTS ==
~/src/github.com/kata-containers/kata-containers/tests/integration/kubernetes ~/src/github.com/kata-containers/kata-containers
namespace/kata-containers-k8s-tests created
Context "kubernetes-admin@kubernetes" modified.
~/src/github.com/kata-containers/kata-containers/tests/integration/kubernetes ~/src/github.com/kata-containers/kata-containers/tests/integration/kubernetes
[run_kubernetes_tests.sh:110] INFO: NAMESPACE       NAME                                          READY   STATUS      RESTARTS   AGE
autorules       autoruler-5ff4dbbf7-rtpz6                     1/1     Running     0          86m
coco-tenant     kbs-546c498b6c-zrnb5                          1/1     Running     0          45m
ingress-nginx   ingress-nginx-admission-create-6cp76          0/1     Completed   0          86m
ingress-nginx   ingress-nginx-admission-patch-l4s8z           0/1     Completed   0          86m
ingress-nginx   ingress-nginx-controller-5cdfb74dc-8fxw9      1/1     Running     0          86m
kube-flannel    kube-flannel-ds-54mkv                         1/1     Running     0          81m
kube-flannel    kube-flannel-ds-ck5zp                         1/1     Running     0          86m
kube-system     coredns-7db6d8ff4d-tmkdq                      1/1     Running     0          86m
kube-system     coredns-7db6d8ff4d-zjzj4                      1/1     Running     0          86m
kube-system     etcd-kata-k8s-ctlplane-0                      1/1     Running     0          86m
kube-system     kata-deploy-w56vs                             1/1     Running     0          67m
kube-system     kube-apiserver-kata-k8s-ctlplane-0            1/1     Running     0          86m
kube-system     kube-controller-manager-kata-k8s-ctlplane-0   1/1     Running     0          86m
kube-system     kube-multus-ds-tvcnl                          1/1     Running     0          81m
kube-system     kube-multus-ds-v68hd                          1/1     Running     0          86m
kube-system     kube-proxy-9xh72                              1/1     Running     0          81m
kube-system     kube-proxy-fj7ww                              1/1     Running     0          86m
kube-system     kube-scheduler-kata-k8s-ctlplane-0            1/1     Running     0          86m
nydus-system    nydus-snapshotter-pwtnw                       1/1     Running     0          70m
[run_kubernetes_tests.sh:111] INFO: Executing k8s-guest-pull-image.bats
1..4
ok 1 Test we can pull an unencrypted image outside the guest with runc and then inside the guest successfully
# pod "node-debugger-kata-k8s-worker-0-p4kh8" deleted
# No resources found in kata-containers-k8s-tests namespace.
# Pod /tmp/bats-run-9xAPUi/file/0/pod-config.yaml.in.VVF file:
# # Copyright (c) 2021, 2022 IBM Corporation
# #
# # SPDX-License-Identifier: Apache-2.0
# #
# apiVersion: v1
# kind: Pod
# metadata:
#   name: test-e2e
# spec:
#   containers:
#     - name: test-container
#       image: quay.io/sjenning/nginx:1.15-alpine
#       imagePullPolicy: Always
#       command:
#         - sleep
#         - "30"
#   nodeName: kata-k8s-worker-0
# pod/test-e2e created
# pod/test-e2e condition met
# Runc pod test-e2e is running
# pod "test-e2e" deleted
# metadata.annotations."io.containerd.cri.runtime-handler"
# Pod /tmp/bats-run-9xAPUi/file/0/pod-config.yaml.in.bxG file:
# # Copyright (c) 2021, 2022 IBM Corporation
# #
# # SPDX-License-Identifier: Apache-2.0
# #
# apiVersion: v1
# kind: Pod
# metadata:
#   name: test-e2e
#   annotations:
#     io.containerd.cri.runtime-handler: "kata-qemu-coco-dev"
# spec:
#   runtimeClassName: kata-qemu-coco-dev
#   containers:
#     - name: test-container
#       image: quay.io/sjenning/nginx:1.15-alpine
#       imagePullPolicy: Always
#       command:
#         - sleep
#         - "30"
#   nodeName: kata-k8s-worker-0
# pod/test-e2e created
# pod/test-e2e condition met
# Kata pod test-e2e with nydus annotation is running
# Checking the image was pulled in the guest
# pod "node-debugger-kata-k8s-worker-0-8mv2r" deleted
# sandbox_id is: b679cb143af3dfe697e1a12c26b9b41cf64c29de8eac36fa0ab466ad5714c2bc
# pod "node-debugger-kata-k8s-worker-0-2dg5t" deleted
# allrootfs is: /run/kata-containers/shared/sandboxes/b679cb143af3dfe697e1a12c26b9b41cf64c29de8eac36fa0ab466ad5714c2bc/mounts/b679cb143af3dfe697e1a12c26b9b41cf64c29de8eac36fa0ab466ad5714c2bc/rootfs
# count of container rootfs in host is: 1, expect count is: 1
# error: resource name may not be empty
# pod "test-e2e" deleted
ok 2 Test we can pull a large image inside the guest # skip Test not supported for qemu-coco-dev.
# pod "node-debugger-kata-k8s-worker-0-q9wgq" deleted
# No resources found in kata-containers-k8s-tests namespace.
# error: resource name may not be empty
# No resources found in kata-containers-k8s-tests namespace.
ok 3 Test we can pull an unencrypted image inside the guest twice in a row and then outside the guest successfully # skip Skip this test until we use containerd 2.0 with 'image pull per runtime class' feature: https://github.com/containerd/containerd/issues/9377
# pod "node-debugger-kata-k8s-worker-0-gdpq8" deleted
# No resources found in kata-containers-k8s-tests namespace.
# error: resource name may not be empty
# No resources found in kata-containers-k8s-tests namespace.
ok 4 Test we can pull an other unencrypted image outside the guest and then inside the guest successfully # skip Skip this test until we use containerd 2.0 with 'image pull per runtime class' feature: https://github.com/containerd/containerd/issues/9377
# pod "node-debugger-kata-k8s-worker-0-52vhk" deleted
# No resources found in kata-containers-k8s-tests namespace.
# error: resource name may not be empty
# No resources found in kata-containers-k8s-tests namespace.
[run_kubernetes_tests.sh:110] INFO: NAMESPACE       NAME                                          READY   STATUS      RESTARTS   AGE
autorules       autoruler-5ff4dbbf7-rtpz6                     1/1     Running     0          87m
coco-tenant     kbs-546c498b6c-zrnb5                          1/1     Running     0          47m
ingress-nginx   ingress-nginx-admission-create-6cp76          0/1     Completed   0          88m
ingress-nginx   ingress-nginx-admission-patch-l4s8z           0/1     Completed   0          88m
ingress-nginx   ingress-nginx-controller-5cdfb74dc-8fxw9      1/1     Running     0          87m
kube-flannel    kube-flannel-ds-54mkv                         1/1     Running     0          82m
kube-flannel    kube-flannel-ds-ck5zp                         1/1     Running     0          88m
kube-system     coredns-7db6d8ff4d-tmkdq                      1/1     Running     0          87m
kube-system     coredns-7db6d8ff4d-zjzj4                      1/1     Running     0          87m
kube-system     etcd-kata-k8s-ctlplane-0                      1/1     Running     0          88m
kube-system     kata-deploy-w56vs                             1/1     Running     0          68m
kube-system     kube-apiserver-kata-k8s-ctlplane-0            1/1     Running     0          88m
kube-system     kube-controller-manager-kata-k8s-ctlplane-0   1/1     Running     0          88m
kube-system     kube-multus-ds-tvcnl                          1/1     Running     0          82m
kube-system     kube-multus-ds-v68hd                          1/1     Running     0          88m
kube-system     kube-proxy-9xh72                              1/1     Running     0          82m
kube-system     kube-proxy-fj7ww                              1/1     Running     0          88m
kube-system     kube-scheduler-kata-k8s-ctlplane-0            1/1     Running     0          88m
nydus-system    nydus-snapshotter-pwtnw                       1/1     Running     0          72m
[run_kubernetes_tests.sh:111] INFO: Executing k8s-confidential-attestation.bats
1..1
ok 1 Get CDH resource
# pod "node-debugger-kata-k8s-worker-0-k4d5z" deleted
# No resources found in kata-containers-k8s-tests namespace.
# [bats-exec-test:59] INFO: k8s configured to use runtimeclass
# Set resource success
#  resource: YWF0ZXN0Cg==
# Set resource policy success
#  policy: CnBhY2thZ2UgcG9saWN5CgpkZWZhdWx0IGFsbG93ID0gdHJ1ZQoK
# metadata.annotations."io.katacontainers.config.hypervisor.kernel_params"
# pod/aa-test-cc created
# pod/aa-test-cc condition met
#   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
#                                  Dload  Upload   Total   Spent    Left  Speed
# aatest
# 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     7  100     7    0     0     22      0 --:--:-- --:--:-- --:--:--    22
# Name:                aa-test-cc
# Namespace:           kata-containers-k8s-tests
# Priority:            0
# Runtime Class Name:  kata
# Service Account:     default
# Node:                kata-k8s-worker-0/192.168.122.128
# Start Time:          Thu, 25 Apr 2024 15:47:44 -0300
# Labels:              <none>
# Annotations:         io.katacontainers.config.hypervisor.kernel_params:
#                        agent.guest_components_rest_api=resource agent.aa_kbc_params=cc_kbc::http://192.168.122.156:30776
#                      k8s.v1.cni.cncf.io/network-status:
#                        [{
#                            "name": "cbr0",
#                            "interface": "eth0",
#                            "ips": [
#                                "10.244.1.12"
#                            ],
#                            "mac": "96:4e:f2:a9:08:97",
#                            "default": true,
#                            "dns": {},
#                            "gateway": [
#                                "10.244.1.1"
#                            ]
#                        }]
# Status:              Running
# IP:                  10.244.1.12
# IPs:
#   IP:  10.244.1.12
# Containers:
#   bash-curl:
#     Container ID:  containerd://afb5b6b44aabc504df451b512fca5ecd5b3f830a7202e1608afa09434ab423b1
#     Image:         storytel/alpine-bash-curl:latest
#     Image ID:      docker.io/storytel/alpine-bash-curl@sha256:38744e2e5138fa92ae600e5aa224e74090f8fe06358838322ba676ce98eb891b
#     Port:          <none>
#     Host Port:     <none>
#     Command:
#       sh
#       -c
#       curl http://127.0.0.1:8006/cdh/resource/default/aa/key; sleep 1000
#
#     State:          Running
#       Started:      Thu, 25 Apr 2024 15:47:52 -0300
#     Ready:          True
#     Restart Count:  0
#     Environment:    <none>
#     Mounts:
#       /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-sfffp (ro)
# Conditions:
#   Type                        Status
#   PodReadyToStartContainers   True
#   Initialized                 True
#   Ready                       True
#   ContainersReady             True
#   PodScheduled                True
# Volumes:
#   kube-api-access-sfffp:
#     Type:                    Projected (a volume that contains injected data from multiple sources)
#     TokenExpirationSeconds:  3607
#     ConfigMapName:           kube-root-ca.crt
#     ConfigMapOptional:       <nil>
#     DownwardAPI:             true
# QoS Class:                   BestEffort
# Node-Selectors:              katacontainers.io/kata-runtime=true
# Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
#                              node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
# Events:
#   Type    Reason          Age   From     Message
#   ----    ------          ----  ----     -------
#   Normal  AddedInterface  13s   multus   Add eth0 [10.244.1.12/24] from cbr0
#   Normal  Pulling         9s    kubelet  Pulling image "storytel/alpine-bash-curl:latest"
#   Normal  Pulled          6s    kubelet  Successfully pulled image "storytel/alpine-bash-curl:latest" in 2.241s (2.241s including waiting). Image size: 6089404 bytes.
#   Normal  Created         6s    kubelet  Created container bash-curl
#   Normal  Started         6s    kubelet  Started container bash-curl
# pod "aa-test-cc" deleted
# DEBUG: system logs of node 'kata-k8s-worker-0' since test start time (2024-04-25 18:47:40)
# -- Logs begin at Thu 2024-04-25 17:19:35 UTC, end at Thu 2024-04-25 18:48:01 UTC. --
# Apr 25 18:47:45 kata-k8s-worker-0 kata[30136]: time="2024-04-25T18:47:45.445875602Z" level=info msg="loaded configuration" file=/opt/kata/share/defaults/kata-containers/configuration-qemu-coco-dev.toml format=TOML name=containerd-shim-v2 pid=30136 sandbox=3d5bef45c2d94d059bae536af2667e63d5da624f4b4f3c60881b62ea9de8daa6 source=katautils

<SNIP>

# Apr 25 18:47:58 kata-k8s-worker-0 kata[30136]: [0;38;5;245m[0;1;31m[0;38;5;245mtime="2024-04-25T18:47:58.834456951Z" level=debug msg="State() end" container=3d5bef45c2d94d059bae536af2667e63d5da624f4b4f3c60881b62ea9de8daa6 name=containerd-shim-v2 pid=30136 sandbox=3d5bef45c2d94d059bae536af2667e63d5da624f4b4f3c60881b62ea9de8daa6 source=containerd-kata-shim-v2[0m
# Apr 25 18:47:58 kata-k8s-worker-0 kata[30136]: [0;38;5;245m[0;1;31m[0;38;5;245mtime="2024-04-25T18:47:58.83475414Z" level=debug msg="Delete() start" container=3d5bef45c2d94d059bae536af2667e63d5da624f4b4f3c60881b62ea9de8daa6 name=containerd-shim-v2 pid=30136 sandbox=3d5bef45c2d94d059bae536af2667e63d5da624f4b4f3c60881b62ea9de8daa6 source=containerd-kata-shim-v2[0m
# Apr 25 18:47:58 kata-k8s-worker-0 kata[30136]: [0;38;5;245m[0;1;31m[0;38;5;245mtime="2024-04-25T18:47:58.86709201Z" level=debug msg="Delete() end" container=3d5bef45c2d94d059bae536af2667e63d5da624f4b4f3c60881b62ea9de8daa6 name=containerd-shim-v2 pid=30136 sandbox=3d5bef45c2d94d059bae536af2667e63d5da624f4b4f3c60881b62ea9de8daa6 source=containerd-kata-shim-v2[0m
# Apr 25 18:47:58 kata-k8s-worker-0 kata[30136]: [0;38;5;245m[0;1;31m[0;38;5;245mtime="2024-04-25T18:47:58.867419251Z" level=debug msg="Shutdown() start" container=3d5bef45c2d94d059bae536af2667e63d5da624f4b4f3c60881b62ea9de8daa6 name=containerd-shim-v2 pid=30136 sandbox=3d5bef45c2d94d059bae536af2667e63d5da624f4b4f3c60881b62ea9de8daa6 source=containerd-kata-shim-v2[0m
# Apr 25 18:47:58 kata-k8s-worker-0 kata[30136]: [0;38;5;245m[0;1;31m[0;38;5;245mtime="2024-04-25T18:47:58.867478753Z" level=debug msg="Shutdown() end" container=3d5bef45c2d94d059bae536af2667e63d5da624f4b4f3c60881b62ea9de8daa6 name=containerd-shim-v2 pid=30136 sandbox=3d5bef45c2d94d059bae536af2667e63d5da624f4b4f3c60881b62ea9de8daa6 source=containerd-kata-shim-v2[0m
[run_kubernetes_tests.sh:110] INFO: NAMESPACE       NAME                                          READY   STATUS      RESTARTS   AGE
autorules       autoruler-5ff4dbbf7-rtpz6                     1/1     Running     0          88m
coco-tenant     kbs-546c498b6c-zrnb5                          1/1     Running     0          47m
ingress-nginx   ingress-nginx-admission-create-6cp76          0/1     Completed   0          88m
ingress-nginx   ingress-nginx-admission-patch-l4s8z           0/1     Completed   0          88m
ingress-nginx   ingress-nginx-controller-5cdfb74dc-8fxw9      1/1     Running     0          88m
kube-flannel    kube-flannel-ds-54mkv                         1/1     Running     0          83m
kube-flannel    kube-flannel-ds-ck5zp                         1/1     Running     0          88m
kube-system     coredns-7db6d8ff4d-tmkdq                      1/1     Running     0          88m
kube-system     coredns-7db6d8ff4d-zjzj4                      1/1     Running     0          88m
kube-system     etcd-kata-k8s-ctlplane-0                      1/1     Running     0          88m
kube-system     kata-deploy-w56vs                             1/1     Running     0          68m
kube-system     kube-apiserver-kata-k8s-ctlplane-0            1/1     Running     0          88m
kube-system     kube-controller-manager-kata-k8s-ctlplane-0   1/1     Running     0          88m
kube-system     kube-multus-ds-tvcnl                          1/1     Running     0          83m
kube-system     kube-multus-ds-v68hd                          1/1     Running     0          88m
kube-system     kube-proxy-9xh72                              1/1     Running     0          83m
kube-system     kube-proxy-fj7ww                              1/1     Running     0          88m
kube-system     kube-scheduler-kata-k8s-ctlplane-0            1/1     Running     0          88m
nydus-system    nydus-snapshotter-pwtnw                       1/1     Running     0          72m
[run_kubernetes_tests.sh:111] INFO: Executing k8s-confidential.bats
1..1
ok 1 Test unencrypted confidential container launch success and verify that we are running in a secure enclave. # skip Test not supported for qemu-coco-dev.
# [bats-exec-test:59] INFO: k8s configured to use runtimeclass
# error: arguments in resource/name form must have a single resource and name
# Error from server (NotFound): error when deleting "/home/wmoschet/src/github.com/kata-containers/kata-containers/tests/integration/kubernetes/runtimeclass_workloads_work/pod-confidential-unencrypted.yaml": services "confidential-unencrypted" not found
# Error from server (NotFound): error when deleting "/home/wmoschet/src/github.com/kata-containers/kata-containers/tests/integration/kubernetes/runtimeclass_workloads_work/pod-confidential-unencrypted.yaml": deployments.apps "confidential-unencrypted" not found
~/src/github.com/kata-containers/kata-containers/tests/integration/kubernetes
~/src/github.com/kata-containers/kata-containers

```

**Comment by fitzthum** [comment]
> would make sense to have agent.guest_components_rest_api=resource already set on configuration.toml's kernel_params?

Yes

**Comment by wainersm** [comment]
Only added a fix to make `.github/workflows/kata-runtime-classes-sync.yaml` happy.

**Comment by wainersm** [comment]
> > would make sense to have agent.guest_components_rest_api=resource already set on configuration.toml's kernel_params?
> 
> Yes

What about TDX and SNP configurations? Perhaps this is change for another PR before discussing a little bit more as I wanted to keep qemu-coco-dev as similar as possible to the TEE configurations.

**Comment by fitzthum** [comment]
> What about TDX and SNP configurations? Perhaps this is change for another PR before discussing a little bit more as I wanted to keep qemu-coco-dev as similar as possible to the TEE configurations.

I would enable it there too, although that could be in a different PR I guess.

**Comment by stevenhorsman** [comment]
Sorry I'm late to the party here:

> @fitzthum would make sense to have agent.guest_components_rest_api=resource already set on configuration.toml's kernel_params?

It's worth noting that that should we the default value, so I'm not sure this is essential?

@stevenhorsman remember the measured boot feature? I was considering have it enabled by default so that it will be tested (currently it's tested with tdx only IIRC) ... what do you think? But perhaps in a follow up PR...

I think we need to re-visit the follow on task to make that change more practical, but I can see an argument to use it in this config.

**Comment by wainersm** [comment]
@fitzthum @stevenhorsman thanks for the input! I think I will keep the config as is on this PR; work on a follow up.

**Comment by fitzthum** [comment]
> It's worth noting that that should we the default value, so I'm not sure this is essential?

Yeah, I was looking at the code yesterday. Resource is the default value, but I wasn't sure if it would be set if the arg wasn't there at all. It doesn't seem like there is a unit test for that case and we still set the value in the attestation test. I took a really quick look so I may have missed something. I am in favor of it being the default.

**Comment by stevenhorsman** [comment]
> > It's worth noting that that should we the default value, so I'm not sure this is essential?
> 
> Yeah, I was looking at the code yesterday. Resource is the default value, but I wasn't sure if it would be set if the arg wasn't there at all. It doesn't seem like there is a unit test for that case and we still set the value in the attestation test. I took a really quick look so I may have missed something. I am in favor of it being the default.

Maybe I misinterpreted how the code works when I added it, but my understanding is:
- There are dozens of unit tests cases that don't specify `agent.guest_components_rest_api` in the content -and they check that the value is `GuestComponentsFeatures::default()`: `https://github.com/kata-containers/kata-containers/blob/f72c6ba8145a701b2cad7994d4e52a3be3570f98/src/agent/src/config.rs#L539`
- I set the default for the enum to be resources: https://github.com/kata-containers/kata-containers/blob/f72c6ba8145a701b2cad7994d4e52a3be3570f98/src/agent/src/config.rs#L71-L72

Saying that I don't have any issues with explicitly setting it in the configuration (I left it there for the attestation tests as I think it provides a bit more assurance for people without having to dig into the code/doc), but wanted to confirm that it shouldn't cause any issues.

**Review by stevenhorsman — APPROVED** [review]
LGTM and simplifies the test non-hypervisor code nicely. Let's hope the tests pass, which I guess we won't know until it merges as the change is in the workflow!

**Comment by wainersm** [comment]
Only rebased to pick up the bump of golang version; this should fix the run-containerd-tests job.

**Pull request merged**
