### PR TITLE
versions: Udpate Cloud Hypervisor to 55479a64d237

### PR DESCRIPTION
**Pull request by fidencio**
Let's update cloud-hypervisor to a version that exposes the TDx support
via the OpenAPI's auto-generated code.

Fixes: #3663

Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @fidencio.

lgtm

**Comment by fidencio** [comment]
Hmmm.
```
17:55:16 HEAD is now at 55479a64 openapi: Expose TDx configuration
17:55:16 ./scripts/dev_cli.sh: line 121: docker: command not found
17:55:16 [Cloud Hypervisor] Error pulling container image. Aborting.
17:55:16 [install_cloud_hypervisor.sh:41] ERROR: /home/jenkins/workspace/workspace/kata-containers-2.0-vfio-PR/go/src/github.com/kata-containers/kata-containers/tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh
17:55:16 [jenkins_job_build.sh:208] ERROR: sudo -E PATH=/home/jenkins/workspace/workspace/kata-containers-2.0-vfio-PR/go/bin:/usr/local/go/bin:/usr/sbin:/sbin:/home/jenkins/workspace/workspace/kata-containers-2.0-vfio-PR/go/bin:/usr/local/go/bin:/usr/sbin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin .ci/install_cloud_hypervisor.sh
17:55:16 Failed at /home/jenkins/ci_entry_point.sh +91: .ci/jenkins_job_build.sh "${repo_to_test}"
17:55:16 ++ handle_error 91
17:55:16 ++ local exit_code=127
17:55:16 ++ local line_number=91
17:55:16 ++ echo 'Failed at /home/jenkins/ci_entry_point.sh +91: .ci/jenkins_job_build.sh "${repo_to_test}"'
17:55:16 ++ exit 127
```

**Review by devimc — APPROVED** [review]
thanks @fidencio

**Comment by fidencio** [comment]
As https://github.com/kata-containers/tests/pull/4456 got merged, let me /retest-vfio

**Pull request merged**
