### PR TITLE
kata-ctl: Move GuestProtection code to kata-sys-util

### PR DESCRIPTION
**Pull request by amshinde**
Move the GuestProtection code in kata-ctl to the src/libs/kata-sys-util crate to allow it to be consumed by other components.

Fixes: #7144

This is wip as it depends on https://github.com/kata-containers/kata-containers/pull/6726. This PR includes a commit from PR 6726 to make this work in order to make use of cpu utilities from kata-sys-util.

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @amshinde - please could you rebase to resolve the conflict?

**Review by jodh-intel — APPROVED** [review]
Thanks @amshinde.

lgtm

**Review by cmaf — APPROVED** [review]

**Pull request merged**
