### PR TITLE
agent: update cargo.lock

### PR DESCRIPTION
**Pull request by danmihai1**
Update Kata Agent's Cargo.lock after the recent changes to Cargo.toml.

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks @danmihai1!

**Comment by sprt** [comment]
How come the CI didn't catch this in the affected PR? What was it?

**Comment by danmihai1** [comment]
> How come the CI didn't catch this in the affected PR? What was it?

It was the last PR that changed Cargo.toml. Cargo.lock gets automatically re-generated if it's not good enough for the latest Cargo.toml, when cargo is building the Agent code, and I guess CI doesn't check that the file changed during build. 

(I have seen similar issues in the past, when agent/Cargo.toml has changed - this is not a new type of issue for Kata)

**Review by gkurz — APPROVED** [review]
`cargo clippy` doesn't generate further changes after this PR. Thanks @danmihai1 !

**Pull request merged**
