### PR TITLE
gpu: fix build guest kernel with gpu

### PR DESCRIPTION
**Pull request by Jimmy-Xu**
Some fixes for Nvidia GPU
1. Running `./build-kernel.sh -v 5.10.25 -g nvidia -f setup` fails
2. Building nvidia driver in kata container fails

Fixes and Related: 
https://github.com/kata-containers/kata-containers/issues/3380 
https://github.com/kata-containers/kata-containers/issues/9143
https://github.com/kata-containers/kata-containers/issues/5183

### CODE REVIEW

**Review by Apokleos — APPROVED** [review]
Thx @Jimmy-Xu Please format the PR with adding "Fixes" in commit message.

anyway, LGTM !

**Review by justxuewei — APPROVED** [review]
Lgtm, thanks!

**Comment by justxuewei** [comment]
`signed-off-by` info should be appened at the end.

**Comment by fidencio** [comment]
@Jimmy-Xu, please bump https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kernel/kata_config_version as well.

**Comment by zvonkok** [comment]
Before merging this I want to check on a internal bug about this issue. https://github.com/NVIDIA/open-gpu-kernel-modules/issues/391

**Comment by Jimmy-Xu** [comment]
The following guest kernel were tested:

**5.10.25**
```
cd  $GOPATH/src/github.com/kata-containers/kata-containers/tools/packaging/kernel

# Generate kernel config
$ ./build-kernel.sh -v 5.10.25 -g nvidia -f setup

# Building NVIDIA driver under kernel 5.10.25 requires CONFIG_X86_PAT 
$ grep CONFIG_X86_PAT kata-linux-5.10.25-126/.config
CONFIG_X86_PAT=y
```

**5.4.180**
```
$ rm -f ./patches/5.4.x/{0002-ACPI-Always-build-evged-in.patch,0003-5.4.x-PTP_KVM-support-for-arm-arm64.patch}
$ ./build-kernel.sh -v 5.4.180 -g nvidia -f setup 
$ grep CONFIG_X86_PAT kata-linux-5.4.180-126/.config
CONFIG_X86_PAT=y
```

**4.19.73**
```
$ rm -f ./patches/4.19.x/0005-arm64-backport-Arm64-KVM-Dynamic-IPA-and-52bit-IPA-s.patch
$ ./build-kernel.sh -v 4.19.73 -g nvidia -f setup
$ grep CONFIG_X86_PAT kata-linux-4.19.73-126/.config
CONFIG_X86_PAT=y
```

**Comment by Jimmy-Xu** [comment]
Test build the guest linux kernel on CentOS 7.9 x86_64

**Build step:**
```
cd $GOPATH/src/github.com/kata-containers/kata-containers/tools/packaging/kernel

# Example
## Generate kernel config
$ ./build-kernel.sh -v 5.10.25 -g nvidia -f  setup

## Building NVIDIA drivers for kernel 5.8+ in kata container requires CONFIG_X86_PAT
## (https://bugs.launchpad.net/ubuntu/+source/linux-kvm/+bug/1922800)
$ grep CONFIG_X86_PAT kata-linux-5.10.25-126/.config
CONFIG_X86_PAT=y

## Build guest kernel
./build-kernel.sh -v 5.10.25 -g nvidia build
```


**Result:**

| kernel version              | setup  | build  |
|-----------------------|--------|--------|
| 4.19.1, 4.19.86              | passed | passed |
| 5.4.180, 5.4.209           | passed | passed |
| 5.10.25                          | passed | passed |
| 5.13.19                          | passed | passed |
| 5.15.109                        | passed | passed |
| 5.16.20                          | passed | passed |
| 5.19.17                           | passed | passed |
| 6.1.52                             | passed | passed |
| 6.7.1                                | passed | passed |


**Notes:**
If applying the patch fails, try removing the patch and trying again:
- for 4.19.x: `rm -f ./patches/4.19.x/0005-arm64-backport-Arm64-KVM-Dynamic-IPA-and-52bit-IPA-s.patch`
- for 5.4.x: `rm -f ./patches/5.4.x/{0002-ACPI-Always-build-evged-in.patch,0003-5.4.x-PTP_KVM-support-for-arm-arm64.patch}`

**Review by zvonkok — APPROVED** [review]
LGTM, thanks!

**Comment by justxuewei** [comment]
@Jimmy-Xu There are some issues in static check CI. Please take a look at this.

**Pull request merged**
