### PR TITLE
CI: Set docker version to v20.10 in ubuntu:20.04 for s390x|ppc64le

### PR DESCRIPTION
**Pull request by stevenhorsman**
This is to make a docker version to v20.10 in docker upstream image ubuntu:20.04 for s390x and ppc64le.

Fixes: #6211
Signed-off-by: Hyounggyu Choi <Hyounggyu.Choi@ibm.com>
Cherry-picked: f49b89b

### CODE REVIEW

**Comment by stevenhorsman** [comment]
@arronwy - if you can check the TDX jobs for this as well that would be appreciated!

**Comment by ryansavino** [comment]
@arronwy Any update here on the tdx jobs? We got a couple PRs waiting on this one in order to validate the s390x tests. Thanks!

**Comment by fidencio** [comment]
We're facing:
```
04:12:38 INFO: Initialize the test environment
04:12:38 [init.sh:319] INFO: Check there aren't dangling processes from previous tests
04:12:39 3215827
04:12:39 3216936
04:12:39 3217635
04:12:39 ERROR: Found unexpected /bin/containerd-shim-kata-v2 present
04:12:39 
```

This is happening before running the tests due to some job that's not related.

I'm giving my approval and want to move on on this, with the agreement the same can be done when other vendors CIs end up broken on things that are not related to the patches. :-)

**Review by fidencio — APPROVED** [review]
lgtm, thanks @stevenhorsman!

**Pull request merged**
