### PR TITLE
kernel: remove depricated CONFIG_ND_BLK

### PR DESCRIPTION
**Pull request by Alex-Carter01**
Fragment included config depricated as of this commit:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?id=f8669f1d6a86a6b17104ceca9340ded280307ac1

Fixes: kata-containers#4848
Signed-off-by: Alex Carter <alex.carter@ibm.com>

### CODE REVIEW

**Comment by ManaSugi** [comment]
@Alex-Carter01 Thank you.
Could you also update the [kata_config_version](https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kernel/kata_config_version)?

**Comment by Alex-Carter01** [comment]
config version incremented.

Thank you @ManaSugi, I was not aware of this convention

**Comment by fidencio** [comment]
This one got superseded by https://github.com/kata-containers/kata-containers/pull/4861, thus I'm closing it.

**Pull request closed without merging**
