### PR TITLE
docs: Adding hyperlink to virtio-net in kata documentation 2.0

### LINKED ISSUE #612: Clarifying virtio net in the virtualization documentation 2.0
# Description of problem

In the kata virtualization document virtio net is mentioned however no link is provided to what it means (as part of the different virtio block). A lot of work has been done in the past year by the virtio-networking community to help reader understand this block.

This is a duplicate of [#709](https://github.com/kata-containers/documentation/issues/709)

# Expected result

A link to relevant material describing virtio net

# Actual result

No such link :-).

### PR DESCRIPTION
**Pull request by ariel-adam**
Referring virtio-net mentioning in the kata virtualization
documentation to the virtio-networking blog series published
and explaining how it works.

Fixes #612

Signed-off-by: Ariel Adam <aadam@redhat.com>

### CODE REVIEW

**Comment by ariel-adam** [comment]
@jodh-intel do I need to retest or does that happen automatically ?

**Review by GabyCT — APPROVED** [review]

**Comment by fidencio** [comment]
`continuous-integration/travis-ci/pr` is failing because of:
```
INFO: Spell checking file 'docs/design/virtualization.md'
WARNING: Word 'implementor': did you mean one of the following?: OpenTelemetry
WARNING: Word 'implementor': did you mean one of the following?: OpenTelemetry
ERROR: Spell check failed for file: 'docs/design/virtualization.md'
INFO: spell check failed for document docs/design/virtualization.md
ERROR: spell check failed, See https://github.com/kata-containers/documentation/blob/master/Documentation-Requirements.md#spelling for more information.
The command "ci/static-checks.sh" exited with 1.
```

The word is not used in this PR, but it's present in the filed changed.

Do I understand correctly that fixing this would be a matter of adding the "implementor" word to the dictionary, as recommended by https://github.com/kata-containers/tests/tree/master/cmd/check-spelling#adding-a-new-word ?

**Comment by jodh-intel** [comment]
@fidencio - This seems to be more fall out from #811.

But the fix is easy - [the word actually ends in "er"](https://en.wiktionary.org/wiki/implementer), so to avoid adding a custom word, just correct the spelling :smile:

**Comment by fidencio** [comment]
@ariel-adam, based on James' comment, could you add a new commit to this PR, fix the spelling of the "implementor" word? The following diff should be enough.

```
diff --git a/docs/design/virtualization.md b/docs/design/virtualization.md
index b019993b..67b48099 100644
--- a/docs/design/virtualization.md
+++ b/docs/design/virtualization.md
@@ -22,10 +22,10 @@ the multiple hypervisors and virtual machine monitors that Kata supports.
 ## Mapping container concepts to virtual machine technologies
 
 A typical deployment of Kata Containers will be in Kubernetes by way of a Container Runtime Interface (CRI) implementation. On every node,
-Kubelet will interact with a CRI implementor (such as containerd or CRI-O), which will in turn interface with Kata Containers (an OCI based runtime).
+Kubelet will interact with a CRI implementer (such as containerd or CRI-O), which will in turn interface with Kata Containers (an OCI based runtime).
 
 The CRI API, as defined at the [Kubernetes CRI-API repo](https://github.com/kubernetes/cri-api/), implies a few constructs being supported by the
-CRI implementation, and ultimately in Kata Containers. In order to support the full [API](https://github.com/kubernetes/cri-api/blob/a6f63f369f6d50e9d0886f2eda63d585fbd1ab6a/pkg/apis/runtime/v1alpha2/api.proto#L34-L110) with the CRI-implementor, Kata must provide the following constructs:
+CRI implementation, and ultimately in Kata Containers. In order to support the full [API](https://github.com/kubernetes/cri-api/blob/a6f63f369f6d50e9d0886f2eda63d585fbd1ab6a/pkg/apis/runtime/v1alpha2/api.proto#L34-L110) with the CRI-implementer, Kata must provide the following constructs:
 
 ![API to construct](./arch-images/api-to-construct.png)
 
```

Please, add that as a new commit as part of the same pull-request.

**Comment by ariel-adam** [comment]
I've fixed this typo however I didn't insert it so I wander why did it fail on my commit :-)....

**Comment by jodh-intel** [comment]
Thanks @ariel-adam - for the explanation, see https://github.com/kata-containers/kata-containers/pull/855#issuecomment-703697615.

/test

**Comment by fidencio** [comment]
I personally would prefer having the typo fixed in a **new** commit, as mentioned https://github.com/kata-containers/kata-containers/pull/855#issuecomment-703701095.

The reason for that is to try to have commits that are fixing one specific issue and, later on, could be traced and pointed out more easily.

However, if having the fix for the spelling squashed into this commit is fine for the other maintainers, I will **not** block it to be merged.

**Comment by ariel-adam** [comment]
@jodh-intel @fidencio Split it to 2 commits.

**Comment by jodh-intel** [comment]
Thanks @ariel-adam. However, Travis is failing and if you look at the log it's because one of your commits is lacking a sign-off - see: https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#certificate-of-origin.

**Comment by amshinde** [comment]
@ariel-adam Needs a "Signed-off" on one of your commits.

**Comment by c3d** [comment]
@ariel-adam Reminder you need to sign-off 

```
12  0b33c204844103afef4de114613959e25e872304    The sign-off is missing.
13
14  What should I do to fix it ?
15
16  All proposed commits should include a Signed-Off-By: <your-email-address> line in their commit message.
17  This is most conveniently done by using --signoff (-s) when running git commit.
```

**Comment by c3d** [comment]
Closing, I took this PR over at the request of @ariel-adam and I have transferred it to #1121.

**Pull request closed without merging**
