### PR TITLE
stable-2.3: add VFIO kernel dependencies for ppc64le

### PR DESCRIPTION
**Pull request by Amulyam24**
Recently added VFIO kernel configs require addtional
dependencies on pcc64le.

Fixes: #2991

Signed-off-by: Amulyam24 <amulmek1@in.ibm.com>

### CODE REVIEW

**Review by gkurz — APPROVED** [review]
Thanks @Amulyam24 !

**Comment by fidencio** [comment]
/retest-fedora

```
[reset] Reading configuration from the cluster...
[reset] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
[preflight] Running pre-flight checks
The 'update-cluster-status' phase is deprecated and will be removed in a future release. Currently it performs no operation
[reset] Stopping the kubelet service
[reset] Unmounting mounted directories in "/var/lib/kubelet"
Build timed out (after 5 minutes). Marking the build as aborted.
Build was aborted
Performing Post build task...
Match found for :.* : True
Logical operation result is TRUE
Running script  : #!/bin/bash

export GOPATH=$WORKSPACE/go
export GOROOT="/usr/local/go"
export PATH=${GOPATH}/bin:/usr/local/go/bin:/usr/sbin:/usr/local/bin:${PATH}

cd $GOPATH/src/github.com/kata-containers/tests
.ci/teardown.sh "$WORKSPACE/artifacts"
[kata-containers-2.0-fedora-PR] $ /bin/bash /tmp/jenkins7442511625111558914.sh
Terminated
[jenkins_job_build.sh:215] ERROR: ci/run.sh
++ handle_error 84
++ local exit_code=143
++ local line_number=84
++ echo 'Failed at /tmp/jenkins/workspace/kata-containers-2.0-fedora-PR/ci_entry_point.sh +84: .ci/jenkins_job_build.sh "${repo_to_test}"'
Failed at /tmp/jenkins/workspace/kata-containers-2.0-fedora-PR/ci_entry_point.sh +84: .ci/jenkins_job_build.sh "${repo_to_test}"
++ exit 143
```
cc @snir911 @c3d

**Comment by fidencio** [comment]
This is a backport of https://github.com/kata-containers/kata-containers/pull/2992

**Comment by fidencio** [comment]
I am assuming we don´t need to bump the config as it's related to the last config bump.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @Amulyam24!

**Review by amshinde — APPROVED** [review]

**Pull request merged**
