### PR TITLE
rootfs: build OPA binary from source for ppc64le and s390x

### PR DESCRIPTION
**Pull request by BbolroC**
This PR is to build a binary for OPA from source code for ppc64le and s390x.

Fixes: #7616

Signed-off-by: Hyounggyu Choi <Hyounggyu.Choi@ibm.com>

### CODE REVIEW

**Comment by BbolroC** [comment]
@danmihai1  Please check out a discussion for this PR:  https://katacontainers.slack.com/archives/C879ACQ00/p1693216957300559

**Review by jodh-intel — APPROVED** [review]
Thanks @BbolroC.

**Pull request merged**
