### PR TITLE
metrics: Fix check results for tensorflow benchmark

### LINKED ISSUE #7684: metrics: Fix check results for tensorflow benchmark

### PR DESCRIPTION
**Pull request by GabyCT**
This PR fixes the check results for tensorflow benchmark now that we change the name of the test.

Fixes #7684

### CODE REVIEW

**Review by chavafg — APPROVED** [review]

**Comment by dborquez** [comment]
Looks good, but I also suggest to patch the `gha_run.sh` script to update the name of the test:
https://github.com/kata-containers/kata-containers/blob/4ba684e6e460d022108f7bb80024c65ceb67c10b/tests/metrics/gha-run.sh#L83

**Review by dborquez — CHANGES_REQUESTED** [review]
Please update the name of the test in the `gha_run.sh` script:
https://github.com/kata-containers/kata-containers/blob/4ba684e6e460d022108f7bb80024c65ceb67c10b/tests/metrics/gha-run.sh#L83

**Review by dborquez — APPROVED** [review]

**Pull request merged**
