### PR TITLE
osbuilder: add pkg bash for alpine

### PR DESCRIPTION
**Pull request by cheriL**
Fix: #8447

### CODE REVIEW

**Comment by fidencio** [comment]
I've approved this, but you'll need to re-work the PR to properly add a commit message explaining why we're adding the `bash` component into the alpine rootfs / initrd.

Please, do that and our CI will then be happy.

**Review by cmaf — COMMENTED** [review]
@cheriL could you also make sure the Fixes line is in the commit (following the [contributing guide](https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#closing-issues))

**Comment by cheriL** [comment]
Sure @fidencio @cmaf !   Done.

**Review by amshinde — APPROVED** [review]

**Comment by fidencio** [comment]
@cheriL, can we have this one rebased again?  Sorry, for inconvenience.

**Pull request merged**
