### PR TITLE
kata-deploy: Remove kata-deploy-docker.sh

### PR DESCRIPTION
**Pull request by fidencio**
Kata Containers 2.x is not supported outside of the kubernetes world.
With this in mind, let's remove leftovers from the 1.x deployments &
documentation.

Fixes: #1356

Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>

### CODE REVIEW

**Comment by egernst** [comment]
Not appropriate I'm sure, but I actually use it to install it onto a dev host quickly for testing with ctr, etc.

I don't use it w/ Docker (so the conf update is garbage), but I do use it as a way to quickly to the cp to /opt/kata/

**Comment by fidencio** [comment]
> Not appropriate I'm sure, but I actually use it to install it onto a dev host quickly for testing with ctr, etc.
> 
> I don't use it w/ Docker (so the conf update is garbage), but I do use it as a way to quickly to the cp to /opt/kata/

I'd be more than happy with an issue, even if blocking this one, about adding a kata-deploy-ctr.sh script.

**Review by likebreath — APPROVED** [review]

**Review by liubin — APPROVED** [review]

**Pull request merged**
