### PR TITLE
trace-forwarder/agent-ctl: run cargo fmt/clippy in make check

### PR DESCRIPTION
**Pull request by liubin**
Add make check to run cargo fmt/clippy
for Rust projects.

Fixes: #3656

Signed-off-by: bin <bin@hyper.sh>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @liubin.

lgtm

**Review by fidencio — APPROVED** [review]
lgtm, thanks @liubin!

**Review by lifupan — APPROVED** [review]

**Pull request merged**
