### PR TITLE
main | release: Standardize kata static file name

### PR DESCRIPTION
**Pull request by singhwang**
release: Standardize kata static file name

The string representing the architecture aarch64 and x86_64 need to be changed to arm64 and amd64 for the release.

Fixes: #6986

Signed-off-by: Singh Wang <wangxin_0611@126.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @singhwang!

**Review by fidencio — APPROVED** [review]
lgtm, thanks @singhwang!

**Review by amshinde — APPROVED** [review]

**Comment by singhwang** [comment]
> Sorry, at the time you opened your PR we were having issues with our CI, which leads to required tests failing without having nothing to do with this PR.
> 
> AS this has been already fixed on main, we´d like to ask you to rebase your PR atop of the current `main` branch.
> 
> Thanks for the consideration, and sorry for the trouble.

ok, I’ll take care of it today.

**Comment by singhwang** [comment]
Please move to the new pr.
https://github.com/kata-containers/kata-containers/pull/6997

**Pull request closed without merging**
