### PR TITLE
kata-monitor: fix collecting metrics for sandboxes not started through CRI

### LINKED ISSUE #3705: kata-monitor does not see existing containers using containerd
As shown in https://github.com/kata-containers/tests/pull/4461#pullrequestreview-885873674, `kata-monitor` is not showing existing (running) containers for me:

```bash
$ /opt/kata/bin/kata-runtime --version
kata-runtime  : 2.3.2
   commit   : 1af292c9e693e9bc8e8324a9eb860dad45306fb5
   OCI specs: 1.0.2-dev
$ kata-monitor --version
kata-monitor
 Version:       0.2.0
 Go version:    go1.17.3
 Git commit:    1af292c9e693e9bc8e8324a9eb860dad45306fb5
 OS/Arch:       linux/amd64
$ containerd --version
containerd github.com/containerd/containerd v1.6.0 39259a8f35919a0d02c9ecc2871ddd6ccf6a7c6e
```

Check for sandboxes:

```
$ sudo ls -l /run/vc/sbs
total 0
drwx------ 3 root root 100 Feb 17 14:19 foo100
```

Start the monitor:

```bash
$ sudo kata-monitor -log-level trace
INFO[0000] announce                                      app=kata-monitor arch=amd64 git-commit=8d3ace4a7d36894084d5b2f66eca4efe4eafb0ba go-version=go1.16.9 listen-address=":8090" log-level=trace os=linux runtime-endpoint=/run/containerd/containerd.sock version=0.2.0
DEBU[0000] started fs monitoring @/run/vc/sbs            name=kata-monitor pid=16974 source=kata-monitor
DEBU[0005] connect using endpoint 'unix:///run/containerd/containerd.sock' with '3s' timeout  name=kata-monitor pid=16974 source=kata-monitor
DEBU[0005] connected successfully using endpoint: unix:///run/containerd/containerd.sock  name=kata-monitor pid=16974 source=kata-monitor
DEBU[0005] ListPodSandboxRequest: &ListPodSandboxRequest{Filter:&PodSandboxFilter{Id:,State:&PodSandboxStateValue{State:SANDBOX_READY,},LabelSelector:map[string]string{},},}  name=kata-monitor pid=16974 source=kata-monitor
DEBU[0005] ListPodSandboxResponse: &ListPodSandboxResponse{Items:[]*PodSandbox{},}  name=kata-monitor pid=16974 source=kata-monitor
INFO[0005] synced sandbox cache with the container engine  count=0 name=kata-monitor pid=16974 source=kata-monitor
DEBU[0005] dump sandbox cache                            name=kata-monitor pid=16974 sandboxes="map[]" source=kata-monitor
```

Check for sandboxes

```bash
$ curl -s localhost:8090/sandboxes
$
```

Additional info:

- Tested with `kata-monitor` in the 2.3.2 release and `main`'s `HEAD`.
- I see the same behaviour with QEMU and CH.

### PR DESCRIPTION
**Pull request by fgiudici**
This PR targets to:
1) fix #3705
2) rename symbols and labels containing "Kube" to "CRI": the collection of CRI metadata we just added belong to CRI spec, not kubernetes. Any CRI consumer will get those labels (renamed to cri_name, cri_namespace and cri_uid).
3) bump kata-monitor version: we don't stick to the kata shim version, as kata-monitor should usually work with older and newer shim releases. We want anyway have a new version in kata-monitor binary we release as from commit #7516a8c51b40e5b84b46f1888b2337c50e1acce5  we now totally rely on FS events. May be useful for debugging.

What is still missing is giving-up when trying to retrieve CRI metadata: if the sandbox has not been created through CRI (e.g., containerd 'ctr run') we will keep polling containerd CRI interface. While I plan to address this very soon, I think would be better if we merge this PR before we release kata 2.4.0-rc0: the changes here are very limited.

### CODE REVIEW

**Comment by fgiudici** [comment]
Hey @fidencio, @jodh-intel , @liubin! I was thinking could be good to merge this PR before releasing 2.4-rc0, mainly to change the new labels attached to metrics from kube_[name, namespace, uid] to cri_[name, namespace, uid] before having them in an official release. I kept the changes here very minimal for this reason.
Otherwise we can take all the time we may need and I would also add here a rework to make the CRI interface totally optional.
WDYT?

**Review by bergwolf — APPROVED** [review]
lgtm!

**Review by liubin — APPROVED** [review]

**Pull request merged**
