### PR TITLE
warning_fix: fix warnings when build with cargo-1.68.0

### PR DESCRIPTION
**Pull request by Apokleos**
Fixes: #6593

### CODE REVIEW

**Comment by Apokleos** [comment]
> Can you also update this https://github.com/kata-containers/kata-containers/blob/main/versions.yaml#L320-L325 ?

Fixed

**Review by studychao — APPROVED** [review]
Thanks @Apokleos ,that helps a lot.

**Comment by studychao** [comment]
@Apokleos There is one clippy warning in your PR. Please help fix it.

**Review by Tim-0731-Hzt — APPROVED** [review]

**Review by studychao — APPROVED** [review]
Thanks @Apokleos

**Review by quanweiZhou — APPROVED** [review]

**Pull request merged**
