### PR TITLE
versions: Bump rust toolchain

### PR DESCRIPTION
**Pull request by stevenhorsman**
- Bump the rust version to 1.75.0 as agreed on in the AC meeting

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Review by beraldoleal — APPROVED** [review]
LGTM, thanks

**Comment by stevenhorsman** [comment]
@gkurz - FYI - I checked and the current kata-agent (pre image-rs bump) has an MSRV of 1.69.0

**Comment by gkurz** [comment]
> @gkurz - FYI - I checked and the current kata-agent (pre image-rs bump) has an MSRV of 1.69.0

Thanks @stevenhorsman !

Strange because I get that with current main ab8a9882c18b8f058f4b91748492fde95b9836a3 when building with 1.69.0 :

```
error: package `home v0.5.9` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.69.0
```

I actually had to bump to 1.71.0 to be able to build :wink:

Just one request : can you push the lint and warning fixes before the version bump ? For the sake of bisectability.

**Review by zvonkok — APPROVED** [review]

**Comment by stevenhorsman** [comment]
Hi @gkurz - Are you happy with the commit order change?

**Pull request merged**
