### PR TITLE
docs: Repair inconsistencies between 2.0 and 1.x

### PR DESCRIPTION
**Pull request by c3d**
The documentation `how-to/how-to-set-sandbox-config-kata.md` contains a number
of differences relative to the 1.x variant, which do not seem to correspond to
missing features in the actual code.

Fixes: #1046

Signed-off-by: Christophe de Dinechin <dinechin@redhat.com>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @c3d!

**Review by devimc — APPROVED** [review]
thanks @c3d

**Comment by bergwolf** [comment]
@c3d Need rebase

**Comment by fidencio** [comment]
I'm really sorry for the disruption but in order to do the branch name changes announced [here](http://lists.katacontainers.io/pipermail/kata-dev/2021-January/001695.html) I'm adding the "do-not-merge" and the "needs-branch-adjustment" labels to the PR.

I'll add a new comment once the branch changes are done and once it happens I'd like to ask you to resubmit the PR against the new `main` branch, possibly linking to this PR in case you find the conversations / reviews already made important to proceed.

**Comment by fidencio** [comment]
Kata Containers repos are back to business.  Thanks a lot for your patience and I'm very happy to announce that there's no changes needed from your side as renaming the branches automagically reflected here.

If you notice something weird, some missing CI, please, do not hesitate on contacting us here or on #kata-dev on bit.ly/katacontainersslack.

Also, this is a good opportunity to have your PR rebased atop of `main`, to ensure your PR follow all the guidelines (https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format) enforced by this community, or even to re-evaluate whether the PR is currently needed.

Last but not least,  as the default branch has been renamed to `main`, if you have a local clone you'd need to update it and you do so by running:
```
git branch -m 2.0-dev main
git fetch origin
git branch -u origin/main main
```

Happy hacking!

**Comment by jodh-intel** [comment]
@c3d - Just a reminder that this branch is conflicted :smile:

**Comment by cmaf** [comment]
@c3d reminder that this is approved but has conflicts

**Comment by fidencio** [comment]
@c3d, any chance to have this one rebased?

**Comment by c3d** [comment]
Closing since this appears to have been merged in 1fc7b7641dc7021a554c1049094b2b14a57ea958 and was marked as conflicted for no good reason.

**Comment by fidencio** [comment]
Oh, interesting, it was already part of #1045.
Thanks acting on this one!

**Comment by c3d** [comment]
@fidencio  There is still a little bit of #1049 that seems missing though. I'm on it.

**Pull request closed without merging**
