### PR TITLE
gpu: Rename the last bits from `gpu` to `nvidia-gpu`

### PR DESCRIPTION
**Pull request by fidencio**
Let's specifically name the `gpu` runtime class as `nvidia-gpu`.  By
doing this we keep the door open and ease the life of the next vendor
adding GPU support for Kata Containers.

Fixes: #6553

### CODE REVIEW

**Review by wainersm — APPROVED** [review]
Thanks @fidencio !

Renaming gpu to nvidia-gpu is a right decision IMO.

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
