### PR TITLE
runtime-rs: add dbs-upcall feature

### PR DESCRIPTION
**Pull request by Tim-0731-Hzt**
add dbs-upcall feature to dragonball

Fixes:#5949
Signed-off-by: Zhongtao Hu <zhongtaohu.tim@linux.alibaba.com>

### CODE REVIEW

**Comment by Tim-0731-Hzt** [comment]
This is a test

**Review by studychao — APPROVED** [review]
Thanks, @Tim-0731-Hzt

**Review by liubin — APPROVED** [review]

**Pull request merged**
