### PR TITLE
docs: Adding hyperlink to virtio-net in kata documentation 2.0

### LINKED ISSUE #612: Clarifying virtio net in the virtualization documentation 2.0
# Description of problem

In the kata virtualization document virtio net is mentioned however no link is provided to what it means (as part of the different virtio block). A lot of work has been done in the past year by the virtio-networking community to help reader understand this block.

This is a duplicate of [#709](https://github.com/kata-containers/documentation/issues/709)

# Expected result

A link to relevant material describing virtio net

# Actual result

No such link :-).

### PR DESCRIPTION
**Pull request by ariel-adam**
Referring virtio-net mentioning in the kata virtualization
documentation to the virtio-networking blog series published
and explaining how it works.

Fixes #612

Signed-off-by: Ariel Adam <aadam@redhat.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm!

**Review by jodh-intel — APPROVED** [review]
Thanks @ariel-adam.

lgtm

**Comment by jodh-intel** [comment]
Hi @ariel-adam - The travis push CI check is failing. We can't restart that check and it is required so I think the options are to either re-push (`git push -f`) or click "close and comment" and then click "re-open" to re-trigger this check.

**Comment by ariel-adam** [comment]
CI failed on a doc fix (:-) ?)).
Re-triggering the CI

**Comment by ariel-adam** [comment]
@jodh-intel any idea why the CI is failing on this? What am I missing :-)?

**Comment by jodh-intel** [comment]
@ariel-adam - it looks like Travis is confused because your branch moved. I'm going to close and re-open the PR to see if that re-triggers Travis...

**Comment by jodh-intel** [comment]
Hmm. Well that "works" but we cannot clear the erroneous "continuous-integration/travis-ci/push" check. I think you'll have to close this PR and open a fresh one. You might want to rename your local branch to ensure it is different to this one:

```
$ git branch -m update-virt-doc2-0 update-virt-doc2-0-take-2
$ git push
```

**Comment by cmaf** [comment]
@ariel-adam could you create a new PR for this with a different local branch? We haven't been able to clear the continuous-integration/travis-ci/push check.

**Pull request closed without merging**
