### PR TITLE
dragonball: Uniform the spelling of Virtio

### PR DESCRIPTION
**Pull request by justxuewei**
The changes are:

- VirtIoError -> VirtioError
- VirtIoResult -> VirtioResult
- VirtIoDevice -> VirtioDevice

Fixes: #8464

### CODE REVIEW

**Review by Apokleos — APPROVED** [review]
Thx @justxuewei LGTM!

**Review by studychao — COMMENTED** [review]
This modification seems to break the naming convention of Rust
https://rust-lang.github.io/api-guidelines/naming.html

"In UpperCamelCase, acronyms and contractions of compound words count as one word: use Uuid rather than UUID, Usize rather than USize or Stdin rather than StdIn. In snake_case, acronyms and contractions are lower-cased: is_xid_start"

**Review by lifupan — APPROVED** [review]

**Review by studychao — CHANGES_REQUESTED** [review]
since 2 reviewers have ack this PR, I have to request the change.

**Comment by justxuewei** [comment]
Hi @studychao, I've changed `VirtIoXxx` to `VirtioXxx`. PTAL, thanks!

**Review by studychao — APPROVED** [review]
Thanks @justxuewei !

**Pull request merged**
