### PR TITLE
tools: Fix groupname if it differs from username

### PR DESCRIPTION
**Pull request by haslersn**

### CODE REVIEW

**Comment by jodh-intel** [comment]
Thanks for raising @haslersn. However, the static checks are failing as there is is no "`Fixes #XXX`" comment in your commit:

- https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format

As shown in the doc above, please also add a brief explanation of the change after the one line summary in your commit.

**Comment by haslersn** [comment]
Done

**Review by dborquez — APPROVED** [review]
LGTM,. thanks @haslersn

**Review by fidencio — APPROVED** [review]
lgtm, thanks @haslersn!

**Review by amshinde — APPROVED** [review]

**Pull request merged**
