### PR TITLE
runtime-rs: remove the version number from the commit display message

### PR DESCRIPTION
**Pull request by chentt10**
The displayed commit message and version message are partially duplicated. Remove the version number from the commit display message.

Fixes:#5735

Signed-off-by: Chen Taotao <chentt10@chinatelecom.cn>

### CODE REVIEW

**Comment by liubin** [comment]
@chentt10 Had you compared the changes between the original and modified version?

From the source, it seems that `VERSION_COMMIT` contains a version number like `3.0.0`

**Comment by chentt10** [comment]
> @chentt10 Had you compared the changes between the original and modified version?
> 
> From the source, it seems that `VERSION_COMMIT` contains a version number like `3.0.0`

Yes . `RUNTIME_VERSION_COMMIT` contains the version number and commit hash, so using the `containerd-shim-kata-v2 --version` command causes the `commit` message to contain the version number and commit hash, which is partially duplicated by the information contained in `version`, so this patch uses `RUNTIME_GIT_COMMIT` for `commit` and removes `RUNTIME_VERSION_COMMIT `. The following is a comparison of the before and after changes.

Original
```shell
# containerd-shim-kata-v2  --version
Kata Containers containerd shim: id: io.containerd.kata.v2, version: 3.1.0-alpha0, commit: 3.1.0-alpha0-06a604b75333cc489d70af1a01efb502d24ae8dc
```
After modification
```
# containerd-shim-kata-v2 --version
Kata Containers containerd shim: id: io.containerd.kata.v2, version: 3.1.0-alpha0, commit: 67fe703ff5dfd7a02dc94e8b746565819a5ed42b
```

**Review by liubin — APPROVED** [review]

**Comment by liubin** [comment]
PTAL @Tim-0731-Hzt @studychao 
/test

**Review by Tim-0731-Hzt — APPROVED** [review]
LGTM

**Pull request merged**
