### PR TITLE
RFC: Add a YAML representation of the available options

### PR DESCRIPTION
**Pull request by jodh-intel**
A YAML version of `configuration.toml` that encoded a *lot* more detail about each option.

Fixes: #494.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
A very early implementation of a potentially useful idea. Note the `categories` so that each option can affect positively (`+`) or negatively (`-`) such categories as `security`, `network-performance`, *etc*.

As a random example that includes some of the interesting fields:

```yaml
disable_vhost_net:
  description: |
    If `vhost-net` backend for `virtio-net` is not desired, set to
    true. Which trades off security (`vhost-net` runs ring0)
    for network I/O performance.
  type: boolean
  values:
    default: false
    impacts:
      - category: "+security"
      - category: "-network"
        impact-explanation: |
          If set to true security is theoretically improved (since
          `vhost-net` runs in CPU ring 0), although network I/O
          performance will be impacted.
        introduced: "1.3.0"
```

**Comment by jodh-intel** [comment]
Remember, it's an RFC (there are tons of "FIXME"'s :smile:)

**Comment by fidencio** [comment]
I'm really sorry for the disruption but in order to do the branch name changes announced [here](http://lists.katacontainers.io/pipermail/kata-dev/2021-January/001695.html) I'm adding the "do-not-merge" and the "needs-branch-adjustment" labels to the PR.

I'll add a new comment once the branch changes are done and once it happens I'd like to ask you to resubmit the PR against the new `main` branch, possibly linking to this PR in case you find the conversations / reviews already made important to proceed.

**Comment by fidencio** [comment]
Kata Containers repos are back to business.  Thanks a lot for your patience and I'm very happy to announce that there's no changes needed from your side as renaming the branches automagically reflected here.

If you notice something weird, some missing CI, please, do not hesitate on contacting us here or on #kata-dev on bit.ly/katacontainersslack.

Also, this is a good opportunity to have your PR rebased atop of `main`, to ensure your PR follow all the guidelines (https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format) enforced by this community, or even to re-evaluate whether the PR is currently needed.

Last but not least,  as the default branch has been renamed to `main`, if you have a local clone you'd need to update it and you do so by running:
```
git branch -m 2.0-dev main
git fetch origin
git branch -u origin/main main
```

Happy hacking!

**Comment by jodh-intel** [comment]
Closing as this was just an experiment.

**Pull request closed without merging**
