### PR TITLE
Update prometheus/procfs to support loongarch64

### PR DESCRIPTION
**Pull request by zhaixiaojuan**
This PR fixes TestAcrnCreateVM test failure on LoongArch64: https://github.com/kata-containers/kata-containers/issues/7830

### CODE REVIEW

**Comment by stevenhorsman** [comment]
Hey @zhaixiaojuan, thanks for the PR. It might be useful for you to take a look at the [contributing guide](https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#certificate-of-origin) and there are some things we required on commits, like DCO sign-off and a specific commit body format, which are detailed there. Let us know if you having any issues with finding these. Thanks!

**Comment by zhaixiaojuan** [comment]
@stevenhorsman 
Thank you so much, I have submitted the corresponding issu and modified the submission body format.
At the same time, I uploaded my local test results on x86 and loongarch64. For details, see: https://github.com/kata-containers/kata-containers/commit/4d101e2e53919db2c1b2b9976e6ca571e9af7fee

**Comment by zhaixiaojuan** [comment]
@stevenhorsman 
Hi, stevenhorsman, 
I fixed the static checks(make vendor) error.
I'm not sure if the errors with Add backport label, jenkins-ci-dragonball-ARM-ubuntu-20.04 and jenkins-ci-ubuntu-1804-cloud-hypervisor-k8s-containerd-2.0 need to be resolved.

Add backport label error:
```
    data: {
Error: Unhandled error: HttpError: Resource not accessible by integration
      message: 'Resource not accessible by integration',
      documentation_url: 'https://docs.github.com/rest/issues/comments#create-an-issue-comment'
    }
  },
```

jenkins-ci-dragonball-ARM-ubuntu-20.04 and jenkins-ci-ubuntu-1804-cloud-hypervisor-k8s-containerd-2.0 error:
```
URI: | /job/kata-containers-dragonball-ubuntu-Arm-20.04-PR/1344/
404
Not Found
Stapler
```

**Comment by stevenhorsman** [comment]
I'll re-run the tests and try and babysit the failing ones to see if I can get them to pass, or if there are underlying issues

**Comment by zhaixiaojuan** [comment]
@stevenhorsman 
Hi, stevenhorsman,
I don't think the remaining two failures need to be addressed. Now I need to wait for this PR to be reviewed, right?

**Comment by stevenhorsman** [comment]
> @stevenhorsman Hi, stevenhorsman, I don't think the remaining two failures need to be addressed. Now I need to wait for this PR to be reviewed, right?

I will try and re-run the metrics tests as they didn't used to be required as they were run in Jenkins as well, but I think that might have just changed.

**Comment by stevenhorsman** [comment]
Closing and re-opening to re-trigger the tests

**Comment by stevenhorsman** [comment]
@zhaixiaojuan - apologies, but it looks like we didn't managed to get the tests passing quick enough to get it in before another vendoring PR went in and caused a conflict. If you are able to rebase then let us know and we'll re-run the tests. Thanks!

**Comment by zhaixiaojuan** [comment]
@stevenhorsman I have resolved this conflict.

**Comment by zhaixiaojuan** [comment]
@stevenhorsman Hi, it now appears that the failure may have been caused by the build environment itself.

**Comment by stevenhorsman** [comment]
> @stevenhorsman Hi, it now appears that the failure may have been caused by the build environment itself.

Yes there is an issue that is blocking the CI, that is being worked on. Apologies for the inconvenience

**Review by stevenhorsman — APPROVED** [review]
The required tests are passing now, so this change LGTM. Thanks

**Comment by stevenhorsman** [comment]
Sorry this needs re-vendoring again :(

**Pull request closed without merging**
