### PR TITLE
kata-deploy: Update agent without rebuild all rootfs

### PR DESCRIPTION
**Pull request by jcvenegas**
For development one changing part may be agent, but not the full
guest rootfs. After update the agentm, if I do:
```
make rootfs-image-tarball
```
The agent will not be updated as rootfs has a mark file to avoid rebuild it again.
While it is useful because can take a lot of time. Agent changes could be common
specially for agent PRs.

Add logic to build agent out of rootfs. Then pass a tarball to osbuilder,
the agent tarball will be installed every make rootfs-image-tarball.

Fixes: #2430

Depends on: https://github.com/kata-containers/kata-containers/pull/2417

### CODE REVIEW

**Comment by fidencio** [comment]
@jcvenegas, do you happen to have some time to update this one?

**Comment by jodh-intel** [comment]
Marking as stale as this PR may have been abandoned.

**Comment by jodh-intel** [comment]
Ping @jcvenegas.

**Comment by fidencio** [comment]
A head's up that may affect your PR.

In the Architecture Committee meeting from January 25th, 2022, the Architecture Committee has agreed on using the "Dismiss stale pull request approvals when new commits are pushed" configuration from GitHub.  It basically means that if your PR has been rebased or updated, the approvals given will be erased.

In order to minimize traumas due to the new approach, please, consider adding a note on the changes done before the rebase / force-push, and also pinging the reviewers for a subsequent round of reviews.

Thanks for your understanding!

Related issue: https://github.com/kata-containers/community/issues/249

**Comment by fidencio** [comment]
As this PR has been waiting for an update since October 2021, I'm closing it for now.

@jcvenegas, please, if you find some free cycles to work on this PR, please, just re-open it and let us know.
Thanks for the contribution and looking forward to seeing an up-to-date version of this PR.

**Pull request closed without merging**
