### PR TITLE
runtime-rs: Show config files attempted on config load failure

### PR DESCRIPTION
**Pull request by jodh-intel**
PR #8483 changed the location of the rust runtime config files to
`/etc/kata-containers/runtime-rs/`. However, if you haven't updated your
system to create that directory, attempting to create a container using
the rust runtime was giving the following cryptic message
(formatted for easier reading):

```
failed to handler message try init runtime instance

Caused by:
    0: load config
    1: load toml config
    2: entity not found
```

Now, the message is as follows (again, reformatted for easier reading):

```
failed to handle message try init runtime instance

Caused by:
    0: load config
    1: load TOML config failed (tried [
        \"/etc/kata-containers/runtime-rs/configuration.toml\",
        \"/usr/share/defaults/kata-containers/runtime-rs/configuration.toml\",
        \"/opt/kata/share/defaults/kata-containers/runtime-rs/configuration.toml\"
    ])
```

Fixes: #8557.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jodh-intel!

**Review by cmaf — APPROVED** [review]
thanks @jodh-intel

**Review by amshinde — APPROVED** [review]

**Comment by GabyCT** [comment]
@jodh-intel could you please rebase this PR so the cloud hypervisor (runtime-rs) CI can be launched? thanks

**Pull request merged**
