### PR TITLE
Upgrade to Cloud Hypervisor v28.0 

### PR DESCRIPTION
**Pull request by likebreath**
This release has been tracked in our new [roadmap project](https://github.com/orgs/cloud-hypervisor/projects/6) as iteration v28.0.

### Community Engagement (Reminder)

Just a reminder that we have a new mailing list to support broader community discussions.  Please consider [subscribing](https://lists.cloudhypervisor.org/g/dev/). We plan to use this to announce a regular meeting for those interested in talking about Cloud
Hypervisor development.

### Long Term Support (LTS) Release

This is the first version of Cloud Hypervisor to be released under the LTS release process. Point releases for bug fixes will be made for the next 18 months; live migration and live upgrade will be supported between the point releases of the LTS.

### Virtualised TPM Support

Support for adding an emulated CRB TPM has been added. This has it's own TPM documentation.

### Transparent Huge Page Support

By default, but controllable through `--memory thp=off` if it possible to back the guest memory with Transparent Huge Pages (no file backing/`shared=off`) then this will be used resulting in improved boot performance.

### README Quick Start Improved

The README has been refreshed with the quick start guide updated to reflect the different firmware options and to recommend the use of pre-built binaries.

### Notable Bug Fixes

* Inappropriate Copy-on-Write of pinned pages (e.g. VFIO) leading to higher
  memory consumption
* Multiple `virtio` device bug fixes found through fuzzing
* Large QCOW files (> 4TiB) are now supported
* Support for > 31 vCPUS on aarch64
* Multiple fixes to OpenAPI specification file
* Programming of the MSI-X table has been optimised leading to faster boot on
  newer Linux kernels
* Error on reboot from race to close TAP devices
* Non-spec compliant virtio-block read-only support
  
### Removals

The following functionality has been removed:

* Support for non-PVH firmware booting has been removed
* I/O ports used for older versions of firmware have been removed
* Deprecated API options for kernel/cmdline/initramfs have been removed

Fixes: #5683

Signed-off-by: Bo Chen <chen.bo@intel.com>

### CODE REVIEW

**Review by amshinde — APPROVED** [review]

**Comment by likebreath** [comment]
I believe the failing CI jobs are not relevant to changes, as they have been also being failing for a while on various PRs.

**Review by cmaf — APPROVED** [review]
thanks @likebreath

**Pull request merged**
