### PR TITLE
rustjail: Add tests for hook_grpc_to_oci

### PR DESCRIPTION
**Pull request by fidencio**
Add test coverage for hook_grpc_to_oci in rustjail/src/lib.rs

Fixes: #4125

Signed-off-by: Garrett Mahin <garrett.mahin@gmail.com>

I'm opening this one on behalf of @garrettmahin

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @fidencio.

lgtm

**Comment by fidencio** [comment]
> Thanks @fidencio.
> 
> lgtm

Hey, thanks @garrettmahin! :-)
I'm just the one who open the PR, all the credits for working on this go to Garret! :-)

**Pull request merged**
