### PR TITLE
coco: ci: Fully implement compilation of CSI driver and require it for CoCo tests [2/x]

### PR DESCRIPTION
**Pull request by sprt**
This implements the CSI driver compilation and adds that job as a requirement for the CoCo tests.

Depends on: #10561

Addresses: #10560

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
LGTM (once rebased on #10561). Thanks!

**Review by c3d — APPROVED** [review]
Not feeling very competent on the topic, but looks good to me.

**Comment by stevenhorsman** [comment]
As it's thanksgiving I've used maintainer rights to rebase this and see if it fixes the CI

**Comment by stevenhorsman** [comment]
After Fabiano's heroics fixing the CI I've rebase on that too.

**Pull request merged**
