### PR TITLE
genpolicy: support insecure registries and custom pause containers

### PR DESCRIPTION
**Pull request by burgerdev**
This PR adds support for a few registry options that allow running genpolicy in hermetic environments (e.g. build systems). Instead of adding more arguments to the individual function calls, I decided to pass around an options struct that holds the currently required options: `use_cache`, `pause_container_image` and `insecure_registries`. 

I think the right place to obtain the pause container image from is the settings file, because this is where other implementation details of the CRI currently live (such as default env vars, capabilities, etc.). The `cluster_config` section seemed like a good idea, but I'm open to alternatives. Although there already is a `pause_container` section, that one is parsed as a `KataSpec`, where putting an image reference does not make sense. 

Insecure registries are something specific to the environment where genpolicy  is run, not the container runtime environment. Since the settings file deals with settings for the latter, I decided not to put them there but rather make them arguments to the CLI.

Fixes: #9008

### CODE REVIEW

**Comment by burgerdev** [comment]
cc @danmihai1

**Comment by sprt** [comment]
Thanks @burgerdev! Dan will be back from vacation next week and will be able to give this a proper look then. 🙂

**Review by Redent0r — APPROVED** [review]
LGTM

**Comment by danmihai1** [comment]
Thanks for helping out, @burgerdev !

**Comment by danmihai1** [comment]
@burgerdev , when you get a chance, please fix the new "make check" issues - from https://github.com/kata-containers/kata-containers/actions/runs/8344078088/job/23067991633?pr=9294

**Comment by burgerdev** [comment]
I fixed the linting issues, but still need to resolve the merge conflict with #9185.

**Comment by burgerdev** [comment]
Rebased, ptal @danmihai1 @Redent0r.

**Review by danmihai1 — APPROVED** [review]

**Comment by burgerdev** [comment]
CI seems to be having a bad day, but I don't think this change here is to blame (lots of test setup issues). Any advice on how to proceed?

**Review by sprt — APPROVED** [review]

**Pull request merged**
