### PR TITLE
version: Fix formatting

### PR DESCRIPTION
**Pull request by stevenhorsman**
Add space before start of comment

Fixes: #5928
Signed-off-by: stevenhorsman <steven@uk.ibm.com>

### CODE REVIEW

**Comment by stevenhorsman** [comment]
@UnmeshDeodhar - The sev tests are failing with:
```
10:06:40 Update apt repositories
10:06:40 
10:06:40 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
10:06:40 
10:06:40 Hit:1 https://download.docker.com/linux/ubuntu focal InRelease
10:06:41 Hit:3 http://us.archive.ubuntu.com/ubuntu focal InRelease
10:06:41 Ign:2 https://packages.cloud.google.com/apt kubernetes-xenial-unstable InRelease
10:06:41 Get:4 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
10:06:41 Err:5 https://packages.cloud.google.com/apt kubernetes-xenial-unstable Release
10:06:41   Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 142.251.214.142 443]
10:06:41 Get:6 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
10:06:41 Get:7 http://us.archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
10:06:41 Reading package lists...
10:06:43 W: Target Packages (stable/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
10:06:43 W: Target Packages (stable/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
10:06:43 W: Target Translations (stable/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
10:06:43 W: Target Translations (stable/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
10:06:43 W: Target CNF (stable/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
10:06:43 W: Target CNF (stable/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
10:06:43 E: The repository 'http://apt.kubernetes.io/ kubernetes-xenial-unstable Release' no longer has a Release file.
10:06:43 W: Target Packages (stable/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
10:06:43 W: Target Packages (stable/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
10:06:43 W: Target Translations (stable/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
10:06:43 W: Target Translations (stable/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
10:06:43 W: Target CNF (stable/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
10:06:43 W: Target CNF (stable/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
10:06:43 [setup_env_ubuntu.sh:15] ERROR: sudo -E apt update
```
Can you manually look at this PR and review that the two comment format lines won't cause any issues with SEV. Thanks.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @stevenhorsman!

**Review by dubek — APPROVED** [review]
LGTM, thanks @stevenhorsman .

**Review by Ji-Xinyou — APPROVED** [review]

**Comment by stevenhorsman** [comment]
It's worth noting that the kata-ctl test that is failing has been re-worked in `main`: https://github.com/kata-containers/kata-containers/pull/5735 so we should pick up this fix when we do the merge from there in the next day or so.

**Comment by stevenhorsman** [comment]
I think I'll merge this giving the limited scope of the change and that all required tests are passing.

**Pull request merged**
