### PR TITLE
# Kata Containers 1.12.0-alpha1

### PR DESCRIPTION
**Pull request by egernst**
- actions: Pin to a particular sha for actions
- actions: Add action to perform checks for pull requests

57b64f35 actions: Pin to a particular sha for actions
1b157e50 actions: Add github actions to perform DCO check
0d96145c actions: Add action to perform WIP check for pull requests

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm!

**Review by bergwolf — APPROVED** [review]

**Comment by chavafg** [comment]
@likebreath @jcvenegas can you please check that `jenkins-ci-ubuntu-1804-cloud-hypervisor-k8s-containerd-2.0`  job only runs when target branch is `2.0-dev`?

**Comment by likebreath** [comment]
@chavafg Thanks for prompting the issue. With a quick check on the CI log, the CI was failing at the very early setup stage, and hence it should be a Jenkins CI config issue.

```
11:11:52 [kata-2-ubuntu-1804-PR-cloud-hypeprvisor-k8s-containerd] $ /bin/bash /tmp/jenkins7064189154558052522.sh
11:11:52 Cloning into '/tmp/jenkins/workspace/jobs-2.0/kata-2-ubuntu-1804-PR-cloud-hypeprvisor-k8s-containerd/go/src/github.com/kata-containers/tests'...
11:11:54 fatal: Couldn't find remote ref pull/633/head
11:11:54 Build step 'Execute shell' marked build as failure
```

I just adjusted the Jenkins configuration for the clh CI job [here](http://jenkins.katacontainers.io/job/jobs-2.0/job/kata-2-ubuntu-1804-PR-cloud-hypeprvisor-k8s-containerd/) by taking a reference from the CI job `jenkins-ci-ubuntu-18-04` config [here](http://jenkins.katacontainers.io/job/kata-containers-rust-agent-ubuntu-18-04-PR/). I also restarted the CI and see how it goes.

Our CI gurus @jcvenegas @GabyCT, please also take a look at the CLH CI config [here](http://jenkins.katacontainers.io/job/jobs-2.0/job/kata-2-ubuntu-1804-PR-cloud-hypeprvisor-k8s-containerd/).  Any comments or changes you want to make, please just do it. Thanks.

**Comment by egernst** [comment]
Still broken.  Any ideas @likebreath @chavafg @GabyCT ?

**Pull request merged**
