### PR TITLE
rootfs-builder: Don't modify /sbin/init on the build host

### PR DESCRIPTION
**Pull request by liangxianlong**
Don't modify /sbin/init on the build host when using command `AGENT_INIT="yes" ./rootfs.sh centos` to build rootfs.

Fixes: #430

Signed-off-by: liangxianlong <liang.xianlong@zte.com.cn>

### CODE REVIEW

**Comment by amshinde** [comment]
@liangxianlong Thanks for fixing this. 
Nit: You have created a detailed github issue describing the sequence of events, I would also add a mention in the commit message to denote systemd is replaced as the init with the earlier code flow.

**Comment by liangxianlong** [comment]
@amshinde Ok.

**Comment by bergwolf** [comment]
@liangxianlong Please rebase to include the DCO/WIP checks. Thanks!

**Pull request merged**
