### PR TITLE
Update kata-manager.sh

### PR DESCRIPTION
**Pull request by tg5788re**
Added code to test_installation:
sudo kata-runtime check -v
For PR

### CODE REVIEW

**Review by jodh-intel — COMMENTED** [review]
Thanks @tg5788re and congratulations on raising your first Kata PR! :smile:

The change itself is fine, but you'll need to tweak the commit message to conform to our standard format. See my comment on @gabevenberg's original PR [here](https://github.com/kata-containers/kata-containers/pull/6301#pullrequestreview-1301643476) for the full details, but what you'll need to do is:

1. Edit the commit message by running, `git commit --amend`
2. Change the commit message to something like this:
    ```
    utils: Make kata-manager.sh runs checks

    Updated the `kata-manager.sh` script to make it run all the checks on
    the host system before attempting to create a container. If any checks
    fail, they will indicate to the user what the problem is in a clearer
    manner than those reported by the container manager.

    Fixes: #6281.

    Signed-off-by: Your Name <your primary GitHub email address>
    ```
4. Update the PR by running, `git push -f`

See the following for further details:

- https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format
- https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#closing-issues

**Review by cmaf — APPROVED** [review]
thanks @tg5788re, approved pending @jodh-intel's advice

**Review by Tim-0731-Hzt — APPROVED** [review]
LGTM

**Review by GabyCT — APPROVED** [review]

**Comment by liubin** [comment]
@tg5788re you need fix your DCO:

```
Error: The SoB (DCO) check failed

  46deb0d3ebb6d[12](https://github.com/kata-containers/kata-containers/actions/runs/4249184119/jobs/7413658990#step:3:13)07678e7ab740908adddcb7f6f    The sign-off is missing.

  What should I do to fix it ?

  All proposed commits should include a Signed-Off-By: <your-email-address> line in their commit message.
  This is most conveniently done by using --signoff (-s) when running git commit.
```

**Comment by jodh-intel** [comment]
Hi @tg5788re - The reason the CI is failing is that you've got a "merge commit" on the PR. Kata doesn't use those: instead we use rebases to solve the same problem. But no problem! You should be able to run the commands below to rework this PR so that the CI is happy with it:

```bash
# Rename your branch as it shouldn't be called "main"
$ git branch -m kata-manager-use-runtime-checks

# Recreate the main branch
$ git checkout -b main origin/main

# Ensure main is up-to-date
$ git pull

# Switch back to your "feature branch"
$ git checkout kata-manager-use-runtime-checks

# Undo the merge commit:
# Note that this command is "safe" because the merge commit is the top commit so we can just remove all record of it.
# But normally, you wouldn't want to run this! ;)
$ git reset HEAD^ --hard

# Move your commit so that it sits "on top" of the tip ("HEAD") of the main branch
$ git rebase main

# Update this PR on GiHub
$ git push -f
```

**Comment by jodh-intel** [comment]
Replaced by https://github.com/kata-containers/kata-containers/pull/6410.

**Pull request closed without merging**
