### PR TITLE
# Kata Containers 2.5.2

### PR DESCRIPTION
**Pull request by gkurz**
- tools: release: fix bogus version check
- Last backport for 2.5.2
- stable-2.5: fix cargo vendor
- stable-2.5 backports

309756db95ab release: Adapt kata-deploy for 2.5.2
a8187717506b tools: release: fix bogus version check
52993b91b7e3 runtime: store the user name in hypervisor config
30a8166f4ae2 runtime: make StopVM thread-safe
7033c97cd284 runtime: add more debug logs for non-root user operation
e8ec0c402fa0 stable-2.5: fix cargo vendor
d92ada72deb6 kernel: upgrade guest kernel support to 5.19.2
565fdf8263db kernel: fix for set_kmem_limit error
f174fac0d670 sandbox_test: Add test to verify memory hotplug behavior
928654b5cd2f sandbox: don't hotplug too much memory at once
1c0e6b4356e8 hypervisor: Add GetTotalMemoryMB to interface
8f40927df8e7 kernel: Add CONFIG_CGROUP_HUGETLB=y as part of the cgroup fragments

### CODE REVIEW

**Comment by gkurz** [comment]
https://github.com/kata-containers/kata-containers/actions/runs/3152890996

**Review by GabyCT — APPROVED** [review]

**Review by c3d — APPROVED** [review]
/lgtm

**Review by bergwolf — APPROVED** [review]
Thanks!

**Pull request merged**
