### PR TITLE
Revert: "shimv2: update containerd vendor"

### PR DESCRIPTION
**Pull request by devimc**

### CODE REVIEW

**Comment by c3d** [comment]
@devimc I am curious about this change. Is there a related bug? I did not find it.

**Comment by c3d** [comment]
@devimc Found this on #kata-dev thanks to @fidencio 

> fidencio (IRC)APP  15:22
> devimc: oooi! so, you think all the instability in the CI is because of the switch to q35?
> white_check_mark
> eyes
> raised_hands
> 
> 
> 
> 
> 
> 
> devimc (IRC)APP  15:22
> fidencio, I think so
> 15:22
> I'll give a try
> 
> fidencio (IRC)APP  15:23
> devimc: I can see the metrics being affected, but more than that (as in the stability tests breaking and whatnot) seems suspicious
> 15:23
> devimc: do you need some help from marcel on this one?
> 
> devimc (IRC)APP  15:23
> fidencio, not yet
> 15:24
> but thanks
> 
> fidencio (IRC)APP  15:24
> devimc: sure, please, feel free to poke us for anything needed
> 
> devimc (IRC)APP  15:24
> sure thing :)
> 
> fidencio  15:24
> @Marcel Apfelbaum, JFYI ... ^^^
>

**Comment by fidencio** [comment]
@devimc, you also have to revert https://github.com/kata-containers/tests/commit/d5e9dcab9c16687a19ae5a8f09c6678e5bc7e614 and make this one depending on that one.

I've done the opposite way, and tested the PR from the tests repo ... and it didn't solve the issue we're facing.

**Comment by fidencio** [comment]
Howdy!

I'd like to ask you to rebase your PR atop of current `main`, as https://github.com/kata-containers/kata-containers/pull/2197 has been merged and it has a fix that unblocks the CI.

Please, do the rebase and feel free `@fidencio` in case you do not have the powers to run `/test`.

Sorry for the inconvenience and happy hacking!

**Pull request closed without merging**
