### PR TITLE
agent: Update seccomp configuration for errnoRet and flags

### PR DESCRIPTION
**Pull request by ManaSugi**
Update:
- Make the type of `errnoRet` in oci.proto `oneof`
- Update seccomp_grpc_to_oci that can set `errnoRet` as `EPREM` if the
value is empty.
- Update the oci.pb.go based on the above fixes
- Add seccomp `errnoRet` and `flags` option to configs in rustjail

Regarding the type of `errnoRet`, we cannot use `optional` type in the current proto3 version.
Therefore, we should use the `oneof` instead of `optional` as a workaround.

Fixes: #1719

Signed-off-by: Manabu Sugimoto <Manabu.Sugimoto@sony.com>

### CODE REVIEW

**Review by liubin — APPROVED** [review]

**Comment by ManaSugi** [comment]
Could you approve this reqeust?
Regards,

**Comment by liubin** [comment]
cc @lifupan @bergwolf @egernst @jodh-intel @fidencio

**Review by fidencio — APPROVED** [review]
lgtm, thanks @ManaSugi!

And sorry for the delay reviewing this one.  We've been facing a few issues with CI and we're trying to get a release out Today (which, by the way, will include this PR :-)).

**Pull request merged**
