### PR TITLE
docs: remove outdated dependencies from agent docs

### PR DESCRIPTION
**Pull request by snir911**
switched from grpc to ttrpc (a7041c27d)

fixs #558

Signed-off-by: Snir Sheriber <snir911@gmail.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
LGTM!

@snir911, thanks for the contribution!

@bergwolf, would be possible to have your review here as well?

**Comment by fidencio** [comment]
ARM CI failure is not related to this PR.
@chavafg, is the ARM failure being tracked somewhere?

**Comment by chavafg** [comment]
A PR to fix ARM CI issues was merged for 2.0 branch, but this seems like a new error:
```
Aug 24 07:57:06 arm-testing-1 containerd[34930]: time="2020-08-24T07:57:06.040551737Z" level=error msg="Failed to load cni during init, please check CRI plugin status before setting up network for pods" error="cni config load failed: no network config found in /etc/cni/net.d: cni plugin not initialized: failed to load cni config"

```

/cc @jongwu

**Comment by jongwu** [comment]
> A PR to fix ARM CI issues was merged for 2.0 branch, but this seems like a new error:
> 
> ```
> Aug 24 07:57:06 arm-testing-1 containerd[34930]: time="2020-08-24T07:57:06.040551737Z" level=error msg="Failed to load cni during init, please check CRI plugin status before setting up network for pods" error="cni config load failed: no network config found in /etc/cni/net.d: cni plugin not initialized: failed to load cni config"
> ```
> 
> /cc @jongwu

thanks @chavafg, luckily, arm02 works well for now, I need go to see why arm01 fails.

**Comment by chavafg** [comment]
cool, it worked, thanks @jongwu. should we disable arm01 node until fixed?

**Comment by jongwu** [comment]
thanks @chavafg, I think I can fix it.

**Pull request merged**
