### PR TITLE
runtime-rs: delete route model

### PR DESCRIPTION
**Pull request by Tim-0731-Hzt**
As route model is used for specific internal scenario, and it's not for
the general requirement.

Fixes:#4838
Signed-off-by: Zhongtao Hu <zhongtaohu.tim@linux.alibaba.com>

### CODE REVIEW

**Review by liubin — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @Tim-0731-Hzt!

**Comment by liubin** [comment]
Since `runtime-rs` has been merged, please change your target branch to `main`.

**Comment by liubin** [comment]
@Tim-0731-Hzt design doc also has `route` mode for [`Network Interworking Model` feature](https://github.com/kata-containers/kata-containers/blob/main/docs/design/architecture_3.0/README.md#roadmap), please delete this too.

**Comment by Tim-0731-Hzt** [comment]
> @Tim-0731-Hzt design doc also has `route` mode for [`Network Interworking Model` feature](https://github.com/kata-containers/kata-containers/blob/main/docs/design/architecture_3.0/README.md#roadmap), please delete this too.

fixed

**Pull request merged**
