### PR TITLE
[backport] Stable-2.0: versions: Update cloud-hypervisor to release v0.12.0

### PR DESCRIPTION
**Pull request by likebreath**
Highlights for cloud-hypervisor version v0.12.0 include: removal of
`vhost-user-net` and `vhost-user-block` self spawning, migration of
`vhost-user-fs` backend, ARM64 enhancements with full support of
`--watchdog` for rebooting, and enhanced `info` HTTP API to include the
details of devices used by the VM including VFIO devices.

Fixes: #1315

Signed-off-by: Bo Chen <chen.bo@intel.com>
(cherry picked from commit c2d14cdeea63444509d75e5d89a37363b3faaad5)

### CODE REVIEW

**Review by devimc — APPROVED** [review]
thanks @likebreath

**Review by chavafg — APPROVED** [review]

**Review by jcvenegas — APPROVED** [review]
thanks @likebreath

**Comment by GabyCT** [comment]
@likebreath could you please push again this PR? the snap CI has been fixed as well some other CI's for stable-2.0

**Comment by likebreath** [comment]
Looks like the `continuous-integration/travis-ci/pr ` has been failing for a while with multiple PRs. Any insights? Shall we hold on merging this PR for this failure? @GabyCT @chavafg 

As the PR has been waiting for a while, the context for this PR is to fix CLH CIs for branch stable-2.0.

**Comment by chavafg** [comment]
I see that it fails because it is looking for branch `2.0-dev`, which no longer exists.
```
error: pathspec '2.0-dev' did not match any file(s) known to git
```

Took a look at the code and see that in `stable-2.0` branch we still have reference to `2.0-dev`
https://github.com/kata-containers/kata-containers/blame/stable-2.0/ci/lib.sh#L8

I think that the best way is to take the branch from the travis environment in this case, maybe adding a line at:
https://github.com/kata-containers/kata-containers/blob/stable-2.0/.travis.yml#L28 
`export branch=$TRAVIS_BRANCH`

**Comment by likebreath** [comment]
Following @bergwolf 's comments from https://github.com/kata-containers/kata-containers/pull/1466#issuecomment-800774227:

I believe the problem is not related to the PR change itself, given this exact PR was passing when it was opened (back to Feb 12). We were holding on merging this PR at that time for landing the fix on snap CI. I checked the stable-2.0 branch and the only changes are on snap since the PR was passing last time. I would guess the failure is related to changes from the test repo or the Jenkins config.

@chavafg @jcvenegas Would you please help on reproducing this error locally given your better understanding on this particular CI/test? Please let me know when you need my inputs for debugging. Thank you!.

**Comment by likebreath** [comment]
Close the PR in favor of #1409.

**Pull request closed without merging**
