### PR TITLE
build: update golang version to 1.19.3

### LINKED ISSUE #5773: runtime: "runtime·lock: lock count" fatal error
# Description of problem

containerd-shim-kata-v2 crashes sporadically in go runtime library:

```
func unlock2(l *mutex) {
 	...
	if gp.m.locks < 0 {
		throw("runtime·unlock: lock count")
	}
	...
}
```

### PR DESCRIPTION
**Pull request by alex-matei**
This Go release fixes golang/go#56309

Fixes #5773
Signed-off-by: Alexandru Matei <alexandru.matei@uipath.com>

### CODE REVIEW

**Comment by fidencio** [comment]
@alex-matei, please, also update the following places:
* https://github.com/kata-containers/kata-containers/blob/main/.github/workflows/docs-url-alive-check.yaml
* https://github.com/kata-containers/kata-containers/blob/main/.github/workflows/darwin-tests.yaml
* https://github.com/kata-containers/kata-containers/blob/main/.github/workflows/static-checks.yaml

**Comment by alex-matei** [comment]
Updated.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @alex-matei!

**Comment by fidencio** [comment]
@alex-matei, I'm very sorry but we merged a PR that caused a conflict with this one.  Would you mind rebasing it atop of main and fixing the conflict?  It shouldn't be complicated.

**Review by GabyCT — APPROVED** [review]

**Comment by alex-matei** [comment]
Done, I rebased the commit.

**Pull request merged**
