### PR TITLE
docs: Update networking details in the architecture doc

### LINKED ISSUE #3308: Update networking details in architecture document
The networking part of the architecture document needs to be reviewed, and probably updated:

- https://github.com/kata-containers/kata-containers/blob/main/docs/design/architecture/networking.md

### PR DESCRIPTION
**Pull request by amshinde**
Updated the doc to clarify certain networking details and add
external links to some of the networking terms used.

Fixes #3308

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by amshinde** [comment]
@jodh-intel This is my first iteration on updating the networking docs. I am planning on adding some more details in a future PR.

**Review by Jakob-Naucke — APPROVED** [review]
LGTM (it would probably be better to also get an approval from someone more familiar with networking though)

**Comment by fidencio** [comment]
A head's up that may affect your PR.

In the Architecture Committee meeting from January 25th, 2022, the Architecture Committee has agreed on using the "Dismiss stale pull request approvals when new commits are pushed" configuration from GitHub.  It basically means that if your PR has been rebased or updated, the approvals given will be erased.

In order to minimize traumas due to the new approach, please, consider adding a note on the changes done before the rebase / force-push, and also pinging the reviewers for a subsequent round of reviews.

Thanks for your understanding!

Related issue: https://github.com/kata-containers/community/issues/249

**Review by fgiudici — APPROVED** [review]
LGTM! Thanks @amshinde :-)

**Comment by fidencio** [comment]
@fgiudici, thanks for the review!

Spoiler alert, for those who're not that familiar with Francesco, he's also a person with a really strong networking background, and I hope we can take more advantage of that in the project. :-)

**Comment by fidencio** [comment]
@amshinde, thanks for the work on this,
@mcastelino, if you notice something that has to be changed, please, let us know and follow-up changes can come later.

**Pull request merged**
