### PR TITLE
db: fix the issue of failed to init pci root bus

### PR DESCRIPTION
**Pull request by lifupan**
dragonball reserves 2048G of mmio space for the pci root bus by default on physical addresses greater than 4G. However, for some machines with smaller physical address widths, such as 39-bit wide physical addresses, dragonball reserves the mmio space when initializing the memory. It is less than 2048G, so this commit dynamically calculates and allocates the mmio size of each pci root bus.

Fixes: #9509

### CODE REVIEW

**Review by Apokleos — APPROVED** [review]
Thx @lifupan LGTM!

**Review by studychao — APPROVED** [review]
LGTM

**Review by studychao — APPROVED** [review]
LGTM

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
