### PR TITLE
runtime: change containers from slice to map

### PR DESCRIPTION
**Pull request by zhaojizhuang**
runtime: change change conainers from slice to map to avoid avoid data corruption when delete slice items

Fixes: #6475

Signed-off-by: zhaojizhuang <571130360@qq.com>

### CODE REVIEW

**Comment by zhaojizhuang** [comment]
cc @liubin

**Comment by zhaojizhuang** [comment]
cc @liubin

**Comment by liubin** [comment]
```
time="2023-03-29T03:33:07Z" level=error msg="Create new sandbox failed" error="Missing kernel path" sandbox=7f49d00d-1995-4156-8c79-5f5ab24ce138 source=virtcontainers subsystem=sandbox
--- FAIL: TestCreateContainer (0.01s)
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map

goroutine 712 [running]:
testing.tRunner.func1.2({0x16ca860, 0x1a9b5d0})
	/opt/hostedtoolcache/go/1.19.3/x64/src/testing/testing.go:1396 +0x372
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.19.3/x64/src/testing/testing.go:1399 +0x5f0
panic({0x16ca860, 0x1a9b5d0})
	/opt/hostedtoolcache/go/1.19.3/x64/src/runtime/panic.go:890 +0x262
github.com/kata-containers/kata-containers/src/runtime/virtcontainers.(*Sandbox).CreateContainer(0xc0005ccb60, {0x1aa7f20, 0xc00003a198}, 0xc0005ccd00)
	/home/runner/work/kata-containers/kata-containers/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/sandbox.go:1329 +0x10c
github.com/kata-containers/kata-containers/src/runtime/virtcontainers.TestCreateContainer(0x0?)
	/home/runner/work/kata-containers/kata-containers/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/sandbox_test.go:841 +0x2c5
testing.tRunner(0xc00041c820, 0x18a5020)
	/opt/hostedtoolcache/go/1.19.3/x64/src/testing/testing.go:1446 +0x217
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.19.3/x64/src/testing/testing.go:1493 +0x75e
```

**Comment by zhaojizhuang** [comment]
a little ping @liubin

**Review by c3d — CHANGES_REQUESTED** [review]
Typo in commit title: conainer -> container

**Comment by zhaojizhuang** [comment]
> Typo in commit title: conainer -> container

Fixed

**Comment by zhaojizhuang** [comment]
cc @liubin @bergwolf @c3d

**Review by liubin — APPROVED** [review]

**Comment by zhaojizhuang** [comment]
any other reviews?

**Pull request closed without merging**
