### PR TITLE
runtime: delete types or const that no longer needed

### PR DESCRIPTION
**Pull request by Bevisy**
type: ProcessListOptions; ProcessList
const: SocketTypeVSOCK

Fixes: #2285

Signed-off-by: Binbin Zhang <binbin36520@gmail.com>

### CODE REVIEW

**Comment by Bevisy** [comment]
PTAL @liubin

**Review by liubin — APPROVED** [review]

**Comment by Bevisy** [comment]
By searching the jenkins logs, I found that the last few pr failure logs are the same, as follows:
```log
16:45:00 ERROR: kata-log-parser: missing pid: {Data:map[subsystem:oci] Time:2021-08-28 08:39:09.652503608 +0000 UTC Filename:/tmp/jenkins/workspace/kata-containers-2.0-centos-PR/go/src/github.com/kata-containers/tests/kata.log Level:info Msg:shm-size detected: 67108864 Source:virtcontainers Name: Container: Sandbox: Line:3 Count:0 TimeDelta:0 Pid:0}
16:45:00 POST BUILD TASK : FAILURE
```
It looks like the problem is related to src/github.com/kata-containers/tests/cmd/log-parser

**Comment by liubin** [comment]
> By searching the jenkins logs, I found that the last few pr failure logs are the same, as follows:
> 
> ```
> 16:45:00 ERROR: kata-log-parser: missing pid: {Data:map[subsystem:oci] Time:2021-08-28 08:39:09.652503608 +0000 UTC Filename:/tmp/jenkins/workspace/kata-containers-2.0-centos-PR/go/src/github.com/kata-containers/tests/kata.log Level:info Msg:shm-size detected: 67108864 Source:virtcontainers Name: Container: Sandbox: Line:3 Count:0 TimeDelta:0 Pid:0}
> 16:45:00 POST BUILD TASK : FAILURE
> ```

Hi， @Bevisy , this log doesn't matter, don't worry about it. All the required tests have passed.

**Review by likebreath — APPROVED** [review]

**Pull request merged**
