### PR TITLE
stable-3.0: Stable 3.0 backports

### PR DESCRIPTION
**Pull request by amshinde**
This PR adds backports for the stable 3.0 branch

### CODE REVIEW

**Comment by jongwu** [comment]
To let dragonball-arm test pass, https://github.com/kata-containers/kata-containers/pull/5853/commits/c5abc5ed4d34d0d8f1354de887b4fee1b956417b is also needed.

**Comment by fidencio** [comment]
@amshinde, I'm not that comfortable on adding here the patches related to docker, @bergwolf WDYT?
With this in mind, I'd drop the first 6 patches.

**Comment by jongwu** [comment]
Hi @amshinde -, should backport https://github.com/kata-containers/kata-containers/pull/5693  to fix arm-unit-test issue.

**Comment by amshinde** [comment]
@fidencio Ack, I have removed the docker related changes. It would have been nice to have the docker support, but it requires porting a lot of code, and not just a simple fix.

**Review by cmaf — APPROVED** [review]

**Review by chavafg — APPROVED** [review]

**Pull request merged**
