### PR TITLE
runtime: qemu/virtio-mem: fix block size

### PR DESCRIPTION
**Pull request by jongwu**
virtio-mem block size is not a const value, but the current implementation set it to 4M. From [1] we can see that the block size may vary with page size. So, we should caculate blk size depends on host configuration.

Fixes: #7656
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>
[1] https://github.com/qemu/qemu/blob/408af44d04476c633065bfb1eca6865ea93f2984/hw/virtio/virtio-mem.c#L119

### CODE REVIEW

**Comment by fidencio** [comment]
```
Error: qemu.go:17:2: SA1019: "io/ioutil" has been deprecated since Go 1.16: As of Go 1.16, the same functionality is now provided by package io or package os, and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
	"io/ioutil"
```

From the static checks.

**Comment by jongwu** [comment]
Thanks @fidencio -,  fixed.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jongwu!

**Review by cmaf — APPROVED** [review]
thanks @jongwu

**Pull request closed without merging**
