### PR TITLE
tests/k8s: disable "fail-fast" behavior by default

### PR DESCRIPTION
**Pull request by wainersm**
The k8s test suite halts on the first failure, i.e., failing-fast. This isn't the behavior that we used to see when running tests on Jenkins and it seems that running the entire test suite is still the most productive way. So this disable fail-fast by default.

However, if you still wish to run on fail-fast mode then just export K8S_TEST_FAIL_FAST=yes in your environment.

Fixes: #9697

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @wainersm!

**Comment by sprt** [comment]
I thought about doing this a while ago but for some reason that I don't remember, I decided against it - maybe in my testing some failing tests would not clean up properly and thus cause further failures down the chain. Any worries re: this nowadays?

**Review by GabyCT — APPROVED** [review]

**Comment by fidencio** [comment]
> I thought about doing this a while ago but for some reason that I don't remember, I decided against it - maybe in my testing some failing tests would not clean up properly and thus cause further failures down the chain. Any worries re: this nowadays?

This may actually happen.  Let me add a do-not-merge label so we can discuss this properly.
Thanks for bringing this up, @sprt!

**Comment by danmihai1** [comment]
I think we'd like to know if some of the tests are not cleaning up properly after a failure. So, unless you guys are already aware of such tests, I think it's worth making this change and exposing these tests.

**Comment by fidencio** [comment]
based on @danmihai1's comment, and on the approbals from other members of the community, I'm removing the `do-not-merge` label.

We can experiment with this, and fix things up as we go if / when we hit the issues.

**Review by sprt — APPROVED** [review]

**Pull request merged**
