### PR TITLE
Docs: fix tables format error

### PR DESCRIPTION
**Pull request by yahaa**
Fixes: https://github.com/kata-containers/kata-containers/issues/4725

### CODE REVIEW

**Comment by liubin** [comment]
@yahaa Thank you for your PR, but you need to fix your commit message by reading [this patch format](https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format)

**Comment by yahaa** [comment]
> @yahaa Thank you for your PR, but you need to fix your commit message by reading [this patch format](https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format)

I fixed it.

**Review by liubin — APPROVED** [review]
Thank you @yahaa

**Review by snir911 — APPROVED** [review]

**Pull request merged**
