### PR TITLE
action: Add issue to project and move to "In progress" on linked PR

### PR DESCRIPTION
**Pull request by jodh-intel**
Add GitHub actions to:

- Add newly-created issues to the issue backlog project.
- Move issues with a linked PR into the "In progress" column
  of the issue backlog project.

Related: https://github.com/kata-containers/kata-containers/issues/512

Fixes: #637.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Replaced https://github.com/kata-containers/kata-containers/pull/638.

**Comment by jodh-intel** [comment]
Ping @kata-containers/kata-containers - please tal.

**Comment by jodh-intel** [comment]
Ping y'all - this is the last one of these PRs we need to land, and arguably one of the most important! :smile:

**Review by GabyCT — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm!

**Pull request merged**
