### PR TITLE
fix number of queues handling in dragonball share fs device

### PR DESCRIPTION
**Pull request by pmores**
Looks like a copy/paste error...

### CODE REVIEW

**Review by bergwolf — APPROVED** [review]
nice catch, thanks!

**Review by lifupan — APPROVED** [review]

**Review by studychao — APPROVED** [review]
Thanks!

**Comment by pmores** [comment]
Thanks for the approvals! Labelling checks are failing but honestly I have no idea about forward- and backporting, could someone help please?

**Comment by studychao** [comment]
> Thanks for the approvals! Labelling checks are failing but honestly I have no idea about forward- and backporting, could someone help please?

It's not required CI. I'll merge this one.
Thanks for catching this!

**Pull request merged**
