### PR TITLE
Don't use a globally installed mock hook for hook tests

### PR DESCRIPTION
**Pull request by dgibson**
Address #3941.  Make some additional cleanups in vicinity while we're at it.

### CODE REVIEW

**Review by fidencio — CHANGES_REQUESTED** [review]
I can't review the commit message, but ...
```
virtcontainers: Run mock hook from build tree rather than system bin dir

Running unit tests should generally have minimal dependencies on things
outside the build tree.  It *definitely* should modify system wide things
outside the build tree.  Currently the runtime "make test" target does so,
though.
...
```

By saying "It *definitely* should modify system wide things
outside the build tree. ", did you mean "It *definitely* should NOT modify system wide things
outside the build tree. "?

```
virtcontainers: Remove unused install/uninstall targets
We've now removed the need to install the mock hook binary for unit tests.
However, it turns out that managing that was the *only* thing that the
install and uninstall targets in the virtcontainers Makefile handlded.
```

Shouldn't "handlded" be "handled"?

Requesting changes till the commit messages are fixed.

Changes are good otherwise.

I'd let CI finish this run before resubmitting the series, so we can have an idea whether it's happy or not with those.

**Comment by c3d** [comment]
@fidencio Could you edit your comment above to replace "NOT should" by "should NOT" ? ;-)

**Comment by fidencio** [comment]
> @fidencio Could you edit your comment above to replace "NOT should" by "should NOT" ? ;-)

Done.

**Comment by dgibson** [comment]
> I can't review the commit message, but ...
> 
> ```
> virtcontainers: Run mock hook from build tree rather than system bin dir
> 
> Running unit tests should generally have minimal dependencies on things
> outside the build tree.  It *definitely* should modify system wide things
> outside the build tree.  Currently the runtime "make test" target does so,
> though.
> ...
> ```
> 
> By saying "It _definitely_ should modify system wide things outside the build tree. ", did you mean "It _definitely_ should NOT modify system wide things outside the build tree. "?

Oops, yes, corrected.

> ```
> virtcontainers: Remove unused install/uninstall targets
> We've now removed the need to install the mock hook binary for unit tests.
> However, it turns out that managing that was the *only* thing that the
> install and uninstall targets in the virtcontainers Makefile handlded.
> ```
> 
> Shouldn't "handlded" be "handled"?

Oops, again, fixed.

**Review by liubin — APPROVED** [review]
Thank you @dgibson, installing the hook to the system is really a bad idea.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @dgibson!

**Pull request merged**
