### PR TITLE
[backport] ci: static checks: use defined target_branch

### PR DESCRIPTION
**Pull request by snir911**
Fixes: #2214
Signed-off-by: Snir Sheriber <ssheribe@redhat.com>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @snir911.

lgtm

**Review by fidencio — APPROVED** [review]
lgtm, thanks @snir911!

**Comment by snir911** [comment]
/retest-vfio 
(passing on main)

**Review by devimc — APPROVED** [review]

**Pull request closed without merging**
