### PR TITLE
config: remove CONFIG_CGROUP_HUGETLB to fix CLH CI Test on x86

### PR DESCRIPTION
**Pull request by jongwu**
Bump config will lead to failure of clh ci test on x86. see [5196](https://github.com/kata-containers/kata-containers/issues/5196). Removing CONFIG_CGROUP_HUGETLB can fix it.
Also both [731d39df4](https://github.com/kata-containers/kata-containers/pull/4956/commits/731d39df452c57b2e182094b2a3eed2ca4238e68) and [0a6f0174f59a](https://github.com/kata-containers/kata-containers/commit/0a6f0174f59a23af77ecb406839515f4d6cffe24) bump kata_config_version from 95 to 96. That's say these changes have not tested simultaneously.

### CODE REVIEW

**Comment by amshinde** [comment]
@jongwu Is the kernel config affecting just cloud-hypervisor?

**Comment by jongwu** [comment]
> @jongwu Is the kernel config affecting just cloud-hypervisor?

In my tests, bumping kernel config leads to failure of cloud-hypervisor but does not affect other jobs. Removing CONFIG_CGROUP_HUGETLB can cancel the failure of clh CI.

**Comment by jongwu** [comment]
Help TAL @fidencio @gkurz

**Pull request closed without merging**
