### PR TITLE
stable 2.1 | Backports

### PR DESCRIPTION
**Pull request by snir911**
88677381 vendor: update govmm
c6a39f71 runtime: virtcontainers: make rootfs image read-only
6456cb28 osbuilder/scripts: add support to yq version 4 and above
c1dcc5f7 osbuilder: Skip installing golang for building rootfs
9b8cc4581d023e2f54829147d3aa7281acfcd135 ci: static checks: use defined target_branch
8f76626fd6c78e6db54d5f04d52d09f2f704a46e qemu: stop the virtiofsd specifically
4c809a53d238fd124bc7058af73e536ce010c250 shimv2: fix the issue of leaking the hypervisor processes
1ab72518b3e3f2229576b0347b39a1c84fa9bd41 agent: Fix to parsing of /proc/self/mountinfo
55c5c871d2a5316d414caa3f328e859323dac32e agent: enhance tests of execute_hook
aa264f915fc9a52d8b4063568f712209341dbdcb agent: update netlink libraries
b3623a2c40f2a8d18c5c9b453c48f00486ebe893 shimv2: fix the issue of leaking wait goroutines
ecdd137c6f00b363581df9c2ff01d4e58a286852 runtime: do not hot-remove PMEM devices 
23d31d5a7c6c5b849cc9a24de78632e0de0be7f2 ci: snap: Fetch history to all branches and tags
8310a3d70a1e98e8bba4683d3bb3dd47df870217 virtcontainers: Don't fail memory hotplug
799cb27234272c0e6fc792f7fefadb652628bda8 agent: upgrade mio to v0.7.13 to fix epoll_fd leak problem
ce11a6f6 versions: Update containerd to v1.3.10

### CODE REVIEW

**Comment by snir911** [comment]
/test
vfio is likely to fail until #2222 is merged and this one will be rebased

**Review by jodh-intel — APPROVED** [review]
Thanks @snir911.

lgtm

**Review by wainersm — APPROVED** [review]

**Comment by fidencio** [comment]
Please, add https://github.com/kata-containers/kata-containers/pull/2222 to this list. :-)

**Comment by fidencio** [comment]
> Please, add #2222 to this list. :-)

Actually, no, let me fix that one (commit message, reference, whatnot) and get that one merged first.

**Comment by fidencio** [comment]
@Jakob-Naucke, is s390x supposed to work well on the stable-2.1 branch as well?  Or can we ignore it for now as the next stable release is, most likely, going to be last one?

**Comment by fidencio** [comment]
Oh, now I remember, vfio is failing because we first need to merge https://github.com/kata-containers/kata-containers/pull/2222, but we need https://github.com/kata-containers/tests/pull/3744 merged first.

**Comment by Jakob-Naucke** [comment]
> @Jakob-Naucke, is s390x supposed to work well on the stable-2.1 branch as well?

https://github.com/kata-containers/tests/pull/3607 is missing

> Or can we ignore it for now as the next stable release is, most likely, going to be last one?

I don't quite understand -- 2.2 is our last stable release, ever? No

**Comment by fidencio** [comment]
> > Or can we ignore it for now as the next stable release is, most likely, going to be last one?
> 
> I don't quite understand -- 2.2 is our last stable release, ever? No

We are releasing 2.2.0 next week (more or less ;-)), and with that stable-2.1 branch will reach its EOL and we'll start maintaining the stable-2.2 branch only.

**Comment by Jakob-Naucke** [comment]
> We are releasing 2.2.0 next week (more or less ;-)), and with that stable-2.1 branch will reach its EOL and we'll start maintaining the stable-2.2 branch only.

Ah yes, of course. I don't have a strong opinion. We could backport that in tests for CI prettiness*, or forgo it because (I think) it's only a tests issue, so the kata-containers release itself isn't really broken.

*something s390x CI stability on watch something something

**Comment by fidencio** [comment]
> > We are releasing 2.2.0 next week (more or less ;-)), and with that stable-2.1 branch will reach its EOL and we'll start maintaining the stable-2.2 branch only.
> 
> Ah yes, of course. I don't have a strong opinion. We could backport that in tests for CI prettiness*, or forgo it because (I think) it's only a tests issue, so the kata-containers release itself isn't really broken.
> 
> *something s390x CI stability on watch something something

Up to you, @Jakob-Naucke.  Let me know if you open the PR, or let me know if I should disable this specific CI as part of the stable-2.1 branch.

**Comment by Jakob-Naucke** [comment]
> Up to you, @Jakob-Naucke. Let me know if you open the PR, or let me know if I should disable this specific CI as part of the stable-2.1 branch.

Disable it then. Because we could backport, but ideally we shouldn't be using libpod anyways (see https://github.com/kata-containers/tests/pull/3700#discussion_r667907019), but that's another change so you can even "backport" it, so...

**Comment by snir911** [comment]
Bumping containerd to v3.1.10 is included (#2222)
/test

**Comment by snir911** [comment]
@Jakob-Naucke Hi, does this jenkins-vfio-host:ubuntu18-04-vm:fedora32 failure ring any bells ?
```
 level=debug msg="qemu-system-x86_64: -object memory-backend-file,id=mem0,mem-path=/usr/share/kata-containers/kata-containers.img,size=134217728: can't open backing store /usr/share/kata-containers/kata-containers.img for guest RAM: Read-only file system" name=containerd-shim-v2 pid=87244 sandbox=vfiotest19216 source=virtcontainers subsystem=qemu
```

**Comment by Jakob-Naucke** [comment]
> @Jakob-Naucke Hi, does this jenkins-vfio-host:ubuntu18-04-vm:fedora32 failure ring any bells ?
> 
> ```
>  level=debug msg="qemu-system-x86_64: -object memory-backend-file,id=mem0,mem-path=/usr/share/kata-containers/kata-containers.img,size=134217728: can't open backing store /usr/share/kata-containers/kata-containers.img for guest RAM: Read-only file system" name=containerd-shim-v2 pid=87244 sandbox=vfiotest19216 source=virtcontainers subsystem=qemu
> ```

@snir911 hmm. I have worked with `memory-backend-file` in the context of https://github.com/kata-containers/govmm/pull/161, but this strikes me. The `mem-path` is usually something like `/dev/shm` and I have no idea why the Kata containers image would be used for a memory backend. It appears this is configured by `file_mem_backend` in Kata's configuration. Is it at all possible that that path ended up there? And if it did, is that intended?

/cc @devimc

**Comment by devimc** [comment]
> @Jakob-Naucke Hi, does this jenkins-vfio-host:ubuntu18-04-vm:fedora32 failure ring any bells ?

@snir911 please include https://github.com/kata-containers/kata-containers/pull/2300 in this PR

**Comment by snir911** [comment]
/test
HI @devimc, do you mind to check whether https://github.com/kata-containers/kata-containers/pull/2226/commits/b54ca3de6a78425b355210d33664eec56af8921a make sense? as 37a426b4c656941257fc9f9f2931956126004db3 was not backported it required some modifications from your original patch (https://github.com/kata-containers/kata-containers/commit/070590fb533afee77bc8e0a0ae376928bbbfb34b)

**Comment by devimc** [comment]
@snir911 it makes sense, vfio CI is passing, thanks

**Comment by fidencio** [comment]
> /test
> HI @devimc, do you mind to check whether [b54ca3d](https://github.com/kata-containers/kata-containers/commit/b54ca3de6a78425b355210d33664eec56af8921a) make sense? as [37a426b](https://github.com/kata-containers/kata-containers/commit/37a426b4c656941257fc9f9f2931956126004db3) was not backported it required some modifications from your original patch ([070590f](https://github.com/kata-containers/kata-containers/commit/070590fb533afee77bc8e0a0ae376928bbbfb34b))

+1 for the approach and thanks a lot for being careful to not bring https://github.com/kata-containers/kata-containers/commit/37a426b4c656941257fc9f9f2931956126004db3 in.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @snir911!

I wanna cry seeing all the CIs passing and, trust me, tears of joy!
Amazing work!

**Pull request merged**
