### PR TITLE
backport-2.2: remove default config for arm64.

### PR DESCRIPTION
**Pull request by jongwu**
The current default config in qemu for arm64 doesn't suit for qemu
version 5.1+, so remove them here.

Fixes: #2595
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Comment by jongwu** [comment]
help review @fidencio

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jongwu!

**Pull request merged**
