### PR TITLE
gha: Fix the failure of gha metrics for StratoVirt

### PR DESCRIPTION
**Pull request by WenyuanLau**
Update the metrics test baseline for StratoVirt and re-enable.

Fixes: #8656 

Related: #8496

### CODE REVIEW

**Comment by GabyCT** [comment]
If you enable but do not run each tests it will be safer and easier to verify which test has issues and avoid the random failures with other hypervisors

**Comment by WenyuanLau** [comment]
@GabyCT I record the data for 5 times when StratoVirt running in GHA but failure, and I get the `fio` limit just by compare the performance between StratoVirt and other VMMs in the same baremetal. I did run the metrics in the baremetal for many times and get the stable data.

How can I repeat and get the inproper status you said? :)

**Comment by WenyuanLau** [comment]
I've done some tests, how about we enable Speed & Density metric tests and skip other tests for StratoVirt first? After things are stable, we can enable other tests step by step. @GabyCT 

My plan: 
1. Speed & Density (launchtimes, memory_usage, memory_usage_inside_container) 
2. iperf
3. latency 
4. blogbench 
5. fio 
6. tensorflow

**Review by GabyCT — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @WenyuanLau!

**Pull request merged**
