### PR TITLE
runtime-rs: fix build error on AArch64

### PR DESCRIPTION
**Pull request by jongwu**
Vfio support introduce build error on AArch64. Remove arch related annotation can avoid this error.

Fixes: #7187

### CODE REVIEW

**Comment by jongwu** [comment]
Hi @GabyCT @Tim-0731-Hzt -, Could you help TAL this?

**Comment by xuejun-xj** [comment]
@jongwu Hi, thanks for fix. A small suggestion.
On arm, we use smmu to support iommu. The do_check_iommu_on funtion only checks iommu support on intel or amd. Could you please add some similar check on arm? And use "target_arch" to wrap INTEL_PREFIX and AMD_PREFIX.
BTW, should we check "iommu.strict" and "iommu.passthrough" in cmdline?

**Review by xuejun-xj — APPROVED** [review]
LGTM

**Comment by jongwu** [comment]
> @jongwu Hi, thanks for fix. A small suggestion. On arm, we use smmu to support iommu. The do_check_iommu_on funtion only checks iommu support on intel or amd. Could you please add some similar check on arm? And use "target_arch" to wrap INTEL_PREFIX and AMD_PREFIX. 

Sorry, I forget to look into the code.

> BTW, should we check "iommu.strict" and "iommu.passthrough" in cmdline?

For "iommu.strict" I think no. For "iommu.passthrough" I'm not sure. Maybe share the same behaviour with x86. We can leave aside and add it once need.

**Comment by xuejun-xj** [comment]
> > @jongwu Hi, thanks for fix. A small suggestion. On arm, we use smmu to support iommu. The do_check_iommu_on funtion only checks iommu support on intel or amd. Could you please add some similar check on arm? And use "target_arch" to wrap INTEL_PREFIX and AMD_PREFIX.
> 
> Sorry, I forget to look into the code.
> 
> > BTW, should we check "iommu.strict" and "iommu.passthrough" in cmdline?
> 
> For "iommu.strict" I think no. For "iommu.passthrough" I'm not sure. Maybe share the same behaviour with x86. We can leave aside and add it once need.

All right, thanks! I agree with it. :)

**Review by Tim-0731-Hzt — APPROVED** [review]
Thanks @jongwu ,LGTM

**Review by fidencio — APPROVED** [review]
ltgm, thanks @jongwu!

**Comment by wainersm** [comment]
hi @jongwu , I don't know anything about this piece of code so I cannot approve it myself. But thanks for sending this fix that will unlock other PRs from being merged!

**Comment by fidencio** [comment]
Merging this one to unblock other PRs to being merged.

**Pull request merged**
