### PR TITLE
GHA: fix up referenced yaml exceeding 20 limit problem

### PR DESCRIPTION
**Pull request by bergwolf**
GHA has an undocumented limitation that there can be at most 20  referenced yamls in a single yaml file. We work around it by combining multiple jobs into a single yaml file.

### CODE REVIEW

**Comment by bergwolf** [comment]
testing PR against my own repo looks ok, the `ci-on-push.yaml` jobs are running
https://github.com/bergwolf/kata-containers/actions/runs/6448197404

**Review by fidencio — APPROVED** [review]
lgtm, thanks @bergwolf!

**Comment by ananos** [comment]
LTGM!

**Review by ananos — APPROVED** [review]

**Pull request merged**
