### PR TITLE
kata-deploy: Switch Kubernetes URL

### PR DESCRIPTION
**Pull request by stevenhorsman**
The payload build is failing with:
```
ERROR: failed to solve: process "/bin/sh -c apk --no-cache add bash curl && \tARCH=$(uname -m) && \tif [ \"${ARCH}\" = \"x86_64\" ]; then ARCH=amd64; fi && \tif [ \"${ARCH}\" = \"aarch64\" ]; then ARCH=arm64; fi && \tDEBIAN_ARCH=${ARCH} && \tif [ \"${DEBIAN_ARCH}\" = \"ppc64le\" ]; then DEBIAN_ARCH=ppc64el; fi && \tcurl -fL --progress-bar -o /usr/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/${ARCH}/kubectl && \tchmod +x /usr/bin/kubectl && \tcurl -fL --progress-bar -o /usr/bin/jq https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-${DEBIAN_ARCH} && \tchmod +x /usr/bin/jq && \tmkdir -p ${DESTINATION} && \ttar xvf ${WORKDIR}/${KATA_ARTIFACTS} -C ${DESTINATION} && \trm -f ${WORKDIR}/${KATA_ARTIFACTS} && \tapk del curl && \tapk --no-cache add py3-pip && \tpip install --no-cache-dir yq==3.2.3" did not complete successfully: exit code: 22
```

Looking into this, the problem is that
https://storage.googleapis.com/kubernetes-release/release/v1.31.1/bin/linux/amd64/kubectl doesn't exist. The [kubectl install doc](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-kubectl-on-linux) recommends the `dl.k8s.io` site, so let's switch to this.

**Note:** I've not updated the URLS of the kubectl install in `deploy_k0s` and `deploy_k3s` yet as I'm not sure if the dl.k8s.io has all the back level versions, but we should look at this soon once our builds are unblocked

### CODE REVIEW

**Comment by BbolroC** [comment]
For `k0s`:

```
$ sudo k0s kubectl version
Client Version: v1.30.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.30.4+k0s
$ wget https://dl.k8s.io/release/v1.30.4/bin/linux/amd64/kubectl
--2024-09-17 10:15:58--  https://dl.k8s.io/release/v1.30.4/bin/linux/amd64/kubectl
Resolving dl.k8s.io (dl.k8s.io)... 34.107.204.206, 2600:1901:0:26f3::
Connecting to dl.k8s.io (dl.k8s.io)|34.107.204.206|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://cdn.dl.k8s.io/release/v1.30.4/bin/linux/amd64/kubectl [following]
--2024-09-17 10:15:58--  https://cdn.dl.k8s.io/release/v1.30.4/bin/linux/amd64/kubectl
Resolving cdn.dl.k8s.io (cdn.dl.k8s.io)... 151.101.161.55, 2a04:4e42:26::311
Connecting to cdn.dl.k8s.io (cdn.dl.k8s.io)|151.101.161.55|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 51454104 (49M) [application/octet-stream]
Saving to: ‘kubectl’

kubectl                                                      100%[=============================================================================================================================================>]  49.07M   300MB/s    in 0.2s

2024-09-17 10:15:58 (300 MB/s) - ‘kubectl’ saved [51454104/51454104]
```

`k3s` uses the same version `v1.30.4` like:

```
$ curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644
[INFO]  Finding release for channel stable
[INFO]  Using v1.30.4+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.30.4+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.30.4+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Skipping installation of SELinux RPM
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s
[INFO]  Creating /usr/local/bin/crictl symlink to k3s
[INFO]  Creating /usr/local/bin/ctr symlink to k3s
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.
[INFO]  systemd: Starting k3s
```

Why don't we update those URLs for `deploy_k3s()` and `deploy_k0s()`?

**Comment by stevenhorsman** [comment]
> Why don't we update those URLs for `deploy_k3s()` and `deploy_k0s()`?

Sure, I can bump them too

**Review by BbolroC — APPROVED** [review]
LGTM, thanks @stevenhorsman !

**Review by fidencio — APPROVED** [review]
lgtm, thanks @stevenhorsman

**Review by GabyCT — APPROVED** [review]

**Comment by stevenhorsman** [comment]
The CI seems to be stuck, so I'll try closing and re-opening this PR...

**Review by sprt — APPROVED** [review]
Thanks @stevenhorsman!

**Comment by fidencio** [comment]
Can we just force-push this one?

**Pull request merged**
