### PR TITLE
runtime: clean/refactor code

### LINKED ISSUE #1081: Clean codes
Clean code that has no meanings, or should not to happen, etc.

### PR DESCRIPTION
**Pull request by liubin**
This PR mainly cleans code.

Fixes #1081

### CODE REVIEW

**Review by jodh-intel — COMMENTED** [review]
Hi @liubin - thanks for raising. Cleanup is good ;)

However, please can you add more details to the commits, especially the VC cleanup commit. I think you need to say we can now remove this code since we've removed the runtime CLI commands, including `kata-network`?

Also, I think you may need to update atleast the following:

- `docs/design/kata-api-design.md`
- `src/runtime/netmon/netmon.go`

But also, if those agent APIs are no longer needed, shouldn't you update `src/agent/protocols/protos/agent.proto`, atleast to mark the functions as "deprecated" and make the agent handlers NOPs?

**Comment by liubin** [comment]
@jodh-intel , Since we will support Docker in the future, these interfaces may be needed, so I will drop this commit.

**Comment by jodh-intel** [comment]
> @jodh-intel , Since we will support Docker in the future, these interfaces may be needed

We need a tracking issue for that. We already have https://github.com/kata-containers/kata-containers/issues/722, but I suspect that isn't going to be correct as we would obviously prefer to using shimv2 with docker/podman/etc

**Review by jodh-intel — APPROVED** [review]
Thanks @liubin.

lgtm

**Review by bergwolf — APPROVED** [review]

**Pull request merged**
