### PR TITLE
mod: unify runc and containerd dependencies

### PR DESCRIPTION
**Pull request by fidencio**
We have many indirect dependencies on their older versions which are carrying CVEs.

This is #2339, revisited, as I do believe that `make handle_vendor` is behaving weirdly due to the golang versions that Tao, the CI, and I are using.

So, let's give it a try with this one and see if the CI is happy.

### CODE REVIEW

**Review by snir911 — APPROVED** [review]

**Review by egernst — APPROVED** [review]

**Comment by fidencio** [comment]
@Jakob-Naucke, seems s390x CI has gone broken.

**Pull request merged**
