### PR TITLE
gha: tdx: Ensure kata-deploy is removed after the tests run

### PR DESCRIPTION
**Pull request by fidencio**
We must ensure that no kata-deploy is left behind after the tests
finish, otherwise it may interfere with the next run.

Fixes: #6647

### CODE REVIEW

**Review by jepio — APPROVED** [review]
LGTM. Consider moving `KUBECONFIG: /etc/rancher/k3s/k3s.yaml`  to job level instead of setting it in every step.

**Review by stevenhorsman — APPROVED** [review]
Assuming there is no need to wait for the delete to process in order to go onto the next step (which the testing should pick up), this looks good to me. Thanks!

**Comment by fidencio** [comment]
> LGTM. Consider moving `KUBECONFIG: /etc/rancher/k3s/k3s.yaml` to job level instead of setting it in every step.

Done, thanks!

**Comment by fidencio** [comment]
@stevenhorsman, @jepio, as I've added a few PRs atop of what you reviewed, I'd like to ask for a second pass from both of you.

Thanks!

**Comment by stevenhorsman** [comment]
> @stevenhorsman, @jepio, as I've added a few PRs atop of what you reviewed, I'd like to ask for a second pass from both of you.
> 
> Thanks!

It mostly looks like timeouts, waits, overheard etc that is changed, so if tests are good then I'm fine. Thanks!

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
