### PR TITLE
runtime-rs: fix the bug of func count_files

### PR DESCRIPTION
**Pull request by gaohuatao-1**
When the total number of files observed is greater than limit, return -1 directly. runtime has fixed this bug, it should b ported to runtime-rs.

Fixes:#9829

### CODE REVIEW

**Review by Apokleos — COMMENTED** [review]
Thx @gaohuatao-1 It looks good for me but lacks the UT of such general function.

**Review by justxuewei — APPROVED** [review]
Lgtm, thanks!

**Comment by gaohuatao-1** [comment]
@justxuewei @Apokleos I have added a ut to the method. PTAL again, thanks.

**Comment by gaohuatao-1** [comment]
@Apokleos  Hi, PTAL, Thanks.

**Review by Apokleos — COMMENTED** [review]
Thx @gaohuatao-1 Compared with `CountFiles in kata runtime with golang`, this commit looks good to me. 
But I try to set the `limit < 0` (limit declared as i32), the UT fails. I think the argument  `limit: i32` in count_files()  shoud be change as `limit: u32`, maybe it's another bug, what do you think ?

**Comment by gaohuatao-1** [comment]
> Thx @gaohuatao-1 Compared with `CountFiles in kata runtime with golang`, this commit looks good to me. But I try to set the `limit < 0` (limit declared as i32), the UT fails. I think the argument `limit: i32` in count_files() shoud be change as `limit: u32`, maybe it's another bug, what do you think ?

If the input param limit of func count_files is smaller than zero, test_count_files is still passed.  Of course, you cannot set the   local var limit to -1.  Could you please post your test code?

**Comment by Apokleos** [comment]
> > Thx @gaohuatao-1 Compared with `CountFiles in kata runtime with golang`, this commit looks good to me. But I try to set the `limit < 0` (limit declared as i32), the UT fails. I think the argument `limit: i32` in count_files() shoud be change as `limit: u32`, maybe it's another bug, what do you think ?
> > @Apokleos
> > Thanks for your reply.
> > I  did the test:  the input param limit of func count_files is smaller than zero and test_count_files is still passed.  such as:
> > image
> 
> Could you please take a look again? Thanks a lot.
>
what's about -2 ? IMO, if you set -1 the return value is -1 which looks same with the Ok(-1), but they are in fact not same, I think.

**Comment by gaohuatao-1** [comment]
> is



> > > Thx @gaohuatao-1 Compared with `CountFiles in kata runtime with golang`, this commit looks good to me. But I try to set the `limit < 0` (limit declared as i32), the UT fails. I think the argument `limit: i32` in count_files() shoud be change as `limit: u32`, maybe it's another bug, what do you think ?
> > > @Apokleos
> > > Thanks for your reply.
> > > I  did the test:  the input param limit of func count_files is smaller than zero and test_count_files is still passed.  such as:
> > > image
> > 
> > 
> > Could you please take a look again? Thanks a lot.
> 
> what's about -2 ? IMO, if you set -1 the return value is -1 which looks same with the Ok(-1), but they are in fact not same, I think.
-2 is ok, too. such as:
image

**Review by Apokleos — APPROVED** [review]
Thx @gaohuatao-1 LGTM

**Pull request merged**
