### PR TITLE
clh: Port cloud-hypervisor related changes from kata-runtime

### PR DESCRIPTION
**Pull request by likebreath**
As we are bringing online a CI job for covering kata 2.0 w/ cloud-hypervisor
(https://github.com/kata-containers/tests/pull/2797), we need to back port 
related patches from kata-runtime (kata 1.x). 

This PR ported the following patches from the runtime repo:

39b53f44 * chenb/clh_backporting clh: enable build using Podman                                                                                                                      
04b156f6 * qemu-virtiofs: Update to qemu 5.0 + virtiofs + dax                                                                                                                        
3ec05a9f * clh: Add support to unplug block devices                                                                                                                                  
45e32e1b * clh: Set 'Id' explicitly while hotplugging block device                                                                                                                   
895959d0 * clh: Provide cpu topology to API                                                                                                                                          
31594387 * clh: opeanapi: update api for cloud hypervisor                                                                                                                            
89836cd3 * versions: cloud-hypervisor 0.9.0                                                                                                                                          
8d5a60ac * versions: Update qemu-virtiofs to 5.0                                                                                                                                       
76a64667 * clh: Remove the use of deprecated '--memory file=' parameter  

Signed-off-by: Bo Chen chen.bo@intel.com

### CODE REVIEW

**Comment by likebreath** [comment]
@jcvenegas @GabyCT Can you please help look into the failure from the CLH CI ( log is [here]( http://jenkins.katacontainers.io/job/jobs-2.0/job/kata-2-ubuntu-1804-PR-cloud-hypeprvisor-k8s-containerd/24/))? I was assuming it should be 'equivalent' to what we have in the tests/2.0-dev repo (http://jenkins.katacontainers.io/job/kata-containers-2.0-tests-ubuntu-clh-virtiofs-PR/) which was passing. But the CI is failing on `make cri-containerd`, not `make kubernetes`(the actual k8s+containerd tests).

**Comment by likebreath** [comment]
After the changes over the CI config file, the CI now is passing (http://jenkins.katacontainers.io/job/jobs-2.0/job/kata-2-ubuntu-1804-PR-cloud-hypeprvisor-k8s-containerd/25/).  Also, the PR is updated to prepare for merging.
/test

**Comment by likebreath** [comment]
This PR is ready for review. All the CI jobs are now passing, including the one for CLH. PTAL. @jcvenegas @devimc @amshinde  @GabyCT @chavafg @egernst

**Review by jodh-intel — APPROVED** [review]
Thanks @likebreath!

lgtm

**Pull request merged**
