### PR TITLE
runk: Upgrade liboci-cli to v0.0.4

### PR DESCRIPTION
**Pull request by utam0k**
We can remove the custom kill command.

Fix: https://github.com/kata-containers/kata-containers/issues/6083

### CODE REVIEW

**Comment by utam0k** [comment]
@ManaSugi Hi, I love runk project. May I ask you to review this PR?

**Comment by liubin** [comment]
Thank you, @utam0k, you need to amend your commit message:

- write something in the commit message, not only a title.
- create an issue to describe what you want to do and add a `Fixes: #xxx` in your one commit message.
- include a `Signed-Off-By` in each commit.

Please refer to https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format for more information.

**Comment by utam0k** [comment]
@liubin Thanks for your guide. I have updated my commits.

**Review by liubin — APPROVED** [review]

**Review by ManaSugi — APPROVED** [review]
LGTM, thank you! @utam0k

**Pull request merged**
