### PR TITLE
ci: Enable versions and kernel tag to enable CLH CI for kata 2.0

### LINKED ISSUE #532: clh: Enable versions and kernel tag to enable CLH CI for kata 2.0

### PR DESCRIPTION
**Pull request by GabyCT**
This PR updates the versions for the virtiofs kernel branch and
as there is a tag based in kernel 5.6 move patches to uses the tag name.
This PR is needed to enable CLH CI for kata 2.0
This PR is backporting
kata-containers/runtime#2843 and kata-containers/packaging#1098.

Fixes #532

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
This is related with https://github.com/kata-containers/tests/pull/2789, and it seems that the CI setup is working for clh, what is failing is the execution of tests, but that can be seen in another PR

**Comment by likebreath** [comment]
@GabyCT Thanks for taking the efforts on enabling the CLH CI in kata 2.0. This PR looks good to me. 

Two nits here:

1. This PR is essentially back-porting the following two PRs from 1.x to 2.0. Can you please include these back-ported PRs in the commit message?
https://github.com/kata-containers/runtime/pull/2843
https://github.com/kata-containers/packaging/pull/1098

2. It seems we are still maintaining the kata kernel config version (https://github.com/kata-containers/kata-containers/blob/2.0-dev/tools/packaging/kernel/kata_config_version). If that's true, can you please bump the kernel config version in the PR?

As for next step, it looks like we have a running CI for CLH + kata 2.0.  Once this PR is merged, I think we are ready to start the comprehensive back-porting process for clh related paches from 1.x to 2.0. I can take the first shot from there, and hopefully we can bring the parity of qemu and clh in kata 2.0 soon (in terms of passing k8s+containerd tests). Any comments or thoughts, please don't hesitate to share. @GabyCT @jcvenegas @chavafg @amshinde @egernst

**Comment by GabyCT** [comment]
@likebreath changes applied

**Pull request merged**
