### PR TITLE
Only keep one VERSION file

### PR DESCRIPTION
**Pull request by fidencio**
Instead of having different VERSION files spread accross the project,
let's always use the one in the topsrcdir and remove all the others.

Fixes: #1579

Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>

### CODE REVIEW

**Review by egernst — APPROVED** [review]
Looks good --thanks Fabiano!

**Comment by fidencio** [comment]
I'm having a hard time to understand why the static check is failing.

**Comment by wainersm** [comment]
> I'm having a hard time to understand why the static check is failing.

I looked at the logging but couldn't understand either. :(

**Comment by fidencio** [comment]
Okay, I got it!  The test we have for our release versions is wrong!
Let me fix that and update the PR.

**Pull request merged**
