### PR TITLE
mount: fix the issue of missing check file exists

### PR DESCRIPTION
**Pull request by lifupan**
It's better to check whether the destination file exists
before creating them, if it had been existed, then return
directly.

Fixes: #2247

Signed-off-by: fupan.lfp <fupan.lfp@antgroup.com>

### CODE REVIEW

**Comment by Jakob-Naucke** [comment]
OOI /retest-s390x

**Comment by Jakob-Naucke** [comment]
s390x failed again:
```
E0720 05:02:04.857732 1998841 remote_runtime.go:157] StopPodSandbox "aeaa343d74e6adf5c822124d5a44aa83a338db525b4dd92156383c86b57ca21e" from runtime service failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    container_stats_test.go:139: 
        	Error Trace:	container_stats_test.go:139
        	            				container_stats_test.go:189
        	Error:      	Received unexpected error:
        	            	rpc error: code = DeadlineExceeded desc = context deadline exceeded
        	Test:       	TestContainerListStatsWithIdFilter
--- FAIL: TestContainerListStatsWithIdFilter (71.37s)
```

but it is quite possible that this is not a bug in this PR, but this PR is merely uncovering another bug. Taking a look.

**Comment by Jakob-Naucke** [comment]
> s390x failed again

Never mind, this also happens on other runs occasionally and is not related.

**Review by Tim-Zhang — APPROVED** [review]

**Comment by jodh-intel** [comment]
Hi @lifupan - ooi, why do we need this change? The safest approach would be to always attempt to create the destination directory and just ignore `EEXIST` since the creation is atomic so it's race-free (well, assuming only a single directory needs to be created).

**Comment by lifupan** [comment]
> Hi @lifupan - ooi, why do we need this change? The safest approach would be to always attempt to create the destination directory and just ignore `EEXIST` since the creation is atomic so it's race-free (well, assuming only a single directory needs to be created).

Hi  @jodh-intel 

Since for some special storage‘s mount destination would be created from the host side under the host shared directory to guest, because the shared dir was readonly in the guest.  BTW, why the creation is race-free, and what's the drawback of the checking exist and return directly?

**Comment by jodh-intel** [comment]
@lifupan - `mkdir(2)` is atomic, but by splitting the logic, we'll ultimately be calling `stat(2)` _and then_ `mkdir(2)`. So there will be a small time window between the two calls when another process could do something (like `rmdir(2)`). However, since the mounting occurs before the workload starts, there isn't realistically an opportunity for another process to cause problems here (assuming the agent is the init process; if we're using systemd there might be but, only for a service that started before the agent, but that implies a custom image with custom rogue services, so the risk seems low imho :)

**Review by bergwolf — APPROVED** [review]

**Comment by lifupan** [comment]
> @lifupan - `mkdir(2)` is atomic, but by splitting the logic, we'll ultimately be calling `stat(2)` _and then_ `mkdir(2)`. So there will be a small time window between the two calls when another process could do something (like `rmdir(2)`). However, since the mounting occurs before the workload starts, there isn't realistically an opportunity for another process to cause problems here (assuming the agent is the init process; if we're using systemd there might be but, only for a service that started before the agent, but that implies a custom image with custom rogue services, so the risk seems low imho :)

Hi @jodh-intel 
Yes, for this ensure_destination_exists funciton, it could only make sure the destination dir/file exist after it check, but it couldn't make sure the destination file wouldn't  be "rm". And if that happened, then there's must be something wrong with it and should be fixed.

**Pull request merged**
