### PR TITLE
runtime: cloud-hypervisor: reduce memory footprint

### LINKED ISSUE #1056: Improve cloud-hypervisor memory footprint
Cloud-hypervisor support DAX, let's enable it and reduce the memory footprint ~10M

### PR DESCRIPTION
**Pull request by devimc**
Cloud-hypervisor supports DAX, let's enable it to reduce its memory
footprint.

Before this patch:

**19.96M**

```
20448kB -- [/usr/share/kata-containers/kata.img]
```

With this patch:

**10.83M**

```
11100kB -- [/usr/share/kata-containers/kata.img]
```

fixes #1056

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by devimc** [comment]
cc @likebreath @rbradford

**Comment by likebreath** [comment]
@devimc Thanks for PR and the numbers. I vaguely recall I was advised to not include `DAX` while adding the support of booting from pmem device with clh in kata, but don't recall why. I thought there was an issue of using `DAX` in clh+kata (may be resolved). Any comments here? @rbradford 

/test

**Comment by rbradford** [comment]
Sound's good. This is just a Linux kernel related thing (not anything to do with CH.)

**Review by jodh-intel — APPROVED** [review]
Thanks @devimc.

lgtm

**Review by bergwolf — APPROVED** [review]
+1!

**Pull request merged**
