### PR TITLE
kernel: Update kernel config name

### PR DESCRIPTION
**Pull request by zvonkok**
Fixes: #7294

When installing the kernel config adjust the name like the vmlinuz and vmlinux files so that any added suffixes are also reflected in the kernel config name and are not overwritten.

### CODE REVIEW

**Review by jepio — APPROVED** [review]
Looks good.

Can you bump the config version to make static checks pass.

**Comment by zvonkok** [comment]
Done thanks.

**Review by fidencio — CHANGES_REQUESTED** [review]
Taking a look at https://github.com/kata-containers/kata-containers/actions/runs/5546387177/jobs/10126753661?pr=7333#step:4:45, it shows that the PR didn't solve the issue.

**Comment by zvonkok** [comment]
@fidencio if you look at the build step, the cached versions were used.

**Comment by jepio** [comment]
> @fidencio if you look at the build step, the cached versions were used.

It looks like you didn't push the kernel config version bump :)

**Comment by zvonkok** [comment]
@jepio @fidencio It was late yesterday and I just realized that I pushed my `main` for this PR but update the kernel version config bump in my `kernel-config-name` branch ... Mea culpa.

**Review by fidencio — APPROVED** [review]
From the GHA:
```
./opt/
./opt/kata/
./opt/kata/share/
./opt/kata/share/kata-containers/
./opt/kata/share/kata-containers/vmlinuz-nvidia-gpu.container
./opt/kata/share/kata-containers/vmlinux-5.19.2-110-nvidia-gpu
./opt/kata/share/kata-containers/vmlinux-nvidia-gpu.container
./opt/kata/share/kata-containers/config-5.19.2-110-nvidia-gpu
./opt/kata/share/kata-containers/vmlinuz-5.19.2-110-nvidia-gpu
```

It works as expected.

Thanks @zvonkok!

**Pull request merged**
