### PR TITLE
agent/agent-ctl: update tokio to 1.8.1

### PR DESCRIPTION
**Pull request by egernst**
Update to latest tokio to address RUSTSEC-2021-0072:
 Task dropped in wrong thread when aborting `LocalSet` task

Fixes: #2165

Updated by running "cargo update -p tokio" for both agent and agent-ctl

Signed-off-by: Eric Ernst <eric_ernst@apple.com>

### CODE REVIEW

**Comment by mxpv** [comment]
I think we also have to change Cargo.toml

**Comment by egernst** [comment]
Done. 1.2.0 was getting overriden anyway during cargo update. I think we should just set to "1", since we aren't getting pinned to 1.2.0 anyway...

**Review by amshinde — APPROVED** [review]

**Comment by fidencio** [comment]
Adding the do-not-merge label till we get the release out.

**Comment by fidencio** [comment]
I'm really sorry for the disruption we had, but I'm glad to say that 2.2.0-alpha1 release is finally out and we're removing all the `do-not-merge` labels that were added due to this.

Thanks a lot for your understanding and happy hacking!

**Review by fidencio — APPROVED** [review]
lgtm, thanks @egernst!

**Pull request merged**
