### PR TITLE
tests: k8s: k8s-copy-file auto-generated policy

### PR DESCRIPTION
**Pull request by danmihai1**
Auto-generate policy for k8s-copy-file.bats.

Fixes: #9050

### CODE REVIEW

**Comment by ChengyuZhu6** [comment]
minor nit in the forth commit 😉: `tests: k8s: addional policy testing utilities` > `tests: k8s: additional policy testing utilities`

**Comment by danmihai1** [comment]
> minor nit in the forth commit 😉: `tests: k8s: addional policy testing utilities` > `tests: k8s: additional policy testing utilities`

Fixed - thanks!

**Review by GabyCT — APPROVED** [review]

**Review by ChengyuZhu6 — APPROVED** [review]
LGTM ! Thanks @danmihai1

**Review by sprt — APPROVED** [review]

**Pull request merged**
