### PR TITLE
agent/config: Make CDH_API_TIMEOUT configurable

### PR DESCRIPTION
**Pull request by BbolroC**
In `k8s-guest-pull-image.bats`, a container sometimes fails to start due to the following error:

```
Message:   failed to create containerd task: failed to create shim task: ttrpc err: Receive packet timeout Elapsed(())
```

This issue occurs when fulfilling volume mounts for a large image (https://github.com/kata-containers/kata-containers/actions/runs/10465537902/job/28980940906). 

It was identified that CDH_API_TIMEOUT (default: 50s) influences this situation. 
This PR makes the variable configurable so that the timeout can be adjusted on the fly via annotations.

Signed-off-by: Hyounggyu Choi <Hyounggyu.Choi@ibm.com>

### CODE REVIEW

**Comment by fidencio** [comment]
@BbolroC, please, expose this to the Kata Containers configuration, so we can set this in the configuration file as well.

**Review by ChengyuZhu6 — COMMENTED** [review]
@BbolroC Could you please also update https://github.com/kata-containers/kata-containers/blob/main/src/agent/README.md#agent-options ?

**Comment by ChengyuZhu6** [comment]
@BbolroC Thanks for the fix! I have a quick question: Have you found the root cause of the issue? Was it simply due to insufficient execution time for  CDH, or were there other factors that caused the timeout? I haven't encountered this error in previous CI runs.

**Comment by BbolroC** [comment]
> @BbolroC, please, expose this to the Kata Containers configuration, so we can set this in the configuration file as well.

Done. Thanks for the feedback. 😉

**Comment by BbolroC** [comment]
> @BbolroC Could you please also update https://github.com/kata-containers/kata-containers/blob/main/src/agent/README.md#agent-options ?

Done, thanks for the feedback. 😉

**Comment by ChengyuZhu6** [comment]
@BbolroC Would you mind updating the config in the doc? https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-set-sandbox-config-kata.md

**Review by ChengyuZhu6 — APPROVED** [review]
The PR looks good to me. LGTM. Thanks @BbolroC ! Let’s see if the CI works as expected.

**Comment by BbolroC** [comment]
# Please do not merge this 

until I finish testing the changes and get an approval from @fidencio. Thanks!

**Pull request merged**
