### PR TITLE
virtcontainers: Add function to capabilities test

### LINKED ISSUE #428: Increase unit test coverage for virtcontainers/types/capabilities.go
Coverage for virtcontainers/types/capabilities.go can be increased to 100% by adding test checking multiqueue support functions.

### PR DESCRIPTION
**Pull request by cmaf**
Add function that tests multiqueue functions in types/capabilities.go.

Fixes #428

Signed-off-by: Chelsea Mafrica <chelsea.e.mafrica@intel.com>

### CODE REVIEW

**Comment by cmaf** [comment]
I noticed that other functions in capabilities_test.go do not use `assert := assert.New(t)` and use `t` as an argument such as in `assert.True(t, caps.IsFsSharingSupported())`. Is there a preferred way of doing this?

**Comment by cmaf** [comment]
Backport: [#2845](https://github.com/kata-containers/runtime/pull/2845)

**Comment by bergwolf** [comment]
@cmaf Please rebase to include the DCO/WIP checks. Thanks!

**Pull request merged**
