### PR TITLE
scripts: Add an enhanced die function

### LINKED ISSUE #9105: tests: Re-add die call with details
Since we switch to GitHub actions for the CI, we have lost the `die()` implementation that also logs lots of details about the failing test. In the old tests repo, `die()` (from https://github.com/kata-containers/tests/blob/main/lib/common.bash#L38which) calls `dump_details()` (from https://github.com/kata-containers/tests/blob/main/lib/error.sh) and that produces a YAML dump of useful environmental information.

Related: #9103.

### PR DESCRIPTION
**Pull request by GabyCT**
This PR adds an enhanced die function in order to dump more information in a yaml format that will help with the debugging.

Fixes #9105

### CODE REVIEW

**Review by danmihai1 — APPROVED** [review]
Should KATA_TEST_VERBOSE be enabled by default?

**Review by jodh-intel — APPROVED** [review]
Thanks, @GabyCT!

lgtm

**Comment by GabyCT** [comment]
> Should KATA_TEST_VERBOSE be enabled by default?

@danmihai1 I was going to first just enabled it in a certain GHA runners as I do not want to mess with people's CI's :P

**Pull request merged**
