### PR TITLE
stable-2.3 | Upgrade to Cloud Hypervisor v20.0 and Openapi-generator v5.3.0

### PR DESCRIPTION
**Pull request by likebreath**
Backport two PRs related to Cloud Hypervisor upgrade (https://github.com/kata-containers/kata-containers/pull/3179) and openapi-generator upgrade (https://github.com/kata-containers/kata-containers/pull/3200).

Signed-off-by: Bo Chen chen.bo@intel.com

### CODE REVIEW

**Comment by fidencio** [comment]
CentOS 8 job got aborted, cc @snir911 @c3d

**Review by fidencio — APPROVED** [review]
lgtm, thanks @likebreath!

**Review by snir911 — APPROVED** [review]
LGTM thanks!

**Pull request merged**
