### PR TITLE
CCv0: set dependencies to v0.4.0 tag

### PR DESCRIPTION
**Pull request by jepio**
This covers td-shim, attestation-agent and image-rs.

Fixes: #6366

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jepio!

**Review by GabyCT — APPROVED** [review]

**Comment by fidencio** [comment]
TDX Cloud Hypervisor has passed but didn't report back: http://10.112.240.208:8080/job/kata-containers-CCv0-cloud-hypervisor-TDX-CRI_CONTAINERD_K8S-PR/744/consoleFull

**Comment by fidencio** [comment]
SEV has passed but didn't report back yet: http://jenkins.katacontainers.io/job/kata-containers-CCv0-ubuntu-20.04_sev-x86_64-CC_SEV_CRI_CONTAINERD_K8S-PR/588/console

**Pull request merged**
