### PR TITLE
gpu: Remove the old SNP, TDX targets

### PR DESCRIPTION
**Pull request by zvonkok**
Remove the old SNP, TDX GPU related targets we no rely on #8872

Fixes:  #8873

### CODE REVIEW

**Comment by fidencio** [comment]
So, just to make it clear for the maintainers, all the tests are going to fail as we're removing a build target.
This is expected, and someone will have to mark the checks as non-required and then as required again.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @zvonkok!

**Review by jepio — APPROVED** [review]

**Comment by zvonkok** [comment]
Closing in favour #9026

**Pull request closed without merging**
