### PR TITLE
# Kata Containers 2.3.2

### PR DESCRIPTION
**Pull request by snir911**
- stable-2.3 | workflows: Use base instead of head ref for kata-deploy-test
- stable-2.3-backports
- [backport from main] agent: fix the issue of missing create a new session for container
- stable-2.3 - kata-deploy: validate conf file can be created
- stable-2.3 | kata-monitor: increase delay before syncing with the container manager
- stable-2.3 | versions: Upgrade to Cloud Hypervisor v21.0
- stable-2.3: backport lint fixes from main
- stable-2.3 | runtime: -Wl,--s390-pgste for s390x
- stable-2.3 | kata-manager: Retrieve static tarball
- stable-2.3 | ci: Pass function arguments in static-checks.sh

977f1f5b workflows: Use base instead of head ref for kata-deploy-test
99ed596a workflows: Fix typo in kata-deploy-push action
13b7d93b workflows: Ensure a label change re-triggers the actions
b8463224 workflows: Ensure force-skip-ci skips all actions
8c8571f4 workflows: Use the correct branch ref on test kata-deploy
620bb97e runtime: Provide protection for shared data
770d4acf tools: Fix groupname if it differs from username
cedb01d2 runtime: close span before return from function in case of error
a661e538 agent: fix the issue of missing create a new session for container
bed0f3c8 kata-deploy: validate conf file can be created
786c667e kata-monitor: increase delay before syncing with the container manager
e3b00f39 runtime: -Wl,--s390-pgste for s390x
3260adc4 virtcontainers: clh: Re-generate the client code
cc64461f versions: Upgrade to Cloud Hypervisor v21.0
f2c6cd08 ci: Pass function arguments in static-checks.sh
78afa10a agent: resolve unused variables in tests
a8298676 agent: remove unused field in mount handling
87f9a690 agent: drop unused fields from network
fc012a2b agent: clear cargo test warnings
63c5a8aa uevent: Fix clippy issue in test code
d1530afa kata-manager: Retrieve static tarball

### CODE REVIEW

**Comment by snir911** [comment]
adding dnm until[ test-kata-deploy](https://github.com/kata-containers/kata-containers/actions/runs/1779904331) passes 
/test

**Comment by fidencio** [comment]
To monitor: https://github.com/kata-containers/kata-containers/actions/runs/1779904331

**Comment by fidencio** [comment]
Still failing, with the same failure as before:
```
Run tag=$(echo $GITHUB_REF | cut -d/ -f3-)
  tag=$(echo $GITHUB_REF | cut -d/ -f3-)
  pushd $GITHUB_WORKSPACE
  git checkout $tag
  pkg_sha=$(git rev-parse HEAD)
  popd
  mv kata-static.tar.xz $GITHUB_WORKSPACE/tools/packaging/kata-deploy/kata-static.tar.xz
  docker build --build-arg KATA_ARTIFACTS=kata-static.tar.xz -t quay.io/kata-containers/kata-deploy-ci:$pkg_sha $GITHUB_WORKSPACE/tools/packaging/kata-deploy
  docker login -u *** -p *** quay.io
  docker push quay.io/kata-containers/kata-deploy-ci:$pkg_sha
  mkdir -p packaging/kata-deploy
  ln -s $GITHUB_WORKSPACE/tools/packaging/kata-deploy/action packaging/kata-deploy/action
  echo "::set-output name=PKG_SHA::${pkg_sha}"
  shell: /usr/bin/bash -e {0}
~/work/kata-containers/kata-containers ~/work/kata-containers/kata-containers
error: pathspec 'main' did not match any file(s) known to git
Error: Process completed with exit code 1.
```

At this point I think the best we can do is wait till https://github.com/kata-containers/kata-containers/pull/3587 gets tested, reviewed, and merged.

Hopefully that will work as expected for both `main` and `stable-*` branches.

**Comment by fidencio** [comment]
> /test_kata_deploy

```
Error from server (NotFound): deployments.apps "coredns" not found
[
  {
    "cloudName": "AzureCloud",
    "homeTenantId": "***",
    "id": "***",
    "isDefault": true,
    "managedByTenants": [],
    "name": "Microsoft Azure Sponsorship",
    "state": "Enabled",
    "tenantId": "***",
    "user": {
      "name": "***",
      "type": "servicePrincipal"
    }
  }
]
```

**Comment by fidencio** [comment]
> /test_kata_deploy

https://github.com/kata-containers/kata-containers/actions/runs/1786404062

Finally!

**Review by fidencio — APPROVED** [review]
lgtm, thanks @snir911!

**Review by egernst — APPROVED** [review]

**Pull request merged**
