### PR TITLE
debug: Test PR

### LINKED ISSUE #105: test: Test PR
See if CI is working

### PR DESCRIPTION
**Pull request by GabyCT**
This is a test PR to see if the CI is working.

Fixes #105 

Depends-on: github.com/kata-containers/tests#2194

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
@grahamwhaley , I am trying to enable the CI for this repository and it is performing the ./setup.sh from the test repository , however, it is running the part of the fast CI and even if I am modifying or adding a new script (which is just a test) is skipping the testing and putting that the fast CI is being enabled http://jenkins.katacontainers.io/job/kata-containers-rust-agent-ubuntu-18-04-PR/12/console any idea of why?
/cc @chavafg @jodh-intel

**Comment by grahamwhaley** [comment]
@GabyCT - that Jenkins link you posted (which is indeed the link from the CI status on this PR), points to the `rust-agent` build - I presume it is meant to point to the `kata-containers` build. So, I suspect somewhere in the setup (maybe on github...?), this repo is pointing to the wrong Jenkins CI job, and thus checking out and looking at the wrong source repo - so it does not see your test change, and thus does a fast path skip.....
I'm going to guess a copy/paste issue when setting up this repo - that we did not update a `rust-agent` line to a `kata-containers` line...?

**Comment by grahamwhaley** [comment]
@GabyCT - ah, forget that - I was confused (predominantly as the name of the repo is not the same as the name of the jenkins job, unlike our other repo/job relationships I think). I remember, the rust agent is *in* this repo.  Staring at the logs, it seems maybe the fast path is checking the master branch and not the PR branch, but I don't know why yet. Quite confusing. Still staring....

**Comment by grahamwhaley** [comment]
@GabyCT - OK, what I think is happening is that this repo is **not** being checked out to the relevant PR branch, because it is not listed as a kata repo in the resolve cloning code at https://github.com/kata-containers/tests/blob/master/.ci/resolve-kata-dependencies.sh#L64-L72
I think you need to add this repo path to a new var at the top of that file and add it to that list - and then hopefully you will see the `Fetching pull request` log entry, where the repo gets moved to the correct PR branch before we do the static/fast checks.

/cc @chavafg for more expertise in that area - I know the fast path code, but not so much the repo clone stuff ;-)

**Comment by chavafg** [comment]
thanks @grahamwhaley for the hints. You're right, we are not checking out to the PR. @GabyCT I think that you just need to add `kata-containers` repo to this list: https://github.com/kata-containers/tests/blob/master/.ci/resolve-kata-dependencies.sh#L10. With that, it should be able to checkout to the correct PR branch.

**Pull request closed without merging**
