### PR TITLE
CC: Rename SEV firmware to AMDSEV.fd

### PR DESCRIPTION
**Pull request by Alex-Carter01**
Renaming the output binary from the AmdSevPkg from OVMF.fd to AMDSEV.fd so it does not conflict with the base x86_64 build.

Changing install name in ovmf static builder and the location in the sev config file.

Fixes: #6337

### CODE REVIEW

**Review by fitzthum — APPROVED** [review]

**Comment by Alex-Carter01** [comment]
linking the correct new issue. had pointed to the snp x86_64 ovmf issue

**Review by larrydewey — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @Alex-Carter01!

**Comment by fidencio** [comment]
We can get this one merged as it doesn't affect TDX, and the queue is extremely long Today.

**Pull request merged**
