### PR TITLE
Split architecture doc into separate files

### PR DESCRIPTION
**Pull request by jodh-intel**
Move the architecture document to separate `docs/design/architecture/` directory and split some of the main sections into separate files to make the main file smaller and more manageable.

Fixes: #3246.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Note one frustration with this PR: the Kata 1.x -> Kata 2.x overview diagram (https://github.com/kata-containers/kata-containers/blob/main/docs/design/arch-images/shimv2.svg) is now in `history.md` meaning the doc has no overview diagram.

However, this will be addressed on #3245. We can re-use the diagram above but will need to remove the Kata 1.x part. See #3245 for details on what we need to change in that diagram.

**Review by devimc — APPROVED** [review]
lgtm

**Review by GabyCT — APPROVED** [review]

**Review by likebreath — APPROVED** [review]

**Review by cmaf — APPROVED** [review]
lgtm but I'll let @jodh-intel merge in case there anything still needs to be addressed in this or https://github.com/kata-containers/kata-containers/issues/3245 first

**Pull request merged**
