### PR TITLE
shimv2: Backport fixes for #2527

### LINKED ISSUE #2527: shimv2: Adding debugging msgs to shimv2 API calls
**Which feature do you think can be improved?**

Logging

**How can it be improved?**

Adding log msgs to shimv2 api calls 

**Additional Information**

It will make runtime debugging easier

### PR DESCRIPTION
**Pull request by c3d**
Backport @snir911's fixes for #2527 to stable-2.2.

Fixes #2527

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @c3d!

**Review by cmaf — APPROVED** [review]
thanks @c3d

**Comment by snir911** [comment]
Thanks!

**Pull request merged**
