### PR TITLE
agent: implement NVDIMM/PMEM block driver

### LINKED ISSUE #1289: [forward-port] support PMEM inside Kata Containers when running under Kubernetes
see https://github.com/kata-containers/runtime/issues/2262 for more details

### PR DESCRIPTION
**Pull request by devimc**
Support pmem-csi[1] k8s pluging, unlike SCSI and virtio devices,
NVDIMM/PMEM devices support DAX, improving IO Read and Write
operations.

fixes #1289

Signed-off-by: Julio Montes <julio.montes@intel.com>

[1]: https://github.com/intel/pmem-csi

### CODE REVIEW

**Comment by devimc** [comment]
@jodh-intel @lifupan @bergwolf @liubin  please take a look

**Review by GabyCT — APPROVED** [review]

**Review by likebreath — APPROVED** [review]
LGTM. Thanks @devimc

**Pull request merged**
