### PR TITLE
agent: fix the broken protobuf generation code

### PR DESCRIPTION
**Pull request by fengwang666**
After the protocols are moved to upper libs ([PR3355](https://github.com/kata-containers/kata-containers/pull/3355)),
the runtime protocol generation is broken. This fixes it.

Fixes: #3414

Signed-off-by: Feng Wang <feng.wang@databricks.com>

### CODE REVIEW

**Comment by fengwang666** [comment]
@lifupan @liubin PTAL

**Review by egernst — APPROVED** [review]
Thanks Feng

**Review by liubin — APPROVED** [review]

**Review by bergwolf — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @fengwang666!

**Review by jodh-intel — APPROVED** [review]
Thanks @fengwang666!

This does suggest we should be attempting to regenerate the code from the pb files in the CI as an extra test to avoid this sort of problem in future.

**Comment by jodh-intel** [comment]
Merging as the s390x issue cannot be related to this change...

**Pull request merged**
