### PR TITLE
support disable_guest_seccomp

### PR DESCRIPTION
**Pull request by quanweiZhou**
runtime-rs: support disable_guest_seccomp

support disable_guest_seccomp

Fixes: #4691

### CODE REVIEW

**Review by liubin — APPROVED** [review]

**Comment by jodh-intel** [comment]
@quanweiZhou - #4681 also touches `amend_spec()` so you might need to co-ordinate with @Tim-0731-Hzt on writing a new test?

**Comment by quanweiZhou** [comment]
> @quanweiZhou - #4681 also touches `amend_spec()` so you might need to co-ordinate with @Tim-0731-Hzt on writing a new test?

I think we can add two test functions, and then resolve the conflict when merging Cc @Tim-0731-Hzt.

**Comment by quanweiZhou** [comment]
> dinate with @Tim-0731-Hz

Thanks for your review, already add the test for `amend_spec`.

**Review by jodh-intel — APPROVED** [review]
Thanks @quanweiZhou.

lgtm

**Pull request merged**
