### PR TITLE
versions: update cni plugins version

### PR DESCRIPTION
**Pull request by littlejawa**
Use cni plugins v1.2.0 to get latest fixes.

Fixes: #6110

### CODE REVIEW

**Review by cmaf — APPROVED** [review]
thanks @littlejawa

**Comment by littlejawa** [comment]
- rebased to get the flannel update, hoping it'll fix some of the CI failures
- fixed a typo in the commit message

**Review by GabyCT — APPROVED** [review]

**Review by amshinde — APPROVED** [review]

**Pull request merged**
