### PR TITLE
acrn: Drop support

### PR DESCRIPTION
**Pull request by fidencio**
As we don't have any CI, nor maintainer to keep ACRN code around, we better have it removed than give users the expectation that it should or would work at some point.

cc @chavafg

### CODE REVIEW

**Comment by fidencio** [comment]
cc @kata-containers/architecture-committee, as I think this **MUST** be discussed in an AC meeting.

If it brings the attention of someone who may fancy the challenge to maintain it, then we don't drop it. :-)

**Comment by chavafg** [comment]
+1 
We couldn't find anyone inside Intel that can maintain the integration, which at this point must be broken as there hasn't been any CI in place.

**Comment by zvonkok** [comment]
Can we hold this until I am back? We may have resources around this. Thanks!

**Comment by fidencio** [comment]
> Can we hold this until I am back? We may have resources around this. Thanks!

We can hold till you're back, for sure.

**Comment by fidencio** [comment]
> We can hold till you're back, for sure.

It's been discussed in the AC meeting that if any work will be done with ACRN, we better target runtime-rs instead of wasting resources on trying to get it to work on go runtime first.

**Review by chavafg — APPROVED** [review]
As this was already discussed and agreed to remove in golang runtime in AC meeting, approving.

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
