### PR TITLE
metrics: Fix README for pytorch

### LINKED ISSUE #7689: metrics: fix pytorch readme reference

### PR DESCRIPTION
**Pull request by GabyCT**
This PR fixes the pytorch reference in the README file.

Fixes #7689

### CODE REVIEW

**Comment by portersrc** [comment]
Hi @GabyCT LGTM!

While we are here: Should the tensorflow example in the README also get updated? There's no `tensorflow.sh`; there are three such scripts with different suffixes.
Related to this: There _is_ a `tensorflow.sh` file in a similar folder in the [kata-continers/tests](https://github.com/kata-containers/tests/tree/main/metrics/machine_learning) repo. Do you know why there are duplicates?

**Comment by GabyCT** [comment]
> Hi @GabyCT LGTM!
> 
> While we are here: Should the tensorflow example in the README also get updated? There's no `tensorflow.sh`; there are three such scripts with different suffixes. Related to this: There _is_ a `tensorflow.sh` file in a similar folder in the [kata-continers/tests](https://github.com/kata-containers/tests/tree/main/metrics/machine_learning) repo. Do you know why we have both of these folders (and whether both are needed)?

@portersrc yes, let me do the update for tensorflow also, and regarding to the tests repository we are doing the migration from that repo to here so in the meantime there is going to be duplication

**Review by cmaf — APPROVED** [review]

**Review by dborquez — APPROVED** [review]

**Pull request merged**
