### PR TITLE
stable-2.4 | First round of backports for the 2.4.1 release

### PR DESCRIPTION
**Pull request by fidencio**
This round includes fixes for the following issues:
* #3816 
* #3695
* #4001
* #3756
* #3757
* #4043
* #4054
* #4063
* #4018
  * I'm not sure that I see this as a fix-up, but I'd be fine having it in, @fengwang666, @egernst, let me know your opinion on this
* #4061
* #3704
* #4140
* #4123
* #4151

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Review by egernst — APPROVED** [review]

**Comment by fidencio** [comment]
@jongwu, I am seeing failures with the ARM CI here in the stable-2.4 branch.
Are you aware of something?

See: http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-ARM-PR/3742/console

**Comment by jongwu** [comment]
@fidencio -, It seems there is no enough space for inotify user wathch in the ARM CI node. I have enlarged the number. let's see its next run.

**Comment by fidencio** [comment]
> @fidencio -, It seems there is no enough space for inotify user wathch in the ARM CI node. I have enlarged the number. let's see its next run.

And it worked like a charm, thanks for the very quick response @jongwu!

**Pull request merged**
