### PR TITLE
build-checks: Install protoc in the ci environments

### PR DESCRIPTION
**Pull request by ChengyuZhu6**
To test PR #8484, the compilation process for the kata-agent relies on protoc:
https://github.com/kata-containers/kata-containers/actions/runs/8016317290/job/21898040849?pr=8484 https://github.com/kata-containers/kata-containers/actions/runs/8016534530/job/21898654435?pr=8484 

Fixes: #9141

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
I wonder if it is worth mentioning in the commit message that it's image-rs that specifically has pulled in this requirement? I'll be interest to see if we need clang in `make test` now as well

**Review by BbolroC — APPROVED** [review]
LGTM, thanks @ChengyuZhu6 !

**Comment by ChengyuZhu6** [comment]
> I wonder if it is worth mentioning in the commit message that it's image-rs that specifically has pulled in this requirement? I'll be interest to see if we need clang in `make test` now as well

Sure. Let me try.

**Comment by ChengyuZhu6** [comment]
>I wonder if it is worth mentioning in the commit message that it's image-rs that specifically has pulled in this requirement?

Done.

**Comment by ChengyuZhu6** [comment]
we could remove clang in the ci: https://github.com/kata-containers/kata-containers/actions/runs/8017296177/job/21900866856?pr=8484

**Comment by ChengyuZhu6** [comment]
> > we could remove clang in the ci: https://github.com/kata-containers/kata-containers/actions/runs/8017296177/job/21900866856?pr=8484
> 
> Just to check I understand - we can remove it in the static build checks, but it's still needed in the agent component build?

yes. We still need clang: 
```
$ make agent-tarball
   Compiling rustls-webpki v0.102.2
   Compiling cgroups-rs v0.3.3
   Compiling webbrowser v0.8.12
   Compiling serde_with v3.6.1
   Compiling crypto_secretbox v0.1.1
   Compiling rsa v0.9.6
   Compiling tonic v0.9.2
   Compiling ed25519-dalek v2.1.1
   Compiling image-rs v0.1.0 (https://github.com/confidential-containers/guest-components?rev=4eb69cf#4eb69cf1)
   Compiling derive_builder v0.20.0
error: failed to run custom build command for `loopdev v0.5.0 (https://github.com/mdaffin/loopdev?rev=c9f91e8f0326ce8a3364ac911e81eb32328a5f27#c9f91e8f)`

Caused by:
  process didn't exit successfully: `/home/zcy/go/src/github.com/kata-containers/kata-containers/src/agent/target/release/build/loopdev-b6e640d1801884cc/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', /root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-be2141875385cea5/bindgen-0.63.0/./lib.rs:2338:31
```

**Review by GabyCT — APPROVED** [review]

**Review by danmihai1 — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @ChengyuZhu6!

**Pull request merged**
