### PR TITLE
metrics: Enable kata runtime in K8s for FIO test.

### PR DESCRIPTION
**Pull request by dborquez**
This PR configures the corresponding kata runtime in K8s based on the tested hypervisor.

This PR also enables FIO metrics test in the kata metrics-ci.

Fixes: #7665

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Review by chavafg — APPROVED** [review]

**Review by GabyCT — CHANGES_REQUESTED** [review]
@dborquez seems like ERROR: Found unexpected /opt/kata/bin/containerd-shim-kata-v2 present

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
