### PR TITLE
CCv0: Merge main into `ccv0`

### PR DESCRIPTION
**Pull request by stevenhorsman**
Weekly merge of main branch into CCv0 26th November

Fixes: #3132
Depends-on: github.com/kata-containers/tests#4226

Signed-off-by: stevenhorsman <steven@uk.ibm.com>

### CODE REVIEW

**Comment by stevenhorsman** [comment]
```
$ git diff --stat upstream/main -- . ':!*/vendor/*'
 .github/workflows/commit-message-check.yaml                                   |   2 +-
 docs/how-to/README.md                                                         |   3 +
 docs/how-to/ccv0.sh                                                           | 501 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 docs/how-to/how-to-build-and-test-ccv0.md                                     | 378 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/agent/protocols/build.rs                                                  |   1 +
 src/agent/protocols/protos/image.proto                                        |  31 ++++++
 src/agent/protocols/src/lib.rs                                                |   2 +
 src/agent/src/config.rs                                                       | 118 +++++++++++++++++++++++
 src/agent/src/image_rpc.rs                                                    | 231 ++++++++++++++++++++++++++++++++++++++++++++
 src/agent/src/main.rs                                                         |   1 +
 src/agent/src/rpc.rs                                                          | 111 ++++++++++++++++++---
 src/agent/src/sandbox.rs                                                      |   2 +
 src/runtime/go.mod                                                            |  40 ++++----
 src/runtime/go.sum                                                            | 412 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++---------------------
 src/runtime/pkg/containerd-shim-v2/create.go                                  |   5 +
 src/runtime/pkg/containerd-shim-v2/image.go                                   |  84 ++++++++++++++++
 src/runtime/pkg/katautils/config.go                                           |   1 +
 src/runtime/pkg/oci/utils.go                                                  |   5 +
 src/runtime/virtcontainers/agent.go                                           |   4 +
 src/runtime/virtcontainers/container.go                                       |   5 +
 src/runtime/virtcontainers/image/image.go                                     |  23 +++++
 src/runtime/virtcontainers/interfaces.go                                      |   4 +
 src/runtime/virtcontainers/kata_agent.go                                      |  25 +++++
 src/runtime/virtcontainers/mock_agent.go                                      |   5 +
 src/runtime/virtcontainers/pkg/agent/protocols/client/client.go               |   2 +
 src/runtime/virtcontainers/pkg/agent/protocols/grpc/image.pb.go               | 613 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/runtime/virtcontainers/pkg/mock/mock.go                                   |   4 +
 src/runtime/virtcontainers/pkg/vcmock/sandbox.go                              |   5 +
 src/runtime/virtcontainers/sandbox.go                                         |   9 ++
 tools/agent-ctl/src/client.rs                                                 | 112 +++++++++++++++++++++-
 tools/osbuilder/rootfs-builder/README.md                                      |   6 ++
 tools/osbuilder/rootfs-builder/rootfs.sh                                      |  77 ++++++++++++++-
 tools/osbuilder/rootfs-builder/signed-container-artifacts/README.md           |  14 +++
 tools/osbuilder/rootfs-builder/signed-container-artifacts/public.gpg          |  30 ++++++
 tools/osbuilder/rootfs-builder/signed-container-artifacts/quay_policy.json    |  18 ++++
 tools/osbuilder/rootfs-builder/signed-container-artifacts/signatures.tar      | Bin 0 -> 2157 bytes
 tools/osbuilder/rootfs-builder/ubuntu/Dockerfile-aarch64.in                   |   5 +
 tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in                           |   5 +
 tools/osbuilder/rootfs-builder/ubuntu/config.sh                               |   1 +
 tools/osbuilder/scripts/lib.sh                                                |  19 ++++
 tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml               |   2 +-
 tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml                 |   2 +-
 tools/packaging/kata-deploy/local-build/Makefile                              |   3 +
 tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-image.sh |  24 +++++
 versions.yaml                                                                 |  22 ++++-
 45 files changed, 2809 insertions(+), 158 deletions(-)
 ```

**Review by jodh-intel — APPROVED** [review]
Nice - thanks @stevenhorsman.

lgtm

**Comment by fidencio** [comment]
@stevenhorsman @jodh-intel, shall we relax the commit message check on this branch, making it non-required? Please, see: https://github.com/kata-containers/kata-containers/runs/4333237743?check_suite_focus=true

**Comment by jodh-intel** [comment]
Pasting the error here to make the issue clearer:

```
Run tim-actions/commit-message-checker-with-regex@v0.3.1
Error: 

  d08bcde7aa37c6270ecf3246d31169bf5f991f9c    Subject too long (max 75)

See the document below for help on formatting commits for the project.

https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format
```

@Tim-Zhang - It looks like this is triggering on a merge commit:

```
commit d08bcde7aa37c6270ecf3246d31169bf5f991f9c
Merge: 653b461d 6955d144
Author: Fabiano Fidêncio <fabiano@fidencio.org>
Date:   Fri Nov 19 15:58:55 2021 +0100

    Merge pull request #3068 from fidencio/wip/kata-deploy-re-add-latest-and-stable-tags

    kata-deploy: Add back stable & latest tags
```

```bash
$ echo -n 'Merge pull request #3068 from fidencio/wip/kata-deploy-re-add-latest-and-stable-tags' | wc -c
84
```

Is there a way to configure https://github.com/tim-actions/commit-message-checker-with-regex to ignore merge commits or particular branches?

**Comment by stevenhorsman** [comment]
FYI @jodh-intel, @fidencio - I've added https://github.com/kata-containers/kata-containers/pull/3133/commits/0214eac4c58aff3ab37b541877cd9d4351a47869 to allow the merge commit message to be longer than 75 chars. There is probably a nice way to do it though!

**Comment by fidencio** [comment]
> FYI @jodh-intel, @fidencio - I've added [0214eac](https://github.com/kata-containers/kata-containers/commit/0214eac4c58aff3ab37b541877cd9d4351a47869) to allow the merge commit message to be longer than 75 chars. There is probably a nice way to do it though!

I think that one should be proposed on the `main` branch, as sooner than later we'll see more development branches showing up here, and that will save folks some reasonable time.

Thanks, @stevenhorsman!

**Comment by jodh-intel** [comment]
@fidencio - sneaky - thanks! ;)

**Review by sameo — APPROVED** [review]

**Pull request merged**
