### PR TITLE
runtime: fix missing of VhostUserDeviceReconnect parameter assignment

### PR DESCRIPTION
**Pull request by markyangcc**
Below commit implements the vhost-user-blk reconnection functionality, 
[runtime: add reconnect timeout for vhost user block](https://github.com/kata-containers/kata-containers/pull/6076/commits/ca02c9f5124eb13af6c63b4be9e1ff1ec750bb48)

However, this commit has missed assigning `VhostUserDeviceReconnect` when new the QEMU HypervisorConfig, resulting in `VhostUserDeviceReconnect` always set to default value 0.

Fixes: #9848

### CODE REVIEW

**Review by justxuewei — APPROVED** [review]
Lgtm, thanks!

**Review by Apokleos — COMMENTED** [review]
Thx @markyangcc for your contribution. 
Could you please add [this message](https://github.com/kata-containers/kata-containers/pull/9849#issue-2353205200) to git's commit ？You can follow[ the example ](https://github.com/kata-containers/kata-containers/pull/9849#issue-2353205200) 
IMO, this maybe only involve small changes but as a result of go format causing the whole `HypervisorConfig` change(L909 ->L979)

**Comment by markyangcc** [comment]
> Thx @markyangcc for your contribution. Could you please add [this message](https://github.com/kata-containers/kata-containers/pull/9849#issue-2353205200) to git's commit ？You can follow[ the example ](https://github.com/kata-containers/kata-containers/pull/9849#issue-2353205200) IMO, this maybe only involve small changes but as a result of go format causing the whole `HypervisorConfig` change(L909 ->L979)

Yes, real change is this line, most of changes caused by go format,

```
return vc.HypervisorConfig{
	// ...
	VhostUserDeviceReconnect: h.VhostUserDeviceReconnect,
}, nil
```

Also, commit message updated.

**Review by Apokleos — APPROVED** [review]
Thx @markyangcc LGTM

**Pull request merged**
