### PR TITLE
Bump guest-components / trustee to a version that supports ITA

### PR DESCRIPTION
**Pull request by fidencio**
Please, see each commit for a better explanation.

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks, @fidencio.

lgtm

**Review by ChengyuZhu6 — APPROVED** [review]
LGTM thanks @fidencio

**Review by GabyCT — APPROVED** [review]

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks

**Review by stevenhorsman — APPROVED** [review]
Sorry, LGTM, I just had to re-re-read the commit message!

**Pull request merged**
