### PR TITLE
runtime.docs: Fixing s390 vfio-ap url

### LINKED ISSUE #8078: make static-checks failing with invalid url
# Description of problem

make static-checks is failing due to 404 url.

# Expected result

No error.

# Actual result

```
[static-checks.sh:544] ERROR: found HTTP error status codes for URL https://www.kernel.org/doc/html/latest/s390/vfio-ap.html (404)
ERROR: Invalid URL 'https://www.kernel.org/doc/html/latest/s390/vfio-ap.html' found in the following files:

src/runtime/virtcontainers/README.md
make: *** [Makefile:46: static-checks] Error 1
```

### PR DESCRIPTION
**Pull request by beraldoleal**
make static-checks are failing due to this error.

Fixes #8078

### CODE REVIEW

**Review by wainersm — APPROVED** [review]
The link is indeed broken. thanks @beraldoleal

**Review by GabyCT — APPROVED** [review]

**Comment by GabyCT** [comment]
@beraldoleal currently the `make static checks` is failing with
```
INFO: Spell checking file 'src/runtime/virtcontainers/README.md'
[kata-spell-check.sh:275] WARNING: Word 'executables': did you mean one of the following?: executable, executable s, executrices
ERROR: Spell check failed for file: 'src/runtime/virtcontainers/README.md'
```
could you please fix that? thanks

**Comment by beraldoleal** [comment]
Thank you @GabyCT.

IIUC, is this fix are you expecting?

https://github.com/kata-containers/tests/pull/5777

Or in another place?

**Comment by GabyCT** [comment]
> Thank you @GabyCT.
> 
> IIUC, is this fix are you expecting?
> 
> [kata-containers/tests#5777](https://github.com/kata-containers/tests/pull/5777)
> 
> Or in another place?

Please don't do it in the test repo as that soon will be disabled do it here put the word that are failing just between `` (for example `machine`) and that is it

**Pull request closed without merging**
