### PR TITLE
backport ci: Temporarily skip agent shutdown test on s390x

### PR DESCRIPTION
**Pull request by Jakob-Naucke**
backport of #2508

### CODE REVIEW

**Comment by Jakob-Naucke** [comment]
Oh great, of all the things, s390x is failing:
```
go: downloading golang.org/x/text v0.3.4
/home/jenkins/workspace/kata-containers-2.0-ubuntu-s390x-PR/go/pkg/mod/github.com/golang/protobuf@v1.4.3/proto/buffer.go:11:2: google.golang.org/protobuf@v1.25.0: reading https://proxy.golang.org/google.golang.org/protobuf/@v/v1.25.0.zip: 502 Bad Gateway
```

I can reach the URL at this time... /retest-s390x

**Comment by Jakob-Naucke** [comment]
```
not ok 1 Kubectl exec
# (in test file k8s-exec.bats, line 56)
#   `container_name=$(kubectl exec $pod_name -c $second_container_name -- env | grep CONTAINER_NAME)' failed
# [bats-exec-test:23] INFO: k8s configured to use runtimeclass
# pod/busybox created
# pod/busybox condition met
# Defaulted container "first-test-container" out of: first-test-container, second-test-container
# I0830 12:43:35.009467    6878 log.go:184] (0xc0000c73f0) (0xc000460280) Create stream
# I0830 12:43:35.009624    6878 log.go:184] (0xc0000c73f0) (0xc000460280) Stream added, broadcasting: 1
...
```

honestly looks like a one-off to me -- /retest-debian

**Review by fidencio — APPROVED** [review]
lgtm, thanks @Jakob-Naucke!

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
