### PR TITLE
Backport 3.2 | local-build: Remove GID before creating group

### PR DESCRIPTION
**Pull request by alex-matei**
docker install now creates a group with gid 999 which happens to match what we need to get docker-in-docker to work. Remove the group first as we don't need it.

Fixes: #7726
Signed-off-by: Jeremi Piotrowski <jpiotrowski@microsoft.com>
(cherry picked from commit 3b881fb)

EDIT: I added a commit to fix the dragonball build that was failing.

Fixes: #7888

### CODE REVIEW

**Comment by fidencio** [comment]
/test

We don't support this branch anymore, but we also don't prevent folks from building from this branch, so we can have it in.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @alex-matei

**Review by amshinde — APPROVED** [review]

**Comment by amshinde** [comment]
@alex-matei Static checks seem to be failing from last week. I have rerun them to see if they fail again. Can you take a look?

**Comment by alex-matei** [comment]
@amshinde I investigated the problem, it is related to versioning of dependencies in dragonball.  I opened a new issue #7888 and added a commit in this PR to fix it (I don't know rust, take it with a grain of salt).

**Comment by gkurz** [comment]
Superseder by #8022 .

**Comment by gkurz** [comment]
Superseded by #8022 .

**Comment by alex-matei** [comment]
@gkurz We need this commit https://github.com/kata-containers/kata-containers/pull/7779/commits/910ba10df2923e9ba4dee093910dd5d391ded545 from this PR in stable-3.2. It fixes issue #7888. Without it the make check for dragonball fails, as can be seen here for #8022: https://github.com/kata-containers/kata-containers/actions/runs/6480696226/job/17596724114?pr=8022 . I will open a new PR for it.

**Pull request closed without merging**
