### PR TITLE
# Kata Containers 3.0.0

### PR DESCRIPTION
**Pull request by bergwolf**
- stable-3.0: backport agent fixes
- backport fix for 3.0.0 release

fb4430549 release: Adapt kata-deploy for 3.0.0
20c02528e agent: reduce reference count for failed mount
3eb6f5858 agent: don't exit early if signal fails due to ESRCH
8dc8565ed versions: Update gperf url to avoid libseccomp random failures
740e7e2f7 kata-sys-util: fix typo `unknow`

### CODE REVIEW

**Comment by bergwolf** [comment]
https://github.com/kata-containers/kata-containers/actions/runs/3210457628

**Review by liubin — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @bergwolf!

**Pull request merged**
