### PR TITLE
docs: add agent policy documentation

### PR DESCRIPTION
**Pull request by danmihai1**
Add initial agent policy documentation.

 Fixes: #7671

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @danmihai1!

This will be expanded later with instructions on how to generate your own policy, as in, what can be blocked and how, right?

**Review by stevenhorsman — APPROVED** [review]
This looks like a great intro on policies to me. Thanks!

**Comment by danmihai1** [comment]
> lgtm, thanks @danmihai1!
> 
> This will be expanded later with instructions on how to generate your own policy, as in, what can be blocked and how, right?

Indeed. My next opportunity for such doc improvements will be https://github.com/kata-containers/kata-containers/pull/8248. That's an app generating relatively complex policies, that can be used as examples in the docs.

**Comment by fidencio** [comment]
Merging it as the CI won't be triggered for doc changes.

**Pull request merged**
