### PR TITLE
agent: fix panic on malformed device resource in container update

### PR DESCRIPTION
**Pull request by bergwolf**
Somehow containerd is sending a malformed device with empty device type in update API. While it
should not happen, we should not panic either.

Fixes: #946

### CODE REVIEW

**Review by liubin — APPROVED** [review]
LGTM, Thanks @bergwolf

**Comment by fidencio** [comment]
@bergwolf, I've added the needs-backport label but I'd ike to double-check with you ... as this is coming from containerd, there's a big chance the go agent also has the same issue, right?

**Comment by fidencio** [comment]
This looks like a non known error.
```
not ok 1 Block Storage Support
# (in test file k8s-block-volume.bats, line 46)
#   `kubectl wait --for condition=ready "pod/${pod_name}"' failed
# INFO: k8s configured to use runtimeclass
# storageclass.storage.k8s.io/local-storage created
# persistentvolume/block-loop-pv created
# persistentvolumeclaim/block-loop-pvc created
# pod/pod-block-pv created
# error: timed out waiting for the condition on pods/pod-block-pv
# pod "pod-block-pv" deleted
# persistentvolumeclaim "block-loop-pvc" deleted
# persistentvolume "block-loop-pv" deleted
# storageclass.storage.k8s.io "local-storage" deleted
Failed at 86: bats "${K8S_TEST_ENTRY}"
```

**Comment by bergwolf** [comment]
@fidencio go-agent works fine as it does not check the field

**Review by jodh-intel — APPROVED** [review]
Thanks @bergwolf.

**Review by fidencio — APPROVED** [review]
lgtm, thanks!

Would be niced to avoid merging this while the Ubuntu CI is failing (as Yesterday's night it was passing without any issue).

**Comment by bergwolf** [comment]
The commit itself can hardly break any normal case. The ubuntu CI issues on 2.0 seem to be related to temporary ubuntu environment issues. Now it  is working.

**Comment by fidencio** [comment]
> The commit itself can hardly break any normal case. The ubuntu CI issues on 2.0 seem to be related to temporary ubuntu environment issues. Now it is working.

Merged it, please! :-)

**Pull request merged**
