### PR TITLE
ci: Remove stdio tests

### PR DESCRIPTION
**Pull request by fidencio**
Since those tests have been added they never had a single green run.

As the maintainer who added those tests was already pinged and didn't reply for 2 weeks, I'm proposing to have those tests removed.

https://github.com/kata-containers/kata-containers/pull/10185#issuecomment-2295308757

cc @kata-containers/architecture-committee @Tim-Zhang

### CODE REVIEW

**Comment by stevenhorsman** [comment]
I'm mixed on whether to comment it out, or just revert https://github.com/kata-containers/kata-containers/pull/9534 to remove the code as I'm not sure if there is much benefit in leaving it commented unless there is a imminent plan to fix it, in which case an `if: false` condition might be simpler?

**Comment by Tim-Zhang** [comment]
@fidencio I'm sorry for missing your message. I totally agree with you to remove these tests because when I writing stdio tests I found it was hard to implement so now it looks hack, and it doesn't work properly now due to lack of testing.

**Review by Tim-Zhang — APPROVED** [review]

**Comment by fidencio** [comment]
> I'm mixed on whether to comment it out, or just revert #9534 to remove the code as I'm not sure if there is much benefit in leaving it commented unless there is a imminent plan to fix it, in which case an `if: false` condition might be simpler?

I am fine about removing the code, this PR was just to bring awareness to the problem.

**Comment by Tim-Zhang** [comment]
@stevenhorsman I think, we can keep that PR because it fixed https://github.com/kata-containers/kata-containers/issues/9532

**Comment by stevenhorsman** [comment]
> @stevenhorsman I think, we can keep that PR because it fixed #9532

Yes sorry for being unclear. I meant specifically https://github.com/kata-containers/kata-containers/pull/9534/commits/704da86e9bc24df6d292b4ae04454f813c6f263a

**Comment by fidencio** [comment]
@stevenhorsman, commit reverted, and we don't need to run CI on this one.

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
