### PR TITLE
runtime-rs: add support for core scheduling

### PR DESCRIPTION
**Pull request by Ji-Xinyou**
Linux 5.14 supports core scheduling to have better security control
for SMT siblings. This PR supports that for Rust runtime when containerd enables SCHED_SCORE in its configuration.

Fixes: #4429
Signed-off-by: Ji-Xinyou <jerryji0414@outlook.com>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @Ji-Xinyou.

lgtm

**Comment by Ji-Xinyou** [comment]
Thanks @Jodh-Intel, there is still a design issue that i am not sure about and need your insight.

In shim_run.rs, I log a warning if containerd sets SCHED_CORE but the systemcall failed. But in kata runtime 2.x (go version), it looks to me that if the systemcall failed, the shim does not start at all. Instead, it just returns instead.

Which approach do you think is more appropriate, I am not really sure about this.

**Comment by jodh-intel** [comment]
@Ji-Xinyou - in which case, I think we should retain the existing behaviour. I assume you're referring to:

https://github.com/kata-containers/kata-containers/pull/4310

/cc @egernst.

**Comment by liubin** [comment]
Since `runtime-rs` has been merged, please change your target branch to `main`.

**Comment by Ji-Xinyou** [comment]
@liubin Done, target branch changed to main.

**Review by liubin — APPROVED** [review]

**Pull request merged**
