### PR TITLE
packaging: fix initrd build

### PR DESCRIPTION
**Pull request by UnmeshDeodhar**
Fixing initrd build by providing correct suffix.

Fixes: #6388

### CODE REVIEW

**Review by fitzthum — APPROVED** [review]

**Comment by stevenhorsman** [comment]
The latest sev run errored with:
```
10:57:36 [init] Using Kubernetes version: v1.23.1
10:57:36 [preflight] Running pre-flight checks
10:57:36 error execution phase preflight: [preflight] Some fatal errors occurred:
10:57:36 	[ERROR Port-6443]: Port 6443 is in use
```
The cleanup step should reset Kubernetes, so I think the only thing I can do is hope that it worked and re-queue.

**Comment by UnmeshDeodhar** [comment]
@stevenhorsman I have cleaned up the k8s configuration and have restarted the jobs.

**Comment by fidencio** [comment]
s390x passed but didn't report back: http://jenkins.katacontainers.io/job/kata-containers-CCv0-ubuntu-20.04-s390x-PR/498/

**Pull request merged**
