### PR TITLE
kernel: add CONFIG_VIRTIO_MEM to whitelist.conf

### PR DESCRIPTION
**Pull request by Kvasscn**
When build kernel 5.4.32, the script report an error in fragment merging.
The reason is that Kernel 5.4.x not yet support Virtio Mem, so add
CONFIG_VIRTIO_MEM in whitelist.conf to avoid reporting error.

Fixes: #2644

Signed-off-by: zhanghj <zhanghj.lc@inspur.com>

### CODE REVIEW

**Review by sameo — APPROVED** [review]

**Review by cmaf — COMMENTED** [review]
@Kvasscn this works, but I'm wondering about the comment in whitelist.conf.
```
# configuration options which may dropped in newer kernels
# without generating an error in fragment merging
```
Since CONFIG_VIRTIO_MEM was introduced in later kernels, I wanted to double check that this is an acceptable use of whitelist.conf. (Maybe @sameo since he also reviewed?)

If so, should we also add kernel config options to the whitelist that cause the previous LTS setup to fail?

**Review by cmaf — APPROVED** [review]

**Comment by cmaf** [comment]
@Kvasscn once you rebase this to resolve the conflict we can merge it

**Comment by jodh-intel** [comment]
Marking as stale as this PR may have been abandoned.

**Comment by jodh-intel** [comment]
Any update on this @Kvasscn?

**Comment by fidencio** [comment]
A head's up that may affect your PR.

In the Architecture Committee meeting from January 25th, 2022, the Architecture Committee has agreed on using the "Dismiss stale pull request approvals when new commits are pushed" configuration from GitHub.  It basically means that if your PR has been rebased or updated, the approvals given will be erased.

In order to minimize traumas due to the new approach, please, consider adding a note on the changes done before the rebase / force-push, and also pinging the reviewers for a subsequent round of reviews.

Thanks for your understanding!

Related issue: https://github.com/kata-containers/community/issues/249

**Comment by fidencio** [comment]
As this PR has been waiting for an update since September 2021, I'm closing it for now.

@Kvasscn, please, if you find some free cycles to work on this PR, please, just re-open it and let us know.
Thanks for the contribution and looking forward to seeing an up-to-date version of this PR.

**Pull request closed without merging**
