### PR TITLE
runtime: Allow machine_type in kata config for remote hypervisors

### PR DESCRIPTION
**Pull request by squarti**
Fixes: #10211

### CODE REVIEW

**Review by skaegi — APPROVED** [review]
lgtm -- oops wrong repo, but this is a simple change that we need.

**Review by amshinde — APPROVED** [review]

**Review by Apokleos — APPROVED** [review]
Thx @squarti LGTM

**Comment by mkulke** [comment]
If we're defaulting to `q35` in the `h.machineType()` call, this will be set as pod annotation and conflict with the default instance size that is configured on a peerpod installation. We probably cannot use a defaulting logic here, since the runtime has no business in deciding a default for the "remote" in a remote hypervisor.

```
2024/09/02 13:55:02 [adaptor/cloud] Instance type selected by the cloud provider based on instance type annotation: q35
2024/09/02 13:54:37 [adaptor/cloud] error starting instance: creating an instance : failed to verify instance type: requested instance type ("q35") is not default ("Standard_DC2es_v5") and supported instance types list is empty
```

**Comment by mkulke** [comment]
> > If we're defaulting to `q35` in the `h.machineType()` call, this will be set as pod annotation and conflict with the default instance size that is configured on a peerpod installation. We probably cannot use a defaulting logic here, since the runtime has no business in deciding a default for the "remote" in a remote hypervisor.
> > ```
> > 2024/09/02 13:55:02 [adaptor/cloud] Instance type selected by the cloud provider based on instance type annotation: q35
> > 2024/09/02 13:54:37 [adaptor/cloud] error starting instance: creating an instance : failed to verify instance type: requested instance type ("q35") is not default ("Standard_DC2es_v5") and supported instance types list is empty
> > ```
> 
> Yeah, I see what you mean. The default for remote hypervisor should be "" unless specified in the runtime configuration. Should we change to `machineType := h.MachineType` ?

yup, I think that would fix it.

**Pull request merged**
