### PR TITLE
cargo: Disable verbose build

### LINKED ISSUE #2112: trace-forwarder build is noisy
I don't think we have any good reason to build it with `-v`.

### PR DESCRIPTION
**Pull request by sameo**
There are no reasons why we'd want all those gory details by default.

Fixes #2112

Signed-off-by: Samuel Ortiz <samuel.e.ortiz@protonmail.com>

### CODE REVIEW

**Review by fidencio — CHANGES_REQUESTED** [review]
While I don't disagree about the change, I'd like to ask whether we could change this also on `tools/agent-ctl/Makefile`.

With that we can ensure a pattern to be followed.

Thanks, @sameo.

**Comment by sameo** [comment]
> While I don't disagree about the change, I'd like to ask whether we could change this also on `tools/agent-ctl/Makefile`.
> 
> With that we can ensure a pattern to be followed.

Makes sense, I did not  see there was another one. Fixed  now.

**Review by fidencio — APPROVED** [review]
Thanks @sameo!

lgtm!

**Review by egernst — APPROVED** [review]

**Review by mxpv — APPROVED** [review]

**Comment by egernst** [comment]
(rerunning jenkins-ci-ubuntu-20-04 )...

**Review by jodh-intel — APPROVED** [review]
Thanks @sameo.

lgtm

**Comment by fidencio** [comment]
Howdy!

I'd like to ask you to rebase your PR atop of current `main`, as https://github.com/kata-containers/kata-containers/pull/2197 has been merged and it has a fix that unblocks the CI.

Please, do the rebase and feel free `@fidencio` in case you do not have the powers to run `/test`.

Sorry for the inconvenience and happy hacking!

**Comment by fidencio** [comment]
Hey, we've had yet another breakage in our CI and now it's fixed as part of https://github.com/kata-containers/kata-containers/pull/2203 ... it means that you'll need to rebase your PR atop of current main.

Sorry for the inconvenience.

**Comment by sameo** [comment]
This is no longer needed. Verbosity was removed with commits 27b299b and 6999dcc .

**Pull request closed without merging**
