### PR TITLE
fix wrong notes for func GetSandboxesStoragePathRust()

### PR DESCRIPTION
**Pull request by yanggangtony**
fix wrong notes for func GetSandboxesStoragePathRust()

### CODE REVIEW

**Review by Tim-0731-Hzt — APPROVED** [review]
LGTM

**Comment by liubin** [comment]
Thank you @yanggangtony , before this PR being merged, you need fix your commit message https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format

**Review by liubin — APPROVED** [review]

**Comment by yanggangtony** [comment]
@liubin 
thanks for review.

**Comment by Tim-0731-Hzt** [comment]
@yanggangtony, you need to raise an issue for this PR, and add Fixes:#XXX in the commit

**Comment by yanggangtony** [comment]
@Tim-0731-Hzt 
ah, thanks for the advice.
update it.

**Review by cmaf — APPROVED** [review]

**Comment by c3d** [comment]
@cmaf It looks like the jenkins-ci-s390x-unit-ubuntu-20-04 job completed several hours ago, but somehow github did not see it, so I cannot merge this. What is the procedure in that case?

**Pull request merged**
