### PR TITLE
kata-deploy: QEMU, for 2.x, already includes virtiofs

### PR DESCRIPTION
**Pull request by bergwolf**
There's no reason to ship qemu & qemu-virtiofs when the former already
includes vitiofs support (and that's the default for 2.x deployments).

In case we will enable experimental qemu DAX support, we should add a
new target, a "qemu-experimental" target, as Carlos has been working on.

Fixes: #1424

Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @bergwolf!
(And sorry I forgot to backport it).

By the way you may also need this whole PR: 2c8ea0a8d109441593853e207ba3ef78ff5b2f02 (which contains this fix here) and 10ed3da4ebe2b8b4df280f50b0df3578ce30d5fd

**Comment by bergwolf** [comment]
travis failed on network issues -- it reports that https://clearlinux.org/ is not accessible but I can open it on my side. Just tried to restart it a few times and all failed at the same place. IMO we can safely ignore it for now.

**Review by liubin — APPROVED** [review]

**Pull request merged**
