### PR TITLE
runtime: fix typo in sandbox.go

### LINKED ISSUE #8794: runtime: fixed sandbox.go typo
# Description of problem
comment typo in  sandbox.go

### PR DESCRIPTION
**Pull request by eltociear**
controler -> controller

Fixes #8794

### CODE REVIEW

**Review by Apokleos — APPROVED** [review]
Thx @eltociear LGTM!

**Review by Tim-0731-Hzt — APPROVED** [review]

**Comment by gkurz** [comment]
Hi @eltociear ! Please create an issue and add a corresponding `Fixes #XXXX` line in the changelog of the commit as required by our contribution [guidelines](https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#submit-issues-before-prs). This is mandatory to pass the required `Commit Message Check` test.

**Comment by Apokleos** [comment]
Sorry @eltociear I label it as "do-not-merge".
As @gkurz said above, we, who pushes request, need follow the community [guidelines](https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#submit-issues-before-prs).

**Pull request closed without merging**
