### PR TITLE
virtcontainers: Move unit tests for types/sandbox.go

### LINKED ISSUE #435: Some unit tests should be in a different directory
The unit tests for virtcontainers/types/sandbox.go and virtcontainers/types/container.go are in the parent directory instead of in virtcontainers/types, making it appear as if there is no coverage for `sandbox` and `container`. Some of these tests should be moved to the virtcontainers/types directory.

### PR DESCRIPTION
**Pull request by cmaf**
Move unit tests that were in virtcontainers/sandbox_test.go relating to Socket, Volume, and SandboxState to types/sandbox_test.go.

Change testSandboxStateTransition function to use SandboxState only instead of Sandbox from virtcontainers/sandbox.go.

Fixes #435

Signed-off-by: Chelsea Mafrica <chelsea.e.mafrica@intel.com>

### CODE REVIEW

**Comment by cmaf** [comment]
Ported from [#2853](https://github.com/kata-containers/runtime/pull/2853)

**Comment by bergwolf** [comment]
The ARM CI is trying to download non-existing cri-containerd binary. It is **NOT network issue**. /cc @Pennyzct 
```
Download tarball from https://storage.googleapis.com/cri-containerd-release/cri-containerd-3a4acfbc99aa976849f51a8edd4af20ead51d8d7.linux-arm64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 
```

**Comment by bergwolf** [comment]
ARM failure is unrelated and tracked at https://github.com/kata-containers/tests/issues/2743

Let's merge this.

**Pull request merged**
