### PR TITLE
agent: don't set permission of existing directory in copy_file

### LINKED ISSUE #6367: agent: copy_file unconditionally changes permission of existing parent directory
The handler of the `CopyFile` agent API unconditionally changes the permission of the parent directory of a target file.

`copy_file` copies a specified file in the host to the guest. When the parent of the target file path does not exist, `agent` creates the parent directory using ` fs::create_dir_all`. Then, `agent` set the permission of the parent directory based on `dir_mode` parameter of the `CopyFile` agent API.

This logic leads to override the permission of the parent directory, even when the parent directory already exists.  `copy_file` should not change the permission of the parent directory, when the parent directory already exists.

https://github.com/kata-containers/kata-containers/blob/44a780f262883ce5e1f3377a844a5320d9713b51/src/agent/src/rpc.rs#L1880-L1896

`CopyFile` is used in peer pods, and this issue causes incorrect directory permissions of Kubernetes Volumes.
https://github.com/confidential-containers/cloud-api-adaptor/issues/616

### PR DESCRIPTION
**Pull request by yoheiueda**
This patch fixes the issue that do_copy_file changes the directory permission of the parent directory of a target file, even when the parent directory already exists.

Fixes #6367

### CODE REVIEW

**Review by liubin — APPROVED** [review]

**Review by YushuoEdge — APPROVED** [review]

**Review by stevenhorsman — APPROVED** [review]
LGTM, so once the tests are passing I think we can merge this. Thanks @yoheiueda!

**Comment by stevenhorsman** [comment]
It looks like the two failing tests are `dragonball` on ARM (which is failing for other PRs and not required), and qemu-devmapper, which is failing with the:
```
INFO: Install Kubernetes
Install Kubernetes components
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: no valid OpenPGP data found.
```
issue, which I think it due to a google cloud issues, so we are probably blocked until that is resolved.

**Pull request merged**
