### PR TITLE
# Kata Containers 2.3.3

### PR DESCRIPTION
**Pull request by egernst**
- back port:: runtime: make selinux configurable
- stable-2.3 | kata-deploy: Use (kata with) qemu as the default shim-v2 binary
- stable-2.3 | shim: log events for CRI-O
- stable-2.3 | agent: fix invalid hooks env issues
- stable-2.3 | packaging: Use `patch` for applying patches

0b6e9f83 runtime: make selinux configurable
408477a2 kata-deploy: Use (kata with) qemu as the default shim-v2 binary
9431498e shim: log events for CRI-O
406f00a3 packaging: Use `patch` for applying patches
7af719e4 agent: handle hook process result
9b34cf46 agent: valid envs for hooks
9c195364 agent: Fix execute_hook() args error
9bea3a42 agent: check environment variables if empty or invalid

### CODE REVIEW

**Review by Jakob-Naucke — APPROVED** [review]
Thank you @egernst -- nothing remaining from my side.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @egernst!

**Comment by egernst** [comment]
ARM failure:
```
09:01:46 === RUN   TestCreateSandboxNoopAgentSuccessful
09:01:46     api_test.go:149: 
09:01:46         	Error Trace:	api_test.go:149
09:01:46         	Error:      	Received unexpected error:
09:01:46         	            	mkdir call failed: mkdir /tmp/vc/mockfs/sbs/7f49d00d-1995-4156-8c79-5f5ab24ce138: no such file or directory
09:01:46         	Test:       	TestCreateSandboxNoopAgentSuccessful
09:01:46     api_test.go:150: 
09:01:46         	Error Trace:	api_test.go:150
09:01:46         	Error:      	Expected value not to be nil.
09:01:46         	Test:       	TestCreateSandboxNoopAgentSuccessful
09:01:46     api_test.go:154: 
09:01:46         	Error Trace:	api_test.go:154
09:01:46         	Error:      	Expected value not to be nil.
09:01:46         	Test:       	TestCreateSandboxNoopAgentSuccessful
09:01:46 --- FAIL: TestCreateSandboxNoopAgentSuccessful (0.06s)
09:01:46 panic: runtime error: invalid memory address or nil pointer dereference [recovered]
09:01:46 	panic: runtime error: invalid memory address or nil pointer dereference
09:01:46 [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x91bb04]
09:01:46 
09:01:46 goroutine 135 [running]:
09:01:46 testing.tRunner.func1.2({0xa43620, 0x13d3060})
09:01:46 	/usr/local/go/src/testing/testing.go:1209 +0x258
09:01:46 testing.tRunner.func1(0x40001836c0)
09:01:46 	/usr/local/go/src/testing/testing.go:1212 +0x278
09:01:46 panic({0xa43620, 0x13d3060})
09:01:46 	/usr/local/go/src/runtime/panic.go:1038 +0x224
09:01:46 github.com/kata-containers/kata-containers/src/runtime/virtcontainers.TestCreateSandboxNoopAgentSuccessful(0x40001836c0)
09:01:46 	/home/jenkins/workspace/kata-containers-2.0-ubuntu-ARM-PR/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/api_test.go:156 +0x2d4
09:01:46 testing.tRunner(0x40001836c0, 0xbbc588)
09:01:46 	/usr/local/go/src/testing/testing.go:1259 +0x100
09:01:46 created by testing.(*T).Run
09:01:46 	/usr/local/go/src/testing/testing.go:1306 +0x350
09:01:46 FAIL	github.com/kata-containers/kata-containers/src/runtime/virtcontainers	0.099s
09:01:46 ?   	github.com/kata-containers/kata-containers/src/runtime/virtcontainers/device/api	[no test files]
```

**Comment by fidencio** [comment]
> /test_kata_deploy

https://github.com/kata-containers/kata-containers/runs/5379079329?check_suite_focus=true

**Pull request merged**
