### PR TITLE
ci: Transition GARM tests to free runners, pt. II

### PR DESCRIPTION
**Pull request by wainersm**
This is a continuation of @sprt 's efforts to migrate our workflows from GARM to free runners. His https://github.com/kata-containers/kata-containers/issues/9940 tracks the migration of non-k8s workflows, which he has either disabled or already migrated. This PR, however, is focused on migrating all the k8s workflows to free runners because 1) it will save money from our azure subscription likewise; 2) GARM is broken and it might block our 3.7.0 release

You will noticed that I started just migrating the workflows but then I decided to merge two of them (merge run-k8s-tests-on-garm and run-k8s-tests-with-crio-on-garm) which will force re-triggering of CI on existing PRs I guess. Well, I had it broke already then I decided to go further and renamed the jobs :)

>Note: This will reduce the number of jobs executed in half - 1. With GARM we have two VM profiles ("small" and "normal") which run subsets of k8s tests each (see https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/run_kubernetes_tests.sh#L27 and   https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/run_kubernetes_tests.sh#L77). I removed the `instance-type` parameter from the matrix and set `K8S_TEST_HOST_TYPE: all` which will make it to run both "small" and "normal" tests on a single job (hence reducing the amount of jobs triggered).

@fidencio ^^ please let me know if I am missing something and I cannot merge "small" and "normal" jobs.

Ok, tested on my fork of kata-containers:
 * Before the merge of merge run-k8s-tests-on-garm and run-k8s-tests-with-crio-on-garm: https://github.com/wainersm/kata-containers/actions/runs/9912848706
 * After the merge and rename: https://github.com/wainersm/kata-containers/actions/runs/9913412674

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @wainersm!

**Review by GabyCT — APPROVED** [review]

**Comment by stevenhorsman** [comment]
As discussed on slack - adding a hold to this until 3.7.0 is released

**Review by stevenhorsman — APPROVED** [review]
The job name gets interesting when the whole `k8s-extra-params` is added, but that's not a big concern, so the PR looks good to me. Thanks

**Comment by wainersm** [comment]
> The job name gets interesting when the whole `k8s-extra-params` is added, but that's not a big concern, so the PR looks good to me. Thanks

Indeed, it will generate bizarre names. So I will change to:
```
diff --git a/.github/workflows/run-k8s-tests-on-amd64.yaml b/.github/workflows/run-k8s-tests-on-amd64.yaml
index 7f86da8e7..107e73a9f 100644
--- a/.github/workflows/run-k8s-tests-on-amd64.yaml
+++ b/.github/workflows/run-k8s-tests-on-amd64.yaml
@@ -47,7 +47,6 @@ jobs:
             snapshotter: ""
             instance: ubuntu-22.04
             k8s: k0s
-            k8s-extra-params: '--cri-socket remote:unix:///var/run/crio/crio.sock --kubelet-extra-args --cgroup-driver="systemd"'
     runs-on: ${{ matrix.instance }}
     env:
       DOCKER_REGISTRY: ${{ inputs.registry }}
@@ -56,7 +55,7 @@ jobs:
       PR_NUMBER: ${{ inputs.pr-number }}
       KATA_HYPERVISOR: ${{ matrix.vmm }}
       KUBERNETES: ${{ matrix.k8s }}
-      KUBERNETES_EXTRA_PARAMS: ${{ matrix.k8s-extra-params }}
+      KUBERNETES_EXTRA_PARAMS: ${{ matrix.container_runtime != 'crio' && '' ||  '--cri-socket remote:unix:///var/run/crio/crio.sock --kubelet-extra-args --cgroup-driver="systemd"' }}
       SNAPSHOTTER: ${{ matrix.snapshotter }}
       USING_NFD: "false"
       K8S_TEST_HOST_TYPE: all
```

**Comment by wainersm** [comment]
Updates:
 * rebased & resolved conflict
 * removed `k8s-extra-params` from the matrix (@stevenhorsman)
 * added a commit to remove the `instance` from the matrix too
 
@sprt are you happy with this PR?

**Comment by wainersm** [comment]
ah, forgot to mention that I tested the latest updates in https://github.com/wainersm/kata-containers/actions/runs/10290188339/job/28479596129

**Comment by stevenhorsman** [comment]
This is a workflow only change that isn't tested by the PR checks as it is not triggered with a on/pull_request. It also has at least two reviews with the `force-skip-ci` label, therefore we can skip the CI and use admin rights to merge this.

**Comment by sprt** [comment]
ACK

**Pull request merged**
