### PR TITLE
runtime: Create tracer later in shimv2

### LINKED ISSUE #1411: runtime from main branch fails to read shimv2 configPath option
Building latest on main, the configPath is not being honored for shimv2.

If you specify configpath as part of your containerd configuration, it will pass the config path as an option to the v2 as part of the create request.

On main branch e830192fcab199dac9c7c2166182bd28adb797ce, I see this fail:
```
[eernst@localhost runtime]$ sudo ctr run --rm --runtime-config-path /etc/kata-containers/configuration-qemu.toml --runtime io.containerd.kata-qemu.v2  -t docker.io/library/busybox:latest test3 sh
ctr: io.containerd.kata.v2: Cannot find usable config file (config file "/etc/kata-containers/configuration.toml" unresolvable: file /etc/kata-containers/configuration.toml does not exist, config file "/usr/share/defaults/kata-cont
ainers/configuration.toml" unresolvable: file /usr/share/defaults/kata-containers/configuration.toml does not exist)
```

Stable 2.0 works as expected:

```
[eernst@localhost runtime]$ sudo ctr run --rm --runtime-config-path /etc/kata-containers/configuration-qemu.toml --runtime io.containerd.kata-qemu.v2  -t docker.io/library/busybox:latest test3 sh
/ #
```

You'll see same behavior if you're calling from crictl and leveraging the containerd config toml.

### PR DESCRIPTION
**Pull request by cmaf**
Remove loading of configuration from New() so that it is not loaded more
than once. Start tracer in create() so that it is created after the
runtime config is loaded in its original location.

Fixes #1411

Signed-off-by: Chelsea Mafrica <chelsea.e.mafrica@intel.com>

### CODE REVIEW

**Comment by egernst** [comment]
Thanks! Code looks good. May be worth adding a bit more into commit message highlighting the problem of loading in New() phase (ie, don't know where the correct configuration.toml for the runtime is located at that point).

Other than that, LGTM!

**Comment by cmaf** [comment]
@egernst good call, I added a little more detail. 

/test

**Review by egernst — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
@cmaf,

The change LGTM, but I must admit I didn't run the tests, but I'm taking @egernst's word on that.

I'd like to suggest adding a test case just to avoid regressions on this, but that can come as a follow-up patch.

**Review by jodh-intel — APPROVED** [review]
Thanks @cmaf.

**Pull request merged**
