### PR TITLE
CCv0: Update dependencies to v0.6.0 for release

### PR DESCRIPTION
**Pull request by sprt**
This updates image-rs, attestation-agent, and td-shim to v0.6.0 for the upcoming release.

### CODE REVIEW

**Review by fitzthum — APPROVED** [review]
LGTM

**Review by Xynnn007 — APPROVED** [review]
lgtm, thanks!

**Review by jepio — APPROVED** [review]

**Comment by stevenhorsman** [comment]
SEV failed with:
```
07:53:29 Err:5 https://packages.cloud.google.com/apt kubernetes-xenial-unstable Release
07:53:29   Certificate verification failed: The certificate is NOT trusted. The certificate issuer is unknown.  Could not handshake: Error in the certificate verification. [IP: 142.250.189.174 443]
```
so I've re-queued it.

**Comment by stevenhorsman** [comment]
The other three jobs failed with:
```
 Compiling prost-types v0.8.0
error[E0061]: this function takes 3 arguments but 2 arguments were supplied
   --> /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.3/src/util_libc.rs:110:14
    |
110 |     let fd = open(path.as_ptr() as *const _, libc::O_RDONLY | libc::O_CLOEXEC);
    |              ^^^^------------------------------------------------------------- an argument of type `u32` is missing
    |
note: function defined here
   --> /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.145/src/unix/linux_like/linux/musl/lfs64.rs:112:26
    |
112 | pub unsafe extern "C" fn open64(
    |                          ^^^^^^
help: provide the argument
    |
110 |     let fd = open(path.as_ptr() as *const _, libc::O_RDONLY | libc::O_CLOEXEC, /* u32 */);
    |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
which is more of a problem. This was seen on `main` in https://github.com/kata-containers/kata-containers/issues/7032, so I think it's best to cherry-pick the fix into `CCv0`

**Comment by stevenhorsman** [comment]
> which is more of a problem. This was seen on `main` in #7032, so I think it's best to apply that fix into `CCv0`

https://github.com/kata-containers/kata-containers/pull/7038 created to hopefully fix this issue in `CCv0` and once that's merged we can re-run these tests.

**Comment by stevenhorsman** [comment]
> @sprt - I think you will need to rebase this PR to get the static checks passing.

FYI - As there was some urgency, I did the rebase for you.

/test

**Pull request merged**
