### PR TITLE
CCv0: agent: validate hugepage size is supported

### PR DESCRIPTION
**Pull request by snir911**
before setting a limit, otherwise paths may not be found. guest supporting different hugepage size is more likely with peer-pods where podvm may use different flavor.

(sent only against CCv0 however, it may make sense to port also to main)
Fixes: #5191
Signed-off-by: Snir Sheriber <ssheribe@redhat.com>

### CODE REVIEW

**Review by pmores — APPROVED** [review]
Looks good to me!

**Comment by snir911** [comment]
@liubin do you think it should be ported  also to main?

**Comment by gkurz** [comment]
> (sent only against CCv0 however, it may make sense to port also to main)

I'm a bit confused by the workflow... if this PR fixes something in main, why don't we merge it in main first and then backport to CCv0 ?

**Comment by snir911** [comment]
> > (sent only against CCv0 however, it may make sense to port also to main)
> 
> I'm a bit confused by the workflow... if this PR fixes something in main, why don't we merge it in main first and then backport to CCv0 ?

The reason is that i know it's essential for peer-pods where host and podvm may support different hugepage sizes. I was not even sure it's possible in kata where guest is an actual virtual machine which eventually using/sharing the same cpu

**Comment by snir911** [comment]
updated:
```
@@ -261,7 +261,7 @@ fn set_hugepages_resources(
     let hugetlb_controller = cg.controller_of::<HugeTlbController>();
 
     for l in hugepage_limits.iter() {
-        if hugetlb_controller.is_none() || hugetlb_controller.unwrap().size_supported(&l.page_size)
+        if hugetlb_controller.is_some() && hugetlb_controller.unwrap().size_supported(&l.page_size)
         {
             let hr = HugePageResource {
                 size: l.page_size.clone(),
@@ -271,7 +271,7 @@ fn set_hugepages_resources(
         } else {
             warn!(
                 sl!(),
-                "{} page size is not supported, dropping requested limit", l.page_size
+                "{} page size support cannot be verified, dropping requested limit", l.page_size
             );
         }
     }
```
/test
@gkurz

**Review by gkurz — APPROVED** [review]
LGTM and it was a good opportunity to read some more rust code ! :smile:

Thanks @snir911 !

**Comment by amshinde** [comment]
@snir911 LGTM. I would suggest first get this applied to main and then backport to CCV0. I think we have seen similar errors on the main branch.

**Pull request merged**
