### PR TITLE
CCv0: Merge main into CCv0 branch

### PR DESCRIPTION
**Pull request by Megan-Wright**
Merge remote-tracking branch 'upstream/main' into CCv0

Fixes: #6126
Signed-off-by: Megan Wright <megan.wright@ibm.com>

### CODE REVIEW

**Comment by Megan-Wright** [comment]
```
git diff --stat upstream/main -- . ':!*/vendor/*'
 src/runtime/Makefile                                                            |  122 +++++
 src/runtime/arch/amd64-options.mk                                               |    2 +
 src/runtime/cmd/kata-runtime/kata-check_amd64.go                                |    2 +
 src/runtime/cmd/kata-runtime/kata-check_arm64.go                                |    3 +
 src/runtime/cmd/kata-runtime/kata-check_ppc64le.go                              |    3 +
 src/runtime/cmd/kata-runtime/kata-check_s390x.go                                |    3 +
 src/runtime/config/configuration-clh-tdx.toml.in                                |  443 ++++++++++++++++++
 src/runtime/config/configuration-clh.toml.in                                    |    2 +-
 src/runtime/config/configuration-qemu-sev.toml.in                               |  675 ++++++++++++++++++++++++++
 src/runtime/config/configuration-qemu-tdx.toml.in                               |  651 ++++++++++++++++++++++++++
 src/runtime/config/configuration-qemu.toml.in                                   |   27 +-
 src/runtime/go.mod                                                              |    3 +-
 src/runtime/go.sum                                                              |  282 +----------
 src/runtime/hack/update-generated-hypervisor-proto.sh                           |   13 +
 src/runtime/pkg/README.md                                                       |    1 +
 src/runtime/pkg/containerd-shim-v2/create.go                                    |    5 +
 src/runtime/pkg/containerd-shim-v2/image.go                                     |   84 ++++
 src/runtime/pkg/govmm/qemu/qemu.go                                              |   28 +-
 src/runtime/pkg/govmm/qemu/qmp.go                                               |   66 +++
 src/runtime/pkg/katautils/config-settings.go.in                                 |    7 +
 src/runtime/pkg/katautils/config.go                                             |  272 ++++++-----
 src/runtime/pkg/oci/utils.go                                                    |    5 +
 src/runtime/pkg/oci/utils_test.go                                               |    2 +-
 src/runtime/pkg/sev/README.md                                                   |   14 +
 src/runtime/pkg/sev/ovmf.go                                                     |  101 ++++
 src/runtime/pkg/sev/sev.go                                                      |  217 +++++++++
 src/runtime/pkg/sev/sev_test.go                                                 |   54 +++
 src/runtime/pkg/sev/testdata/README.md                                          |    9 +
 src/runtime/pkg/sev/testdata/ovmf_suffix.bin                                    |  Bin 0 -> 4096 bytes
 src/runtime/pkg/sev/vcpu_sigs.go                                                |   76 +++
 src/runtime/pkg/sev/vcpu_sigs_test.go                                           |   21 +
 src/runtime/pkg/sev/vmsa.go                                                     |  172 +++++++
 src/runtime/protocols/hypervisor/hypervisor.pb.go                               | 1848 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/runtime/protocols/hypervisor/hypervisor.proto                               |   46 ++
 src/runtime/protocols/simple-kbs/keybroker.pb.go                                |  573 +++++++++++++++++++++++
 src/runtime/protocols/simple-kbs/keybroker.proto                                |   68 +++
 src/runtime/protocols/simple-kbs/keybroker_grpc.pb.go                           |  141 ++++++
 src/runtime/vendor/github.com/containerd/containerd/plugin/plugin.go            |    4 +
 src/runtime/vendor/github.com/containerd/containerd/runtime/v2/shim/shim.go     |    6 +-
 src/runtime/vendor/github.com/containerd/containerd/runtime/v2/task/image.pb.go |  565 ++++++++++++++++++++++
 src/runtime/vendor/github.com/containerd/containerd/runtime/v2/task/image.proto |   37 ++
 src/runtime/vendor/modules.txt                                                  |    3 +-
 src/runtime/virtcontainers/acrn.go                                              |    9 +
 src/runtime/virtcontainers/agent.go                                             |    3 +
 src/runtime/virtcontainers/clh.go                                               |   15 +-
 src/runtime/virtcontainers/container.go                                         |    5 +
 src/runtime/virtcontainers/fc.go                                                |    4 +
 src/runtime/virtcontainers/fs_share_linux.go                                    |   57 ++-
 src/runtime/virtcontainers/hypervisor.go                                        |  434 +++++------------
 src/runtime/virtcontainers/hypervisor_config_darwin.go                          |    4 +
 src/runtime/virtcontainers/hypervisor_config_linux.go                           |    4 +
 src/runtime/virtcontainers/hypervisor_linux.go                                  |    2 +
 src/runtime/virtcontainers/image/image.go                                       |   24 +
 src/runtime/virtcontainers/interfaces.go                                        |    3 +
 src/runtime/virtcontainers/kata_agent.go                                        |  155 ++++--
 src/runtime/virtcontainers/mock_agent.go                                        |    5 +
 src/runtime/virtcontainers/mock_hypervisor.go                                   |    4 +
 src/runtime/virtcontainers/monitor.go                                           |   11 +-
 src/runtime/virtcontainers/mount.go                                             |   24 +-
 src/runtime/virtcontainers/pkg/agent/protocols/client/client.go                 |   35 ++
 src/runtime/virtcontainers/pkg/agent/protocols/grpc/image.pb.go                 |  613 ++++++++++++++++++++++++
 src/runtime/virtcontainers/pkg/mock/mock.go                                     |    4 +
 src/runtime/virtcontainers/pkg/vcmock/sandbox.go                                |    5 +
 src/runtime/virtcontainers/qemu.go                                              |  120 ++++-
 src/runtime/virtcontainers/qemu_amd64.go                                        |  234 ++++++++-
 src/runtime/virtcontainers/qemu_amd64_test.go                                   |   24 +-
 src/runtime/virtcontainers/qemu_arch_base.go                                    |   56 ++-
 src/runtime/virtcontainers/remote.go                                            |  298 ++++++++++++
 src/runtime/virtcontainers/sandbox.go                                           |   74 +--
 src/runtime/virtcontainers/types/sandbox.go                                     |   12 +
 70 files changed, 7990 insertions(+), 904 deletions(-)
```

**Review by GabyCT — APPROVED** [review]

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
