### PR TITLE
CCv0 | CCv0: Merge from main -- August 1st

### PR DESCRIPTION
**Pull request by fidencio**
Conflicts:
        src/runtime/pkg/katautils/config.go
        src/runtime/virtcontainers/container.go
        src/runtime/virtcontainers/hypervisor.go
        src/runtime/virtcontainers/qemu_arch_base.go
        src/runtime/virtcontainers/sandbox.go
        tests/integration/kubernetes/gha-run.sh
        tests/integration/kubernetes/setup.sh
        tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml
        tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh
        tools/packaging/kata-deploy/scripts/kata-deploy.sh
        tools/packaging/kernel/kata_config_version
        versions.yaml

### CODE REVIEW

**Review by wainersm — APPROVED** [review]
@fidencio it is a bunch of stuff...if the tests pass I think we will be good :)

**Comment by fidencio** [comment]
CLH TDX passed but didn't report back: http://10.112.240.228:8080/job/kata-containers-CCv0-cloud-hypervisor-TDX-CRI_CONTAINERD_K8S-PR/1052/console

**Pull request merged**
