### PR TITLE
agent: add configurable container pipe size cmdline option

### LINKED ISSUE #152: Add cmdline option to configure stdout/stderr pipe size
This ticket is to add a cmdline option to configure the stdout/stderr pipe size. Should only configure it if the cmdline option is present.

See https://github.com/kata-containers/runtime/issues/2467 for more context.

### PR DESCRIPTION
**Pull request by awprice**
Adds a cmdline option to configure the stdout/stderr pipe sizes.
Uses `F_SETPIPE_SZ` to resize the write side of the pipe after
creation.

Example Cmdline option: `agent.container_pipe_size=2097152`

fixes #152

Signed-off-by: Alex Price <aprice@atlassian.com>

### CODE REVIEW

**Comment by awprice** [comment]
Equivalent PR for the Go agent - https://github.com/kata-containers/agent/pull/756

**Comment by awprice** [comment]
Tests pass. I've noticed that the tests that I added to `src/agent/rustjail/src/process.rs` didn't seem to get run:
```
running 21 tests
test config::tests::test_get_hotplug_timeout ... ok
test config::tests::test_get_container_pipe_size ... ok
test config::tests::test_logrus_to_slog_level ... ok
test config::tests::test_new ... ok
test config::tests::test_get_log_level ... ok
test mount::tests::test_get_cgroup_mounts ... ok
test mount::tests::test_get_mount_fs_type_from_file ... ok
test mount::tests::test_mount ... ok
test mount::tests::test_remove_mounts ... ok
test namespace::tests::test_namespace_type ... ok
test namespace::tests::test_setup_persistent_ns ... ok
test sandbox::tests::add_and_get_container ... ok
test sandbox::tests::get_container_entry_exist ... ok
test config::tests::test_parse_cmdline ... ok
test sandbox::tests::remove_sandbox_storage ... ok
test sandbox::tests::get_container_no_entry ... ok
test sandbox::tests::unset_and_remove_sandbox_storage ... ok
test sandbox::tests::set_sandbox_storage ... ok
test tests::test_setup_debug_console_invalid_shell ... ok
test tests::test_setup_debug_console_no_shells ... ok
test sandbox::tests::unset_sandbox_storage ... ok
test result: ok. 21 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```
Should they have been run?

**Comment by lifupan** [comment]
> Tests pass. I've noticed that the tests that I added to `src/agent/rustjail/src/process.rs` didn't seem to get run:
> 
> ```
> running 21 tests
> test config::tests::test_get_hotplug_timeout ... ok
> test config::tests::test_get_container_pipe_size ... ok
> test config::tests::test_logrus_to_slog_level ... ok
> test config::tests::test_new ... ok
> test config::tests::test_get_log_level ... ok
> test mount::tests::test_get_cgroup_mounts ... ok
> test mount::tests::test_get_mount_fs_type_from_file ... ok
> test mount::tests::test_mount ... ok
> test mount::tests::test_remove_mounts ... ok
> test namespace::tests::test_namespace_type ... ok
> test namespace::tests::test_setup_persistent_ns ... ok
> test sandbox::tests::add_and_get_container ... ok
> test sandbox::tests::get_container_entry_exist ... ok
> test config::tests::test_parse_cmdline ... ok
> test sandbox::tests::remove_sandbox_storage ... ok
> test sandbox::tests::get_container_no_entry ... ok
> test sandbox::tests::unset_and_remove_sandbox_storage ... ok
> test sandbox::tests::set_sandbox_storage ... ok
> test tests::test_setup_debug_console_invalid_shell ... ok
> test tests::test_setup_debug_console_no_shells ... ok
> test sandbox::tests::unset_sandbox_storage ... ok
> test result: ok. 21 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
> ```
> 
> Should they have been run?

Yeah, the tests in subcrates didn't run. I had submit a PR https://github.com/kata-containers/kata-containers/pull/156 to address this issue.

**Comment by awprice** [comment]
@jodh-intel Could I get a review on this please?

**Comment by jodh-intel** [comment]
I spy a lovely green button to press...

**Comment by jodh-intel** [comment]
Thanks again @awprice!

**Pull request merged**
