### PR TITLE
[2.1.0] kernel: configs: Open CONFIG_VIRTIO_MEM in x86_64 Linux kernel

### PR DESCRIPTION
**Pull request by teawater**
Open CONFIG_VIRTIO_MEM in x86_64 Linux kernel.

Fixes: #1798

Signed-off-by: Hui Zhu <teawater@antfin.com>

Porting from https://github.com/kata-containers/kata-containers/pull/1799

### CODE REVIEW

**Comment by fidencio** [comment]
@teawater, as https://github.com/kata-containers/kata-containers/pull/1799#issuecomment-834124507, here we also need to bump https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kernel/kata_config_version

**Review by fidencio — APPROVED** [review]
lgtm, thanks @teawater!

**Review by liubin — APPROVED** [review]

**Pull request merged**
