### PR TITLE
kernel: Add console kernel config for s390

### PR DESCRIPTION
**Pull request by BbolroC**
This config is to update console kernel config for s390. This gets boot time messages displayed again to journal.

Fixes: #6162

Signed-off-by: Hyounggyu Choi <Hyounggyu.Choi@ibm.com>

### CODE REVIEW

**Review by cmaf — COMMENTED** [review]
@BbolroC, I think we should also increment `kata_config_version` with this update

**Comment by amshinde** [comment]
@BbolroC lgtm, please update `kata_config_version` file as @cmaf suggested.

**Comment by BbolroC** [comment]
@cmaf @amshinde Thanks for the review. I've just updated the version. :wink:

**Review by liubin — APPROVED** [review]

**Review by cmaf — APPROVED** [review]

**Comment by BbolroC** [comment]
The PR is all about s390x config. Why don't we merge this?

**Comment by BbolroC** [comment]
@GabyCT I was wondering if you could review and merge this. It is just simple config change. :wink: Thanks.

**Pull request merged**
