### PR TITLE
# Kata Containers 3.0.0-rc1

### PR DESCRIPTION
**Pull request by gkurz**
- tools: release: fix bogus version check
- osbuilder: Export directory variables for libseccomp
- kata-deploy: support runtime-rs for kata deploy
- Last backport for 3.0-rc1
- stable-3.0: backport runtime/runtime-rs dependency updates

babab160bc61 tools: release: fix bogus version check
af22e7137500 osbuilder: Export directory variables for libseccomp
b0c5f040f02f runtime-rs: set agent timeout to 0 for stream RPCs
d44e39e0592c runtime-rs: fix incorrect comments
43b0e95800f6 runtime: store the user name in hypervisor config
81801888a29f runtime: make StopVM thread-safe
fba39ef32d03 runtime: add more debug logs for non-root user operation
63309514cacc runtime-rs: drop dependency on rustc-serialize
e229a03cc814 runtime: update runc dependency
d663f110d737 kata-deploy: get the config path from cri options
c6b3dcb67d5f kata-deploy: support kata-deploy for runtime-rs
a394761a5cc7 kata-deploy: add installation for runtime-rs

### CODE REVIEW

**Comment by gkurz** [comment]
https://github.com/kata-containers/kata-containers/actions/runs/3152567270

**Review by bergwolf — APPROVED** [review]
Thanks!

**Pull request merged**
