### PR TITLE
Update Kata to use qemu-6.1

### PR DESCRIPTION
**Pull request by dgibson**
qemu-6.1 is now released.  This includes a bunch of things we've been carrying around patches for, and also ACPI hotplug support for q35 which we need to fix some future problems.

Update our packaging to use the new qemu version.

### CODE REVIEW

**Comment by bergwolf** [comment]
On qemu-experimental, does qemu-6.1 support virtio-fs dax?

**Comment by dgibson** [comment]
> On qemu-experimental, does qemu-6.1 support virtio-fs dax?

I think so, but I don't know the code well enough to be sure.

**Comment by bergwolf** [comment]
@stefanha could you help to clarify qemu v6.1 status of virtio-fs dax support?

**Comment by stefanha** [comment]
> @stefanha could you help to clarify qemu v6.1 status of virtio-fs dax support?

DAX is not yet supported in QEMU 6.1.

**Comment by bergwolf** [comment]
Thanks @stefanha !

Hi @dgibson, since dax is not supported by qemu v6.1,  we still need the qemu-experimental branch as its main goal is to provide a virtiofs dax-enabled version of qemu.

**Comment by dgibson** [comment]
Ok, I've changed the series to keep the experimental branch, and move the virtiofs-dax patches forwards to it.  Not entirely sure how to test that the patches still all apply properly on the experimental version - AFAICT the CI doesn't use it.  I'm trying to do a manual attempt with Wainer's vagrant stuff, but I'm not really sure what I'm doing.

**Comment by dgibson** [comment]
@stefanha the virtio fs dax patches that are in the Kata tree no longer apply clean to v6.1.  I could probably rebase them, but it seems like it would be more sensible to grab a new snapshot of the virtio-fs-dax branch.  Where would I find that?

**Comment by stefanha** [comment]
> @stefanha the virtio fs dax patches that are in the Kata tree no longer apply clean to v6.1. I could probably rebase them, but it seems like it would be more sensible to grab a new snapshot of the virtio-fs-dax branch. Where would I find that?

@dagrh can advise about the best git tree to use. He's working on upstreaming DAX in QEMU.

**Comment by dgibson** [comment]
Ok, new version updates qemu-experimental to current tree that @dagrh pointed me towards.

**Review by jcvenegas — APPROVED** [review]

**Review by jcvenegas — CHANGES_REQUESTED** [review]
Sorry,  seems that qemu 6.1.0 build in snap is broken, l will block this PR with `requested-changes`

**Comment by dgibson** [comment]
I think I've fixed the snap problem.

/test
/test-vfio

**Review by c3d — APPROVED** [review]
Looks good to me. Thanks!

**Review by jcvenegas — APPROVED** [review]

**Comment by jcvenegas** [comment]
@dgibson  I is green but there is a problem with s390x build

**Comment by GabyCT** [comment]
The error is the following
```
Applying patch: /home/jenkins/workspace/kata-containers-2.0-ubuntu-s390x-PR/go/src/github.com/kata-containers/kata-containers/tools/packaging/qemu/patches/6.1.x/*.patch
error: can't open patch '/home/jenkins/workspace/kata-containers-2.0-ubuntu-s390x-PR/go/src/github.com/kata-containers/kata-containers/tools/packaging/qemu/patches/6.1.x/*.patch': No such file or directory
```
/cc @Jakob-Naucke

**Comment by dgibson** [comment]
1

> The error is the following
> 
> ```
> Applying patch: /home/jenkins/workspace/kata-containers-2.0-ubuntu-s390x-PR/go/src/github.com/kata-containers/kata-containers/tools/packaging/qemu/patches/6.1.x/*.patch
> error: can't open patch '/home/jenkins/workspace/kata-containers-2.0-ubuntu-s390x-PR/go/src/github.com/kata-containers/kata-containers/tools/packaging/qemu/patches/6.1.x/*.patch': No such file or directory
> ```
> 
> /cc @Jakob-Naucke

Gah. Looks like the scripts in the tests repo break if the patches directory (not the tag_patches directory) has no patches in it, even with no_patches.txt.  Why s390 is going through that path when the other builds don't, I have no idea, but for whatever reason it is.

**Comment by dgibson** [comment]
Urgh.  Ok, so the "static build" path used by most of the targets uses the patching scripts from within the kata-containers repo, which work.  The other build path uses patching logic from the tests repo, which breaks in this case.

**Comment by devimc** [comment]
please fix your `Depends-on`  -> `Depends-on: github.com/kata-containers/tests#3958`

**Comment by Jakob-Naucke** [comment]
See #2618 for the now-occurring s390x failure, which is unrelated to this PR.

**Comment by dgibson** [comment]
> See #2618 for the now-occurring s390x failure, which is unrelated to this PR.

Thanks for the information.  I suspected that failure was unrelated, but it's good to have it confirmed.

I think we're ready to merge.  Any objections?

**Pull request merged**
