### PR TITLE
CCv0: update dependencies for CoCo release 0.5.0

### PR DESCRIPTION
**Pull request by wainersm**
Updated the following dependencies:

 * td-shim to commit [10568bab569bc40034cc973f26fbb0a768dcc3e3](https://github.com/confidential-containers/td-shim/commit/10568bab569bc40034cc973f26fbb0a768dcc3e3)
 * attestation-agent to commit [c939d211fe5ac497715008e36161aff20cabb6e6](https://github.com/confidential-containers/attestation-agent/commit/c939d211fe5ac497715008e36161aff20cabb6e6)
 * image-rs to commit [b28eaae46bcea69ac28d079381b7aa1ef6851ad9](https://github.com/confidential-containers/image-rs/commit/b28eaae46bcea69ac28d079381b7aa1ef6851ad9)

### CODE REVIEW

**Comment by wainersm** [comment]
Added the do-not-merge label because it is still using intermediary image-rs and ocicrypt-rs trees.

**Comment by wainersm** [comment]
Hi @kata-containers/intel ,

Could someone give more details about the failed jenkins-ci-tdx-x86_64-cc_cri_containerd_k8s-qemu and jenkins-ci-tdx-x86_64-cc_cri_containerd_k8s-cloud-hypervisor  jobs?

**Comment by wainersm** [comment]
As https://github.com/confidential-containers/image-rs/pull/138 was merged, I updated this PR to use the upstream image-rs tree

**Comment by fidencio** [comment]
```
18:59:20 $ cargo xbuild -p td-shim --target x86_64-unknown-none --no-default-features --features main,tdx --profile release
18:59:20 Build timed out (after 20 minutes). Marking the build as aborted.
19:19:20 .ci/install_kata.sh: line 72: 3703878 Terminated              "${cidir}/install_td_shim.sh"
```

I wonder if we need to adjust something on the script used to build td-shim, @wainersm

**Comment by wainersm** [comment]
> ```
> 18:59:20 $ cargo xbuild -p td-shim --target x86_64-unknown-none --no-default-features --features main,tdx --profile release
> 18:59:20 Build timed out (after 20 minutes). Marking the build as aborted.
> 19:19:20 .ci/install_kata.sh: line 72: 3703878 Terminated              "${cidir}/install_td_shim.sh"
> ```
> 
> I wonder if we need to adjust something on the script used to build td-shim, @wainersm

hmmm... it seems so. I will try to reproduce that error. Thanks for the logs @fidencio !

**Comment by fidencio** [comment]
TDX QEMU succeeded but didn't report back: http://10.112.240.208:8080/job/kata-containers-CCv0-qemu-TDX-CRI_CONTAINERD_K8S-PR/863/console

**Comment by wainersm** [comment]
> > ```
> > 18:59:20 $ cargo xbuild -p td-shim --target x86_64-unknown-none --no-default-features --features main,tdx --profile release
> > 18:59:20 Build timed out (after 20 minutes). Marking the build as aborted.
> > 19:19:20 .ci/install_kata.sh: line 72: 3703878 Terminated              "${cidir}/install_td_shim.sh"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I wonder if we need to adjust something on the script used to build td-shim, @wainersm
> 
> hmmm... it seems so. I will try to reproduce that error. Thanks for the logs @fidencio !

@fidencio I could build td-shim on my machine. But I just noticed one thing: the log above shows that the jenkins job was aborted after 20min.... probably there is a timeout of "inactive" that aborts the job after X minutes of logs not coming to the console. Could you try to increase that timeout?

**Comment by fidencio** [comment]
Cloud Hypervisor TDX has passed: http://10.112.240.208:8080/job/kata-containers-CCv0-cloud-hypervisor-TDX-CRI_CONTAINERD_K8S-PR/828/

**Review by fidencio — APPROVED** [review]
lgtm, thanks @wainersm!

**Pull request merged**
