### PR TITLE
ci: kernel no sudo

### PR DESCRIPTION
**Pull request by zvonkok**
Build kernel without sudo docker this is not needed. This is part 4 of N

### CODE REVIEW

**Comment by zvonkok** [comment]
```
✦ ❯ ls -lh build/kernel-nvidia-gpu/{builddir,destdir}
build/kernel-nvidia-gpu/builddir:
total 176M
drwxr-xr-x 27 zvonkok zvonkok 4.0K May 28 11:17 kata-linux-6.1.62-131
-rw-r--r--  1 root    root     17M May 28 11:17 kata-static-kernel-nvidia-gpu-headers.tar.xz
-rw-r--r--  1 root    root     14M May 28 11:17 kata-static-kernel-nvidia-gpu.tar.xz
-rw-r--r--  1 root    root     103 May 28 11:17 kernel-nvidia-gpu-sha256sum
-rw-r--r--  1 zvonkok zvonkok 129M May 28 10:06 linux-6.1.62.tar.xz
-rw-r--r--  1 zvonkok zvonkok   86 May 28 10:04 linux-6.1.62.tar.xz.sha256
-rw-r--r--  1 zvonkok zvonkok 8.4M May 28 11:18 linux-headers-6.1.62-nvidia-gpu_6.1.62-nvidia-gpu-5_amd64.deb
-rw-r--r--  1 zvonkok zvonkok 7.1M May 28 11:18 linux-image-6.1.62-nvidia-gpu_6.1.62-nvidia-gpu-5_amd64.deb
-rw-r--r--  1 zvonkok zvonkok 1.3M May 28 11:18 linux-libc-dev_6.1.62-nvidia-gpu-5_amd64.deb
-rw-r--r--  1 zvonkok zvonkok 6.1K May 28 11:18 linux-upstream_6.1.62-nvidia-gpu-5_amd64.buildinfo
-rw-r--r--  1 zvonkok zvonkok 2.1K May 28 11:18 linux-upstream_6.1.62-nvidia-gpu-5_amd64.changes
-rw-r--r--  1 zvonkok zvonkok  79K May 28 10:04 sha256sums.asc

build/kernel-nvidia-gpu/destdir:
total 4.0K
drwxr-xr-x 3 zvonkok zvonkok 4.0K May 28 10:07 opt
```

The final tarball is not owned by the user since we're doing a sudo tar in kata-deploy-binaries.sh. Once we have all parts build without sudo the final tarball should be owned by the user as well.

**Comment by fidencio** [comment]
lgtm, thanks @zvonkok!

**Review by dborquez — APPROVED** [review]
lgtm, thanks @zvonkok

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
