### PR TITLE
static-build,clh: Add the ability to build from a PR

### PR DESCRIPTION
**Pull request by fidencio**
Right now it doesn't do much for us, as we're always building from a
specific version.  However, this opens the possibility for us to add a
CI, similar to the one we have for CRI-O, for testing against each
cloud-hypervisor PR, on the cloud-hypervisor branch.

Fixes: #3908

Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

### CODE REVIEW

**Comment by jongwu** [comment]
arm ci fails as there is a bug in the latest code of [acpica](https://github.com/acpica/acpica/pulls). I'll fix it in the qemu uefi installation script.

**Review by devimc — APPROVED** [review]

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
