### PR TITLE
shimv2: handle ctx passed by containerd

### LINKED ISSUE #1088: shimv2 cannot be shutdown due to container list not empty
Forward port of https://github.com/kata-containers/runtime/issues/2992.

### PR DESCRIPTION
**Pull request by cmaf**
Sometimes shim process cannot be shutdown because of container list
is not empty. This container list is written in shim service, while
creating container. We find that if containerd cancel its Create
Container Request due to timeout, but runtime didn't handle it properly
and continue creating action, then this container cannot be deleted at
all. So we should make sure the ctx passed to Create Service rpc call
is effective.

Fixes #1088

Signed-off-by: Yves Chan <shanks.cyp@gmail.com>
Signed-off-by: Chelsea Mafrica <chelsea.e.mafrica@intel.com>

### CODE REVIEW

**Comment by cmaf** [comment]
This is a forward port of https://github.com/kata-containers/runtime/pull/2991 which was already merged.

backport pr: https://github.com/kata-containers/runtime/pull/2991

**Review by egernst — APPROVED** [review]

**Comment by egernst** [comment]
Looks good. Hoping the CI is content.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @cmaf!

**Comment by fidencio** [comment]
* **jenkins-ci-ubuntu-1804-cloud-hypervisor-k8s-containerd-2.0**:
```
08:39:39 # wipe any partition on sdb and add the device as LVM_DEVICE variable
08:39:39 device=/dev/sdb
08:39:39 echo "LVM_DEVICE=\"$device\"" | sudo tee -a /etc/environment
08:39:39 mount | grep -q $device && sudo umount $(mount | grep $device | cut -d' ' -f1)
08:39:39 sudo dd if=/dev/zero of=$device bs=128M count=1
08:39:39 	deploymentName=ubuntu1804-azure1203071608710
08:39:39 	osType=Linux
08:39:39 	publicDNSName=ubuntu1804-azuref40ea0.eastus2.cloudapp.azure.com
08:39:39 	sshPort=22
08:39:39 	mode=EXCLUSIVE
08:39:39 	templateName=ubuntu1804-azure
08:39:39 	cleanUpAction=DELETE
08:39:39 ] which is computer com.microsoft.azure.vmagent.AzureVMComputer@529b7d91 and has channel null
```
So, lack of space. I wonder if we should limit ourselves to only store the logs / artifacts for 10 days, instead of 30.  It's been proven 30 days has made us hit out of space several times in the past.  The question is, does someone sees a clear and strong reason to keep the artifacts around for more than 10 days?

**Pull request merged**
