### PR TITLE
runtime: Add support for key annotations to remote hyp

### PR DESCRIPTION
**Pull request by bpradipt**
Fixes: #7140

### CODE REVIEW

**Comment by bpradipt** [comment]
> Channeling Fabiano whilst he is on vacation I think he would request that some of the information from the issue was added to the commit body so that develops can see the reason for adding without have to go to github.
> 
> The code looks good though and I'll need to remember to cherry-pick this into my remote-hypervisor -> main branch once it gets merged into `CCv0`

I updated the commit message and also added a reference to the cloud-api-adaptor PR for completeness sake.

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks!

**Review by GabyCT — APPROVED** [review]

**Comment by stevenhorsman** [comment]
@bpradipt - it's worth noting that we'll need to bump the operator to pick up the latest kata-containers-runtime-ci payload in order to pick this code up so we can use it in CAA. I'll try and get a PR for that created this afternoon

**Comment by stevenhorsman** [comment]
> @bpradipt - it's worth noting that we'll need to bump the operator to pick up the latest kata-containers-runtime-ci payload in order to pick this code up so we can use it in CAA. I'll try and get a PR for that created this afternoon

Done: https://github.com/confidential-containers/operator/pull/220

**Pull request merged**
