### PR TITLE
kernel: Add CONFIG_SEV_GUEST to SEV kernel config

### PR DESCRIPTION
**Pull request by Alex-Carter01**
Adding kernel config to sev case since it is needed for SNP and SNP will use the SEV kernel. Incrementing kernel config version to reflect changes.

Fixes: #6123
Signed-off-by: Alex Carter <Alex.Carter@ibm.com>

### CODE REVIEW

**Comment by Alex-Carter01** [comment]
@dubek @fitzthum

**Review by GabyCT — APPROVED** [review]

**Review by amshinde — APPROVED** [review]

**Review by cmaf — APPROVED** [review]
thanks @Alex-Carter01

**Comment by jpecholt** [comment]
Out of curiosity, how do you build the kernel? There exists a specific config fragment for SNP [here](https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kernel/configs/fragments/x86_64/snp/snp.conf) that has the required configurations. To use it, you follow this guide / section [here](https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-run-kata-containers-with-SNP-VMs.md#how-to-build):
```sh
$ pushd kata-containers/tools/packaging/kernel/
$ ./build-kernel.sh -a x86_64 -x snp setup
$ ./build-kernel.sh -a x86_64 -x snp build
$ sudo -E PATH="${PATH}" ./build-kernel.sh -x snp install
$ popd
```

**Comment by Alex-Carter01** [comment]
> Out of curiosity, how do you build the kernel? There exists a specific config fragment for SNP [here](https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kernel/configs/fragments/x86_64/snp/snp.conf) that has the required configurations. To use it, you follow this guide / section [here](https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-run-kata-containers-with-SNP-VMs.md#how-to-build):
> 
> ```shell
> $ pushd kata-containers/tools/packaging/kernel/
> $ ./build-kernel.sh -a x86_64 -x snp setup
> $ ./build-kernel.sh -a x86_64 -x snp build
> $ sudo -E PATH="${PATH}" ./build-kernel.sh -x snp install
> $ popd
> ```
> 
> Edit: If the SEV kernel is supposed to support both SEV and SEV-SNP, it makes sense to clean that config fragment up, or if they are to remain separate, it makes sense to use two configs?

@jpecholt My understanding is that the goal is for the SEV kernel to also support SNP and unify them. I would be on board to remove the snp config and [entry from the version file](https://github.com/kata-containers/kata-containers/blob/7fc35f19eb4a0d6591ab9991d8a2b1802adf3a23/versions.yaml#L105).

I just want to check if there are any objections first. I can add that I have tested SNP with the SEV kernel (just getting a pod running, not verified)

@fitzhum is there anything else missing to just use the SEV kernel?

**Comment by larrydewey** [comment]
@Alex-Carter01 will you re-base this?

**Review by jepio — APPROVED** [review]
LGTM. I'll create a follow-up issue for the removal of ptp-kvm from guest that we discussed in the SNP wg call.

**Comment by Alex-Carter01** [comment]
rebased

**Pull request merged**
