### PR TITLE
agent: overwrite OCI process spec when overwriting pause image

### PR DESCRIPTION
**Pull request by squarti**
The PR replaces the OCI process spec of the pause container with the spec of
the guest provided pause bundle.

Fixes: https://github.com/kata-containers/kata-containers/issues/10537

### CODE REVIEW

**Comment by stevenhorsman** [comment]
I think the RH folks use https://github.com/confidential-containers/cloud-api-adaptor/commit/f6f1223b4b475b02d839fff51affb189867016fe which renames the pause binary in the podvm build that helps with this problem? @bpradipt could confirm. However I'm not against this improvement

**Comment by bpradipt** [comment]
> I think the RH folks use [confidential-containers/cloud-api-adaptor@f6f1223](https://github.com/confidential-containers/cloud-api-adaptor/commit/f6f1223b4b475b02d839fff51affb189867016fe) which renames the pause binary in the podvm build that helps with this problem? @bpradipt could confirm. However I'm not against this improvement

I think this approach is more flexible and will allow the same image to be used with crio and containerd without changing the pause binary name in config or the VM image.

**Review by stevenhorsman — APPROVED** [review]
This looks reasonable to me. Thanks @squarti!

**Review by bpradipt — APPROVED** [review]
/lgtm
Thanks @squarti

**Comment by squarti** [comment]
@stevenhorsman @bpradipt Any chance to get this change in 3.11.0 release?

**Comment by stevenhorsman** [comment]
> @stevenhorsman @bpradipt Any chance to get this change in 3.11.0 release?

Yeah, I'm just investigating some of the CI failures

**Pull request merged**
