### PR TITLE
runtime-rs: ignore unconfigured network interfaces

### PR DESCRIPTION
**Pull request by cheriL**
Ignore unconfigured network interfaces like tunl0 when create endpoints.

Fixes: #7020

### CODE REVIEW

**Review by Tim-0731-Hzt — APPROVED** [review]
Thanks @cheriL LGTM

**Review by lifupan — APPROVED** [review]

**Comment by cheriL** [comment]
Do I need rebase? Seems like a compilation problem of kata-ctl in the static check.

**Review by amshinde — APPROVED** [review]

**Comment by ananos** [comment]
@cheriL can you rebase with current main, squash so we can kick-off a retest?

**Comment by cheriL** [comment]
@ananos done

**Comment by ananos** [comment]
@cheriL can you also squash the format/clippy commits to the main one as these only refer to the same files?

**Comment by cheriL** [comment]
@ananos Fixed.

**Pull request merged**
