### PR TITLE
stable-2.3 Missing backports

### PR DESCRIPTION
**Pull request by snir911**
b1f4e945b365f95521dbb5d9f2948023f38ec9f4 security: Update rust crate versions **(modifed and cargo updated)**
99ef52a3 osbuilder: Add protoc to the alpine container
d1bc409d osbuilder: avoid to copy versions.txt which already deprecated
cb5c948a kata-manager: Retrieve static tarball
84571506 kata-deploy: Deal with empty containerd conf file
2ebaaac7 osbuilder: be runtime consistent also with podman build
39b35d00 agent: user container ID as watchable storage key for hashmap

d79268ac6519088b21011772a61337bcc9930699 tools/packaging: add copyright to kata-monitor's Dockerfile
428cf0a685865d53c4a65f3f69d275644bec09df packaging: delint tests dockerfiles
1ea9b703830d4f618c3f4ab628d5f371f3043058 packaging: delint kata-deploy dockerfiles
aeb2b673b31103509d2e992ebb1f88836f54e39e ci/openshift-ci: delint dockerfiles
aeb2b673b31103509d2e992ebb1f88836f54e39e osbuilder: delint dockerfiles
bc120289ec9e838099e96ae2cc078e90bcc8630f packaging: delint kata-monitor dockerfiles
bc71dd5812dbda6f2dbb919716de1732040c9496 packaging: delint static-build dockerfiles
2938bb7f892483f0674e16baa00a5a3702d8dbe0 packaging/qemu: Use QEMU script to update submodules
5d49ccd613c2090711a22aa7214f4b6708642ae8 packaging/qemu: Use partial git clone

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @snir911!

**Comment by fidencio** [comment]
s390x and arm:
```
ERROR: Required Copyright header check ('Copyright') failed for the following files:

tools/packaging/kata-monitor/Dockerfile
```

We're mssing the backport of #3109

**Comment by fidencio** [comment]
> 

And it seems that oin ARM / s390x we may be running the static checks based on `main` rather than on the branch used, as the static checks on the dockerfiles was only added as part of kata-containers/tests#4194.

For the sake of consistency, we better backport it there, or ensure we're running the tests with the correct branch (I'd do both, but mainly ensure the latter).

**Review by c3d — APPROVED** [review]
Thanks @snir911, lgtm.

**Comment by snir911** [comment]
/retest-fedora
@Jakob-Naucke any idea about the s390x/arm failure (http status failure on valid links)

**Comment by snir911** [comment]
added dependency on https://github.com/kata-containers/tests/pull/4310
/test

**Comment by snir911** [comment]
link checker gets **_"429 Too Many Requests"_** on the arm and s390x machines, I'll retry later (not sure how long i should wait though :P) 
@jodh-intel as git blame shows you authored this part :) any idea to workaround it?

**Review by bergwolf — APPROVED** [review]

**Comment by bergwolf** [comment]
ARM and s390x CI failed on network issues when checking valid URLs. I've retriggered them.

**Comment by bergwolf** [comment]
BTW, I don't think we should ever run URL checks in different Jenkins jobs. It is better to just run it **ONCE** in github workflow. I've created https://github.com/kata-containers/tests/issues/4311 to track it.

**Comment by snir911** [comment]
@Jakob-Naucke @stevenhorsman @davidhay1969 s390x job is failing (regardless to the changes it seems, hence, also blocks https://github.com/kata-containers/tests/pull/4310 and probably others) , should we fix/skip/disable job?

**Review by amshinde — APPROVED** [review]

**Pull request merged**
