### PR TITLE
[fwport-2.0] qemu: update build dependencies to support QEMU 5

### PR DESCRIPTION
**Pull request by devimc**

### CODE REVIEW

**Comment by devimc** [comment]
@lifupan @fidencio @bergwolf @amshinde  please take a look

**Review by fidencio — APPROVED** [review]
lgtm!

**Review by amshinde — APPROVED** [review]

**Comment by amshinde** [comment]
@likebreath @GabyCT Is the jenkins-ci-ubuntu-1804-cloud-hypervisor-k8s-containerd-2.0 CI still wip?

**Comment by likebreath** [comment]
> @likebreath @GabyCT Is the jenkins-ci-ubuntu-1804-cloud-hypervisor-k8s-containerd-2.0 CI still wip?

@amshinde No, it should be working fine. Let me see why it is broken. With a quick look, it looks like something wrong for the setup.

**Review by lifupan — APPROVED** [review]

**Comment by likebreath** [comment]
clh CI failing is a separate issue. Merging this PR now.

**Pull request merged**
