### PR TITLE
[backport] Fixup systemd cgroup handling

### PR DESCRIPTION
**Pull request by fgiudici**
Port to 2.0 stable branch https://github.com/kata-containers/kata-containers/pull/1514

### CODE REVIEW

**Review by cmaf — APPROVED** [review]
thanks @fgiudici

**Review by fidencio — APPROVED** [review]
lgtm, thanks @fgiudici!

**Comment by fidencio** [comment]
@fgiudici, could you rebase this one atop of current `stable-2.0` branch?

**Pull request merged**
