### PR TITLE
docs: fix typo in key filename in AWS installation guide

### PR DESCRIPTION
**Pull request by Sig00rd**

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks @Sig00rd!

**Review by c3d — APPROVED** [review]
/lgtm

**Comment by c3d** [comment]
Hi @Sig00rd, you need to add a short description to your commit message, and a line that looks like:

Fixes: #12345

Where the number is an issue describing the problem. I know this is annoying on such a small fix, but while we discussed having a short-circuit for trivial issues, we never actually implemented it, so our CI won't pass until you do that.

**Comment by Sig00rd** [comment]
sure thing @c3d, I've added it

**Comment by stevenhorsman** [comment]
Hey @Sig00rd - you also need to add the DCO sign-off to each commit e.g. a line that looks something like:
```
Signed-off-by: Joe Bloggs <joe@example.com>
```

I _think_ you can add the sign-off to the last commit with:
```
git commit --amend --signoff
```
but for future reference I normally use the `-s` flag when doing `git commit`. If you hit any problems, please let me know :)

**Comment by c3d** [comment]
@Sig00rd You will need to adhere to [the commit message guidelines](https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format). Summary here:

- A description of the commit (besides the on-liner)
- A "Fixes" lines that begins with "Fixes: " and not "fixes" or anything else. Computers are stupid that way.
- A signed-off-by

This is the price to pay to get consistent commits 😄

**Comment by Sig00rd** [comment]
@stevenhorsman @c3d thanks guys, I believe it should be all right now, let me know if that's not the case

**Comment by stevenhorsman** [comment]
All passed now, so can be merged. Thanks @Sig00rd!

**Pull request merged**
