### PR TITLE
runtime-rs: blanks filled & fixes made to virtiofsd launch

### LINKED ISSUE #5572: runtime-rs cannot start virtiofsd
This is a known problem, virtiofsd support in runtime-rs is not complete. A fix should at least make it possible for virtiofsd to launch in common scenarios.

### PR DESCRIPTION
**Pull request by pmores**
The 'config' argument to ShareVirtioFsStandalone::new() is now actually used, taking care of an explicit TODO.

If a shared path doesn't exist in ShareVirtioFsStandalone::virtiofsd_args() it is now created instead of returning an error, thus following ShareVirtioFsInline's suit.

The '-o vhost_user_socket=...' command line argument doesn't seem to be supported by newer versions of virtiofsd so we replace it with '--socket-path' which should be functionally equivalent according to docs.

Fixes #5572

Signed-off-by: Pavel Mores <pmores@redhat.com>

### CODE REVIEW

**Review by Tim-0731-Hzt — APPROVED** [review]
Thanks @pmores LGTM

**Review by Ji-Xinyou — APPROVED** [review]
Nice catch, Thanks @pmores , LGTM!

**Comment by pmores** [comment]
Thanks for your reviews @Tim-0731-Hzt @Ji-Xinyou !  I just pushed an update but that's just to placate `cargo fmt`, no substantive changes.

**Review by liubin — APPROVED** [review]

**Pull request merged**
