### PR TITLE
scripts: Use shebang /usr/bin/env bash

### PR DESCRIPTION
**Pull request by haslersn**
Not all distros have `/bin/bash`, e.g. NixOS.

### CODE REVIEW

**Comment by dgibson** [comment]
Chances are many of these scripts don't actually use bash specific extensions, they just have `#! /bin/bash` from habit.  So a more elegant approach would probably be to change that to `#! /bin/sh` for those scripts that don't specifically require bash.

**Comment by jcvenegas** [comment]
yay for NixOS, @haslersn  could you plase open an issue and add a 
```
Fixes: #<issue_number>
```
as part of the commit boddy.

I hope the next docs help you about the commit format:  https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#github-best-practices

**Comment by haslersn** [comment]
@jcvenegas Done.

**Review by jodh-intel — APPROVED** [review]
Thanks @haslersn.

lgtm, although if you want to fix this issue permanents, you should also consider adding a static check in the script below to avoid any new scripts being added that hard-code the shell path:

- https://github.com/kata-containers/tests/blob/main/.ci/static-checks.sh#L1055

**Review by jcvenegas — APPROVED** [review]

**Comment by jcvenegas** [comment]
@haslersn  It would be great,  if you are interesting on contribute with an static check for scripts.

**Pull request merged**
