### PR TITLE
CCv0: Update image-rs & AA

### PR DESCRIPTION
**Pull request by surajssd**
- image-rs & AA: 5df1101ba325993bb230981fe1efdf8570b84505

### CODE REVIEW

**Comment by stevenhorsman** [comment]
The tests don't make happy reading. It looks like anything related to signed, or encrypted images, or from and authenticated registry isn't working, so it feels likely that the offline_fs_kbc json files we create aren't been read by this version of the attestation-agent (maybe because it's in the transition to CDH already?). More specifically the error I see is `"agent pull image err. rpc error: code = Internal desc = No such file or directory (os error 2)"`. Unfortunately image-rs doesn't give us enough information to know what file is missing though.

**Comment by stevenhorsman** [comment]
Oh - it looks like the CCv0 daily baseline is completely broken: http://jenkins.katacontainers.io/view/Daily%20CCv0%20baseline/, so the problems I saw above could well be unrelated to this PR

**Comment by surajssd** [comment]
Also seeing this which is causing a lot of s390x jobs to fail.

**Comment by surajssd** [comment]
Closing in favour of #7797

**Pull request closed without merging**
