### PR TITLE
agent: fix pipestream fd cleanup

### PR DESCRIPTION
**Pull request by bergwolf**
pipestream takes ownership of the raw fd as it closes the fd when it is
dropped. We should dup a new fd for each pipestream. Otherwise the
process stream fd will be closed multiple times, creating random fd related
failures.

Fixes: #4598

### CODE REVIEW

**Review by liubin — APPROVED** [review]

**Review by teawater — APPROVED** [review]

**Comment by bergwolf** [comment]
Adding do-not-merge label. Let's wait a bit and let @Tim-Zhang confirm the change.

**Comment by Tim-Zhang** [comment]
Hi @bergwolf I have found the real problem and have created a new pull request: https://github.com/kata-containers/kata-containers/pull/4715

**Comment by bergwolf** [comment]
Closing in favor of https://github.com/kata-containers/kata-containers/pull/4715

**Pull request closed without merging**
