### PR TITLE
runtime: pass correct parameter format with macvtap for acrn

### PR DESCRIPTION
**Pull request by hongzhanchen**
According to https://projectacrn.github.io/3.0/developer-guides/hld/virtio-net.html, we need to pass tap=tap0_kata for macvtap to fix issue #9565

### CODE REVIEW

**Review by lifupan — APPROVED** [review]

**Review by Apokleos — APPROVED** [review]
Thx @hongzhanchen LGTM

**Comment by Apokleos** [comment]
Hi @hongzhanchen Could you please rebase this code ?

**Pull request closed without merging**
