### PR TITLE
docs: fix minikube installation guide runtimeclasses error

### PR DESCRIPTION
**Pull request by YchauWang**
the kata-deploy project scripts were changed, but minikube installation guide doc still use old yaml script. fix guide doc use the new yaml script of runtimeClasses.

Fixes: #2276

Signed-off-by: wangyongchao.bj <wangyongchao.bj@inspur.com>

### CODE REVIEW

**Comment by liubin** [comment]
Hi @YchauWang , it seems your commit message lines are too long:

```
ERROR: commit 02f9468206452ad387568e13e4a47b49acde1f8c: body line 1 too long (max 150, got 165): "the kata-deploy project scripts were changed, but minikube installation guide doc still use old yaml script. fix guide doc use the new yaml script of runtimeClasses."

```

**Comment by YchauWang** [comment]
Thanks @liubin , I fixed it now.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @YchauWang!

**Review by snir911 — APPROVED** [review]
LGTM!

**Pull request merged**
