### PR TITLE
memory_offset must be larger than 32 bit

### LINKED ISSUE #2006: io.katacontainers.config.hypervisor.memory_offset: must be larger than 32 bit
**Which feature do you think can be improved?**

Kata Containers and PMEM-CSI can be used together to make PMEM volumes available inside a container (https://intel.github.io/pmem-csi/0.9/docs/design.html#kata-containers-support). It's currently broken (https://github.com/intel/pmem-csi/issues/987) but that'll get addressed.

**How can it be improved?**

`io.katacontainers.config.hypervisor.memory_offset` (https://github.com/kata-containers/kata-containers/blob/main/docs/how-to/how-to-set-sandbox-config-kata.md) or the corresponding global config must be used to reserve enough of the address space for PMEM.

- Right now, that annotation is limited to uint32 values, i.e. 4GB maximum. This is not useful for real PMEM, which is considerably larger. This basically has to become a uint64.

- Specifying such large numbers as decimals is not useful. Consider accepting a short hand like "400Gi", for example by parsing with https://pkg.go.dev/k8s.io/apimachinery/pkg/api/resource#ParseQuantity

- Ideally, Kata Containers should figure out that a container uses PMEM and then adapt the offset automatically.

CC @devimc

### PR DESCRIPTION
**Pull request by devimc**
fixes #2006 

cc @pohly

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Comment by snir911** [comment]
@devimc just pointing your attention to the failing static checks :) LGTM overall

**Review by fidencio — APPROVED** [review]
@devimc, lgtm!

Please, let's also wait for @pohly's review.

On a side note, I must say last time I saw @pohly around both of us were doing some work on Evolution and that feels like a decade ago. :-) (I'm pretty sure Patrick doesn't even remember me!)

**Comment by pohly** [comment]
The change itself looks fine to me. I just want to point out that ideally, users shouldn't have to configure this at all when using PMEM volumes. We probably need a separate tracking issue for "determine memory offset dynamically for the configured PMEM volumes".

> On a side note, I must say last time I saw @pohly around both of us were doing some work on Evolution and that feels like a decade ago. :-) (I'm pretty sure Patrick doesn't even remember me!)

You missed the time then when @devimc and I were working on this PMEM support initially. Regarding Evolution, of course... I don't remember you. Sorry! It definitely must have been a decade ago. Now I feel old.

**Review by jodh-intel — APPROVED** [review]
Thanks @devimc.

lgtm

**Pull request merged**
