### PR TITLE
nydus: upgrad to v2.2.0

### PR DESCRIPTION
**Pull request by jongwu**
upgrad nydus version to v2.2.0 thus it can pass the test on arm64

### CODE REVIEW

**Review by liubin — APPROVED** [review]

**Review by GabyCT — APPROVED** [review]

**Comment by jongwu** [comment]
There is a bug in nydusd 2.2.0 on Arm but get  [fixed](https://github.com/dragonflyoss/image-service/pull/1149) now. We can merge this first and wait for the next release of nydus then upgrad again. Thus I can build latest nydus to test  kata + nydus on Arm.

WDYT? @liubin

**Comment by liubin** [comment]
> There is a bug in nydusd 2.2.0 on Arm but get [fixed](https://github.com/dragonflyoss/image-service/pull/1149) now. We can merge this first and wait for the next release of nydus then upgrad again. Thus I can build latest nydus to test kata + nydus on Arm.
> 
> WDYT? @liubin

Sounds good to me.

**Comment by jongwu** [comment]
Thanks! @liubin

**Pull request merged**
