### PR TITLE
stable-2.4: backport agent fixes

### PR DESCRIPTION
**Pull request by egernst**
Backport signal handling fix, as well as agent test improvements.

### CODE REVIEW

**Comment by fidencio** [comment]
I am not sure if I understand the errors I'm seeing here.  It seems to be using `main` tests branch against a `stable-2.4` kata-containers branch.

**Comment by fidencio** [comment]
I am not sure if I understand the errors I'm seeing here.  It seems to be using `main` tests branch against a `stable-2.4` kata-containers branch.

**Comment by fidencio** [comment]
> I am not sure if I understand the errors I'm seeing here. It seems to be using `main` tests branch against a `stable-2.4` kata-containers branch.

Okay, no, that's **not** the case.
What's actually happening is that the cached QEMU version used is the same, regardless to which branch is being used.  However, we stopped building virtiofsd as part of QEMU on `main`, so the cached version doesn't have it ... and here we are trying to install it.

@wainersm, any idea on how to easily solve this?

**Comment by wainersm** [comment]
> 

> > I am not sure if I understand the errors I'm seeing here. It seems to be using `main` tests branch against a `stable-2.4` kata-containers branch.
> 
> Okay, no, that's **not** the case. What's actually happening is that the cached QEMU version used is the same, regardless to which branch is being used. However, we stopped building virtiofsd as part of QEMU on `main`, so the cached version doesn't have it ... and here we are trying to install it.
> 
> @wainersm, any idea on how to easily solve this?

easily... hmm... maybe change the value of `qemu_latest_build_url` so use an invalid job, it will give "cache miss" and then try to build locally:

```
diff --git a/.ci/install_qemu.sh b/.ci/install_qemu.sh
index f20f6889..3137f23a 100755
--- a/.ci/install_qemu.sh
+++ b/.ci/install_qemu.sh
@@ -220,7 +220,7 @@ main() {
                vanilla)
                        CURRENT_QEMU_VERSION=$(get_version "assets.hypervisor.qemu.version")
                        QEMU_REPO_URL=$(get_version "assets.hypervisor.qemu.url")
-                       qemu_latest_build_url="${jenkins_url}/job/kata-containers-2.0-qemu-$(uname -m)/${cached_artifacts_path}"
+                       qemu_latest_build_url="${jenkins_url}/job/kata-containers-stable-2.4-qemu-$(uname -m)/${cached_artifacts_path}"
                        ;;
                *)
                        info "qemu type '${qemu_type}' not supported"

```
Ideally we should have cache jobs for the branches.

**Comment by egernst** [comment]
@wainersm -- can you clarify -- we should send a PR on the stable branches to update QEMU caching, then all should be good -- is that right?

**Comment by egernst** [comment]
(rebased)

**Review by snir911 — APPROVED** [review]
Thanks! would be nice also to refer to the original PRs/commit in each of the commits but LGTM anyhow

**Review by fidencio — APPROVED** [review]
lgtm, thanks @egernst!

**Review by jodh-intel — APPROVED** [review]

**Pull request merged**
