### PR TITLE
A couple of kata-deploy fixes

### PR DESCRIPTION
**Pull request by wainersm**
While trying to use kata-deploy on openshift-ci (#6492) I noticed some problems that I hope are fixed by the commits on this PR.

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @wainersm!

My bad on those! /o\

**Comment by wainersm** [comment]
> lgtm, thanks @wainersm!
> 
> My bad on those! /o\

Don't worry! ;)

**Review by Tim-0731-Hzt — APPROVED** [review]
Thanks @wainersm LGTM

**Pull request merged**
