### PR TITLE
CC | cherry-pick #7819 and #7821 from main branch

### PR DESCRIPTION
**Pull request by jiangliu**
cherry-pick #7819 and #7821 from main branch.

### CODE REVIEW

**Comment by fidencio** [comment]
@jiangliu, this one looks good to me, but I'd like to get the TDX CI running before merging this one.

**Comment by jiangliu** [comment]
> @jiangliu, this one looks good to me, but I'd like to get the TDX CI running before merging this one.

Sure, then I will move on to review PRs from Chengyu.

**Comment by fidencio** [comment]
> Sure, then I will move on to review PRs from Chengyu.

I've synced with Chengyu on the operator front Yesterday.

There are other PRs from him here, but I think we need to get the nydus part done first.
Once that's done, we can then better understand what has to be tested, which are the depenencies for each case, how the config files will look, etc.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jiangliu!

**Pull request merged**
