### PR TITLE
CC | Merge from main to CCv0 -- Aug 7th, 2023

### PR DESCRIPTION
**Pull request by fidencio**
Weekly merge.

Fixes: #7563

### CODE REVIEW

**Comment by fidencio** [comment]
Fedora:
```
13:02:37 not ok 1 Replication controller
13:02:37 # (from function `waitForProcess' in file /tmp/jenkins/workspace/kata-containers-CCv0-tests-fedora-PR/go/src/github.com/kata-containers/tests/lib/common.bash, line 107,
13:02:37 #  in test file k8s-replication.bats, line 40)
13:02:37 #   `waitForProcess "$wait_time" "$sleep_time" "$cmd"' failed
13:02:37 # INFO: k8s configured to use runtimeclass
13:02:37 # replicationcontroller/replicationtest created
13:02:37 #   Normal  SuccessfulCreate  0s    replication-controller  Created pod: replicationtest-lg4q5
13:02:37 # Name:         replicationtest
13:02:37 # Namespace:    default
13:02:37 # Selector:     app=nginx-rc-test
13:02:37 # Labels:       app=nginx-rc-test
13:02:37 # Annotations:  <none>
13:02:37 # Replicas:     1 current / 1 desired
13:02:37 # Pods Status:  0 Running / 1 Waiting / 0 Succeeded / 0 Failed
13:02:37 # Pod Template:
13:02:37 #   Labels:  app=nginx-rc-test
13:02:37 #   Containers:
13:02:37 #    nginxtest:
13:02:37 #     Image:        quay.io/sjenning/nginx:1.15-alpine
13:02:37 #     Port:         80/TCP
13:02:37 #     Host Port:    0/TCP
13:02:37 #     Environment:  <none>
13:02:37 #     Mounts:       <none>
13:02:37 #   Volumes:        <none>
13:02:37 # Events:
13:02:37 #   Type    Reason            Age   From                    Message
13:02:37 #   ----    ------            ----  ----                    -------
13:02:37 #   Normal  SuccessfulCreate  92s   replication-controller  Created pod: replicationtest-lg4q5
13:02:37 # replicationcontroller "replicationtest" deleted
```

This is not related to this PR.

**Review by stevenhorsman — APPROVED** [review]
I had a non-thorough review, but focussed on the bits that I know have most of the frequently touched differences between main and CCv0 and it looks okay. The tests are the real arbiter of whether it's okay though!

**Pull request merged**
