### PR TITLE
stable-2.0 | agent: vendor all the used crates

### PR DESCRIPTION
**Pull request by fidencio**
This it not different than what we've been doing for the go code, and it
does help a lot distro maintainers, as usually the build machines don't
provide access to the internet during the build time, forcing the
package maintainers to manually vendor the code themselves.

Knowing about this, let's make their life simpler by vendoring the code
ourselves, which will lead to us releasing the vendored code together
with our released tarballs.

Fixes: #1203

Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>

This is a backport of https://github.com/kata-containers/kata-containers/pull/1380

### CODE REVIEW

**Comment by dgibson** [comment]
@fidencio , is there a procedure documented somewhere for updating the vendored packages to a new version?

**Comment by bergwolf** [comment]
The original PR #1380 is still under discussion. Mark this as `wip`.

**Comment by fidencio** [comment]
Oh, I forgot about this one.

For this one we'll have to hack the scripts used as part of the release, by actually adding a `make dist` target and probably pushing our own tarballs together with the tags, as the current tarballs seem to be autogenerated by GitHub itself. :-/

For now, I'm closing this one.

**Pull request closed without merging**
