### PR TITLE
ci: fix virtiofs-experimental build

### LINKED ISSUE #1421: Enable virtiofs experimental build
- Add new CI job to keep testing new features in virtiofs

Latest patches for qemu virtiofs  https://gitlab.com/virtio-fs/qemu/-/tree/virtio-fs-dev are based in qemu 6.0 (in development), instead of pull patches from that branch just follow it , but not provide by default to avoid stability issues.

### PR DESCRIPTION
**Pull request by jcvenegas**
qemu: Build experimental qemu.
qemu: Improve cache build
qemu: Add suffix for qemu binaries.
qemu: add CACHE_TIMEOUT
qemu: Apply patches for specific versions.
packaging: Use local file for assets.
qemu: patches: Fail if not patches directory
versions: Update qemu database
qemu: move 5.0.0 patches to its own dir.

Depends-on: https://github.com/kata-containers/tests/pull/3255

Fixes #1421

Signed-off-by: Carlos Venegas <jos.c.venegas.munoz@intel.com>

### CODE REVIEW

**Review by devimc — APPROVED** [review]
snap CI looks happy, lgtm

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
