### PR TITLE
osbuilder: Bump fedora image version

### PR DESCRIPTION
**Pull request by stevenhorsman**
- Swap out an EoL fedora image for the latest

Fixes: #6923

### CODE REVIEW

**Review by studychao — APPROVED** [review]
LGTM, thanks

**Review by Amulyam24 — COMMENTED** [review]
Thanks @stevenhorsman !

**Review by GabyCT — APPROVED** [review]

**Comment by fidencio** [comment]
All the k8s CIs on GHA failed because https://github.com/kata-containers/kata-containers/pull/6913 was not merged.
I don't think it's worth re-triggering them at this point, and I'd be happy to have this one merged as it's.

**Pull request merged**
