### PR TITLE
clh: Add hugepages support

### LINKED ISSUE #455: The cloud hypervisor cannot be configured to use hugepages
The cloud hypervisor supports hugepages, but there is no related configuration options in the configuration file.

### PR DESCRIPTION
**Pull request by BetaXOi**
This commit adds cloud hypervisor hugepages support.

Fixes #455

Signed-off-by: NingBo <ning.bo9@zte.com.cn>

### CODE REVIEW

**Comment by devimc** [comment]
@likebreath @sboeuf please take a look

**Comment by likebreath** [comment]
@BetaXOi Thanks for the PR. As mentioned in another PR from you, we are missing CI jobs on CLH in Kata 2.0, so we may need to hold on merging the PR until we have that. We are in the process of consolidating development efforts of clh support in Kata 1.x and Kata 2.0 (https://github.com/kata-containers/kata-containers/issues/461). 

Please bear with us during this transition time. I see you submitted the original PR to kata 1.x (kata-runtime). Sorry for the confusions.

On the other hand, a quick question about the PR: do we have code path in Kata that checks whether there is (enough) available huge pages on host to start the hypervisor w/ `enable_hugepages=true`?

**Comment by likebreath** [comment]
@BetaXOi As mentioned in another PR from you,I now removed the `dnm` label from this PR. Please rebase the PR and we will be able to merge it as long as related CI jobs are passing. Thanks again for patience and contributions.

**Comment by likebreath** [comment]
The CI is now happy, including CLH CI jobs. But I am wondering how does it make differences on the memory foot-print when using huge-pages as default. As we are missing metrics CI for kata 2.0, @BetaXOi do you mind back-porting this PR to kata 1.x first and check how the metrics works there?

I am making this PR `do-not-merge` before we have a better idea of its implications of using huge-page as default. Any questions or advises, please don't hesitate to share. Thanks.

**Pull request closed without merging**
