### PR TITLE
workflow: trigger release for 3.x releases

### PR DESCRIPTION
**Pull request by bergwolf**
So that we can push 3.x artifacts to the release page.

Fixes: #4919

### CODE REVIEW

**Review by liubin — APPROVED** [review]

**Review by fidencio — COMMENTED** [review]
@bergwolf, https://github.com/kata-containers/kata-containers/blob/828574d27c18c6f2806eb314503bbf59e370cd94/.github/workflows/snap-release.yaml#L5 should also be updated.

I wonder if jenkins / actions in general should also be updated, but that's out of the scope of this PR.

**Comment by bergwolf** [comment]
Thanks @fidencio ! Updated.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @bergwolf!

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
