### PR TITLE
# Kata Containers 2.2.3

### PR DESCRIPTION
**Pull request by bergwolf**
4f73e58d7 packaging/static-build: s390x fixes
45f65a73c agent: Handle uevent remove actions
06d304934 agent: fix race condition when test watcher
0366f6e81 template: disable template unit test on arm
7cb650abc runtime: DefaultMaxVCPUs should not greater than defaultMaxQemuVCPUs
e97cd23bd runtime: current vcpu number should be limited
6b6d81cce runtime: kernel version with '+' as suffix panic in parse
a479eca7d docs: Fix outdated links
b794a3940 virtcontainers: clh: Re-generate the client code
39d95f486 versions: Upgrade to Cloud Hypervisor v19.0

### CODE REVIEW

**Comment by fidencio** [comment]
@bergwolf, the bump doesn't look correct, as it's bringing in a bunch of non-related-to-the-bump commits.

**Comment by bergwolf** [comment]
@fidencio I looked through the `main` history and cherry-picked the obvious stable commits whose author didn't submit them to stable. Should I just drop them as they missed the backport window?

**Comment by fidencio** [comment]
> @fidencio I looked through the `main` history and cherry-picked the obvious stable commits whose author didn't submit them to stable. Should I just drop them as they missed the backport window?

No, no. let's keep them. :-)
I thought it was some mistake happening with the script, as it's not the case, I'm totally fine on having those in.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @bergwolf!
And thanks for the missing backports you're bringing in!

**Comment by fidencio** [comment]
I'd like to ask to only have this one merged after we have the results of the test-kata-deploy (it'll save us some time in case something goes wrong).

**Comment by bergwolf** [comment]
kata-deploy passed https://github.com/kata-containers/kata-containers/actions/runs/1425258811

**Review by jodh-intel — APPROVED** [review]
Thanks @bergwolf.

lgtm

**Pull request merged**
