### PR TITLE
CCv0: Update image-rs, AA and td-shim

### PR DESCRIPTION
**Pull request by surajssd**
- image-rs & AA: e5e6e69ae0ea01393a125cde8e2772ad98aba39c
- td-shim: 3f18d9f3f51c9428c034cf01b45ab94bcd0d1622

### CODE REVIEW

**Comment by fidencio** [comment]
@surajssd, can you hold this one, just to make sure some other PRs get in first?  Mainly thinking about CDH, which is also bumping the guest components.

**Comment by surajssd** [comment]
Oh yes, we don't need to merge this right away. I am here to see the pipelines and where they fail.

**Comment by fidencio** [comment]
> I am here to see the pipelines and where they fail.

/cc @arronwy, do you know if the TD-Shim issue got fixed and we can re-enable the TDX Cloud Hypervisor CI?

**Comment by surajssd** [comment]
It seems that the problem with setting up cc containerd is coming from iptables code here: https://github.com/kata-containers/tests/blob/CCv0/integration/confidential/lib.sh#L230

```bash
        sudo iptables -P FORWARD ACCEPT
```

Right now the error I see is: 

```bash
09:25:14 # Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
```

So I will try adding `-w` flag.

**Comment by surajssd** [comment]
Created PR for the iptables issue: https://github.com/kata-containers/tests/pull/5766

**Comment by fidencio** [comment]
> Created PR for the iptables issue: [kata-containers/tests#5766](https://github.com/kata-containers/tests/pull/5766)

Merged, thanks!

**Comment by arronwy** [comment]
> > I am here to see the pipelines and where they fail.
> 
> /cc @arronwy, do you know if the TD-Shim issue got fixed and we can re-enable the TDX Cloud Hypervisor CI?

The issue seems due to the Host OS environment, we use the same cloud hypervisor/td-shim/kernel/rootfs on different server, one is ok, but on current CI servre, it will hangs during boot

**Comment by surajssd** [comment]
Currently facing: https://github.com/confidential-containers/guest-components/issues/354

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks!

**Comment by stevenhorsman** [comment]
FYI Suraj - as part of https://github.com/kata-containers/kata-containers/pull/7948 I had to bump the guest-components to the as-was latest commit, so that's why we have conflicts now

**Comment by fitzthum** [comment]
Now that we've hit the freeze, it's time to get this PR in.

@surajssd can I trouble you for a rebase before you take off for Kubecon? (if not I can make a new PR)

I think we probably want to bump image-rs and the AA to `e5e6e69ae0ea01393a125cde8e2772ad98aba39c` so that we can pickup a few fixes that have gone in recently.

Maye we should also update td-shim to `3f18d9f3f51c9428c034cf01b45ab94bcd0d1622`

**Comment by surajssd** [comment]
@fitzthum done.

**Comment by fitzthum** [comment]
@BbolroC @stevenhorsman We have an s390x failure. Seems like it's some issue with the ring crate which gets pulled in somewhere. Is this expected?

**Comment by stevenhorsman** [comment]
> @BbolroC @stevenhorsman We have an s390x failure. Seems like it's some issue with the ring crate which gets pulled in somewhere. Is this expected?

No it's not expected - IIRC we shouldn't be defaulting to use the feature that picks up ring, but maybe that's changed recently?

**Comment by Xynnn007** [comment]
> > @BbolroC @stevenhorsman We have an s390x failure. Seems like it's some issue with the ring crate which gets pulled in somewhere. Is this expected?
> 
> No it's not expected - IIRC we shouldn't be defaulting to use the feature that picks up ring, but maybe that's changed recently?
> 
> @Xynnn007 - Ding it looks like you've made the recent updates around rust-tls and I think you understand the ring dependencies better than I do, so you might be able to help? It is worth noting that the s390x support was added to ring recently ([briansmith/ring#1297](https://github.com/briansmith/ring/pull/1297)), but I guess it might take a while to bubble up through the dependencies' releases

Oh right. `aliyun` kms plugin involves `ring` which will be used to parse TLS cert. I disabled `aliyun` kms plugin for `s390x` in https://github.com/confidential-containers/guest-components/pull/381/commits/404bba7bc59af8831be1bb1578e7f802a9e839c3

This commit is together with some bug fixes for v0.8.0 https://github.com/confidential-containers/guest-components/pull/381 that we met when making a demo.

PTAL if it could be merged and then change the rev to that.

**Comment by fitzthum** [comment]
I have merged the fixes PR @Xynnn007 mentioned above. Guest components are at `615a46ff16ee8670014946d14e44e85cede82f01`. I'm not sure if @surajssd will be able to update this PR. Maybe an admin can do it (@stevenhorsman?). If not I will just make a new one.

**Comment by portersrc** [comment]
@stevenhorsman , do you have a sense for why the latest s390x build failure could happen?
Link to jenkins console output is [here](http://jenkins.katacontainers.io/job/kata-containers-CCv0-ubuntu-20.04-s390x-PR/942/consoleFull).
It has this:
```15:49:09 thread 'watcher::tests::create_tmpfs' panicked at 'assertion failed: is_mounted(mount_point).unwrap()', src/watcher.rs:1307:test watcher::tests::make_target_path ... ok
15:49:09 13
15:49:09 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
15:49:09 test watcher::tests::create_tmpfs ... FAILED```
There are some INFO messages prior to the failure that look related, e.g.
```15:49:09 INFO: skipping loop test[0]: TestData { test_user: NonRootOnly, storage: Storage { driver: "", driver_options: [], source: "src", fstype: "tmpfs", options: [], mount_point: "mnt", fs_group: MessageField(None), special_fields: SpecialFields { unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } } }, error_contains: "EPERM: Operation not permitted", make_source_dir: true, make_mount_dir: false, deny_mount_permission: false } in kata_agent::storage::tests which needs non-root```
The code for the assertion seems to be [here](https://github.com/kata-containers/kata-containers/blob/d93275224b3b6605089874393adb133a8c85d438/src/agent/src/watcher.rs#L1307).

**Comment by fitzthum** [comment]
Thanks to @ryansavino for triggering the tests a few times. Looks like things are passing now. Can we dig up another reviewer for this?

**Review by Xynnn007 — APPROVED** [review]

**Comment by stevenhorsman** [comment]
> @stevenhorsman , do you have a sense for why the latest s390x build failure could happen?
> Link to jenkins console output is [here](http://jenkins.katacontainers.io/job/kata-containers-CCv0-ubuntu-20.04-s390x-PR/942/consoleFull).

Hi Chris,

yes this test has been flakey for a while, so it's been disabled on `main`: https://github.com/kata-containers/kata-containers/pull/8289

**Pull request merged**
