### PR TITLE
clh: Use vanilla kernel.

### PR DESCRIPTION
**Pull request by jcvenegas**
Qemu config alredy use vanilla kernel build for virtiofs.

Lets make cosisntent the usage of kernel.

Depends-on: github.com/kata-containers/tests#3172

Fixes: github.com/kata-containers/tests#3171

Signed-off-by: Carlos Venegas <jos.c.venegas.munoz@intel.com>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]

**Review by egernst — APPROVED** [review]
Yes, please, thank-you.

**Comment by fidencio** [comment]
I'm really sorry for the disruption but in order to do the branch name changes announced [here](http://lists.katacontainers.io/pipermail/kata-dev/2021-January/001695.html) I'm adding the "do-not-merge" and the "needs-branch-adjustment" labels to the PR.

I'll add a new comment once the branch changes are done and once it happens I'd like to ask you to resubmit the PR against the new `main` branch, possibly linking to this PR in case you find the conversations / reviews already made important to proceed.

**Comment by fidencio** [comment]
Kata Containers repos are back to business.  Thanks a lot for your patience and I'm very happy to announce that there's no changes needed from your side as renaming the branches automagically reflected here.

If you notice something weird, some missing CI, please, do not hesitate on contacting us here or on #kata-dev on bit.ly/katacontainersslack.

Also, this is a good opportunity to have your PR rebased atop of `main`, to ensure your PR follow all the guidelines (https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format) enforced by this community, or even to re-evaluate whether the PR is currently needed.

Last but not least,  as the default branch has been renamed to `main`, if you have a local clone you'd need to update it and you do so by running:
```
git branch -m 2.0-dev main
git fetch origin
git branch -u origin/main main
```

Happy hacking!

**Review by likebreath — APPROVED** [review]
This is great. Thanks @jcvenegas

**Comment by likebreath** [comment]
I guess you will need to fight with the `static check` GH action, and please don't forget to restart the CI after the updates. 

```
ERROR: No "Fixes" found
ERROR: checkcommits failed. See the document below for help on formatting
commits for the project.
```

**Comment by jcvenegas** [comment]
This PR seems to be not taking latest changes on https://github.com/kata-containers/tests/pull/3172 ,

I think that is because it modifies the Jenkins CI job, so new variables will not be exported.

https://github.com/kata-containers/tests/blob/main/.ci/jenkins_job_build.sh

Seems that to handle that will need to modify
https://github.com/kata-containers/tests/blob/master/.ci/ci_entry_point.sh 
and make it resolve dependencies before  execute that script or merge tests repo and this repo :) .

**Pull request merged**
