### PR TITLE
vendor: update OpenTelemetry

### LINKED ISSUE #2591: Upgrade OpenTelemetry version in runtime
Runtime tracing uses v0.15.0, upgrade to latest 1.0.0-RC3.

### PR DESCRIPTION
**Pull request by cmaf**
Upgrade OpenTelemetry from v0.15.0 to 1.0.0-RC3.

Fixes #2591

### CODE REVIEW

**Comment by cmaf** [comment]
It looks like I'll need to finish https://github.com/kata-containers/kata-containers/issues/2547 to get this merged, adding WIP until then

**Comment by cmaf** [comment]
To do: update commits - the issue numbers in the git log refer to opentelemetry issues, not kata containers issues.

**Comment by cmaf** [comment]
@liubin @jodh-intel this is ready for review. There were a significant number of changes between versions so I broke it into 2 patches. If you are able, please look carefully at the changes to `tracing.go`. 

The upgrade resulted in a few changes to output, mainly to a few internal span attributes that we didn't explicitly configure in Kata.

v0.15.0:
otel-v0-15-0

v1.0.0:
otel-v1-0-0

**Review by liubin — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Thanks @cmaf.

lgtm

**Pull request merged**
