### PR TITLE
runtime: fix creation of SEV confidential container on SNP enabled host.

### PR DESCRIPTION
**Pull request by niteeshkd**
Fixes the issue #9036 .

### CODE REVIEW

**Comment by niteeshkd** [comment]
@ryansavino @fitzthum @zvonkok @jpecholt

**Review by ryansavino — APPROVED** [review]
Ah, thanks Niteesh for fixing this.

**Review by fitzthum — APPROVED** [review]
Great catch. We're changing a lot of stuff to `ConfidentialGuest`, but the `snpGuest` flag should be `SevSnpGuest`, because `ConfidentialGuest` is true for both SEV and SNP.

**Review by fidencio — CHANGES_REQUESTED** [review]
@niteeshkd, would you mind to add a commiit message explaining why this is needed?
If this is a regression, mind to mention when we regressed?

This kind of information is crucial for maintainers to navigate through the history of the projects (and bugs, and fixes).

**Comment by fidencio** [comment]
Answering some of my own questions here, it seems that the regression was introduced by de39fb7d3897bbb318c98ddd97805e54fa2b2625.  Let's also loop in @zvonkok to the loop to make sure it doesn't break his GPU related work, and if it does break, figure out the best way to solve.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @niteeshkd!

**Comment by niteeshkd** [comment]
Created #9040 to add a test in future.

**Comment by ryansavino** [comment]
All required checks are passing on this one. @stevenhorsman @danmihai1 @fidencio We good to merge this?

**Review by danmihai1 — APPROVED** [review]

**Review by stevenhorsman — APPROVED** [review]
LGTM

**Pull request merged**
