### PR TITLE
docs: fix brackets usage error for developer guide

### PR DESCRIPTION
**Pull request by focus-zhaos**
Fixed 3 errors which misused the bracket to substitute parameter for initrd-img creation at the developer guide.

Fixes: #2079

Signed-off-by: Sheng Zhao <zhaosheng.ste@bytedance.com>

### CODE REVIEW

**Review by devimc — APPROVED** [review]
thanks @focus-zhaos

**Review by fidencio — APPROVED** [review]
lgtm, thanks @focus-zhaos!

@Jakob-Naucke, mind to also take a look?

**Comment by fidencio** [comment]
@focus-zhaos, you need the `Fixes: #` and the `Signed-off-by: ` tag as part of the commit message of your commit.

**Review by jcvenegas — APPROVED** [review]

**Review by Jakob-Naucke — APPROVED** [review]
yes, we/I should make this

```diff
diff --git a/docs/Developer-Guide.md b/docs/Developer-Guide.md
index 7f9c9e70..089f1ae2 100644
--- a/docs/Developer-Guide.md
+++ b/docs/Developer-Guide.md
@@ -360 +360 @@ $ export ARCH=$(uname -m)
-$ [ ${ARCH} == "ppc64le" ] && export LIBC=gnu || export LIBC=musl
+$ [ ${ARCH} == "ppc64le" ] || [ ${ARCH} == "s390x" ] && export LIBC=gnu || export LIBC=musl
```

but this doesn't make the PR less valid. LGTM!

**Pull request merged**
