### PR TITLE
stable-2.3 | kata-deploy: fix tar command in dockerfile

### PR DESCRIPTION
**Pull request by snir911**
backports https://github.com/kata-containers/kata-containers/pull/3395

### CODE REVIEW

**Review by wainersm — APPROVED** [review]
As I approved the PR for the main branch... LGTM

**Review by bergwolf — APPROVED** [review]
thanks!

**Review by fidencio — APPROVED** [review]
lgtm, thanks @snir911!

**Review by jodh-intel — APPROVED** [review]

**Comment by snir911** [comment]
/retest-arm
(trying to get different arm machine)

**Comment by wainersm** [comment]
@snir911 what did you do to make the arm job pass?
I noticed it was failing the static-checks in http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-ARM-PR/3039/consoleFull . It is weird because it was checking a documentation file which you are not touching on this PR...

**Comment by snir911** [comment]
@wainersm it was failing because of `429 Too Many Requests response status`, see https://github.com/kata-containers/tests/issues/4311
I noticed that we 3 arm nodes, i just ran it when the first 2 nodes were in use by others so that it will be running on the least used machine (and ip)

**Comment by wainersm** [comment]
> @wainersm it was failing because of `429 Too Many Requests response status`, see [kata-containers/tests#4311](https://github.com/kata-containers/tests/issues/4311) I noticed that we 3 arm nodes, i just ran it when the first 2 nodes were in use by others so that it will be running on the least used machine (and ip)

ah, ok. thanks!

**Pull request merged**
