### PR TITLE
agent: Correct rustjail device filemode permission typo

### PR DESCRIPTION
**Pull request by skaegi**
Corrects device filemode permissions typo/regression in rustjail containers to `666` instead of `066`. `666` is the standard and expected value for these devices in containers -- and the value set [previously](https://github.com/kata-containers/kata-containers/blob/6f6a164451905219e402b328ef16f51f8c818deb/src/agent/rustjail/src/container.rs#L160).

Fixes: #10454

Signed-off-by: Simon Kaegi <simon.kaegi@gmail.com>

### CODE REVIEW

**Review by Apokleos — APPROVED** [review]
Thx @skaegi Yes, first of all, sorry for this mistake.
LGTM.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @skaegi!

**Comment by stevenhorsman** [comment]
@skaegi - thanks you spotting and fixing this. A quick question to you, or anyone else - would it be helpful to have a new Kata release with fix in sooner than the 3 weeks time our next one is due?

@kata-containers/architecture-committee - at the moment it doesn't look like any code features have merged since 3.10, so 3,10.1 could be on the cards, but I'm not sure if it's even worth worrying about and we just push out a 3.11 if needed? I'm happy to run this release process btw if it happens.

**Comment by skaegi** [comment]
Thanks @stevenhorsman @Apokleos @fidencio, 3.10.1 would be helpful. We build the agent for the local micro-VM for use with clh but not the remote-vm we use for cloud-api-adaptor, which grabs the release agent currently so it's more difficult for us. If it's easy ... yes please.

**Review by stevenhorsman — APPROVED** [review]

**Comment by stevenhorsman** [comment]
The required tests pass here, so time to merge this I think.

**Pull request merged**
