### PR TITLE
ci: Run some of the GARM tests in smaller instances

### PR DESCRIPTION
**Pull request by fidencio**
With the idea of reducing the costs, let's make sure we run the following jobs in smaller instances:
* docker
* nerdctl
* cri-containerd
* nydus
* k8s - devmapper

### CODE REVIEW

**Comment by mkbhanda** [comment]
Impressed by this series of economizing on instance size PRs!

**Review by jodh-intel — APPROVED** [review]
Thanks @fidencio.

lgtm

**Review by jepio — APPROVED** [review]

**Pull request merged**
