### PR TITLE
Remove additional links to tests directory

### PR DESCRIPTION
**Pull request by cmaf**
Remove links and references to files/scripts in tests repo when they can be replaced by ones from the kata containers repo.

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Review by dborquez — APPROVED** [review]
lgtm, thank you @cmaf

**Comment by cmaf** [comment]
@dborquez @GabyCT thanks, I am testing one additional thing and may request another review

**Comment by cmaf** [comment]
@GabyCT @dborquez disregard the earlier message, I'm going to get this one merged quickly

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks @cmaf

**Pull request merged**
