### PR TITLE
ci: cache: Allow pushing our artefacts to an OCI registry

### PR DESCRIPTION
**Pull request by fidencio**
This will help us to replace the Jenkins jobs currently used for our cached artefacts, which are used as part of our CI.

### CODE REVIEW

**Comment by fidencio** [comment]
After running the first round of builds using https://github.com/kata-containers/kata-containers/pull/7957/commits/2e1fbda1f06d583e4e8c8863258f4bf24ead50e5, which was forcing the PUSH_TO_REGISTRY, we can see that the following packages have been created:
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Fcloud-hypervisor
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Fkernel-dragonball-experimental
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Fkernel
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Ffirecracker
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Fkernel-nvidia-gpu
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Fovmf
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Fkernel-nvidia-gpu-snp
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Fovmf-sev
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Fqemu-snp-experimental
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Fnydus
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Frootfs-initrd
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Fqemu-tdx-experimental
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Frootfs-image
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Fkernel-tdx-experimental
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Fshim-v2
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Frootfs-initrd-mariner
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Fkernel-sev
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Ftdvf
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Frootfs-image-tdx
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Fvirtiofsd
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Fkernel-nvidia-gpu-tdx-experimental
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Frootfs-initrd-sev
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Fqemu
* https://github.com/kata-containers/kata-containers/pkgs/container/cached-artefacts%2Fcloud-hypervisor-glibc

Now I'm going to drop the commit that forces the artefacts to be pushed, and re-run the CI.

Part 2 will come after this one is merged, and will actually take advantage of the stored artefacts.

**Review by chavafg — APPROVED** [review]

**Review by GabyCT — APPROVED** [review]

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
