### PR TITLE
fix(fmt): fix cargo fmt

### PR DESCRIPTION
**Pull request by Ji-Xinyou**
Fix cargo fmt to pass static check.

Fixes: #5639
Signed-off-by: Ji-Xinyou <jerryji0414@outlook.com>

### CODE REVIEW

**Review by Tim-0731-Hzt — APPROVED** [review]

**Comment by studychao** [comment]
Could you rebase your PR to the latest main of Kata so that we could restart the CI to solve `vmm-sys-util` problem

**Comment by Ji-Xinyou** [comment]
> Could you rebase your PR to the latest main of Kata so that we could restart the CI to solve `vmm-sys-util` problem

I have squashed the fixfmt commit to the latest commit of main branch.

**Comment by Ji-Xinyou** [comment]
> Could you rebase your PR to the latest main of Kata so that we could restart the CI to solve `vmm-sys-util` problem

I have rebased to the latest commit in main branch.

**Review by GabyCT — APPROVED** [review]

**Review by amshinde — APPROVED** [review]

**Comment by amshinde** [comment]
@Ji-Xinyou This needs a rebase

**Comment by liubin** [comment]
@Ji-Xinyou there is a git issue, the pr only have a merge commit

**Review by studychao — APPROVED** [review]

**Comment by fidencio** [comment]
@Ji-Xinyou, I'm closing this one as it'll be merged as part of https://github.com/kata-containers/kata-containers/pull/5669

**Pull request closed without merging**
