### PR TITLE
rootfs: Stop building and shipping OPA

### PR DESCRIPTION
**Pull request by fidencio**
Since OPA binary was replaced by the regorus crate, we can finally stop building and shipping the binary.

### CODE REVIEW

**Comment by zvonkok** [comment]
I think you missed versions.yaml
```
  open-policy-agent:
    description: "Open Policy Agent"
    url: "https://github.com/open-policy-agent/opa"
    version: "v0.55.0"
```

**Review by zvonkok — APPROVED** [review]
LGTM,  A mim parece-me bem

**Comment by BbolroC** [comment]
Hi, Fabi. Could you revert what https://github.com/kata-containers/kata-containers/pull/9489 introduced?

**Comment by fidencio** [comment]
> Hi, Fabi. Could you revert what #9489 introduced?

Done! :-)

**Comment by BbolroC** [comment]
It looks the PR got mixed up with the previous 3 commits.

**Comment by BbolroC** [comment]
I have noticed the following error for `run-cri-containerd`:

```
go build  -gcflags=-trimpath=/home/runner/actions-runner/_work/kata-containers/kata-containers/src -buildmode=pie  -o bin/containerd -ldflags '-X github.com/containerd/containerd/version.Version=v1.7.16 -X github.com/containerd/containerd/version.Revision=83031836b2cf55637d7abf847b17134c51b38e53 -X github.com/containerd/containerd/version.Package=github.com/containerd/containerd -s -w ' -tags "no_btrfs"  ./cmd/containerd
# tags.cncf.io/container-device-interface/internal/validation/k8s
vendor/tags.cncf.io/container-device-interface/internal/validation/k8s/objectmeta.go:43:16: undefined: errors.Join
note: module requires Go 1.20
```

Example: https://github.com/kata-containers/kata-containers/actions/runs/8844120756/job/24285892891

Do you think it should be handled in this PR or in a separate PR.

**Review by BbolroC — APPROVED** [review]
LGTM, thanks @fidencio !

**Review by danmihai1 — APPROVED** [review]
Thanks @fidencio !

**Pull request merged**
