### PR TITLE
bump sirupsen/logrus to 1.9.0

### PR DESCRIPTION
**Pull request by yanggangtony**
As src/runtime/go.mod update the sirupsen/logrus  to 1.9.0.
Also current latest version is  [1.9.0](https://github.com/sirupsen/logrus/releases/tag/v1.9.0).

So update tools/log-parser/go.mod to match that.

### CODE REVIEW

**Comment by yanggangtony** [comment]
Hello , can anybody review these pr? 
Its have been a long time.

**Comment by c3d** [comment]
Hi @yanggangtony, please follow the guidelines outlined here: https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format

Notably, you need to have an associated issue, and your patch needs to mention it in a `Fixes: #<issue number>` line.

**Comment by yanggangtony** [comment]
> Hi @yanggangtony, please follow the guidelines outlined here: https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format
> 
> Notably, you need to have an associated issue, and your patch needs to mention it in a `Fixes: #<issue number>` line.

Ah, thanks for reminder.
Rebased it.

**Pull request closed without merging**
