### PR TITLE
agent: "Revert agent: Disable seccomp feature on aarch64 temporarily"

### PR DESCRIPTION
**Pull request by ManaSugi**
Re-enable seccomp feature on aarch64 because CI is ready
by https://github.com/kata-containers/tests/pull/4124.

This reverts commit 42add7f201cf082d0d06d676c5cf20e6088ac2fb.

Fixes: #2939

Signed-off-by: Manabu Sugimoto <Manabu.Sugimoto@sony.com>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
\o/ - thanks @ManaSugi.

lgtm

**Comment by ManaSugi** [comment]
Building the kata-agent on aarch64 was successfull but the `syscall_assert!(unsafe { dup2(0, 1) }, -EPERM)` in `test_init_seccomp` failed with the following message.

```
thread 'seccomp::tests::test_init_seccomp' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `-1`', rustjail/src/seccomp.rs:215:9
```

I think the reason is that `dup2` system call is  obsolete on aarch64 ,unfortunately.
https://marcin.juszkiewicz.com.pl/download/tables/syscalls.html

Hence, I'll change the tested system call from `dup2` to `dup3`.

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
