### PR TITLE
network: Fix error message for setting hardware address on TAP interface

### PR DESCRIPTION
**Pull request by chenhengqi**
Error out with the correct interface name and hardware address instead.

Signed-off-by: Hengqi Chen <chenhengqi@outlook.com>

### CODE REVIEW

**Comment by liubin** [comment]
Thank you, @chenhengqi, you should update your commit message by [this format](https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format).

**Comment by chenhengqi** [comment]
OK, added a `Fixes` tag and force pushed.

**Review by liubin — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @chenhengqi!

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
