### PR TITLE
docs: Remove duplicate sentences

### PR DESCRIPTION
**Pull request by xinydev**
Fixes: https://github.com/kata-containers/kata-containers/issues/5926

Signed-off-by: Xin Yang <xinydev@gmail.com>

### CODE REVIEW

**Comment by Ji-Xinyou** [comment]
@xinydev Please reference the previous PRs and commit messages. You need a `related issue` and a `commit message body`

**Comment by xinydev** [comment]
> @xinydev Please reference the previous PRs and commit messages. You need a `related issue` and a `commit message body`

Thanks for the reminder, I have changed it

**Review by Ji-Xinyou — APPROVED** [review]

**Review by Tim-0731-Hzt — APPROVED** [review]

**Review by cmaf — APPROVED** [review]

**Comment by xinydev** [comment]
Looks like a no-backport-needed label is needed here, I don't have permission to add

**Comment by liubin** [comment]
> Looks like a no-backport-needed label is needed here, I don't have permission to add

This check is not required, wait for `test` and `test-dragonball` to be triggered.

**Pull request merged**
