### PR TITLE
[backport | stable-2.0] allow network sysctl backport

### PR DESCRIPTION
**Pull request by snir911**
This is backporting of #1229, the two first patches are required only for clean porting, can also modified and backported without them

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
@snir911, thanks for the backport!

The first patch is not intrusive at all, that's fine by me. The second patch looks like something we'd like to have it backported regardless of the third patch, isn't it?

So, all in all, this looks reasonable to me, thanks!

**Comment by snir911** [comment]
Closing, coverd by #1251

**Pull request closed without merging**
