### PR TITLE
versions: Update the rust toolchain to 1.66.0

### PR DESCRIPTION
**Pull request by fidencio**
We're doing the bump on main, as we'll need this as part of the CCv0 branch due to the dependencies we have there.

Link to the 1.66.0 release:
https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1660-2022-12-15

Fixes: #5966

Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

### CODE REVIEW

**Review by Ji-Xinyou — APPROVED** [review]
LGTM, I think this also relates to a pending PR, https://github.com/kata-containers/kata-containers/pull/5754

**Comment by fidencio** [comment]
> LGTM, I think this also relates to a pending PR, #5754

Some of your changes, if not all of them, will still be very much appreciated, by the way!

**Review by arronwy — APPROVED** [review]
Thanks @fidencio , LGTM!

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks @fidencio

**Pull request merged**
