### PR TITLE
backport 2.0-dev commits to stable-2.0.0

### PR DESCRIPTION
**Pull request by bergwolf**
The PR backports commits from `2.0-dev` branch to `stable-2.0.0` branch, up to commit 80cfd01130cdf4268fdc90e2ba094a0d303e1e9e ("Merge pull request #936 from bergwolf/default-virtiofs").

d164de8d package: drop qemu-virtiofs shim
40550628 packaging: install virtiofsd for normal qemu build as well
8eaa9e08 runtime: enable virtiofs by default
529b4d5f runtime: Pass `--thread-pool-size=1` to virtiofsd
f0dfd2df packaging: Apply virtiofs performance related fixes to 5.x
b77c6e3e tools: Improve agent-ctl README
23381b3b tools: Make agent-ctl support more APIs
a5865155 tools: Remove commented out code in agent-ctl
70d92e82 tools: Log request in agent-ctl tool if debug enabled
77f8c5c9 tools: Rename agent-ctl command to GetGuestDetails
fec6bb8c tools: Fix comment in agent-ctl
255df961 kernel: update to 5.4.71
774788eb config: make virtio-fs part of standard kernel
ee8adc01 agent: remove `unwrap()` for `e.as_errno()`
76a695ff agent: Use `?` instead of `match` when the error returns directly
ba4af9d1 kata-monitor: use regexp to check if runtime is kata containers
8fe74601 agent: use anyhow `context` to attach context to `Error` instead of `match`
c27065a8 agent: remove useless match
3e31559b agent: Use `ok_or_else` instead of match for Option -> Result
45ee8e85 agent: Fix crasher if AddARPNeighbors request empty
f3a97dd0 agent: Fix crasher if UpdateRoutes request empty
6ebc9976 agent: Fix crasher if UpdateInterface request empty
be56aea0 agent: replace `match Result` with `or_else`
cea49681 agent: replace unnecessary `match Result` with `map_err`
da9f8bb8 agent: replace check! with map_err for readability
d24ed650 agent: remove `check!` in child process because we cant' see logs.
843db84d agent: replace `if let Err` with `or_else`
cbc366e3 agent: refactor namespace::setup to optimize error handling
eacbc18c agent: replace `if let Err` with `map_err`
fb68d770 rustjail: add length check for uid_mappings in rootless euid mapping
e38e8410 versions: Update Kubernetes, containerd, cri-o and cri-tools
671430d9 annotations: Correct unit tests to validate new protections
3fea21b5 annotations: Split addHypervisorOverrides to reduce complexity
5de01111 annotations: Add unit test for checkPathIsInGlobs
02bd651f annotations: Add unit test for regexpContains function
d9c87288 makefile: Add missing generated vars to `USER_VARS`
c0ef6bf2 makefile: Improve names of config entries for annotation checks
17f3ee84 annotations: Give better names to local variabes in search functions
49a00e99 annotations: Rename checkPathIsInGlobList with checkPathIsInGlobs
ed088dfe config: Add better comments in the template files
39097c54 config: Whitelist hypervisor annotations by name
6afc1c07 config: Use glob instead of regexp to match paths in annotations
1e7bc0ff annotations: Fix typo in comment
4a391e8f config: Add makefile variables for path lists
9dcf6473 config: Protect file_mem_backend against annotation attacks
677d329b config: Protect vhost_user_store_path against annotation attacks
72bb71fb config: Add security warning on configuration examples
2e8f2cc7 config: Protect ctlpath from annotation attack
c31b4c49 config: Protect jailer_path annotation
8a34cc00 config: Add examples for path_list configuration
f22e4b60 annotations: Simplify negative logic
c238d036 config: Add hypervisor path override through annotations
c4614bd5 config: Fix typo in function name
e7e615b7 config: Protect virtio_fs_daemon annotation
1fedaf85 config: Add 'List' alternates for hypervisor configuration paths
c749bb1e agent: fix panic on malformed device resource in container update
e80b36ba cpuset: add cpuset pkg
986a0160 cpuset: don't set cpuset.mems in the guest
8a208f79 sandbox: consider cpusets if quota is not enforced
dc9b3cbf cpuset: support setting mems for sandbox
9f464966 virtcontainers: add method for calculating cpuset for sandbox
dd486a6d cpuset: add cpuset pkg
c4f57a51 docs: Update upgrading guide
6362c530 docs: update the build kata containers kernel document
82e307da agent/device: Check type as well as major:minor when looking up devices
1b78ae21 agent/device: Index all devices in spec before updating them
2ad22175 agent/device: Forward port update_spec_device_list() unit test
3d6445cd agent/device: update_spec_device_list() should error if dev not found
9eb780e8 sandbox: don't constrain cpus, mem only cpuset, devices
034f1eff cgroups: add ability to update CPUSet
ce07a0c0 agent: fix errorneous parsing for guest block size
7e134cc6 docs: Add containerd install guide
8183ff13 agent: use ok_or/map_err instead of match
5937b956 rustjail: use Iterator to manipulate vector elements
07762036 rustjail: delete codes commented out
37feef5e rustjail: delete unused test code
650800ee agent: use chain of Result to avoid early return
12dd7529 agent: update not accurate comments
63af4b0a agent: use macro to simplify parse_cmdline function in config.rs
b21c8f97 agent: add blank lines between methods
5079937a agent: delete unused field in agentService
ac609795 agent: use no-named closure to reduce codes
c4339541 agent: use a local fn to reduce duplicated codes
e1afe2a6 packaging: fix cloud-hypervisor binary path
26ad704a packaging: fix missing cloud_hypervisor_repo
1c9b43b6 packaging: apply qemu v5.1 stable fixes
598debe7 agent: fix aarch64 build
c1d63acc docs: add namespace key to pod/container config files
0aa15c3c docs: Add crictl example json files
01c30402 runtime: Clear the VCMock 1.x API Methods from 2.0
57d844e0 ci: snap: add event filtering
ab88d144 agent: do not follow link when mounting container proc and sysfs
03ed5dba agent: set init process non-dumpable
0fa83d5b agent-ctl: include cargo lock updates
aefffbb9 versions: add plugins section
0a2478b6 virtiofs: Disable DAX
fe5341da snap: specify python version
650ffd80 osbuilder: Create target directory for agent
fa7f24cf rust-agent: Treat warnings as error
3ebb1390 rust-agent: Identify unused results in tests
73cbbf8d rust-agent: Log returned errors rather than ignore them
7d82f540 rust-agent: Remove unused imports
b32d07d9 rust-agent: Report errors to caller if possible
819fb62f rust-agent: Ignore write errors while writing to the logs
fa675b1d rust-agent: Remove unused code that has undefined behavior
29fd432f rust-agent: Remove 'mut' where not needed
798d1423 rust-agent: Remove uses of deprecated functions
94d44dd3 rust-agent: Remove or rename unused parameters
c746eebb rust-agent: Remove or rename unused variables
f8a8f8c7 rust-agent: Remove unused functions
cd64ea80 rust-agent: Remove useless braces
d78f9776 rust-agent: Remove unused macros
48ce64d5 packaging: Revert "packaging: Stop providing OBS packages"
d9c8b616 clh: Support VFIO device unplug
8f9fd59c clh: Remove unnecessary VmmPing
693971f3 versions: cloud-hypervisor: Bump to version 6d30fe05
598df664 docs: Change kata_tap0 to tap0_kata
1d913776 docs: update networking description
87fffcdf dev-guide: update kata-agent install details
5268c1ba docs: Update docs for enabling agent debug console
daff2e88 docs: update dev guide for agent build
fffc96d8 ci: add github action to test the snap
a84c387c versions: cloud-hypervisor: bump version
936fcf3c runtime: cloud-hypervisor: tag openapi-generator-cli container

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
thanks, @bergwolf!

**Review by gnawux — APPROVED** [review]
great job

**Comment by bergwolf** [comment]
ah, need to backport tests commits to tests repo `stable-2.0.0` as well.

**Comment by bergwolf** [comment]
These two are marked `required` but cannot be triggered?
```
check-pr-porting-labels Expected — Waiting for status to be reported
jenkins-ci-ubuntu-1804-cloud-hypervisor-k8s-containerd-2.0 Expected — Waiting for status to be reported
```

**Comment by egernst** [comment]
Why is SGX a stability/bug fix?

**Review by egernst — CHANGES_REQUESTED** [review]
Question on some of the back ports. Overall looks good...

**Comment by bergwolf** [comment]
@egernst Good point! Let me drop it. Thanks!

**Review by egernst — APPROVED** [review]

**Comment by bergwolf** [comment]
* `jenkins-ci-ARM-ubuntu-18-04 ` is under investigation in https://github.com/kata-containers/tests/pull/2980. ARM CI was having environment issues in the last few days and just came back to being usable.

* `jenkins-vfio-host:ubuntu18-04-vm:fedora32` failed on accessing `.ci/vfio_jenkins_job_build.sh` script and should be fixed by https://github.com/kata-containers/tests/pull/2979, which has passed `jenkins-vfio-host:ubuntu18-04-vm:fedora32` test. Somehow the `Depends-on` tag is not working for VFIO.
```
00:54:51 + .ci/vfio_jenkins_job_build.sh github.com/kata-containers/kata-containers
00:54:51 ci_entry_point.sh: line 70: .ci/vfio_jenkins_job_build.sh: No such file or directory
00:54:51 ++ handle_error 70
```

**Pull request merged**
