### PR TITLE
virtcontainers: clean up useless code

### PR DESCRIPTION
**Pull request by rapiz1**
Fixes: #2275

### CODE REVIEW

**Comment by Rapiz1** [comment]
@liubin Could you kindly review?

**Comment by liubin** [comment]
@Rapiz1 welcome to Kata Containers community, but first, you should update your commit message as our development guideline suggested. You can read [this](http://liubin.org/kata-dev-book/src/your-first-pr.html) to get an example.

**Comment by Rapiz1** [comment]
@liubin Thanks for pointing it out. I've update the commit message.

**Review by sameo — APPROVED** [review]

**Comment by liubin** [comment]
The commit body is: 

```
virtcontainers: clean up useless code
Fixes: #2275

Signed-off-by: Yujia Qiao <rapiz3142@gmail.com>
```

The body only contains Fixes and SoB. Is this by design or changed recently?

CC @jodh-intel @fidencio @Tim-Zhang @bergwolf

**Review by liubin — APPROVED** [review]

**Pull request merged**
