### PR TITLE
Use github action to do Fixes/Length/Subsystem check for commit message

### PR DESCRIPTION
**Pull request by Tim-Zhang**
The commit checks does not need to wait for CI dependencies to be installed,
It's a waste of time. we need show errors ASAP.

And we should display as many problems as possible at once
Fixes: #487

See preview here: https://github.com/Tim-Zhang/test/actions/runs/194701719

Signed-off-by: Tim Zhang <tim@hyper.sh>

### CODE REVIEW

**Comment by Tim-Zhang** [comment]
@jodh-intel The https://github.com/kata-containers/.github repo stores issue templates for now, There is no workflow in it. 
Are you sure you want me to add workflows in the repo?

if so we should add workflows `PR-wip-checks` too.

**Comment by Tim-Zhang** [comment]
I have update the code to support long line already, need test tomorrow.

**Comment by jodh-intel** [comment]
Thanks @Tim-Zhang!

**Comment by jodh-intel** [comment]
@Tim-Zhang - the `.github` repo was supposed to be for all common github config. However, on reflection, maybe you are right and it does make sense to do all the new magic in *this* repo (for Kata 2.x) and leave the other repos "as is" to avoid disrupting them.

wdyt @chavafg, @gnawux, @amshinde?

**Comment by liubin** [comment]
Now:

```
    - name: Check Subject Line Length
      uses: tim-actions/commit-message-checker-with-regex@v0.3.0
      with:
        commits: ${{ steps.get-pr-commits.outputs.commits }}
        pattern: '^.{0,75}(\n.*)*$'
        error: 'Subject too long (max 75)'
        post_error: |+
          See the document below for help on formatting commits for the project.
          https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format
    - name: Check Body Line Length
      if: ${{ success() || failure() }}
      uses: tim-actions/commit-message-checker-with-regex@v0.3.0
      with:
        commits: ${{ steps.get-pr-commits.outputs.commits }}
        pattern: '^.+(\n.{0,72})*$|^.+\n\s*[^a-zA-Z\s\n]'
        error: 'Body line too long (max 72)'
        post_error: |+
          See the document below for help on formatting commits for the project.
          https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format

```

How about changing to:

```
    - name: Commits Check
      uses: tim-actions/commit-message-checker-with-regex@v0.3.0
      with:
        commits: ${{ steps.get-pr-commits.outputs.commits }}
        post_error: |+
          See the document below for help on formatting commits for the project.
          https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format
        - rule:   Check Subject Line Length
          pattern: '^.{0,75}(\n.*)*$'
          error: 'Subject too long (max 75)'
        - rule: Check Body Line Length
          pattern: '^.+(\n.{0,72})*$|^.+\n\s*[^a-zA-Z\s\n]'
          error: 'Body line too long (max 72)'
```

**Comment by Tim-Zhang** [comment]
@liubin I can not agree with you, I think different checks should be separated into different steps for flexible.

**Comment by Tim-Zhang** [comment]
@jodh-intel Those errors are not duplicate. I mean to write these message repeatedly because I can't find a better way to show the error tips.  
You can check the effect https://github.com/Tim-Zhang/test/actions/runs/194701719 . The error tips should display in every step.

**Comment by jodh-intel** [comment]
Hi @Tim-Zhang - All I mean is that currently there are multiple instances of the `post_error` string - they all have exactly the same sentence and the same URL. My diff used a YAML anchor to avoid that so you can define the static string one and reference multiple times.

**Comment by Tim-Zhang** [comment]
@jodh-intel sorry... I have applied your patch and do some minor updates for obey the syntax check of github action.

**Comment by jodh-intel** [comment]
As an updated to here:https://github.com/kata-containers/kata-containers/pull/486#pullrequestreview-460778578, I've discovered that actions only work for the repo they are defined in - somewhat frustratingly, you cannot seemingly put them in the magic https://github.com/kata-containers/.github repo to make them apply to all the repos in the org :sob:

**Comment by amshinde** [comment]
> As an update to [#486 (review)](https://github.com/kata-containers/kata-containers/pull/486#pullrequestreview-460778578), I've discovered that actions only work for the repo they are defined in - somewhat frustratingly, you cannot seemingly put them in the magic https://github.com/kata-containers/.github repo to make them apply to all the repos in the org

@jodh-intel Thanks for checking this. Maybe raise a feature request for this with them?

@Tim-Zhang Thanks for taking this up. Are you planning to port these checks for 1.x repos?

**Comment by bergwolf** [comment]
DCO check seems stuck?

**Comment by Tim-Zhang** [comment]
> DCO check seems stuck?

It's not a problem because I updated moved the DCO into Commit Message Check.

**Pull request merged**
