### PR TITLE
CCv0: Merge main into CCv0 branch

### PR DESCRIPTION
**Pull request by GeorginaKin**
Merge remote-tracking branch 'upstream/main' into CCv0
    
Fixes: #5696
Signed-off-by: Georgina Kinge <georgina.kinge@ibm.com>

### CODE REVIEW

**Comment by GeorginaKin** [comment]
```
git diff --stat upstream/main -- . ':!*/vendor/*'
 .github/workflows/cc-payload-after-push.yaml                                       |   98 +
 .github/workflows/cc-payload.yaml                                                  |   88 +
 .github/workflows/commit-message-check.yaml                                        |    4 +-
 .github/workflows/deploy-ccv0-demo.yaml                                            |  129 ++
 ci/install_libseccomp.sh                                                           |    3 +-
 docs/how-to/README.md                                                              |    4 +
 docs/how-to/ccv0.sh                                                                |  640 ++++++
 docs/how-to/data/confidential-agent-config.toml.in                                 |   45 +
 docs/how-to/how-to-build-and-test-ccv0.md                                          |  479 +++++
 ...-generate-a-kata-containers-payload-for-the-confidential-containers-operator.md |   44 +
 docs/how-to/how-to-setup-swap-devices-in-guest-kernel.md                           |    2 +
 docs/how-to/how-to-use-virtio-fs-nydus-with-kata.md                                |    1 +
 docs/how-to/how-to-use-virtio-mem-with-kata.md                                     |    2 +
 src/agent/Cargo.lock                                                               | 4131 +++++++++++++++++++++++++++++++++++----
 src/agent/Cargo.toml                                                               |    8 +-
 src/agent/Makefile                                                                 |    8 +
 src/agent/rustjail/src/cgroups/fs/mod.rs                                           |   19 +-
 src/agent/rustjail/src/lib.rs                                                      |    8 +-
 src/agent/src/config.rs                                                            |  327 +++-
 src/agent/src/device.rs                                                            |   18 +-
 src/agent/src/image_rpc.rs                                                         |  412 ++++
 src/agent/src/main.rs                                                              |    1 +
 src/agent/src/rpc.rs                                                               |  197 +-
 src/agent/src/sandbox.rs                                                           |    2 +
 src/agent/src/signal.rs                                                            |    2 +-
 src/libs/oci/src/lib.rs                                                            |   10 +-
 src/libs/protocols/.gitignore                                                      |    3 +
 src/libs/protocols/build.rs                                                        |   21 +-
 src/libs/protocols/protos/image.proto                                              |   31 +
 src/libs/protocols/src/lib.rs                                                      |    4 +
 src/libs/protocols/src/trans.rs                                                    |    4 +-
 src/runtime/Makefile                                                               |  137 ++
 src/runtime/arch/amd64-options.mk                                                  |    2 +
 src/runtime/cmd/kata-runtime/kata-check_amd64.go                                   |    2 +
 src/runtime/cmd/kata-runtime/kata-check_arm64.go                                   |    3 +
 src/runtime/cmd/kata-runtime/kata-check_ppc64le.go                                 |    3 +
 src/runtime/cmd/kata-runtime/kata-check_s390x.go                                   |    3 +
 src/runtime/config/configuration-clh-tdx-eaa-kbc.toml.in                           |  428 ++++
 src/runtime/config/configuration-clh-tdx.toml.in                                   |  428 ++++
 src/runtime/config/configuration-clh.toml.in                                       |    2 +-
 src/runtime/config/configuration-qemu-sev.toml.in                                  |  660 +++++++
 src/runtime/config/configuration-qemu-tdx-eaa-kbc.toml.in                          |  636 ++++++
 src/runtime/config/configuration-qemu-tdx.toml.in                                  |  636 ++++++
 src/runtime/config/configuration-qemu.toml.in                                      |   27 +-
 src/runtime/go.mod                                                                 |    2 +
 src/runtime/go.sum                                                                 |  278 +--
 src/runtime/hack/update-generated-hypervisor-proto.sh                              |   13 +
 src/runtime/pkg/README.md                                                          |    1 +
 src/runtime/pkg/containerd-shim-v2/create.go                                       |    5 +
 src/runtime/pkg/containerd-shim-v2/image.go                                        |   84 +
 src/runtime/pkg/govmm/qemu/qemu.go                                                 |   28 +-
 src/runtime/pkg/govmm/qemu/qmp.go                                                  |   66 +
 src/runtime/pkg/katautils/config-settings.go.in                                    |    7 +
 src/runtime/pkg/katautils/config.go                                                |  267 +--
 src/runtime/pkg/oci/utils.go                                                       |    5 +
 src/runtime/pkg/oci/utils_test.go                                                  |    2 +-
 src/runtime/pkg/sev/README.md                                                      |   14 +
 src/runtime/pkg/sev/sev.go                                                         |  165 ++
 src/runtime/pkg/sev/sev_test.go                                                    |   32 +
 src/runtime/pkg/sev/testdata/README.md                                             |    9 +
 src/runtime/pkg/sev/testdata/ovmf_suffix.bin                                       |  Bin 0 -> 4096 bytes
 src/runtime/protocols/hypervisor/hypervisor.pb.go                                  | 1848 +++++++++++++++++
 src/runtime/protocols/hypervisor/hypervisor.proto                                  |   46 +
 src/runtime/protocols/simple-kbs/keybroker.pb.go                                   |  573 ++++++
 src/runtime/protocols/simple-kbs/keybroker.proto                                   |   68 +
 src/runtime/protocols/simple-kbs/keybroker_grpc.pb.go                              |  141 ++
 src/runtime/virtcontainers/acrn.go                                                 |    9 +
 src/runtime/virtcontainers/agent.go                                                |    3 +
 src/runtime/virtcontainers/clh.go                                                  |   15 +-
 src/runtime/virtcontainers/container.go                                            |    5 +
 src/runtime/virtcontainers/fc.go                                                   |    4 +
 src/runtime/virtcontainers/fs_share_linux.go                                       |   57 +-
 src/runtime/virtcontainers/hypervisor.go                                           |  430 ++--
 src/runtime/virtcontainers/hypervisor_config_darwin.go                             |    4 +
 src/runtime/virtcontainers/hypervisor_config_linux.go                              |    4 +
 src/runtime/virtcontainers/hypervisor_linux.go                                     |    2 +
 src/runtime/virtcontainers/image/image.go                                          |   23 +
 src/runtime/virtcontainers/interfaces.go                                           |    3 +
 src/runtime/virtcontainers/kata_agent.go                                           |  156 +-
 src/runtime/virtcontainers/mock_agent.go                                           |    5 +
 src/runtime/virtcontainers/mock_hypervisor.go                                      |    4 +
 src/runtime/virtcontainers/monitor.go                                              |   11 +-
 src/runtime/virtcontainers/mount.go                                                |   24 +-
 src/runtime/virtcontainers/pkg/agent/protocols/client/client.go                    |   35 +
 src/runtime/virtcontainers/pkg/agent/protocols/grpc/image.pb.go                    |  613 ++++++
 src/runtime/virtcontainers/pkg/mock/mock.go                                        |    4 +
 src/runtime/virtcontainers/pkg/vcmock/sandbox.go                                   |    5 +
 src/runtime/virtcontainers/qemu.go                                                 |  120 +-
 src/runtime/virtcontainers/qemu_amd64.go                                           |  199 +-
 src/runtime/virtcontainers/qemu_amd64_test.go                                      |   24 +-
 src/runtime/virtcontainers/qemu_arch_base.go                                       |   56 +-
 src/runtime/virtcontainers/remote.go                                               |  298 +++
 src/runtime/virtcontainers/sandbox.go                                              |   82 +-
 src/runtime/virtcontainers/types/sandbox.go                                        |   12 +
 src/tools/agent-ctl/src/client.rs                                                  |  117 +-
 src/tools/agent-ctl/src/utils.rs                                                   |    2 +-
 tools/osbuilder/image-builder/Dockerfile                                           |    1 +
 tools/osbuilder/image-builder/image_builder.sh                                     |   22 +-
 tools/osbuilder/rootfs-builder/README.md                                           |    6 +
 tools/osbuilder/rootfs-builder/agent-config.toml.in                                |   44 +
 tools/osbuilder/rootfs-builder/alpine/Dockerfile.in                                |    4 +
 tools/osbuilder/rootfs-builder/clearlinux/Dockerfile.in                            |    5 +
 tools/osbuilder/rootfs-builder/init_trusted_storage.sh                             |  130 ++
 tools/osbuilder/rootfs-builder/rootfs.sh                                           |  101 +
 tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in                                |   26 +-
 tools/osbuilder/rootfs-builder/ubuntu/config.sh                                    |   22 +-
 tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh                                |   28 +-
 tools/osbuilder/scripts/lib.sh                                                     |   25 +
 tools/packaging/guest-image/build_image.sh                                         |   59 +-
 tools/packaging/kata-deploy-cc/Dockerfile                                          |   30 +
 tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh                              |  289 +++
 tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml                    |    2 +-
 tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml                      |    4 +-
 tools/packaging/kata-deploy/local-build/Makefile                                   |   68 +
 tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile                     |   16 +-
 tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh          |   20 +-
 tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh                    |  209 +-
 tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh    |   36 +
 tools/packaging/kata-deploy/scripts/kata-deploy.sh                                 |    0
 tools/packaging/kernel/build-kernel.sh                                             |   35 +-
 .../kernel/configs/fragments/common/confidential_containers/cryptsetup.conf        |   21 +
 .../kernel/configs/fragments/common/confidential_containers/initramfs.conf         |    1 +
 tools/packaging/kernel/configs/fragments/x86_64/crypto.conf                        |    3 +
 tools/packaging/scripts/lib.sh                                                     |   82 +
 tools/packaging/static-build/cache_components.sh                                   |  114 ++
 tools/packaging/static-build/cloud-hypervisor/build-static-clh.sh                  |   39 +-
 tools/packaging/static-build/initramfs/Dockerfile                                  |   72 +
 tools/packaging/static-build/initramfs/build-initramfs.sh                          |   15 +
 tools/packaging/static-build/initramfs/build.sh                                    |   49 +
 tools/packaging/static-build/initramfs/init.sh                                     |   44 +
 tools/packaging/static-build/initramfs/initramfs.list                              |   21 +
 tools/packaging/static-build/kernel/Dockerfile                                     |    1 +
 tools/packaging/static-build/kernel/build.sh                                       |    9 +-
 tools/packaging/static-build/ovmf/build.sh                                         |    7 +-
 tools/packaging/static-build/qemu/build-base-qemu.sh                               |   21 +-
 tools/packaging/static-build/qemu/build-static-qemu-cc.sh                          |   94 +
 tools/packaging/static-build/shim-v2/build.sh                                      |   42 +-
 tools/packaging/static-build/shim-v2/install_go_rust.sh                            |   12 +-
 tools/packaging/static-build/td-shim/Dockerfile                                    |    4 +-
 tools/packaging/static-build/td-shim/build-td-shim.sh                              |    4 +-
 tools/packaging/static-build/td-shim/build.sh                                      |   13 +-
 tools/packaging/static-build/virtiofsd/build.sh                                    |   14 +-
 tools/packaging/static-build/virtiofsd/gnu/Dockerfile                              |    3 +-
 tools/packaging/static-build/virtiofsd/musl/Dockerfile                             |    3 +-
 utils.mk                                                                           |    4 +-
 versions.yaml                                                                      |   51 +-
 146 files changed, 16237 insertions(+), 1380 deletions(-)
```

**Review by GabyCT — APPROVED** [review]

**Comment by stevenhorsman** [comment]
Sorry, I was being slow about the:
```
INFO: Running 'static_check_docs' function
INFO: Installing xurls utility
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
make: *** [Makefile:41: static-checks] Error 1
```
failure.

It is because the fix to that is in the tests repo, so I think we need to get https://github.com/kata-containers/tests/pull/5270 merged first before this will run (or pull it in as a dependency and flip the logic if that isn't possible

**Comment by fidencio** [comment]
TDX Cloud Hypervisor CI is failing, and rather than blocking this PR I've created https://github.com/kata-containers/tests/issues/5276 to track this down and figure out the issue.

I'm running the TDX QEMU CI now, if that one passes I'd be fine on merging this one.

**Comment by fidencio** [comment]
> TDX Cloud Hypervisor CI is failing, and rather than blocking this PR I've created [kata-containers/tests#5276](https://github.com/kata-containers/tests/issues/5276) to track this down and figure out the issue.
> 
> I'm running the TDX QEMU CI now, if that one passes I'd be fine on merging this one.

This also failed with QEMU.

As it passed on the tests PR that was depending on this one, I'd like to have this one merged and track the issue as a new issue rather than blocking this PR.

**Pull request merged**
