### PR TITLE
docs: Add contributing and code of conduct docs

### LINKED ISSUE #13: Add missing standard docs
This repo needs:

- a contributing doc
- a code of conduct doc

### PR DESCRIPTION
**Pull request by jodh-intel**
Add the standard contributing and code of conduct documents.

Fixes #13.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
@kata-containers/kata-containers @kata-containers/documentation - any objections before we merge this one?

**Comment by jodh-intel** [comment]
5... 4... 3...

**Comment by gnawux** [comment]
No objection I think

On Mar 1, 2018 22:52, "Graham Whaley" <notifications@github.com> wrote:

@kata-containers/kata-containers
<https://github.com/orgs/kata-containers/teams/kata-containers>
@kata-containers/documentation
<https://github.com/orgs/kata-containers/teams/documentation> - any
objections before we merge this one?

—
You are receiving this because you are on a team that was mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/kata-containers/kata-containers/pull/14#issuecomment-369616223>,
or mute the thread

**Comment by grahamwhaley** [comment]
yeah, somewhat over-due. Any late-objectors please re-open an Issue and/or PR...

**Pull request merged**
