### PR TITLE
runtime: Switch to using the rust version of virtiofsd (all arches but powerpc)

### PR DESCRIPTION
**Pull request by fidencio**
So far this has been done for x86_64.  Now that the support for building
and testing has been added for all arches, let's do the full switch.

Fixes: #4258, #4259, #4260

Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>

### CODE REVIEW

**Comment by fidencio** [comment]
s390x error is not related as it's not even using virtiofsd.

The other arches (power and arm) are failing due to (or very similar).
```
ctr: failed to create shim: failed to launch qemu: exit status 1, error messages from qemu log: qemu-system-ppc64: -device vhost-user-fs-pci,chardev=char-59c5926825f6071e,tag=kataShared: Failed to read msg header. Read 0 instead of 12. Original request 1.
qemu-system-ppc64: -device vhost-user-fs-pci,chardev=char-59c5926825f6071e,tag=kataShared: vhost_backend_init failed: Protocol error
: unknown
```

/cc @Amulyam24 @jongwu

**Comment by Amulyam24** [comment]
> s390x error is not related as it's not even using virtiofsd.
> 
> The other arches (power and arm) are failing due to (or very similar).
> 
> ```
> ctr: failed to create shim: failed to launch qemu: exit status 1, error messages from qemu log: qemu-system-ppc64: -device vhost-user-fs-pci,chardev=char-59c5926825f6071e,tag=kataShared: Failed to read msg header. Read 0 instead of 12. Original request 1.
> qemu-system-ppc64: -device vhost-user-fs-pci,chardev=char-59c5926825f6071e,tag=kataShared: vhost_backend_init failed: Protocol error
> : unknown
> ```
> 
> /cc @Amulyam24 @jongwu

Hi @fidencio, I believe to have seen this earlier on `ppc64le`. Let me debug further and get back on it.

**Comment by jongwu** [comment]
Hello @fidencio @Amulyam24 -, that's my fault. I should export the build env before build virtiofsd. So, the virtiofsd for non-x86 is not static.
Try adding "export" before [here](https://github.com/kata-containers/kata-containers/blob/62d1ed06512377f949d6e966152795351be1e18a/tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh#L74) and the following env setting will do.

**Comment by fidencio** [comment]
@Amulyam24, the power CI is failing with:
```
ctr: failed to create shim: fork/exec /usr/libexec/virtiofsd: no such file or directory: not found
ctr: failed to create shim: fork/exec /usr/libexec/virtiofsd: no such file or directory: not found
ctr: failed to create shim: fork/exec /usr/libexec/virtiofsd: no such file or directory: not found
```

But looking at the logs it seems that virtiofsd was correctly build and installed.
It's installed in /opt/kata/libexec/virtiofsd, but there's a symbolic link to it under /usr/libexec/virtiofsd.

Mind to take a deeper look on what may be going on?

**Comment by fidencio** [comment]
> @Amulyam24, the power CI is failing with:
> 
> ```
> ctr: failed to create shim: fork/exec /usr/libexec/virtiofsd: no such file or directory: not found
> ctr: failed to create shim: fork/exec /usr/libexec/virtiofsd: no such file or directory: not found
> ctr: failed to create shim: fork/exec /usr/libexec/virtiofsd: no such file or directory: not found
> ```
> 
> But looking at the logs it seems that virtiofsd was correctly build and installed. It's installed in /opt/kata/libexec/virtiofsd, but there's a symbolic link to it under /usr/libexec/virtiofsd.
> 
> Mind to take a deeper look on what may be going on?

@jongwu, that's the same failure on ARM as well.

**Review by amshinde — APPROVED** [review]

**Review by cmaf — APPROVED** [review]

**Comment by jongwu** [comment]
Hi @fidencio -, we should export all of the build ENVs before building virtiofsd, like:

>    export RUSTFLAGS='-C target-feature=+crt-static -C link-self-contained=yes'
   export LIBSECCOMP_LINK_TYPE=static
   export LIBSECCOMP_LIB_PATH=/usr/lib/${ARCH_LIBC}
   export LIBCAPNG_LINK_TYPE=static
   export LIBCAPNG_LIB_PATH=/usr/lib/${ARCH_LIBC}

**Comment by fidencio** [comment]
And we're back to:
```
ctr: failed to create shim: failed to launch qemu: exit status 1, error messages from qemu log: qemu-system-ppc64: -device vhost-user-fs-pci,chardev=char-341a7fa549c056f3,tag=kataShared: Failed to read msg header. Read 0 instead of 12. Original request 1.
qemu-system-ppc64: -device vhost-user-fs-pci,chardev=char-341a7fa549c056f3,tag=kataShared: vhost_backend_init failed: Protocol error
: unknown
```

**Comment by Amulyam24** [comment]
> And we're back to:
> 
> ```
> ctr: failed to create shim: failed to launch qemu: exit status 1, error messages from qemu log: qemu-system-ppc64: -device vhost-user-fs-pci,chardev=char-341a7fa549c056f3,tag=kataShared: Failed to read msg header. Read 0 instead of 12. Original request 1.
> qemu-system-ppc64: -device vhost-user-fs-pci,chardev=char-341a7fa549c056f3,tag=kataShared: vhost_backend_init failed: Protocol error
> : unknown
> ```

@fidencio, I've tried reproducing this issue locally and I see that virtiofsd crashes. I'm planning to gather more info and create an issue in the official repo for some help in resolving it. Does it sound okay since it might block this PR or do you want to proceed by neglecting this change for `ppc64le` for now?(I'm aware that the failing Power CI is dependent on this change)

**Comment by fidencio** [comment]
> 

Perfect, so I will rollback the change for Power, let you debug and open an issue on their repo, and proceed with the merging of this one doing the switch for ARM.

**Review by jongwu — COMMENTED** [review]
Should install rust before install virtiofsd in snap build.

**Review by jodh-intel — COMMENTED** [review]
Hi @fidencio - Thanks for raising. The snap changes should be something like this (I'm happy to test them if you want to add them to this PR):

```diff
diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
index badfc99ee..d3d1cba75 100644
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -275,17 +275,16 @@ parts:
     override-build: |
       source "${SNAPCRAFT_PROJECT_DIR}/snap/local/snap-common.sh"

-      # Currently, only one platform uses the new rust virtiofsd. The
-      # others make use of QEMU's C implementation.
-      #
-      # See "tools/packaging/scripts/configure-hypervisor.sh".
-      if [ "${arch}" = 'x86_64' ]
+      if [ "${arch}" = 'ppc64le' ]
       then
-          echo "INFO: Building rust version of virtiofsd"
-      else
+          # This platform uses QEMU's C implementation of virtiofsd,
+          # which is handled by the 'qemu' part, so nothing more to do here.
+          #
+          # See "tools/packaging/scripts/configure-hypervisor.sh".
           echo "INFO: Building QEMU's C version of virtiofsd"
-          # Handled by the 'qemu' part, so nothing more to do here.
           exit 0
+      else
+          echo "INFO: Building rust version of virtiofsd"
       fi

       cd "${kata_dir}"
```

**Comment by fidencio** [comment]
> Hi @fidencio - Thanks for raising. The snap changes should be something like this (I'm happy to test them if you want to add them to this PR):
> 
> ```diff
> diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
> index badfc99ee..d3d1cba75 100644
> --- a/snap/snapcraft.yaml
> +++ b/snap/snapcraft.yaml
> @@ -275,17 +275,16 @@ parts:
>      override-build: |
>        source "${SNAPCRAFT_PROJECT_DIR}/snap/local/snap-common.sh"
> 
> -      # Currently, only one platform uses the new rust virtiofsd. The
> -      # others make use of QEMU's C implementation.
> -      #
> -      # See "tools/packaging/scripts/configure-hypervisor.sh".
> -      if [ "${arch}" = 'x86_64' ]
> +      if [ "${arch}" = 'ppc64le' ]
>        then
> -          echo "INFO: Building rust version of virtiofsd"
> -      else
> +          # This platform uses QEMU's C implementation of virtiofsd,
> +          # which is handled by the 'qemu' part, so nothing more to do here.
> +          #
> +          # See "tools/packaging/scripts/configure-hypervisor.sh".
>            echo "INFO: Building QEMU's C version of virtiofsd"
> -          # Handled by the 'qemu' part, so nothing more to do here.
>            exit 0
> +      else
> +          echo "INFO: Building rust version of virtiofsd"
>        fi
> 
>        cd "${kata_dir}"
> ```

I've added this last week, @jodh-intel, please, take a look at https://github.com/kata-containers/kata-containers/pull/4308/commits/ad0b26e834e6cd8096fa1bee807d3bfcbd6ce3e9#diff-56759910381a014fecfd7556dd72ddd68c747d922a5b7df2044b9ce7c552f5f5R275-R291

**Comment by jodh-intel** [comment]
Thanks @fidencio !

**Comment by jongwu** [comment]
ARM CI fails for 

> tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh: line 80: cargo: command not found

We should install rust before build virtiofsd in snap build. @fidencio

**Comment by BbolroC** [comment]
> ARM CI fails for
> 
> > tools/packaging/static-build/virtiofsd/build-static-virtiofsd.sh: line 80: cargo: command not found
> 
> We should install rust before build virtiofsd in snap build. @fidencio

same on s390x :wink:

**Comment by jodh-intel** [comment]
Related: #4249, #4253.

**Pull request merged**
