### PR TITLE
Dragonball: update linux_loader to 0.6.0

### PR DESCRIPTION
**Pull request by studychao**
Since linux-loader 0.4.0 and 0.5.0 is yanked due to null terminator bug(furture information : https://github.com/rust-vmm/linux-loader/blob/main/CHANGELOG.md ), we need to update linux-loader to 0.6.0.

And as_str() function should also be changed.

fixes: #5253

Signed-off-by: Chao Wu <chaowu@linux.alibaba.com>

### CODE REVIEW

**Review by Tim-0731-Hzt — APPROVED** [review]

**Review by liubin — APPROVED** [review]

**Comment by Tim-0731-Hzt** [comment]
/(re)test-fedora

**Pull request merged**
