### PR TITLE
ci: replace spaces by tabs as indent

### PR DESCRIPTION
**Pull request by liubin**
Replace spaces by tabs as indent in file ci/lib.sh

Fixes: #743

Signed-off-by: bin liu <bin@hyper.sh>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm!

@jodh-intel, @liubin,
Can we add a test to ensure the code-style is respected?

**Comment by jodh-intel** [comment]
@fidencio - that would be great, but shell is a bit awkward. If anyone can find something that would work or wants to write something, we could add that to https://github.com/kata-containers/tests/blob/master/.ci/static-checks.sh#L967.

**Comment by liubin** [comment]
@jodh-intel @fidencio I found a tool https://github.com/mvdan/sh , which is under active development. And I also did a try for the `ci/` directory:

```diff

-	[ -x  "${GOPATH}/bin/yq" ] && return
+	[ -x "${GOPATH}/bin/yq" ] && return
 
-	read -r -a sysInfo <<< "$(uname -sm)"
+	read -r -a sysInfo <<<"$(uname -sm)"


-clone_tests_repo()
-{
+clone_tests_repo() {
 	# KATA_CI_NO_NETWORK is (has to be) ignored if there is
 	# no existing clone.
-	if [ -d "$tests_repo_dir" -a -n "$KATA_CI_NO_NETWORK" ]
-	then
+	if [ -d "$tests_repo_dir" -a -n "$KATA_CI_NO_NETWORK" ]; then
 		return
 	fi
 
 	go get -d -u "$tests_repo" || true
 
-       if [ -n "${TRAVIS_BRANCH:-}" ]; then
-               ( cd "${tests_repo_dir}" && git checkout "${TRAVIS_BRANCH}" )
-       fi
+	if [ -n "${TRAVIS_BRANCH:-}" ]; then
+		(cd "${tests_repo_dir}" && git checkout "${TRAVIS_BRANCH}")
+	fi
 }

-run_static_checks()
-{
+run_static_checks() {
 	clone_tests_repo
 	bash "$tests_repo_dir/.ci/static-checks.sh" "github.com/kata-containers/kata-containers"
 }
 
-run_go_test()
-{
+run_go_test() {

```

If we add a shell script format check, there will be a bulk update to all script files to meet the tool's required style(also tools may be customed ).

**Comment by fidencio** [comment]
@liubin, @jodh-intel, I see.
I'll open a new issue so we can track the possibility of using a script, does that sound reasonable?

In any case, regardless of using a tool or not, this PR is good to go and should **not** be blocked by my suggestion.

**Comment by jodh-intel** [comment]
@fidencio - A script to track a shell checker sounds perfect to me. That tool looks interesting. Yes, we've done a few bulk updates in the past (I cannot tell you how long it took to ensure all our docs passed the [`check-spelling`](https://github.com/kata-containers/tests/tree/master/cmd/check-spelling) and [`check-markdown`](https://github.com/kata-containers/tests/tree/master/cmd/check-markdown) tests. But it was worth it! :smile:)

**Comment by liubin** [comment]
Hi @fidencio , have you crated the new issue to track this ? If not , I can to create it.

**Pull request merged**
