### PR TITLE
virtcontainers: Add a Virtualization.framework skeleton

### PR DESCRIPTION
**Pull request by dcantah**
Fixes: #6004

A Virtualization.framework based Hypervisor implementation. This is just stubs for now to eventually get this building.

### CODE REVIEW

**Comment by liubin** [comment]
Consider adding `Virtualizationl.framework` to these parts:

https://github.com/kata-containers/kata-containers/blob/cb7f9524be3247ca08cdbbce0ada2d493afcc7ef/src/runtime/virtcontainers/hypervisor_linux.go#L28-L47

https://github.com/kata-containers/kata-containers/blob/f1381eb361aa2202d48607df8cfc6dbfe6db580c/src/runtime/virtcontainers/hypervisor.go#L163-L204

This will also ensure `virtFramework` implement the hypervisor interface.

**Comment by liubin** [comment]
Oh, I saw https://github.com/kata-containers/kata-containers/pull/5996

**Review by liubin — APPROVED** [review]

**Comment by dcantah** [comment]
@liubin Yea, trying to split this up as much as possible (where it makes sense). Think it'll be easier to land and review

**Comment by dcantah** [comment]
CI fails seem like network issues. Also /cc @egernst @mxpv

**Comment by liubin** [comment]
> CI fails seem like network issues. Also /cc @egernst @mxpv

Seems network error, don't worry, I'll restart them:

> E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/r/rdma-core/librdmacm1_28.0-1ubuntu1_amd64.deb  503  Service Unavailable [IP: 52.252.75.106 80]

**Comment by egernst** [comment]
(restarted metrics, vfio test)

**Pull request merged**
