### PR TITLE
runtime: Support for host cgroupv2

### PR DESCRIPTION
**Pull request by yaoyinnan**
Added support for cgroups v2 to Kata Containers so that Kata Containers will work on systems that only support cgroups v2.

Fixes: #3073

Signed-off-by: yaoyinnan <yaoyinnan@foxmail.com>

### CODE REVIEW

**Comment by snir911** [comment]
Nice! Thanks! were you able to run CI jobs [locally](https://github.com/kata-containers/tests/tree/main/.ci#running-the-ci-locally) (or [locally](https://github.com/kata-containers/tests#using-vagrant-to-test-your-code-changes), both requires some modifications)?
Also please update the [host-cgroups docs](https://github.com/kata-containers/kata-containers/blob/main/docs/design/host-cgroups.md) (maybe it appears in other docs as well, i didn't check).

/test
(I suppose this should be followed by some new CI jobs that uses cgruoupsv2 host at some point, but meanwhile let's see how it goes with current jobs ;) )

**Comment by yaoyinnan** [comment]
@snir911 OK I will revise the CI tests and docs later.

**Comment by yaoyinnan** [comment]
Currently the `Manager` of `containerd/cgroups` lacks the `MoveTo` method, I need to wait for the PR (https://github.com/containerd/cgroups/pull/235) to be merged before I can update the mod.

**Comment by liyimeng** [comment]
@yaoyinnan Thanks for the great work, is it finally ready?

**Review by bergwolf — APPROVED** [review]
lgtm! @yaoyinnan Please rebase your PR, thanks!

**Comment by bergwolf** [comment]
There are a few left-overs though:
1. @yaoyinnan Please update docs about the change, like in docs/install/container-manager/containerd/containerd-install.md and docs/design/host-cgroups.md
2. Let's switch one of the exiting CI jobs to run cgroups v2 host instead. @GabyCT Is it doable? Or do you prefer to add a new job for cgroupsv2?

**Comment by fidencio** [comment]
This is a very nice work, indeed!
I do believe we should add a new CI job for cgroupsv2.

**Comment by yaoyinnan** [comment]
@liyimeng Not ready yet, still need to add a new CI job, I will do it soon.

@fidencio Yes, I will add a new CI job later.

**Comment by fidencio** [comment]
> @liyimeng Not ready yet, still need to add a new CI job, I will do it soon.
> 
> @fidencio Yes, I will add a new CI job later.

Gaby has already a CI setup using Ubuntu 22.04, which comes with cgroupsv2 by default.
She'll make her PR depend on this one, so we should be good to go in that front.

**Comment by fidencio** [comment]
Reference: https://github.com/kata-containers/tests/pull/4902

**Comment by GabyCT** [comment]
@bergwolf and @yaoyinnan, we have a CI job that has cgroupsv2 which is Ubuntu 22.04, to trigger that CI, we just need to do /test-ubuntu22

**Comment by GabyCT** [comment]
I put a Depends-On on my PR (which is adding or changing packages) that will change the setup of Ubuntu to test this PR

**Comment by GabyCT** [comment]
Some of the tests are failing but most of them are passing

**Comment by GabyCT** [comment]
The job using cgroupsv2 is now passing see https://github.com/kata-containers/tests/pull/4902
However, these are the set of tests that are failing with cgroupsv2:
- Stability test with sandbox cgroup only enabled
- Tracing tests
- Vcpus and KSM integration tests
- Nydus tests
- Kata monitor tests
/cc @bergwolf @yaoyinnan @fidencio @amshinde @cmaf @liubin @fgiudici 

The error that I can see in some tests 
```
time="2022-07-04T16:42:03.992022077Z" level=error msg="Module is not loaded and it can not be inserted. Please consider running with sudo or as root" arch=amd64 command=kata-env module=vhost_net name=kata-runtime pid=45306 source=runtime
time="2022-07-04T16:42:03.992061477Z" level=error msg="kernel property vhost_net not found" arch=amd64 command=kata-env description="Host kernel accelerator for virtio network" name=vhost_net pid=45306 source=runtime type=module
time="2022-07-04T16:42:40.44216645Z" level=error msg="Create new sandbox failed" error="Could not create the sandbox resource controller cgroups: cgroup mountpoint does not exist" name=containerd-shim-v2 pid=48544 sandbox=kata-4rQGGg source=virtcontainers subsystem=sandbox
time="2022-07-11T18:28:18.935111491Z" level=info msg="failed to get OOM event from sandbox" error="rpc error: code = Internal desc = \"\"" name=containerd-shim-v2 pid=83896 sandbox=da987dedcf15dbf8900ebd5383604f400333a5277ea4a2c0d92089f6455b875e source=containerd-kata-shim-v2
time="2022-07-11T18:28:18.936167306Z" level=error msg="failed to cleanup the &{%!s(*v2.Manager=&{/sys/fs/cgroup /sys/fs/cgroup/vc/kubepods/besteffort/pod6ed531dc-5007-431b-becc-8dbaf7f1e664/kata_da987dedcf15dbf8900ebd5383604f400333a5277ea4a2c0d92089f6455b875e}) /vc/kubepods/besteffort/pod6ed531dc-5007-431b-becc-8dbaf7f1e664/kata_da987dedcf15dbf8900ebd5383604f400333a5277ea4a2c0d92089f6455b875e %!s(*specs.LinuxCPU=&{<nil> <nil> <nil> <nil> <nil>  }) [{%!s(bool=false)  %!s(*int64=<nil>) %!s(*int64=<nil>) rwm} {%!s(bool=true) c %!s(*int64=0xc00020f860) %!s(*int64=0xc00020f868) rwm} {%!s(bool=true) c %!s(*int64=0xc00020f870) %!s(*int64=0xc00020f878) rwm} {%!s(bool=true) c %!s(*int64=0xc0004828a8) %!s(*int64=0xc0004828b0) rwm} {%!s(bool=true) c %!s(*int64=0xc0004828d8) %!s(*int64=0xc0004828e0) rwm} {%!s(bool=true) c %!s(*int64=0xc000482908) %!s(*int64=0xc000482910) rwm} {%!s(bool=true) c %!s(*int64=0xc000482968) %!s(*int64=0xc000482970) rwm} {%!s(bool=true) c %!s(*int64=0xc000482998) %!s(*int64=0xc0004829a0) rwm} {%!s(bool=true) c %!s(*int64=0xc0004829c8) %!s(*int64=0xc0004829d0) rwm} {%!s(bool=true) c %!s(*int64=0xc0004829f8) %!s(*int64=0xc000482a00) rwm} {%!s(bool=true) c %!s(*int64=0xc000482a28) %!s(*int64=0xc000482a30) rwm} {%!s(bool=true) c %!s(*int64=0xc000482a58) %!s(*int64=0xc000482a60) rwm} {%!s(bool=true) c %!s(*int64=0xc000482ab8) %!s(*int64=0xc000482ac0) rwm} {%!s(bool=true) c %!s(*int64=0xc000482ae8) %!s(*int64=0xc000482af0) rwm} {%!s(bool=true) c %!s(*int64=0xc00020f938) %!s(*int64=0xc00020f940) m} {%!s(bool=true) b %!s(*int64=0xc00020f938) %!s(*int64=0xc00020f940) m} {%!s(bool=true) c %!s(*int64=0xc00020f948) %!s(*int64=0xc00020f940) rwm} {%!s(bool=true) c %!s(*int64=0xc00020f950) %!s(*int64=0xc00020f958) rwm}] {%!s(int32=0) %!s(uint32=0)}} resource controllers" error="write /sys/fs/cgroup/vc/kubepods/besteffort/pod6ed531dc-5007-431b-becc-8dbaf7f1e664/cgroup.procs: device or resource busy" name=containerd-shim-v2 pid=83896 sandbox=da987dedcf15dbf8900ebd5383604f400333a5277ea4a2c0d92089f6455b875e source=virtcontainers subsystem=sandbox
time="2022-07-11T18:28:19.04695555Z" level=info msg="scanner return error: read unix @->/run/vc/vm/e6de40d6563e99b1f6c5d1ee4a1cfa9a6e457bc870ea649825ecfa17083e8d2e/qmp.sock: use of closed network connection" name=containerd-shim-v2 pid=84259 sandbox=e6de40d6563e99b1f6c5d1ee4a1cfa9a6e457bc870ea649825ecfa17083e8d2e source=virtcontainers/hypervisor subsystem=qmp
time="2022-07-11T18:28:19.060835656Z" level=info msg="scanner return error: read unix @->/run/vc/vm/af1ebe4868dcbfbbaed88ca4b4c6582b43ff66be874b9d25340c52f3bc67911f/qmp.sock: use of closed network connection" name=containerd-shim-v2 pid=84262 sandbox=af1ebe4868dcbfbbaed88ca4b4c6582b43ff66be874b9d25340c52f3bc67911f source=virtcontainers/hypervisor subsystem=qmp
time="2022-07-11T18:28:21.623425766Z" level=info msg="scanner return error: read unix @->/run/vc/vm/062f659ec79596aadd0ddebcb19fb27e19ae92127a181f1509a99e42205b2ad4/qmp.sock: use of closed network connection" name=containerd-shim-v2 pid=84545 sandbox=062f659ec79596aadd0ddebcb19fb27e19ae92127a181f1509a99e42205b2ad4 source=virtcontainers/hypervisor subsystem=qmp
time="2022-07-11T18:28:24.340253864Z" level=info msg="watchSandbox gets an error or stop signal" error="<nil>" name=containerd-shim-v2 pid=84262 sandbox=af1ebe4868dcbfbbaed88ca4b4c6582b43ff66be874b9d25340c52f3bc67911f source=containerd-kata-shim-v2
time="2022-07-11T18:28:24.351059824Z" level=info msg="failed to get OOM event from sandbox" error="rpc error: code = Internal desc = \"\"" name=containerd-shim-v2 pid=84262 sandbox=af1ebe4868dcbfbbaed88ca4b4c6582b43ff66be874b9d25340c52f3bc67911f source=containerd-kata-shim-v2
time="2022-07-11T18:28:24.353773264Z" level=error msg="failed to cleanup the &{%!s(*v2.Manager=&{/sys/fs/cgroup /sys/fs/cgroup/vc/kubepods/besteffort/pod6352b079-d31b-4a28-ab33-fe7e680c0c52/kata_af1ebe4868dcbfbbaed88ca4b4c6582b43ff66be874b9d25340c52f3bc67911f}) /vc/kubepods/besteffort/pod6352b079-d31b-4a28-ab33-fe7e680c0c52/kata_af1ebe4868dcbfbbaed88ca4b4c6582b43ff66be874b9d25340c52f3bc67911f %!s(*specs.LinuxCPU=&{<nil> <nil> <nil> <nil> <nil>  }) [{%!s(bool=false)  %!s(*int64=<nil>) %!s(*int64=<nil>) rwm} {%!s(bool=true) c %!s(*int64=0xc00012c160) %!s(*int64=0xc00012c168) rwm} {%!s(bool=true) c %!s(*int64=0xc00012c190) %!s(*int64=0xc00012c198) rwm} {%!s(bool=true) c %!s(*int64=0xc0005aecf8) %!s(*int64=0xc0005aed00) rwm} {%!s(bool=true) c %!s(*int64=0xc0005aed28) %!s(*int64=0xc0005aed30) rwm} {%!s(bool=true) c %!s(*int64=0xc0005aed58) %!s(*int64=0xc0005aed60) rwm} {%!s(bool=true) c %!s(*int64=0xc0005aed88) %!s(*int64=0xc0005aed90) rwm} {%!s(bool=true) c %!s(*int64=0xc0005aedb8) %!s(*int64=0xc0005aedc0) rwm} {%!s(bool=true) c %!s(*int64=0xc0005aede8) %!s(*int64=0xc0005aedf0) rwm} {%!s(bool=true) c %!s(*int64=0xc0005aee18) %!s(*int64=0xc0005aee20) rwm} {%!s(bool=true) c %!s(*int64=0xc0005aee48) %!s(*int64=0xc0005aee50) rwm} {%!s(bool=true) c %!s(*int64=0xc0005aee78) %!s(*int64=0xc0005aee80) rwm} {%!s(bool=true) c %!s(*int64=0xc0005aeea8) %!s(*int64=0xc0005aeeb0) rwm} {%!s(bool=true) c %!s(*int64=0xc0005aeed8) %!s(*int64=0xc0005aeee0) rwm} {%!s(bool=true) c %!s(*int64=0xc00012c358) %!s(*int64=0xc00012c370) m} {%!s(bool=true) b %!s(*int64=0xc00012c358) %!s(*int64=0xc00012c370) m} {%!s(bool=true) c %!s(*int64=0xc00012c378) %!s(*int64=0xc00012c370) rwm} {%!s(bool=true) c %!s(*int64=0xc00012c3a0) %!s(*int64=0xc00012c3a8) rwm}] {%!s(int32=0) %!s(uint32=0)}} resource controllers" error="write /sys/fs/cgroup/vc/kubepods/besteffort/pod6352b079-d31b-4a28-ab33-fe7e680c0c52/cgroup.procs: device or resource busy" name=containerd-shim-v2 pid=84262 sandbox=af1ebe4868dcbfbbaed88ca4b4c6582b43ff66be874b9d25340c52f3bc67911f source=virtcontainers subsystem=sandbox
time="2022-07-11T18:28:24.384832325Z" level=info msg="watchSandbox gets an error or stop signal" error="<nil>" name=containerd-shim-v2 pid=84259 sandbox=e6de40d6563e99b1f6c5d1ee4a1cfa9a6e457bc870ea649825ecfa17083e8d2e source=containerd-kata-shim-v2
time="2022-07-11T18:28:24.390428108Z" level=info msg="failed to get OOM event from sandbox" error="rpc error: code = Internal desc = \"\"" name=containerd-shim-v2 pid=84259 sandbox=e6de40d6563e99b1f6c5d1ee4a1cfa9a6e457bc870ea649825ecfa17083e8d2e source=containerd-kata-shim-v2
time="2022-07-11T18:28:24.392649541Z" level=error msg="failed to cleanup the &{%!s(*v2.Manager=&{/sys/fs/cgroup /sys/fs/cgroup/vc/kubepods/besteffort/pod1ad6fd35-064f-4881-94bf-d1a0f8868872/kata_e6de40d6563e99b1f6c5d1ee4a1cfa9a6e457bc870ea649825ecfa17083e8d2e}) /vc/kubepods/besteffort/pod1ad6fd35-064f-4881-94bf-d1a0f8868872/kata_e6de40d6563e99b1f6c5d1ee4a1cfa9a6e457bc870ea649825ecfa17083e8d2e %!s(*specs.LinuxCPU=&{<nil> <nil> <nil> <nil> <nil>  }) [{%!s(bool=false)  %!s(*int64=<nil>) %!s(*int64=<nil>) rwm} {%!s(bool=true) c %!s(*int64=0xc000211fc0) %!s(*int64=0xc000211fc8) rwm} {%!s(bool=true) c %!s(*int64=0xc000211ff0) %!s(*int64=0xc000211ff8) rwm} {%!s(bool=true) c %!s(*int64=0xc000413898) %!s(*int64=0xc0004138a0) rwm} {%!s(bool=true) c %!s(*int64=0xc0004138c8) %!s(*int64=0xc0004138d0) rwm} {%!s(bool=true) c %!s(*int64=0xc000413928) %!s(*int64=0xc000413930) rwm} {%!s(bool=true) c %!s(*int64=0xc000413958) %!s(*int64=0xc000413960) rwm} {%!s(bool=true) c %!s(*int64=0xc000413988) %!s(*int64=0xc000413990) rwm} {%!s(bool=true) c %!s(*int64=0xc0004139b8) %!s(*int64=0xc0004139c0) rwm} {%!s(bool=true) c %!s(*int64=0xc0004139e8) %!s(*int64=0xc0004139f0) rwm} {%!s(bool=true) c %!s(*int64=0xc000413a18) %!s(*int64=0xc000413a20) rwm} {%!s(bool=true) c %!s(*int64=0xc000413a48) %!s(*int64=0xc000413a50) rwm} {%!s(bool=true) c %!s(*int64=0xc000413a78) %!s(*int64=0xc000413a80) rwm} {%!s(bool=true) c %!s(*int64=0xc000413aa8) %!s(*int64=0xc000413ab0) rwm} {%!s(bool=true) c %!s(*int64=0xc0002dc1e8) %!s(*int64=0xc0002dc1f0) m} {%!s(bool=true) b %!s(*int64=0xc0002dc1e8) %!s(*int64=0xc0002dc1f0) m} {%!s(bool=true) c %!s(*int64=0xc0002dc1f8) %!s(*int64=0xc0002dc1f0) rwm} {%!s(bool=true) c %!s(*int64=0xc0002dc200) %!s(*int64=0xc0002dc208) rwm}] {%!s(int32=0) %!s(uint32=0)}} resource controllers" error="write /sys/fs/cgroup/vc/kubepods/besteffort/pod1ad6fd35-064f-4881-94bf-d1a0f8868872/cgroup.procs: device or resource busy" name=containerd-shim-v2 pid=84259 sandbox=e6de40d6563e99b1f6c5d1ee4a1cfa9a6e457bc870ea649825ecfa17083e8d2e source=virtcontainers subsystem=sandbox
time="2022-07-11T18:28:25.790501275Z" level=info msg="scanner return error: read unix @->/run/vc/vm/385dfa42d003e6f55e91021c1c4291a53461142011623181254cbe7886cff41f/qmp.sock: use of closed network connection" name=containerd-shim-v2 pid=85043 sandbox=385dfa42d003e6f55e91021c1c4291a53461142011623181254cbe7886cff41f source=virtcontainers/hypervisor subsystem=qmp
time="2022-07-11T18:28:25.963250837Z" level=info msg="watchSandbox gets an error or stop signal" error="<nil>" name=containerd-shim-v2 pid=84545 sandbox=062f659ec79596aadd0ddebcb19fb27e19ae92127a181f1509a99e42205b2ad4 source=containerd-kata-shim-v2
```

For more details you can see that in the jenkins job

**Review by GabyCT — APPROVED** [review]

**Comment by yaoyinnan** [comment]
@GabyCT Thanks a lot for your help. I will fix and test these failed test sets.

**Comment by fgiudici** [comment]
Nice PR! Seems the tests are all passing now :-)

**Comment by yaoyinnan** [comment]
> > Thank your @yaoyinnan @GabyCT
> > Since it works with basic functions, I'd like to get this one to be merged and fix the test issues in some coming PRs. WDYT? @bergwolf @fidencio @amshinde @cmaf @fgiudici
> 
> adding wip until agreed
> 
> BTW @yaoyinnan do you know it would work also with systemd cgroups driver?

@snir911 Due to the problem that containerd/cgroups described in https://github.com/kata-containers/kata-containers/issues/2868#issuecomment-953997436 does not support systemd cgroups driver well, I still use it when supporting cgroup v2 The processing scheme for systemd cgroups driver in https://github.com/kata-containers/kata-containers/issues/2963, that is, currently systemd cgroup is supported only when sandbox_cgroup_only=true.

After my discussion with @liubin, I plan to address the issue of systemd support when sandbox_cgroup_only=false in future PRs, and fix the issue mentioned in https://github.com/kata-containers/tests/issues/4922.

**Comment by fidencio** [comment]
@yaoyinnan, can we remove the "wip" label and have this one merged?

**Pull request merged**
