### PR TITLE
qemu: Upgrade qemu to 9.1.0

### PR DESCRIPTION
**Pull request by amshinde**
New features added in the major release have been disabled for now.
Deprecated features related to live-block-migration and avx512f have been removed.
Plan is to test the newly added features for performance and add them as
required in the future.

The major release includes quite a few bug fixes and improvments related
to storage and memory:

Block improvements:
- The block layer is now thread safe and multiple I/O threads can send I/O
requests to the same disk image. virtio-blk can be configured to make use
of this and improve scalability
- Fixed I/O errors in the libblkio based block drivers caused by incorrect
memory alignment of bounce buffers
- In 'blklogwrites', potential log corruption bugs were fixed related to
concurrent requests and to write zeroes operations

Memory improments:
- Memory backends specified on the QEMU commandline can now be preallocated
concurrently/asynchronously in some configurations, to speedup QEMU startup
with preallocation on multiple memory backends: one requirement is that memory
backends that are getting preallocated have a "thread-context" set.
- QEMU 8.2 accidentally allowed for creation of memory backends with sizes that
are not aligned to the (huge) page size. This has been fixed.

### CODE REVIEW

**Comment by fidencio** [comment]
@amshinde, what's the motivation to do that? Just a new release? Or are the features you depend on?
The commit message doesn't have any information on those.

**Comment by amshinde** [comment]
@fidencio I am not making use of the features introduced right away, but plan to test them out in the future. 
In general it is always recommended to move to the latest release to include any fixes partcularly around security included in the new release. We used to diligently do this before, but have fallen back on this.

This release contains a lots of bug fixes around block that I think will be useful to have including the addition of multi-queue support handled by multiple threads for virtio-blk. Will be useful to assess this improvement in kata in the future.
Block specific improvements:
- The block layer is now thread safe and multiple I/O threads can send I/O requests to the same disk image. virtio-blk can be configured to make use of this and improve scalability
- Fixed I/O errors in the libblkio based block drivers caused by incorrect memory alignment of bounce buffers
- In 'blklogwrites', potential log corruption bugs were fixed related to concurrent requests and to write zeroes operations


Memory improments include:
Memory backends specified on the QEMU commandline can now be preallocated concurrently/asynchronously in some configurations, to speedup QEMU startup with preallocation on multiple memory backends: one requirement is that memory backends that are getting preallocated have a "thread-context" set.
QEMU 8.2 accidentally allowed for creation of memory backends with sizes that are not aligned to the (huge) page size. This has been fixed.

In addition in 9.1.0, there was support added for Intel QPL (Query Processing Library) that makes use of accelerator present on certain Intel platforms. For now this is disabled, but I do want to test this feature out for specific workloads in the future to to measure perf improvements after enabling this feature.

**Comment by fidencio** [comment]
@amshinde, makes sense.  Please, reflect that into the commit message.

**Comment by amshinde** [comment]
@fidencio I have updated the commit message accordingly. Please take a look.

**Comment by amshinde** [comment]
Build was failing due to missing dependency tomli. I addressed this in the second commit by installing this with pip as the distribution package is available only on 22.04.

However, the buidl is now failing at a later point with :+1: 
```
Run-time dependency glib-2.0 found: NO 
../meson.build:926:10: ERROR: Dependency lookup for glib-2.0 with method 'pkgconfig' failed: Invalid version, need 'glib-2.0' ['>=2.66.0'] found '2.64.6'.
A full log can be found at /qemu/build/meson-logs/meson-log.txt
ERROR: meson setup failed
```

Ubuntu 20.04 has glib version 2.64.6. See https://launchpad.net/ubuntu/focal/+source/glib2.0
But qemu 9.0 has glib dependency of  >=2.66.0.
So at this point if we continue to use Ubuntu 20.04 as the base image for qemu 9.0, the builds will fail.
We can solve this by moving to 22.04. 
@fidencio @gkurz and others, do you see any objection to this to upgrading at this point?

**Comment by amshinde** [comment]
I just checked with 9.0.0 tag instead of 9.1.0 tag of qemu and the configure seems to be passing there, which means the dependency was added for 9.1.0. We could upgrade to 9.0.0 for now but have to address this at some point.

**Comment by fidencio** [comment]
> @fidencio @gkurz and others, do you see any objection to this to upgrading at this point?

No objection on bumping the dep to 22.04, at all.  And I'd stick to 9.1.0, @amshinde.
Thanks for taking care of this one.

**Comment by zvonkok** [comment]
Background for me is the support for iommufd which is a new VFIO implementation in the kernel. Intel TDX with pass-through and AMD needs that for CoCo. If our baseline with Kata already supports this we will have better support with CoCo.

**Comment by fidencio** [comment]
This is an interesting one. :-)

There is a linking issue that @amshinde hit, which can be fixed by disabling `gio` on the QEMU side.  However, this is not the main problem.  https://bugs.launchpad.net/ubuntu/+source/pmdk/+bug/1982425 is.

We'd need to statically build libpmem ourselves, as we're doing right now with liburing (which then won't be needed anymore, as the version on Ubuntu 22.04 is good enough).


I won't take this over, but I hope this helps @amshinde or @zvonkok to proceed with this PR.

**Comment by zvonkok** [comment]
For reference this is what we build currently:
```
qemu 8.2.4

  Build environment
    Build directory                              : /qemu/build
    Source path                                  : /qemu
    Download dependencies                        : YES

  Directories
    Build directory                              : /qemu/build
    Source path                                  : /qemu
    Download dependencies                        : YES
    Install prefix                               : /opt/kata
    BIOS directory                               : share/kata-qemu/qemu
    firmware path                                : share/qemu-firmware
    binary directory                             : /opt/kata/bin
    library directory                            : /opt/kata/lib/kata-qemu
    module directory                             : lib/kata-qemu/qemu
    libexec directory                            : /opt/kata/libexec/kata-qemu
    include directory                            : /opt/kata/include
    config directory                             : /opt/kata/etc
    local state directory                        : /opt/kata/var
    Manual directory                             : /opt/kata/share/man
    Doc directory                                : /opt/kata/share/doc

  Host binaries
    python                                       : /qemu/build/pyvenv/bin/python3 (version: 3.8)
    sphinx-build                                 : NO
    gdb                                          : 
    iasl                                         : NO
    genisoimage                                  : 

  Configurable features
    Documentation                                : NO
    system-mode emulation                        : YES
    user-mode emulation                          : NO
    block layer                                  : YES
    Install blobs                                : YES
    module support                               : NO
    fuzzing support                              : NO
    Audio drivers                                : oss
    Trace backends                               : log
    D-Bus display                                : YES
    QOM debugging                                : NO
    Relocatable install                          : NO
    vhost-kernel support                         : YES
    vhost-net support                            : YES
    vhost-user support                           : YES
    vhost-user-crypto support                    : YES
    vhost-user-blk server support                : YES
    vhost-vdpa support                           : YES
    build guest agent                            : NO

  Compilation
    host CPU                                     : x86_64
    host endianness                              : little
    C compiler                                   : cc -m64 -mcx16
    Host C compiler                              : cc -m64 -mcx16
    C++ compiler                                 : NO
    Objective-C compiler                         : NO
    CFLAGS                                       : -O2 -fno-semantic-interposition -falign-functions=32 -D_FORTIFY_SOURCE=2 -g -O2
    LDFLAGS                                      : -O2 -fno-semantic-interposition -falign-functions=32 -D_FORTIFY_SOURCE=2 -z noexecstack -z relro -z now
    QEMU_CFLAGS                                  : -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -fno-strict-aliasing -fno-common -fwrapv -fstack-protector-strong
    QEMU_LDFLAGS                                 : -static-pie -fstack-protector-strong -Wl,-z,relro -Wl,-z,now -Wl,--warn-common
    link-time optimization (LTO)                 : NO
    PIE                                          : YES
    static build                                 : YES
    malloc trim support                          : YES
    membarrier                                   : NO
    debug graph lock                             : NO
    debug stack usage                            : NO
    mutex debugging                              : NO
    memory allocator                             : system
    avx2 optimization                            : YES
    avx512bw optimization                        : NO
    avx512f optimization                         : YES
    gcov                                         : NO
    thread sanitizer                             : NO
    CFI support                                  : NO
    strip binaries                               : NO
    sparse                                       : NO
    mingw32 support                              : NO

  Cross compilers
    x86_64                                       : cc

  Targets and accelerators
    KVM support                                  : YES
    HVF support                                  : NO
    WHPX support                                 : NO
    NVMM support                                 : NO
    Xen support                                  : NO
    Xen emulation                                : YES
    TCG support                                  : NO
    target list                                  : x86_64-softmmu
    default devices                              : YES
    out of process emulation                     : YES
    vfio-user server                             : NO

  Block layer support
    coroutine backend                            : ucontext
    coroutine pool                               : YES
    Block whitelist (rw)                         : 
    Block whitelist (ro)                         : 
    Use block whitelist in tools                 : NO
    VirtFS (9P) support                          : YES
    VirtFS (9P) Proxy Helper support (deprecated): NO
    Live block migration                         : NO
    replication support                          : NO
    bochs support                                : NO
    cloop support                                : NO
    dmg support                                  : NO
    qcow v1 support                              : NO
    vdi support                                  : NO
    vhdx support                                 : NO
    vmdk support                                 : NO
    vpc support                                  : NO
    vvfat support                                : NO
    qed support                                  : NO
    parallels support                            : NO
    FUSE exports                                 : NO
    VDUSE block exports                          : YES

  Crypto
    TLS priority                                 : NORMAL
    GNUTLS support                               : NO
    libgcrypt                                    : NO
    nettle                                       : NO
    AF_ALG support                               : NO
    rng-none                                     : NO
    Linux keyring                                : YES
    Linux keyutils                               : NO

  User interface
    SDL support                                  : NO
    SDL image support                            : NO
    GTK support                                  : NO
    pixman                                       : NO
    VTE support                                  : NO
    PNG support                                  : NO
    VNC support                                  : NO
    spice protocol support                       : NO
    curses support                               : NO
    brlapi support                               : NO

  Audio backends
    OSS support                                  : YES
    sndio support                                : NO
    ALSA support                                 : NO
    PulseAudio support                           : NO
    PipeWire support                             : NO
    JACK support                                 : NO

  Network backends
    AF_XDP support                               : NO
    slirp support                                : NO
    vde support                                  : NO
    netmap support                               : NO
    l2tpv3 support                               : YES

  Dependencies
    libtasn1                                     : NO
    PAM                                          : NO
    iconv support                                : NO
    virgl support                                : NO
    rutabaga support                             : NO
    blkio support                                : NO
    curl support                                 : NO
    Multipath support                            : NO
    Linux AIO support                            : YES
    Linux io_uring support                       : YES 2.0
    ATTR/XATTR support                           : YES
    RDMA support                                 : NO
    PVRDMA support                               : NO
    fdt support                                  : internal
    libcap-ng support                            : YES
    bpf support                                  : NO
    rbd support                                  : NO
    smartcard support                            : NO
    U2F support                                  : NO
    libusb                                       : NO
    usb net redir                                : NO
    OpenGL support (epoxy)                       : NO
    GBM                                          : NO
    libiscsi support                             : NO
    libnfs support                               : NO
    seccomp support                              : YES 2.5.1
    GlusterFS support                            : NO
    hv-balloon support                           : NO
    TPM support                                  : YES
    libssh support                               : NO
    lzo support                                  : NO
    snappy support                               : NO
    bzip2 support                                : NO
    lzfse support                                : NO
    zstd support                                 : NO
    NUMA host support                            : NO
    capstone                                     : NO
    libpmem support                              : YES 1.8
    libdaxctl support                            : NO
    libudev                                      : NO
    FUSE lseek                                   : NO
    selinux                                      : YES 3.0
    libdw                                        : NO

  Subprojects
    dtc                                          : YES
    keycodemapdb                                 : YES
    libvduse                                     : YES
    libvhost-user                                : YES

  User defined options
    Native files                                 : config-meson.cross
    datadir                                      : /opt/kata/share/kata-qemu
    libdir                                       : /opt/kata/lib/kata-qemu
    libexecdir                                   : /opt/kata/libexec/kata-qemu
    prefer_static                                : true
    prefix                                       : /opt/kata
    attr                                         : enabled
    auth_pam                                     : disabled
    avx2                                         : enabled
    avx512bw                                     : disabled
    avx512f                                      : enabled
    bochs                                        : disabled
    brlapi                                       : disabled
    bzip2                                        : disabled
    cap_ng                                       : enabled
    capstone                                     : disabled
    cloop                                        : disabled
    colo_proxy                                   : disabled
    curl                                         : disabled
    curses                                       : disabled
    debug_graph_lock                             : false
    debug_tcg                                    : false
    dmg                                          : disabled
    docs                                         : disabled
    glusterfs                                    : disabled
    gtk                                          : disabled
    guest_agent                                  : disabled
    guest_agent_msi                              : disabled
    hexagon_idef_parser                          : false
    hv_balloon                                   : disabled
    kvm                                          : enabled
    libdw                                        : disabled
    libiscsi                                     : disabled
    libnfs                                       : disabled
    libpmem                                      : enabled
    libssh                                       : disabled
    libudev                                      : disabled
    libusb                                       : disabled
    linux_aio                                    : enabled
    live_block_migration                         : disabled
    lzo                                          : disabled
    malloc_trim                                  : enabled
    nettle                                       : disabled
    opengl                                       : disabled
    parallels                                    : disabled
    pipewire                                     : disabled
    pixman                                       : disabled
    pkgversion                                   : kata-static
    png                                          : disabled
    qcow1                                        : disabled
    qed                                          : disabled
    qom_cast_debug                               : false
    rdma                                         : disabled
    relocatable                                  : false
    replication                                  : disabled
    rutabaga_gfx                                 : disabled
    sdl                                          : disabled
    seccomp                                      : enabled
    slirp                                        : disabled
    smartcard                                    : disabled
    snappy                                       : disabled
    sparse                                       : disabled
    spice                                        : disabled
    tcg                                          : disabled
    tcg_interpreter                              : false
    tools                                        : disabled
    usb_redir                                    : disabled
    vde                                          : disabled
    vdi                                          : disabled
    vhdx                                         : disabled
    vhost_net                                    : enabled
    virglrenderer                                : disabled
    virtfs                                       : enabled
    vmdk                                         : disabled
    vnc                                          : disabled
    vnc_jpeg                                     : disabled
    vnc_sasl                                     : disabled
    vpc                                          : disabled
    vte                                          : disabled
    vvfat                                        : disabled
    xen                                          : disabled
```

**Comment by zvonkok** [comment]
Based on that we need to disable more features that are enabled in 9.1.1

**Comment by fidencio** [comment]
> Based on that we need to disable more features that are enabled in 9.1.1

Yeah, and I'd rather take the approach taken by Red Hat on this one.
Disable everything, literally everything, and then just come back enabling the bare minimum needed.
cc @gkurz

**Pull request closed without merging**
