### PR TITLE
Kbs deploy overlays update

### PR DESCRIPTION
**Pull request by stevenhorsman**
In https://github.com/confidential-containers/trustee/pull/521
the overlays logic was modified to add sample
s390x support and simplify non-ibm-se platforms.
We need to update the logic in `kbs_k8s_deploy`
to match and can remove the dummying of `IBM_SE_CREDS_DIR`
for non-SE flows now.

Signed-off-by: stevenhorsman <steven@uk.ibm.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @stevenhorsman!

**Comment by fidencio** [comment]
At least one of the failing tests is related to https://github.com/kata-containers/kata-containers/issues/10403

**Comment by stevenhorsman** [comment]
@BbolroC has found a bug in the trustee code, so this is on hold until we've fixed it.

**Comment by stevenhorsman** [comment]
Updated to the new version, ready for @BbolroC to re-check :)

**Comment by BbolroC** [comment]
> Updated to the new version, ready for @BbolroC to re-check :)

Here is a test result:

```
::group::Deploy the KBS
ibm-se overlay being used as IBM_SE_CREDS_DIR was set
persistentvolume/test-local-pv created
namespace/coco-tenant created
configmap/kbs-config-68g582hg7m created
configmap/policy-config-55tfg2kc22 created
secret/kbs-auth-public-key-9m4588mf7b created
secret/keys-gmf2g75547 created
service/kbs created
persistentvolumeclaim/test-local-pvc created
deployment.apps/kbs created
~/go/src/github.com/kata-containers/kata-containers
::endgroup::
::group::Check the service healthy
pod/kbs-checker-494161 created
pod "kbs-checker-494161" deleted
KBS service respond to requests
::endgroup::
::group::Check the kbs service is exposed
Trying to connect at http://172.23.236.42:30191. Timeout=350
KBS service respond to requests at http://172.23.236.42:30191
::endgroup::
~/go/src/github.com/kata-containers ~/se-e2e
~/se-e2e
$ echo $?
0
$ kubectl get all -n coco-tenant
NAME                       READY   STATUS    RESTARTS   AGE
pod/kbs-5d7df7c8fc-t95wr   1/1     Running   0          3m30s

NAME          TYPE       CLUSTER-IP    EXTERNAL-IP   PORT(S)          AGE
service/kbs   NodePort   10.43.53.98   <none>        8080:30191/TCP   3m34s

NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/kbs   1/1     1            1           3m31s

NAME                             DESIRED   CURRENT   READY   AGE
replicaset.apps/kbs-5d7df7c8fc   1         1         1       3m30s
```

Looks great! Thanks!

**Review by BbolroC — APPROVED** [review]
LGTM thanks @stevenhorsman ! It should have been done by me. I appreciate your work. ❤️

**Pull request merged**
