### PR TITLE
virtcontainers: Improved test coverage for fc.go from 4.6% to 18.5%

### PR DESCRIPTION
**Pull request by eberroca**
Expanded tests on fc_test.go to cover more lines of code. Coverage went from 4.6% to 18.5%.

Fixes: #266

### CODE REVIEW

**Review by amshinde — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Thanks @eberroca.

lgtm

**Comment by amshinde** [comment]
@eberroca The static checks are failing: https://github.com/kata-containers/kata-containers/actions/runs/4835386235/jobs/8617636942?pr=6763

```
Error: fc_test.go:202:2: S1021: should merge variable declaration with assignment on next line (gosimple)
	var initialMemSize uint32
	^
make: *** [Makefile:41: static-checks] Error 1
Error: Process completed with exit code 2.
```
Can you please fix this?

**Comment by eberroca** [comment]
> @eberroca The static checks are failing: https://github.com/kata-containers/kata-containers/actions/runs/4835386235/jobs/8617636942?pr=6763
> 
> ```
> Error: fc_test.go:202:2: S1021: should merge variable declaration with assignment on next line (gosimple)
> 	var initialMemSize uint32
> 	^
> make: *** [Makefile:41: static-checks] Error 1
> Error: Process completed with exit code 2.
> ```
> 
> Can you please fix this?

I will !

**Pull request merged**
