### PR TITLE
Update Kata to qemu 6.1

### PR DESCRIPTION
**Pull request by dgibson**
Qemu 6.1 adds ACPI hotplug support under bridges for `q35` which we really need to fix https://github.com/kata-containers/kata-containers/issues/2174.

For now, based on and supersedes https://github.com/kata-containers/kata-containers/pull/1958.

### CODE REVIEW

**Comment by dgibson** [comment]
@fidencio @marcel-apf, for your attention

**Comment by dgibson** [comment]
Amongst other things, to fix this we'll need a govmm update including https://github.com/kata-containers/govmm/pull/192

**Comment by dgibson** [comment]
Depends-on: https://github.com/kata-containers/tests/pull/3778

**Comment by devimc** [comment]
@dgibson `Depends-on: ...` should be part of a commit message

**Comment by marcel-apf** [comment]
@dgibson looks good to me, why does the title is "QEMU 6.1" but the patches are for QEMU 6.0?

**Comment by dgibson** [comment]
> @dgibson looks good to me, why does the title is "QEMU 6.1" but the patches are for QEMU 6.0?

Because I'm not finished yet, and I pased this on an earlier PR (not mine) which was just aiming for QEMU 6.0.  I'm still debugging the problems going to qemu 6.0, after that I'll move to 6.1.

**Comment by dgibson** [comment]
Ok, I've partially identified the next problem.  QEMU is complaining of a missing `size` parameter on an `object-add` of a `memory-backend-device`.  However... in this case Kata does appear to be giving a `size` parameter.

I've reproduced the problem in QEMU, and I'm looking into it.

**Comment by dgibson** [comment]
Ah.. found it.  govmm is putting the object properties in a `props` sub-object rather than at the top level of the `object-add` arguments.  Use of `props` was removed in qemu 6.0 (commit `50243407457a`) and deprecated in 5.0 (commit `5f07c4d60d09`).

**Comment by dgibson** [comment]
Closing.  Now that I've sorted out the problems this is obsoleted by #2382

**Pull request closed without merging**
