### PR TITLE
Fixes tests on AMD machines

### PR DESCRIPTION
**Pull request by beraldoleal**
Some tests are failing when running on AMD machines. I suspect GH CI is not running on amd and is not failing there. Vide individual commits for details.

### CODE REVIEW

**Review by wainersm — APPROVED** [review]
Good catch @beraldoleal ! LGTM!

**Review by jepio — APPROVED** [review]

**Comment by jepio** [comment]
The failing `run-metrics` test is being fixed here https://github.com/kata-containers/kata-containers/pull/7787.

**Comment by beraldoleal** [comment]
@jepio thank you. Can we run again only the failing tests?

**Comment by jepio** [comment]
No need in this case

**Pull request merged**
