### PR TITLE
stable-2.0 | cherry-pick fixes for test-kata-deploy GitHub actions

### PR DESCRIPTION
**Pull request by fidencio**
This series contains cherry-picks for the following issue:
#1634, #1640, #1645

### CODE REVIEW

**Comment by snir911** [comment]
@fidencio is this still wip?

**Comment by fidencio** [comment]
@snir911, nops, all the stable-2.x backport PRs can be reviewed and, hopefully, merged. :-)

**Review by snir911 — APPROVED** [review]

**Comment by fidencio** [comment]
https://github.com/kata-containers/kata-containers/pull/1659 fixes the travis-ci, so no need to block this one because of the travis-ci failures.

**Review by wainersm — APPROVED** [review]

**Pull request merged**
