### PR TITLE
CC | agent: Update the merge_oci_process function to change cwd

### PR DESCRIPTION
**Pull request by Jordan9500**
agent: Update the merge_oci_process function to change cwd

Change the if statement to check if the CWD is set to / Add unit tests for the correct merging of working directory in the container and image process

Note: there is an outstanding question about one test case

Fixes: #5721

Co-authored-by: stevenhorsman <steven@uk.ibm.com>
Signed-off-by: jordan9500 <jordan.jackson@ibm.com>

### CODE REVIEW

**Comment by BbolroC** [comment]
@stevenhorsman Please ignore the test result for s390x. Thanks.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @Jordan9500!

**Pull request merged**
