### PR TITLE
kata-monitor: fix can't monitor /run/vc/sbs

### PR DESCRIPTION
**Pull request by xujunjie-cover**
fix can't monitor /run/vc/sbs.

Fixes: #4685

### CODE REVIEW

**Review by liubin — APPROVED** [review]
Thank you @xujunjie-cover

**Comment by liubin** [comment]
@xujunjie-cover thank you for your PR.

But you need to fix your commit message by:

- add DCO
- add commit message body

You can read [this](https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format) for more info.

**Comment by liubin** [comment]
@xujunjie-cover Your signoff is invalid:

```
Signed-off-by: Junjie Xu [xu.junjie@99cloud.net](xu.junjie@99cloud.net)
```

You should add it by `git commit -s`: https://github.com/apps/dco

**Comment by xujunjie-cover** [comment]
> @xujunjie-cover Your signoff is invalid:
> 
> ```
> Signed-off-by: Junjie Xu [xu.junjie@99cloud.net](xu.junjie@99cloud.net)
> ```
> 
> You should add it by `git commit -s`: https://github.com/apps/dco

Done, Thanks, This is my first pr to kata. sorry to waste your precious time.

**Review by liubin — APPROVED** [review]

**Pull request merged**
