### PR TITLE
Release process related fixes

### PR DESCRIPTION
**Pull request by snir911**
update docs and script

### CODE REVIEW

**Review by egernst — DISMISSED** [review]
Good suggestions -- thanks for doing the release and for helping improve the process.

**Comment by egernst** [comment]
Something odd is going on with the kata-deploy-build workflow with your yq commit. Can you TAL? https://github.com/kata-containers/kata-containers/runs/5054022983?check_suite_focus=true#step:4:18

**Comment by egernst** [comment]
(restarted metrics, vfio CI)

**Review by sameo — APPROVED** [review]

**Review by egernst — APPROVED** [review]

**Pull request merged**
