### PR TITLE
fix arm CI

### PR DESCRIPTION
**Pull request by bergwolf**
ARM CI is passing now http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-ARM-PR/409/console

Depends-on: github.com/kata-containers/tests#2945

### CODE REVIEW

**Comment by jongwu** [comment]
Thanks a lot @bergwolf, I have noticed this qemu issue and seek remedy for it, thanks again. let it as a workaround and wait for qemu 5.2 to be released then upgrade qemu again.

**Comment by jongwu** [comment]
Thanks @bergwolf  - ARM CI return normal again! 👍

**Review by liubin — APPROVED** [review]

**Review by lifupan — APPROVED** [review]

**Pull request merged**
