### PR TITLE
agent: use method params instead of const params in functions

### PR DESCRIPTION
**Pull request by cheriL**
Fixes: #8325

### CODE REVIEW

**Review by amshinde — APPROVED** [review]

**Review by gkurz — APPROVED** [review]
LGTM. Thanks @cheriL !

**Comment by gkurz** [comment]
> LGTM. Thanks @cheriL !

@cheriL Note that there were some changes in CI that require you to rebase this PR and force-push.

**Comment by cheriL** [comment]
@gkurz Done

**Comment by gkurz** [comment]
I've rebased again to get some more CI fixes.

**Pull request merged**
