### PR TITLE
docs: Update travis and go report card url

### LINKED ISSUE #432: Update travis and go report card url
Fix travis and go report card url for the README

### PR DESCRIPTION
**Pull request by GabyCT**
This PR fixes travis and go report carl url for the runtime README for kata
2.0

Fixes #432

Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hmm - looks like the wip and sob checks have stalled (everywhere) @GabyCT.

**Comment by jodh-intel** [comment]
A retrigger isn't working and https://zuul.opendev.org/t/kata-containers/builds?pipeline=SoB-check shows that the Zuul checks stopped on 17 July!

@ttx - do you know who we can talk to about this? Looks like a Zuul service might need restarting maybe?

/cc @chavafg

**Comment by ttx** [comment]
I'll look into it -- it's running alright for all other tenants, so it's not just a restart situation :)

**Comment by jodh-intel** [comment]
Thanks @ttx!

**Comment by ttx** [comment]
Issue is actually a regression that affects the gitHub Zuul driver, fix being tested now.

**Comment by ttx** [comment]
To unblock this, config was updated to not require WIP/SOB checks anymore, but I think this will need a new push before GitHub realizes it.

**Comment by bergwolf** [comment]
Maybe you need to rebase to master to include DCO/WIP checks.

**Pull request merged**
