### PR TITLE
agent: simplify error handling

### PR DESCRIPTION
**Pull request by wedsonaf**
We extend the `Result` and `Option` types with associated types that allows converting a `Result<T, E>` and `Option<T>` into `ttrpc::Result<T>`.

This allows the elimination of many `match` statements in favor of calling the map function plus the `?` operator. This transformation simplifies the code.

Fixes: #7624

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @wedsonaf!

This is yet another nice cleanup!

**Review by jepio — APPROVED** [review]
lgtm

**Pull request merged**
