### PR TITLE
Tokio vulnerability bump

### PR DESCRIPTION
**Pull request by stevenhorsman**
Update tokio dependency in various crates to address the
high severity security vulnerability https://rustsec.org/advisories/RUSTSEC-2024-0019

### CODE REVIEW

**Review by zvonkok — APPROVED** [review]
LGTM thanks @stevenhorsman

**Review by danmihai1 — APPROVED** [review]
Thanks, Steve!

**Comment by wainersm** [comment]
Hi @stevenhorsman !

k8s-confidential-attestation.bats failed on TDX then I re-triggered the job; don't belive it's related with the bump but...let's give it a 2nd chance.

**Review by wainersm — APPROVED** [review]

**Review by Apokleos — APPROVED** [review]
Thx @stevenhorsman LGTM

**Pull request merged**
