### PR TITLE
arm64/CI: fix unit test failure on arm64

### PR DESCRIPTION
**Pull request by jongwu**
There are lots of unit test failure on arm64. fix or skip them to unblock the CI.

### CODE REVIEW

**Review by fengwang666 — COMMENTED** [review]
Just curious, why is there a dependency among different unit test cases?

**Comment by jongwu** [comment]
Hi @fengwang666 -, the key point of this issue lies that the tests run concurrently. For example, while test_add_remove  is running, test_drop_privs starts and changes the user to nobody but test_add_remove need "root" user then error may occur.

**Comment by bergwolf** [comment]
Is `kata-ctl` compilable at all? I'm getting this locally:
```
[neverland@kata-ctl]$cargo build
   Compiling kata-ctl v0.0.1 (/home/bergwolf/src/kata/kata-containers/src/tools/kata-ctl)
error[E0583]: file not found for module `version`
 --> src/ops.rs:7:1
  |
7 | pub mod version;
  | ^^^^^^^^^^^^^^^^
  |
  = help: to create the module `version`, create file "src/ops/version.rs" or "src/ops/version/mod.rs"

error[E0425]: cannot find function `get` in module `version`
   --> src/ops/check_ops.rs:128:28
    |
128 |     let version = version::get().unwrap();
    |                            ^^^ not found in `version`
    |
help: consider importing one of these items
    |
6   | use nix::sys::personality::get;
    |
6   | use reqwest::blocking::get;
    |
6   | use reqwest::get;
    |
help: if you import `get`, refer to it directly
    |
128 -     let version = version::get().unwrap();
128 +     let version = get().unwrap();
    |

Some errors have detailed explanations: E0425, E0583.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `kata-ctl` due to 2 previous errors
```

**Comment by jongwu** [comment]
Hi @bergwolf -, try make first and the version file may created?

**Review by GabyCT — APPROVED** [review]

**Review by dborquez — APPROVED** [review]

**Pull request merged**
