### PR TITLE
gha: add cri-containerd workflow for ppc64le

### PR DESCRIPTION
**Pull request by Amulyam24**
This PR adds workflow to run containerd tests on Power as a part of CI migration.

Fixes: #8500

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
Code LGTM. Thanks!

**Comment by stevenhorsman** [comment]
I don't think this workflow will be run on this PR, so if you can trigger it to run on your fork that would be interesting to see, if it's not too much issues with required secrets.

**Comment by Amulyam24** [comment]
> I don't think this workflow will be run on this PR, so if you can trigger it to run on your fork that would be interesting to see, if it's not too much issues with required secrets.

Sure, I'll test it and share the run.

One test is failing on containerd, added logic to skip it for now and shall fix it sooner than later :)

**Review by GabyCT — APPROVED** [review]

**Comment by Amulyam24** [comment]
@stevenhorsman @GabyCT, here is the sample run from my fork(ran it with some fixes for image repos), PTAL - https://github.com/Amulyam24/kata-containers/actions/runs/6979218191/job/18992653789?pr=6

**Comment by stevenhorsman** [comment]
Thanks, this is looking good, so I think it's ready to merge

**Comment by Amulyam24** [comment]
Hi @stevenhorsman, we have 2 approvals, can this PR be merged?

**Comment by stevenhorsman** [comment]
> Hi @stevenhorsman, we have 2 approvals, can this PR be merged?

Yes, I think once the required tests are passing we are good to go

**Comment by stevenhorsman** [comment]
@Amulyam24 - I think it's failing because of the dependency on the other PR. I'm not sure that that a same repo dependency makes sense at a commit level? If this PR needs to wait for that PR to be merged first then let's drop that message from the commit and add a do-not-merge label to this, otherwise we need to drop the message anyway

**Pull request merged**
