### PR TITLE
# Kata Containers 2.1.0-rc0

### PR DESCRIPTION
**Pull request by fidencio**
- Update kata-deploy to use CRI-O drop-in files
- Update dependencies versions
- fix build kernel shell error when setup with `-f`
- virtcontainers: Fix virtio-fs on s390x
- Runtimeclass updates
- versions: Upgrade to cloud-hypervisor v15.0
- clh: return error if apiSocketPath failed
- runtime: fix dropped error
- agent: Update seccomp configuration for errnoRet and flags
- Fix the issue that sandbox size is not right after update
- docs: Document limitation regarding subpaths
- qemu: kill virtiofsd if failure to start VMM
- runtime/virtcontainers: Fix typo on qmp error msg
- cli: delete not used files
- runtime: delete not used function parameter builtIn
- add io.katacontainers.config.hypervisor.virtio_fs_extra_args handling
- Entropy source annotation
- runtime: Fix stdout/stderr output from container being truncated
- fix the issue of missing set fsGroup for EphemeralStorage
- qemu: Fix assertion failure on shutdown
- Assorted clippy fixes for Rust agent
- agent: use channel instead of pipe(2) to send exit signal of process
- Improve agent shutdown handling
- Enable virtio-fs on s390x
- block: Generate PCI path for virtio-blk devices on clh
- runtime: Disable trace for healthcheck
- agent/rustjail: Fix accidental damage from tokio conversion
- cli: Use genericGetExpectedHostDetails on s390x
- runtime/tests: Change "moo FAILURE" message
- Update the information about the release process
- remove ProcessListContainer API

2047f26f kata-deploy: Adapt CRI-O config to use drop-in files
8de2f914 kata-deploy: Rely on CRIO default's values for manage_ns_lifecycle
ea9936e0 versions: Bump runc to v1.0.0-rc93
9c333b2c versions: Bump CRI-O version to 1.21.x
e33f207b versions: Bump critools version to 1.21.0
8e5df723 versions: Bump kubernetes version to 1.21.0
d15f84c9 versions: Remove Docker entry
516f4ec0 versions: Remove OpenShift entry
be101ac1 versions: Remove CRI-O meta dependencies
1ca6bedf versions: Upgrade to cloud-hypervisor v15.0
906c0df4 kata-deploy: don't update worker pool nodes
3ee61776 virtcontainers: Enable virtio-fs on s390x
8385ff95 runtime: Re-vendor GoVMM
adba4532 virtcontainers: Revert "virtcontainers: Allow s390x appendVhostUserDevice"
ede078bc kata-deploy: aks-test: bump kubernetes/containerd
484af12b kata-deploy: update to handle new runtimeclass path
05c224c3 runtimeclass: add nodeSelector
ee7de8ab tools: fix build kernel shell error
7d5a4252 docs: Document limitation regarding subpaths
36776408 runtime/virtcontainers: Fix typo on qmp error msg
12a65d23 runtimeclass: drop stale runtimeclass definitions
0787ea80 cgroupsCreate: not set resources to c.config.Resources
831224aa Sandbox: Fix ContainerConfig ptr in CreateContainer and createContainers
a57c8ab1 qemu: kill virtiofsd if failure to start VMM
ff2b9e54 cli: delete not used files
0d0a520d clh: return error if apiSocketPath failed
fc6bb01a runtime: fix dropped error
30ff6ee8 runtime: handle io.katacontainers.config.hypervisor.virtio_fs_extra_args
677f0d99 runtime: delete not used function parameter builtIn
dcb9f403 config: Protect annotation for entropy_source
f4c26aad agent: fix the issue of missing set fsGroup for EphemeralStorage
628d55bf kata-agent: fix the issue of fsGroup missing
0405beb2 agent: Remove unused Default implementation for NamespaceType
7b83b7ec agent/uevent: Better initialize Uevent in test
b0190a40 agent: Use vec![] macro rather than init-then-push
1c43245e agent/device: Remove unneeded Result<> wrappers from uev matchers
e41cdb8b agent: Use str::is_empty() method in config::get_string_value()
2377c097 agent: Use CamelCase for NamespaceType values
75eca6d5 agent/rustjail: Clean up error path in execute_hook()s async task
6ce1e56d agent/rustjail: Remove an unnecessary PathBuf
3c4485ec agent/rustjail: Clean up some static definitions with vec! macro
eaec5a6c agent/oci: Change name case to make clippy happy
3f5fdae0 agent/rustjail: (trivial) Clean up comment on process_grpc_to_oci()
210f39a4 agent/rustjail: Simplify renaming imports
d4a54137 runtime: Fix stdout/stderr output from container being truncated
8ecf8e5c agent: use channel instead of pipe to send exit signal of process
81c5ff12 agent: Update seccomp configuration for errnoRet and flags
8a33bd4c qemu: Fix assertion failure on shutdown
7f609113 virtcontainers: Allow s390x appendVhostUserDevice
67ac4f45 runtime: update GoVMM for memory backend support
6577b01a agent/rustjail: Fix accidental damage from tokio conversion
de2631e7 utils: Make WaitLocalProcess safer
9256e590 shutdown: Don't sever console watcher too early
51ab8700 utils: Improve WaitLocalProcess
507ef636 utils: Add waitLocalProcess function
1d5098de agent/block: Generate PCI path for virtio-blk devices on clh
e7c97f0f runtime/tests: Change "moo FAILURE" message
8bc53498 docs: Simplify the repo bumping section
8a47b05a docs: Mention that an app token should be used with hub
d434c2e9 docs: OBS account is not require anymore
543f9da3 runtime: Disable trace for healthcheck
421439c6 API: remove ProcessListContainer/ListProcesses
1366f0fb cli: Use genericGetExpectedHostDetails on s390x

### CODE REVIEW

**Review by egernst — APPROVED** [review]
Yea!

**Review by likebreath — APPROVED** [review]

**Comment by likebreath** [comment]
Happy release day. Thanks for the heavy-lifting @fidencio.

**Comment by fidencio** [comment]
ARM CI issues is tracked here: https://github.com/kata-containers/tests/issues/3478

**Comment by fidencio** [comment]
And we're back facing instabilities with the metrics:
```
01:09:02 Report Summary:
01:09:02 +-----+----------------------+-------+--------+--------+-------+--------+--------+--------+-------+-----+
01:09:02 | P/F |         NAME         |  FLR  |  MEAN  |  CEIL  |  GAP  |  MIN   |  MAX   |  RNG   |  COV  | ITS |
01:09:02 +-----+----------------------+-------+--------+--------+-------+--------+--------+--------+-------+-----+
01:09:02 | *F* | boot-times           | 90.0% | 116.0% | 110.0% | 20.0% | 104.3% | 275.8% | 164.3% | 31.6% |  20 |
01:09:02 | P   | memory-footprint     | 95.0% | 101.0% | 105.0% | 10.0% | 101.0% | 101.0% | 0.0%   | 0.0%  |   1 |
01:09:02 | P   | memory-footprint-ksm | 95.0% | 101.0% | 105.0% | 10.0% | 101.0% | 101.0% | 0.0%   | 0.0%  |   1 |
01:09:02 | P   | blogbench            | 90.0% | 97.1%  | 110.0% | 20.0% | 97.1%  | 97.1%  | 0.0%   | 0.0%  |   1 |
01:09:02 | P   | blogbench            | 90.0% | 94.2%  | 110.0% | 20.0% | 94.2%  | 94.2%  | 0.0%   | 0.0%  |   1 |
01:09:03 +-----+----------------------+-------+--------+--------+-------+--------+--------+--------+-------+-----+
```

**Comment by fidencio** [comment]
> And we're back facing instabilities with the metrics:
> 
> ```
> 01:09:02 Report Summary:
> 01:09:02 +-----+----------------------+-------+--------+--------+-------+--------+--------+--------+-------+-----+
> 01:09:02 | P/F |         NAME         |  FLR  |  MEAN  |  CEIL  |  GAP  |  MIN   |  MAX   |  RNG   |  COV  | ITS |
> 01:09:02 +-----+----------------------+-------+--------+--------+-------+--------+--------+--------+-------+-----+
> 01:09:02 | *F* | boot-times           | 90.0% | 116.0% | 110.0% | 20.0% | 104.3% | 275.8% | 164.3% | 31.6% |  20 |
> 01:09:02 | P   | memory-footprint     | 95.0% | 101.0% | 105.0% | 10.0% | 101.0% | 101.0% | 0.0%   | 0.0%  |   1 |
> 01:09:02 | P   | memory-footprint-ksm | 95.0% | 101.0% | 105.0% | 10.0% | 101.0% | 101.0% | 0.0%   | 0.0%  |   1 |
> 01:09:02 | P   | blogbench            | 90.0% | 97.1%  | 110.0% | 20.0% | 97.1%  | 97.1%  | 0.0%   | 0.0%  |   1 |
> 01:09:02 | P   | blogbench            | 90.0% | 94.2%  | 110.0% | 20.0% | 94.2%  | 94.2%  | 0.0%   | 0.0%  |   1 |
> 01:09:03 +-----+----------------------+-------+--------+--------+-------+--------+--------+--------+-------+-----+
> ```

Let's add this to the list of things we really need to address before we get 2.1.0 final release out.
For now, I made the CI not required and I'm moving forward with the merge & tagging.

**Pull request merged**
