### PR TITLE
runtime-rs: report error on missing or empty fields in configuration

### PR DESCRIPTION
**Pull request by yaoyinnan**
Removed the setting of default values for runtime fields. Added explicit checks for missing or empty fields, reporting errors with clear messages.

Fixes: #8838

### CODE REVIEW

**Review by justxuewei — APPROVED** [review]
Lgtm, thanks!

**Review by Apokleos — APPROVED** [review]
LGTM！

**Comment by justxuewei** [comment]
Please rebase atop of main to get the CI passed.

**Comment by justxuewei** [comment]
Please correct your email.

**Comment by yaoyinnan** [comment]
> Please rebase atop of main to get the CI passed.

rebased and corrected my email

**Pull request merged**
