### PR TITLE
ci: Actually enable the CRI-O tests

### PR DESCRIPTION
**Pull request by fidencio**
The test has been added to the repo, but we have to also add it to the
list of jobs to be executed.

Fixes: #8005

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks

**Comment by beraldoleal** [comment]
LGTM.

**Review by zvonkok — APPROVED** [review]
LGTM, thanks!

**Comment by fidencio** [comment]
I am bypassing the CI as it doesn't make sense to have it running for a change that will only be able to be tested after it's merged.

**Pull request merged**
