### PR TITLE
packaging: Cache the container used to build the kata-deploy artefacts

### PR DESCRIPTION
**Pull request by fidencio**
As we'll move the CI to be using the kata-deploy scripts to build the components, let's cache the images used and improve a little bit the building time of those components, while also having a realiable way to reproduce issues when debugging any sort of issues.

This has been in place as part of the CCv0 branch for a while and is a forward-port of that.

### CODE REVIEW

**Review by BbolroC — APPROVED** [review]
LGTM, thanks! :wink:

**Review by arronwy — APPROVED** [review]
Thanks @fidencio ,  LGTM! It helps a lots for the CI,

**Pull request merged**
