### PR TITLE
Upgrade to Cloud Hypervisor v21.0 

### PR DESCRIPTION
**Pull request by likebreath**
Highlights from the Cloud Hypervisor release v21.0: 1) Efficient Local
Live Migration (for Live Upgrade); 2) Recommended Kernel is Now 5.15; 3)
Bug fixes on OpenAPI yaml spec file, avoid deadlock for live-migration,
etc.

Details can be found: https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v21.0

Note: The client code of cloud-hypervisor's (CLH) OpenAPI is automatically
generated by openapi-generator [1-2]. As the API changes do not
impact usages in Kata, no additional changes in kata's runtime are
needed to work with the current version of cloud-hypervisor.

[1] https://github.com/OpenAPITools/openapi-generator
[2] https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/pkg/cloud-hypervisor/README.md

Fixes: #3519

Signed-off-by: Bo Chen <chen.bo@intel.com>

### CODE REVIEW

**Comment by likebreath** [comment]
@fidencio Once this PR is landed, you should be good to go with your PR that adds support of accepting opened TAP FDs for creating network interface with CH in Kata.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @likebreath!

**Comment by fidencio** [comment]
vfio error:
```
06:13:12 + sudo driverctl unset-override 0000:00:03.0
06:13:12 make: *** [Makefile:126: vfio] Error 1
06:13:12 [run.sh:113] ERROR: sudo -E PATH=/home/jenkins/workspace/workspace/kata-containers-2.0-vfio-PR/go/bin:/usr/local/go/bin:/usr/sbin:/sbin:/home/jenkins/workspace/workspace/kata-containers-2.0-vfio-PR/go/bin:/usr/local/go/bin:/usr/sbin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin CRI_RUNTIME=containerd bash -c make vfio
06:13:12 [jenkins_job_build.sh:208] ERROR: .ci/run.sh
06:13:12 Failed at /home/jenkins/ci_entry_point.sh +91: .ci/jenkins_job_build.sh "${repo_to_test}"
06:13:12 ++ handle_error 91
06:13:12 ++ local exit_code=2
06:13:12 ++ local line_number=91
06:13:12 ++ echo 'Failed at /home/jenkins/ci_entry_point.sh +91: .ci/jenkins_job_build.sh "${repo_to_test}"'
06:13:12 ++ exit 2
```

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
