### PR TITLE
version: bump to kubernetes 1.23

### PR DESCRIPTION
**Pull request by egernst**
Current latest release is 1.23.1. Let's update to this version for our
integration testing.

Fixes: #3477

Signed-off-by: Eric Ernst <eric_ernst@apple.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @egernst!

**Comment by fidencio** [comment]
Note to self, update CRI-O after this PR gets merged.

**Comment by fidencio** [comment]
/test_kata_deploy

(Eric, sorry for polluting the comments here, but I need this to test yet another thing)

**Review by snir911 — APPROVED** [review]
Thanks!

**Pull request merged**
