### PR TITLE
runtime: Enable FUSE_DAX kernel config for DAX

### LINKED ISSUE #3165: virtiofs DAX not working due to missing kernel config
[CONFIG_FUSE_DAX](https://cateee.net/lkddb/web-lkddb/FUSE_DAX.html) needs to be enabled.

See the kernel code: https://github.com/torvalds/linux/blob/cb690f5238d71f543f4ce874aa59237cf53a877c/fs/fuse/virtio_fs.c#L805-L806

### PR DESCRIPTION
**Pull request by fengwang666**
Otherwise DAX device cannot be set up. Manually tested end to end and confirm DAX is working after enabling this config.

Fixes #3165

Signed-off-by: Feng Wang <feng.wang@databricks.com>

### CODE REVIEW

**Review by fidencio — CHANGES_REQUESTED** [review]
@fengwang666, please, also bump https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kernel/kata_config_version.

**Comment by fidencio** [comment]
Also, I see this as a bug fix, so I'd suggest backporting this one to stable-2.3 once this one gets merged.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @fengwang666!

**Review by jcvenegas — APPROVED** [review]

**Comment by fidencio** [comment]
@fengwang666, please, raise a backport PR for this one.

**Comment by fengwang666** [comment]
backport PR: https://github.com/kata-containers/kata-containers/pull/3177

**Pull request merged**
