### PR TITLE
github: Remove kata-deploy-test action

### PR DESCRIPTION
**Pull request by fidencio**
Currently the action is not running because it's broken, and it was
broken by 50fea9f.

Sadly, I cannot just test a fix on a PR as every single time we end up
triggering what's currently on main, rather than triggering the content
of the PR itself.

With this in mind, let me just remove the file and re-add it as part of
a new PR and, hopefully, have it tested in this way.

Sorry for the breakage, by the way.

Fixes: #1634

Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>

### CODE REVIEW

**Review by wainersm — APPROVED** [review]

**Comment by egernst** [comment]
I don't think we wanted to merge this.

This test is designed to test kata-deploy, not the Kata Containers static binary creation. ie, you'd want to run this if you were modifying the kata-deploy scripting, to make sure it installs still correctly.

I think we want to keep this in (revert this?), and add a new test if you want to test static build

**Comment by egernst** [comment]
@fidencio  ^^

**Pull request merged**
