### PR TITLE
modify the minimum version of rust according to the tokio library ver…

### PR DESCRIPTION
**Pull request by houfangdong**
Agent compilation depends on tokio, but the tokio library cannot be compiled on lower versions of rust,
According to the requirements of the tokio community, 
the minimum version of rust is [1.45](https://github.com/tokio-rs/tokio#supported-rust-versions).

Fixes: [#3849](https://github.com/tokio-rs/tokio/issues/3849)

Signed-off-by: houfangdong <houfangdong@loongson.cn>

### CODE REVIEW

**Comment by devimc** [comment]
thanks @houfangdong - please fix your commit message format, take a look https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format

**Comment by houfangdong** [comment]
Thanks for the suggestion, is it this format?@devimc

**Comment by devimc** [comment]
> Thanks for the suggestion, is it this format?@devimc

@houfangdong almost, 80 is the maximum number of character per line, please fix your commit message (git commit --amend) and push it again

**Comment by liubin** [comment]
@houfangdong This repo has a `master` branch but it is not used. You should not merge master to your develop branch.

**Comment by houfangdong** [comment]
thanks,@liubin, Is it correct for me to push main now?

**Comment by liubin** [comment]
@houfangdong I'd suggest checking out a new dev branch from the latest main branch and use it to replace the current `main` branch.

Usually using `main` branch as a dev branch is not recommended.

[Here](https://github.com/liubin/kata-dev-book/blob/main/src/your-first-pr.md#%E4%BF%AE%E6%94%B9%E4%BB%A3%E7%A0%81) is a Chinese document, hope it will be helpful.

**Comment by houfangdong** [comment]
Thanks, in accordance with the community request, I resubmitted the [pr](https://github.com/kata-containers/kata-containers/pull/2004), and this one will be closed.
@liubin

**Comment by Tim-Zhang** [comment]
duplicated

**Pull request closed without merging**
