### PR TITLE
gha: Disable stratovirt for gha metrics

### LINKED ISSUE #8496: gha: Disable stratovirt for gha metrics

### PR DESCRIPTION
**Pull request by GabyCT**
This PR disables the stratovirt for gha metrics.

Fixes #8496

### CODE REVIEW

**Comment by amshinde** [comment]
@GabyCT Can you explain why we are doing this? is it failing? Might as well mark it an non-required in the github checks and continue to have this running.

**Comment by GabyCT** [comment]
@amshinde yes it is always failing, the job was enabled but to make it work it will require someone to fix it and work on that, so that is the main reason why I am disabling this until we have someone to work on this

**Comment by zvonkok** [comment]
@WenyuanLau FYI, stratovirt failing PTAL

**Review by zvonkok — APPROVED** [review]
LGTM, thanks!

**Comment by WenyuanLau** [comment]
Thanks for the reminding. @zvonkok  I've noticed the failing in these days caused by the wrong baseline, mainly because of the different running environment. I will fix them recently according to the data in the last GHA tests. :)

**Pull request merged**
