### PR TITLE
move the oci and protocols crates from agent to upper libs

### PR DESCRIPTION
**Pull request by lifupan**
move the oci and protocols crates from agent to upper libs, thus they can be shared between agent and other incoming rust runtimes.

Fixes: #3348

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @lifupan !

lgtm

**Comment by jodh-intel** [comment]
The static checks are failing on `cargo vendor`:

```
cargo vendor
error: failed to sync

Caused by:
  failed to load pkg lockfile

Caused by:
  failed to get `oci` as a dependency of package `kata-agent-ctl v0.0.1 (/home/runner/work/kata-containers/kata-containers/src/github.com/kata-containers/kata-containers/src/tools/agent-ctl)`

Caused by:
  failed to load source for dependency `oci`

Caused by:
  Unable to update /home/runner/work/kata-containers/kata-containers/src/github.com/kata-containers/kata-containers/src/agent/oci

Caused by:
  failed to read `/home/runner/work/kata-containers/kata-containers/src/github.com/kata-containers/kata-containers/src/agent/oci/Cargo.toml`

```

**Comment by jodh-intel** [comment]
Static checks failing:

```
[static-checks.sh:473] INFO: Checking SPDX license header
ERROR: Required SPDX license header check ('SPDX-License-Identifier: Apache-2.0') failed for the following files:

src/libs/protocols/protos/gogo/protobuf/gogoproto/gogo.proto
src/libs/protocols/protos/google/protobuf/empty.proto
```
This PR is blocked on https://github.com/kata-containers/tests/pull/4306

**Review by liubin — APPROVED** [review]

**Pull request merged**
