### PR TITLE
sandbox: Add device permissions such as /dev/null to cgroup

### PR DESCRIPTION
**Pull request by Bevisy**
adds the default devices for unix such as /dev/null, /dev/urandom to
the container's resource cgroup spec

Fixes: #2539

Signed-off-by: Binbin Zhang <binbin36520@gmail.com>

### CODE REVIEW

**Comment by Bevisy** [comment]
Maybe we don't necessarily need so many device permissions, the known ones are /dev/null, /dev/urandom

**Comment by fidencio** [comment]
@fgiudici, mind to review this one?

**Comment by fidencio** [comment]
@Bevisy, this is a regression and I'd also be super interested to know which commit introduced it.  Did you bisect the issue?

**Comment by fgiudici** [comment]
lgtm
This solves the issue, great job @Bevisy !
Wondering anyway why the /dev/null and /dev/random devices are no more allowed by default.
This should be investigated... maybe we need to fix this "earlier" in the code?
BTW, this fixes the issue and LGTM as we need to fix it in kata 2.2 stable ASAP.
As Fabiano wrote anyway, we should find what changed the default device permissions (vendored code??).

**Comment by Bevisy** [comment]
@fidencio , when using different cgroup driver(cgroupfs and systemd), we will encounter different problems(refer https://github.com/kata-containers/kata-containers/issues/2539#issuecomment-914057260). This pr fixes the problem with using the cgroupfs driver. For the case using the systemd driver, I will continue to investigate.

@fgiudici , 
>I tried to dig into the cause of the problem, and found that it might be a problem introduced by this commit 32c9ae1 , before that the commit compiled and created pods normally.

It may be related to the containererd version, I will continue to confirm.

**Comment by fidencio** [comment]
> @fidencio , when using different cgroup driver(cgroupfs and systemd), we will encounter different problems(refer [#2539 (comment)](https://github.com/kata-containers/kata-containers/issues/2539#issuecomment-914057260)). This pr fixes the problem using the cgroupfs driver. For the case using the systemd driver, I will continue to investigate.

Perfect, thanks!
The reason I'm being pedantic about this is to ensure we pin-point what caused the issue.  Red Hat has been using `sandbox_cgroup_only=true`, running with CRI-O, and that was working for 2.1.0 at least.

So, knowing what cause the regression is, at least, educational. :-)

Thanks a lot for working on this, @Bevisy!

**Comment by yylt** [comment]
@Bevisy 
think about https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#default-devices
might be should compare and set, not add devices directely

**Review by fidencio — APPROVED** [review]
lgtm, thanks @Bevisy!

cc @devimc @lifupan @bergwolf

**Review by devimc — APPROVED** [review]
thanks @Bevisy

**Comment by fidencio** [comment]
@yylt mentioned, but the comment doesn't seem to be here anymore
"""
think about https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#default-devices
might be should compare and set, not add devices directely
"""

@yylt, shall we hold this PR till we get this addressed?

**Comment by fidencio** [comment]
Holding it till @yylt's comments are addressed / commented on.

**Comment by yylt** [comment]
> Holding it till @yylt's comments are addressed / commented on.

sorry for that

what i commented is devices visible or not in the container, and json path in spec is `.linux.devices`

but here which dicussed is the access permitted to the devices, and json path in spec is `.linux.resources.devices`

the patch is correct

**Review by sameo — APPROVED** [review]

**Comment by sameo** [comment]
@fidencio @Bevisy Can we remove the do-not-merge label?

**Comment by fidencio** [comment]
> @fidencio @Bevisy Can we remove the do-not-merge label?

Done!
@yylt, thanks for chiming in. :-)

**Pull request merged**
