### PR TITLE
update golang.org/x/net

### LINKED ISSUE #9486: golang.org/x/net has some vulnerabilities and needs to be updated
# Description of problem
There are several reported vulnerabilities in the `golang.org/x/net` package that our internal security tooling is flagging. We'd like to update that package to close those vulnerabilities. 

Vulnerabilities:
https://github.com/advisories/GHSA-2wrh-6pvc-2jm9
https://github.com/advisories/GHSA-39qc-96h7-956f
https://github.com/advisories/GHSA-4374-p667-p6c8
https://github.com/advisories/GHSA-4r78-hx75-jjj2
https://github.com/advisories/GHSA-69cg-p879-7622
https://github.com/advisories/GHSA-83g2-8m93-v3w7
https://github.com/advisories/GHSA-h86h-8ppg-mxmh
https://github.com/advisories/GHSA-hgr8-6h9x-f7q9
https://github.com/advisories/GHSA-mv93-wvcp-7m7r
https://github.com/advisories/GHSA-qppj-fm5r-hxr3
https://github.com/advisories/GHSA-vfw5-hrgq-h5wf
https://github.com/advisories/GHSA-vvpx-j8f3-3w6h

# Further information
Attempting to fix this here: https://github.com/kata-containers/kata-containers/pull/9485

### PR DESCRIPTION
**Pull request by sparky005**
updates the update golang.org/x/net package. there are some reported vulnerabilities in this package and it's getting flagged by our internal security team. 

Updated the packages as follows:
```bash
cd src/runtime/virtcontainers/pkg/cloud-hypervisor/client
go get -u golang.org/x/net
go mod tidy
go mod vendor
```

Fixes #9486

### CODE REVIEW

**Comment by stevenhorsman** [comment]
Hi @sparky005 - Thanks for the PR - it looks like there are a couple of failures here:
- The runtime static checks are failing as the runtime go modules need tidying:
```
Run cd src/runtime
go mod tidy
go: downloading golang.org/x/sys v0.19.0
go: downloading golang.org/x/net v0.24.0
go mod vendor
go mod verify
```
-

**Comment by sparky005** [comment]
Thanks so much @stevenhorsman! Looks like I forgot to include some files in my original commit 😅. I've added them now but it looks like I'm still getting a failure, which looks like it may have been a kubelet issue? Not sure if that's related to my change or not.

**Comment by stevenhorsman** [comment]
> Thanks so much @stevenhorsman! Looks like I forgot to include some files in my original commit 😅. I've added them now but it looks like I'm still getting a failure, which looks like it may have been a kubelet issue? Not sure if that's related to my change or not.

Probably not - our integration test are not super stable. Let me do a bit of babysitting on it and see if I can get enough passing

**Comment by lifupan** [comment]
Thanks @sparky005， it's seemed some cases still failed, let me retest them.

**Review by lifupan — APPROVED** [review]
LGTM.

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks @sparky005!

**Pull request merged**
