### PR TITLE
CCv0: Merge main into CCv0 branch

### PR DESCRIPTION
**Pull request by Megan-Wright**
Merge remote-tracking branch 'upstream/main' into CCv0
    
Fixes: #5457
Signed-off-by: Megan Wright <megan.wright@ibm.com>

### CODE REVIEW

**Comment by Megan-Wright** [comment]
```
git diff --stat upstream/main -- . ':!*/vendor/*'
 .github/workflows/commit-message-check.yaml                                                       |    4 +-
 .github/workflows/deploy-ccv0-demo.yaml                                                           |  129 ++++
 .github/workflows/static-checks.yaml                                                              |    2 +-
 ci/install_libseccomp.sh                                                                          |    3 +-
 docs/how-to/README.md                                                                             |    4 +
 docs/how-to/ccv0.sh                                                                               |  640 +++++++++++++++++++
 docs/how-to/data/confidential-agent-config.toml.in                                                |   45 ++
 docs/how-to/how-to-build-and-test-ccv0.md                                                         |  479 ++++++++++++++
 docs/how-to/how-to-generate-a-kata-containers-payload-for-the-confidential-containers-operator.md |   44 ++
 docs/how-to/how-to-setup-swap-devices-in-guest-kernel.md                                          |    2 +
 docs/how-to/how-to-use-virtio-fs-nydus-with-kata.md                                               |    1 +
 docs/how-to/how-to-use-virtio-mem-with-kata.md                                                    |    2 +
 src/agent/Cargo.lock                                                                              | 2946 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++--------
 src/agent/Cargo.toml                                                                              |    6 +
 src/agent/rustjail/src/cgroups/fs/mod.rs                                                          |   19 +-
 src/agent/rustjail/src/lib.rs                                                                     |    8 +-
 src/agent/src/config.rs                                                                           |  208 ++++++
 src/agent/src/device.rs                                                                           |   18 +-
 src/agent/src/image_rpc.rs                                                                        |  411 ++++++++++++
 src/agent/src/main.rs                                                                             |    1 +
 src/agent/src/rpc.rs                                                                              |  197 +++++-
 src/agent/src/sandbox.rs                                                                          |    2 +
 src/libs/oci/src/lib.rs                                                                           |   10 +-
 src/libs/protocols/.gitignore                                                                     |    3 +
 src/libs/protocols/build.rs                                                                       |   21 +-
 src/libs/protocols/protos/image.proto                                                             |   31 +
 src/libs/protocols/src/lib.rs                                                                     |    4 +
 src/libs/protocols/src/trans.rs                                                                   |    4 +-
 src/runtime/Makefile                                                                              |  106 ++++
 src/runtime/arch/amd64-options.mk                                                                 |    2 +
 src/runtime/cmd/kata-runtime/kata-check_amd64.go                                                  |    2 +
 src/runtime/cmd/kata-runtime/kata-check_arm64.go                                                  |    3 +
 src/runtime/cmd/kata-runtime/kata-check_ppc64le.go                                                |    3 +
 src/runtime/cmd/kata-runtime/kata-check_s390x.go                                                  |    3 +
 src/runtime/config/configuration-clh-tdx.toml.in                                                  |  428 +++++++++++++
 src/runtime/config/configuration-clh.toml.in                                                      |    2 +-
 src/runtime/config/configuration-qemu-sev.toml.in                                                 |  660 +++++++++++++++++++
 src/runtime/config/configuration-qemu-tdx.toml.in                                                 |  636 +++++++++++++++++++
 src/runtime/config/configuration-qemu.toml.in                                                     |   27 +-
 src/runtime/go.mod                                                                                |    2 +
 src/runtime/go.sum                                                                                |  282 +--------
 src/runtime/hack/update-generated-hypervisor-proto.sh                                             |   13 +
 src/runtime/pkg/containerd-shim-v2/create.go                                                      |    5 +
 src/runtime/pkg/containerd-shim-v2/image.go                                                       |   84 +++
 src/runtime/pkg/govmm/qemu/qemu.go                                                                |   28 +-
 src/runtime/pkg/govmm/qemu/qmp.go                                                                 |   66 ++
 src/runtime/pkg/katautils/config-settings.go.in                                                   |    7 +
 src/runtime/pkg/katautils/config.go                                                               |  265 ++++----
 src/runtime/pkg/oci/utils.go                                                                      |    5 +
 src/runtime/pkg/oci/utils_test.go                                                                 |    2 +-
 src/runtime/pkg/sev/sev.go                                                                        |  163 +++++
 src/runtime/protocols/hypervisor/hypervisor.pb.go                                                 | 1848 +++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/runtime/protocols/hypervisor/hypervisor.proto                                                 |   46 ++
 src/runtime/protocols/simple-kbs/keybroker.pb.go                                                  |  573 +++++++++++++++++
 src/runtime/protocols/simple-kbs/keybroker.proto                                                  |   68 ++
 src/runtime/protocols/simple-kbs/keybroker_grpc.pb.go                                             |  141 +++++
 src/runtime/virtcontainers/acrn.go                                                                |    9 +
 src/runtime/virtcontainers/agent.go                                                               |    3 +
 src/runtime/virtcontainers/clh.go                                                                 |   11 +-
 src/runtime/virtcontainers/container.go                                                           |    5 +
 src/runtime/virtcontainers/fc.go                                                                  |    4 +
 src/runtime/virtcontainers/fs_share_linux.go                                                      |   57 +-
 src/runtime/virtcontainers/hypervisor.go                                                          |  426 ++++---------
 src/runtime/virtcontainers/hypervisor_config_darwin.go                                            |    4 +
 src/runtime/virtcontainers/hypervisor_config_linux.go                                             |    4 +
 tools/osbuilder/rootfs-builder/ubuntu/config.sh                                                   |   14 +-
 tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh                                               |   17 +-
 tools/osbuilder/scripts/lib.sh                                                                    |   25 +
 tools/packaging/guest-image/build_image.sh                                                        |   34 +-
 tools/packaging/kata-deploy-cc/Dockerfile                                                         |   30 +
 tools/packaging/kata-deploy-cc/scripts/kata-deploy.sh                                             |  287 +++++++++
 tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml                                   |    2 +-
 tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml                                     |    4 +-
 tools/packaging/kata-deploy/local-build/Makefile                                                  |   64 ++
 tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile                                    |   16 +-
 tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh                         |   12 +-
 tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh                                   |  196 +++++-
 tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-payload.sh                   |   24 +
 tools/packaging/kata-deploy/scripts/kata-deploy.sh                                                |    0
 tools/packaging/kernel/build-kernel.sh                                                            |   35 +-
 tools/packaging/kernel/configs/fragments/common/confidential_containers/cryptsetup.conf           |   21 +
 tools/packaging/kernel/configs/fragments/common/confidential_containers/initramfs.conf            |    1 +
 tools/packaging/kernel/configs/fragments/x86_64/crypto.conf                                       |    3 +
 tools/packaging/scripts/lib.sh                                                                    |   16 +
 tools/packaging/static-build/kernel/Dockerfile                                                    |    1 +
 tools/packaging/static-build/kernel/build.sh                                                      |    1 +
 tools/packaging/static-build/qemu/build-base-qemu.sh                                              |    8 +-
 tools/packaging/static-build/qemu/build-static-qemu-cc.sh                                         |   35 +
 tools/packaging/static-build/shim-v2/build.sh                                                     |   11 +-
 utils.mk                                                                                          |    4 +-
 versions.yaml                                                                                     |   38 +-
 121 files changed, 12962 insertions(+), 1253 deletions(-)
```

**Comment by BbolroC** [comment]
FYI: @Megan-Wright https://github.com/kata-containers/kata-containers/pull/5447 has been merged onto `main`, which fixes a CI failure on s390x.

**Comment by BbolroC** [comment]
> /test-s390x

I think you need to rebase the branch somewhere after the fix (7248cf51c57cb3bbc79a98b79394e00fae2ccb76, merged yesterday). Otherwise, the test for s390x will fail.

**Comment by fidencio** [comment]
```
19:18:47 INFO: build initramfs for cc kernel
19:18:47 /tmp/jenkins/workspace/kata-containers-CCv0-ubuntu-20.04-x86_64-CC_CRI_CONTAINERD-PR/go/src/github.com/kata-containers/kata-containers/tools/packaging/kata-deploy/local-build/kata-deploy-binaries.sh: line 138: /tmp/jenkins/workspace/kata-containers-CCv0-ubuntu-20.04-x86_64-CC_CRI_CONTAINERD-PR/go/src/github.com/kata-containers/kata-containers/tools/packaging/static-build/initramfs/build.sh: Permission denied
```

I'm debugging what may be causing this ...

**Comment by fidencio** [comment]
https://github.com/kata-containers/kata-containers/pull/5508 fixes the issue.

**Comment by fidencio** [comment]
s390x error is legit!
```
Status: Downloaded newer image for quay.io/kata-containers/cc-builders:qemu-94807e73e72ebddad4df96a85c24b9110391db22
quay.io/kata-containers/cc-builders:qemu-94807e73e72ebddad4df96a85c24b9110391db22
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/s390x) and no specific platform was requested
exec /usr/bin/bash: exec format error
```

**Review by fidencio — APPROVED** [review]
lgtm, thanks @Megan-Wright!

**Pull request merged**
