### PR TITLE
kernel: Fix vsock packets drop when the driver initializes

### PR DESCRIPTION
**Pull request by alex-matei**
This patch addresses a 10 second connection timeout occurring in HybridVSockDialer. When the virtio vsock driver initializes the kernel can drop reply packets to connection requests.

 If the agent `dial_timeout` is also set to 10 seconds, this leads to kata shim completely freezing in commonDialer when trying to write to the `cancel` channel. This second issue is fixed in PR #5668 (and PR #8151 which I closed as duplicate). Corresponding issues are #8150 and #5667.

Fixes: #8291

### CODE REVIEW

**Comment by fidencio** [comment]
@alex-matei:
```
Run kernel_dir="tools/packaging/kernel/"
tools/packaging/kernel/patches/5.10.x/0001-vsock-virtio-avoid-potential-deadlock-when-vsock-dev.patch
tools/packaging/kernel/patches/5.10.x/0002-vsock-each-transport-cycles-only-on-its-own-sockets.patch
tools/packaging/kernel/patches/5.10.x/0003-vsock-virtio-initialize-vdev-priv-before-using-VQs.patch
tools/packaging/kernel/patches/5.10.x/0004-vsock-virtio-enable-VQs-early-on-probe.patch
tools/packaging/kernel/patches/5.10.x/0005-vsock-virtio-factor-our-the-code-to-initialize-and-d.patch
tools/packaging/kernel/patches/5.10.x/0006-vsock-virtio-add-support-for-device-suspend-resume.patch
tools/packaging/kernel/patches/5.10.x/0007-vsock-virtio-initialize-the_virtio_vsock-before-usin.patch
tools/packaging/kernel/patches/5.[19](https://github.com/kata-containers/kata-containers/actions/runs/6848678174/job/18625595591?pr=8431#step:3:20).x/0001-vsock-virtio-initialize-the_virtio_vsock-before-usin.patch
tools/packaging/kernel/patches/5.19.x/no_patches.txt
tools/packaging/kernel/patches/6.2-TDX-v1.x/0001-vsock-virtio-initialize-the_virtio_vsock-before-usin.patch
tools/packaging/kernel/patches/6.2-TDX-v1.x/no_patches.txt
Kernel directory has changed, checking if tools/packaging/kernel/kata_config_version has been updated
Please bump version in tools/packaging/kernel/kata_config_version
```

**Comment by alex-matei** [comment]
@fidencio Fixed.

**Comment by fidencio** [comment]
The content of the PR itself looks good to me, and I'd like to see the tests run before approving it.

One last thing that I'd like to ask you to add is a full description of what you're doing / updating / why it's needed as part of the commit message.

Developers will not always have access to GitHub, and may rely on the commit message to understand why a change was made.  Please, add this, but do that after we have the tests passing.

**Comment by fidencio** [comment]
@alex-matei, please, update the commit message and I will approve the PR.

**Comment by alex-matei** [comment]
@fidencio Thanks, I updated the commit message to explain what is going on and fixed a small error with the arm-experimental version, I incorrectly set it to 5.15.200, it should be 5.15.138. Can you please add the backport label so that it can be ported to 3.2?

**Review by fidencio — APPROVED** [review]
lgtm, thanks @alex-matei!

**Comment by fidencio** [comment]
@alex-matei, I broke the actions Yesterday, my bad. Thankfully it's already been fixed, and I'd like to ask you to rebase your PR atop of main so the tests can be triggered.

**Comment by alex-matei** [comment]
@fidencio Done, rebased atop of main.

**Review by jepio — APPROVED** [review]

**Comment by jepio** [comment]
Thanks so much for hunting this down!

**Pull request merged**
