### PR TITLE
kernel building: Add module unload to SEV kernel config

### PR DESCRIPTION
**Pull request by Alex-Carter01**
adding to the sev kernel config for use of the efi secret kernel module.

Fixes: kata-containers#5866
Signed-off-by: Alex Carter <Alex.Carter@ibm.com>

### CODE REVIEW

**Review by fidencio — COMMENTED** [review]
You need to also bump the kernel version in https://github.com/kata-containers/kata-containers/blob/CCv0/tools/packaging/kernel/kata_config_version

**Review by dubek — APPROVED** [review]
Looks good (with the kata config number increase).

**Comment by Alex-Carter01** [comment]
Adding kernel config increment. 

Whoops, thanks for reminding!

**Review by fidencio — APPROVED** [review]
lgtm, thanks @Alex-Carter01!

**Comment by fidencio** [comment]
Static checks are failing:
```
Run tim-actions/commit-message-checker-with-regex@v0.3.1
Error: 

  [21](https://github.com/kata-containers/kata-containers/actions/runs/3688158072/jobs/6242844178#step:7:22)f7f18cd8633144cb6710ecd30313d68774d999    No "Fixes" found

See the document below for help on formatting commits for the project.

https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format
0s
Run tim-actions/commit-message-checker-with-regex@v0.3.[1](https://github.com/kata-containers/kata-containers/actions/runs/3688158072/jobs/6242844178#step:8:1)
Error: 

  21f7f[18](https://github.com/kata-containers/kata-containers/actions/runs/3688158072/jobs/6242844178#step:8:19)cd8633144cb6710ecd30313d68774d999    Failed to find subsystem in subject

See the document below for help on formatting commits for the project.

https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format
```

**Review by wainersm — APPROVED** [review]
Thank @Alex-Carter01 !

I left a comment on https://github.com/kata-containers/kata-containers/issues/5866 , so if you could reply...

**Review by fitzthum — APPROVED** [review]
I second the comment about changing the short log. This PR is technically more general than the EFI_SECRET module.

**Comment by wainersm** [comment]
hi @Alex-Carter01 , please format the commit as explained here: https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format

**Comment by Alex-Carter01** [comment]
rebased and config version incremented

**Comment by wainersm** [comment]
The failing CI jobs are unrelated with this PR.

I applied the changes proposed here on CCv0 and built the SEV kernel just fine. Going to merge it.

**Pull request merged**
