### PR TITLE
runtime: proper host cgroups by default

### PR DESCRIPTION
**Pull request by egernst**
For 2.0, let's enable sanboxCgroupOnly by default. This flag tells the
runtime to place the VMM, vcpu and IO threads within the cgroup
specified by the upper layer.

If PodOverhead isn't utilized, or if over-constrainted cgroups are
specified, there's a higher chance of OOM. Setting up the runtimeClass
and/or pods to take microVM into account is important, and this should
be handled in order to guarantee system stability.

Fixes: #971

Signed-off-by: Eric Ernst <eric.g.ernst@gmail.com>

### CODE REVIEW

**Comment by egernst** [comment]
This will likely depend on changes in tests to ensure that an appropriate runtimeClass is applied, and that Kubernetes 1.18 is utilized.

**Review by bergwolf — APPROVED** [review]
Thanks!

**Review by fidencio — APPROVED** [review]
lgtm!

**Review by jodh-intel — APPROVED** [review]
Thanks @egernst.

**Comment by fidencio** [comment]
Interesting ... the failures I see in some of the CIs (CentOS, Debian, and Fedora) are quite similar to failures I've faced when solving a non terminating pods issue on CRI-O. Are those 3 CIs using CRI-O?

```
01:09:03 [reset] Unmounting mounted directories in "/var/lib/kubelet"
01:09:28 W1015 23:09:27.986404  151715 cleanupnode.go:81] [reset] Failed to remove containers: [failed to stop running pod 0037f8bc7cb1bf24d0607972e653e150171bc50d0f8637fb9787cbfeaf65e396: output: time="2020-10-15T23:09:03Z" level=fatal msg="stopping the pod sandbox \"0037f8bc7cb1bf24d0607972e653e150171bc50d0f8637fb9787cbfeaf65e396\" failed: rpc error: code = Unknown desc = failed to stop infra container for pod sandbox 0037f8bc7cb1bf24d0607972e653e150171bc50d0f8637fb9787cbfeaf65e396: failed to stop container k8s_POD_sysctl-test_default_1cf6e6ca-9003-496c-8634-7f8f6e29e7d9_1: ttrpc: closed: unknown"
```

Here's the CRI-O PR, for reference: https://github.com/cri-o/cri-o/pull/4263

**Comment by egernst** [comment]
I'm concerned about the following error: http://jenkins.katacontainers.io/blue/organizations/jenkins/kata-containers-2.0-ubuntu-PR/detail/kata-containers-2.0-ubuntu-PR/582/pipeline#log-3286 :
```
ERROR: 7 pods left and found at /run/vc/sbs
```

Similar is seen across a few of the jobs. Taking a quick look, AFAICT the runtimeClass is included with PodOverhead, so this is unexpected.

**Comment by jodh-intel** [comment]
@egernst - I agree. Could you raise an issue to track that failure?

**Comment by bergwolf** [comment]
CI failed all because pods were left after tests. Looks like we have some pod cleanup issue with this PR.
```
07:09:28 0037f8bc7cb1bf24d0607972e653e150171bc50d0f8637fb9787cbfeaf65e396
07:09:28 1dc30d77e405f7eeb4ce555b2c711166d225f6291028de64b8a32f8a117c6eec
07:09:28 385acde919ef51003aa606a2764f72ce1fc76b84ee364ca51ef6b5a3f5b90199
07:09:28 516b00c3bbcb74f4aa245dbc700e7b33b01df40a3f78dfaabc6b1538480b37a8
07:09:28 894fa86d399f434756871772b10ae199387219930ffc833b53901266bf3a007b
07:09:28 ERROR: 5 pods left and found at /run/vc/sbs
```

**Comment by bergwolf** [comment]
fwiw, I wasn't able to reproduce it locally. Ran the k8s bats several times and no pods were left.

**Comment by bergwolf** [comment]
I found find the following log after testing:
```
[443654.799302] containerd invoked oom-killer: gfp_mask=0xcc0(GFP_KERNEL), order=0, oom_score_adj=-999
[443654.799306] CPU: 3 PID: 26735 Comm: containerd Not tainted 5.4.0-1026-azure #26~18.04.1-Ubuntu
[443654.799307] Hardware name: Microsoft Corporation Virtual Machine/Virtual Machine, BIOS 090008  12/07/2018
[443654.799308] Call Trace:
[443654.799316]  dump_stack+0x57/0x75
[443654.799321]  dump_header+0x4f/0x200
[443654.799323]  oom_kill_process+0xe6/0x120
[443654.799325]  out_of_memory+0x109/0x510
[443654.799329]  mem_cgroup_out_of_memory+0xbb/0xd0
[443654.799332]  try_charge+0x762/0x7c0
[443654.799336]  ? __alloc_pages_nodemask+0x153/0x320
[443654.799339]  mem_cgroup_try_charge+0x75/0x190
[443654.799341]  mem_cgroup_try_charge_delay+0x22/0x50
[443654.799343]  __handle_mm_fault+0x4cc/0x1330
[443654.799346]  ? __switch_to_asm+0x40/0x70
[443654.799348]  ? __switch_to_asm+0x40/0x70
[443654.799350]  handle_mm_fault+0xb7/0x200
[443654.799354]  __do_page_fault+0x29c/0x4c0
[443654.799356]  do_page_fault+0x35/0x110
[443654.799358]  page_fault+0x39/0x40
[443654.799361] RIP: 0033:0x7fe795baa346
[443654.799363] Code: 14 72 48 89 11 eb 98 0f 1f 44 00 00 48 39 d8 72 22 e9 8d f6 ff ff 66 0f 1f 44 00 00 48 8b 50 10 48 83 c0 18 4c 01 f2 48 39 c3 <48> 89 11 0f 86 70 f6 ff ff 8b 50 08 48 8b 08 4c 01 f1 48 83 fa 26
[443654.799365] RSP: 002b:00007ffca978f1b0 EFLAGS: 00010202
[443654.799367] RAX: 0000556d1b529f30 RBX: 0000556d1b6e7070 RCX: 0000556d1d6dc028
[443654.799367] RDX: 0000556d1c6ba804 RSI: 00007ffca978f250 RDI: 00007fe795dc59f0
[443654.799368] RBP: 00007ffca978f2c0 R08: 0000000000000000 R09: 0000000000000798
[443654.799370] R10: 00007fe795dc6170 R11: 0000000000000206 R12: 0000000000000000
[443654.799371] R13: 0000000000000000 R14: 0000556d1a6ab000 R15: 00007fe795dc6170
[443654.799373] memory: usage 675840kB, limit 675840kB, failcnt 84
[443654.799375] memory+swap: usage 0kB, limit 9007199254740988kB, failcnt 0
[443654.799375] kmem: usage 20864kB, limit 9007199254740988kB, failcnt 0
[443654.799376] Memory cgroup stats for /kubepods/burstable/podd1ff73ae-32f9-47c2-acc9-9600e60e8a58:
[443654.799390] anon 27525120
                file 642723840
                kernel_stack 294912
                slab 3579904
                sock 0
                shmem 642723840
                file_mapped 642723840
                file_dirty 0
                file_writeback 0
                anon_thp 4194304
                inactive_anon 640831488
                active_anon 29589504
                inactive_file 135168
                active_file 0
                unevictable 0
                slab_reclaimable 1773568
                slab_unreclaimable 1806336
                pgfault 197637
                pgmajfault 0
                workingset_refault 0
                workingset_activate 0
                workingset_nodereclaim 0
                pgrefill 0
                pgscan 0
                pgsteal 0
                pgactivate 0
                pgdeactivate 0
                pglazyfree 363
                pglazyfreed 0
                thp_fault_alloc 0
                thp_collapse_alloc 0
[443654.799391] Tasks state (memory values in pages):
[443654.799391] [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
[443654.799395] [  26516]     0 26516   332112     9637   245760        0          -999 containerd-shim
[443654.799398] [  26533]     0 26533    19135      321    49152        0          -999 virtiofsd
[443654.799400] [  26546]     0 26546   733187   168841  1572864        0          -999 qemu-system-x86
[443654.799402] [  26549]     0 26549   748227     1607   237568        0          -999 virtiofsd
[443654.799404] [  26735]     0 26735    15796     4551   110592        0          -999 containerd
[443654.799406] oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=kata_9509222927ac7a8d97ef20daa7025fbbb01f25585b162e99d594ff734c68625a,mems_allowed=0,oom_memcg=/kubepods/burstable/podd1ff73ae-32f9-47c2-acc9-9600e60e8a58,task_memcg=/kubepods/burstable/podd1ff73ae-32f9-47c2-acc9-9600e60e8a58/kata_9509222927ac7a8d97ef20daa7025fbbb01f25585b162e99d594ff734c68625a,task=qemu-system-x86,pid=26546,uid=0
[443654.799437] Memory cgroup out of memory: Killed process 26546 (qemu-system-x86) total-vm:2932748kB, anon-rss:13808kB, file-rss:34020kB, shmem-rss:627536kB, UID:0 pgtables:1536kB oom_score_adj:-999
[443654.834430] oom_reaper: reaped process 26546 (qemu-system-x86), now anon-rss:0kB, file-rss:12kB, shmem-rss:627784kB
```

When a pod is killed before being started, containerd would not know about its existence and thus will not tell kata to clean it up. Then the pod directory is left behind in kata.

**Comment by egernst** [comment]
So looks like an OOMkill. 160MB not being enough is quite interesting

**Comment by bergwolf** [comment]
@egernst There must be something else other than oom. I tested #985 (which is #972 plus more change that I thought might be necessary upon code inspection) with 300MB memory pod overhead and CI still reported pods being left behind.

**Comment by bergwolf** [comment]
Got a bit more logs here http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-initrd-PR/151/consoleFull
With 300MB pod overhead, no more oom killer triggered.

One pod was left after testing: 2af0776c358a897bcc57cb874d7366e9e1b68efbf903bdd1d1f08b12f19c1c8f

However, the only message relating to it in containerd logs is:
```
Oct 19 05:43:55 ubuntu1804-azure1564c0 containerd[12074]: time="2020-10-19T05:43:55.694004675Z" level=info msg="RunPodsandbox for &PodSandboxMetadata{Name:deploymenttest-68b7b5895-l6kmp,Uid:eaffb59c-fd00-4c07-a02f-f7f089761bc9,Namespace:default,Attempt:0,}"
Oct 19 05:43:56 ubuntu1804-azure1564c0 containerd[12074]: time="2020-10-19T05:43:56.885373126Z" level=info msg="shim disconnected" id=2af0776c358a897bcc57cb874d7366e9e1b68efbf903bdd1d1f08b12f19c1c8f
Oct 19 05:43:57 ubuntu1804-azure1564c0 containerd[12074]: time="2020-10-19T05:43:57.246392122Z" level=error msg="RunPodSandbox for &PodSandboxMetadata{Name:busybox,Uid:0e6b7307-c209-4d3b-9b00-b9f027a2a341,Namespace:default,Attempt:1,} failed, error" error="failed to create containerd task: ttrpc: closed: unknown"
```

Looks like a pod was created with sandbox container ID `2af0776c358a897bcc57cb874d7366e9e1b68efbf903bdd1d1f08b12f19c1c8f` that quitted very quickly.

**Comment by bergwolf** [comment]
Giving the fact that `160MB` pod overhead still leads to OOM, and that there are unknown reasons that pod directories are not cleaned up properly, I don't think the `sandbox_cgroup_only` option can be turned on by default ATM. Let's drop it from the `2.0` release.

We can continue the investigation and turn on the switch when we figure out all the details and fix them.

**Comment by egernst** [comment]
> @egernst There must be something else other than oom. I tested #985 (which is #972 plus more change that I thought might be necessary upon code inspection) with 300MB memory pod overhead and CI still reported pods being left behind.

@bergwolf I think we should consider your changes from #972 in general, while we continue to debug. WDYT?

**Comment by egernst** [comment]
@chavafg @GabyCT -- do we have any tests in place for 2.0 and for 1.x for setting sandbox cgroup only and using PodOverhead? I want to make sure this is exercised in our CI so we can move this forward, even if it isn't by default now.

**Comment by chavafg** [comment]
I see that we have checks for sandbox cgroups only on 1.x: https://github.com/kata-containers/tests/blame/master/.ci/run.sh#L26 , but we only run the containerd-cri integration tests with this config.
In addition there is a k8s test with sandbox cgroups only + huge pages, but this one is being skipped. 
For 2.x, both are disabled.

**Comment by fidencio** [comment]
I'm really sorry for the disruption but in order to do the branch name changes announced [here](http://lists.katacontainers.io/pipermail/kata-dev/2021-January/001695.html) I'm adding the "do-not-merge" and the "needs-branch-adjustment" labels to the PR.

I'll add a new comment once the branch changes are done and once it happens I'd like to ask you to resubmit the PR against the new `main` branch, possibly linking to this PR in case you find the conversations / reviews already made important to proceed.

**Comment by fidencio** [comment]
Kata Containers repos are back to business.  Thanks a lot for your patience and I'm very happy to announce that there's no changes needed from your side as renaming the branches automagically reflected here.

If you notice something weird, some missing CI, please, do not hesitate on contacting us here or on #kata-dev on bit.ly/katacontainersslack.

Also, this is a good opportunity to have your PR rebased atop of `main`, to ensure your PR follow all the guidelines (https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format) enforced by this community, or even to re-evaluate whether the PR is currently needed.

Last but not least,  as the default branch has been renamed to `main`, if you have a local clone you'd need to update it and you do so by running:
```
git branch -m 2.0-dev main
git fetch origin
git branch -u origin/main main
```

Happy hacking!

**Pull request closed without merging**
