### PR TITLE
ci: cache: Use the artefacts stored in ghcr.io/kata-containers/cached-artefacts/${component}

### PR DESCRIPTION
**Pull request by fidencio**
With this we can get rid of the Jenkins logic and jobs related to caching the components.

### CODE REVIEW

**Comment by fidencio** [comment]
@Amulyam24, this will make the builds for powerpc slower, as it's removing the cached components / way to cache the components on Jenkins.

I know this is a drawback, but I do believe we can live with this for some time, for the sake of reducing the CI costs, and also reducing the complexity.

**Review by zvonkok — APPROVED** [review]
LGTM, thanks @fidencio

**Review by stevenhorsman — APPROVED** [review]
LGTM. Thanks!

**Comment by fidencio** [comment]
I've opened an issue for the nerdctl + cloud hypervisor CI failures: https://github.com/kata-containers/kata-containers/issues/7968

**Comment by Amulyam24** [comment]
Thanks for the heads up @fidencio. I assume that once the ppc64le support PR for oras is merged, we can start using the artefacts for Power in the same manner?
P.S: I am working on having the workflow for building kata-static-tarballs for ppc64le

**Pull request merged**
