### PR TITLE
Built-in Sandbox: add more unit tests for dragonball.

### PR DESCRIPTION
**Pull request by wllenyj**
This pull request introduces more unit tests for Dragonball.
Since `runtime-rs` has been merged into the `main` branch, so reopen this pr.  The previous pr #4604.

### CODE REVIEW

**Comment by liubin** [comment]
@wllenyj `src/dragonball/test_resources/img/x86_64/initrd/initrd.img` is a 24.7MB large file, I'd like to remove it and the test case that use it.

Any other options?

**Comment by wllenyj** [comment]
@liubin Or is there another place where you can store it? And then download it in CI ?

**Comment by liubin** [comment]
@wllenyj I'm sorry for this another comment, it' better to split this big one into many small ones that:

- easy to review and will let it been merged ASAP
- leave hard things, like the test image alone, don't block other ones.

And for holding test resources, I don't have any good ideas, maybe we can put it in an repo that only contains test resources.

**Comment by wllenyj** [comment]
@liubin Ok, I will do it later.

**Comment by liubin** [comment]
@wllenyj 

I created #4928 for share test code includes `skip_if_not_root!()` or `skip_if_root!()`, you can wait a moment.

**Comment by wllenyj** [comment]
@liubin Thanks for your pr #4928.

>  it' better to split this big one into many small ones that:

Fixed.

**Review by liubin — APPROVED** [review]

**Review by cmaf — APPROVED** [review]
thanks @wllenyj

**Pull request merged**
