### PR TITLE
Rust fixes + Golang bump

### PR DESCRIPTION
**Pull request by fidencio**
As we've a bunch of PRs that are depending on each other on this very same repo, let me group those together and open a single PR with the hope that it'll simplify having them merged.

This groups together:
* https://github.com/kata-containers/kata-containers/pull/5658
* https://github.com/kata-containers/kata-containers/pull/5640
* https://github.com/kata-containers/kata-containers/pull/5511

### CODE REVIEW

**Comment by studychao** [comment]
wow thanks @fidencio ,that's quite useful!

**Comment by fidencio** [comment]
All the failures on the BM machines are because those systems are still using golang 1.17.3, and I'm not exactly sure why.
/cc @Amulyam24 @jongwu @BbolroC

**Comment by fidencio** [comment]
> All the failures on the BM machines are because those systems are still using golang 1.17.3, and I'm not exactly sure why. /cc @Amulyam24 @jongwu @BbolroC

This seems to be solved after merging the tests PR.

**Review by GabyCT — APPROVED** [review]

**Review by bergwolf — APPROVED** [review]
Thanks a lot @fidencio !

**Comment by bergwolf** [comment]
> All the failures on the BM machines are because those systems are still using golang 1.17.3, and I'm not exactly sure why.

It is because we use the jenkins install script of main branch from tests repo to setup the test environment. In the script the PR dependency is resolved but it cannot update the script itself.

**Comment by fidencio** [comment]
Had to close and re-open to retrigger the static-checks.

**Review by studychao — APPROVED** [review]

**Review by sameo — APPROVED** [review]

**Pull request merged**
