### PR TITLE
qemu: remove default config for arm64.

### PR DESCRIPTION
**Pull request by jongwu**
The current default config in qemu for arm64 doesn't suit for qemu
version 5.1+, so remove them here.

Fixes: #2595
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>

### CODE REVIEW

**Comment by GabyCT** [comment]
@jongwu could you please add if this will require backport? thanks

**Comment by jongwu** [comment]
@fidencio @GabyCT -, help review.

**Comment by sameo** [comment]
@jongwu Would you be able to provide a working config for qemu+arm64?

**Comment by jongwu** [comment]
hello @sameo -, do you mean the qemu device config? if so I think the default is the best for now.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jongwu!

**Comment by sameo** [comment]
> hello @sameo -, do you mean the qemu device config? if so I think the default is the best for now.

for the record: the default config for aarch64 that's provided by the upstream project is the best config for now. LGTM.

**Review by sameo — APPROVED** [review]

**Pull request merged**
