### PR TITLE
Add loongarch64 support in agent

### PR DESCRIPTION
**Pull request by zhaixiaojuan**
The LoongArch architecture (LoongArch) is an Instruction Set Architecture (ISA) that has a RISC style.

Documentations:
ISA:
https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html
ABI:
https://loongson.github.io/LoongArch-Documentation/LoongArch-ELF-ABI-EN.html
More docs can be found at:
https://loongson.github.io/LoongArch-Documentation/README-EN.html

Fixes: https://github.com/kata-containers/kata-containers/issues/7423

### CODE REVIEW

**Comment by bergwolf** [comment]
What about runtime and vmm?

**Comment by zhaixiaojuan** [comment]
> What about runtime and vmm?

The basic functions have been transplanted, and the test is currently running, and the code will be uploaded after the test is completed

**Pull request closed without merging**
