### PR TITLE
main | docs: Fix missing critical steps in how-to-hotplug-memory-arm64.md

### PR DESCRIPTION
**Pull request by singhwang**
docs: Fix missing critical steps in how-to-hotplug-memory-arm64.md

The key steps in how-to-hotplug-memory-arm64.md are missing, resulting in the kata qemu pod not being created successfully.

Fixes: #6105

Signed-off-by: Singh Wang <wangxin_0611@126.com>

### CODE REVIEW

**Comment by singhwang** [comment]
I have submitted this patch to the stable-3.0 branch, and this time I will submit it to the main branch again.

**Comment by jongwu** [comment]
Hi @singhwang -, does your code only cover document file or also including the change about dragonball? What's those dragonball changes related with arm64? Also, I can't see your second commits. Maybe you should new a branch other than main  to do the change in your side and push it again. Hope it will help.

**Comment by singhwang** [comment]
> Hi @singhwang -, does your code only cover document file or also including the change about dragonball? What's those dragonball changes related with arm64? Also, I can't see your second commits. Maybe you should new a branch other than main to do the change in your side and push it again. Hope it will help.

My changes only include documentation, not drgonball.

**Comment by jongwu** [comment]
@singhwang -，The first commit mixes with the change of dragonball. Can you check it?

**Comment by singhwang** [comment]
> @singhwang -，The first commit mixes with the change of dragonball. Can you check it?

Let me resubmit a pr. The current pr I submitted the code to pull down the changes.

**Pull request closed without merging**
