### PR TITLE
docs: Fix relative links in Markdown

### LINKED ISSUE #3045: Docs links in non-main branches points to main
# Description of problem

When kata's documentation refers to full-path link within the repository it will usually points to the **main** branch docs, also when the link is pointed from other branches such as **stable**, this may lead to a missing or non-relevant (to branch) files 

# Expected result

All links are pointing to the documentation on the same branch of the link

# Actual result

Most links points to main branch

# Further information

* [Here's an example](https://github.com/kata-containers/kata-containers/pull/3039) where a backport was required in order to fix a broken link on **stable** as it was removed from **main**
* [Relative paths](https://github.blog/2013-01-31-relative-links-in-markup-files/) is the straight foreword solution, however, it may break link validation checks or other tests 
* Also having some job verifying all internal links added in a PR are valid (according to the chosen solution) could be nice

### PR DESCRIPTION
**Pull request by hxtmdev**
Relative links within this repository allow for easier navigation to
the corresponding file / directory in the current commit / for the
selected version.

Link text was slightly changed / fixed in
- docs/Unit-Test-Advice.md
- docs/how-to/how-to-run-docker-with-kata.md

Fixes #3045

### CODE REVIEW

**Comment by hxtmdev** [comment]
Should a follow-up issue for the checking CI job (see #3045) be created?

**Review by devimc — APPROVED** [review]
lgtm - thanks

**Review by egernst — APPROVED** [review]
Looks good -- thanks for addressing this issue!

**Review by snir911 — DISMISSED** [review]
LGTM, thank you!
as there are still links that need to be fixed I'd suggest to leave the issue open (re-open it) after merge

**Comment by hxtmdev** [comment]
> LGTM, thank you! as there are still links that need to be fixed I'd suggest to leave the issue open (re-open it) after merge

@snir911 Can you point me to an example please? I used `grep 'https://github.com/kata-containers/kata-containers/\(tree\|blob\)' *.md **/*.md -C5` (might be zsh only) which now only results in
```
tools/packaging/kernel/README.md-configuration.
tools/packaging/kernel/README.md-
tools/packaging/kernel/README.md-Example:
tools/packaging/kernel/README.md-
tools/packaging/kernel/README.md-```bash
tools/packaging/kernel/README.md:# From https://github.com/kata-containers/kata-containers/blob/main/versions.yaml
tools/packaging/kernel/README.md-$ kernel_version_in_versions_file=5.4.60
tools/packaging/kernel/README.md:# From https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kernel/kata_config_version
tools/packaging/kernel/README.md-$ kata_config_version=83
tools/packaging/kernel/README.md-$ latest_kernel_version=${kernel_version_in_versions_file}-${kata_config_version}
tools/packaging/kernel/README.md-```
tools/packaging/kernel/README.md-
tools/packaging/kernel/README.md-The resulting version is 5.4.60-83, this helps identify whether or not the kernel
```
which I left as is because it's inside a code block and not clickable, a relative link would of course help in an editor, less so on GitHub.

**Comment by snir911** [comment]
Hi, I'm sorry, pls ignore, i misread your PR msg

**Comment by egernst** [comment]
Seem the EFK change needs to merge first (or be included in this PR)

**Comment by hxtmdev** [comment]
(rebased so the static checks can see the EFK markdown fix)

**Review by egernst — DISMISSED** [review]

**Review by snir911 — APPROVED** [review]

**Review by egernst — APPROVED** [review]

**Pull request merged**
