### PR TITLE
Fixes make check errors

### PR DESCRIPTION
**Pull request by beraldoleal**
Compiler is giving us two errors when running make check.

### CODE REVIEW

**Comment by fidencio** [comment]
@beraldoleal, which version of the compiler? I'm asking because we're not seeing those as part of our CI.

**Comment by beraldoleal** [comment]
@fidencio 1.72.0. I just installed with `ci/install_rust.sh`

**Comment by fidencio** [comment]
> @fidencio 1.72.0. I just installed with `ci/install_rust.sh`

I wonder how we're not facing these as part of our CI then.

**Review by fidencio — APPROVED** [review]
Regardless of CI catching it or not, this one lgtm! Thanks a lot @beraldoleal!

**Review by jodh-intel — APPROVED** [review]
Thanks @beraldoleal! lgtm

**Comment by wainersm** [comment]
@beraldoleal running the jobs again as the build of the rootfs failed

**Pull request merged**
