### PR TITLE
actions: Remove wip-check

### PR DESCRIPTION
**Pull request by Tim-Zhang**
wip-check action would set commit status to failure and the commit will be marked as failure forever,
and this is not corret.

Fixes: #525

Signed-off-by: Tim Zhang <tim@hyper.sh>

### CODE REVIEW

**Comment by amshinde** [comment]
@Tim-Zhang Why are we removing this? I fail to understand when/where the condition is met that you mentioned in the commit message.  
I see that the action is behaving satisfactorily while testing it out, any updates to a PR or change in labels triggers this action correctly.
What I think can be an improvement is that the action should specifically check for the `wip` keywords only at the beginning of the commit message subject and not fail if the keyword is present anywhere else in the commit body.

**Comment by Tim-Zhang** [comment]
> @Tim-Zhang Why are we removing this? I fail to understand when/where the condition is met that you mentioned in the commit message.
> I see that the action is behaving satisfactorily while testing it out, any updates to a PR or change in labels triggers this action correctly.
> What I think can be an improvement is that the action should specifically check for the `wip` keywords only at the beginning of the commit message subject and not fail if the keyword is present anywhere else in the commit body.

The wip-check will leave a ❌ on the commit, I think is not good, for the further information please see #525

**Comment by bergwolf** [comment]
per #525, does the wip check PR labels? We use labels a lot but I don't see labels mentioned in the wip apps introduction page.

> After my investigation, I found that GitHub action is indeed not suitable for this work. I think we can replace the Action wip-check with a GitHub App: https://github.com/apps/wip

**Comment by Tim-Zhang** [comment]
> per #525, does the wip check PR labels? We use labels a lot but I don't see labels mentioned in the wip apps introduction page.
> 
> > After my investigation, I found that GitHub action is indeed not suitable for this work. I think we can replace the Action wip-check with a GitHub App: https://github.com/apps/wip

Yes, it does, but it's not free!

image

**Comment by jodh-intel** [comment]
If I'm understanding this correctly, the problem is that there is no GitHub event for the action to detect when the "wip" *comment* is removed from the PR title? It certainly is possible to detect when the `wip` *label* is removed using the [`unlabeled`](https://docs.github.com/en/actions/reference/events-that-trigger-workflows) event (as I do on https://github.com/kata-containers/proxy/pull/276/files for example).

If the problem is detecting the removal of the wip comment, I suggest we switch to only supporting blocking a PR from landing if it has a `wip` *label* (and updating https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#github-labels-and-keywords-that-block-prs and informing the community of this change).

**Comment by jodh-intel** [comment]
Hi @Tim-Zhang - please can you provide further info on this.

**Pull request closed without merging**
