### PR TITLE
[backport stable-2.1] versions: Upgrade to cloud-hypervisor v16.0

### PR DESCRIPTION
**Pull request by likebreath**
Back-porting PR https://github.com/kata-containers/kata-containers/pull/1993.

Highlights from the Cloud Hypervisor release v16.0: 

1. Improved live migration support;
2. Improved `vhost-user` support; 
3. ARM64 ACPI and UEFI support; 
4. Bug fixes.

Details can be found: https://github.com/cloud-hypervisor/cloud-hypervisor/releases/tag/v16.0

Note: The client code of cloud-hypervisor's OpenAPI is automatically
generated by `openapi-generator` [1-2]. As the API changes do not
impact usages in Kata, no additional changes in kata's runtime are
needed to work with the current version of cloud-hypervisor.

[1] https://github.com/OpenAPITools/openapi-generator
[2] https://github.com/kata-containers/kata-containers/blob/main/src/runtime/virtcontainers/pkg/cloud-hypervisor/README.md

Fixes: #1992

Signed-off-by: Bo Chen <chen.bo@intel.com>
(cherry picked from commit 85c40001dab1f51eae0d2920cfbc74ee86a70d64)

### CODE REVIEW

**Comment by fidencio** [comment]
Hmmm.
```
ERROR: Invalid URL 'http://jenkins.katacontainers.io/job/kata-containers-runtime-ubuntu-18-04-master/badge/icon' found in the following files:

src/runtime/README.md
ERROR: Invalid URL 'http://jenkins.katacontainers.io/job/kata-containers-runtime-ubuntu-18-04-master/' found in the following files:
```

**Comment by GabyCT** [comment]
@fidencio and @likebreath the error can be fixed by https://github.com/kata-containers/kata-containers/pull/2033

**Review by GabyCT — APPROVED** [review]

**Comment by likebreath** [comment]
@GabyCT @chavafg Any thoughts on why the GH action on `Static checks` is still failing?

```
make[1]: Leaving directory '/home/runner/work/kata-containers/kata-containers/src/github.com/kata-containers/kata-containers/tools/agent-ctl'
Error: The operation was canceled.
```

**Comment by likebreath** [comment]
Looks like the GH action won't automatically rebase (fast-forwarding) for you. A manual rebase on the latest `stable-2.1` branch resolved the issue of `static check` failure.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @likebreath!

**Pull request merged**
