### PR TITLE
genpolicy: cargo clippy fixes

### PR DESCRIPTION
**Pull request by danmihai1**
Clean up cargo clippy errors.

Fixes: #8818

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
The code changes LGTM and using rust 1.72.0 matching the versions.yaml there were no clippy errors when I tried it locally after this change:
```
genpolicy stevenh$ cargo clippy --all-features --release -- -D warnings
    Finished release [optimized] target(s) in 0.21s
```
Thanks Dan!

**Review by fidencio — APPROVED** [review]
lgtm, thanks @danmihai1!

**Pull request merged**
