### PR TITLE
build: Improve top-level Makefile

### LINKED ISSUE #331: Improve top-level Makefile
Improve the top-level Makefile to avoid hard-coding standard target names / duplicating rules.

Replaces #75.

### PR DESCRIPTION
**Pull request by jodh-intel**
Define a set of functions that support the standard rules (build, install, test, *etc*). Then simply add new components and tools to the appropriate variable to support all the standard build semantics.

Fixes #331.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Notes:

- osbuilder is not handled as it's too different to other components.
- we could add more rules in `utils.mk` to allow things like `make build-all-tools` or `make build-all-components` at a later point.

**Comment by bergwolf** [comment]
```
make: Entering directory '/home/travis/gopath/src/github.com/kata-containers/kata-containers/src/agent'
make: *** No rule to make target 'check'.  Stop.
make: Leaving directory '/home/travis/gopath/src/github.com/kata-containers/kata-containers/src/agent'
```

**Comment by jodh-intel** [comment]
Debian and 18.04 CI Are failing with this:

```
Init cluster using /var/run/crio/crio.sock
sudo: kubeadm: command not found
Failed at 109: sudo -E kubeadm init --config "${kubeadm_config_file}"
Failed at 80: ./init.sh
sudo: kubeadm: command not found
```

/cc @GabyCT

**Comment by jodh-intel** [comment]
It's actually earlier than that:

```
Install Kubernetes
Install Kubernetes components
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: no valid OpenPGP data found.
Failed at 32: sudo apt-key add -
Kubernetes not installed
```

**Comment by chavafg** [comment]
could that be transient error? 
Restarting job, btw, lets see if `/test-ubuntu` works

/test-ubuntu

**Comment by chavafg** [comment]
ubuntu job passed now. have also restarted the debian job via jenkins.

**Pull request merged**
