### PR TITLE
DNM, just tests | Remove musl installations

### PR DESCRIPTION
**Pull request by Jakob-Naucke**
We needed those for the Go agent, but Rustup just takes care of
everything. I need to test this specifically on ARM, where this already
appeared to work on CentOS, but there were some issues.

Signed-off-by: Jakob Naucke <jakob.naucke@ibm.com>

### CODE REVIEW

**Comment by Jakob-Naucke** [comment]
okay I know what I need to know

**Comment by Jakob-Naucke** [comment]
I'm going to derail this for some more /debug-s390x since #4548 has been merged

**Comment by Jakob-Naucke** [comment]
okay we're back in the game can we repeat this? /debug-s390x

**Comment by Jakob-Naucke** [comment]
nothing is ever reproducible /debug-s390x

**Comment by jodh-intel** [comment]
@Jakob-Naucke - please can you update to resolve the conflicts?

**Comment by Jakob-Naucke** [comment]
@jodh-intel this is never to be merged, I just need a space to `/debug-s390x` (hopefully not for long anymore)

**Comment by Jakob-Naucke** [comment]
What can I say? Interactively, it keeps working, even on the public instance… /debug-s390x

**Pull request closed without merging**
