### PR TITLE
agent: upgrade cgroups to 0.2.0

### PR DESCRIPTION
**Pull request by Tim-Zhang**
- upgrade crate cgroups to 0.2.0
- Avoid container stats panic caused by cgroup controller non-exist

### CODE REVIEW

**Review by lifupan — APPROVED** [review]

**Comment by liubin** [comment]
Hi @Tim-Zhang , CI failed due to:

```
error: this lifetime isn't used in the function definition
   --> rustjail/src/cgroups/fs/mod.rs:949:15
    |
949 | fn new_cgroup<'a>(
    |               ^^
    |
    = note: `-D clippy::extra-unused-lifetimes` implied by `-D warnings`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#extra_unused_lifetimes
error: aborting due to previous error

```

**Comment by Tim-Zhang** [comment]
> Hi @Tim-Zhang , CI failed due to:
> 
> ```
> error: this lifetime isn't used in the function definition
>    --> rustjail/src/cgroups/fs/mod.rs:949:15
>     |
> 949 | fn new_cgroup<'a>(
>     |               ^^
>     |
>     = note: `-D clippy::extra-unused-lifetimes` implied by `-D warnings`
>     = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#extra_unused_lifetimes
> error: aborting due to previous error
> ```

Fixed, thx.

**Review by liubin — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Thanks @Tim-Zhang.

lgtm

**Comment by jodh-intel** [comment]
@devimc - the snap CI is faling:

```
Building godeps 
Error: unknown command "r" for "yq"
Run 'yq --help' for usage.
Failed to run 'override-build': Exit code was 1.
Error: Process completed with exit code 2.
```

**Pull request merged**
