### PR TITLE
agent: add tests for update_container_namespaces

### LINKED ISSUE #4034: agent tests: Add tests for update_container_namespaces in src/rpc.rs
Add tests for `update_container_namespaces` function in the `src/rpc.rs` file in the agent. Related to #292.

### PR DESCRIPTION
**Pull request by bradenrayhorn**
Add test coverage for update_container_namespaces function
in src/rpc.rs. Includes minor refactor to make function easier
to test.

Fixes #4034

Signed-off-by: Braden Rayhorn <bradenrayhorn@fastmail.com>

### CODE REVIEW

**Review by liubin — APPROVED** [review]

**Comment by bradenrayhorn** [comment]
Resolved merge conflict.

**Review by jodh-intel — APPROVED** [review]
Thanks @bradenrayhorn!

lgtm

**Comment by arronwy** [comment]
Can one of the admins verify this patch?

**Pull request merged**
