### PR TITLE
VirtioFS: backports & default settings to improve performance

### PR DESCRIPTION
**Pull request by fidencio**
This PR contains two patches mentioned by @dagrh during the Architecture Meeting Today that could help with performance.

Please, refer to:
https://github.com/kata-containers/kata-containers/issues/943 and https://github.com/kata-containers/kata-containers/issues/944

### CODE REVIEW

**Comment by egernst** [comment]
This looks good to me; what was the default pool-size before?

**Comment by fidencio** [comment]
> This looks good to me; what was the default pool-size before?

The default thread-pool-size is 64.

**Review by egernst — APPROVED** [review]

**Comment by egernst** [comment]
@bergwolf PTAL?

**Review by likebreath — APPROVED** [review]

**Review by amshinde — APPROVED** [review]

**Review by bergwolf — APPROVED** [review]

**Pull request merged**
