### PR TITLE
ci: shim-v2 no sudo

### PR DESCRIPTION
**Pull request by zvonkok**
Build shim-v2 without sudo docker this is not needed. This is part 6 of N

### CODE REVIEW

**Comment by zvonkok** [comment]
Some example errors due to `sudo` and `USER` mixup 

```
Caused by:
  process didn't exit successfully: `/zvonkok/github.com/zvonkok/kata-containers/src/runtime-rs/target/release/build/protocols-3fb9d939f88e505c/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=protos/google/protobuf/empty.proto
  cargo:rerun-if-changed=protos/gogo/protobuf/gogoproto/gogo.proto
  cargo:rerun-if-changed=protos/oci.proto
  cargo:rerun-if-changed=protos/types.proto
  cargo:rerun-if-changed=protos/csi.proto
  
  
  ✦ ❯ ls -lh src/libs/protocols/src 
total 1.1M
-rw-r--r-- 1 root    root    492K May 28 11:12 agent.rs
-rw-r--r-- 1 root    root     47K May 28 11:12 agent_ttrpc_async.rs
-rw-r--r-- 1 root    root     45K May 28 11:12 agent_ttrpc.rs
-rw-r--r-- 1 root    root     26K May 28 11:12 csi.rs
-rw-r--r-- 1 root    root    5.9K May 28 11:12 empty.rs
-rw-r--r-- 1 root    root     28K May 28 11:12 gogo.rs
-rw-r--r-- 1 root    root     23K May 28 11:12 health.rs
-rw-r--r-- 1 root    root    3.5K May 28 11:12 health_ttrpc_async.rs
-rw-r--r-- 1 root    root    3.2K May 28 11:12 health_ttrpc.rs
-rw-rw-r-- 1 zvonkok zvonkok  639 May 28 08:11 lib.rs
-rw-r--r-- 1 root    root    300K May 28 11:12 oci.rs
-rw-rw-r-- 1 zvonkok zvonkok 2.0K May 28 08:11 serde_config.rs
-rw-rw-r-- 1 zvonkok zvonkok  30K May 28 08:11 trans.rs
-rw-r--r-- 1 root    root     50K May 28 11:12 types.rs

 ❯ sudo chown zvonkok src/libs/protocols/src/*
```

```
✦ ❯ ls -lh build/shim-v2/{builddir,destdir}
build/shim-v2/builddir:
total 64M
-rw-r--r-- 1 root root 64M May 28 11:49 kata-static-shim-v2.tar.xz
-rw-r--r-- 1 root root  93 May 28 11:49 shim-v2-sha256sum

build/shim-v2/destdir:
total 4.0K
drwxr-xr-x 3 zvonkok zvonkok 4.0K May 28 11:50 opt
```

The final tarball is not owned by the user since we're doing a sudo tar in kata-deploy-binaries.sh. Once we have all parts build without sudo the final tarball should be owned by the user as well.

**Review by BbolroC — APPROVED** [review]
LGTM, thanks @zvonkok

**Review by Apokleos — APPROVED** [review]
Thx @zvonkok LGTM

**Review by fidencio — APPROVED** [review]
lgtm, thanks @zvonkok!

**Pull request merged**
