### PR TITLE
Fix lints and remove allow attributes which silence these warnings

### PR DESCRIPTION
**Pull request by Tim-Zhang**
Remove following attributes:

`#![allow(non_camel_case_types)]`
`#![allow(unused_parens)]`
`#![allow(unused_unsafe)]`
`#![allow(dead_code)]`
`#![allow(non_snake_case)`

### CODE REVIEW

**Review by jcvenegas — APPROVED** [review]

**Review by mxpv — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Thanks @Tim-Zhang!

**Review by lifupan — APPROVED** [review]

**Pull request merged**
