### PR TITLE
stable-2.3: backport lint fixes from main

### PR DESCRIPTION
**Pull request by egernst**
These result in build failures when using recent toolchain - let's ensure these fixes are on stable branch as well.

### CODE REVIEW

**Review by jcvenegas — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thanks @egernst!

**Comment by egernst** [comment]
(seems ARM CI has been having some network connectivity issues? -- restart job)

**Comment by Jakob-Naucke** [comment]
#3526 was required -- /retest-arm /retest-s390x

**Pull request merged**
