### PR TITLE
CC | kata-deploy: Add executable bit to script

### PR DESCRIPTION
**Pull request by jepio**
We need the executable bit set because it is preserved into the runtime-payload-ci image.

Fixes: #7460

### CODE REVIEW

**Comment by fidencio** [comment]
Nice, can you also do this for the `main` branch?

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jepio!

**Comment by jepio** [comment]
> Nice, can you also do this for the `main` branch?

Main branch doesn't have this issue.

**Comment by fidencio** [comment]
> Main branch doesn't have this issue.

Yeah, I noticed I didn't break it there, thanks for the fix!. :-)

**Comment by fidencio** [comment]
We can merge this one without running the CIs, as the change will only be tested as part of the operator tests.

**Pull request merged**
