### PR TITLE
kernel: Updates to kernel config for ppc64le

### PR DESCRIPTION
**Pull request by jing-wang4**
Need to enable virtiofs and ipv6 to kernel config for ppc64le.

Fixes: #1333
Signed-off-by: Jing Wang <jing.wang4@ibm.com>

### CODE REVIEW

**Comment by jing-wang4** [comment]
@fidencio 
Please review this PR per your comment: https://github.com/kata-containers/kata-containers/pull/1314#issuecomment-769946296
Thanks!

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jing-wang4.

**Comment by fidencio** [comment]
@kata-containers/power, please, also take a look. :-)

**Review by likebreath — APPROVED** [review]

**Comment by fidencio** [comment]
So, patch looks good and I won't block it to be merged, but we really need to get PowerPC CI working.
@kata-containers/power, let's sync next week in order to get the CI working.

**Pull request merged**
