### PR TITLE
packaging/kernel: Add additional security options

### PR DESCRIPTION
**Pull request by jodh-intel**
Update the guest kernel configuration by applying a number of security
options as recommended by the [`kconfig-hardened-check`](https://github.com/a13xp0p0v/kconfig-hardened-check) tool.

Fixes: #4224.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Note that there will need to be follow-on PRs to allow a fully "clean" `kconfig-hardened-check` report since:

- Some of the kernel options are a bit awkward to deal with.
- Our tooling need to be improved to deal with some of the recommended options.

See: #4226.

**Review by cmaf — COMMENTED** [review]
@jodh-intel I like the idea, but currently a lot of the tests are unable to construct the .config:
```
ERROR: Failed to construct requested .config file
```

**Comment by egernst** [comment]
I'm curious -- can you run the kernel src's  scripts/bloat-o-meter   with and without this config change?

**Comment by jodh-intel** [comment]
@cmaf - Thanks. The problem was that a block of config options require an external package dependency that isn't installed on the CI systems. I'll add that chunk to the pile of security options to add in the future and have just removed them from this PR to give us a chance to enable atleast some of these settings.

---
@egernst - Yep. There is of course an impact. For binary size, comparing Kata version 2.4.1 (kernel 5.15.26) with the changes on this PR:

```bash
$ bloat-o-meter /opt/kata/share/kata-containers/vmlinux-5.15.26-90 /usr/share/kata-containers/vmlinux.container|grep ^Total:
Total: Before=10196974, After=11218623, chg +10.02%
```

This relates to the "full fat kernel" discussions we had recently (https://github.com/kata-containers/kata-containers/issues/3399, https://gist.github.com/jodh-intel/b9e0d241b6bb1700bc0074dadc3c99b8). There was / is interest in making Kata use the hosts own kernel. I've added some more comments on that to #3399.

**Comment by jodh-intel** [comment]
CI failures seem to be arch-specific so I'm going to have to potentially move some of these config options to arch-specific fragments it seems...

**Comment by jodh-intel** [comment]
@jongwu - the ARM CI is failing with this error (I think we used to see this a lot in the past?):

```
16:55:24 Building remotely on [arm03_slave](http://jenkins.katacontainers.io/computer/arm03_slave) (arm_node arm-ubuntu-2004) in workspace /home/jenkins/workspace/kata-containers-2.0-ubuntu-ARM-PR
16:55:24 [WS-CLEANUP] Deleting project workspace...
16:55:24 [WS-CLEANUP] Deferred wipeout is used...
16:55:37 ERROR: [WS-CLEANUP] Cannot delete workspace: Unable to delete '/home/jenkins/workspace/kata-containers-2.0-ubuntu-ARM-PR'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts. (Discarded 10412 additional exceptions)
16:55:37 ERROR: Cannot delete workspace: Unable to delete '/home/jenkins/workspace/kata-containers-2.0-ubuntu-ARM-PR'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts. (Discarded 10412 additional exceptions)
```

**Comment by jongwu** [comment]
@jodh-intel -, I see that the error for Arm CI is about k8s hugepages test,

> 14:47:03 not ok 1 Hugepages
14:47:03 # (in test file k8s-hugepages.bats, line 51)
14:47:03 #   `kubectl wait --for=condition=Ready --timeout=$timeout pod "$pod_name"' failed
14:47:03 # INFO: k8s configured to use runtimeclass
14:47:03 # pod/hugepage-pod created
14:47:03 # error: timed out waiting for the condition on pods/hugepage-pod
14:47:03 # pod "hugepage-pod" deleted

It seems this PR cause this failure, otherwise Arm CI passes. I'll look into it.

**Comment by jodh-intel** [comment]
Thanks @jongwu!

**Comment by jongwu** [comment]
Hello @jodh-intel -, some update about my debug. In my local test, it's the "CONFIG_INIT_ON_FREE_DEFAULT_ON" that cause the hugepage test failure on Arm, but I can't give the reason for now.

**Comment by fidencio** [comment]
@jodh-intel, we're closing this PR as it's been opened and inactive for more than one year.
If you think this is a mistake and the PR should be re-opened, please, feel free to do so after rebasing it atop of current main.

**Pull request closed without merging**
