### PR TITLE
Stop getting OOM events from agent for "ttrpc closed" error

### PR DESCRIPTION
**Pull request by liubin**
Stop getting OOM events from agent for "ttrpc closed" error

Fixes: #3815

### CODE REVIEW

**Review by c3d — APPROVED** [review]
Looks good. The commit about "logs" should probably not have the "Fixes" tag, since it's really a cleanup commit.

**Comment by c3d** [comment]
@liubin You will also need to add the porting labels.

**Review by egernst — APPROVED** [review]

**Comment by egernst** [comment]
I'm okay with seeing this back ported.

**Pull request merged**
