### PR TITLE
github: Remove issue template and use central one

### PR DESCRIPTION
**Pull request by jodh-intel**
Remove the GitHub issue template from this repository. We already have a
central set of templates [1] that are being used so the template in this
repository is redundant.

[1] - https://github.com/kata-containers/.github/tree/master/.github/ISSUE_TEMPLATE/

Fixes: #728.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Review by liubin — APPROVED** [review]

**Comment by liubin** [comment]
It's seems comment lines length check not worked correctly.

BTW, just an experience, I have leaved the URL line alone without anything else to pass the "Commit Message Check"

**Comment by jodh-intel** [comment]
Hi @liubin - yes, we're discussing improving that check on https://github.com/kata-containers/kata-containers/pull/688.

**Review by bergwolf — APPROVED** [review]

**Pull request merged**
