### PR TITLE
kata-monitor: fix agentUrl from containerd shim

### PR DESCRIPTION
**Pull request by deagon**
It should be "/agent-url" here.

Fix: #9013

### CODE REVIEW

**Comment by deagon** [comment]
@liubin @fengwang666 Take a review pls.

**Comment by justxuewei** [comment]
Hi @deagon. Thanks for your contribution. The format of commit message is incorrect. Please refer to [this doc](https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#closing-issues). Your PR will not be merged until you fix that.

**Comment by deagon** [comment]
> Hi @deagon. Thanks for your contribution. The format of commit message is incorrect. Please refer to [this doc](https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#closing-issues). Your PR will not be merged until you fix that.

@justxuewei Sorry for my misoperation.

**Review by justxuewei — APPROVED** [review]
Lgtm, thanks!

**Review by Apokleos — APPROVED** [review]
Thx @deagon LGTM!

**Pull request merged**
