### PR TITLE
kata-deploy-cc: Port fixes

### PR DESCRIPTION
**Pull request by stevenhorsman**
Port over fixes from `kata-deploy` into `kata-deploy-cc`
- https://github.com/kata-containers/kata-containers/pull/6829
- https://github.com/kata-containers/kata-containers/pull/6913
- https://github.com/kata-containers/kata-containers/pull/6648

Fixes: #6955

### CODE REVIEW

**Comment by fidencio** [comment]
TDX QEMU CI has passed but didn't report back.

**Comment by fidencio** [comment]
I've restarted the SEV one.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @stevenhorsman

**Comment by stevenhorsman** [comment]
The s390x test has also passed, but not reported back yet: http://jenkins.katacontainers.io/job/kata-containers-CCv0-ubuntu-20.04-s390x-PR/632/ so I think this is ready to merge

**Pull request merged**
