### PR TITLE
Cherrypick agent-policy support from main to CCv0

### PR DESCRIPTION
**Pull request by bpradipt**
With the focus of the CoCo community to port changes from CCv0 to main as part of "merge-to-main" effort, this PR is a digression.  

This PR cherrypicks the agent policy support from main to CCv0 to help with the following:

1. Provide a building block to continue experimenting with policy and identify issues at the earliest. This is especially helpful for remote hypervisor (peer-pods) as currently we have no way to test this feature and identify areas of improvements.
2. Provide a building building block to prototype and understand any potential gaps or integration issues with the `initdata` specification discussed in the following issue -  https://github.com/confidential-containers/confidential-containers/issues/171 

Is it ok with folks to have this PR in CCv0 with the disclaimer: "use at your own risk" or something similar ?

### CODE REVIEW

**Comment by bpradipt** [comment]
@fidencio @stevenhorsman ptal. And please feel free to close it, if it creates unnecessary distractions to the merge to main work.

**Comment by fidencio** [comment]
That's fair.

**Comment by bpradipt** [comment]
> Keep in mind we have no CIs available to run this code. So, if you really want to have it merged, we can have it merged, but there will be absolutely **zero** tests for this code.

Yes. And also that's why anyone using this commit will be knowingly using it with these risks.

**Comment by bpradipt** [comment]
> > Keep in mind we have no CIs available to run this code. So, if you really want to have it merged, we can have it merged, but there will be absolutely **zero** tests for this code.
> 
> Yes. And also that's why anyone using this commit will be knowingly using it with these risks.

I have added a statement in the commit message itself indicating there are no tests for this feature.

**Review by danmihai1 — APPROVED** [review]

**Comment by fidencio** [comment]
With Dan's approval, I'm going ahead and merging this one.

**Comment by bpradipt** [comment]
Thanks @danmihai1 @fidencio

**Pull request merged**
