### PR TITLE
vendor: Update github.com/containerd/cgroups to v1.0.2

### PR DESCRIPTION
**Pull request by c3d**
This new version reportedly has better support for cgroup v2.
Note that this commit only integrates the new version, it
does not add any v2 support in Kata Containers.

Fixes: #2857

Signed-off-by: Christophe de Dinechin <dinechin@redhat.com>

### CODE REVIEW

**Comment by c3d** [comment]
I realize that some files were missing from the initial `go vendor` because we don't actually use the `v2`. So for review purpose, I added the missing files "manually", but I wonder what the good practice is here.

**Comment by mattico** [comment]
cc https://github.com/kata-containers/kata-containers/issues/927

**Comment by fidencio** [comment]
Based on https://github.com/kata-containers/kata-containers/pull/2861#issuecomment-946650003, I'm adding the `wip` label.

**Comment by jodh-intel** [comment]
Marking as stale as this PR may have been abandoned.

**Comment by jodh-intel** [comment]
Any update on this @c3d or shall we close?

**Comment by c3d** [comment]
@jodh-intel Somehow, I thought this was completed. I'll revive it.

**Comment by jodh-intel** [comment]
Thanks @c3d.

**Comment by fidencio** [comment]
A head's up that may affect your PR.

In the Architecture Committee meeting from January 25th, 2022, the Architecture Committee has agreed on using the "Dismiss stale pull request approvals when new commits are pushed" configuration from GitHub.  It basically means that if your PR has been rebased or updated, the approvals given will be erased.

In order to minimize traumas due to the new approach, please, consider adding a note on the changes done before the rebase / force-push, and also pinging the reviewers for a subsequent round of reviews.

Thanks for your understanding!

Related issue: https://github.com/kata-containers/community/issues/249

**Comment by jodh-intel** [comment]
@c3d - could you rebase to resolve the conflict?

**Comment by jodh-intel** [comment]
Ping @c3d to resolve the conflict on this PR.

**Comment by jodh-intel** [comment]
Re-ping @c3d.

**Comment by arronwy** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
