### PR TITLE
CCv0 | Update guest components dependency version

### PR DESCRIPTION
**Pull request by Xynnn007**
Update Attestation-Agent and  image-rs version. They are needed to fix the CI error. Refer to https://github.com/confidential-containers/kbs/issues/124

Fixes: #7285

### CODE REVIEW

**Comment by fidencio** [comment]
@stevenhorsman, I'd like to have this one merged before the https://github.com/kata-containers/kata-containers/pull/7300, so we ensure TDX won't break there.

**Review by fidencio — APPROVED** [review]
lgtm, thanks a lot @Xynnn007 and @arronwy for working on this! <3

**Comment by fidencio** [comment]
Adding the `do-not-merge` label till all the TEE CIs have passed.

**Comment by fidencio** [comment]
Cloud Hypervisor TDX passed but didn't report back: http://10.112.240.228:8080/job/kata-containers-CCv0-cloud-hypervisor-TDX-CRI_CONTAINERD_K8S-PR/963/console

**Comment by UnmeshDeodhar** [comment]
@fitzthum it is indeed weird. I have seen this once before and I just retriggered the job and the test passed. So not sure what might be an issue here. Let me take a look.

**Comment by UnmeshDeodhar** [comment]
Retriggered the SEV job. SEV test is passing now.

**Pull request merged**
