### PR TITLE
CCv0: Merge main into CCv0 branch 

### PR DESCRIPTION
**Pull request by stevenhorsman**
Merge remote-tracking branch 'upstream/main' into CCv0

Fixes: #3376
Signed-off-by: stevenhorsman <steven@uk.ibm.com>

### CODE REVIEW

**Comment by stevenhorsman** [comment]
```bash
$ git diff --stat upstream/main -- . ':!*/vendor/*'
 .github/workflows/commit-message-check.yaml                                   |    4 +-
 .github/workflows/deploy-ccv0-demo.yaml                                       |  126 ++++++++++++++++++++++++++
 .github/workflows/static-checks.yaml                                          |    2 +-
 docs/how-to/README.md                                                         |    3 +
 docs/how-to/ccv0.sh                                                           |  501 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 docs/how-to/data/confidential-agent-config.toml.in                            |   40 +++++++++
 docs/how-to/how-to-build-and-test-ccv0.md                                     |  381 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/agent/Cargo.lock                                                          | 1070 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++---
 src/agent/Cargo.toml                                                          |    7 ++
 src/agent/protocols/build.rs                                                  |    1 +
 src/agent/protocols/protos/image.proto                                        |   31 +++++++
 src/agent/protocols/src/lib.rs                                                |    2 +
 src/agent/src/config.rs                                                       |  118 ++++++++++++++++++++++++
 src/agent/src/image_rpc.rs                                                    |  494 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/agent/src/main.rs                                                         |    1 +
 src/agent/src/rpc.rs                                                          |  115 ++++++++++++++++++++----
 src/agent/src/sandbox.rs                                                      |    2 +
 src/runtime/go.mod                                                            |   40 ++++-----
 src/runtime/go.sum                                                            |  412 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++----------------------
 src/runtime/pkg/containerd-shim-v2/create.go                                  |    5 ++
 src/runtime/pkg/containerd-shim-v2/image.go                                   |   84 +++++++++++++++++
 src/runtime/pkg/katautils/config.go                                           |    1 +
 src/runtime/pkg/oci/utils.go                                                  |    5 ++
 src/runtime/virtcontainers/agent.go                                           |    4 +
 src/runtime/virtcontainers/container.go                                       |    5 ++
 src/runtime/virtcontainers/image/image.go                                     |   23 +++++
 src/runtime/virtcontainers/interfaces.go                                      |    4 +
 src/runtime/virtcontainers/kata_agent.go                                      |   25 ++++++
 src/runtime/virtcontainers/mock_agent.go                                      |    5 ++
 src/runtime/virtcontainers/pkg/agent/protocols/client/client.go               |    2 +
 src/runtime/virtcontainers/pkg/agent/protocols/grpc/image.pb.go               |  613 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 src/runtime/virtcontainers/pkg/mock/mock.go                                   |    4 +
 src/runtime/virtcontainers/pkg/vcmock/sandbox.go                              |    5 ++
 src/runtime/virtcontainers/sandbox.go                                         |    9 ++
 src/tools/agent-ctl/src/client.rs                                             |  112 +++++++++++++++++++++--
 tools/osbuilder/rootfs-builder/README.md                                      |    7 ++
 tools/osbuilder/rootfs-builder/alpine/Dockerfile.in                           |    4 +
 tools/osbuilder/rootfs-builder/clearlinux/Dockerfile.in                       |    4 +
 tools/osbuilder/rootfs-builder/rootfs.sh                                      |   95 +++++++++++++++++++-
 tools/osbuilder/rootfs-builder/signed-container-artifacts/README.md           |   14 +++
 tools/osbuilder/rootfs-builder/signed-container-artifacts/public.gpg          |   30 +++++++
 tools/osbuilder/rootfs-builder/signed-container-artifacts/quay_policy.json    |   18 ++++
 tools/osbuilder/rootfs-builder/signed-container-artifacts/signatures.tar      |  Bin 0 -> 2157 bytes
 tools/osbuilder/rootfs-builder/ubuntu/Dockerfile-aarch64.in                   |    5 ++
 tools/osbuilder/rootfs-builder/ubuntu/Dockerfile.in                           |    6 ++
 tools/osbuilder/rootfs-builder/ubuntu/config.sh                               |   14 ++-
 tools/osbuilder/rootfs-builder/ubuntu/rootfs_lib.sh                           |    9 ++
 tools/osbuilder/scripts/lib.sh                                                |   25 ++++++
 tools/packaging/guest-image/build_image.sh                                    |   22 +++--
 tools/packaging/kata-deploy/kata-cleanup/base/kata-cleanup.yaml               |    2 +-
 tools/packaging/kata-deploy/kata-deploy/base/kata-deploy.yaml                 |    4 +-
 tools/packaging/kata-deploy/local-build/Makefile                              |    3 +
 tools/packaging/kata-deploy/local-build/dockerbuild/Dockerfile                |   16 ++--
 tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh     |    7 +-
 tools/packaging/kata-deploy/local-build/kata-deploy-build-and-upload-image.sh |   24 +++++
 tools/packaging/kata-deploy/scripts/kata-deploy.sh                            |   16 +++-
 versions.yaml                                                                 |   30 +++++--
 57 files changed, 4412 insertions(+), 199 deletions(-)
```

**Comment by stevenhorsman** [comment]
I think the static-checks issue is due to a problem in the ocicrypt-rs package that is pulled in. `ocicrypt-rs` states that it supports `hmac` `">=0.11"` in its [Cargo.toml](https://github.com/containers/ocicrypt-rs/blob/9af596112a64326828416806e049cf0e0ffc9320/Cargo.toml#L31), but it is using the [`NewMac` trait](https://docs.rs/hmac/0.11.0/hmac/trait.NewMac.html) that has been removed in `v0.12.0`.
I think the issue has to be solved in ocicrypt-rs, so I'll have a see if I can get a reproduce on just that repo and raise the issue/PR to fix it there.

**Comment by stevenhorsman** [comment]
I've managed to reproduce the build error on the `ocicrypt-rs` repo, so created the [issues](https://github.com/containers/ocicrypt-rs/issues/16) and attempted to fix it in [PR #17](https://github.com/containers/ocicrypt-rs/pull/17). So once that is merged hopefully the kata agent build in the static checks will start to work again.

**Comment by fidencio** [comment]
A head's up that may affect your PR.

In the Architecture Committee meeting from January 25th, 2022, the Architecture Committee has agreed on using the "Dismiss stale pull request approvals when new commits are pushed" configuration from GitHub.  It basically means that if your PR has been rebased or updated, the approvals given will be erased.

In order to minimize traumas due to the new approach, please, consider adding a note on the changes done before the rebase / force-push, and also pinging the reviewers for a subsequent round of reviews.

Thanks for your understanding!

Related issue: https://github.com/kata-containers/community/issues/249

**Comment by stevenhorsman** [comment]
As with https://github.com/kata-containers/tests/pull/4313, now the [ocicrypt-rs issue](https://github.com/containers/ocicrypt-rs/issues/16) has been solved (with thanks to @sameo), the tests are now all passing. It is work noting that due to the long blockers, the version of `main` this is merging is from 4th Jan, so after it's merged my intention is to immediately do another merge of the latest `main` in, but I want to do them as separate PRs to avoid doubling up on merge complexities.

**Review by wainersm — APPROVED** [review]
LGTM

**Pull request merged**
