### PR TITLE
Add katacontainers end-to-end arch image

### PR DESCRIPTION
**Pull request by zanetworker**
**How to categorize this PR?**

/area documentation 
/kind enhancement

**What this PR does / why we need it:**

This PR adds a Katacontainers e2e flow figure, the figure can be used in many places or simply just as a reference. It contains pieces from Kata 1.x and Kata 2.0 (e.g., kata-monitor). 

Fixes: #1185

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @zanetworker!

**Comment by c3d** [comment]
@zanetworker Thanks for the great work.

In the katacontainers-e2e-with-bg.png, it seems like the background logo on the cri-o / containerd side is wrong. It looks like the kata logo to me.

**Comment by c3d** [comment]
Maybe add a small arrow up for VMEXIT and down for ioctls()?

**Comment by zanetworker** [comment]
> In the katacontainers-e2e-with-bg.png, it seems like the background logo on the cri-o / containerd side is wrong. It looks like the kata logo to me.

The Kata logo on the left side is there to emphasize that the low-level runtime being communicated with is kata. 

> Maybe add a small arrow up for VMEXIT and down for ioctls()?

Can do :)

**Review by c3d — APPROVED** [review]
It looks like reviewing binary files is a bit more complicated than regular files.

Here are a few suggestions:
* Amend the commit text to explain how the pictures are produced. If I understand correctly, the SVG is the source. At least mention the tools you used to produce the diagrams, and how you produced the PNG files. In short, make it so that someone else can edit your pictures.
* Check if the leftmost logo next to CRI-O should really be kata. Looks to me like you meant something else.
* Add small arrows to indicate direction for VMEXIT and ioctls()
* Add other hypervisor names after QEMU, something like VMM: QEMU, Firecracker, …
* Mention alternate names for configuration files? E.g. `/etc/kata-containers/configuration.toml` like you did for crio
* Add the path to the runtime binary in crio.conf. It's important to understand the flow.

Approving nonetheless, since it's a really good document already, and I think you can do the changes in later iterations of the document.

**Comment by c3d** [comment]
@zanetworker Also just thought about something else. Your little character on the left talks directly to the kubelet. In practice, this is not how this works. I don't know if it's at all feasible to show either something that talks directly to cri-o like `crictl`, or if you want to stick to the k8s world, maybe remove the character and replace with with a Kubernetes / OpenShift blob?

**Comment by zanetworker** [comment]
> Here are a few suggestions:

@c3d thanks for the feedback I will try to incorporate them. 

>  I don't know if it's at all feasible to show either something that talks directly to cri-o like crictl, or if you want to stick to the k8s world, maybe remove the character and replace with a Kubernetes / OpenShift blob?

In my case, since I added the Kubelet I consider it as the CRI client, which could be replaced with `crictl` or something else but it was meant as an example and also to relate to the Kubernetes world. 

It's not that far off if we speak about Kubernetes. The real flow is 1) create a pod, 2) scheduler picks it up, modify the pod with the node, 3) kubelet sees that change, recognizes its responsibility, and starts grinning.  Would replacing the solid line with a dotted one be okay?

**Comment by c3d** [comment]
On 2020-12-16 at 09:45 CET, Adel Zaalouk wrote...
>> Here are a few suggestions:
>
> @c3d thanks for the feedback I will try to incorporate them.
>
>>  I don't know if it's at all feasible to show either something that talks directly to cri-o like crictl, or if you want to stick to the k8s world, maybe remove the character and replace with a Kubernetes / OpenShift blob?
>
> In my case, since I added the Kubelet I consider it as the CRI client, which could be replaced with `crictl` or something else but it was meant as an example and also to relate to the Kubernetes world.
>
> It's not that far off if we speak about Kubernetes. The real flow is 1)
> create a pod, 2) scheduler picks it up, modify the pod with the node, 3)
> kubelet sees that change, recognizes its responsibility, and starts
> grinning.  Would replacing the solid line with a dotted one be okay?

I was not suggesting it was far off, but that the wetware is one step
further away, in that the non-binary entity typing at a keyboard would
typically talk to either kubectl, oc, or something like that, rather than to
the kubelet directly.


--
Cheers,
Christophe de Dinechin (IRC c3d)

**Comment by bergwolf** [comment]
One more suggest, please add these nice pictures to one of the existing docs so that they are actually referenced.

**Comment by zanetworker** [comment]
@bergwolf what would be a good place in your opinion?

**Comment by jodh-intel** [comment]
@zanetworker - Thanks for raising! I agree with @bergwolf. You could try either adding to:

- https://github.com/kata-containers/kata-containers/blob/2.0-dev/docs/design/architecture.md
- Or maybe you could create a new markdown doc just for these images and add a reference to *that* document to https://github.com/kata-containers/kata-containers/blob/2.0-dev/docs/design/README.md.

Other random thoughts:

- These images are quite big - I wonder if you could optimise the file size a bit? A quick test shows that ImageMagicking to JPG reduces the filesize from 2.2M to a more manageable 647K.
- Is that *really* what users look like? :fearful: :scream:

**Comment by fidencio** [comment]
I'm really sorry for the disruption but in order to do the branch name changes announced [here](http://lists.katacontainers.io/pipermail/kata-dev/2021-January/001695.html) I'm adding the "do-not-merge" and the "needs-branch-adjustment" labels to the PR.

I'll add a new comment once the branch changes are done and once it happens I'd like to ask you to resubmit the PR against the new `main` branch, possibly linking to this PR in case you find the conversations / reviews already made important to proceed.

**Comment by fidencio** [comment]
Kata Containers repos are back to business.  Thanks a lot for your patience and I'm very happy to announce that there's no changes needed from your side as renaming the branches automagically reflected here.

If you notice something weird, some missing CI, please, do not hesitate on contacting us here or on #kata-dev on bit.ly/katacontainersslack.

Also, this is a good opportunity to have your PR rebased atop of `main`, to ensure your PR follow all the guidelines (https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format) enforced by this community, or even to re-evaluate whether the PR is currently needed.

Last but not least,  as the default branch has been renamed to `main`, if you have a local clone you'd need to update it and you do so by running:
```
git branch -m 2.0-dev main
git fetch origin
git branch -u origin/main main
```

Happy hacking!

**Comment by jodh-intel** [comment]
Hi @zanetworker - Do you still think you could work on the tweaks mentioned above?

**Comment by zanetworker** [comment]
@jodh-intel will try to work on them soon.

**Comment by jodh-intel** [comment]
Thanks @zanetworker!

**Comment by zanetworker** [comment]
@jodh-intel tweaks re-worked.

**Comment by jodh-intel** [comment]
Thanks @zanetworker. But please could you reference the new markdown doc in one of the docs suggested in https://github.com/kata-containers/kata-containers/pull/1184#issuecomment-755266743? Currently, the CI is failing due to this:

```
ERROR: Document docs/design/end-to-end-flow.md is not referenced
```

**Comment by zanetworker** [comment]
@jodh-intel done.

**Review by jodh-intel — APPROVED** [review]
Thanks @zanetworker.

lgtm

**Pull request merged**
