### PR TITLE
volume cleanup, RO blk device support

### PR DESCRIPTION
**Pull request by egernst**
Backport from 2.0-dev

### CODE REVIEW

**Review by mxpv — APPROVED** [review]

**Comment by fidencio** [comment]
@kata-containers/redhat, please, take a look at the fedora-32-crio and fedora-32-crio-k8s-e2e-minimal failures: http://jenkins.katacontainers.io/job/kata-containers-2.0-fedora-PR/677/ and http://jenkins.katacontainers.io/job/kata-containers-2.0-fedora-PR-crio-k8s-e2e-minimal/101/

**Review by fidencio — APPROVED** [review]
looks reasonable to me!
I'd like to have @devimc's ack before you merge this one, though.

**Review by devimc — APPROVED** [review]
thanks @egernst

**Pull request merged**
