### PR TITLE
docs: use curl as default downloader for runtime-rs

### PR DESCRIPTION
**Pull request by Tim-0731-Hzt**
use curl as default downloader for runtime-rs @jodh-intel 

Fixes: #4879
Signed-off-by: Zhongtao Hu <zhongtaohu.tim@linux.alibaba.com>

### CODE REVIEW

**Review by liubin — APPROVED** [review]

**Comment by liubin** [comment]
@Tim-0731-Hzt can you change https://github.com/kata-containers/kata-containers/pull/4881/files#diff-5cde30498645ccfbe65ada42a2aa0678df8dcbac8ad647d86b568432eed8dce7L84 btw?

```diff
- $ make && make install
+ $ make && sudm make install

```

**Comment by Tim-0731-Hzt** [comment]
> @Tim-0731-Hzt can you change https://github.com/kata-containers/kata-containers/pull/4881/files#diff-5cde30498645ccfbe65ada42a2aa0678df8dcbac8ad647d86b568432eed8dce7L84 btw?
> 
> ```diff
> - $ make && make install
> + $ make && sudo make install
> ```

fixed

**Review by studychao — APPROVED** [review]

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
