### PR TITLE
osbuilder: Fix the order of checking the distro config directory

### PR DESCRIPTION
**Pull request by ManaSugi**
Check if the distro config directory exists before using the directory

Fixes: #2148

Signed-off-by: Manabu Sugimoto <Manabu.Sugimoto@sony.com>

### CODE REVIEW

**Review by liubin — APPROVED** [review]

**Comment by fidencio** [comment]
Please, rebase your PR atop of current main, as it'll need a fix included as part of https://github.com/kata-containers/kata-containers/pull/2127 (which just got merged).

Sorry for the inconvenience.

**Comment by ManaSugi** [comment]
I rebased it.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @ManaSugi!

**Review by amshinde — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Thanks @ManaSugi.

lgtm

**Comment by fidencio** [comment]
Howdy!

I'd like to ask you to rebase your PR atop of current `main`, as https://github.com/kata-containers/kata-containers/pull/2197 has been merged and it has a fix that unblocks the CI.

Please, do the rebase and feel free `@fidencio` in case you do not have the powers to run `/test`.

Sorry for the inconvenience and happy hacking!

**Comment by ManaSugi** [comment]
I rebased it. @fidencio

**Comment by fidencio** [comment]
Hey, we've had yet another breakage in our CI and now it's fixed as part of https://github.com/kata-containers/kata-containers/pull/2203 ... it means that you'll need to rebase your PR atop of current main.

Sorry for the inconvenience.

**Comment by ManaSugi** [comment]
I rebased @fidencio

**Pull request merged**
