### PR TITLE
ci: Reduce the size of the AKS VMs

### PR DESCRIPTION
**Pull request by fidencio**
We do **not** need a very powerful machine for our tests, as we're not building anything there.

The instance we switched to (Standard_D2s_v5) still has nested virt available, as shown here[0], but has half of the amount of vCPUs / Memory, which should be fine only for running the tests, costing us basically half of the price[1].

[0]:
https://learn.microsoft.com/en-us/azure/virtual-machines/dv5-dsv5-series [1]:
https://azure.microsoft.com/en-us/pricing/details/virtual-machines/linux/#pricing

Fixes: #7955

### CODE REVIEW

**Review by sprt — APPROVED** [review]
Approved pending CI

**Comment by sprt** [comment]
Is the configmap test failure new?

**Comment by fidencio** [comment]
> Is the configmap test failure new?

It fails due to the size of the instance, which only has 2 vCPUS.
I'm working on getting exactly which and how many tests will need a bigger instance, and we could split which tests will run on which instance ... still saving quite a bunch on our side.

WDYT?

**Comment by sprt** [comment]
@fidencio Great idea, thanks for this!

**Comment by sprt** [comment]
> It fails due to the size of the instance, which only has 2 vCPUS.

Oh I just noticed this - not familiar with this test but is the request required? https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/runtimeclass_workloads/inotify-configmap-pod.yaml#L19

**Comment by fidencio** [comment]
> > It fails due to the size of the instance, which only has 2 vCPUS.
> 
> Oh I just noticed this - not familiar with this test but is the request required? https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/runtimeclass_workloads/inotify-configmap-pod.yaml#L19

It is. :-)

**Comment by fidencio** [comment]
> > > It fails due to the size of the instance, which only has 2 vCPUS.
> > 
> > 
> > Oh I just noticed this - not familiar with this test but is the request required? https://github.com/kata-containers/kata-containers/blob/main/tests/integration/kubernetes/runtimeclass_workloads/inotify-configmap-pod.yaml#L19
> 
> It is. :-)

No, it's not!!!

**Review by chavafg — APPROVED** [review]

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
