### PR TITLE
runtime: update runc and image-spec dependencies

### PR DESCRIPTION
**Pull request by bergwolf**
To address two depbot security warnings.

Fixes: #3475

### CODE REVIEW

**Comment by fidencio** [comment]
Tao, I am sorry, I missed this one and ended up opening a very similar PR: https://github.com/kata-containers/kata-containers/pull/3490, with its backport: https://github.com/kata-containers/kata-containers/pull/3491

The image-spec dependency will be automagically uipdated, I think, as soon as we pull in containerd 1.6.0, which should be released later Today.

**Comment by Bevisy** [comment]
> Tao, I am sorry, I missed this one and ended up opening a very similar PR: #3490, with its backport: #3491

@fidencio may not 3491, but #3492 :smile:

**Comment by fidencio** [comment]
> > Tao, I am sorry, I missed this one and ended up opening a very similar PR: #3490, with its backport: #3491
> 
> @fidencio may not 3491, but #3492 smile

Thanks, @Bevisy! :-)

**Comment by bergwolf** [comment]
@fidencio I think we should pin them instead of having multiple dependency versions in `go.sum`, which means we are still using the vulnerable code.

**Review by amshinde — APPROVED** [review]

**Comment by fidencio** [comment]
@bergwolf, can you rebase this atop of `main`?

**Comment by fidencio** [comment]
#3496 is now merged and the breakage should be fixed.

**Review by egernst — APPROVED** [review]

**Comment by bergwolf** [comment]
ARM CI looks very unstable. @jongwu could you take a look? Failing most of times in the last 30-ish runs. 

> 15:34:37 [kubelet-check] It seems like the kubelet isn't running or healthy.
15:34:37 [kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.

@fidencio @GabyCT should it be removed from the required CI jobs for now?

**Comment by jongwu** [comment]
> ARM CI looks very unstable. @jongwu could you take a look? Failing most of times in the last 30-ish runs.
> 
> > 15:34:37 [kubelet-check] It seems like the kubelet isn't running or healthy.
> > 15:34:37 [kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp [::1]:10248: connect: connection refused.
> 
> @fidencio @GabyCT should it be removed from the required CI jobs for now?

Sorry for the trouble.
For now, I have not caught the root cause of this error. I only see this error in "arm01". I shutdown the "arm01" so all the ci jobs will deploy to "arm02" and "arm03". If it doesn't work, we can take Arm CI off the "Require List". I will fix it when I have the time.

**Comment by bergwolf** [comment]
@jongwu Thanks for taking care of it! I see ARM CI now works!

**Pull request merged**
