### PR TITLE
packaging: Remove skopeo & umoci

### PR DESCRIPTION
**Pull request by stevenhorsman**
- Remove skopeo and umoci from the CC image

Fixes: #4889
Signed-off-by: stevenhorsman <steven@uk.ibm.com>

### CODE REVIEW

**Comment by wainersm** [comment]
Very good @stevenhorsman !

I've only one question: does it break the build if it doesn't even export SKOPEO/UMOCI inside the container (see https://github.com/kata-containers/kata-containers/blob/CCv0/tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh#L46)?

**Comment by sameo** [comment]
That's very nice, thanks a lot @stevenhorsman !

**Comment by stevenhorsman** [comment]
> Very good @stevenhorsman !
> 
> I've only one question: does it break the build if it doesn't even export SKOPEO/UMOCI inside the container (see https://github.com/kata-containers/kata-containers/blob/CCv0/tools/packaging/kata-deploy/local-build/kata-deploy-binaries-in-docker.sh#L46)?

I don't think so, I ran the deploy payload build and produced new image in quay.io: kata-containers-77176cd7b94ec1a8c7afba08e246e84ca21cd161, but I'll test that now.

**Comment by wainersm** [comment]
> So this removes skopeo/umoci from the guest image, but are we adding in `image-rs` somewhere? Currently there is code in [image_rpc.rs](https://github.com/kata-containers/kata-containers/blob/CCv0/src/agent/src/image_rpc.rs) that is expecting to use skopeo/umoci. Are we going to update that?

IIUC correctly image_rpc.rs conditionally run skopeo if it is present, otherwise fallback to image-rs. (e.g. https://github.com/kata-containers/kata-containers/blob/CCv0/src/agent/src/image_rpc.rs#L262). If we plan to keep that logic I would at least log a message saying it is using skopeo or not, because it can silently fool one.

image-rs is statically linked with the agent binary: https://github.com/kata-containers/kata-containers/blob/CCv0/src/agent/Cargo.toml#L71

**Review by wainersm — APPROVED** [review]

**Comment by wainersm** [comment]
The payload built with this change pass the non-TEE tests on operator CI: https://github.com/confidential-containers/operator/pull/88

**Comment by wainersm** [comment]
@stevenhorsman I still see umoci installed in the kata image:
```
vagrant@ubuntu2004:/opt/confidential-containers/share/kata-containers/kata-image$ sudo ls usr/local/bin/
attestation-agent  umoci
vagrant@ubuntu2004:/opt/confidential-containers/share/kata-containers/kata-image$ sudo ls -l usr/local/bin/umoci 
-rwxr-xr-x 1 root root 10374009 Sep 20 14:31 usr/local/bin/umoci
vagrant@ubuntu2004:/opt/confidential-containers/share/kata-containers/kata-image$ sudo file usr/local/bin/umoci 
usr/local/bin/umoci: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=zCs8TmyGL13uQjKadnlx/jgoUI5ypG8pcrgW9ug7I/w0_k3K32PKmQommDoMJd/pdY0eYssmAtEK2S0Jyfu, not stripped
```

**Comment by fitzthum** [comment]
> IIUC correctly image_rpc.rs conditionally run skopeo if it is present, otherwise fallback to image-rs. 

Ah yes, I was just looking at the `pull_image_from_registry` method, which relies on `skopeo` but I guess there is a switch in `pull_image`.

**Comment by wainersm** [comment]
> @stevenhorsman I still see umoci installed in the kata image:
> 
> ```
> vagrant@ubuntu2004:/opt/confidential-containers/share/kata-containers/kata-image$ sudo ls usr/local/bin/
> attestation-agent  umoci
> vagrant@ubuntu2004:/opt/confidential-containers/share/kata-containers/kata-image$ sudo ls -l usr/local/bin/umoci 
> -rwxr-xr-x 1 root root 10374009 Sep 20 14:31 usr/local/bin/umoci
> vagrant@ubuntu2004:/opt/confidential-containers/share/kata-containers/kata-image$ sudo file usr/local/bin/umoci 
> usr/local/bin/umoci: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=zCs8TmyGL13uQjKadnlx/jgoUI5ypG8pcrgW9ug7I/w0_k3K32PKmQommDoMJd/pdY0eYssmAtEK2S0Jyfu, not stripped
> ```

ok, skopeo/umoci is installed on the guest rootfs so that, on build time, it will pull and unpack the pause image (see  75b9f3fa3caaae62f49b4733f65cbab0cc87dbee). Perhaps we can delete them afterwards?

**Review by fitzthum — APPROVED** [review]
LGTM. Seems like this doesn't break the SEV stuff either.

**Comment by stevenhorsman** [comment]
> @stevenhorsman I still see umoci installed in the kata image:
> 
> ```
> vagrant@ubuntu2004:/opt/confidential-containers/share/kata-containers/kata-image$ sudo ls usr/local/bin/
> attestation-agent  umoci
> vagrant@ubuntu2004:/opt/confidential-containers/share/kata-containers/kata-image$ sudo ls -l usr/local/bin/umoci 
> -rwxr-xr-x 1 root root 10374009 Sep 20 14:31 usr/local/bin/umoci
> vagrant@ubuntu2004:/opt/confidential-containers/share/kata-containers/kata-image$ sudo file usr/local/bin/umoci 
> usr/local/bin/umoci: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=zCs8TmyGL13uQjKadnlx/jgoUI5ypG8pcrgW9ug7I/w0_k3K32PKmQommDoMJd/pdY0eYssmAtEK2S0Jyfu, not stripped
> ```

Yes,

Sorry I noticed a couple of weeks ago that in rootfs.sh any `AA_KBC` being set pulls in `umoci`. I don't think that is needed any more, so after this change I think we should make a new PR to stop that happening.

**Pull request merged**
