### PR TITLE
docs: fix broken links

### LINKED ISSUE #826: docs: failed to find heading for link "supported-distributions"
FATA[0000] file="docs/install/README.md": failed to find heading for link "supported-distributions" ({Doc:docs/install/README.md Address:supported-distributions ResolvedPath: Description:Supported Distributions Type:internal-link})  commit=874194ca413219d5d6f85c4c68a958bdf4b5c53b name=kata-check-markdown pid=21260 source=check-markdown version=0.0.1

traviThe command "ci/static-checks.sh" exited with 1.
cache.2

store build cache

### PR DESCRIPTION
**Pull request by devimc**
Some sections and files were removed in a previous commit,
remove all reference to such sections and files to fix the
check-markdown test.

fixes #826

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by fidencio** [comment]
Oops, sorry!

**Review by fidencio — APPROVED** [review]
lgtm!
Again, sorry for the breakage.

**Comment by devimc** [comment]
@fidencio  np :smile: 

/test

**Review by cmaf — APPROVED** [review]
lgtm @devimc

**Review by jodh-intel — APPROVED** [review]
Thanks @devimc!

What worries me is how the previous changes passed the checkcommits test...?

**Comment by fidencio** [comment]
> Thanks @devimc!
> 
> What worries me is how the previous changes passed the checkcommits test...?

@jodh-intel, my guess is that it's related to the issue fixed by https://github.com/kata-containers/kata-containers/pull/811

**Comment by bergwolf** [comment]
somehow `jenkins-ci-ubuntu-1804-cloud-hypervisor-k8s-containerd-2.0 ` and `jenkins-ci-ubuntu-1804-containerd-k8s-e2e-minimal` are not triggered?

**Comment by bergwolf** [comment]
Somehow the two tests cannot be triggered but they are marked required to block merges. @likebreath @jcvenegas @GabyCT could you help take a look?

image

**Review by GabyCT — APPROVED** [review]

**Comment by likebreath** [comment]
> Somehow the two tests cannot be triggered but they are marked required to block merges. @likebreath @jcvenegas @GabyCT could you help take a look?
> 
> image

The issue now is being fixed. The reason was that we put `*.md` in the `Excluded regions` in the Jenkin's configuration for the two CI jobs, which literally means we won't run these CI jobs if changes are only from `*.md`... 

New things learnt for me. If this is not the ideal way to fix the issue, please let me know. @GabyCT @chavafg

**Comment by amshinde** [comment]
> The issue now is being fixed. The reason was that we put `*.md` in the `Excluded regions` in the Jenkin's configuration for the two CI jobs, which literally means we won't run these CI jobs if changes are only from `*.md`...

It makes sense to not run those jobs on doc changes, but I dont think we have a way to make them as non-required on a case-by-case basis in github. Will let @GabyCT @chavafg confirm.

**Comment by chavafg** [comment]
@amshinde is right. 
I think the best would be to make sure our https://github.com/kata-containers/tests/blob/2.0-dev/.ci/ci-fast-return.sh works correctly, so that it doesn't run the whole test suite when there are only documentation changes. 
There is already an open issue for this: https://github.com/kata-containers/tests/issues/2365, but we haven't had the chance to take a look at it. If someone has the chance to jump into it, it would be great.

**Pull request merged**
