### PR TITLE
runtime-rs: merge from main into runtime-rs branch

### PR DESCRIPTION
**Pull request by jiangliu**
Merge from main into runtime-rs branch to pull in the directory structure related changes.

### CODE REVIEW

**Comment by bergwolf** [comment]
`error: pathspec 'runtime-rs' did not match any file(s) known to git`
Looks like we need a runtime-rs branch in the tests repo as well. I've created it there and added the same protection rule as `runtime-rs` branch in the kata-containers repo.

**Comment by liubin** [comment]
@jiangliu you may need [this](https://github.com/kata-containers/kata-containers/commit/0214eac4c58aff3ab37b541877cd9d4351a47869) to pass the commit message check.

**Comment by liubin** [comment]
close and reopen because the `move-linked-....` check can't be triggered:

image

**Review by bergwolf — APPROVED** [review]
Thanks!

**Review by liubin — APPROVED** [review]

**Pull request merged**
