### PR TITLE
build: remove unused variables from Makefile

### PR DESCRIPTION
**Pull request by littlejawa**
Fixes: #1003

Signed-off-by: Julien Ropé <jrope@redhat.com>

### CODE REVIEW

**Review by cmaf — COMMENTED** [review]
thanks @littlejawa, could you please add some details to the commit message so that it matches the patch format in our [guidelines](https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format)?

**Comment by littlejawa** [comment]
@cmaf thanks for the review. 
I've reworded the commit message - hope it's good now.

**Review by egernst — APPROVED** [review]

**Comment by egernst** [comment]
LGTM -- thanks @littlejawa

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
