### PR TITLE
CC | config: Add sev suffix to initrd

### PR DESCRIPTION
**Pull request by stevenhorsman**
- Add new sev initrd name and path to point to the correct name of the file built

Note: I added extensive notes on what I think the associated failures were in #5938, so please check that out for details.

Fixes: #5938
Signed-off-by: stevenhorsman <steven@uk.ibm.com>

### CODE REVIEW

**Comment by stevenhorsman** [comment]
FYI @UnmeshDeodhar - we are seeing the network issues here:
```
12:15:40 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
12:15:40 
12:15:40 E: The repository 'https://download.docker.com/linux/ubuntu focal Release' no longer has a Release file.
12:15:40 W: Target Packages (stable/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
12:15:40 W: Target Packages (stable/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
12:15:40 W: Target Translations (stable/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
12:15:40 W: Target Translations (stable/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
12:15:40 W: Target CNF (stable/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
12:15:40 W: Target CNF (stable/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
12:15:40 [install_kubernetes.sh:33] ERROR: chronic sudo -E apt update
12:15:40 [jenkins_job_build.sh:251] ERROR: ci/setup.sh
```

**Comment by stevenhorsman** [comment]
SEV tests failed again with network problems:
```
14:02:50 Purging configuration files for kubeadm (1.23.1-00) ...
14:02:50 dpkg: warning: while removing kubeadm, directory '/etc/systemd/system/kubelet.service.d' not empty so not removed
14:02:50 Purging configuration files for kubelet (1.23.1-00) ...
14:02:50 Warning: apt-key output should not be parsed (stdout is not a terminal)
14:02:53 OK
14:02:53 Ign:1 https://download.docker.com/linux/ubuntu focal InRelease
14:02:56 Err:2 https://download.docker.com/linux/ubuntu focal Release
14:02:56   Could not handshake: Error in the pull function. [IP: 65.8.158.64 443]
14:02:56 Hit:4 http://us.archive.ubuntu.com/ubuntu focal InRelease
14:02:56 Hit:5 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease
14:02:56 Hit:3 https://packages.cloud.google.com/apt kubernetes-xenial-unstable InRelease
14:02:56 Hit:6 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease
14:02:56 Hit:7 http://us.archive.ubuntu.com/ubuntu focal-security InRelease
14:02:56 Reading package lists...
14:02:56 
14:02:56 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
14:02:56 
14:02:56 E: The repository 'https://download.docker.com/linux/ubuntu focal Release' no longer has a Release file.
14:02:56 W: Target Packages (stable/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
14:02:56 W: Target Packages (stable/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
14:02:56 W: Target Translations (stable/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
14:02:56 W: Target Translations (stable/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
14:02:56 W: Target CNF (stable/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
14:02:56 W: Target CNF (stable/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
14:02:56 [install_kubernetes.sh:33] ERROR: chronic sudo -E apt update
```

**Review by fitzthum — APPROVED** [review]
LGTM

**Review by fidencio — APPROVED** [review]
lgtm, thanks @stevenhorsman!

**Comment by stevenhorsman** [comment]
@ryansavino - we're hitting out of space on the amd milan node. Can you help with this please?:
```
09:20:02 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to amd-milan-coco-ci-ubuntu2004-001
09:20:02 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1784)
09:20:02 		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:356)
09:20:02 		at hudson.remoting.Channel.call(Channel.java:1000)
09:20:02 		at hudson.FilePath.act(FilePath.java:1194)
09:20:02 		at hudson.FilePath.act(FilePath.java:1183)
09:20:02 		at hudson.FilePath.mkdirs(FilePath.java:1374)
09:20:02 		at hudson.model.AbstractProject.checkout(AbstractProject.java:1211)
09:20:02 		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:647)
09:20:02 		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:85)
09:20:02 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:519)
09:20:02 		at hudson.model.Run.execute(Run.java:1897)
09:20:02 		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:44)
09:20:02 		at hudson.model.ResourceController.execute(ResourceController.java:101)
09:20:02 		at hudson.model.Executor.run(Executor.java:442)
09:20:02 java.nio.file.FileSystemException: /home/jenkins/workspace/kata-containers-CCv0-ubuntu-20.04_sev-x86_64-CC_SEV_CRI_CONTAINERD_K8S-PR: No space left on device
```

**Comment by ryansavino** [comment]
cleaned up the drive. I should have more storage added this week.

**Comment by stevenhorsman** [comment]
The apt update command failed:
```
Reading package lists...
17:19:06 W: Target Packages (stable/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
17:19:06 W: Target Packages (stable/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
17:19:06 W: Target Translations (stable/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
17:19:06 W: Target Translations (stable/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
17:19:06 W: Target CNF (stable/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
17:19:06 W: Target CNF (stable/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
17:19:06 E: The repository 'http://apt.kubernetes.io/ kubernetes-xenial-unstable Release' no longer has a Release file.
17:19:06 W: Target Packages (stable/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
17:19:06 W: Target Packages (stable/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
17:19:06 W: Target Translations (stable/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
17:19:06 W: Target Translations (stable/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
17:19:06 W: Target CNF (stable/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
17:19:06 W: Target CNF (stable/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list:50 and /etc/apt/sources.list.d/docker.list:1
17:19:06 [setup_env_ubuntu.sh:15] ERROR: sudo -E apt update
17:19:06 [jenkins_job_build.sh:251] ERROR: ci/setup.sh
17:19:06 ++ handle_error 91
17:19:06 ++ local exit_code=100
17:19:06 ++ local line_number=91
```

**Pull request merged**
