### PR TITLE
runtime: use github.com/mdlayher/vsock@v1.1.0

### LINKED ISSUE #3625: runtime: github.com/mdlayher/vsock v1.0.0 is now available
**Which feature do you think can be improved?**

The Kata runtime package.

**How can it be improved?**

Upgrade to the stable release of github.com/mdlayher/vsock.

**Additional Information**

n/a

**Before raising this enhancement request**

n/a

### PR DESCRIPTION
**Pull request by mdlayher**
Fixes #3625
Signed-off-by: Matt Layher <mdlayher@gmail.com>

Hi all! I know kata containers has been a longtime user of my vsock package, and I finally tagged v1.0.0 today!

https://github.com/mdlayher/vsock/releases/tag/v1.0.0

The code is much tidier now, but only supports Go 1.12+ as that is the minimum required version for every feature we need from Go's runtime network poller integration. As far as I can tell, your tests use Go 1.16+ so that should be fine.

There is a slight breaking API change to enable future expansion via an optional Config parameter (perhaps for network namespaces, timeouts, etc.) so I've adjusted the code for that.

Thanks all!

### CODE REVIEW

**Comment by egernst** [comment]
Awesome to receive this PR - thanks!

**Comment by mdlayher** [comment]
Looking at the CI builds, I see a couple hitting HTTP 503s. But this is interesting:

```
thread 'container::tests::test_execute_hook_with_error' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', rustjail/src/container.rs:1532:14
```

I ran into a transient `EPIPE` in my own CI so I suspect this is the Rust side communicating with my Go library over vsock? I wonder if something has changed and I need to consume this error under certain conditions in Go. But since I am not touching the Rust side of things, I'm curious if you all have any input too.

**Comment by mdlayher** [comment]
For context: on the Go side, I ran into this when exercising my CloseRead/CloseWrite APIs which wrap the `shutdown(2)` system call:

```go
	// Any write to a read-closed connection should return EPIPE.
	//
	// TODO(mdlayher): this test was flappy until err != nil check was added;
	// sometimes it returns EPIPE and sometimes it does not. Check this.
	<-readClosed
	if _, err := vc1.Write(b); err != nil && !isBrokenPipe(err) {
		t.Fatalf("expected vc1.Write broken pipe, but got: %v", err)
	}
```

**Comment by sameo** [comment]
> Looking at the CI builds, I see a couple hitting HTTP 503s. But this is interesting:
> 
> ```
> thread 'container::tests::test_execute_hook_with_error' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', rustjail/src/container.rs:1532:14
> ```
> 
> I ran into a transient `EPIPE` in my own CI so I suspect this is the Rust side communicating with my Go library over vsock? I wonder if something has changed and I need to consume this error under certain conditions in Go. But since I am not touching the Rust side of things, I'm curious if you all have any input too.

Thanks a lot for the PR @mdlayher 
This is more likely a flake, I kicked the action to run again, let's see.

**Comment by mdlayher** [comment]
```
ls: cannot access '/run/vc/sbs': No such file or directory
Build timed out (after 30 minutes). Marking the build as aborted.
Build was aborted
```

From: http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-20.04-PR/1751/.

**Comment by mdlayher** [comment]
I've pushed v1.0.1 to incorporate a couple minor fixes.

**Comment by mdlayher** [comment]
And now a v1.1.0! Thanks. Should be the last one.

**Review by jodh-intel — APPROVED** [review]
Thanks @mdlayher !

lgtm

**Review by fidencio — APPROVED** [review]
lgtm, thanks @mdlayher!

I've re-triggered the GitHub actions as the failure was not related to your PR.

**Pull request merged**
