### PR TITLE
ci: Reorder webhook deployment

### PR DESCRIPTION
**Pull request by ldoktor**
in b9d88f74edc463dc14ef52135c592fbb6bd5c792 the `runtime_class` CM was added which overrides the one we previously set. Let's reorder our logic to first deploy webhook and then override the default CM in order to use the one we really want.

Since we need to change dirs we also have to use realpath to ensure the files are located well.

Related to: https://github.com/kata-containers/kata-containers/pull/10329

### CODE REVIEW

**Comment by ldoktor** [comment]
@sprt @stevenhorsman @wainersm could you please take a look at this hotfix? It fixes the ocp CI (and here you have the answer to the question, do we test the webhook? ;-) )

**Review by sprt — APPROVED** [review]
Apologies @ldoktor - if this fixes an urgent issue for you I can approve this.

However I'm not intimately familiar with this code but looks like with #10329 we now have two configMaps that serve the same purpose? Is this something we should address?

**Comment by ldoktor** [comment]
The kata-webhook requires this CM to be set. Previously it was only mentioned somewhere in a readme file so CI scripts configured it but in #10329 a default "kata" type was added meaning applying the webhook overrides the previously set value.

This commit fixes it by first applying the webhook and only then overriding the expected value.

As for where this is used, we're running daily jobs to run a subset of openshift-tests e2e tests on OCP with kata-containers to ensure the basic functionality and cluster stability is kept ;-) So yes, it'd be appreciated if it can be merged soon.

**Review by Redent0r — APPROVED** [review]

**Review by stevenhorsman — APPROVED** [review]
As @sprt said it might be good to re-evaluate how the webhook runtime class is set and unify the approaches, but I'm happy to unblock this now.

**Pull request merged**
