### PR TITLE
runtime: fix a typo in kata-collect-data.sh

### PR DESCRIPTION
**Pull request by Kvasscn**
Fix a typo while to check if mountpoint exist.

Fixes: #3365

Signed-off-by: zhanghj <zhanghj.lc@inspur.com>

### CODE REVIEW

**Review by wainersm — APPROVED** [review]
Good catch. Looks good to me. Thanks @Kvasscn !

**Review by liubin — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Thanks @Kvasscn!

lgtm

btw, if you're keen, you might also want to look at:

- https://github.com/kata-containers/kata-containers/issues/1005
- https://github.com/kata-containers/kata-containers/issues/3047

**Pull request merged**
