### PR TITLE
Stable-3.0 | Upgrade to Cloud Hypervisor v28.0

### PR DESCRIPTION
**Pull request by likebreath**
This patch brings the first LTS release (v28.0) of Cloud Hypervisor to the stable-3.0 branch, which involves backporting a set of PRs, including #5311, #5493, #5584, #5597, #5684.

Signed-off-by: Bo Chen chen.bo@intel.com

### CODE REVIEW

**Review by cmaf — APPROVED** [review]

**Comment by likebreath** [comment]
Looks like the stable branch is failing on quite some CI jobs, which is also observed from the other PR [1]. I don't think these failures are related to the PR changes. 

[1] https://github.com/kata-containers/kata-containers/pull/5591

**Comment by jongwu** [comment]
@likebreath -, need backport https://github.com/kata-containers/kata-containers/pull/5669 to stable-3.0 to fix Arm CI failure.

**Comment by likebreath** [comment]
>  need backport #5669 to stable-3.0 to fix Arm CI failure.

@jongwu Thank you for the pointers.

@fidencio Looks like we need quite more backports to make stable-3.0 CI jobs happy, and I think these backports should be done in a separate PR. Given your broad coverage of Kata PRs in general, would you please take a look at the backporting issues for stable-3.0? Anything I can help with, please just ask. Thank you.

**Review by GabyCT — APPROVED** [review]

**Comment by fidencio** [comment]
https://github.com/kata-containers/kata-containers/pull/5669 may be too intrusive to backport to stable-3.0, as that updates some dependencies on the tests side as well.

Let's see if this is really needed or if we can get away without doing that.

@bergwolf, WDYT?

**Pull request merged**
