### PR TITLE
packaging/qemu: partial git clone

### LINKED ISSUE #3291: packaging/qemu: speed up the source cloning
**Which feature do you think can be improved?**

Clone of QEMU sources when performing a static-build:
```
cd kata-containers/tools/packaging
./static-build/qemu/build-static-qemu.sh
```

**How can it be improved?**

@Bevisy came up with that idea of not cloning the entire git tree in order tor reduce the tree size and speed up the operation. In https://github.com/kata-containers/kata-containers/pull/3109#discussion_r755263124 he suggested to use `--depth=1`.

I ran some tests locally with `--depth=1` and it indeed reduces a lot the time/size of git clone. However, because we (usually) don't build on master, an additional fetch (`git fetch VERSION`) is required and that takes longer too (although it speed up if compared with a full clone).

Then I tried with `--filter=tree:0` which won't fetch the tree and blob objects right away. Additional objects are fetched on `git checkout VERSION` and that is faster than `--depth=1`   

**Additional Information**

Compare `--depth=1` vs `--filter=tree:0`:

```
[wmoschet@wainer-laptop packaging]$ time bash -c 'version="v6.1.0"; git clone --depth=1 https://github.com/qemu/qemu qemu1 && cd qemu1 && git fetch origin $version && git checkout FETCH_HEAD'
Cloning into 'qemu1'...
remote: Enumerating objects: 9000, done.
remote: Counting objects: 100% (9000/9000), done.
remote: Compressing objects: 100% (7703/7703), done.
remote: Total 9000 (delta 1338), reused 3871 (delta 1018), pack-reused 0
Receiving objects: 100% (9000/9000), 32.35 MiB | 987.00 KiB/s, done.
Resolving deltas: 100% (1338/1338), done.
remote: Enumerating objects: 562740, done.
remote: Counting objects: 100% (562685/562685), done.
remote: Compressing objects: 100% (101890/101890), done.
remote: Total 556697 (delta 461255), reused 548712 (delta 453408), pack-reused 0
Receiving objects: 100% (556697/556697), 290.83 MiB | 1.10 MiB/s, done.
Resolving deltas: 100% (461255/461255), completed with 4597 local objects.
From https://github.com/qemu/qemu
 * tag                     v6.1.0     -> FETCH_HEAD
Note: switching to 'FETCH_HEAD'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at f9baca549e Update version for v6.1.0 release

real	5m39.725s
user	1m11.771s
sys	0m12.811s
[wmoschet@wainer-laptop packaging]$ time bash -c 'version="v6.1.0"; git clone --filter=tree:0 https://github.com/qemu/qemu qemu2 && cd qemu2 && git checkout $version'
Cloning into 'qemu2'...
remote: Enumerating objects: 96132, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 96132 (delta 0), reused 1 (delta 0), pack-reused 96131
Receiving objects: 100% (96132/96132), 39.21 MiB | 1016.00 KiB/s, done.
Resolving deltas: 100% (14802/14802), done.
remote: Enumerating objects: 583, done.
remote: Counting objects: 100% (322/322), done.
remote: Compressing objects: 100% (322/322), done.
remote: Total 583 (delta 0), reused 0 (delta 0), pack-reused 261
Receiving objects: 100% (583/583), 271.14 KiB | 1.79 MiB/s, done.
remote: Enumerating objects: 8416, done.
remote: Counting objects: 100% (5345/5345), done.
remote: Compressing objects: 100% (4809/4809), done.
remote: Total 8416 (delta 872), reused 536 (delta 536), pack-reused 3071
Receiving objects: 100% (8416/8416), 32.08 MiB | 991.00 KiB/s, done.
Resolving deltas: 100% (1354/1354), done.
Updating files: 100% (8720/8720), done.
remote: Enumerating objects: 570, done.
remote: Counting objects: 100% (288/288), done.
remote: Compressing objects: 100% (288/288), done.
remote: Total 570 (delta 0), reused 0 (delta 0), pack-reused 282
Receiving objects: 100% (570/570), 263.85 KiB | 928.00 KiB/s, done.
remote: Enumerating objects: 1586, done.
remote: Counting objects: 100% (1207/1207), done.
remote: Compressing objects: 100% (1173/1173), done.
remote: Total 1586 (delta 93), reused 34 (delta 34), pack-reused 379
Receiving objects: 100% (1586/1586), 8.86 MiB | 972.00 KiB/s, done.
Resolving deltas: 100% (124/124), done.
Updating files: 100% (2012/2012), done.
Note: switching to 'v6.1.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at f9baca549 Update version for v6.1.0 release

real	1m37.105s
user	0m13.234s
sys	0m3.568s

```

### PR DESCRIPTION
**Pull request by wainersm**
This PR changes the method to clone the QEMU source tree in order to speed up its build. It is used the `--depth=1` argument of `git` to fetch just the needed objects.

While here I change the way that the submodules are cloned. 

Fixes #3291

### CODE REVIEW

**Comment by wainersm** [comment]
@Bevisy here is :)

@gkurz mind to review it? In special the commit https://github.com/kata-containers/kata-containers/pull/3302/commits/2938bb7f892483f0674e16baa00a5a3702d8dbe0 which I suspect we don't need to clone the submodules at all because QEMU's configure does it automatically. Am I right?

**Review by Bevisy — APPROVED** [review]
lgtm

**Review by devimc — APPROVED** [review]
lgtm - thanks  @wainersm

**Comment by wainersm** [comment]
The failed build (http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-PR-x86_64-clh-crio-kata-repo/1656/) seems not related with this PR. I will re-run the test.

/test-clh

**Review by bergwolf — APPROVED** [review]

**Comment by gkurz** [comment]
> @Bevisy here is :)
> 
> @gkurz mind to review it? In special the commit [2938bb7](https://github.com/kata-containers/kata-containers/commit/2938bb7f892483f0674e16baa00a5a3702d8dbe0) which I suspect we don't need to clone the submodules at all because QEMU's configure does it automatically. Am I right?

Hi @wainersm ! Covid made me a bit late on this one, sorry. 

> @Bevisy here is :)
> 
> @gkurz mind to review it? In special the commit [2938bb7](https://github.com/kata-containers/kata-containers/commit/2938bb7f892483f0674e16baa00a5a3702d8dbe0) which I suspect we don't need to clone the submodules at all because QEMU's configure does it automatically. Am I right?

Yes, upstream QEMU's configure does that automatically AFAIK.

**Pull request merged**
