### PR TITLE
stable-2.2 | virtcontainers: clh: Upgrade to the openapi-generator v5.2.1 

### PR DESCRIPTION
**Pull request by likebreath**
This PR backports PR #2488: virtcontainers: clh: Upgrade to the openapi-generator v5.2.1

### CODE REVIEW

**Comment by fidencio** [comment]
> @fidencio Please let me know whether stable-2.2 is the right branch for backporting. Thank you.
> 
> /test

@likebreath, I think we want this as part of stable-2.2 and possibly also as part of stable-2.1.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @likebreath!

**Comment by Jakob-Naucke** [comment]
@likebreath if you care about getting s390x green you should rebase

**Review by GabyCT — APPROVED** [review]

**Comment by fidencio** [comment]
```
time="2021-08-30T14:43:09-04:00" level=error msg="unable to delete test" error="cannot find init process!: unknown"
ctr: cannot find init process!: unknown
[default_vcpus_test.sh:173] ERROR: sudo ctr run --runtime=io.containerd.kata.v2 -d quay.io/prometheus/busybox:latest test sh -c nproc | grep 4
make: *** [Makefile:155: vcpus] Error 1
[run.sh:44] ERROR: sudo -E PATH=/home/jenkins/workspace/kata-containers-2.0-ubuntu-s390x-PR/go/bin:/usr/local/go/bin:/usr/sbin:/sbin:/home/jenkins/workspace/kata-containers-2.0-ubuntu-s390x-PR/go/bin:/usr/local/go/bin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin CRI_RUNTIME=containerd bash -c make vcpus
[jenkins_job_build.sh:193] ERROR: ci/run.sh
Build step 'Execute shell' marked build as failure
```

@Jakob-Naucke, mind to take a look?

**Comment by likebreath** [comment]
> if you care about getting s390x green you should rebase

@Jakob-Naucke I believe the PR was already rebased to the latest from stable-2.2 branch.

**Comment by fidencio** [comment]
> ```
> time="2021-08-30T14:43:09-04:00" level=error msg="unable to delete test" error="cannot find init process!: unknown"
> ctr: cannot find init process!: unknown
> [default_vcpus_test.sh:173] ERROR: sudo ctr run --runtime=io.containerd.kata.v2 -d quay.io/prometheus/busybox:latest test sh -c nproc | grep 4
> make: *** [Makefile:155: vcpus] Error 1
> [run.sh:44] ERROR: sudo -E PATH=/home/jenkins/workspace/kata-containers-2.0-ubuntu-s390x-PR/go/bin:/usr/local/go/bin:/usr/sbin:/sbin:/home/jenkins/workspace/kata-containers-2.0-ubuntu-s390x-PR/go/bin:/usr/local/go/bin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin CRI_RUNTIME=containerd bash -c make vcpus
> [jenkins_job_build.sh:193] ERROR: ci/run.sh
> Build step 'Execute shell' marked build as failure
> ```
> 
> @Jakob-Naucke, mind to take a look?

Oh, and I had missed https://github.com/kata-containers/kata-containers/pull/2525#issuecomment-908504377, sorry.

I think we can merge it as it is and avoid running the whole set of tests again.

**Pull request merged**
