### PR TITLE
tools: Make agent-ctl support more APIs

### PR DESCRIPTION
**Pull request by jodh-intel**
Added new `agent-ctl` commands to allow the following agent API calls to be made:

- `AddARPNeighborsRequest`
- `CloseStdinRequest`
- `CopyFileRequest`
- `GetMetricsRequest`
- `GetOOMEventRequest`
- `MemHotplugByProbeRequest`
- `OnlineCPUMemRequest`
- `ReadStreamRequest`
- `ReseedRandomDevRequest`
- `SetGuestDateTimeRequest`
- `TtyWinResizeRequest`
- `UpdateContainerRequest`
- `WriteStreamRequest`

Also did some tidy-up, and added more debug and better docs.

Fixes: #969.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
The `agent-ctl` tool has found some interesting bugs recently (see #965), so please can folks try running it and seeing what they can do!

`cargo run -- examples` shows lots more ideas :)

**Comment by jodh-intel** [comment]
Ping for review :smile:

**Review by devimc — APPROVED** [review]

**Comment by amshinde** [comment]
ping @lifupan @bergwolf

**Review by bergwolf — APPROVED** [review]

**Pull request merged**
