### PR TITLE
virtcontainers: Split the rootless package into OS specific parts

### PR DESCRIPTION
**Pull request by egernst**
Move the netns specific bits into a Linux specific file.

Fixes: #3607

Signed-off-by: Samuel Ortiz <s.ortiz@apple.com>
Signed-off-by: Eric Ernst <eric_ernst@apple.com>

### CODE REVIEW

**Review by sameo — APPROVED** [review]

**Review by devimc — APPROVED** [review]
lgtm - uhmm :thinking: .. darwin support is coming... ?

**Comment by egernst** [comment]
centos and s390x are failing with unrelated issues. Restarted the ARM CI - appears to be a flake with downloading alpine image.

**Pull request merged**
