### PR TITLE
kernel: Add caching of kernel-headers

### PR DESCRIPTION
**Pull request by zvonkok**
Fixes: #9481

We need to cache the kernel-headers for the NVIDIA GPU initrd/image build.

### CODE REVIEW

**Review by BbolroC — APPROVED** [review]
LGTM, thanks @zvonkok !

**Comment by fidencio** [comment]
```
⋊> kata-containers on kernel-headers-tarball ≡ tar tf build/kata-static-kernel-nvidia-gpu.tar.xz 
./
./opt/
./opt/kata/
./opt/kata/share/
./opt/kata/share/kata-containers/
./opt/kata/share/kata-containers/vmlinuz-6.1.62-128-nvidia-gpu
./opt/kata/share/kata-containers/vmlinux-6.1.62-128-nvidia-gpu
./opt/kata/share/kata-containers/config-6.1.62-128-nvidia-gpu
./opt/kata/share/kata-containers/vmlinuz-nvidia-gpu.container
./opt/kata/share/kata-containers/vmlinux-nvidia-gpu.container

⋊> kata-containers on kernel-headers-tarball ≡ tar tf build/kata-static-kernel-nvidia-gpu-headers.tar.xz 
./linux-headers-6.1.62-nvidia-gpu_6.1.62-nvidia-gpu-2_amd64.deb
./linux-libc-dev_6.1.62-nvidia-gpu-2_amd64.deb
./linux-image-6.1.62-nvidia-gpu_6.1.62-nvidia-gpu-2_amd64.deb
`` `

**Comment by fidencio** [comment]
```
⋊> kata-containers on kernel-headers-tarball ≡ tar tf build/kata-static-kernel-nvidia-gpu-confidential-modules.tar.xz 
./
./kernel/
./kernel/drivers/
./kernel/drivers/virt/
./kernel/drivers/virt/coco/
./kernel/drivers/virt/coco/efi_secret/
./kernel/drivers/virt/coco/efi_secret/efi_secret.ko
./modules.order
./modules.builtin
./modules.builtin.modinfo
./modules.dep
./modules.dep.bin
./modules.alias
./modules.alias.bin
./modules.softdep
./modules.symbols
./modules.symbols.bin
./modules.builtin.bin
./modules.builtin.alias.bin
./modules.devname

⋊> kata-containers on kernel-headers-tarball ≡ tar tf build/kata-static-kernel-nvidia-gpu-confidential-headers.tar.xz 
./linux-image-6.7.0-nvidia-gpu-confidential_6.7.0-2_amd64.deb
./linux-libc-dev_6.7.0-2_amd64.deb
./linux-headers-6.7.0-nvidia-gpu-confidential_6.7.0-2_amd64.deb
```

**Review by fidencio — APPROVED** [review]
lgtm, thanks @zvonkok!

**Comment by fidencio** [comment]
@zvonkok, please, also bump https://github.com/kata-containers/kata-containers/blob/main/tools/packaging/kernel/kata_config_version

It seems a new build is not being triggered, and that's not your PR's fault.  So, just bump that file and it'll ensure a new kernel build will  be trigerred, instead of trying to use the cache (which yet doesn't contain the kernel-headers).

**Pull request merged**
