### PR TITLE
src: Fixed typo mod.rs

### PR DESCRIPTION
**Pull request by Christopher-C-Robinson**
Fixed the typo in comment in the delete method located in mod.rs file.

Fixes: #6256.

Signed-off-by: Christopher Robinson <christopher.cadiz.robinson@gmail.com>

### CODE REVIEW

**Review by Tim-0731-Hzt — APPROVED** [review]
Thanks @Christopher-C-Robinson

**Review by studychao — APPROVED** [review]
Thanks! @Christopher-C-Robinson

**Comment by jodh-intel** [comment]
Thanks @Christopher-C-Robinson! The CI is being picky I'm afraid as the author email address in your commit is different to your default GitHub email address. There are various ways to fix this, but I think something like this should work:

```bash
# Set your email address to the expected one
$ git config --global user.email christopher.cadiz.robinson@gmail.com

# Save the details of the current commit
$ git log -1|grep '^  '|sed 's/^ *//g' > /tmp/commit.log

# Undo your commit changes
$ git reset HEAD^

# Recreate the commit using your new email address
$ git commit -aF /tmp/commit.txt

# Update this PR
$ git push -f
```

**Pull request merged**
