### PR TITLE
stable-2.0 | build: Only keep one VERSION file

### PR DESCRIPTION
**Pull request by fidencio**
Instead of having different VERSION files spread accross the project,
let's always use the one in the topsrcdir and remove all the others,
keeping only a synlink to the topsrcdir one.

Fixes: #1579

Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>
(cherry picked from commit 572aff53e8a6996f1b95d062a53f4f7a1c660d30)

### CODE REVIEW

**Comment by fidencio** [comment]
https://github.com/kata-containers/kata-containers/pull/1659 fixes the travis-ci, so no need to block this one because of the travis-ci failures.

**Review by snir911 — APPROVED** [review]
Actually i find it a bit annoying when i pass a sub folder to a container (for building purposes) and i don't have the top dir version file, lgtm though :)

**Review by wainersm — APPROVED** [review]

**Pull request merged**
