### PR TITLE
Fix async problems

### PR DESCRIPTION
**Pull request by Tim-Zhang**
- Fix fork/child in execute_hook
- Close stdin in execute_hook after it was sent
- Add unittest test_execute_hook
- Remove unnecessary #[async_trait]
- Remove crate signal-hook which are no longer used
- Fix unit test test_process

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @Tim-Zhang.

lgtm

/cc @mxpv

**Review by lifupan — APPROVED** [review]

**Comment by egernst** [comment]
Thanks Tim! restarting failed ubuntu job...

**Review by mxpv — APPROVED** [review]

**Pull request merged**
