### PR TITLE
versions: Update to current Rust 1.56.1

### LINKED ISSUE #3061: Update to newer Rust version
# Description of problem

According to our `versions.yaml` we currently support Rust versions down to 1.45.0 (although the oldest our CI appears to actually use is 1.47.0, and that not in most places).  Since we already routinely get Rust via `rustup` rather than from distros, there's no compelling reason to keep compatibility with older Rust versions.

Current Rust (1.56.1) contains a number of features that are of potential benefit to us:

- Cargo support for rust versioning (the `package.rust-version` tag in `Cargo.toml`).  This will let the toolchain itself warn usefully about outdated Rust versions.
- Edition 2021 is now stabilized
- `str::split_once` is useful for parsing things in a number of places
- `HashMap<T>` now implements `From<[T; N]>` which can make several conversions less awkward (particularly in unit test cases)
- `[T; N]` now implements `IntoIterator<Item=T>` which is also useful for several loops (particularly in unit test cases)
-

### PR DESCRIPTION
**Pull request by dgibson**
This updates the Rust versions listed in versions.yaml, both the minimum
and latest listed, to 1.56.1.  This Rust version:

- stabilizes the 2021 Rust edition, allowing us to use new edition
  features when we're ready

- introduces a rust-version flag in the Cargo.toml which will allow
  better Rust compiler version management (since native tools will
  understand it, not just our own scripts)

- A number of useful standard library extensions

fixes #3061

Signed-off-by: David Gibson <david@gibson.dropbear.id.au>

### CODE REVIEW

**Comment by devimc** [comment]
I see an improvement in boot-times

```
02:08:37 time="2021-11-18T08:08:37Z" level=debug msg="Compare check for [boot-times]"
02:08:37 time="2021-11-18T08:08:37Z" level=debug msg="Checking value [mean]"
02:08:37 time="2021-11-18T08:08:37Z" level=debug msg=" Check minval (0.536000 < 0.524700)"
02:08:37 time="2021-11-18T08:08:37Z" level=warning msg="Failed Minval (0.536000 > 0.524700) for [boot-times]"
02:08:37 time="2021-11-18T08:08:37Z" level=debug msg=" Check maxval (0.737000 > 0.524700)"
```

let's /retest-ubuntu-metrics

**Review by devimc — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Thanks @dgibson.

lgtm

**Comment by dgibson** [comment]
@bergwolf @jodh-intel thanks for the acks, however, given the concern @fidencio raised [here](https://github.com/kata-containers/kata-containers/issues/3061#issuecomment-972615493), I'm putting this on indefinite hiatus.

**Comment by jodh-intel** [comment]
@dgibson - can we close this PR then?

**Comment by dgibson** [comment]
@jodh-intel yes.  I might look at this again, but I'll probably take a different approach.

**Comment by jodh-intel** [comment]
Thanks @dgibson. Closing this for now then...

**Pull request closed without merging**
