### PR TITLE
runtime: remove covertool from cli test

### PR DESCRIPTION
**Pull request by zhsj**
covertool has no active since 2018 and is not compatible with go1.16

```
  ../vendor/github.com/dlespiau/covertool/pkg/cover/cover.go:76:29: cannot use f (type dummyTestDeps) as type testing.testDeps in argument to testing.MainStart:
  dummyTestDeps does not implement testing.testDeps (missing SetPanicOnExit0 method)
```

Fixes: #1862

Signed-off-by: Shengjing Zhu <zhsj@debian.org>

### CODE REVIEW

**Comment by fidencio** [comment]
@zhsj, may I ask you to rebase this one atop of current `main`?  The static check is failing due to link that doesn't even exist as part of current `main`.

**Comment by fidencio** [comment]
(sorry, close and comment button are too close :-/)

**Review by jodh-intel — APPROVED** [review]
Thanks @zhsj.

lgtm

**Comment by jodh-intel** [comment]
We need another review over here y'all...!

**Review by fidencio — APPROVED** [review]
lgtm, thanks @zhsj!

**Pull request merged**
