### PR TITLE
cargo: Use latest nix crate for all Rust code bases

### LINKED ISSUE #2114: The nix crate version differs between all the kata rust code bases
We should make it run on the latest 0.21.0.

### PR DESCRIPTION
**Pull request by sameo**
Our dependencies already bring several versions of nix, we should avoid
adding even more fragementation.

Fixes #2114

Signed-off-by: Samuel Ortiz <samuel.e.ortiz@protonmail.com>

### CODE REVIEW

**Comment by fidencio** [comment]
@sameo:
```
Error: 

  fb6eeadbdc2df58c90f59db1dbd3b4f0ef53cf43    Failed to find subsystem in subject

See the document below for help on formatting commits for the project.

https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format
```

**Review by fidencio — APPROVED** [review]
lgtm, thanks @sameo!

Please, fix up the "component" part of the commit message and update the PR.

**Comment by sameo** [comment]
> lgtm, thanks @sameo!
> 
> Please, fix up the "component" part of the commit message and update the PR.

Fixed!

**Review by mxpv — APPROVED** [review]

**Pull request merged**
