### PR TITLE
runtime: Fix README link

### LINKED ISSUE #2612: Wrong license link in src/runtime/README.md
This should point to the root LICENSE file.

### PR DESCRIPTION
**Pull request by sameo**
The LICENSE file lives in the project's root.

Fixes #2612

Signed-off-by: Samuel Ortiz <s.ortiz@apple.com>

### CODE REVIEW

**Comment by fidencio** [comment]
@sameo, is it causing some test to fail?  If so, it also deserves a backport.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @sameo!

**Comment by sameo** [comment]
> @sameo, is it causing some test to fail? If so, it also deserves a backport.

@fidencio See https://github.com/kata-containers/kata-containers/pull/2332/checks?check_run_id=3584177629

**Comment by fidencio** [comment]
> > @sameo, is it causing some test to fail? If so, it also deserves a backport.
> 
> @fidencio See https://github.com/kata-containers/kata-containers/pull/2332/checks?check_run_id=3584177629

Then we should backport it to stable-2.2 as well.  Thanks!

**Comment by sameo** [comment]
> > > @sameo, is it causing some test to fail? If so, it also deserves a backport.
> > 
> > 
> > @fidencio See https://github.com/kata-containers/kata-containers/pull/2332/checks?check_run_id=3584177629
> 
> Then we should backport it to stable-2.2 as well. Thanks!

See #2614.

**Comment by sameo** [comment]
@amshinde Could you PTAL?

**Review by bergwolf — APPROVED** [review]

**Comment by fidencio** [comment]
> /retest-ubuntu

I had to call the retest as `jenkins-ci-ubuntu-20-04` is not kicking off.
/cc @GabyCT as we may need help to further investigate what may be happening.

**Pull request merged**
