### PR TITLE
CCv0: Merge main into CCv0

### PR DESCRIPTION
**Pull request by stevenhorsman**
Weekly merge of main branch content into CCv0

- A few merge conflicts due to `main` updating to `containerd 1.5.8` and `CCv0` updating to the `confidential-containers/ali-ccv0` version. Hopefully I managed to resolve them ok
- I then ran `make -C src/runtime handle_vendor` to update the vendor modules

Fixes: #3085

### CODE REVIEW

**Comment by wllenyj** [comment]
Thanks @stevenhorsman ,
Can we drop the commit `runtime: Update containerd to 1.5.8` ?

**Comment by sameo** [comment]
> Thanks @stevenhorsman , Can we drop the commit `runtime: Update containerd to 1.5.8` ?

@wllenyj This is an upstream commit. Your commit, updating to the ali-CCv0 branch is merged on top of it. `runtime/go.mod` shows:

```
github.com/containerd/containerd => github.com/confidential-containers/containerd v1.6.0-beta.0.0.20211116180256-99bbe62c8989
```

**Comment by sameo** [comment]
@stevenhorsman I wonder if we should consider rebasing the CCv0 patches on top of kata upstream? I know downstream CCv0 would have to reset, etc, but the commit history would be a lot cleaner imho.

**Comment by stevenhorsman** [comment]
> @stevenhorsman I wonder if we should consider rebasing the CCv0 patches on top of kata upstream? I know downstream CCv0 would have to reset, etc, but the commit history would be a lot cleaner imho.

Hi Samuel, that is the process I was doing up until 2 weeks ago, but people complained about it, and I was told to switch to merging in `main` into `CCv0` instead so it didn't impact downstream `CCv0` changes! I don't mind which, but I need consensus, or otherwise not do it at all and let the branches drifty

**Comment by sameo** [comment]
> > @stevenhorsman I wonder if we should consider rebasing the CCv0 patches on top of kata upstream? I know downstream CCv0 would have to reset, etc, but the commit history would be a lot cleaner imho.
> 
> Hi Samuel, that is the process I was doing up until 2 weeks ago, but people complained about it, and I was told to switch to merging in `main` into `CCv0` instead so it didn't impact downstream `CCv0` changes! I don't mind which, but I need consensus, or otherwise not do it at all and let the branches drift apart

Hi @stevenhorsman, thanks a lot for the PR. I definitely did not mean to **not** maintain that branch and let it drift, that would be the worst solution :-) I just wanted to open the discussion, I did not know that it already took place.

To me, rebasing has 2 advantages:

1. Cleaner git history
2. Easier/visual way to track all our pending patches

Just curious: Who was complaining about you rebasing that I should try to convince back ;-) ?

**Review by sameo — APPROVED** [review]

**Comment by stevenhorsman** [comment]
@sameo, hey Samuel,

I think it's a tricky decision. I think there are definitely pros of rebasing as you've said.

The other discussion about merging being the better approach was in your Agent API restriction PR #2658 (which as an aside I'd still like to see closed as I don't think it is required as it's all in the CCv0 branch).

I guess there are a few things to consider in the decision:
- How easy it is to do (this is definitely the least important as I don't want to optimise for me at the detriment to everyone else)
- How easy it is for others to cope with. This is where I observed and was told that the rebase method fell down. Frequently PRs wouldn't get re-based on `CCv0` after the `CCv0` rebase on `main` for a while while, which meant that they turned into a bit of a mess with conflicts and commits that didn't line up. I guess this is partly related to our PRs tending to have long lifetimes, so could get hit by several of the weekly re-base. Ideally if we could get into a pattern of frequently, smaller PRs that we can review and merge quicker that would help, but that is easier said than done!
There was also the complaint that a user couldn't do a `git pull` of the `CCv0` branch anymore without getting conflicts. If this is something we want to work, I'm not sure there is a mitigation with the 'rebase and force push' approach, but I'm far from being an expert.
- How easy it is to be confident that the merge/rebase contains all the changes required. As @wllenyj pointed out last week, we can technically remove all the merged conflicts, but still leave some code incompatibilities when foundational code used by a `CCv0` specific feature changes. Given that we can only run the CCv0 CI pipeline on PRs my approach to help this was to create this PR to ensure all tests passed (except the commit message checks for the `Merging ...` message) before it was merged. I'm not sure how easy this would be for a rebase scenario - I guess I could still create the PR and run the tests, but we couldn't merge it and would need to force push due to difference in commit history?
- How long we are going to do it for. I guess the question of if/when we aim to merge `CCv0` code back into the `main` branch has a baring on this decision as the longer it goes on the more differences we'll add up during the rebase which will add complications.

I'm sure there are other issues as well, but these are the ones I can think of immediately.

Sorry if I moved too swiftly on switching the process, I felt like the other conversation was one sided and the only disadvantage was more effort for me, but I didn't want to hold it up. I figured you would have been aware of it as the PR creator, but sorry if I've left important people out of the loop.

_This post got long and rambling, I hope it makes sense. Let me know if there is anything I can do to help with the process. In the mean time I guess I'll leave this PR un-merged._

**Comment by sameo** [comment]
> @sameo, hey Samuel,
> 
> I think it's a tricky decision. I think there are definitely pros of rebasing as you've said.
> 
> The other discussion about merging being the better approach was in your Agent API restriction PR #2658 (which as an aside I'd still like to see closed as I don't think it is required as it's all in the CCv0 branch).
> 

Ah sorry about that. It's closed now.

> I guess there are a few things to consider in the decision:
> 
>     * How easy it is to do (this is definitely the least important as I don't want to optimise for me at the detriment to everyone else)
> 
>     * How easy it is for others to cope with. This is where I observed and was told that the rebase method fell down. Frequently PRs wouldn't get re-based on `CCv0` after the `CCv0` rebase on `main` for a while while, which meant that they turned into a bit of a mess with conflicts and commits that didn't line up. I guess this is partly related to our PRs tending to have long lifetimes, so could get hit by several of the weekly re-base. Ideally if we could get into a pattern of frequently, smaller PRs that we can review and merge quicker that would help, but that is easier said than done!
>       There was also the complaint that a user couldn't do a `git pull` of the `CCv0` branch anymore without getting conflicts. If this is something we want to work, I'm not sure there is a mitigation with the 'rebase and force push' approach, but I'm far from being an expert.
> 

My take is that  `CCv0` is a development branch, and it makes sense to merge `main` into it periodically if we ever plan to send a `CCv0` PR back at some point, containing *most* CC related patches. If we're planning to feed `main` with `CCv0` patches in small batches, then things may become painful when merging `main` back if it contains modified/corrected versions of CCv0 patches that got approved and merged.

>     * How easy it is to be confident that the merge/rebase contains all the changes required. As @wllenyj pointed out last week, we can technically remove all the merged conflicts, but still leave some code incompatibilities when foundational code used by a `CCv0` specific feature changes. Given that we can only run the CCv0 CI pipeline on PRs my approach to help this was to create this PR to ensure all tests passed (except the commit message checks for the `Merging ...` message) before it was merged. I'm not sure how easy this would be for a rebase scenario - I guess I could still create the PR and run the tests, but we couldn't merge it and would need to force push due to difference in commit history?
> 

That's a good point. I'm not sure we could run the CI if there would be merge conflicts and there would be some if we rebase on top of `main`

>     * How long we are going to do it for. I guess the question of if/when we aim to merge `CCv0` code back into the `main` branch has a baring on this decision as the longer it goes on the more differences we'll add up during the rebase which will add complications.
> 

I guess it would make sense to start pushing code upstream once we have a working CCv0 branch, i.e. something that works e2e while supporting the non CC use cases.


> I'm sure there are other issues as well, but these are the ones I can think of immediately.
> 
> Sorry if I moved too swiftly on switching the process, I felt like the other conversation was one sided and the only disadvantage was more effort for me, but I didn't want to hold it up. I figured you would have been aware of it as the PR creator, but sorry if I've left important people out of the loop.
>

No worries at all. The discussion happened in one of *my* PR and I missed it, my fault :-)

 
> _This post got long and rambling, I hope it makes sense. Let me know if there is anything I can do to help with the process. In the mean time I guess I'll leave this PR un-merged._

Thanks a lot for the clarification. Let's use the merge strategy for now, I guess we have too many downstream consumers to continue doing the rebase one.

*Heads-up: After you sent that PR I merged PR #3023 in CCv0*

**Comment by stevenhorsman** [comment]
@sameo, thanks for the comments (and actions). As you say, despite some of the issues with it, I'll carry on with the merge strategy in the short term and we can see how we get on and always re-visit the discussion later.
I think post CNCF proposal will be a key time as we decide what of CCv0 we want to keep and is strategic and get that merged 'upstream' and what is temporary (hopefully most of my code will be here) and we want to replace and do properly based on agreed upon interfaces etc. and the new development can be delivered either directly into `main`, or into a confidential containers  fork of `main` or something.

In the very short term do you have any suggestions for what to do with this PR given the the commit message check failures. All the commits that fail with the error "Failed to find subsystem in subject" are of the form `Merge pull request <x> from <y>`, which I think are unavoidable with the merge strategy.
I guess one option is I use admin privilege and merge anyway, or maybe we could modify the `CCv0` static check to allow that format as well? 
I'm happy to chat to the CI folks and see if they have a better solution as well if you think that would be helpful?

**Comment by sameo** [comment]
> maybe we could modify the `CCv0` static check to allow that format as well?

I think that makes sense as this is the strategy we're going to apply. Or add one supported subsystem: `ccv0-main-merge` or something like that, and amend the merge point commit message accordingly.

**Review by jodh-intel — APPROVED** [review]
Thanks @stevenhorsman - lgtm.

It might be interesting to add a `git diff main --stat` comment on each PR like this to show how the CCv0 branch is changing.

**Comment by stevenhorsman** [comment]
For reference the `git diff main --shortstat` is
`1156 files changed, 90023 insertions(+), 46721 deletions(-)`
If I exclude vendor files with `git diff --stat main -- . ':!*/vendor/*'`
I get `254 files changed, 10536 insertions(+), 5620 deletions(-)`:

```
 .github/workflows/commit-message-check.yaml        |   2 +-
 .github/workflows/kata-deploy-test.yaml            |  24 +-
 .github/workflows/main.yaml                        | 295 -------
 .github/workflows/release.yaml                     |  28 +
 .github/workflows/require-pr-porting-labels.yaml   |   5 +-
 .github/workflows/static-checks.yaml               |  10 +-
 Makefile                                           |  17 +-
 VERSION                                            |   2 +-
 ci/go-no-os-exit.sh                                |  30 -
 ci/install_libseccomp.sh                           | 109 +++
 ci/install_rust.sh                                 |   2 +-
 docs/Developer-Guide.md                            |  56 +-
 docs/README.md                                     |   4 +
 docs/Release-Process.md                            |   2 +-
 docs/design/arch-images/kata-2-metrics.drawio      |   2 +-
 docs/design/arch-images/kata-2-metrics.png         | Bin 95006 -> 91835 bytes
 docs/design/data/metrics.yaml                      |   4 -
 docs/design/kata-2-0-metrics.md                    |  95 ++-
 docs/design/kata-design-requirements.md            |   2 +-
 docs/how-to/README.md                              |   5 +-
 docs/how-to/ccv0.sh                                | 499 +++++++++++
 docs/how-to/how-to-build-and-test-ccv0.md          | 293 +++++++
 docs/how-to/how-to-set-sandbox-config-kata.md      |   2 -
 .../how-to-use-k8s-with-cri-containerd-and-kata.md |  10 +-
 .../how-to/how-to-use-kata-containers-with-acrn.md |   2 +-
 docs/how-to/privileged.md                          |   6 +-
 docs/how-to/run-kata-with-k8s.md                   |  90 +-
 docs/how-to/service-mesh.md                        |   8 +-
 docs/tracing.md                                    | 214 +++++
 docs/use-cases/using-Intel-SGX-and-kata.md         | 156 ++--
 pkg/logging/Cargo.toml                             |   2 +-
 pkg/logging/Makefile                               |  18 +
 pkg/logging/src/lib.rs                             | 197 ++++-
 snap/snapcraft.yaml                                |  32 +-
 src/agent/Cargo.lock                               |  99 ++-
 src/agent/Cargo.toml                               |  18 +-
 src/agent/Makefile                                 |  29 +-
 src/agent/README.md                                | 151 ++--
 src/agent/protocols/Cargo.toml                     |   8 +-
 src/agent/protocols/build.rs                       | 159 +++-
 src/agent/protocols/protos/agent.proto             |   8 -
 src/agent/protocols/protos/image.proto             |  31 +
 src/agent/protocols/protos/types.proto             |   1 +
 src/agent/protocols/src/lib.rs                     |   2 +
 src/agent/rustjail/Cargo.toml                      |   4 +
 src/agent/rustjail/src/container.rs                | 123 ++-
 src/agent/rustjail/src/lib.rs                      |   2 +
 src/agent/rustjail/src/mount.rs                    |  70 +-
 src/agent/rustjail/src/process.rs                  |  26 +
 src/agent/rustjail/src/seccomp.rs                  | 237 ++++++
 src/agent/samples/configuration-all-endpoints.toml |  39 +
 src/agent/src/config.rs                            | 391 +++++----
 src/agent/src/device.rs                            | 477 +++++++++--
 src/agent/src/image_rpc.rs                         | 168 ++++
 src/agent/src/linux_abi.rs                         |   3 +
 src/agent/src/main.rs                              |  56 +-
 src/agent/src/namespace.rs                         | 122 +++
 src/agent/src/netlink.rs                           |  49 +-
 src/agent/src/pci.rs                               | 299 +++++--
 src/agent/src/rpc.rs                               | 249 ++++--
 src/agent/src/sandbox.rs                           |  14 +
 src/agent/src/tracer.rs                            |  45 +-
 src/agent/src/uevent.rs                            |   8 +
 src/agent/src/watcher.rs                           |   5 +
 src/agent/vsock-exporter/Cargo.toml                |   2 +-
 src/runtime/Makefile                               |  39 +-
 src/runtime/cmd/kata-monitor/main.go               |  94 +-
 src/runtime/cmd/kata-runtime/exit.go               |  28 -
 src/runtime/cmd/kata-runtime/exit_test.go          |  42 -
 src/runtime/cmd/kata-runtime/factory.go            |   2 +-
 src/runtime/cmd/kata-runtime/kata-check.go         |   2 +-
 .../cmd/kata-runtime/kata-check_generic_test.go    |   4 +-
 .../cmd/kata-runtime/kata-check_ppc64le_test.go    |  24 +-
 .../cmd/kata-runtime/kata-check_s390x_test.go      |  24 +-
 src/runtime/cmd/kata-runtime/kata-env.go           |  72 +-
 .../cmd/kata-runtime/kata-env_generic_test.go      |   1 +
 src/runtime/cmd/kata-runtime/kata-env_test.go      |  72 +-
 src/runtime/cmd/kata-runtime/main.go               |  11 +-
 src/runtime/cmd/kata-runtime/main_test.go          | 284 +-----
 src/runtime/cmd/kata-runtime/utils_test.go         |   2 +-
 src/runtime/cmd/netmon/netmon.go                   |   2 +-
 src/runtime/cmd/netmon/netmon_test.go              |   8 +-
 src/runtime/config/configuration-acrn.toml.in      |  17 +-
 src/runtime/config/configuration-clh.toml.in       |  44 +-
 src/runtime/config/configuration-fc.toml.in        |  17 +-
 src/runtime/config/configuration-qemu.toml.in      |  38 +-
 src/runtime/data/completions/bash/kata-runtime     |  75 +-
 src/runtime/go.mod                                 |  53 +-
 src/runtime/go.sum                                 | 467 +++++++---
 src/runtime/pkg/containerd-shim-v2/create.go       | 104 +--
 src/runtime/pkg/containerd-shim-v2/create_test.go  |  80 +-
 src/runtime/pkg/containerd-shim-v2/delete_test.go  |  21 +-
 src/runtime/pkg/containerd-shim-v2/errors.go       |   2 +-
 src/runtime/pkg/containerd-shim-v2/errors_test.go  |   2 +-
 src/runtime/pkg/containerd-shim-v2/image.go        |  84 ++
 src/runtime/pkg/containerd-shim-v2/service.go      |   6 +-
 src/runtime/pkg/containerd-shim-v2/service_test.go |   8 +-
 src/runtime/pkg/containerd-shim-v2/stream_test.go  |  24 +-
 src/runtime/pkg/containerd-shim-v2/utils.go        |  12 +-
 src/runtime/pkg/containerd-shim-v2/utils_test.go   | 264 +-----
 src/runtime/pkg/containerd-shim-v2/wait.go         |   2 +-
 src/runtime/pkg/katatestutils/constraints.go       |   9 +-
 src/runtime/pkg/katatestutils/constraints_test.go  |   1 -
 src/runtime/pkg/katatestutils/utils.go             | 230 ++++-
 src/runtime/pkg/katautils/config-settings.go.in    |   2 +
 src/runtime/pkg/katautils/config.go                |  53 +-
 src/runtime/pkg/katautils/config_test.go           |  22 +-
 src/runtime/pkg/katautils/container_engine.go      |  77 --
 src/runtime/pkg/katautils/create.go                |  10 +-
 src/runtime/pkg/katautils/create_test.go           | 110 +--
 src/runtime/pkg/katautils/hook.go                  |   8 +-
 src/runtime/pkg/katautils/katatrace/tracing.go     | 123 ++-
 src/runtime/pkg/katautils/logger.go                |   5 +-
 src/runtime/pkg/katautils/utils_test.go            | 164 ----
 src/runtime/{virtcontainers => }/pkg/oci/utils.go  |  81 +-
 .../{virtcontainers => }/pkg/oci/utils_test.go     |  78 --
 .../pkg/oci/utils_test_config.go                   |   0
 src/runtime/pkg/utils/utils.go                     |  56 ++
 src/runtime/{virtcontainers => }/pkg/uuid/uuid.go  |   0
 .../{virtcontainers => }/pkg/uuid/uuid_test.go     |   0
 src/runtime/virtcontainers/acrn.go                 | 121 +--
 src/runtime/virtcontainers/acrn_test.go            |  33 +-
 src/runtime/virtcontainers/agent.go                |  10 +-
 src/runtime/virtcontainers/api.go                  |   6 +-
 src/runtime/virtcontainers/api_test.go             |   2 +-
 src/runtime/virtcontainers/clh.go                  | 202 +++--
 src/runtime/virtcontainers/clh_test.go             |  76 +-
 src/runtime/virtcontainers/container.go            |  43 +-
 src/runtime/virtcontainers/container_test.go       |   6 +-
 src/runtime/virtcontainers/device/config/config.go |  36 +-
 .../virtcontainers/documentation/Developers.md     |   5 -
 .../virtcontainers/documentation/api/1.0/api.md    |  38 +-
 src/runtime/virtcontainers/endpoint.go             |  16 +-
 src/runtime/virtcontainers/endpoint_test.go        |  14 +-
 .../factory/template/template_test.go              |  19 +-
 src/runtime/virtcontainers/fc.go                   | 170 ++--
 src/runtime/virtcontainers/fc_metrics.go           |   4 +-
 src/runtime/virtcontainers/fc_test.go              |  28 +-
 src/runtime/virtcontainers/hypervisor.go           | 176 ++--
 src/runtime/virtcontainers/hypervisor_arm64.go     |  10 +
 .../virtcontainers/hypervisor_arm64_test.go        |   7 +
 src/runtime/virtcontainers/hypervisor_test.go      |  23 +-
 src/runtime/virtcontainers/image/image.go          |  23 +
 src/runtime/virtcontainers/interfaces.go           |   4 +
 src/runtime/virtcontainers/ipvlan_endpoint.go      |   9 +-
 src/runtime/virtcontainers/kata_agent.go           | 202 ++---
 src/runtime/virtcontainers/kata_agent_test.go      | 191 +----
 ...dgedmacvlan_endpoint.go => macvlan_endpoint.go} |  66 +-
 ...n_endpoint_test.go => macvlan_endpoint_test.go} |   8 +-
 src/runtime/virtcontainers/macvtap_endpoint.go     |  14 +-
 src/runtime/virtcontainers/mock_agent.go           |  11 +-
 src/runtime/virtcontainers/mock_hypervisor.go      |  75 +-
 src/runtime/virtcontainers/mock_hypervisor_test.go |  22 +-
 src/runtime/virtcontainers/monitor.go              |   4 +-
 src/runtime/virtcontainers/mount.go                |  22 +-
 src/runtime/virtcontainers/mount_test.go           |   2 +-
 src/runtime/virtcontainers/network.go              | 191 +----
 src/runtime/virtcontainers/network_test.go         |  12 +-
 src/runtime/virtcontainers/persist.go              |   8 +-
 src/runtime/virtcontainers/persist/api/device.go   |   2 +-
 src/runtime/virtcontainers/persist/api/network.go  |  20 +-
 src/runtime/virtcontainers/persist_test.go         |   2 +-
 src/runtime/virtcontainers/physical_endpoint.go    |   6 +-
 .../virtcontainers/physical_endpoint_test.go       |   2 +-
 .../pkg/agent/protocols/client/client.go           |  15 +-
 .../pkg/agent/protocols/grpc/agent.pb.go           | 693 +++++----------
 .../pkg/agent/protocols/grpc/image.pb.go           | 613 +++++++++++++
 .../virtcontainers/pkg/agent/protocols/types.pb.go |  85 +-
 .../virtcontainers/pkg/annotations/annotations.go  |  10 +-
 src/runtime/virtcontainers/pkg/cgroups/cgroups.go  |  64 +-
 src/runtime/virtcontainers/pkg/cgroups/utils.go    |  75 ++
 .../pkg/cloud-hypervisor/client/api/openapi.yaml   |  16 +
 .../cloud-hypervisor/client/docs/MemoryConfig.md   |  26 +
 .../client/docs/MemoryZoneConfig.md                |  26 +
 .../cloud-hypervisor/client/model_memory_config.go |  40 +
 .../client/model_memory_zone_config.go             |  40 +
 .../pkg/cloud-hypervisor/cloud-hypervisor.yaml     |   6 +
 src/runtime/virtcontainers/pkg/mock/mock.go        |  12 +-
 src/runtime/virtcontainers/pkg/nsenter/nsenter.go  |  31 -
 .../virtcontainers/pkg/rootless/rootless.go        |   3 +-
 src/runtime/virtcontainers/pkg/vcmock/sandbox.go   |   5 +
 src/runtime/virtcontainers/qemu.go                 | 286 ++++---
 src/runtime/virtcontainers/qemu_amd64_test.go      |   2 +-
 src/runtime/virtcontainers/qemu_arch_base.go       |  41 +-
 src/runtime/virtcontainers/qemu_arch_base_test.go  |   4 +-
 src/runtime/virtcontainers/qemu_arm64.go           |  17 +
 src/runtime/virtcontainers/qemu_arm64_test.go      |  60 +-
 src/runtime/virtcontainers/qemu_test.go            |  67 +-
 src/runtime/virtcontainers/sandbox.go              | 106 ++-
 src/runtime/virtcontainers/sandbox_metrics.go      |   4 +-
 src/runtime/virtcontainers/sandbox_test.go         |  14 +-
 src/runtime/virtcontainers/tap_endpoint.go         |  18 +-
 src/runtime/virtcontainers/tuntap_endpoint.go      |  18 +-
 .../virtcontainers/{pkg => }/types/errors.go       |   0
 .../virtcontainers/{pkg => }/types/pcipath.go      |   0
 .../virtcontainers/{pkg => }/types/pcipath_test.go |   0
 src/runtime/virtcontainers/utils/utils.go          |  25 +-
 .../virtcontainers/utils/utils_linux_generic.go    |   1 +
 .../virtcontainers/utils/utils_linux_ppc64le.go    |   1 +
 src/runtime/virtcontainers/utils/utils_test.go     |  19 +-
 .../virtcontainers/utils/virtcontainers-setup.sh   |  78 --
 src/runtime/virtcontainers/veth_endpoint.go        |  12 +-
 src/runtime/virtcontainers/vhostuser_endpoint.go   |  10 +-
 src/runtime/virtcontainers/virtcontainers_test.go  |   2 +-
 src/runtime/virtcontainers/vm.go                   |  46 +-
 src/runtime/virtcontainers/vm_test.go              |   2 -
 src/trace-forwarder/Cargo.lock                     |  32 +-
 src/trace-forwarder/Cargo.toml                     |   4 +
 src/trace-forwarder/Makefile                       |  13 +-
 src/trace-forwarder/README.md                      | 154 +++-
 src/trace-forwarder/src/handler.rs                 |  42 +-
 src/trace-forwarder/src/main.rs                    | 349 ++++++--
 src/trace-forwarder/src/server.rs                  | 139 ++-
 src/trace-forwarder/src/utils.rs                   | 357 ++++++++
 tools/agent-ctl/Cargo.lock                         |  18 +-
 tools/agent-ctl/Cargo.toml                         |   8 +-
 tools/agent-ctl/Makefile                           |  11 +-
 tools/agent-ctl/README.md                          | 137 ++-
 tools/agent-ctl/src/client.rs                      | 948 +++++++++++++--------
 tools/agent-ctl/src/main.rs                        |  69 +-
 tools/agent-ctl/src/rpc.rs                         |  20 +-
 tools/agent-ctl/src/types.rs                       |   3 +
 tools/agent-ctl/src/utils.rs                       | 550 ++++++++++--
 tools/osbuilder/dockerfiles/QAT/Dockerfile         |   6 +-
 tools/osbuilder/image-builder/Dockerfile           |   2 +-
 .../osbuilder/rootfs-builder/alpine/Dockerfile.in  |  24 +-
 .../rootfs-builder/centos/config_ppc64le.sh        |   2 +-
 tools/osbuilder/rootfs-builder/rootfs.sh           | 103 ++-
 .../rootfs-builder/ubuntu/Dockerfile-aarch64.in    |   5 +
 .../osbuilder/rootfs-builder/ubuntu/Dockerfile.in  |   5 +
 tools/osbuilder/rootfs-builder/ubuntu/config.sh    |   1 +
 tools/osbuilder/scripts/lib.sh                     |  19 +
 tools/packaging/kata-deploy/.dockerignore          |   1 +
 .../kata-cleanup/base/kata-cleanup-stable.yaml     |  46 -
 .../kata-cleanup/base/kata-cleanup.yaml            |   2 +-
 .../kata-deploy/base/kata-deploy-stable.yaml       |  69 --
 .../kata-deploy/kata-deploy/base/kata-deploy.yaml  |   2 +-
 tools/packaging/kata-deploy/local-build/Makefile   |   3 +
 .../kata-deploy-build-and-upload-image.sh          |  24 +
 tools/packaging/kernel/build-kernel.sh             |   6 +-
 .../kernel/configs/fragments/common/vfio.conf      |   5 +
 .../kernel/configs/fragments/powerpc/vfio.conf     |   3 +
 .../kernel/configs/fragments/x86_64/pci.conf       |   1 +
 .../kernel/configs/fragments/x86_64/vfio.conf      |   3 +
 tools/packaging/kernel/kata_config_version         |   2 +-
 ...ules-use-GitLab-repos-instead-of-qemu.org.patch | 111 +++
 tools/packaging/release/release-notes.sh           |  39 +-
 tools/packaging/scripts/configure-hypervisor.sh    |  35 +-
 tools/packaging/static-build/kernel/Dockerfile     |   4 +-
 tools/packaging/static-build/qemu.blacklist        |   1 -
 tools/packaging/static-build/qemu/Dockerfile       |   3 +-
 utils.mk                                           |   4 +-
 utils/kata-manager.sh                              |  13 +-
 versions.yaml                                      |  46 +-
 254 files changed, 10536 insertions(+), 5620 deletions(-)
```

I'm happy to add this as a comment each week if it would be helpful, but with > 250 files it is fairly long, so it depends if it is still useful.

**Review by sameo — APPROVED** [review]

**Comment by stevenhorsman** [comment]
> > maybe we could modify the `CCv0` static check to allow that format as well?
> 
> I think that makes sense as this is the strategy we're going to apply. Or add one supported subsystem: ccv0-main-merge or something like that, and amend the merge point commit message accordingly.

@sameo - In case you didn't spot it I added the "Merge pull request..." message as an alternative to the subsystem string in https://github.com/kata-containers/kata-containers/pull/3084/commits/7152448f21bd5f6db278bdf1da1bbac8b1fe3999 as I figured it would be easier to do it once rather than amend the commit messages of all those commits (there were ~15 this week) every week, which I hope is okay with you.

**Pull request merged**
