### PR TITLE
runtime: change network checks in kata check command to opt-in

### PR DESCRIPTION
**Pull request by zhsj**
Fixes: #3364

Signed-off-by: Shengjing Zhu <zhsj@debian.org>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Thanks for raising @zhsj, but I'm not sure this is a good idea. Please can you explain a little more about why this should be done?

The check command has evolved over time and is quite careful about how it works: network checks are disabled when running as `root` but when run as a non-`root` user we _want_ users/admins to be notified of new releases in case they are using one of the (many) instlalation types that do not offer automatic updates:

- https://github.com/kata-containers/kata-containers/tree/main/docs/install#packaged-installation-methods

That might not work for all use-cases, but we want to make new releases as visible as possible even for static installations so that users are warned that they should upgrade.

We added the ability to disable network checks to allow the command to be run in a CI / build environment where there was no network access. I'm assuming you wish to run `kata-runtime check` in some sort of build environment that disallows network access so why not just set the env var or specify the option to disable network checks?

**Comment by zhsj** [comment]
@jodh-intel This is change doesn't remove network check, but only changing it to opt-in, instead of opt-out. As I said in #3364, the opt-out policy makes user risky to do accident network access, and may leak user privacy.

**Comment by zhsj** [comment]
> I'm assuming you wish to run kata-runtime check in some sort of build environment that disallows network access so why not just set the env var or specify the option to disable network checks

No, that's not my wish. I want users who run `check` command only access internet when they explicitly allow such behavior. This is not about CI or any build environment.

**Comment by jcvenegas** [comment]
@zhsj so If I understand correctly. The main problem you see is this:
# Problem:
If users use the `check` subcommand it will do some network access to verify the version by default. And this is something that you consider a privacy issue. 

## What is the potential privacy concern?
The privacy issue is that by doing network access to a remote  endpoint their IPs may be collected?

Solution:
Your proposed solution, make explicit that the command will do network usage and remove the option that prevents it?

---
If this is correct I would suggest just add an extra comment in the `check` description saying that it does network access by default.  It will do the same as you propose now, but we keep the logic of check for limited network environments that is the main goal of the flag you want to remote  .

**Comment by zhsj** [comment]
@jcvenegas The point I raised in #3364 is

> When users first run this command, without looking --help or other documents, they are risked to do unexpected network access.

So I don't think adding extra comment in description helps.

**Comment by zhsj** [comment]
> What is the potential privacy concern?
> The privacy issue is that by doing network access to a remote endpoint their IPs may be collected?

Yes. leaking users IP, and their usage of kata-containers.

**Comment by jodh-intel** [comment]
It's worth stating that the `check` command is never run by Kata itself. It's a utility command that the user/admin _may_ run if they want to, but it's not needed to run Kata at all.

If the docs for `--help` are made clearer I would have thought that would be adequate: if you really care about privacy, presumably you don't run random commands, hoping they won't do things you don't expect: you'd look at the docs before running the command (and obviously hope those docs are correct, or check the source code ;-)

If we did land this, we'd improve privacy, but potentially reduce security as users wouldn't be aware of critically important updates. That clearly isn't ideal for everyone.

Also, even if users don't want `check` to hit the network:

- Normally, they would have to hit the network at some point to download a container image (unless those are all generated locally and hosted in a local registry)
- How do they download Kata in the first place?

@zhsj - The other point is that this PR switches the current behaviour, so we would break users who have come to expect this behaviour.

Let's see what others feel as we've got a mix of security, usability, discoverability and privacy arguments here, and I suspect we'll get a number of differnet views on what folk see as the most important.

**Comment by zhsj** [comment]
> Also, even if users don't want check to hit the network:
> Normally, they would have to hit the network at some point to download a container image (unless those are all 
> generated locally and hosted in a local registry)
>How do they download Kata in the first place?

My point is not "check" shouldn't nit network. But should with explicit permission. This is different with the cases you give. That's the whole point of this PR, "opt-in" vs "opt-out".

**Comment by zhsj** [comment]
Let me make my point clear: any action that has potential privacy breach should be **opt-in**. It's not any action that has potential privacy breach should be removed.

**Comment by jodh-intel** [comment]
Can we get more input from the community on this topic please?

**Comment by jodh-intel** [comment]
For reference, the `kata-runtime check` feature that checks for newer Kata Containers releases was added on https://github.com/kata-containers/kata-containers/pull/735 in September 2020.

**Comment by amshinde** [comment]
@zhsj @jodh-intel I am not in favor of this change. Like @jodh-intel mentioned, `kata-runtime check` is a user utility meant to be run separately. If the --help does not mention that we access the internet to check for the latest versions, we can do so. I do not see making  a curl call on a public url to get the latest version is a security breach or compromises his privacy as long as this is documented.

**Comment by Jakob-Naucke** [comment]
@zhsj Let me make a comparison. I know you're coming from Debian, and e.g. `apt` doesn't do this, but the `dnf` package manager will update repositories if they're out of date when doing a `dnf search`, even though the unitiated user might think it would just search the offline index and not create any connection. I'm not aware of such complaints there. Therefore, I think it is not a problem to make such connections, and anyone who is really conscious about not leaking their IP should probably not run commands they don't know well or firewall on an allow-list basis entirely (or heck, air gap).

**Comment by fidencio** [comment]
A head's up that may affect your PR.

In the Architecture Committee meeting from January 25th, 2022, the Architecture Committee has agreed on using the "Dismiss stale pull request approvals when new commits are pushed" configuration from GitHub.  It basically means that if your PR has been rebased or updated, the approvals given will be erased.

In order to minimize traumas due to the new approach, please, consider adding a note on the changes done before the rebase / force-push, and also pinging the reviewers for a subsequent round of reviews.

Thanks for your understanding!

Related issue: https://github.com/kata-containers/community/issues/249

**Comment by fidencio** [comment]
@zhsj, thanks for your input on this, but at this moment several of our contributors, including myself, think the current approach is reasonable.

If that's a limitation for Debian, I'd suggest keeping a downstream patch on Debian side to avoid such connections.

I'm closing this PR now, thanks a lot for your contribution and your understanding!

**Pull request closed without merging**
