### PR TITLE
kata-agent: Check if attestation binaries are enabled as systemd units

### PR DESCRIPTION
**Pull request by bpradipt**
In some environments the guest components, cdh, attestation-agent etc are run as systemd units and this patch enables checking for systemd enabled units before instantiating the processes

### CODE REVIEW

**Comment by bpradipt** [comment]
@mkulke @Xynnn007 @fitzthum I made an attempt to handle the scenario where guest processes are started via systemd. Using this approach enables working of sealed-secrets etc when using systemd units for guest procs. Do you think this approach is relevant?
Putting this as draft as I'm not sure if the approach is acceptable or if there is a better alternative.

**Comment by mkulke** [comment]
I am not sure it's a good idea to employ heuristics to detect whether the services have been launched. I would rather disable the launch guest component processes explicitly. I thought `GuestComponentsProcs::None` is doing exactly that. This can be configured at kata-launch. Is anything not working using this approach?

There might be side-effects in the `launch_x()` fn's that prevent the usage of some CDH functionality, but then we should untangle this.

**Comment by fitzthum** [comment]
At a glance it seems like sealed-secret and other features should work with `GuestComponentsProcs::None` but we should double check since this wasn't always the case.

**Comment by zvonkok** [comment]
I hope this will work for init systems that do not rely on systemd? Didn't dig into the code. For the GPU use case we run a very simple bare minimum init system...

**Comment by bpradipt** [comment]
> I am not sure it's a good idea to employ heuristics to detect whether the services have been launched. I would rather disable the launch guest component processes explicitly. I thought `GuestComponentsProcs::None` is doing exactly that. This can be configured at kata-launch. Is anything not working using this approach?
> 

sealed-secrets is not working with GuestComponentsProcs::None.

**Comment by bpradipt** [comment]
> At a glance it seems like sealed-secret and other features should work with `GuestComponentsProcs::None` (assuming someone else starts the guest components) but we should double check since this wasn't always the case.

It didn't work for me. I think this is because when GuestcomponentsProcs::None then CDH client is not initialised and that's needed for any CDH provided functionality to work.

**Comment by bpradipt** [comment]
> I hope this will work for init systems that do not rely on systemd? Didn't dig into the code. For the GPU use case we run a very simple bare minimum init system...

Yes. The code checks if systemd units are enabled for the guest procs before starting them standalone. On rootfs without systemd the existing behaviour is retained, ie kata-agent spawning the guest procs

**Comment by mkulke** [comment]
> > At a glance it seems like sealed-secret and other features should work with `GuestComponentsProcs::None` (assuming someone else starts the guest components) but we should double check since this wasn't always the case.
> 
> It didn't work for me. I think this is because when GuestcomponentsProcs::None then CDH client is not initialised and that's needed for any CDH provided functionality to work.

I see. then we should make sure the CDH client is started even in cases when kata is not launching the CDH server process. I can take a look.

**Comment by mkulke** [comment]
> > I hope this will work for init systems that do not rely on systemd? Didn't dig into the code. For the GPU use case we run a very simple bare minimum init system...
> 
> Yes. The code checks if systemd units are enabled for the guest procs before starting them standalone. On rootfs without systemd the existing behaviour is retained, ie kata-agent spawning the guest procs

it wouldn't work if guest-components are launched by e.g. runit.

**Comment by mkulke** [comment]
https://github.com/kata-containers/kata-containers/blob/main/src/agent/src/main.rs#L500-L501

this needs to be moved out of the !GCProcs::None path. I am not sure if this client is lazy, but if it's not, peerpods should make sure that kata-agent is only launched once the CDH sock is ready to avoid race conditions.

**Comment by bpradipt** [comment]
> https://github.com/kata-containers/kata-containers/blob/main/src/agent/src/main.rs#L500-L501
> 
> this needs to be moved out of the !GCProcs::None path. I am not sure if this client is lazy, but if it's not, peerpods should make sure that kata-agent is only launched once the CDH sock is ready to avoid race conditions.

Even for bare metal case using systemd based rootfs. So ensuring kata-agent is launched once the CDH sock in is ready in general will be needed.

**Comment by bpradipt** [comment]
> > > I hope this will work for init systems that do not rely on systemd? Didn't dig into the code. For the GPU use case we run a very simple bare minimum init system...
> > 
> > 
> > Yes. The code checks if systemd units are enabled for the guest procs before starting them standalone. On rootfs without systemd the existing behaviour is retained, ie kata-agent spawning the guest procs
> 
> it wouldn't work if guest-components are launched by e.g. runit.

So for supporting runit some changes will be needed as well? I'm assuming the existing mechanism of launching the guest procs by kata-agent is incompatible with runit

**Comment by mkulke** [comment]
> Even for bare metal case using systemd based rootfs. So ensuring kata-agent is launched once the CDH sock in is ready in general will be needed.

yup, also if kata-agent launches CDH as parent, otherwise there would be race conditions. exec will return after the process has spawned, but that doesn't mean the socket has been created yet.

**Comment by bpradipt** [comment]
> > So for supporting runit some changes will be needed as well? I'm assuming the existing mechanism of launching the guest procs by kata-agent is incompatible with runit
> 
> I'm just saying that if we hardcode something with systemctl, you would run into the same problem if someone builds a rootfs with another init system, like runit or supervisord

Ah ok. Thanks for clarifying.

**Comment by mkulke** [comment]
I tried to address the CDH client issue in this [PR](https://github.com/kata-containers/kata-containers/pull/10481).

**Comment by bpradipt** [comment]
This is superseded by https://github.com/kata-containers/kata-containers/pull/10481/, hence closing this one.

**Pull request closed without merging**
