### PR TITLE
gha: Unbreak CI and work around workflow limit

### PR DESCRIPTION
**Pull request by sprt**
#10561 inadvertently broke the CI by going over the limit of 20 reusable workflows:

https://github.com/kata-containers/kata-containers/actions/runs/12054648658/workflow

This commit fixes that by inlining the job.

### CODE REVIEW

**Review by stevenhorsman — APPROVED** [review]
Looks worth a try!

**Review by fidencio — APPROVED** [review]
lgtm, thanks @sprt!

**Comment by fidencio** [comment]
> lgtm, thanks @sprt!

Actually, let me take this back. Gimme a few minutes to figure out how we solved this in the past.

**Review by fidencio — APPROVED** [review]
Yep, we solved a similar failure in the past in the very same way.
lgtm, thanks @sprt!

**Comment by fidencio** [comment]
Let's use the admin powers to have this one merged.

**Pull request merged**
