### PR TITLE
runtime-rs: fix shim close_io call to support kubectl cp

### PR DESCRIPTION
**Pull request by liubin**
Add close_io to shim and call agent's close_stdin in close_io.

Fixes: #4729

Signed-off-by: Bin Liu <bin@hyper.sh>

### CODE REVIEW

**Review by Ji-Xinyou — APPROVED** [review]
Thanks @liubin , LGTM

**Review by studychao — APPROVED** [review]

**Review by bergwolf — APPROVED** [review]
lgtm!

**Pull request merged**
