### PR TITLE
cli: Add aliases for `kata-` options 

### PR DESCRIPTION
**Pull request by knittl**
Change `--kata-config` and --kata-show-default-config-paths` to be prefixless, but keep the old option as alias.

### CODE REVIEW

**Comment by fidencio** [comment]
I'm really sorry for the disruption but in order to do the branch name changes announced [here](http://lists.katacontainers.io/pipermail/kata-dev/2021-January/001695.html) I'm adding the "do-not-merge" and the "needs-branch-adjustment" labels to the PR.

I'll add a new comment once the branch changes are done and once it happens I'd like to ask you to resubmit the PR against the new `main` branch, possibly linking to this PR in case you find the conversations / reviews already made important to proceed.

**Comment by knittl** [comment]
> I'll add a new comment once the branch changes are done and once it happens I'd like to ask you to resubmit the PR against the new `main` branch, possibly linking to this PR in case you find the conversations / reviews already made important to proceed.

Hi, thanks for the headsup. Although, I don't understand why a new PR is required? The target branch can simply be changed for existing PRs (and in fact, GitHub shows that the target branch has already been updated from `2.0-dev` to `main`). Can you quickly explain why a new PR should be opened?
If the base changed, I can rebase the changes. No problem there.

**Comment by fidencio** [comment]
> Although, I don't understand why a new PR is required?

We thought it'd be needed, turns out it's not as we figured out that we could just rename the branch without affecting the existing PRs. This will be part of my second message, once we ensure that all CIs as behaving accordingly to the changes.

> The target branch can simply be changed for existing PRs (and in fact, GitHub shows that the target branch has already been updated from 2.0-dev to main). Can you quickly explain why a new PR should be opened?

As I mentioned above, we thought it'd be needed (as at first the plan was to create a new `main` branch with everything from `2.0-dev` but we realised that we could just rename the branch. Right now, we're in the middle of the process, checking CIs, checking if we missed something.  Once those bits are okay, I'll drop a second message to all PRs that opening a new one is, indeed, not needed.

Does this answer your question?

**Comment by knittl** [comment]
@fidencio thank you, yes, that answers my question to the fullest.

**Comment by fidencio** [comment]
Kata Containers repos are back to business.  Thanks a lot for your patience and I'm very happy to announce that there's no changes needed from your side as renaming the branches automagically reflected here.

If you notice something weird, some missing CI, please, do not hesitate on contacting us here or on #kata-dev on bit.ly/katacontainersslack.

Also, this is a good opportunity to have your PR rebased atop of `main`, to ensure your PR follow all the guidelines (https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format) enforced by this community, or even to re-evaluate whether the PR is currently needed.

Last but not least,  as the default branch has been renamed to `main`, if you have a local clone you'd need to update it and you do so by running:
```
git branch -m 2.0-dev main
git fetch origin
git branch -u origin/main main
```

Happy hacking!

**Comment by fidencio** [comment]
@jodh-intel, mind to take a look at this one?

**Review by jodh-intel — APPROVED** [review]
Thanks @knittl.

**Comment by jodh-intel** [comment]
@knittl - gah! Good news and bad... One of the CI's has failed for this PR:

```
ERROR: Invalid URL 'https://docs.fluentbit.io/manual/parser/logfmt' found in the following files:

docs/how-to/how-to-import-kata-logs-with-fluentd.md
```

Good that the CI caught it, but annoying as it's not related to your change - you just got unlucky as you touched the file that referenced the (now) invalid URL.

If you can add a new commit (ideally as your first commit) to change that broken URL to https://docs.fluentbit.io/manual/pipeline/parsers/logfmt, the CI should be happy ;)

**Comment by knittl** [comment]
@jodh-intel no problem, done :)

**Comment by jodh-intel** [comment]
Thanks very much @knittl !

/retest

**Comment by knittl** [comment]
@jodh-intel It looks like there are again problems with external dependencies? Should I rebase my changes to latest `main`?

**Review by fidencio — APPROVED** [review]
lgtm, thanks @knittl!

**Comment by fidencio** [comment]
@knittl, I'm really sorry to say that we need yet another rebase atop of `main`.

**Comment by knittl** [comment]
@fidencio no problem :) I tried and still get an unrelated (?) build error:

    /usr/bin:/sbin:/bin:/snap/snapcraft/6050/bin/scriptlet-bin
    /bin/bash: line 43: http_proxy: unbound variable
    Failed to run 'override-build': Exit code was 1.

I don't think I changed anything there. Do you think this breakage was caused by my changes?

**Comment by fidencio** [comment]
@devimc, can you take a look at the snap CI issue?

**Comment by fidencio** [comment]
> @fidencio no problem :) I tried and still get an unrelated (?) build error:
> 
> ```
> /usr/bin:/sbin:/bin:/snap/snapcraft/6050/bin/scriptlet-bin
> /bin/bash: line 43: http_proxy: unbound variable
> Failed to run 'override-build': Exit code was 1.
> ```
> 
> I don't think I changed anything there. Do you think this breakage was caused by my changes?

I don't think it's related to your changes, @knittl.  /o\
At least with this rebase the errors we had with the static checks are finally gone.

**Comment by devimc** [comment]
https://github.com/kata-containers/kata-containers/pull/1387 should fix the snap CI

**Comment by fidencio** [comment]
Snap is failing but it's not a blocker, as the failure doesn't seem to be related to this series.  Let me re-run the other jobs and have it merged as soon as possible. :-)

**Pull request merged**
