### PR TITLE
Host cgroups improvements and simplifications

### LINKED ISSUE #2184: Hypervisor threads are not constrained
# Description of problem

With `sandbox_cgroup_only` unset, the hypervisor vcpu threads are not constrained to the limits defined by the sandbox cgroup hierarchy.

# Expected result

When not setting `sandbox_cgroup_only`, all the vcpu threads should be added to the sandbox cgroup hierarchy and follow the limits defined there. This is the expected behaviour.

### PR DESCRIPTION
**Pull request by sameo**
This is an attempt at fixing and simplifying the way Kata Containers handle host cgroups.

The goal of that PR is to:

- Fix #2184
- Have a simple host cgroup partitioning scheme: A sandbox cgroup and a overhead cgroup. When `sandbox_cgroup_only` is enabled, the current behaviour is unchanged. When it is disabled, we start all Kata Containers processes and threads from the unconstrained overhead cgroup and then move the vCPU threads to the sandbox one, as they're getting created.
- Update the host sandbox cgroup design documentation accordingly.
- Reduce the number of external cgroups API dependencies to a single one (`containerd/cgroups`)

With this new approach (sandbox/overhead cgroups), we only support cgroup v1 for now, but I am working on 2 follow up PRs:

* [ ] Dynamically detect the host cgroup hierarchy and use it (Default to v1)
* [ ] Define a more granular setting for the sandbox cgroup and allow for moving running all processes under the sandbox cgroup, but only for a subset of the subsystems. This depends on https://github.com/containerd/cgroups/pull/203

### CODE REVIEW

**Comment by fidencio** [comment]
@sameo, boot times seem to have increased with this PR, see: http://jenkins.katacontainers.io/job/kata-containers-2.0-metrics-ubuntu-20-04-PR/1084/console

Do you think this is expected?  If so, why?

**Comment by sameo** [comment]
> @sameo, boot times seem to have increased with this PR, see: http://jenkins.katacontainers.io/job/kata-containers-2.0-metrics-ubuntu-20-04-PR/1084/console
> 
> Do you think this is expected? If so, why?

It's not expected, but it seems the added latency is consistently showing up.
Let me have a look.

**Comment by egernst** [comment]
Saw boot time failure; which is interesting/not particularly expected:

```
02:38:38 Report Summary:
02:38:38 +-----+----------------------+-------+--------+--------+-------+-------+--------+-------+-------+-----+
02:38:38 | P/F |         NAME         |  FLR  |  MEAN  |  CEIL  |  GAP  |  MIN  |  MAX   |  RNG  |  COV  | ITS |
02:38:38 +-----+----------------------+-------+--------+--------+-------+-------+--------+-------+-------+-----+
02:38:38 | *F* | boot-times           | 95.0% | 109.6% | 105.0% | 10.0% | 91.7% | 168.5% | 83.7% | 14.2% |  20 |
02:38:38 | P   | memory-footprint     | 95.0% | 98.2%  | 105.0% | 10.0% | 98.2% | 98.2%  | 0.0%  | 0.0%  |   1 |
02:38:38 | P   | memory-footprint-ksm | 90.0% | 99.3%  | 110.0% | 20.0% | 99.3% | 99.3%  | 0.0%  | 0.0%  |   1 |
02:38:38 | P   | blogbench            | 90.0% | 99.5%  | 110.0% | 20.0% | 99.5% | 99.5%  | 0.0%  | 0.0%  |   1 |
02:38:38 | P   | blogbench            | 90.0% | 99.7%  | 110.0% | 20.0% | 99.7% | 99.7%  | 0.0%  | 0.0%  |   1 |
02:38:38 +-----+----------------------+-------+--------+--------+-------+-------+--------+-------+-------+-----+
```

**Comment by fidencio** [comment]
@sameo, as part of 518236191cbcaf38f8aef1b4a2c47b93800a33df, you should run `make -C src/runtime handle_vendor`.
When you do that, you'll realise that a bunch of vendored could should be updated:
```
fidencio@quino ~/go/src/github.com/kata-containers/kata-containers $ git status
rebase interactivo en progreso; en fdc42ca7
Los últimos comandos realizados (5 comandos realizados):
   edit 6c43fa45 virtcontainers: cgroups: Add a containerd API based cgroups package
   edit 51823619 virtcontainers: Convert to the new cgroups package API
  (ver más en el archivo .git/rebase-merge/done)
Siguiente comando a realizar (1 comando restante):
   edit 9d8debc9 docs: Host cgroups documentation update
  (usa "git rebase --edit-todo" para ver y editar)
Estás editando un commit mientras se aplica un rebase de la rama 'topic/host-cgroups' en 'fdc42ca7'.
  (usa "git commit --amend" para enmendar el commit actual)
  (usa "git rebase --continue" una vez que estés satisfecho con tus cambios)

Cambios no rastreados para el commit:
  (usa "git add/rm <archivo>..." para actualizar a lo que se le va a hacer commit)
  (usa "git restore <archivo>..." para descartar los cambios en el directorio de trabajo)
	modificado:     src/runtime/go.sum
	borrado:        src/runtime/vendor/github.com/checkpoint-restore/go-criu/v5/.gitignore
	borrado:        src/runtime/vendor/github.com/checkpoint-restore/go-criu/v5/.golangci.yml
	borrado:        src/runtime/vendor/github.com/checkpoint-restore/go-criu/v5/LICENSE
	borrado:        src/runtime/vendor/github.com/checkpoint-restore/go-criu/v5/Makefile
	borrado:        src/runtime/vendor/github.com/checkpoint-restore/go-criu/v5/README.md
	borrado:        src/runtime/vendor/github.com/checkpoint-restore/go-criu/v5/go.mod
	borrado:        src/runtime/vendor/github.com/checkpoint-restore/go-criu/v5/go.sum
	borrado:        src/runtime/vendor/github.com/checkpoint-restore/go-criu/v5/main.go
	borrado:        src/runtime/vendor/github.com/checkpoint-restore/go-criu/v5/notify.go
	borrado:        src/runtime/vendor/github.com/checkpoint-restore/go-criu/v5/rpc/rpc.pb.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/.clang-format
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/.gitignore
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/.golangci.yaml
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/ARCHITECTURE.md
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/CODE_OF_CONDUCT.md
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/CONTRIBUTING.md
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/LICENSE
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/Makefile
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/README.md
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/asm/alu.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/asm/alu_string.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/asm/doc.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/asm/func.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/asm/func_string.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/asm/instruction.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/asm/jump.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/asm/jump_string.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/asm/load_store.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/asm/load_store_string.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/asm/opcode.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/asm/opcode_string.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/asm/register.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/collection.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/doc.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/elf_reader.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/elf_reader_fuzz.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/go.mod
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/go.sum
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/info.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/btf/btf.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/btf/btf_types.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/btf/btf_types_string.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/btf/core.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/btf/doc.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/btf/ext_info.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/btf/fuzz.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/btf/strings.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/btf/types.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/cpu.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/elf.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/endian.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/errors.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/fd.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/feature.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/io.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/pinning.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/ptr.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/ptr_32_be.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/ptr_32_le.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/ptr_64.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/syscall.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/syscall_string.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/unix/types_linux.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/unix/types_other.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/internal/version.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/link/cgroup.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/link/doc.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/link/iter.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/link/kprobe.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/link/link.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/link/netns.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/link/perf_event.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/link/platform.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/link/program.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/link/raw_tracepoint.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/link/syscalls.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/link/tracepoint.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/link/uprobe.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/linker.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/map.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/marshalers.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/prog.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/run-tests.sh
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/syscalls.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/types.go
	borrado:        src/runtime/vendor/github.com/cilium/ebpf/types_string.go
	borrado:        src/runtime/vendor/github.com/cyphar/filepath-securejoin/.travis.yml
	borrado:        src/runtime/vendor/github.com/cyphar/filepath-securejoin/LICENSE
	borrado:        src/runtime/vendor/github.com/cyphar/filepath-securejoin/README.md
	borrado:        src/runtime/vendor/github.com/cyphar/filepath-securejoin/VERSION
	borrado:        src/runtime/vendor/github.com/cyphar/filepath-securejoin/join.go
	borrado:        src/runtime/vendor/github.com/cyphar/filepath-securejoin/vendor.conf
	borrado:        src/runtime/vendor/github.com/cyphar/filepath-securejoin/vfs.go
	borrado:        src/runtime/vendor/github.com/mrunalp/fileutils/.gitignore
	borrado:        src/runtime/vendor/github.com/mrunalp/fileutils/LICENSE
	borrado:        src/runtime/vendor/github.com/mrunalp/fileutils/MAINTAINERS
	borrado:        src/runtime/vendor/github.com/mrunalp/fileutils/README.md
	borrado:        src/runtime/vendor/github.com/mrunalp/fileutils/fileutils.go
	borrado:        src/runtime/vendor/github.com/mrunalp/fileutils/go.mod
	borrado:        src/runtime/vendor/github.com/mrunalp/fileutils/idtools.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/README.md
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/SPEC.md
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/apparmor/apparmor.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/apparmor/apparmor_linux.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/apparmor/apparmor_unsupported.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/capabilities/capabilities.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/capabilities/capabilities_unsupported.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/cgroups.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/cgroups_unsupported.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/devices/devices_emulator.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/ebpf/devicefilter/devicefilter.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/ebpf/ebpf_linux.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/file.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/blkio.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/cpu.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/cpuacct.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/cpuset.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/devices.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/freezer.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/fs.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/hugetlb.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/memory.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/name.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/net_cls.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/net_prio.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/perf_event.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/pids.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/unsupported.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/cpu.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/cpuset.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/create.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/defaultpath.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/devices.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/freezer.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/fs2.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/hugetlb.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/io.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/memory.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs2/pids.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/fscommon/utils.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/stats.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/common.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/cpuset.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/dbus.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/unsupported.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/user.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/v1.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/v2.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/utils.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/cgroups/v1_utils.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/configs/validate/rootless.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/configs/validate/validator.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/console_linux.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/container.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/container_linux.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/criu_opts_linux.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/error.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/factory.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/factory_linux.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/generic_error.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/init_linux.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/intelrdt/cmt.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/intelrdt/intelrdt.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/intelrdt/mbm.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/intelrdt/monitoring.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/intelrdt/stats.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/keys/keyctl.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/logs/logs.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/message_linux.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/network_linux.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/notify_linux.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/notify_linux_v2.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/process.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/process_linux.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/restored_process.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/rootfs_linux.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/seccomp/config.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/seccomp/patchbpf/enosys_linux.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/seccomp/patchbpf/enosys_unsupported.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/seccomp/seccomp_linux.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/seccomp/seccomp_unsupported.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/setns_init_linux.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/specconv/example.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/specconv/spec_linux.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/stacktrace/capture.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/stacktrace/frame.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/stacktrace/stacktrace.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/standard_init_linux.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/state_linux.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/stats_linux.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/sync.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/system/linux.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/system/proc.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/system/syscall_linux_32.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/system/syscall_linux_64.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/system/xattrs_linux.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/utils/cmsg.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/utils/utils.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/libcontainer/utils/utils_unix.go
	borrado:        src/runtime/vendor/github.com/opencontainers/runc/types/events.go
	borrado:        src/runtime/vendor/github.com/seccomp/libseccomp-golang/.gitignore
	borrado:        src/runtime/vendor/github.com/seccomp/libseccomp-golang/CHANGELOG
	borrado:        src/runtime/vendor/github.com/seccomp/libseccomp-golang/LICENSE
	borrado:        src/runtime/vendor/github.com/seccomp/libseccomp-golang/Makefile
	borrado:        src/runtime/vendor/github.com/seccomp/libseccomp-golang/README
	borrado:        src/runtime/vendor/github.com/seccomp/libseccomp-golang/SUBMITTING_PATCHES
	borrado:        src/runtime/vendor/github.com/seccomp/libseccomp-golang/seccomp.go
	borrado:        src/runtime/vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go
	borrado:        src/runtime/vendor/github.com/syndtr/gocapability/LICENSE
	borrado:        src/runtime/vendor/github.com/syndtr/gocapability/capability/capability.go
	borrado:        src/runtime/vendor/github.com/syndtr/gocapability/capability/capability_linux.go
	borrado:        src/runtime/vendor/github.com/syndtr/gocapability/capability/capability_noop.go
	borrado:        src/runtime/vendor/github.com/syndtr/gocapability/capability/enum.go
	borrado:        src/runtime/vendor/github.com/syndtr/gocapability/capability/enum_gen.go
	borrado:        src/runtime/vendor/github.com/syndtr/gocapability/capability/syscall_linux.go
	borrado:        src/runtime/vendor/golang.org/x/net/bpf/asm.go
	borrado:        src/runtime/vendor/golang.org/x/net/bpf/constants.go
	borrado:        src/runtime/vendor/golang.org/x/net/bpf/doc.go
	borrado:        src/runtime/vendor/golang.org/x/net/bpf/instructions.go
	borrado:        src/runtime/vendor/golang.org/x/net/bpf/setter.go
	borrado:        src/runtime/vendor/golang.org/x/net/bpf/vm.go
	borrado:        src/runtime/vendor/golang.org/x/net/bpf/vm_instructions.go
	modificado:     src/runtime/vendor/modules.txt
```

**Review by fidencio — COMMENTED** [review]
@sameo, this is a quite reasonable change of behaviour and, IMHO, the proposed changes make sense.  However, this is also coming quite late in the development cycle.

I'm fine with the change, I'd like to see this getting merged before "-rc0", but I'd like also to ask for a review from a few other folks.

/cc @devimc @c3d to start with.  We may want to loop Mrunal in later on, but I'll leave that at Christophe's discretion to do so (or not).

**Comment by sameo** [comment]
> @sameo, this is a quite reasonable change of behaviour and, IMHO, the proposed changes make sense. However, this is also coming quite late in the development cycle.
> 

I agree it's late for a change that's not trivial.

> I'm fine with the change, I'd like to see this getting merged before "-rc0", but I'd like also to ask for a review from a few other folks.
> 

I will work on the vendoring part and the latency regressions, I got caught up into something else (#2375).

**Comment by egernst** [comment]
Taking a look at this error (the math doesn't add up to what I'm seeing locally): 

```
cgroups.go:20:13: fieldalignment: struct with 64 pointer bytes could be 48 (govet)
17241
type Cgroup struct {
17242
            ^
```

**Comment by fidencio** [comment]
> Taking a look at this error (the math doesn't add up to what I'm seeing locally):
> 
> ```
> cgroups.go:20:13: fieldalignment: struct with 64 pointer bytes could be 48 (govet)
> 17241
> type Cgroup struct {
> 17242
>             ^
> ```

```
fidencio@quino ~/go/src/github.com/kata-containers/kata-containers $ git diff
diff --git a/src/runtime/virtcontainers/pkg/cgroups/cgroups.go b/src/runtime/virtcontainers/pkg/cgroups/cgroups.go
index f8cf49bb..a5adfcc6 100644
--- a/src/runtime/virtcontainers/pkg/cgroups/cgroups.go
+++ b/src/runtime/virtcontainers/pkg/cgroups/cgroups.go
@@ -18,10 +18,11 @@ import (
 )
 
 type Cgroup struct {
-       path    string
-       devices []specs.LinuxDeviceCgroup
+       cgroup cgroups.Cgroup
+       path   string
+
        cpusets *specs.LinuxCPU
-       cgroup  cgroups.Cgroup
+       devices []specs.LinuxDeviceCgroup
 
        sync.Mutex
 }
```

I sincerely wish the compiler would be take the bullet and do this for us.

**Comment by egernst** [comment]
Seeing failures from our favorite test, k8s-oom.bats. Restarting jenkins-ci-fedora-32-crio ...

**Comment by fidencio** [comment]
Added & removed the "wip" label to get the static-checks running.

@egernst https://github.com/kata-containers/kata-containers/pull/2332/commits/ade182bdfd426fbed9b4e16bcdac694c85a9969e shouldn't be part of this PR.  If the static checks pass now, please, update the PR (I tried, but seems that I don't have enough permissions), and let's try to get a second reviewer for this one (hey @devimc! :-))

**Comment by Jakob-Naucke** [comment]
I have a potential fix for what happened there, currently testing internally for a couple of days because I'm not so sure -- /retest-s390x

**Comment by sameo** [comment]
@fidencio I guess we're keeping that one out of 2.2?

**Comment by fidencio** [comment]
> @fidencio I guess we're keeping that one out of 2.2?

Yep, it came too late for 2.2, unfortunately, but I think we should get it merged ASAP.  Let me see if we can get all the CIs green.

**Comment by fidencio** [comment]
@ananos, mind to take a look at this one?  I am afraid this firecracker issue may be real.  This is running with the jailer enabled, by the way.

**Comment by ananos** [comment]
> @ananos, mind to take a look at this one? I am afraid this firecracker issue may be real. This is running with the jailer enabled, by the way.
will do -- I think that something happens here: https://github.com/kata-containers/kata-containers/blob/9bbaa66f3973a91e79752a4237d3ac79e80ab47c/src/runtime/virtcontainers/fc.go#L1169 or two lines below that.

**Comment by ananos** [comment]
re: the fc checks failing, the issue is the following:

https://github.com/firecracker-microvm/firecracker/blob/9b9030d9f4fcfd3e808166ae8ee2147a9d9249df/vmm/src/lib.rs#L1260 

vs

https://github.com/firecracker-microvm/firecracker/blob/e6fe6bdcdf3f12b6879fd0ddd1b85e7fb144e217/src/vmm/src/vstate/vcpu/mod.rs#L244

Apparently, the code was not being executed since firecracker v0.19.1 (where it was working). 

Issue: #2592 
PR that fixes that: #2593

**Comment by fidencio** [comment]
@ananos, thanks a ton for fixing the firecracker CI!

This PR will still need another rebase (due to #2613), but all the tests should be green after that.
Nice work, to everyone involved!

**Comment by fidencio** [comment]
@Jakob-Naucke, I don't think the s390x failure is related to this PR, but I'd like to double check with you.

**Comment by fidencio** [comment]
> @Jakob-Naucke, I don't think the s390x failure is related to this PR, but I'd like to double check with you.

ops, and it seems I commented on an outdated page.  Let's see if it fails again.

**Comment by Jakob-Naucke** [comment]
yes, cf. #2618. It's a little hard to debug because sometimes it doesn't happen 10 times in a row.

**Review by egernst — APPROVED** [review]

**Comment by c3d** [comment]
@sameo As a heads-up, @fgiudici believes that the vendoring in this PR may have broken metrics in the `systemd` case. He believes that the code that dealt with `systemd` cgroups transparently may have been broken / removed. I will let him fill in with more details when he has them (he's investigating).

**Pull request merged**
