### PR TITLE
tools: delete unused param from get_from_kata_deps callers

### LINKED ISSUE #4245: Delete the second parameter of get_from_kata_deps in shell scripts
The second parameter kata version of `get_from_kata_deps` is deleted by https://github.com/kata-containers/kata-containers/commit/a09e58fa80ae81c0d336d9a782da4f38f9492da1 , all the caller should delete it too if they are explicitly using it.

### PR DESCRIPTION
**Pull request by r4f4**
The param was deleted by a09e58fa80ae81c0d336d9a782da4f38f9492da1, so
update the callers not to use it.

Fixes #4245

Signed-off-by: Rafael Fonseca <r4f4rfs@gmail.com>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks for raising @r4f4!

lgtm

**Review by gkurz — COMMENTED** [review]
LGTM @r4f4. Just one request : the `kata_version` variable isn't used anymore in the clh and fc scripts, please drop it as well now.

**Review by gkurz — APPROVED** [review]
Thanks @r4f4 !

**Pull request merged**
