### PR TITLE
agent: Set LIBC=gnu for ppc64le arch by default

### PR DESCRIPTION
**Pull request by bpradipt**
Fixes: #812

Signed-off-by: Pradipta Kr. Banerjee <pradipta.banerjee@gmail.com>

### CODE REVIEW

**Review by fidencio — COMMENTED** [review]
@bpradipt,

I'm on the fence on silently setting the toolchain for a different one based on the arch.
I'd prefer if we raise a warning saying "LIBC is set to $LIBCas musl is not supported for $ARCH". Does this sound reasonable?

**Comment by bpradipt** [comment]
> @bpradipt,
> 
> I'm on the fence on silently setting the toolchain for a different one based on the arch.
> I'd prefer if we raise a warning saying "LIBC is set to $LIBCas musl is not supported for $ARCH". Does this sound reasonable?

@fidencio yeah that's sound reasonable as well.. Can provide a warning so that the right variable can be set during invocation

**Comment by fidencio** [comment]
> > @bpradipt,
> > I'm on the fence on silently setting the toolchain for a different one based on the arch.
> > I'd prefer if we raise a warning saying "LIBC is set to $LIBCas musl is not supported for $ARCH". Does this sound reasonable?
> 
> @fidencio yeah that's sound reasonable as well.. Can provide a warning so that the right variable can be set during invocation

@bpradipt, I'd suggest you still set the default to gnu on Power, but **also** let the user know that.
So, please, just add a warning to the if branch where you're overriding LIBC to gnu. :-)

**Review by fidencio — APPROVED** [review]
lgtm!

Thanks, Pradipta!

**Review by bergwolf — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Thanks @bpradipt.

ooi, is there a musl bug URL you could reference in the commit and this warning message?

**Comment by bpradipt** [comment]
> Thanks @bpradipt.
> 
> ooi, is there a musl bug URL you could reference in the commit and this warning message?

@jodh-intel will providing a link to supported platforms help ? - https://doc.rust-lang.org/nightly/rustc/platform-support.html
I'm not aware of any bug URL, but I can definitely explore and check with few folks if it's a must.

**Comment by jodh-intel** [comment]
Hi @bpradipt - I'm still a little confused by this. musl itself does seem to support ppc64 fwics: https://musl.libc.org/doc/1.1.24/manual.html. Should the message state that the rust `powerpc64le-unknown-linux-musl` target is "unreliable" instead? ooi, what actually happens if you run `rustup target add powerpc64le-unknown-linux-musl` and re-run the build?

**Review by devimc — APPROVED** [review]

**Comment by bpradipt** [comment]
> Hi @bpradipt - I'm still a little confused by this. musl itself does seem to support ppc64 fwics: https://musl.libc.org/doc/1.1.24/manual.html. Should the message state that the rust `powerpc64le-unknown-linux-musl` target is "unreliable" instead? ooi, what actually happens if you run `rustup target add powerpc64le-unknown-linux-musl` and re-run the build?

Hi @jodh-intel yeah musl does have ppc64le support.  As you pointed you a better message is to mention that rust target is unreliable or unavailable. Given that the target is not available today, I will change the warning to `powerpc64le-unknown-linux-musl target is unavailable`.  Does that make sense ?


Currently installing a musl target  throws this error on ppc64le 
```
error: target 'powerpc64le-unknown-linux-musl' not found in channel.  Perhaps check https://forge.rust-lang.org/release/platform-support.html for available targets
``` 

and  `rustup target add powerpc64le-unknown-linux-musl` throw this
```
error: toolchain 'stable-powerpc64le-unknown-linux-gnu' does not contain component 'rust-std' for target 'powerpc64le-unknown-linux-musl'
```

**Comment by jodh-intel** [comment]
Thanks @bpradipt - that would be clearer I think.

**Comment by bpradipt** [comment]
> Thanks @bpradipt - that would be clearer I think.

done.. thanks for the pointer @jodh-intel

**Review by jodh-intel — APPROVED** [review]
Thanks @bpradipt.

lgtm

**Pull request merged**
