### PR TITLE
runtime-rs: built-in Dragonball sandbox part IV - unit tests

### PR DESCRIPTION
**Pull request by studychao**
This pull request introduces more unit tests for Dragonball.

### CODE REVIEW

**Comment by bergwolf** [comment]
@studychao Could you rebase the PR as #4515 is merged?

**Comment by jodh-intel** [comment]
Any update on this @studychao?

**Comment by studychao** [comment]
Hi @jodh-intel , I will handle this PR this week.:)

**Comment by studychao** [comment]
@jodh-intel Sorry James, I was busy with runtime-rs CI problems and didn't have capacility to due with this PR. :(

I'll  handle this after we solve the CI problems

**Comment by studychao** [comment]
Hi Jodh, we are working on this PR and testing UTs with Kata CI. I'll ping you when we finish the test for UTs.

**Comment by studychao** [comment]
> Any update on this @studychao?

And we have reopened a PR #4900 because runtime-rs has been merged into main

**Comment by studychao** [comment]
Close this since #4900 will continue the work

**Pull request closed without merging**
