### PR TITLE
versions: Update cloud-hypervisor to release v0.12.0

### PR DESCRIPTION
**Pull request by likebreath**
Highlights for cloud-hypervisor version v0.12.0 include: removal of
`vhost-user-net` and `vhost-user-block` self spawning, migration of
`vhost-user-fs` backend, ARM64 enhancements with full support of
`--watchdog` for rebooting, and enhanced `info` HTTP API to include the
details of devices used by the VM including VFIO devices.

Fixes: #1315

Signed-off-by: Bo Chen <chen.bo@intel.com>

Forward porting https://github.com/kata-containers/runtime/pull/3124 (issue https://github.com/kata-containers/runtime/issues/3123).

### CODE REVIEW

**Review by devimc — APPROVED** [review]
thanks @likebreath

**Comment by likebreath** [comment]
Converting to draft as there are a few of pending PRs related to changing CLH CI (https://github.com/kata-containers/kata-containers/pull/1302 and https://github.com/kata-containers/tests/pull/3172). Hold this PR until those pending PRs are landed.

**Review by jcvenegas — APPROVED** [review]

**Review by egernst — APPROVED** [review]

**Pull request merged**
