### PR TITLE
virtcontainers: Fix incorrect scripts path

### PR DESCRIPTION
**Pull request by Bevisy**
modify to the correct relative path

Fixes: #2515

Signed-off-by: Binbin Zhang <binbin36520@gmail.com>

### CODE REVIEW

**Review by liubin — APPROVED** [review]

**Review by bergwolf — APPROVED** [review]

**Comment by fidencio** [comment]
I am surprised that this is happening.
@Bevisy, could you give us more details about the environment you're hitting this? Mainly on how / where you cloned both kata-containers & tests repos?

**Comment by fidencio** [comment]
Adding the `do-not-merge` label for now.

**Comment by Bevisy** [comment]
> @Bevisy, could you give us more details about the environment you're hitting this? Mainly on how / where you cloned both kata-containers & tests repos?

Just clone repo kata-containers and tests in {GOPATH}, like:
```sh
$ tree -L 1 $GOPATH/src/github.com/kata-containers
$GOPATH/src/github.com/kata-containers
├── kata-containers
└── tests
```
When the command is executed in the directory, the following error is reported
When excuting `make check...` in the path `kata-containers/kata-containers/src/runtime/virtcontainers`, the following error is reported:
```sh
$ make check-go-test           
bash /home/zbb/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/../.ci/go-test.sh \
        /usr/bin/virtcontainers/bin/test/hook
bash: /home/zbb/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/../.ci/go-test.sh: No such file or directory
make: *** [Makefile:48: check-go-test] Error 127

$ make check-go-static
bash /home/zbb/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/../.ci/static-checks.sh
bash: /home/zbb/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/../.ci/static-checks.sh: No such file or directory
make: *** [Makefile:45: check-go-static] Error 127
```
By looking at the directory structure, I think it should be specified as a script under the same repository directory `kata-containers/kata-containers/ci`, like `go-test.sh`, `static-checks.sh`. These two scripts will call the script corresponding to the tests repository.
Maybe I should change the `ci/static-checks.sh` script to support the specified directory instead of the whole project.

**Comment by fidencio** [comment]
> > @Bevisy, could you give us more details about the environment you're hitting this? Mainly on how / where you cloned both kata-containers & tests repos?
> 
> Just clone repo kata-containers and tests in {GOPATH}, like:
> 
> ```shell
> $ tree -L 1 $GOPATH/src/github.com/kata-containers
> $GOPATH/src/github.com/kata-containers
> ├── kata-containers
> └── tests
> ```
> 
> When excuting `make check...` in the path `kata-containers/kata-containers/src/runtime/virtcontainers`, the following error is reported:
> 
> ```shell
> $ make check-go-test           
> bash /home/zbb/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/../.ci/go-test.sh \
>         /usr/bin/virtcontainers/bin/test/hook
> bash: /home/zbb/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/../.ci/go-test.sh: No such file or directory
> make: *** [Makefile:48: check-go-test] Error 127
> 
> $ make check-go-static
> bash /home/zbb/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/../.ci/static-checks.sh
> bash: /home/zbb/go/src/github.com/kata-containers/kata-containers/src/runtime/virtcontainers/../.ci/static-checks.sh: No such file or directory
> make: *** [Makefile:45: check-go-static] Error 127
> ```


Hmmm. That's interesting and we should **also** ensure we run this test as part of the static checks (https://github.com/kata-containers/kata-containers/blob/main/.github/workflows/static-checks.yaml).

Currently the static statics take advantage of the tests we have as part of the `tests` repo, which does contain the `go-test.sh` and `static-checks.sh` binaries.

Take a look at https://github.com/kata-containers/kata-containers/blob/87152fffcbbe467be44aa6c9386e24919272970d/ci/lib.sh#L42

> 
> By looking at the directory structure, I think it should be specified as a script under the same repository directory `kata-containers/kata-containers/ci`, like `go-test.sh`, `static-checks.sh`. These two scripts will call the script corresponding to the tests repository.

Your fix is correct, but I think we have a deeper problem.  Shall we keep using the scripts from the tests repo?  If so, we should get rid of the ones from the kata-containers repo, and ensure we always clone the tests repo & run the tests from there.  If not, we should ensure we run the tests as they're as part of our static checks (not using the ones from the tests repo).

@GabyCT, opinions?

**Comment by Bevisy** [comment]
There are only two checks failed. How can we trigger them? using "\/test-firecracker" and "\/test-metrics"?

**Comment by Bevisy** [comment]
Finally, all ci check passed :smile:

**Pull request merged**
