### PR TITLE
dnm: runtime: Set 50G memory offset

### PR DESCRIPTION
**Pull request by devimc**
do not merge

fixes #123456789

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by devimc** [comment]
@pohly performance numbers look good http://jenkins.katacontainers.io/job/kata-containers-2.0-metrics-ubuntu-20-04-PR/763/
but I think that the runtime shouldn't set a memory offset by default, this is responsibility of cluster operator (final user), WDYT?
would you like to discuss this in the next architecture committee meeting?

**Comment by pohly** [comment]
> @pohly performance numbers look good http://jenkins.katacontainers.io/job/kata-containers-2.0-metrics-ubuntu-20-04-PR/763/
> but I think that the runtime shouldn't set a memory offset by default, this is responsibility of cluster operator (final user), WDYT?

But there is a default already, isn't it? It's just too small. I don't see why that default shouldn't be increased if it can be done without causing some drawbacks. It would make Kata Containers easier to install and use.

> would you like to discuss this in the next architecture committee meeting?

Sorry, I'm a bit busy at the moment and probably won't have the time.

**Comment by devimc** [comment]
> But there is a default already, isn't it? It's just too small. I don't see why that default shouldn't be increased if it can be done without causing some drawbacks. It would make Kata Containers easier to install and use.

the default is equals to actual host's memory, otherwise memory hot plug wouldn't work

> Sorry, I'm a bit busy at the moment and probably won't have the time.

ok

**Pull request closed without merging**
