### PR TITLE
virtcontainers: add unit tests for container.go

### PR DESCRIPTION
**Pull request by Amulyam24**
Fixes: #268

Signed-off-by: Amulyam24 <amulmek1@in.ibm.com>

### CODE REVIEW

**Comment by fidencio** [comment]
@Amulyam24, can you try to run the `/test` command?  I've invited you to a group, which gives you the permissions to do so.

**Comment by Amulyam24** [comment]
Thanks @fidencio :) I'm not sure if its working though?

**Comment by fidencio** [comment]
> Thanks @fidencio :) I'm not sure if its working though?

It's not working because first you need to accept a GitHub invitation sent to your email.  I think that accepting that and retrying will give us the results we're expecting.

**Comment by Amulyam24** [comment]
> > Thanks @fidencio :) I'm not sure if its working though?
> 
> It's not working because first you need to accept a GitHub invitation sent to your email. I think that accepting that and retrying will give us the results we're expecting.

Got it, Thanks @fidencio.

**Review by amshinde — APPROVED** [review]

**Review by sameo — APPROVED** [review]

**Pull request merged**
