### PR TITLE
gpu: Do not pass-through PCI (Host) Bridges

### PR DESCRIPTION
**Pull request by zvonkok**
On some systems a GPU is in a IOMMU group with a PCI Bridge and PCI Host Bridge. Per default no PCI Bridge needs to be passed-through. When scanning the IOMMU group, ignore devices with a 0x60 class ID prefix.

Fixes: #6663

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
looks sensible to me, thanks @zvonkok!

**Review by fengwang666 — APPROVED** [review]

**Pull request merged**
