### PR TITLE
doc: Add documentation for the virtualization reference architecture

### PR DESCRIPTION
**Pull request by zvonkok**
Adding detailed information about the virtualization reference architecture. 

Fixes: #4041

DependsOn: https://github.com/kata-containers/tests/pull/5703

Signed-off-by: Zvonko Kaiser <zkaiser@nvidia.com>

### CODE REVIEW

**Comment by zvonkok** [comment]
@bergwolf @fidencio @jodh-intel @egernst FYI, PTAL this is intended to work with ANY PCIe device that is capable of doing P2P, not only NV GPUs.

**Review by bergwolf — APPROVED** [review]
Very informative, thanks!

**Comment by bergwolf** [comment]
closing and reopening to trigger the stale actions.

**Comment by bergwolf** [comment]
@zvonkok Please add a reference to the kata-vra.md file in `docs/design/README.md`

```
ERROR: Document docs/design/kata-vra.md is not referenced
```

**Comment by zvonkok** [comment]
@bergwolf https://github.com/kata-containers/tests/pull/5703

**Review by lifupan — APPROVED** [review]

**Pull request merged**
