### PR TITLE
gha: ci: Add skeleton of vfio job

### PR DESCRIPTION
**Pull request by jepio**
This job will run on a nested virt capable Azure VM (improving test concurrency). This is just a placeholder while we adapt the test to GHA.

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks a lot @jepio!

**Review by zvonkok — APPROVED** [review]
LGTM as a skeleton, lets just make sure we get this: https://github.com/kata-containers/tests/pull/5729 incorporated for GPU/DPU accelerator in general testing.

**Comment by fidencio** [comment]
ppc64 CI passed but didn't return back :-/

Rerunning.

**Comment by fidencio** [comment]
http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-ppc64le-main-PR/2388/console

**Comment by fidencio** [comment]
I am actually going to make the CI non-required, merge this one, and make it required again.

**Pull request merged**
