### PR TITLE
CCv0: Update containerd version to be based on 1.6.1

### PR DESCRIPTION
**Pull request by stevenhorsman**
Update containerd to point to Wang Lei's rebase branch so we can test it

Fixes: https://github.com/kata-containers/kata-containers/issues/3830
Signed-off-by: stevenhorsman <steven@uk.ibm.com>

### CODE REVIEW

**Comment by wllenyj** [comment]
@stevenhorsman Thank you for your work.
I have merged CC-main, you can continue at this.

**Comment by stevenhorsman** [comment]
> @stevenhorsman Thank you for your work. I have merged CC-main, you can continue at this.
> 
> And I gave CC-main tag v1.6.1.0, you can try to use it if it works for you.

Thank you very much for doing the rebase so swiftly :)

**Review by fidencio — APPROVED** [review]
lgtm. thanks @stevenhorsman!

**Pull request merged**
