### PR TITLE
agent: fix container stop error with signal SIGRTMIN+3

### PR DESCRIPTION
**Pull request by wxx213**
The nix::sys::signal::Signal package api cannot deal with SIGRTMIN+3,
directly use libc function to send the signal.

Fixes: #3990

Signed-off-by: Wang Xingxing <stellarwxx@163.com>

### CODE REVIEW

**Comment by wxx213** [comment]
Sorry, I just resolved the build issue, please have another try for the test.

**Comment by wxx213** [comment]
I just resolved the build and check issue, please have another try for the test.

**Comment by bergwolf** [comment]
@wxx213 There are still UT failures:
```
   --> rustjail/src/process.rs:286:32
    |
286 |         assert!(process.signal(Signal::SIGCONT).is_ok());
    |                                ^^^^^^ use of undeclared type `Signal`

```

**Comment by wxx213** [comment]
> @wxx213 There are still UT failures:
> 
> ```
>    --> rustjail/src/process.rs:286:32
>     |
> 286 |         assert!(process.signal(Signal::SIGCONT).is_ok());
>     |                                ^^^^^^ use of undeclared type `Signal`
> ```

I fixed it, please try again.

**Comment by bergwolf** [comment]
@wxx213 Could you backport this to stable-2.4 branch? We are about the cut the 2.4.0 release and this is a good candidate to be backported.

**Comment by wxx213** [comment]
> @wxx213 Could you backport this to stable-2.4 branch? We are about the cut the 2.4.0 release and this is a good candidate to be backported.

Ok, I will backport it to stable-2.4 branch.

**Comment by wxx213** [comment]
#4008

**Comment by wxx213** [comment]
#4008

**Review by liubin — APPROVED** [review]

**Pull request merged**
