### PR TITLE
docs: Update link to EFK stack docs

### LINKED ISSUE #3616: docs: EFK link outdated
The EFK link in [docs/how-to/how-to-import-kata-logs-with-fluentd.md](https://github.com/kata-containers/kata-containers/blob/36031056692158d5207311923752a558444a3ca9/docs/how-to/how-to-import-kata-logs-with-fluentd.md) is outdated and should probably point to https://github.com/kubernetes-sigs/instrumentation-addons/tree/master/fluentd-elasticsearch#running-efk-stack-in-production

### PR DESCRIPTION
**Pull request by hxtmdev**
See
https://github.com/kubernetes/kubernetes/commit/5d9b7ae9e5174f898d3b06c21cb2355e759bd94a#diff-ada96bec4aba13195248d6dd21ee67e333bead2bd898b81a1b089d53bd06b4d8R2820

Fixes #3616

### CODE REVIEW

**Comment by hxtmdev** [comment]
Removed link from commit message as per CI error, it can still be found in the PR description.

**Comment by egernst** [comment]
Thanks for the contribution @hxtmdev. LGTM; static checks may ask you to have a body to your commit message, but the change itself looks good!

**Review by snir911 — APPROVED** [review]
LGTM, thanks!

**Review by egernst — DISMISSED** [review]

**Review by egernst — APPROVED** [review]

**Comment by egernst** [comment]
(rebased on top of latest, since there was an issue with the static CI that was unrelated....)

**Review by snir911 — APPROVED** [review]
LGTM
This unrelated static CI issue still appears though

**Pull request merged**
