### PR TITLE
docs: Apply doc team review comments to README

### LINKED ISSUE #10: Fix doc review comments
#7 was merged inadvertently [*], so apply doc team review comments from #7.

---

[*] - as we don't have pullapprove enabled yet - see #9.

### PR DESCRIPTION
**Pull request by jodh-intel**
PR #7 was merged inadvertently, so apply the Documentation Team's
review comments to `README.md`.

Fixes #10.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Apologies @rcaballeromx - your suggested changes are over here. I'll also raise a PR for #9 to avoid any more inadvertent merges... ;)

**Comment by grahamwhaley** [comment]
but I think you need an @kata-containers/documentation ack (@rcaballeromx @klynnrif ) ack.

**Comment by jodh-intel** [comment]
ping @kata-containers/kata-containers

**Comment by grahamwhaley** [comment]
need an ack from one more of @kata-containers/kata-containers  I believe (the pullapprove approvers for this repo) - but, this fix is trivial enough that I'll force merge (you've had 16 days to object ;-) )

**Pull request merged**
