### PR TITLE
config: make virtio-fs part of standard kernel

### PR DESCRIPTION
**Pull request by egernst**
Basic virtio-fs support has made it upstream in the Linux kernel, as
well as in QEMU and Cloud Hypervisor. Let's go ahead and add it to the
standard configuration.

Since the device driver / DAX handling is still in progress for
upstream, we will want to still build a seperate experimental kernel for
those who are comfortable trading off bleeding edge stability/kernel
updates for improved FIO numbers.

Signed-off-by: Eric Ernst <eric.g.ernst@gmail.com>

### CODE REVIEW

**Comment by egernst** [comment]
@jodh-intel - can you help with updating travis so it doesn't check .configs for license header?

**Comment by jodh-intel** [comment]
@egernst - you owe me another virtual :beer:, or an :green_apple: :smile: - https://github.com/kata-containers/tests/pull/2961.

**Comment by egernst** [comment]
/test

rerunning CI now that travis was updated. Thanks @jodh-intel

**Review by likebreath — APPROVED** [review]

**Comment by egernst** [comment]
@devimc I don't think metrics are currently available on 2.0, but we did see a small bump in footprint test when enabling virtio-fs.  Can't do much about that.

**Review by chavafg — APPROVED** [review]

**Pull request merged**
