### PR TITLE
agent:cdh: fix unit tests about sealed secret

### PR DESCRIPTION
**Pull request by ChengyuZhu6**
The root cause is that the CDH client is a global variable, and unit tests `test_unseal_env` and `test_unseal_file` share this lock-free global variable, leading to resource contention and destruction. Merging the two unit tests into one `test_sealed_secret` will resolve this issue. Original commit: https://github.com/kata-containers/kata-containers/commit/31e09058af68a2f7e9c9685f505c7cad53148c8d

Fixes: #10403

### CODE REVIEW

**Comment by fidencio** [comment]
@ChengyuZhu6, please, do this in 2 commits.
1. Re-revert what was reverted
2. Add the fix

By doing this in this way, it makes more clear what the actual fix is.

**Comment by ChengyuZhu6** [comment]
> @ChengyuZhu6, please, do this in 2 commits.
> 
> 1. Re-revert what was reverted
> 2. Add the fix
> 
> By doing this in this way, it makes more clear what the actual fix is.

Done.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @ChengyuZhu6!

**Review by stevenhorsman — APPROVED** [review]
Passes all required tests, so LGTM. Thanks for the prompt fix @ChengyuZhu6!

**Pull request merged**
