### PR TITLE
modify virtio_net_dev_mgr.rs wrong code comments

### PR DESCRIPTION
**Pull request by zhaoxuat**

### CODE REVIEW

**Comment by liubin** [comment]
Thank you @zhaoxuat , but we have a [patch format](https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format) that is needed to merge the PR.

**Comment by zhaoxuat** [comment]
> Thank you @zhaoxuat , but we have a [patch format](https://github.com/kata-containers/community/blob/main/CONTRIBUTING.md#patch-format) that is needed to merge the PR.

done

**Comment by studychao** [comment]
Welcome @zhaoxuat !

**Review by Ji-Xinyou — APPROVED** [review]

**Review by studychao — APPROVED** [review]

**Review by liubin — APPROVED** [review]

**Pull request merged**
