### PR TITLE
clh: Consolidate the code path for device unplug

### PR DESCRIPTION
**Pull request by likebreath**
Forward port PR kata-containers/runtime#3013 for issue kata-containers/runtime#3001.

Fixes: #1076

Signed-off-by: Bo Chen <chen.bo@intel.com>

### CODE REVIEW

**Comment by likebreath** [comment]
@chavafg Can you please help take a look at the failures on centos and debian? I was assuming those PRs are only testing with qemu, while the PR only makes changes to clh. Any questions or comments, please let me know. Thank you.

**Comment by chavafg** [comment]
Hi @likebreath, these jobs have been failing for some days now. I know @fidencio was taking a look as this seems to only happen with cri-o. This is the issue where he is documenting his findings: https://github.com/kata-containers/kata-containers/issues/1080 

I am not sure what is the latest status, but Isee that yesterday and today some of the job runs ended well, so I have restarted both jobs. 
Another option is to disable the test while the issue gets investigated and solved. wdyt @fidencio?

Thanks.

**Review by egernst — APPROVED** [review]

**Comment by fidencio** [comment]
> Another option is to disable the test while the issue gets investigated and solved. wdyt @fidencio?

@chavafg, Today I ended up opening an issue against CRI-O (https://github.com/cri-o/cri-o/issues/4353), with a patch already submitted (https://github.com/cri-o/cri-o/pull/4354).  Also, I've opened an issue in the `kata-containers/tests` repo to disable the test (https://github.com/kata-containers/tests/issues/3033), also with a patch submitted (https://github.com/kata-containers/tests/pull/3032).  I'll take care of bumping CRI-O's version and re-enabling the disabled test as soon as CRI-O has a new release.

**Comment by chavafg** [comment]
thanks @fidencio

**Review by amshinde — APPROVED** [review]

**Pull request merged**
