### PR TITLE
snap: fix snap release channel

### LINKED ISSUE #1174: Update snap-release workflow
Update snap-release workflow according to the new changes introduced in https://github.com/kata-containers/kata-containers/pull/1173 - Kata Containers 2.x should be available in the cadidate channel

### PR DESCRIPTION
**Pull request by devimc**
According to the new snap document
`docs/install/snap-installation-guide.md`, Kata Containers 2.x should
be available in the snapcraft `candidate` channel.

fixes #1174

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @devimc!

**Review by wainersm — APPROVED** [review]
That was easy to review :)

**Comment by wainersm** [comment]
@fidencio Side note: the guide to install on Fedora is out-dated since we don't have kata containers 2.0 packages yet. Perhaps open an issue so we track that work?

**Comment by fidencio** [comment]
> @fidencio Side note: the guide to install on Fedora is out-dated since we don't have kata containers 2.0 packages yet. Perhaps open an issue so we track that work?

Yep, and link the CentOS issue there as well. Please, /cc @etrunko on the issue, as he has taken over the Fedora packaging.

**Comment by fidencio** [comment]
* **jenkis-ci-centos-8**:
```
21:15:25 Error: 
21:15:25  Problem 1: cannot install the best update candidate for package authselect-compat-1.1-2.el8.x86_64
21:15:25   - nothing provides authselect(x86-64) = 1.2.1-2.el8 needed by authselect-compat-1.2.1-2.el8.x86_64
21:15:25  Problem 2: cannot install the best update candidate for package python3-pip-9.0.3-16.el8.noarch
21:15:25   - nothing provides platform-python-pip = 9.0.3-18.el8 needed by python3-pip-9.0.3-18.el8.noarch
21:15:25 (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
21:15:25 Failed at 41: sudo -E yum -y update
21:15:25 ++ handle_error 69
21:15:25 ++ local exit_code=1
21:15:25 ++ local line_number=69
21:15:25 ++ echo 'Failed at /tmp/jenkins/workspace/kata-containers-2.0-centos-PR/ci_entry_point.sh +69: .ci/jenkins_job_build.sh "${repo_to_test}"'
21:15:25 Failed at /tmp/jenkins/workspace/kata-containers-2.0-centos-PR/ci_entry_point.sh +69: .ci/jenkins_job_build.sh "${repo_to_test}"
21:15:25 ++ exit 1
21:15:25 Build step 'Execute shell' marked build as failure
```
@pbrezina, zdar!, any known workaround for the authselect issue?

**Pull request merged**
