### PR TITLE
CCv0: Adding CDI support for cold and hot-plug of VFIO devices

### PR DESCRIPTION
**Pull request by zvonkok**
We need to do proper sandbox sizing when we're doing cold-plug introduce CDI, the de-facto standard for enabling devices in containers. containerd will pass-through annotations for accumulated CPU,Memory and now CDI devices. With that information sandbox sizing can be derived correctly.

Fixes: #7331

For this to work I need the main->CCv0 PR to happen first.

### CODE REVIEW

**Comment by zvonkok** [comment]
The vendor dir was not updated, https://github.com/confidential-containers/containerd/pull/14/files#diff-ff07e6b89901da58ad89827db9dd4dbb835f61109f13ecc37be032cd990ce06a here is the function

**Comment by stevenhorsman** [comment]
SEV is failing with:
```
not ok 3 [cc][kubernetes][containerd][sev] Test SEV encrypted container launch success with NO measurement
```
The same thing happened on the `main` -> `CCv0` PR the first time, so I'll try re-running it...

**Comment by fidencio** [comment]
> The same thing happened on the `main` -> `CCv0` PR the first time, so I'll try re-running it...

It seems like a race in the tests, and it's worth debugging it ... /cc @ryansavino @UnmeshDeodhar @fitzthum @larrydewey

**Comment by stevenhorsman** [comment]
After some re-queues it is just waiting to get feedback from TDX CLH - @arronwy - can you let us know if the tests passed and just the reporting back isn't working, or is there are failure? Thanks!

**Review by stevenhorsman — APPROVED** [review]
I'm not an expert, but this looks okay to me and 99% of the changes are vendor packages, so as long as the tests are all good we should be ok

**Comment by stevenhorsman** [comment]
I've added `do-not-merge` as the 0.7.0 'release champions' get to have the say on anything being merged at this point.

**Comment by zvonkok** [comment]
Verified the `containerd` and CCv0 changes on our internal systems, works as expected.

**Comment by fidencio** [comment]
CLH TDX tests: http://10.112.240.228:8080/job/kata-containers-CCv0-cloud-hypervisor-TDX-CRI_CONTAINERD_K8S-PR/995/console

**Pull request merged**
