### PR TITLE
runtime: delete sandboxlist.go and sandboxlist_test.go

### PR DESCRIPTION
**Pull request by liubin**
Delete sandboxlist.go and sandboxlist_test.go under virtcontainers package.

Fixes: #1078

Signed-off-by: bin liu <bin@hyper.sh>

### CODE REVIEW

**Review by bergwolf — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Thanks @liubin.

**Review by lifupan — APPROVED** [review]

**Comment by devimc** [comment]
@likebreath CLH CI is failing, any thoughts?
```
08:25:09 ERROR: 3 pods left and found at /run/vc/sbs
08:25:09 Failed at 1: popd
08:25:09 Makefile:147: recipe for target 'kubernetes' failed
08:25:09 make: *** [kubernetes] Error 1
```

**Comment by likebreath** [comment]
Looks like to be an issue on cleanup, given all tests are actually passing. Good thing is that it seems to be fairly reproducible. We will need to locate the problematic tests and collect more logs to root-cause the issue. 

Please feel free to setup a local environment to collect those information if you have the cycle. I can take a closer look at it later this week or earlier next week. Any thoughts, please just share. Thanks.

**Comment by liubin** [comment]
@likebreath @devimc The bad thing is that `jenkins-ci-ubuntu-1804-cloud-hypervisor-k8s-containerd-2.0` only fails for this PR :-(

I'm trying to enable debug logs for kubelet ( https://github.com/kata-containers/tests/pull/3040 ) and get off noise logs (https://github.com/kata-containers/kata-containers/pull/1094) to try if can I get some hint.

**Comment by liubin** [comment]
Don't sure if has something like this https://github.com/kubernetes/kubernetes/issues/60987

**Comment by likebreath** [comment]
@liubin Just merged the kata-containers/tests#3040 and restarted the clh CI. Let's see whether we can get more information from the logs. I am wondering are we enabling full debug and collecting logs for kata-runtime (as our CI artifacts)?

**Comment by liubin** [comment]
Add `do-not-merge`, there may be an potential bug.

@likebreath Kata's log level is debug and all  logs are collected in CI job's artifacts.

**Comment by liubin** [comment]
After some dig, I think this may be a random issue may occur in any environment, the root cause is that `cleanupVM` in `clh.go` is not called for some reason. I'll create a [new issue](https://github.com/kata-containers/kata-containers/issues/1098) to track it.

**Comment by devimc** [comment]
@liubin please rebase it to fix the VFIO CI, sorry for inconvenience

**Pull request merged**
