### PR TITLE
sandbox: Allow the device to be accessed,such as /dev/null and /dev/u…

### PR DESCRIPTION
**Pull request by Bevisy**
…random

If the device has no permission, such as /dev/null, /dev/urandom,
it needs to be added into cgroup.

Fixes: #2615

Signed-off-by: Binbin Zhang <binbin36520@gmail.com>

### CODE REVIEW

**Comment by fidencio** [comment]
@amshinde, mind to review this one, as it's based on your request for changes?

**Comment by fidencio** [comment]
@amshinde, @sameo, would you mind to take a look at this one?  I'd really like to have it merged as part of 2.3.0-alpha1 and its backport as part of 2.2.1.

**Review by amshinde — APPROVED** [review]

**Review by fidencio — APPROVED** [review]
lgtm, thank @Bevisy!

**Pull request merged**
