### PR TITLE
runtime: suppport split firmware

### LINKED ISSUE #3583: support split firmware
firmware can be split into FIRMWARE_VARS.fd (UEFI variables as configuration) and FIRMWARE_CODE.fd (UEFI program image).  UEFI variables can be customized per each user while UEFI code is kept same.

### PR DESCRIPTION
**Pull request by devimc**
firmware can be split into FIRMWARE_VARS.fd (UEFI variables as
configuration) and FIRMWARE_CODE.fd (UEFI program image). UEFI
variables can be customized per each user while UEFI code is kept same.

fixes #3583

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @devimc!

**Comment by devimc** [comment]
@Jakob-Naucke is s390x CI unstable ?

**Comment by devimc** [comment]
centos and s390x are unstable and failing a lot, see http://jenkins.katacontainers.io/job/kata-containers-2.0-centos-PR/ and http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-s390x-PR/

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
