### PR TITLE
config: Fix description for OCI hooks

### PR DESCRIPTION
**Pull request by ManaSugi**
- Update url for osbuilder
- Fix typo about poststart

Fixes: #2260

Signed-off-by: Manabu Sugimoto <Manabu.Sugimoto@sony.com>

### CODE REVIEW

**Review by egernst — APPROVED** [review]

**Review by lifupan — APPROVED** [review]

**Review by liubin — APPROVED** [review]

**Comment by fidencio** [comment]
Let me add the do-not-merge label till the 2.2.0-alpha1 release is out.

**Comment by fidencio** [comment]
I'm really sorry for the disruption we had, but I'm glad to say that 2.2.0-alpha1 release is finally out and we're removing all the `do-not-merge` labels that were added due to this.

Thanks a lot for your understanding and happy hacking!

**Pull request merged**
