### PR TITLE
Dragonball: migrate dragonball-sandbox crates to Kata

### PR DESCRIPTION
**Pull request by studychao**
In order to make it easier for developers to contribute to Dragonball, we decide to migrate all dragonball-sandbox crates to Kata.

fixes: #7262

### CODE REVIEW

**Comment by fidencio** [comment]
@studychao, I'm just adding the `do-not-merge` label to ensure this does not get merged before we cut the -rc0 release.

**Comment by studychao** [comment]
> @studychao, I'm just adding the `do-not-merge` label to ensure this does not get merged before we cut the -rc0 release.

That's alright~ I am just trying to pass all CI first. We could merge this before the release.

**Review by fidencio — APPROVED** [review]
As discussed in the Kata Containers Architecture Committee meeting of July 11th, let's get it merged considering that all tests are passing.

We've decided to have this merged **before** cutting the rc0 release, as it'll make it the backport process easier for any issue found for the stable branch.

**Review by jiangliu — APPROVED** [review]

**Review by lifupan — APPROVED** [review]

**Pull request merged**
