### PR TITLE
tests/k8s: skip custom DNS tests on confidential jobs

### PR DESCRIPTION
**Pull request by wainersm**
This test has failed in confidential runtime jobs. Skip it until we don't have a fix.

Fixes: #9663

### CODE REVIEW

**Comment by wainersm** [comment]
@ryansavino @fidencio @BbolroC could you please review it? The `is_confidential_runtime_class` should return true to qemu-tdx, qemu-sev, qemu-snp and qemu-se. In particular I'm not sure if filtering qemu-se is enough if I need to use arch (s390x).

**Review by fitzthum — APPROVED** [review]
cc @AdithyaKrishnan

**Review by BbolroC — APPROVED** [review]
LGTM, thanks @wainersm !

**Review by fidencio — APPROVED** [review]
lgtm, thanks @wainersm!

**Pull request merged**
