### PR TITLE
govmm: Bring the project in

### PR DESCRIPTION
**Pull request by fidencio**
This is a PR that basically brings govmm into the kata-containers repo, under `src/runtime/pkg/govmm`, and does nothing apart from that.

The way to bring all the commits in and still keep the history was:
```
git remote add -f govmm https://github.com/kata-containers/govmm
git merge -s ours --no-commit --allow-unrelated-histories govmm/main
git read-tree --prefix=src/runtime/pkg/govmm/ -u govmm/main
git commit -m "Merge govmm into kata-containers"
```

This is based on https://mirrors.edge.kernel.org/pub/software/scm/git/docs/howto/using-merge-subtree.html and aligns with the discussions we had in the past about the future of govmm.

We'll need further commits to actually start using govmm from the kata-containers repo, but those will come later as this commit will, most likely, have to be merged with a `force-skip-ci` for now.

### CODE REVIEW

**Comment by devimc** [comment]
adding do-not-merge label, latest version of govmm is not working with kata, I'm fixing it here https://github.com/kata-containers/kata-containers/pull/3460

**Comment by devimc** [comment]
removing do-not-merge label, latest kata is not working with the latest govmm

**Comment by fidencio** [comment]
I am adding the `do-not-merge` back, in order to ensure I can test things on my fork first (there's a short series making static checks and other things happy that depends on this one).

**Comment by fidencio** [comment]
Both ARM and s390x CIs are not respecting the `force-skip-ci` label and that's the reason they're failing, and this failure is expected.
Let me cc @Jakob-Naucke and @jongwu for awareness here, as this is something that should be fixed on their side.

**Comment by fidencio** [comment]
Once this PR gets merged, I will open a follow-up PR switching them to using GoVMM from inside kata-containers.
What will be raised, which is already passing all the CIs, can be seen on my own fork: https://github.com/fidencio/kata-containers/pull/22

I'd appreciate if we can review / unblock this one sooner than later.

With everything mention, I am dropping the `do-not-merge` label.

**Review by Jakob-Naucke — APPROVED** [review]
Looking at https://github.com/fidencio/kata-containers/pull/22, I think the GHA should also be updated. I'll look into the force-skip-ci thing.

**Comment by fidencio** [comment]
> Looking at [fidencio#22](https://github.com/fidencio/kata-containers/pull/22), I think the GHA should also be updated. I'll look into the force-skip-ci thing.

Yesterday I've addressed all of those as part of https://github.com/kata-containers/kata-containers/pull/3472, which is already merged.  Let me know if there's something missing from those.

Note, https://github.com/kata-containers/kata-containers/pull/3486 is a really small follow-up from that.

**Review by devimc — APPROVED** [review]

**Comment by fidencio** [comment]
As https://github.com/kata-containers/tests/pull/4385 got merged, let's just do /retest-s390x and /retest-arm

**Comment by fidencio** [comment]
The ARM CI has proven that https://github.com/kata-containers/tests/pull/4385 works as expected, and I'll take advantage of the s390x CI being non-required and I will go ahead and have this one merged.

There's a coming up PR to be open in order to have all the tests green, and that should come in a few minutes.

**Comment by bergwolf** [comment]
@fidencio Why `force-skip-ci` in the PR? Did it cause the static checker to skip too?

**Comment by fidencio** [comment]
> @fidencio Why `force-skip-ci` in the PR? Did it cause the static checker to skip too?

Tao, yes, I explicitly set this to skip every single thing, and let me explain why.

Without the `force-skip-ci` label, the checks would simply break when checking the commit message of all the history being imported, and that would break as, for instance "ciao-launcher" is not a valid subsystem for our cause, but it's the history of GoVMM and it was a valid commit by the time it was merged there.

While I did force the CI to skip, I worked on my own branch in order to have all the static checks passing a second PR, coming atop of that, which was raised a few minutes after this one was merged ... #3496.

In #3496 I fixed all the issues that I could check as part of my own fork, but I didn't count on `s390x` specific issues, and that caused a breakage of almost a full day.

When I noticed such a breakage, well, I did what I could do to fix it.  I've opened an issue to track it (see #3500) and tried to get CI passing ASAP.  By the time I called it a day (late in the night, by the way, as I didn't want to leave things breaking), I had s390x passing on #3496.

So, yes, that's the full background of the breakage and of the skip of the checks.

I hope this explains everything and do not hesitate on asking more questions in case something was not clear.

**Pull request merged**
