### PR TITLE
metrics: fix parsing issue on memory-usage test

### PR DESCRIPTION
**Pull request by dborquez**
This PR fixes an issues in the parsing results stage, by collecting just the n-results from the n-running containers, discarding irrelevant data.

Fixes: #7774

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks @dborquez!

**Comment by GabyCT** [comment]
@dborquez we have the following error
[memory_usage.sh:231] INFO: Creating 20 containers
napping 5 s
tests/metrics/density/memory_usage.sh: line 109: ((: > 0 : syntax error: operand expected (error token is "> 0 ")
[memory_usage.sh:292] ERROR: Failed to find PSS for /usr/local/bin/containerd-shim-kata-qemu-v2

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
