### PR TITLE
CC, kata-deploy: add kata-qemu-sev runtimeclass

### PR DESCRIPTION
**Pull request by Alex-Carter01**
Adds to the configuration of containerd so the correct config is selected.

Fixes: #4851

Signed-Off-By: Alex Carter <alex.carter@ibm.com>

### CODE REVIEW

**Comment by c3d** [comment]
@Alex-Carter01 I think that you need to add the description from #4851 to your commit message to make the CI happy.

**Review by c3d — APPROVED** [review]
Except for the commit message that needs fixing, OK with me.

**Comment by Alex-Carter01** [comment]
Tweaked commit message, hoping this follows the standard. I took another look at the contributing docs.

**Comment by wainersm** [comment]
TDX jobs failing... not good sign

@fidencio mind to look at the logs?

**Review by wainersm — APPROVED** [review]
that was easy @Alex-Carter01 :)

**Comment by fidencio** [comment]
> TDX jobs failing... not good sign
> 
> @fidencio mind to look at the logs?

Looks like a failure setting up k8s, nothing related to this PR.  I restarted the jobs.

**Comment by wainersm** [comment]
apparently networking issues hitting our CI jobs. Let me just re-run them.

/test

**Pull request merged**
