### PR TITLE
osbuilder: Change to "=" operator to make script more portable

### PR DESCRIPTION
**Pull request by Bevisy**
zsh doesn't support "==" as equal comparison operator, so
replace "==" with "=" to make the script more portable

Fixes: #2584

Signed-off-by: Binbin Zhang <binbin36520@gmail.com>

### CODE REVIEW

**Review by c3d — CHANGES_REQUESTED** [review]
Thanks @Bevisy. Could you change the title of the PR. Bash accepts both `=` and `==`, so it is not an error, it's more like a non-posixism that breaks other shells.

**Comment by Bevisy** [comment]
> Thanks @Bevisy. Could you change the title of the PR. Bash accepts both `=` and `==`, so it is not an error, it's more like a non-posixism that breaks other shells.

Thanks for your reminder. It’s indeed because of the difference between zsh and bash. I re-edited the comment and checked other os config.sh scripts to make sure the problem doesn’t occur again.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @Bevisy!

**Review by c3d — CHANGES_REQUESTED** [review]
Sorry, need a minor respin again :-) 

typo: "equal comparsion" should be "equal comparison". Actually, you could reword as "Change to == operator to make script more portable". so that would fit in the 80 chars limit.

(Sorry to be a pain, @Bevisy, the patch itself is approved on my side).

**Comment by Bevisy** [comment]
> Sorry, need a minor respin again :-)
> 
> typo: "equal comparsion" should be "equal comparison". Actually, you could reword as "Change to == operator to make script more portable". so that would fit in the 80 chars limit.
> 
> (Sorry to be a pain, @Bevisy, the patch itself is approved on my side).

This really helped me a lot as I was having a headache on how to add a concise commit message, thanks for the suggestion! :+1:

**Review by c3d — APPROVED** [review]
Thanks a lot @Bevisy. Looking good now. I see you also corrected the error in my comment :-)

**Review by amshinde — APPROVED** [review]

**Comment by Bevisy** [comment]
Jenkins-ci-pmem-Ubuntu-18.04 failed, because downloading go binary failed. Need retest later.

**Comment by GabyCT** [comment]
@Bevisy could you please put if this will require backport or not? thanks

**Comment by Bevisy** [comment]
@GabyCT I think it's no-backport-needed. By the way, what should I do to get jenkins-ci execute permissions and label pr permissions?

**Comment by fidencio** [comment]
> @GabyCT I think it's no-backport-needed. By the way, what should I do to get jenkins-ci execute permissions and label pr permissions?

I'm going to add you to a group that can run the tests.  About the labels, that's something we need to properly think of.

**Pull request merged**
