### PR TITLE
stable-2.4 | Second round of backports for the 2.4.1 release

### PR DESCRIPTION
**Pull request by fidencio**
This round iocludes fixes for the following issues:
* #4196
* #4188

### CODE REVIEW

**Comment by fidencio** [comment]
> /test_kata_deploy

https://github.com/kata-containers/kata-containers/actions/runs/2269321949

**Review by snir911 — APPROVED** [review]
LGTM

**Comment by fidencio** [comment]
@BbolroC, s390x failing: http://jenkins.katacontainers.io/job/kata-containers-2.0-ubuntu-s390x-PR/1624/

**Review by chavafg — APPROVED** [review]

**Comment by fidencio** [comment]
Following https://github.com/kata-containers/ci/issues/470, I'm merging this one without waiting the Ci to get stable again.
Thanks @BbolroC for the quick responses, and the collaboration on this.

**Pull request merged**
