### PR TITLE
[CCv0] Agent configuration file and API restriction

### PR DESCRIPTION
**Pull request by sameo**
This is a port of upstream PR #2517

### CODE REVIEW

**Comment by stevenhorsman** [comment]
Hey @sameo - every week I re-base the `CCv0` branch on `main`, so I think this PR might not be required and we'll hoover it up once the original gets merged?

**Comment by sameo** [comment]
> Hey @sameo - every week I re-base the `CCv0` branch on `main`, so I think this PR might not be required and we'll hoover it up once the original gets merged?

Ah, I did not realize you rebase every week. Let's wait and see if it is merged upstream then.

**Comment by stevenhorsman** [comment]
> Ah, I did not realize you rebase every week. Let's wait and see if it is merged upstream then.

Yes, I think we discussed it whilst you were on vacation, so sorry we didn't catch you up. The aim of it is to try and minimise the divergence from the main branch and make it easier to move changes across there if & when we are ready :)

**Comment by jodh-intel** [comment]
@sameo - Does this sound correct to you?

@stevenhorsman, @sameo  - I get merge conflicts when pulling from `CCv0`...!?! Is this expected?

**Comment by jodh-intel** [comment]
I'm guessing someone accidentally force-pushed to the branch. That option was enabled so I've now disabled forced pushing.

**Comment by stevenhorsman** [comment]
> I'm guessing someone accidentally force-pushed to the branch. That option was enabled so I've now disabled forced pushing.

What was the merge conflict? We're force pushing to the branch as part of the weekly rebase of CCv0 on main

**Comment by jodh-intel** [comment]
@stevenhorsman 

```bash
$ git log --oneline -1|cat
23a17b67 kata-deploy: point to the -cc:v0 image
$ git pull 2>&1|grep CONFLICT
CONFLICT (content): Merge conflict in versions.yaml
CONFLICT (content): Merge conflict in src/agent/src/rpc.rs
CONFLICT (add/add): Merge conflict in docs/how-to/how-to-build-and-test-ccv0.md
CONFLICT (add/add): Merge conflict in docs/how-to/ccv0.sh
```

I'm not sure I'm understanding this - are you force pushing from `main` into `CCv0`? If so, why?

**Comment by stevenhorsman** [comment]
With the `CCv0` branch checked out I'm doing:
`git rebase -i upstream/main`
Then force pushing the rebased branch on the CCv0 remote branch with `git push --force upstream CCv0`
The idea is to minimise the difference between `CCv0` and `main` so that a) we get the new features and fixes from `main` into `CCv0` and so we have as small a set of changes in `CCv0` to merge into `main` to minimise the conflicts for if/when we are ready to put the `CCv0` content into `main`
If you have a better solution to this, that would be great.

**Comment by jodh-intel** [comment]
@stevenhorsman - I'd personally merge from `main` and fixup the conflicts to maintain the history and allow `git pull` to continue to work for those trying to track this work. That's potentially more work I guess, but would help those trying to follow what is going on in the branch rather than having to "start again" every time the branch deviates from its old history. However, if force pushing is the agreed process, and assuming this branch will not be merged into `main`, I guess that's ok for now. We certainly would not allow force pushing to other branches though.

I've re-enabled force push for the `CCv0` branch.

**Review by jodh-intel — APPROVED** [review]
Thanks @sameo.

lgtm, although needs a rebase.

**Comment by jodh-intel** [comment]
Of the 6 open CC PRs, 4 are conflicted, presumably due to the force pushing strategy.

**Comment by stevenhorsman** [comment]
As I said 18 days ago - this code is already in the CCv0 branch, so I think the PR should be closed

**Comment by jodh-intel** [comment]
@stevenhorsman - wfm, but let's get a confirmation from @sameo since he's the author after all.

imho, we need to be a bit more aggressive on these draft CC PRs as -- maybe it's just me? -- it's all extrememly confusing currently.

**Comment by stevenhorsman** [comment]
> imho, we need to be a bit more aggressive on these draft CC PRs as -- maybe it's just me? -- it's all extrememly confusing currently.

Yes, this is a good point. I believe that most of them are still PRs we expect to be merged, but the progress has been slow on a few of them, so maybe they are dead ends now. I think this is something that could be mentioned in the CC call this week? @fitzthum

**Comment by bpradipt** [comment]
> @stevenhorsman - wfm, but let's get a confirmation from @sameo since he's the author after all.
> 
> imho, we need to be a bit more aggressive on these draft CC PRs as -- maybe it's just me? -- it's all extrememly confusing currently.

Agree. Also the force push creates problems for other ongoing PRs and it becomes difficult to apply the changes cleanly for any test.

We can just use a simple priority order based on when the PRs were opened against the ccv0 branch and start merging them. 
This appears to be the first one :-)

**Comment by stevenhorsman** [comment]
> We can just use a simple priority order based on when the PRs were opened against the ccv0 branch and start merging them. This appears to be the first one :-)

Sorry @bpradipt I don't understand your suggestion. We are deliberately not merging the `CCv0` PRs into `main` as it is 'v0', a proof on concept and so most of the code is not suitable to go into main as it doesn't have things like tests created and the interfaces we are using haven't ever been properly defined and agreed. Once we are past the CNCF proposal and are ready to do v1 then we'll need to have a discussion with the wider Kata Containers community about what is acceptable to be supported longer term and then create 'proper' implementations based on that.

**Comment by bpradipt** [comment]
> > We can just use a simple priority order based on when the PRs were opened against the ccv0 branch and start merging them. This appears to be the first one :-)
> 
> Sorry @bpradipt I don't understand your suggestion. We are deliberately not merging the `CCv0` PRs into `main` as it is 'v0', a proof on concept and so most of the code is not suitable to go into main as it doesn't have things like tests created and the interfaces we are using haven't ever been properly defined and agreed. Once we are past the CNCF proposal and are ready to do v1 then we'll need to have a discussion with the wider Kata Containers community about what is acceptable to be supported longer term and then create 'proper' implementations based on that.

@stevenhorsman I'm only talking about merging into CCv0 branch. When force pushing to CCv0, it breaks the inflight PRs, and those need to be rebased. Post rebase if again there is a force push, then the cycle repeats.

**Comment by fidencio** [comment]
@jodh-intel @bpradipt, mea culpa here about how this is currently handled.

When @stevenhorsman approached me asking about a reasonable way to keep this branch up-to-date while doing this work I thought about the (maybe broken?) way I handle my own PRs when working on something upstream.

I work on my local branch, rebase it every week or so against `main`, and force push it so I can keep doing my development, as having a bunch of merges because of the `main` update is not exactly the nicest thing to see.

It seemed like a reasonable idea, at least in the beginning, when not many people were working here (and even less reviewing things here), but it clearly doesn't scale as far as I can see.

So, @jodh-intel, @bpradipt, your suggestion is to do what exactly?
Merge `main` into `CCv0` every Friday?  Don't merge `main` into `CCv0` till the end of the effort?

With the former I think we may still see conflicts happening, mainly on PRs that are not reviewed (and hey, this is a recurring problem that we also face on the `main` branches, where we also see the conflicts happening).  With the latter we may lack behind and it could be quite painful to do the "rebase" atop of main once the effort is over.

In any case, I'd be in favour to switch to whatever you agree on, no problemo.

**Comment by bpradipt** [comment]
> @jodh-intel @bpradipt, mea culpa here about how this is currently handled.
> 
> When @stevenhorsman approached me asking about a reasonable way to keep this branch up-to-date while doing this work I thought about the (maybe broken?) way I handle my own PRs when working on something upstream.
> 
> I work on my local branch, rebase it every week or so against `main`, and force push it so I can keep doing my development, as having a bunch of merges because of the `main` update is not exactly the nicest thing to see.
> 
> It seemed like a reasonable idea, at least in the beginning, when not many people were working here (and even less reviewing things here), but it clearly doesn't scale as far as I can see.
> 
> So, @jodh-intel, @bpradipt, your suggestion is to do what exactly? Merge `main` into `CCv0` every Friday? Don't merge `main` into `CCv0` till the end of the effort?
> 
I like the idea of merging every Friday.

Searching for PRs with `CCv0` label returns 7 PRs, out of which the following are key from functionality standpoint
2956, 2911, 2733, 2658.
So how about we make an attempt to review and merge these PRs to CCv0 before Friday (if possible) and then merge `main` into `CCv0`. 

> With the former I think we may still see conflicts happening, mainly on PRs that are not reviewed (and hey, this is a recurring problem that we also face on the `main` branches, where we also see the conflicts happening). With the latter we may lack behind and it could be quite painful to do the "rebase" atop of main once the effort is over.
> 
> In any case, I'd be in favour to switch to whatever you agree on, no problemo.

**Comment by fidencio** [comment]
> @stevenhorsman - I'd personally merge from `main` and fixup the conflicts to maintain the history and allow `git pull` to continue to work for those trying to track this work. That's potentially more work I guess, but would help those trying to follow what is going on in the branch rather than having to "start again" every time the branch deviates from its old history. However, if force pushing is the agreed process, and assuming this branch will not be merged into `main`, I guess that's ok for now. We certainly would not allow force pushing to other branches though.
> 
> I've re-enabled force push for the `CCv0` branch.

@jodh-intel, first of all, that is on me. :-)

When @stevenhorsman approached me asking what could be a reasonable way to maintain things on the `CCv0` branch in a way that it could be easier to, after the milestone is finished, have a 

> > @jodh-intel @bpradipt, mea culpa here about how this is currently handled.
> > When @stevenhorsman approached me asking about a reasonable way to keep this branch up-to-date while doing this work I thought about the (maybe broken?) way I handle my own PRs when working on something upstream.
> > I work on my local branch, rebase it every week or so against `main`, and force push it so I can keep doing my development, as having a bunch of merges because of the `main` update is not exactly the nicest thing to see.
> > It seemed like a reasonable idea, at least in the beginning, when not many people were working here (and even less reviewing things here), but it clearly doesn't scale as far as I can see.
> > So, @jodh-intel, @bpradipt, your suggestion is to do what exactly? Merge `main` into `CCv0` every Friday? Don't merge `main` into `CCv0` till the end of the effort?
> 
> I like the idea of merging every Friday.
> 
> Searching for PRs with `CCv0` label returns 7 PRs, out of which the following are key from functionality standpoint 2956, 2911, 2733, 2658. So how about we make an attempt to review and merge these PRs to CCv0 before Friday (if possible) and then merge `main` into `CCv0`.

+1 for that, but I'm not officially working on the confidential containers effort (at least not yet).
Would be nice to get an ack from the folks who'll be actively reviewing this, and to be sure that those can be reviewed / closed by the end of this week.

**Comment by stevenhorsman** [comment]
So I'm happy to try out merging main into CCv0 rather than doing a rebase and seeing how straightforward it works out. Just to make sure I understand the proposal is it to do something like:
```
git checkout CCv0 
git fetch upstream
git pull upstream CCv0 
git merge upstream/main
# Fix up merge conflicts
git push upstream CCv0
```
@jodh-intel - is that what you were imagining, or have I got something wrong :) ?

**Comment by jodh-intel** [comment]
@fidencio - np. Yes, the force push methodology is fine for an isolated branch like a personal dev branch (or of course for unmerged PR branches), but it falls down when that branch has multiple consumers because the history they already have locally becomes incorrect after the force push.

@stevenhorsman - yes, that's what I was thinking of. The merge fixup could be painful but tbh, I think that's the price we have to pay to remain close to `main`.  A weekly sync sounds fine with me and an excellent idea to minimise the delta between the two branches. Ironically, a more frequent (daily?) merge might make it less painful overall, but then there is the cost of doing more regular merges.

wdyt @sameo, @wllenyj?

**Comment by stevenhorsman** [comment]
@jodh-intel - thanks for your advice and patience. I'll start with this process from Friday and see how it goes with the merging. 🤞 it is not too painful!

**Comment by wllenyj** [comment]
The patch of the main branch can be merged to CCv0 instead of rebase.

**Comment by jodh-intel** [comment]
Thanks @wllenyj, @stevenhorsman - sounds good to me, and good luck! :smile: :crossed_fingers:

**Comment by sameo** [comment]
Closing as this is coming from upstream.

**Pull request closed without merging**
