### PR TITLE
runtime: fix and refactor Makefile for build and install target

### PR DESCRIPTION
**Pull request by zhsj**
1. The old build & default target are empty. To fix it, the all
   target is renamed to build, since the all target is not mentioned
   in help.
2. Refactor various install targets to have a clear dependency.
3. Fix default PKGLIBEXECDIR which doesn't honor default /usr/local prefix

Fixes: #1861

### CODE REVIEW

**Comment by fidencio** [comment]
@zhsj, please, take a look at the CI failures.
Taking a look at a random one here, I see:
```
cp: cannot stat '//usr/share/defaults/kata-containers/configuration-qemu.toml': No such file or directory
Failed at 79: sudo cp -a "$path" "${PKGDEFAULTSDIR}/configuration.toml"
Failed at 38: "${cidir}/install_runtime.sh" "${tag}"
```

So, either we need to adjust CI or this series needs to be adjusted to ensure we don't regress considering the "old" behaviour

**Comment by fidencio** [comment]
@zhsj, may I bother you to have this one rebased atop of current `main`?

**Comment by liubin** [comment]
@zhsj Do you have any updates?

**Comment by zhsj** [comment]
Sorry I don't have time to take it. Maybe we can close it now?

**Comment by liubin** [comment]
> Sorry I don't have time to take it. Maybe we can close it now?

Indeed the `default` target issue has been fixed by other PRs, I think this one can be closed.

If you have time and other things to be fixed, you can crate another new one.

**Pull request closed without merging**
