### PR TITLE
stable-3.2: Backport everything related to the tests

### PR DESCRIPTION
**Pull request by fidencio**
Yep, I know, this is a huge PR, but here we're bringing everything related to the tests to this branch.

### CODE REVIEW

**Comment by fidencio** [comment]
This will be a nightmare to review, but I've brought it all the tests changes that we've done on main.

Is this really needed? Do github actions are triggered based on the `main`  branch of the project or are they trigerred based on the content of each branch?

Also, this cannot be easily tested before getting merged, and only after the merge is done I will backport PRs that I know for sure that are related to the CI (or that will fix things related to the CI), but those deserve a better review than just be thrown as part of this huge basket here.

**Comment by ldoktor** [comment]
Hello @fidencio, I'm new to this project so I went through all of the commits mainly to get some history wrt testing. I can't say I understand all the changes and I have to say many of the commit messages are not helpful, but this is a cherry-pick and all commits contain the references to the main ones. On top I tried comparing main vs. this PR (using meld), focusing on the files touched inside of this PR, there are a few differences here and there but overall I haven't found anything important.

I'm looking forward for the results if you manage to get this working on your repo, otherwise I think it should be good to go. Worst case it can be hot-fixed or reverted in case it becomes too cumbersome to fix.

**Comment by fidencio** [comment]
We all know this PR would be very hard to properly review, so I've pushed everything here to the https://github.com/kata-containers/kata-containers/tree/stable-3.2-test branch, and I opened a PR (https://github.com/kata-containers/kata-containers/pull/8146) to test that the tests are "running".

Fixes for the tests will come as backports, which I really would not like to get mixed into this bucket.

In order to see that the tests were actually running, please, take a look at: https://github.com/kata-containers/kata-containers/actions/runs/6480062851

We'll merge this PR without running any other tests as running tests is not useful ata this point, for this PR.

**Comment by fidencio** [comment]
I'd need an approval from 2 maintainers, and at least 1 approval from a member of the AC in order to proceed with this with some peace of mind from my side.

**Review by gkurz — APPROVED** [review]
Based on https://github.com/kata-containers/kata-containers/actions/runs/6480062851 that is showing all tests running indeed, I'm approving this PR. Thanks for the colossal work @fidencio !

**Review by stevenhorsman — APPROVED** [review]
I've reviewed all the files changed (the file names, not content) and look to all be either tests related, packaging related to get the tests passing, or changes that have been packages with test updates e.g. https://github.com/kata-containers/kata-containers/pull/7704

I've also checked and every commit has been cherry-picked, except https://github.com/kata-containers/kata-containers/pull/8022/commits/bb1efe0d461d61a63204a6c63e7786c684d2cedf which looks fine, so based on that I think this is low risk code and I'm happy to unblock it.

**Comment by fidencio** [comment]
So, let me hold this one a little bit, because now I'm very puzzled about the GHA behaviour.

**Comment by fidencio** [comment]
> So, let me hold this one a little bit, because now I'm very puzzled about the GHA behaviour.

Nevermind, it's good as it's. :-)

**Comment by fidencio** [comment]
I'm merging this one right now.

**Pull request merged**
