### PR TITLE
CC: tdx: Stick to the 2022ww44 TDX stack for the CCv0 branch

### PR DESCRIPTION
**Pull request by fidencio**
As the Jenkins TDX CI is running on a system with a TDX stack called
"2022ww44", we should keep the QEMU / kernel / OVMF versions matching
what's provided in that stack.

The reason we were able to update this on `main` is because the GHA TDX
CI is running on a TDX stack called "2023ww01", but we have decided to
NOT take the bullet, NOT updating the Jenkins CI in order to avoid
unexepected breakages.

This regression was introduced as part of the last CCv0 merge to main,
and would've been caught by the CI, and should've been caught by the
reviewer (myself :-)), but CI was having a hard time to even build the
compoenents and I wrote in the PR and I'm quoting it here: "I rather
deal with possible breakages on this later on, than block this PR to get
in." ... and here we are. :-)

Fixes: #6884

### CODE REVIEW

**Review by GabyCT — APPROVED** [review]

**Comment by fidencio** [comment]
TDX machine is having a really hard time with network.
I did a `make cc-tdx-kernel-tarball`, `make cc-tdx-qemu-tarball`, and `make cc-tdx-tdvf-tarball` locally, and I could get the artefacts properly built.

I'd propose to get this one merged, get the cache of those artefacts running, and that will help our situation a little bit.

**Review by stevenhorsman — APPROVED** [review]
Reverting these changes makes sense base don the description

**Pull request merged**
