### PR TITLE
dependency: update cgroups-rs

### PR DESCRIPTION
**Pull request by gkurz**
Huge pages failure with cgroups v2.
https://github.com/kata-containers/cgroups-rs/issues/112

Fixes: #6470

(cherry picked from commit a8b55bf8746d48e1793e5a95ea59ebe9ca3224d8)

### CODE REVIEW

**Review by snir911 — APPROVED** [review]
LGTM, thanks

**Review by fidencio — APPROVED** [review]
lgtm, thanks @gkurz and @etrunko!

**Pull request merged**
