### PR TITLE
kata-deploy: Fix `test-kata.sh` and do some small cleanups / improvements in the kata-deploy script

### PR DESCRIPTION
**Pull request by fidencio**
On commit 60f6315 we've started adding the specific version of the image
to be used, in order to ensure people using our content from a tarball
would be relying on the correct image.

However, later on, @bergwolf figured out it had some undesired side
effects, such as
https://github.com/kata-containers/kata-containers/runs/2235812941?check_suite_focus=true

What happens there is that the regular expression used to point the
image to a testing one doesn't take into consideration the $VERSION, and
that breaks the deployment.

Fixes: #1632

### CODE REVIEW

**Comment by fidencio** [comment]
test-kata-deploy

**Review by GabyCT — APPROVED** [review]

**Comment by fidencio** [comment]
Would this trigger the test-kata-deploy?

**Comment by fidencio** [comment]
/"test-kata-deploy"

**Comment by fidencio** [comment]
Victory, we can successfully trigger the action using `/test_kata_deploy`
https://github.com/kata-containers/kata-containers/runs/2288772826?check_suite_focus=true

**Review by wainersm — APPROVED** [review]
Those changes LGTM.

**Pull request merged**
